### ISSUE TITLE
Sources with `MATERIALIZE` envelope (CDCv2) panic if the stream doesn't uphold its properties

### ISSUE THREAD

**Issue by petrosagg** [MaterializeInc/materialize#10406]
### What version of Materialize are you using?

latest main

### How did you install Materialize?

Built from source

### What was the issue?

Currently we consume CDCv2 sources (aka `ENVELOPE MATERIALIZE`) by using the [`capture::source`](https://docs.rs/differential-dataflow/latest/differential_dataflow/capture/index.html) mechanism from differential dataflow. The definition of a well-formed CDCv2 stream is that every pair of `(data, time)` must be associated uniquely with a diff that is final. If a CDCv2 stream ever includes two messages for the same `(data, time)` but with different values in the diff the result is undefined.

The code in differential dataflow currently has defensive checks for that and asserts when the invariant is violated. This isn't great in the setting of materialized as this can bring the whole database down if a single source is misbehaved.

We should somehow catch the error and surface it to the user, either by validating the data before passing them to DD's implementation, of by altering DD's implementation to emit Results in case of errors.

This issue was uncovered by this test failure: https://buildkite.com/materialize/nightlies/builds/614#c60e4559-ba07-42f9-b404-f456f46cc73f

### Relevant log output

This is the stacktrace when the assertion fires:

```source
materialized_1     | 2022-02-01T12:34:48.581320Z  INFO coord::catalog: create sink materialize.public.nums_sink (u158)
materialized_1     | 2022-02-01T12:34:50.916743Z ERROR panic: assertion failed: `(left == right)`
materialized_1     |   left: `1`,
materialized_1     |  right: `-1`
materialized_1     | thread: timely:work-0
materialized_1     | location: /cargo/git/checkouts/differential-dataflow-d065d23d797aa027/19808dc/src/capture.rs:440:33
materialized_1     | version: 0.19.1-dev (f1b4f3b7bc2bd0a8c4f8f4ffb5ddef125519689a)
materialized_1     | backtrace:
materialized_1     |    0: materialized::handle_panic
materialized_1     |              at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d4ef45930efb2807-1/materialize/tests/src/materialized/src/bin/materialized/main.rs:868:21
materialized_1     |    1: core::ops::function::Fn::call
materialized_1     |              at rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/ops/function.rs:70:5
materialized_1     |    2: std::panicking::rust_panic_with_hook
materialized_1     |              at rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:610:17
materialized_1     |    3: std::panicking::begin_panic_handler::{{closure}}
materialized_1     |              at rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:502:13
materialized_1     |    4: std::sys_common::backtrace::__rust_end_short_backtrace
materialized_1     |              at rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/sys_common/backtrace.rs:139:18
materialized_1     |    5: rust_begin_unwind
materialized_1     |              at rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:498:5
materialized_1     |    6: core::panicking::panic_fmt
materialized_1     |              at rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/panicking.rs:107:14
materialized_1     |    7: core::panicking::assert_failed_inner
materialized_1     |    8: core::panicking::assert_failed
materialized_1     |              at rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/panicking.rs:145:5
materialized_1     |    9: differential_dataflow::capture::source::build::{{closure}}::{{closure}}
materialized_1     |              at cargo/git/checkouts/differential-dataflow-d065d23d797aa027/19808dc/src/capture.rs:440:33
materialized_1     |       timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}
materialized_1     |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f09f66/timely/src/dataflow/operators/generic/builder_rc.rs:124:31
materialized_1     |       timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
materialized_1     |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f09f66/timely/src/dataflow/operators/generic/builder_rc.rs:163:26
materialized_1     |       <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
materialized_1     |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f09f66/timely/src/dataflow/operators/generic/builder_raw.rs:205:9
materialized_1     |   10: timely::progress::subgraph::PerOperatorState<T>::schedule
materialized_1     |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f09f66/timely/src/progress/subgraph.rs:684:30
materialized_1     |   11: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
materialized_1     |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f09f66/timely/src/progress/subgraph.rs:344:26
materialized_1     |       <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
materialized_1     |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f09f66/timely/src/progress/subgraph.rs:310:17
materialized_1     |   12: timely::progress::subgraph::PerOperatorState<T>::schedule
materialized_1     |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f09f66/timely/src/progress/subgraph.rs:684:30
materialized_1     |   13: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
materialized_1     |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f09f66/timely/src/progress/subgraph.rs:344:26
materialized_1     |       <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
materialized_1     |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f09f66/timely/src/progress/subgraph.rs:310:17
materialized_1     |   14: timely::worker::Wrapper::step::{{closure}}
materialized_1     |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f09f66/timely/src/worker.rs:749:57
materialized_1     |       core::option::Option<T>::map
materialized_1     |              at rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/option.rs:846:29
materialized_1     |       timely::worker::Wrapper::step
materialized_1     |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f09f66/timely/src/worker.rs:749:26
materialized_1     |   15: timely::worker::Worker<A>::step_or_park
materialized_1     |              at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f09f66/timely/src/worker.rs:396:38
materialized_1     |   16: dataflow::server::Worker<A>::run
materialized_1     |              at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d4ef45930efb2807-1/materialize/tests/src/dataflow/src/server.rs:473:13
materialized_1     |   17: dataflow::server::serve::{{closure}}
```

**Comment by philip-stoev** [comment]
Reproduction test case:

```
> CREATE CONNECTION kafka_conn
  TO KAFKA (BROKER '${testdrive.kafka-addr}');

> CREATE CONNECTION IF NOT EXISTS csr_conn TO CONFLUENT SCHEMA REGISTRY (
    URL '${testdrive.schema-registry-url}'
  );

$ set schema=[
  {
    "type": "array",
    "items": {
      "type": "record",
      "name": "update",
      "namespace": "com.materialize.cdc",
      "fields": [
        {
          "name": "data",
          "type": {
            "type": "record",
            "name": "data",
            "fields": [
              {"name": "a", "type": "long"},
              {"name": "b", "type": "long"}
            ]
          }
        },
        {
          "name": "time",
          "type": "long"
        },
        {
          "name": "diff",
          "type": "long"
        }
      ]
    }
  },
  {
    "type": "record",
    "name": "progress",
    "namespace": "com.materialize.cdc",
    "fields": [
      {
        "name": "lower",
        "type": {
          "type": "array",
          "items": "long"
        }
      },
      {
        "name": "upper",
        "type": {
          "type": "array",
          "items": "long"
        }
      },
      {
        "name": "counts",
        "type": {
          "type": "array",
          "items": {
            "type": "record",
            "name": "counts",
            "fields": [
              {
                "name": "time",
                "type": "long"
              },
              {
                "name": "count",
                "type": "long"
              }
            ]
          }
        }
      }
    ]
  }
  ]


#
# Insert and delete at the same timestamp
#

$ kafka-create-topic topic=topic1
> CREATE SOURCE source1
  FROM KAFKA CONNECTION kafka_conn (TOPIC 'testdrive-topic1-${testdrive.seed}')
  FORMAT AVRO USING SCHEMA '${schema}' ENVELOPE MATERIALIZE
> CREATE SINK sink1 FROM source1
  INTO KAFKA CONNECTION kafka_conn (TOPIC 'testdrive-sink1-${testdrive.seed}') KEY (a) NOT ENFORCED
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY CONNECTION csr_conn ENVELOPE UPSERT

$ kafka-ingest format=avro topic=topic1 schema=${schema}
{"array":[{"data":{"a":1,"b":1},"time":1,"diff":1}]}
{"array":[{"data":{"a":1,"b":1},"time":1,"diff":-1}]}
{"array":[{"data":{"a":2,"b":2},"time":1,"diff":1}]}
{"array":[{"data":{"a":2,"b":2},"time":2,"diff":-1}]}
{"array":[{"data":{"a":3,"b":3},"time":3,"diff":1}]}
{"com.materialize.cdc.progress":{"lower":[0],"upper":[10],"counts":[{"time":1,"count":2}, {"time":2,"count":2}]}}
```

**Comment by philip-stoev** [comment]
Also,

```
thread 'timely:work-0' panicked at 'primary key error: expected at most one update per key and timestamp This can happen when the configured sink key is not a primary key of the sinked relation: sink u32 created from u31.', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-05e1c442f0306d0e4-1/materialize/tests/src/ore/src/collections.rs:67:18
```
This panic even has debugging information for the user ... too bad they will never be able to see it.

**Comment by benesch** [comment]
Closing as stale, as we no longer support CDCv2.
