### ISSUE TITLE
persistence: panic: failed to set up alternative stack guard page: Cannot allocate memory (os error 12) during recovery

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#10425]
### What version of Materialize are you using?

fc2a514628024a03e52bbd631849c82015516728

### How did you install Materialize?

Built from source

### What was the issue?

Attempting to restart from a mzdata directory containing 290K UUID-named files results in a crash:

```
2022-02-03T10:40:43.237361Z ERROR panic: failed to set up alternative stack guard page: Cannot allocate memory (os error 12)
thread: <unnamed>
location: library/std/src/sys/unix/stack_overflow.rs:160:13
version: 0.19.1-dev (905164aeda1c84921717173317b1dd4a86dbcfc1)
```

There is some evidence that this is because of too many threads spawned by `persist::indexed::cache::BlobCache<B>::get_trace_batch_async`

Setting up a breakpoint on the OS `clone()` call reveals repeated creations of new threads with this stack trace:

```
Thread 18 "persist:runtime" hit Breakpoint 1, clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:50
50	in ../sysdeps/unix/sysv/linux/x86_64/clone.S
(gdb) bt
#0  clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:50
#1  0x00007ffff7fa42ec in create_thread (pd=pd@entry=0x7fffc97ff700, attr=attr@entry=0x7fffe26786a0, stopped_start=stopped_start@entry=0x7fffe26785de, stackaddr=stackaddr@entry=0x7fffc97f9f40, 
    thread_ran=thread_ran@entry=0x7fffe26785df) at ../sysdeps/unix/sysv/linux/createthread.c:101
#2  0x00007ffff7fa5e10 in __pthread_create_2_1 (newthread=<optimized out>, attr=<optimized out>, start_routine=<optimized out>, arg=<optimized out>) at pthread_create.c:817
#3  0x00005555599c3185 in std::sys::unix::thread::Thread::new () at library/std/src/sys/unix/thread.rs:85
#4  0x0000555556cca0f1 in persist::indexed::cache::BlobCache<B>::get_trace_batch_async ()
#5  0x0000555556b28de5 in persist::indexed::arrangement::Arrangement::snapshot ()
#6  0x000055555696ad39 in persist::indexed::AppliedState::do_snapshot ()
#7  0x000055555697a533 in persist::indexed::Indexed<L,B>::apply ()
#8  0x0000555556cd1965 in persist::runtime::RuntimeImpl<L,B>::work ()
#9  0x0000555556928a18 in std::sys_common::backtrace::__rust_begin_short_backtrace ()
#10 0x0000555556c8fdb7 in core::ops::function::FnOnce::call_once{{vtable-shim}} ()
#11 0x00005555599c3303 in <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/alloc/src/boxed.rs:1694
#12 <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/alloc/src/boxed.rs:1694
#13 std::sys::unix::thread::Thread::new::thread_start () at library/std/src/sys/unix/thread.rs:106
#14 0x00007ffff7fa5609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#15 0x00007ffff7b5c293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) continue
```

Running the binary in gdb reports that threads exit regularily, but running it with native speed causes threads to accumulate .

One can also see this with strace:
```
strace -f -F target/release/materialized --persistent-kafka-upsert-source --experimental --data-directory /home/pstoev/persist-crash/mzdata/  2>&1
```

Let this run for a while and then hit Ctrl+C. You will see a bunch of `Process detached` messages.

### Relevant log output

```source
2022-02-03T11:01:48.672046Z ERROR panic: failed to set up alternative stack guard page: Cannot allocate memory (os error 12)
thread: <unnamed>
location: library/std/src/sys/unix/stack_overflow.rs:160:13
version: 0.19.1-dev (fc2a514628024a03e52bbd631849c82015516728)
backtrace:
   0: materialized::handle_panic
   1: core::ops::function::Fn::call
   2: std::panicking::rust_panic_with_hook
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:610:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:502:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:139:18
   5: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   6: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   7: std::sys::unix::stack_overflow::imp::get_stackp
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys/unix/stack_overflow.rs:160:13
      std::sys::unix::stack_overflow::imp::get_stack
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys/unix/stack_overflow.rs:166:32
      std::sys::unix::stack_overflow::imp::make_handler
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys/unix/stack_overflow.rs:177:21
   8: std::sys::unix::stack_overflow::Handler::new
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys/unix/stack_overflow.rs:14:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys/unix/thread.rs:104:32
   9: start_thread
             at /build/glibc-eX1tMB/glibc-2.31/nptl/pthread_create.c:477:8
  10: clone

materialized encountered an internal error and crashed.

We rely on bug reports to diagnose and fix these errors. Please
copy and paste the above details and file a report at:

    https://materialize.com/s/bug
```

**Comment by philip-stoev** [comment]
I have a 128Mb zipped mzcompose directory that reproduces this, but I can not uploaded it to GitHub

**Comment by aljoscha** [comment]
Closing this because current persist/storage architecture has moved quite a bit beyond this.

@philip-stoev Please yell at me if you'd like to keep this open.

fyi @danhhz
