### ISSUE TITLE
Coordinator crashes on restart with reconcilation turned on

### ISSUE THREAD

**Issue by lluki** [MaterializeInc/materialize#11569]
### What version of Materialize are you using?

5f6549570

### How did you install Materialize?

Built from source

### What was the issue?

I am testing the command reconciliation using the following steps (as describe in this [comment](https://github.com/MaterializeInc/materialize/pull/11103#issuecomment-1077769109) ). I did a  `rm -rf mzdata` first.

> Instruction on how to run this:
> 
>     1. Build: `cargo build --bin materialized --bin dataflowd --release`
> 
>     2. Run storage: `DATAFLOWD_LOG_FILTER=debug RUST_BACKTRACE=1 cargo run --release --bin dataflowd -- --runtime=storage --listen-addr=localhost:6876 --storage-addr=localhost:6700 --reconcile --linger`
> 
>     3. Run compute: `DATAFLOWD_LOG_FILTER=trace cargo run --release --bin dataflowd -- --runtime=compute --listen-addr=localhost:6877 --storage-addr=localhost:6700 --storage-workers=1 --reconcile --linger`
> 
>     4. Run Mz: `cargo run --release --bin materialized -- -w1 --experimental --storage-compute-addr=localhost:6700 --storage-controller-addr=localhost:6876 --storage-workers=1`
> 
>     5. Ctrl+C Mz, restart, everything should work again. Well, should...

The first start works fine, but after killing materialized and restarting it, materialized and compute immediately crash.

@antiguru  certainly has opinions on this.

### Relevant log output
Output of the three processes:
[compute.txt](https://github.com/MaterializeInc/materialize/files/8408156/compute.txt)
[mz.txt](https://github.com/MaterializeInc/materialize/files/8408157/mz.txt)
[storage.txt](https://github.com/MaterializeInc/materialize/files/8408158/storage.txt)

**Comment by philip-stoev** [comment]
From the attachements:
```
thread 'main' panicked at 'Protocol error: starting frontier tracking for already present identifier System(3000) due to command CreateSources([CreateSourceCommand { id: System(3000), desc: SourceDesc { connector: Local { timeline: EpochMilliseconds, persisted_name: None }, desc: RelationDesc { typ: RelationType { column_types: [ColumnType { scalar_type: Int64, nullable: false }, ColumnType { scalar_type: Int64, nullable: false }, ColumnType { scalar_type: String, nullable: false }], keys: [[0, 1]] }, names: [ColumnName("id"), ColumnName("worker"), ColumnName("name")] } }, since: Antichain { elements: [0] }, ts_bindings: [] }])', /home/lukas/mat/materialize/src/dataflow-types/src/client/partitioned.rs:178:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: <mz_dataflow_types::client::partitioned::PartitionedStorageState<T> as mz_dataflow_types::client::partitioned::PartitionedState<mz_dataflow_types::client::StorageCommand<T>,mz_dataflow_types::client::StorageResponse<T>>>::split_command
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: dataflowd::run::{{closure}}
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: tokio::park::thread::CachedParkThread::block_on
  10: tokio::runtime::thread_pool::ThreadPool::block_on
  11: tokio::runtime::Runtime::block_on
  12: dataflowd::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

```
materialized v0.25.1-dev (5f6549570) listening on 127.0.0.1:6875...
2022-04-04T08:43:48.044295Z ERROR panic: called `Result::unwrap()` on an `Err` value: Connection severed; reconnected
thread: coordinator
location: /home/lukas/mat/materialize/src/coord/src/coord.rs:712:29
version: 0.25.1-dev (5f6549570720a56222cee1d9b179d898a4252099)
backtrace:
   0: materialized::handle_panic
   1: core::ops::function::Fn::call
   2: std::panicking::rust_panic_with_hook
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:610:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:502:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
   5: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   6: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   7: core::result::unwrap_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
   8: mz_coord::coord::Coordinator::serve::{{closure}}
   9: tokio::runtime::enter::Enter::block_on
  10: tokio::runtime::handle::Handle::block_on
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/boxed.rs:1854:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/boxed.rs:1854:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys/unix/thread.rs:108:17
  14: start_thread
             at ./nptl/./nptl/pthread_create.c:435:8
  15: __GI___clone
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:100
```

Having the stack traces as comments or in the body of the ticket makes them searchable in the GH interface so that duplicate issues are not filed.

**Comment by antiguru** [comment]
This is working as designed. Storage doesn't have the equivalent of a command reconciliation, which means that it either crashes on `materialized` disappearing, or arrives in an invalid state.
