### ISSUE TITLE
computed: table inserts fail across the board if one cluster has gone down

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#12251]
### What version of Materialize are you using?

v0.26.1-dev (aa0c81852)

### How did you install Materialize?

Docker image

### What was the issue?

If one cluster has panicked , INSERT statements will hang .

**Comment by philip-stoev** [comment]
@frankmcsherry yes I figured so ... should I just send the ticket to STORAGE?

The only thing that bothers me is that the panic as currently forced happens on the `SELECT` side of the `INSERT` statement. That is, why would storage be wedged by something that should happen before any stuff is actually stored?

**Comment by frankmcsherry** [comment]
Somewhere between ADAPTER and STORAGE we have to evaluate that expression. I'm not sure where that happens, but tbh I'd guess that you wedged ADAPTER somehow. At least, I think STORAGE only accepts fully formed rows, rather than expressions to evaluate.

**Comment by philip-stoev** [comment]
The default cluster is crash looping:

```
2022-05-06T13:35:28.076462Z  INFO computed: coordinator connection accepted
thread 'timely:work-0' panicked at 'panic!', src/expr/src/scalar/func/impls/string.rs:717:9
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::panic_display
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:73:5
   3: mz_expr::scalar::func::impls::string::panic
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c9e9464c59af60b0-1/materialize/tests/src/expr/src/scalar/func/impls/string.rs:717:9
   4: <mz_expr::scalar::func::impls::string::Panic as mz_expr::scalar::func::EagerUnaryFunc>::call
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c9e9464c59af60b0-1/materialize/tests/src/expr/src/scalar/func/macros.rs:78:31
   5: <T as mz_expr::scalar::func::LazyUnaryFunc>::eval
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c9e9464c59af60b0-1/materialize/tests/src/expr/src/scalar/func.rs:3200:26
   6: mz_expr::scalar::func::UnaryFunc::eval
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c9e9464c59af60b0-1/materialize/tests/src/expr/src/scalar/func/macros.rs:258:41
   7: mz_expr::scalar::MirScalarExpr::eval
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c9e9464c59af60b0-1/materialize/tests/src/expr/src/scalar/mod.rs:1153:56
   8: mz_expr::linear::plan::SafeMfpPlan::evaluate_inner
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c9e9464c59af60b0-1/materialize/tests/src/expr/src/linear.rs:1429:29
   9: mz_expr::linear::plan::MfpPlan::evaluate
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c9e9464c59af60b0-1/materialize/tests/src/expr/src/linear.rs:1660:19
  10: mz_compute::render::context::CollectionBundle<S,mz_repr::row::Row,T>::as_collection_core::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c9e9464c59af60b0-1/materialize/tests/src/compute/src/render/context.rs:533:17
  11: mz_compute::render::context::CollectionBundle<S,mz_repr::row::Row,T>::flat_map::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c9e9464c59af60b0-1/materialize/tests/src/compute/src/render/context.rs:395:52
  12: <timely::dataflow::stream::StreamCore<S,alloc::vec::Vec<D>> as timely::dataflow::operators::map::Map<S,D>>::flat_map::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/dataflow/operators/map.rs:79:83
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:280:13
  14: core::option::Option<T>::map
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/option.rs:906:29
  15: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/iter/adapters/map.rs:103:9
  16: <core::iter::adapters::fuse::Fuse<I> as core::iter::adapters::fuse::FuseImpl<I>>::next
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/iter/adapters/fuse.rs:365:9
  17: <core::iter::adapters::fuse::Fuse<I> as core::iter::traits::iterator::Iterator>::next
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/iter/adapters/fuse.rs:70:9
  18: <core::iter::adapters::flatten::FlattenCompat<I,U> as core::iter::traits::iterator::Iterator>::next
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/iter/adapters/flatten.rs:299:19
  19: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/iter/adapters/flatten.rs:51:9
  20: timely::dataflow::channels::pushers::buffer::Session<T,alloc::vec::Vec<D>,P>::give_iterator
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/dataflow/channels/pushers/buffer.rs:132:21
  21: <timely::dataflow::stream::StreamCore<S,alloc::vec::Vec<D>> as timely::dataflow::operators::map::Map<S,D>>::flat_map::{{closure}}::{{closure}}::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/dataflow/operators/map.rs:79:17
  22: timely::dataflow::operators::generic::handles::InputHandleCore<T,D,P>::for_each
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/dataflow/operators/generic/handles.rs:97:13
  23: <timely::dataflow::stream::StreamCore<S,alloc::vec::Vec<D>> as timely::dataflow::operators::map::Map<S,D>>::flat_map::{{closure}}::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/dataflow/operators/map.rs:77:13
  24: <timely::dataflow::stream::StreamCore<G,D1> as timely::dataflow::operators::generic::operator::Operator<G,D1>>::unary::{{closure}}::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/dataflow/operators/generic/operator.rs:401:17
  25: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/dataflow/operators/generic/builder_rc.rs:123:31
  26: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/dataflow/operators/generic/builder_rc.rs:162:26
  27: <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/dataflow/operators/generic/builder_raw.rs:204:9
  28: timely::progress::subgraph::PerOperatorState<T>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/progress/subgraph.rs:684:30
  29: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/progress/subgraph.rs:344:26
  30: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/progress/subgraph.rs:310:17
  31: timely::progress::subgraph::PerOperatorState<T>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/progress/subgraph.rs:684:30
  32: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/progress/subgraph.rs:344:26
  33: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/progress/subgraph.rs:310:17
  34: timely::worker::Wrapper::step::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/worker.rs:754:57
  35: core::option::Option<T>::map
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/option.rs:906:29
  36: timely::worker::Wrapper::step
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/worker.rs:754:26
  37: timely::worker::Worker<A>::step_or_park
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/worker.rs:396:38
  38: mz_compute::server::Worker<A,CR>::run
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c9e9464c59af60b0-1/materialize/tests/src/compute/src/server.rs:166:13
  39: mz_compute::server::serve_boundary::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c9e9464c59af60b0-1/materialize/tests/src/compute/src/server.rs:102:9
  40: timely::execute::execute::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/timely/src/execute.rs:287:22
  41: timely_communication::initialize::initialize_from::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/communication/src/initialize.rs:316:33
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
panic!2022-05-06T13:35:28.954862Z  INFO computed: coordinator connection gone; terminating
2022-05-06T13:35:28.954879Z ERROR mz_dataflow_types::client::tcp: connection unexpectedly terminated cleanly
2022-05-06T13:35:28.955198Z  INFO mz_dataflow_types::client::tcp: Reconnected to localhost:2102
thread 'main' panicked at 'Worker panic: Any { .. }', /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/communication/src/initialize.rs:354:26
stack backtrace:
2022-05-06T13:35:28.955263Z  WARN mz_dataflow_types::client::replicated: Rehydrating replica "default"
   0: rust_begin_unwind
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
   3: core::result::Result<T,E>::expect
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1022:23
   4: <timely_communication::initialize::WorkerGuards<T> as core::ops::drop::Drop>::drop
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/7ad8962/communication/src/initialize.rs:354:13
   5: core::ptr::drop_in_place<timely_communication::initialize::WorkerGuards<()>>
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ptr/mod.rs:188:1
   6: core::ptr::drop_in_place<mz_compute::server::Server>
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ptr/mod.rs:188:1
   7: computed::serve::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c9e9464c59af60b0-1/materialize/tests/src/compute/src/bin/computed.rs:285:1
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
   9: computed::run::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c9e9464c59af60b0-1/materialize/tests/src/compute/src/bin/computed.rs:268:40
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  11: computed::main::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c9e9464c59af60b0-1/materialize/tests/src/compute/src/bin/computed.rs:115:53
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  13: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:54
  14: tokio::coop::with_budget::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
  15: std::thread::local::LocalKey<T>::try_with
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:413:16
  16: std::thread::local::LocalKey<T>::with
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:389:9
  17: tokio::coop::with_budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
  18: tokio::coop::budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
  19: tokio::park::thread::CachedParkThread::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:31
  20: tokio::runtime::enter::Enter::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/enter.rs:151:13
  21: tokio::runtime::thread_pool::ThreadPool::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/mod.rs:73:9
  22: tokio::runtime::Runtime::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/mod.rs:477:43
  23: computed::main
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c9e9464c59af60b0-1/materialize/tests/src/compute/src/bin/computed.rs:115:5
  24: core::ops::function::FnOnce::call_once
             at ./rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by frankmcsherry** [comment]
If you use `--log-filter trace` you can observe the commands that are flowing to the compute instances, which would be helpful!

**Comment by philip-stoev** [comment]
The part where the `SELECT` from the `INSERT ... SELECT` is being processed by the default cluster and not by the cluster specified with `SET` is now #12294 . This ticket is about the inability to perform any further inserts once this happens.

**Comment by frankmcsherry** [comment]
Ah, I'm now reading this more carefully, and I have realized I have no idea what 
```
INSERT INTO log_table SELECT mz_internal.mz_panic(f1) FROM panic_table;
```
does. Again probably best to take it up with ADAPTER, as it is not a primitive COMPUTE command. ADAPTER is asking COMPUTE for something, probably the result of a panic, and .. probably e.g. not canceling it / responding cleanly to failure. For example, if that INSERT hasn't resolved, perhaps we can't do more INSERTs because of serializability. Strongly recommend looping ADAPTER folks in here (ping @mjibson).

**Comment by philip-stoev** [comment]
[gh12251.log.zip](https://github.com/MaterializeInc/materialize/files/8641244/gh12251.log.zip)
This is the `--log-filter trace` log from the main materialized container, that is, the container that also runs the default compute instance and the storaged.

**Comment by jkosh44** [comment]
I took a look at this and the reason for the second `INSERT` hanging is due to lock contention.

`INSERT INTO SELECT`s require a write lock to be taken in the coordinator:
https://github.com/MaterializeInc/materialize/blob/21d7fde1cee7192df353e1879c7b9c1922864bde/src/coord/src/coord.rs#L3990-L4000
So `INSERT INTO log_table SELECT mz_internal.mz_panic(f1) FROM panic_table;` takes a write lock and never releases it because it can never complete successfully. 

Write commits also require a write lock to be taken in the coordinator:
https://github.com/MaterializeInc/materialize/blob/21d7fde1cee7192df353e1879c7b9c1922864bde/src/coord/src/coord.rs#L2794-L2812
So the `INSERT INTO t2 VALUES ( 0 ) ;` is waiting for the write lock that is never released.

`mz_panic` is not something that we expect to ever be called in production, but we would experience similar behavior if someone executed an `INSERT INTO SELECT` and the select tried to read from a slow/unresponsive/crashed COMPUTE node. All other `INSERT`s would be blocked by that one statement, until it completed. 

So if we believe that the COMPUTE node will become healthy and eventually succesfully complete the `INSERT INTO SELECT`, then this is actually working as expected. The `INSERT INTO SELECT` is also cancel-able, which would unblock all subsequent `INSERT`s.

**Comment by jkosh44** [comment]
Though I think that it's not a great UX that a single bad COMPUTE node can potentially block all inserts across all clusters. So there might be some thing that should be done around that.

Another potentially related and important scenario to consider is programmer bugs. If we have a bug that causes a query to never complete successfully we'd see the same behavior as this issue which again is probably not a great UX.

**Comment by mjibson** [comment]
It only blocks if there's a ReadThenWrite, not all INSERTs. And if those are being run as the normal table mutation workload for users, it's pretty reasonable for things to block, because their SELECTs will be blocking too.

**Comment by sploiselle** [comment]
Just to summarize this issue:

If any read operation from a table panics, the global write lock on all tables
gets held until the client causing the panic drops. (The cluster replica
servicing the panic can crash loop, which is #12300, and is distinct from this
issue).

Feels like this issue points to a few issues we could to resolve:

1. Locking all tables is suboptimal because of cases like this, as well as any
  other situation where replicas are unresponsive. We could instead have
  per-table locks to mitigate the pain this issue causes. A pathological
  transaction like this that touches all tables would still seize the ability to
  write to tables, but more granular locks would help in the general case.

    A few notes:

    - Improving the granularity of the locks has benefits beyond resolving this
    issue because it will also improve the general UX of table inserts, which
    could get arbitrarily blocked by slow clusters.

    - It's possible to make locks more granular still by extracting any
    filters off of the `SELECT`, storing them, and then blocking only writes that
    meet those conditions--i.e. providing row-level locks. However, this is at
    least an order of magnitude more complex and wouldn't help us in the case of a
    crash-looping cluster because we'd still need to spin up a dataflow to do the
    evaluation of the write vs. the locks.

2. Terminating outstanding queries on unhealthy clusters (i.e. when waiting on a
  response from a cluster that contains only unhealthy replicas).

  We cannot complete this work immediately, however, because it's predicated on
  open PR #12296

Note that resolving the second issue (terminating outstanding queries on
unhealthy clusters) in obviates the need for the first (more granular locks)
w/r/t this issue. However, because the second solution cannot get immediately
implemented, implementing the first might be a decent stopgap (which also has
additional benefits, so might be worth doing anyway).

**Comment by mjibson** [comment]
Doing 1. has additional correctness risks because we have to account for read sets in the lock handling (maybe this is easy, but it is at least something else to think about).

What happens today if a user cancels a pending UPDATE query whose compute cluster is down? I understand that it would cancel the peek from the UPDATE and allow everything to proceed. Is that the case? If so, it seems that coord could maybe do a similar thing in order to implement 2. without needing to wait for other PRs.

One proposal is that the read phase of ReadThenWrite has an internal timeout for the read. The read timestamps are already designed to be immediately readable (shouldn't ever land as a pending peek in dataflow), so having an internal timeout is maybe ok. 10s? 30s? This proposal is bad because it puts an upper limit on the size of an UPDATE/DELETE as "your read set must be smaller than the time it takes to compute and send the rows over the network to coord" which is super variable.

Maybe we use a timeout today even though we knows it's bad, but then use some health metric once it's available in the future? That seems like a nice tradeoff.

Other options: in the impl of defer_write, which is exactly the place where there's an in progress ReadThenWrite, that could be the thing that does some timeout or otherwise makes a decision about if to issue a peek cancel for the read.

**Comment by frankmcsherry** [comment]
Is another option to not take locks, and instead perform the read and commit it if by the time it returns the timestamp is still a valid write timestamp (or whatever the requirement is for it still to still be a valid transaction). This would allow these sort of transactions to race, with slow transactions being rolled back rather than blocking the system. In .. my perhaps oversimplified mental model.

**Comment by sploiselle** [comment]
I'm digging into both the timeout and the optimistic concurrency control suggestions

**Comment by mjibson** [comment]
The problem with that solution is in a workload with lots of INSERTs and a few UPDATEs or DELETEs, the INSERTs will cause the UPDATE and DELETEs to retry forever. We could probably get away with it, and then users would eventually ask for things like SELECT FOR UPDATE or the equivalent to tell the system "hey please give this transaction priority".

**Comment by frankmcsherry** [comment]
I think this is a "standard" question of whether we want to optimize for high contention or low contention. We can certainly get increasingly complicated, and probably the right thing to do is learn a bit about how these things are used.

One thing I forgot to say but wanted to flag: all of these operations are also "contending" with reads as well, in that holding back table insertions prevents the stream-y updates of views based on tables. Morally, we have this background task that is continually inserting nothing into the tables for the sole purpose of advancing timestamps, and that is also contending.

**Comment by sploiselle** [comment]
Assessed the proposed fixes; tl;dr, think we should just add a timeout to the lock (30 seconds?) because it'll be easy to remove once @teskje's work lands.

Note that these fixes focus on the UX  that the bug causes, and not necessarily addressing the underlying issue.

# Permanent fixes

## Optimistic concurrency control

Frank suggests removing the global table lock entirely and instead relying on
the read timestamp in `ReadThenWrite` operations to determine if a write
occurred after the read; if a write occurred, the current since should be in advance of the
read timestamp, and the transaction containing the `ReadThenWrite` must
rollback. This is a "standard" optimistic concurrency control strategy.

### Complexity

This would require some dramatic reconsideration of assigning timestamps to
table operations. I'd estimate this work at 1-2 weeks, in part due to the
expanded testing this would require.

### Pros

- Totally resolves the issue of wedging table operations while waiting on a
  response from a failed cluster.

### Cons

- We advance our table timestamps every second. This would mean that no
  transaction containing a `ReadThenWrite` could ever take more than a second.
  Even if this value were configurable to `n`, no `ReadThenWrite` operation
  could ever take more than `n`.

  This would make it hard to complete e.g. a complex `INSERT...SELECT`, which has to
  construct an arbitrarily complex dataflow. It's easy to imagine this process taking more than a second.
  
  The only way to overcome this limitation would be a redesign of table
  timestamp advancement. Table timestamp advancement could change though I have
  not considered that with any depth.

- A naive version of this implementation would have a hard time interleaving
  `ReadThenWrite` operations with writes; if _any_ write occurred after the
  `RtW`'s read but before its write, the `RtW` must rollback. Another way to
  express this is that it introduces an optimistic lock across the set of all tables.

  Circumventing this limitation requires something at least as complex as
  read/write set tracking to make the optimistic lock more granular.

- Doesn't do anything to gracefully handle connection to a failed cluster in and
  of itself

### Assessment

A naive implementation of this approach has long-term drawbacks that would make tables much less user-friendly, i.e. not being able to perform any operations that take more than a second seems unfortunate. Coupled with the complexity of this work, I don't favor this approach.

## Cluster replica health monitor

Jan is currently working on a PR to introduce cluster replica introspection; we
could use this system to understand if a cluster is unhealthy (i.e. we should
not expect a response), in which case we can actively cancel the session holding
the table lock. (Canceling the session successfully frees the lock.)

### Complexity

While the implementation of monitoring replica health is complex, it is
something we've determined must be done, so is "free" from the perspective of
the amount of work required to fix this bug.

Actually fixing the bug should be somewhat straightforward with cluster replica
health monitoring in place, i.e. if you detect a cluster is down, you can cancel
all pending peeks associated with it, and this issue is resolved. I estimate
this at 1 week of work, max--most of which would be bundled into other work
we've already committed to doing w/r/t surfacing this data to users.

### Pros

- Relies on replica information to make considered decisions, i.e. addresses the
  heart of the matter, which is handling downed clusters.

### Cons

- This work is on an indeterminate timeline. From Jan:
    > There is no ETA yet. I'm currently figuring out if the planned approach is
    > feasible. Once Ufuk is back from vacation next week, the plan is to decide
    > if implemented this (or something else) for M1 is realistic or not.

### Assessment

This is the ideal solution to the problem, and we are not actively pursuing it at this point only because its timeline is unknown.

Once we have a firmer date from Jan, I'll include it in this issue.

# Temporary fixes

## Query timeouts

Matt suggests adding a timeout to `RtW` operations, determining an upper bound
for the length of time they can hold the lock.

### Complexity

Low--I believe this work could be done in 1-2 days.

### Pros

- Straightforward to implement
- Provides a proxy for cluster replica health
- Small enough amount of work that removing it once we can monitor cluster
  replica health will not feel like we wasted a bunch of time.

### Cons

- Similar to Frank's strategy, this prohibits long-running operations in the
  read portion of a `RtW` operation, i.e. it cannot disambiguate between a
  downed cluster and a complex read.

### Assessment

I dislike the limitation this imposes on the length of the read side of a read then write, but it seems like the simplest bandaid to apply, and the least painful to remove.

## Granular pessimistic locks

The current locking system that enables `ReadThenWrite` operations is a global
lock over all tables. We could mitigate the scope of impact of this issue by
instead holding more granular locks (likely per table). We would do this by:
- Creating a RWMutex for each table
- For `RtW`, both...
    - Provide a write handle to the RWMutex fo the table you're wring to.
    - Provide a read handle to the RWMutex for all tables read from.
- Provide a write handle to the table's RWMutex for all table writes.

### Complexity

This increases the complexity of our table-level concurrency; I think 1 week plus a day or two of slop.

### Pros

- Offers a generalized improvement to table-level concurrency that easily lives
  alongside the replica health monitor (i.e. doesn't require removal/refactor).

### Cons

- This would does nothing to address the real underlying issue (waiting forever
  on a downed replica), but would reduce the impact of the bug's symptom (the
  only writes the block are those to tables we read from). In the pathological case, this is just as bad as the current state, but generally will be less painful.

### Assessment

This is an appealing option because it is a feature that has additional benefit, however it doesn't fix the underlying issue, and requires more investment than adding a timeout.

# Approach

Given the simplicity of the fix, I suggest we take the approach of simply adding a timeout. If Jan's work looks like it will take an abundance of time, we can revisit.

**Comment by jkosh44** [comment]
For timeouts, we could add the session variable `statement_timeout` (https://www.postgresql.org/docs/current/runtime-config-client.html) which would allow users decide an appropriate timeout and add some pg compatibility.

**Comment by sploiselle** [comment]
@jkosh44 That would require plumbing that timeout to e.g. vanilla reads that don't hold a lock, as well. To narrow the scope of this work, not something I'm actively planning to pursue.

**Comment by frankmcsherry** [comment]
Another potential fix, much more sci-fi than these but I wanted to mention: have the coordinator initiate a TAIL rather than a PEEK. This will provide it with a snapshot at a time, but also establish a change log from which it can see the values at various times. If the system time has advanced in the meantime, the coordinator could potentially pick a later result instead, without re-issuing a new PEEK.

**Comment by teskje** [comment]
Just so everyone is aware: The thing I am working on is properly surfacing compute introspection data from clusters with more than one replica. We already surface introspection data, but it only works correctly for clusters that consist of a single replica. The relevant issue is #11782.

Importantly, surfacing the introspection data alone is not enough to determine a replica's health. We also need to figure out, how we can sensibly map the low-level introspection data to health verdicts. #11587 is tracking that.

Also importantly, it currently seems that if we implement #11782 for M1, we won't be able to unconditionally enable it before persist compaction is implemented, which is not planned for M1 (see  #12399 for details). If replica health monitoring uses that introspection data (which it probably should), it too will not unconditionally be available for M1.

It would be possible to initially implement health monitoring on top of our old introspection mechanism. This would have the benefit that health monitoring could be available for M1, and it would work well for detecting failing clusters that only have a single replica. If clusters have more than one replica, this approach would sometimes lead to FPs, declaring clusters as unhealthy even if only some of its replicas are failing. I'm not sure how helpful that would be.

**Comment by sploiselle** [comment]
@frankmcsherry I'm really intrigued by your idea of moving `ReadThenWrite` operations to `TAIL`. I put up #12427 just to fix this issue, but I'm going to sketch out a design for the `TAIL` proposal; removing the table lock from ADAPTER seems like a superior design.
