### ISSUE TITLE
Startup very slow in the presence of many database objects

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#12397]
Item No 5. There seems to be some quadratic or cubic algorithm kicking in because after I created a couple of thousand tables with a script like this:

```
cols = ", ".join(f"f{i} INTEGER" for i in range (100))
for i in range(10000):
    print(f"CREATE TABLE t{i} ({cols});");
```

materialized hangs on restart and is never able to get to the state where it accepts queries. There is one thread that is spinning like this:

```
Thread 1 (Thread 0x7fd84f71a840 (LWP 2106034)):
#0  0x0000560df954be52 in alloc::collections::btree::node::Handle<alloc::collections::btree::node::NodeRef<alloc::collections::btree::node::marker::Mut,K,V,alloc::collections::btree::node::marker::Leaf>,alloc::collections::btree::node::marker::Edge>::insert_recursing ()
#1  0x0000560df9ed6bd3 in alloc::collections::btree::map::BTreeMap<K,V>::insert ()
#2  0x0000560df961c643 in mz_stash::TableTransaction<K,V,I>::verify ()
#3  0x0000560df96220b7 in mz_stash::TableTransaction<K,V,I>::update ()
#4  0x0000560df9b84fa9 in mz_coord::catalog::storage::Transaction<S>::update_item ()
#5  0x0000560df95a0f26 in mz_coord::catalog::migrate::rewrite_items ()
#6  0x0000560df97c529d in mz_coord::catalog::Catalog<S>::open::{{closure}} ()
#7  0x0000560df96c9e29 in materialized::serve_stash::{{closure}} ()
#8  0x0000560df9a79c41 in <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll ()
#9  0x0000560df9d055fd in std::thread::local::LocalKey<T>::with ()
#10 0x0000560df9e6d432 in tokio::park::thread::CachedParkThread::block_on ()
#11 0x0000560df9df30d8 in tokio::runtime::thread_pool::ThreadPool::block_on ()
#12 0x0000560df9a18d91 in tokio::runtime::Runtime::block_on ()
#13 0x0000560df9c1ea6a in materialized::run ()
#14 0x0000560df9c1adee in materialized::main ()
#15 0x0000560df9df1eb3 in std::sys_common::backtrace::__rust_begin_short_backtrace ()
#16 0x0000560df9fafe89 in std::rt::lang_start::{{closure}} ()
#17 0x0000560dfbcfc1d1 in core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once () at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:259
#18 std::panicking::try::do_call () at library/std/src/panicking.rs:492
#19 std::panicking::try () at library/std/src/panicking.rs:456
#20 std::panic::catch_unwind () at library/std/src/panic.rs:137
#21 std::rt::lang_start_internal::{{closure}} () at library/std/src/rt.rs:128
#22 std::panicking::try::do_call () at library/std/src/panicking.rs:492
#23 std::panicking::try () at library/std/src/panicking.rs:456
#24 std::panic::catch_unwind () at library/std/src/panic.rs:137
#25 std::rt::lang_start_internal () at library/std/src/rt.rs:128
#26 0x0000560df9c76b12 in main ()
```

```
postgres=# select count(*) from data;
 count 
-------
 14031
(1 row)
```

_Originally posted by @philip-stoev in https://github.com/MaterializeInc/materialize/issues/12270#issuecomment-1118850346_

**Comment by philip-stoev** [comment]
The test is no longer realistic, the product is not expected to handle hundreds of tables at this time. So closing it for the time being.
