### ISSUE TITLE
Computed fails to re-start after creating a materialized view

### ISSUE THREAD

**Issue by lluki** [MaterializeInc/materialize#12645]
### What version of Materialize are you using?

8bbec1fd3

### How did you install Materialize?

Built from source

### What is the issue?

Materialized does not re-start after a materialized view has been created. The problem is that the spawned computed doesn't come up: ```thread 'timely:work-0' panicked at 'called `Option::unwrap()` on a `None` value', /home/lukas/mat/materialize/src/compute/src/server.rs:219:41```

## Steps to reproduce
Clean everything:
```
$ rm -rf mzdata                                                                                                                                                                                      
$ psql -d postgres -c "DROP DATABASE lukas"
$ psql -d postgres -c "CREATE DATABASE lukas"
```

Launch materialized: `./bin/materialized`
Run the following testdrive script (this is a short version of the replica isolation testdrive script):
```
> CREATE TABLE ten (f1 INTEGER);
> INSERT INTO ten SELECT * FROM generate_series(1, 10);
> CREATE MATERIALIZED VIEW expensive AS SELECT (a1.f1 * 1) +
          (a2.f1 * 10) +
          (a3.f1 * 100) +
          (a4.f1 * 1000) +
          (a5.f1 * 10000) 
  FROM ten AS a1, ten AS a2, ten AS a3, ten AS a4, ten AS a5;
```
Kill materialized with `Ctrl+c`. Restart materialized with `./bin/materialized`. Materialized fails to start computed, log output:
```
$> ./bin/materialized
$ cargo build --bin storaged --bin computed --bin materialized
    Finished dev [unoptimized + debuginfo] target(s) in 0.23s
$ psql -At postgres://lukas@%2Fvar%2Frun%2Fpostgresql -c 'CREATE SCHEMA IF NOT EXISTS consensus'
NOTICE:  schema "consensus" already exists, skipping
CREATE SCHEMA
$ psql -At postgres://lukas@%2Fvar%2Frun%2Fpostgresql -c 'CREATE SCHEMA IF NOT EXISTS catalog'
NOTICE:  schema "catalog" already exists, skipping
CREATE SCHEMA
$ /home/lukas/mat/materialize/target/debug/materialized --persist-consensus-url=postgres://lukas@%2Fvar%2Frun%2Fpostgresql?options=--search_path=consensus --catalog-postgres-stash=postgres://lukas@%2Fvar%2Frun%2Fpostgresql?options=--search_path=catalog
booting server
materialized v0.26.1-dev (8bbec1fd3)
OpenSSL 1.1.1n  15 Mar 2022
librdkafka v1.8.2
invoked as: MZ_ROOT=/home/lukas/mat/materialize /home/lukas/mat/materialize/target/debug/materialized '--persist-consensus-url=postgres://lukas@%2Fvar%2Frun%2Fpostgresql?options=--search_path=consensus' '--catalog-postgres-stash=postgres://lukas@%2Fvar%2Frun%2Fpostgresql?
options=--search_path=catalog'
os: Ubuntu 21.10 (impish) [64-bit]
cpus: 24 logical, 12 physical, 12 useful
cpu0: AMD Ryzen 9 5900X 12-Core Processor 3026MHz
memory: 33581211KB total, 19990419KB used
swap: 34359734KB total, 295961KB used
max log level: info
2022-05-23T15:00:06.170792Z  INFO mz_orchestrator_process: Launching storage-runtime: /home/lukas/mat/materialize/target/debug/storaged --workers=1 --storage-addr=127.0.0.1:2101 --listen-addr=127.0.0.1:2100 --http-console-addr=127.0.0.1:2102 --log-process-name --pid-file-
location=/home/lukas/mat/materialize/mzdata/storage-runtime-0.pid...
storaged: 2022-05-23T15:00:06.178268Z  INFO storaged: about to bind to "127.0.0.1:2100"
storaged: 2022-05-23T15:00:06.178357Z  INFO storaged: listening for coordinator connection on 127.0.0.1:2100...
storaged: 2022-05-23T15:00:06.178371Z  INFO storaged: serving storaged HTTP server on 127.0.0.1:2102
storaged: 2022-05-23T15:00:06.178651Z  INFO mz_storage::boundary::tcp_boundary::server: About to bind to 127.0.0.1:2101
storaged: 2022-05-23T15:00:06.178688Z  INFO mz_storage::boundary::tcp_boundary::server: listening for storage connection on 127.0.0.1:2101...
storaged: 2022-05-23T15:00:06.224304Z  INFO storaged: coordinator connection accepted
2022-05-23T15:00:06.224339Z  INFO mz_dataflow_types::client::tcp: Reconnected to localhost:2100
2022-05-23T15:00:06.616509Z  INFO mz_coord::catalog: create table materialize.public.ten (u1)
2022-05-23T15:00:06.620915Z  INFO mz_coord::catalog: create view materialize.public.expensive (u2)
2022-05-23T15:00:06.621170Z  INFO mz_coord::catalog: create index materialize.public.expensive_primary_idx (u3)
2022-05-23T15:00:06.636523Z  INFO mz_coord::catalog: create table materialize.public.ten (u1)
2022-05-23T15:00:06.640815Z  INFO mz_coord::catalog: create view materialize.public.expensive (u2)
2022-05-23T15:00:06.641058Z  INFO mz_coord::catalog: create index materialize.public.expensive_primary_idx (u3)
2022-05-23T15:00:06.724405Z  INFO mz_orchestrator_process: Launching compute-cluster-1-replica-1: /home/lukas/mat/materialize/target/debug/computed --storage-addr=localhost:2101 --listen-addr=127.0.0.1:2103 --http-console-addr=127.0.0.1:2105 --processes=1 --workers=1 --lo
g-process-name localhost:2104 --process=0 --pid-file-location=/home/lukas/mat/materialize/mzdata/compute-cluster-1-replica-1-0.pid...
computed: 2022-05-23T15:00:06.731516Z  INFO computed: about to bind to "127.0.0.1:2103"
computed: 2022-05-23T15:00:06.731605Z  INFO computed: listening for coordinator connection on 127.0.0.1:2103...
computed: 2022-05-23T15:00:06.731618Z  INFO computed: serving computed HTTP server on 127.0.0.1:2105
computed: 2022-05-23T15:00:06.731863Z  INFO mz_storage::boundary::tcp_boundary::client: About to connect to "localhost:2101"
computed: 2022-05-23T15:00:06.732371Z  INFO mz_storage::boundary::tcp_boundary::client: Connected to storage server
computed: 2022-05-23T15:00:06.781815Z  INFO computed: coordinator connection accepted
2022-05-23T15:00:06.781816Z  INFO mz_dataflow_types::client::tcp: Reconnected to localhost:2103
thread 'timely:work-0' panicked at 'called `Option::unwrap()` on a `None` value', /home/lukas/mat/materialize/src/compute/src/server.rs:219:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-05-23T15:00:06.813560Z  WARN mz_dataflow_types::client::replicated: Rehydrating replica 1
=======================================================================
Thank you for trying Materialize!

We are interested in any and all feedback you have, which may be able
to improve both our software and your queries! Please reach out at:

    Web: https://materialize.com
    GitHub issues: https://github.com/MaterializeInc/materialize/issues
    Email: support@materialize.com
    Twitter: @MaterializeInc
=======================================================================

materialized v0.26.1-dev (8bbec1fd3) listening on 127.0.0.1:6875...
2022-05-23T15:00:06.854877Z ERROR mz_dataflow_types::client::tcp: connection unexpectedly errored: Connection reset by peer (os error 104)
2022-05-23T15:00:06.855199Z ERROR mz_orchestrator_process: compute-cluster-1-replica-1 exited: Ok(ExitStatus(unix_wait_status(134))); relaunching in 5s
2022-05-23T15:00:06.858438Z  WARN mz_dataflow_types::client::tcp: Error connecting to localhost:2103: Connection refused (os error 111); reconnecting in 10ms
2022-05-23T15:00:06.869757Z  WARN mz_dataflow_types::client::tcp: Error connecting to localhost:2103: Connection refused (os error 111); reconnecting in 20ms
2022-05-23T15:00:06.891067Z  WARN mz_dataflow_types::client::tcp: Error connecting to localhost:2103: Connection refused (os error 111); reconnecting in 40ms
2022-05-23T15:00:06.932506Z  WARN mz_dataflow_types::client::tcp: Error connecting to localhost:2103: Connection refused (os error 111); reconnecting in 80ms
2022-05-23T15:00:07.012971Z  WARN mz_dataflow_types::client::tcp: Error connecting to localhost:2103: Connection refused (os error 111); reconnecting in 160ms
2022-05-23T15:00:07.174705Z  WARN mz_dataflow_types::client::tcp: Error connecting to localhost:2103: Connection refused (os error 111); reconnecting in 320ms
2022-05-23T15:00:07.497479Z  WARN mz_dataflow_types::client::tcp: Error connecting to localhost:2103: Connection refused (os error 111); reconnecting in 640ms
2022-05-23T15:00:08.138570Z  WARN mz_dataflow_types::client::tcp: Error connecting to localhost:2103: Connection refused (os error 111); reconnecting in 1s
```

**Comment by lluki** [comment]
> Potential dupe of #12233?
That seems related or even the same! I can reproduce the issue with 100% reliability if it helps.  

> You could enable tracing for `mz_dataflow_types` and see if the communication with the replica actually starts with a `CreateInstance` command.

I'll try.
