### ISSUE TITLE
regression: panic with Kinesis sources in a multi-node cluster

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#12761]
### What version of Materialize are you using?

d6370f3

### How did you install Materialize?

Docker image

### What is the issue?

The Nightly Cluster reports the following:

```
materialized_1     | storaged: 2022-05-24T11:57:21.999283Z ERROR mz_storage::source::kinesis: Error { code: "ResourceInUseException", message: "Stream arn:aws:kinesis:us-east-1:000000000000:stream/testdrive-test-593024159 is not currently ACTIVE or UPDATING.", request_id: "ab5879c4-db58-11ec-9ac9-d1c63e5a9a71" }
materialized_1     | thread 'timely:work-0' panicked at 'assertion failed: `(left == right)`
materialized_1     |   left: `0`,
materialized_1     |  right: `1`', src/storage/src/source/kinesis.rs:163:9
materialized_1     | stack backtrace:
materialized_1     | 2022-05-24T11:57:22.128213Z  WARN mz_dataflow_types::client::tcp: Error connecting to localhost:1234: Cannot assign requested address (os error 99); reconnecting in 1s
materialized_1     |    0: rust_begin_unwind
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
materialized_1     |    1: core::panicking::panic_fmt
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
materialized_1     |    2: core::panicking::assert_failed_inner
materialized_1     |    3: core::panicking::assert_failed
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:182:5
materialized_1     |    4: <mz_storage::source::kinesis::KinesisSourceReader as mz_storage::source::SourceReader>::get_next_message
materialized_1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0254580edf2d085be-1/materialize/tests/src/storage/src/source/kinesis.rs:163:9
materialized_1     |    5: <mz_storage::source::DelimitedValueSource<S> as mz_storage::source::SourceReader>::get_next_message
materialized_1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0254580edf2d085be-1/materialize/tests/src/storage/src/source/mod.rs:192:15
materialized_1     |    6: mz_storage::source::SourceReader::next::{{closure}}
materialized_1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0254580edf2d085be-1/materialize/tests/src/storage/src/source/mod.rs:410:19
materialized_1     |    7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
materialized_1     |    8: <core::pin::Pin<P> as core::future::future::Future>::poll
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/future.rs:124:9
materialized_1     |    9: mz_storage::source::SourceReader::into_stream::{{closure}}
materialized_1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0254580edf2d085be-1/materialize/tests/src/storage/src/source/mod.rs:449:35
materialized_1     |   10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
materialized_1     |   11: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
materialized_1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/async-stream-0.3.3/src/async_stream.rs:53:17
materialized_1     |   12: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
materialized_1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/stream.rs:120:9
```

**Comment by philip-stoev** [comment]
There are at least two issues here:

- whatever is causing the `ResourceInUseException` error in Kinesis
- the fact that a problem with a single source can panic the entire process

**Comment by elindsey** [comment]
The kinesis source isn't in a good state and likely got more busted with the platform work. We're not intending to do any work on it in the M2 timeline - if it breaks anything, we can disable those tests and in the short-term can consider removing the kinesis source altogether.
