### ISSUE TITLE
regression: "no entry found for key" in mz_coord::catalog::CatalogState::get_entry

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#12760]
### What version of Materialize are you using?

0dd2c53

### How did you install Materialize?

Docker image

### What is the issue?

The Kafka Nightly has caused Mz to panic:

```
materialized_1     | thread 'coordinator' panicked at 'no entry found for key', src/coord/src/catalog.rs:277:10
materialized_1     | stack backtrace:
materialized_1     | 2022-05-29T12:07:25.877033Z  WARN mz_dataflow_types::client::tcp: Error connecting to localhost:1234: Cannot assign requested address (os error 99); reconnecting in 1s
materialized_1     | 2022-05-29T12:07:26.878683Z  WARN mz_dataflow_types::client::tcp: Error connecting to localhost:1234: Cannot assign requested address (os error 99); reconnecting in 1s
materialized_1     |    0: rust_begin_unwind
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
materialized_1     |    1: core::panicking::panic_fmt
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
materialized_1     |    2: core::panicking::panic_display
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:72:5
materialized_1     |    3: core::panicking::panic_str
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:56:5
materialized_1     |    4: core::option::expect_failed
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/option.rs:1874:5
materialized_1     |    5: core::option::Option<T>::expect
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/option.rs:718:21
materialized_1     |    6: <alloc::collections::btree::map::BTreeMap<K,V> as core::ops::index::Index<&Q>>::index
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/collections/btree/map.rs:2056:9
materialized_1     |    7: mz_coord::catalog::CatalogState::get_entry
materialized_1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-06b073eba10401c99-1/materialize/tests/src/coord/src/catalog.rs:277:10
materialized_1     |    8: mz_coord::catalog::CatalogState::get_indexes_on::{{closure}}
materialized_1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-06b073eba10401c99-1/materialize/tests/src/coord/src/catalog.rs:356:46
materialized_1     |    9: core::iter::adapters::filter_map::filter_map_fold::{{closure}}
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/iter/adapters/filter_map.rs:36:28
materialized_1     |   10: core::iter::traits::iterator::Iterator::fold
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/iter/traits/iterator.rs:2362:21
materialized_1     |   11: <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::fold
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/iter/adapters/filter_map.rs:85:9
materialized_1     |   12: <core::iter::adapters::filter::Filter<I,P> as core::iter::traits::iterator::Iterator>::fold
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/iter/adapters/filter.rs:101:9
materialized_1     |   13: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/iter/adapters/map.rs:124:9
materialized_1     |   14: <core::iter::adapters::peekable::Peekable<I> as core::iter::traits::iterator::Iterator>::fold
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/iter/adapters/peekable.rs:114:9
materialized_1     |   15: core::iter::traits::iterator::Iterator::for_each
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/iter/traits/iterator.rs:779:9
materialized_1     |   16: <alloc::collections::btree::set::BTreeSet<T> as core::iter::traits::collect::Extend<T>>::extend
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/collections/btree/set.rs:1211:9
materialized_1     |   17: mz_coord::coord::indexes::ComputeInstanceIndexOracle<T>::sufficient_collections
materialized_1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-06b073eba10401c99-1/materialize/tests/src/coord/src/coord/indexes.rs:72:17
materialized_1     |   18: mz_coord::coord::Coordinator<S>::sequence_peek::{{closure}}::{{closure}}
materialized_1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-06b073eba10401c99-1/materialize/tests/src/coord/src/coord.rs:3298:29
materialized_1     |   19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
materialized_1     |   20: mz_coord::coord::Coordinator<S>::sequence_peek::{{closure}}
materialized_1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-06b073eba10401c99-1/materialize/tests/src/coord/src/coord.rs:3078:5
materialized_1     |   21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
materialized_1     |   22: mz_coord::coord::Coordinator<S>::sequence_plan::{{closure}}
materialized_1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-06b073eba10401c99-1/materialize/tests/src/coord/src/coord.rs:1764:63
materialized_1     |   23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
materialized_1     |   24: mz_coord::coord::Coordinator<S>::handle_execute::{{closure}}::{{closure}}
materialized_1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-06b073eba10401c99-1/materialize/tests/src/coord/src/coord.rs:1488:66
materialized_1     |   25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
materialized_1     |   26: mz_coord::coord::Coordinator<S>::handle_execute::{{closure}}
materialized_1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-06b073eba10401c99-1/materialize/tests/src/coord/src/coord.rs:1307:5
materialized_1     |   27: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
materialized_1     |   28: mz_coord::coord::Coordinator<S>::message_command::{{closure}}::{{closure}}
materialized_1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-06b073eba10401c99-1/materialize/tests/src/coord/src/coord.rs:1060:62
materialized_1     |   29: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
materialized_1     |   30: mz_coord::coord::Coordinator<S>::message_command::{{closure}}
materialized_1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-06b073eba10401c99-1/materialize/tests/src/coord/src/coord.rs:978:5
materialized_1     |   31: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
materialized_1     |   32: mz_coord::coord::Coordinator<S>::serve::{{closure}}
materialized_1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-06b073eba10401c99-1/materialize/tests/src/coord/src/coord.rs:770:67
materialized_1     |   33: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
materialized_1     |   34: tokio::park::thread::CachedParkThread::block_on::{{closure}}
materialized_1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/park/thread.rs:263:54
materialized_1     |   35: tokio::coop::with_budget::{{closure}}
materialized_1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:102:9
materialized_1     |   36: std::thread::local::LocalKey<T>::try_with
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:442:16
materialized_1     |   37: std::thread::local::LocalKey<T>::with
materialized_1     |              at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:418:9
materialized_1     |   38: tokio::coop::with_budget
materialized_1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:95:5
materialized_1     |   39: tokio::coop::budget
materialized_1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:72:5
materialized_1     |   40: tokio::park::thread::CachedParkThread::block_on
materialized_1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/park/thread.rs:263:31
materialized_1     |   41: tokio::runtime::enter::Enter::block_on
materialized_1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/enter.rs:151:13
materialized_1     |   42: tokio::runtime::handle::Handle::block_on
materialized_1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/handle.rs:299:9
materialized_1     |   43: mz_coord::coord::serve::{{closure}}::{{closure}}
materialized_1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-06b073eba10401c99-1/materialize/tests/src/coord/src/coord.rs:4962:17
materialized_1     | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
materialized_1     | computed: 2022-05-29T12:07:26.958347Z  INFO computed: coordinator connection gone; terminating
```

test is `tables.td`

**Comment by philip-stoev** [comment]
Affects the ARM build too https://buildkite.com/materialize/nightlies/builds/963#0181a414-e4c2-4b54-93d3-b0d032d1f05b

**Comment by JLDLaughlin** [comment]
reproduction steps: https://materializeinc.slack.com/archives/CMHDK0DK8/p1658423057163659

**Comment by benesch** [comment]
This is possibly fixed by https://github.com/MaterializeInc/materialize/pull/13862. We'll know if https://buildkite.com/materialize/nightlies/builds/1034 passes.
