### ISSUE TITLE
Coordinator panics if you close a TAIL on a dropped cluster

### ISSUE THREAD

**Issue by andrioni** [MaterializeInc/materialize#12951]
### What version of Materialize are you using?

 v0.26.1-dev (cda2513e5)

### How did you install Materialize?

Built from source

### What is the issue?

If I run a `TAIL` statement on a cluster, then drop the cluster, as soon as I stop the `TAIL`, the coordinator panics.

```
c1=> CREATE CLUSTER foo REPLICAS (r1 (size '1'));
CREATE CLUSTER;
c1=> CREATE TABLE t1(f1 int);
CREATE TABLE

-- Run the following on a separate connection
c2=> SET CLUSTER = foo;
SET
c2=> COPY (TAIL (SELECT * FROM t1)) TO STDOUT;

-- Back to the original connection
c1=> DROP CLUSTER foo;
DROP CLUSTER

-- Back on the connection running TAIL, press Ctrl-C
^CCancel request sent
COPY data transfer failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

After this, mz panics, with the log below.

### Relevant log output

```source
thread 'coordinator' panicked at 'called `Option::unwrap()` on a `None` value', /Users/alessandro/workspace/mz/materialize/src/coord/src/coord.rs:4689:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::panicking::panic
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/option.rs:755:21
   4: mz_coord::coord::Coordinator<S>::drop_sinks::{{closure}}
             at ./src/coord/src/coord.rs:4687:13
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
   6: mz_coord::coord::Coordinator<S>::clear_transaction::{{closure}}
             at ./src/coord/src/coord.rs:1626:36
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
   8: mz_coord::coord::Coordinator<S>::sequence_end_transaction_inner::{{closure}}
             at ./src/coord/src/coord.rs:3028:50
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  10: mz_coord::coord::Coordinator<S>::sequence_end_transaction::{{closure}}
             at ./src/coord/src/coord.rs:2995:66
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  12: mz_coord::coord::Coordinator<S>::message_command::{{closure}}::{{closure}}
             at ./src/coord/src/coord.rs:1185:67
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  14: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.34/src/instrument.rs:272:9
  15: mz_coord::coord::Coordinator<S>::message_command::{{closure}}
             at ./src/coord/src/coord.rs:1024:5
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  17: mz_coord::coord::Coordinator<S>::serve::{{closure}}
             at ./src/coord/src/coord.rs:805:67
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  19: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/park/thread.rs:263:54
  20: tokio::coop::with_budget::{{closure}}
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/coop.rs:102:9
  21: std::thread::local::LocalKey<T>::try_with
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:442:16
  22: std::thread::local::LocalKey<T>::with
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:418:9
  23: tokio::coop::with_budget
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/coop.rs:95:5
  24: tokio::coop::budget
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/coop.rs:72:5
  25: tokio::park::thread::CachedParkThread::block_on
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/park/thread.rs:263:31
  26: tokio::runtime::enter::Enter::block_on
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/runtime/enter.rs:151:13
  27: tokio::runtime::handle::Handle::block_on
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/runtime/handle.rs:296:9
  28: mz_coord::coord::serve::{{closure}}::{{closure}}
             at ./src/coord/src/coord.rs:5051:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[1]    25219 abort      RUST_BACKTRACE=1 ./bin/materialized
```

**Comment by philip-stoev** [comment]
Good catch! This would be a "cluster isolation" bug, so I will stick it into the epic.
