### ISSUE TITLE
Coordinator panics when `TAIL`ing a dropped cluster

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#13100]
This looks just like #12951, except that @heeringa observed it on 5ae377002bc1aa4a9ab6a037f6fc0bc8e9f034fe, which seemingly includes the fix for #12951 (https://github.com/MaterializeInc/materialize/pull/12978).

```
2022-06-13T21:31:37.666919Z  WARN mz_dataflow_types::client::replicated: Rehydrating replica 3
2022-06-13T21:31:37.667115Z  WARN mz_dataflow_types::client::replicated: Rehydrating replica 2
2022-06-13T21:32:07.193067Z  INFO mz_coord::catalog: drop table materialize.public.ten_k (u16)
2022-06-13T21:32:10.744437Z  INFO mz_coord::catalog: create table materialize.public.ten_k (u27)
2022-06-13T21:32:43.465334Z  INFO mz_coord::catalog: create view materialize.public.fifty_m (u28)
thread 'coordinator' panicked at 'called `Result::unwrap()` on an `Err` value: IdentifierMissing(User(25))', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03966d7357c9ad138-1/materialize/tests/src/coord/src/coord.rs:4958:47
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::unwrap
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1078:23
   4: mz_coord::coord::Coordinator<S>::drop_sinks::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03966d7357c9ad138-1/materialize/tests/src/coord/src/coord.rs:4958:17
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
   6: mz_coord::coord::Coordinator<S>::clear_transaction::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03966d7357c9ad138-1/materialize/tests/src/coord/src/coord.rs:1824:36
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
   8: mz_coord::coord::Coordinator<S>::sequence_end_transaction_inner::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03966d7357c9ad138-1/materialize/tests/src/coord/src/coord.rs:3286:50
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  10: mz_coord::coord::Coordinator<S>::sequence_end_transaction::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03966d7357c9ad138-1/materialize/tests/src/coord/src/coord.rs:3252:66
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  12: mz_coord::coord::Coordinator<S>::message_command::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03966d7357c9ad138-1/materialize/tests/src/coord/src/coord.rs:1364:67
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  14: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.34/src/instrument.rs:272:9
  15: mz_coord::coord::Coordinator<S>::message_command::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03966d7357c9ad138-1/materialize/tests/src/coord/src/coord.rs:1203:5
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  17: mz_coord::coord::Coordinator<S>::serve::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03966d7357c9ad138-1/materialize/tests/src/coord/src/coord.rs:865:67
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/future/mod.rs:91:19
  19: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/park/thread.rs:263:54
  20: tokio::coop::with_budget::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/coop.rs:102:9
  21: std::thread::local::LocalKey<T>::try_with
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:442:16
  22: std::thread::local::LocalKey<T>::with
             at ./rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/thread/local.rs:418:9
  23: tokio::coop::with_budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/coop.rs:95:5
  24: tokio::coop::budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/coop.rs:72:5
  25: tokio::park::thread::CachedParkThread::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/park/thread.rs:263:31
  26: tokio::runtime::enter::Enter::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/runtime/enter.rs:151:13
  27: tokio::runtime::handle::Handle::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/runtime/handle.rs:296:9
  28: mz_coord::coord::serve::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03966d7357c9ad138-1/materialize/tests/src/coord/src/coord.rs:5319:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Stream closed EOF for environment-001bd74d-48fe-4be0-998e-cb3eca622a5d-0/coordd-0 (coordd)
```

**Comment by benesch** [comment]
Here's the line in question:

https://github.com/MaterializeInc/materialize/blob/5ae377002bc1aa4a9ab6a037f6fc0bc8e9f034fe/src/coord/src/coord.rs#L4958

**Comment by mjibson** [comment]
If the cluster was already dropped, then why did `self.dataflow_client.compute_mut(compute_instance)` there return `Some`?

**Comment by benesch** [comment]
I have the same question. It is strange. We don’t have an exact accounting of the sequence of events because Brent had two terminal tabs open. Maybe somehow the index that was being tailed got dropped, but the cluster stuck around?

**Comment by mjibson** [comment]
This is possibly a controller bug then?

**Comment by benesch** [comment]
> This is possibly a controller bug then?

My money is still on adapter. I figured out how to reproduce this reliably!

```
c1=> CREATE CLUSTER foo REPLICAS (r1 (size '1'));
CREATE CLUSTER;
c1=> CREATE TABLE t1(f1 int);
CREATE TABLE

-- Run the following on a separate connection
c2=> SET CLUSTER = foo;
SET
c2=> COPY (TAIL (SELECT * FROM t1)) TO STDOUT;

-- Back to the original connection
c1=> DROP CLUSTER foo;
DROP CLUSTER
c1=> CREATE CLUSTER newcluster REPLICAS (r1 (size '1')); -- This is the difference.
CREATE CLUSTER;

-- Back on the connection running TAIL, press Ctrl-C
^CCancel request sent
COPY data transfer failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

The trick is to drop the original cluster _and create a new one_ before canceling the tail.

**Comment by benesch** [comment]
Welp, we're reusing cluster IDs. That seems like a massively bad idea.

**Comment by benesch** [comment]
Ah, ok. It is documented to do this:

https://github.com/MaterializeInc/materialize/blob/416ff310d755854120f28ef942acfb2e67637b32/src/stash/src/lib.rs#L877-L878

I suspect this changed when we switched the catalog from using SQLite to using the stash. @mjibson—is it easy to _not_ do that, and guarantee permanently auto-incrementing IDs? I'm not actually sure how to fix this bug otherwise.

**Comment by mjibson** [comment]
> I suspect this changed when we switched the catalog from using SQLite to using the stash.

Hmm, I designed this feature to be exactly compatible with sqlite, which reuses auto incremented ids after delete. See https://www.sqlite.org/autoinc.html:

> On an INSERT, if the ROWID or INTEGER PRIMARY KEY column is not explicitly given a value, then it will be filled automatically with an unused integer, usually one more than the largest ROWID currently in use.

Some [fiddle](https://sqlite.org/fiddle/) output:

```
CREATE TABLE compute_instances (
        id   integer PRIMARY KEY,
        name text
);
insert into compute_instances (name) values ('a');
select * from compute_instances;
delete from compute_instances;
insert into compute_instances (name) values ('b');
select * from compute_instances;
```

```
┌────┬──────┐
│ id │ name │
├────┼──────┤
│ 1  │ a    │
└────┴──────┘
┌────┬──────┐
│ id │ name │
├────┼──────┤
│ 1  │ b    │
└────┴──────┘
```

**Comment by mjibson** [comment]
See https://github.com/MaterializeInc/materialize/blob/0cbaf3a3157b475f40793bc6bce85330912aee0e/src/coord/src/catalog/storage.rs#L613 for where we did this.

**Comment by benesch** [comment]
Well shoot! I guess it’s always been a lurking bug then. Is it easy to fix
nonetheless?

**Comment by mjibson** [comment]
Yup, working on it today.

**Comment by jkosh44** [comment]
I just want to summarize what is causing the issue, much of this is repetitive of what's said above.

# Issue
Cluster IDs have their own separate namespace. When a new cluster is created, it is assigned an ID that is one higher than the maximum of all current cluster IDs. For example if we have the following clusters and ids:
- "default" -> 1
- "bar" -> 22
- "foo" -> 30

Then the next cluster will have an ID of 31.

The sequence of events that cause this issue are as follows:

0. The default cluster exists with ID 1.
1. `c1=> CREATE CLUSTER foo REPLICAS (r1 (size '1'));`
  a. `foo` is created and assigned ID 2 (max(1) + 1).
2. `c1 => CREATE TABLE t1(f1 int);`
  a. `t1` is created in the cluster with ID 2 (`foo`).
3. `c2=> SET CLUSTER = foo;`
  a. Current cluster is set to the cluster with ID 2 (`foo`).
4. `c2=> COPY (TAIL (SELECT * FROM t1)) TO STDOUT;`
  a. A temporary sink is created in the cluster with ID 2 (`foo`). Sinks are used to implement `TAIL`.
5. `c1=> DROP CLUSTER foo;`
  a. The cluster with ID 2 (`foo`) is deleted along with all the metadata about it's objects.
  b. The only existing cluster is the default cluster with ID 1.
6. `c1=> CREATE CLUSTER newcluster REPLICAS (r1 (size '1'));`
  a. `newcluster` is created and assigned ID 2 (max(1) + 1).
7. -- Back on the connection running TAIL, press Ctrl-C
  a. We try and delete the sink that was getting results for the TAIL.
  b. The sink was created in a cluster with ID 2, so we grab a reference to the cluster with ID 2 (`newcluster`).
  c. We ask `newcluster` to delete our sink, `newcluster` doesn't have our sink and panics.

# Solution
We should stop reusing IDs in clusters and instead just monotonically allocate them like we do for `GlobalID`s.
