### ISSUE TITLE
Survivable Postgres errors cause a panic because they are considered Indeterminate

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#13379]
### What version of Materialize are you using?

v0.26.1-dev

### How did you install Materialize?

Docker image

### What is the issue?

The list of Postgres errors that Mz survives is , at the time of writing, limited to SERIALIZATION_FAILURE . All other Postgres errors will cause Mz to panic.

This is surely to cause a lot of grief when operating at scale. For example, simply restarting the postgres instance currently causes a panic. 

I think we need to go through the entire list of possible Postgres errors and categorize them. @petrosagg has mentioned that such a categorization may already exist in the Postgres codebase itself. I found rhe following table: https://www.postgresql.org/docs/current/errcodes-appendix.html but maybe Aurora defines additional errors on top of those.

At the very least, the following should be retriable:

- `thread 'coordinator' panicked at 'cannot append updates: Indeterminate { inner: db error: FATAL: terminating connection due to administrator command`
- any errors indicating that the network connection with Postgres has been disrupted
- any errors that may indicate an outage at Aurora due to misconfiguration, e.g. all sorts of "permission denied" errors, . 
- Class 53 — Insufficient Resources
- Class 57 — Operator Intervention
- Class 08 — Connection Exception
- 42501 | insufficient_privilege

### Relevant log output

```source
environmentd: 2022-07-01T12:19:32.127587Z ERROR mz_stash::postgres: postgres stash connection error: db error: FATAL: terminating connection due to administrator command
environmentd: 2022-07-01T12:19:32.127636Z ERROR mz_stash::postgres: postgres stash connection error: db error: FATAL: terminating connection due to administrator command
environmentd: 2022-07-01T12:19:32.130098Z ERROR mz_persist::postgres: connection error: error communicating with the server: Connection reset by peer (os error 104)
thread 'coordinator' panicked at 'cannot append updates: Indeterminate { inner: db error: FATAL: terminating connection due to administrator command

Caused by:
    FATAL: terminating connection due to administrator command

Stack backtrace:
   0: <mz_persist::location::ExternalError as core::convert::From<tokio_postgres::error::Error>>::from
   1: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
   2: <mz_persist::postgres::PostgresConsensus as mz_persist::location::Consensus>::head::{{closure}}
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: <core::pin::Pin<P> as core::future::future::Future>::poll
   5: <mz_persist::postgres::PostgresConsensus as mz_persist::location::Consensus>::compare_and_set::{{closure}}
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: <core::pin::Pin<P> as core::future::future::Future>::poll
   8: mz_persist_client::impl::metrics::ExternalOpMetrics::run_op::{{closure}}
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: <mz_persist_client::impl::metrics::MetricsConsensus as mz_persist::location::Consensus>::compare_and_set::{{closure}}
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: <core::pin::Pin<P> as core::future::future::Future>::poll
  13: mz_persist_client::impl::machine::Machine<K,V,T,D>::apply_unbatched_cmd::{{closure}}::{{closure}}::{{closure}}::{{closure}}::{{closure}}
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: mz_persist_client::impl::machine::retry_determinate::{{closure}}
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  17: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  18: mz_persist_client::impl::machine::Machine<K,V,T,D>::apply_unbatched_cmd::{{closure}}::{{closure}}::{{closure}}
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  20: mz_persist_client::impl::metrics::CmdMetrics::run_cmd::{{closure}}
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  22: mz_persist_client::impl::machine::Machine<K,V,T,D>::apply_unbatched_cmd::{{closure}}
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  24: mz_persist_client::impl::machine::Machine<K,V,T,D>::compare_and_append::{{closure}}
  25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  26: mz_persist_client::write::WriteHandle<K,V,T,D>::compare_and_append_batch::{{closure}}::{{closure}}
  27: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  28: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  29: mz_persist_client::write::WriteHandle<K,V,T,D>::compare_and_append_batch::{{closure}}
  30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  31: mz_persist_client::write::WriteHandle<K,V,T,D>::compare_and_append::{{closure}}::{{closure}}
  32: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  33: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  34: mz_persist_client::write::WriteHandle<K,V,T,D>::compare_and_append::{{closure}}
  35: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  36: <mz_dataflow_types::client::controller::storage::Controller<T> as mz_dataflow_types::client::controller::storage::StorageController>::append::{{closure}}::{{closure}}::{{closure}}
  37: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  38: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next
  39: <S as futures_core::stream::TryStream>::try_poll_next
  40: <futures_util::stream::try_stream::try_collect::TryCollect<St,C> as core::future::future::Future>::poll
  41: <mz_dataflow_types::client::controller::storage::Controller<T> as mz_dataflow_types::client::controller::storage::StorageController>::append::{{closure}}::{{closure}}
  42: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  43: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  44: <mz_dataflow_types::client::controller::storage::Controller<T> as mz_dataflow_types::client::controller::storage::StorageController>::append::{{closure}}
  45: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  46: <core::pin::Pin<P> as core::future::future::Future>::poll
  47: mz_coord::coord::Coordinator<S>::advance_local_input::{{closure}}::{{closure}}
  48: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  49: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  50: mz_coord::coord::Coordinator<S>::advance_local_input::{{closure}}
  51: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  52: mz_coord::coord::Coordinator<S>::serve::{{closure}}
  53: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  54: tokio::park::thread::CachedParkThread::block_on::{{closure}}
  55: tokio::coop::with_budget::{{closure}}
  56: std::thread::local::LocalKey<T>::try_with
  57: std::thread::local::LocalKey<T>::with
  58: tokio::park::thread::CachedParkThread::block_on
  59: tokio::runtime::enter::Enter::block_on
  60: tokio::runtime::handle::Handle::block_on
  61: mz_coord::coord::serve::{{closure}}::{{closure}}
  62: std::sys_common::backtrace::__rust_begin_short_backtrace
  63: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
  64: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  65: std::panicking::try::do_call
  66: __rust_try
  67: std::panicking::try
  68: std::panic::catch_unwind
  69: std::thread::Builder::spawn_unchecked_::{{closure}}
  70: core::ops::function::FnOnce::call_once{{vtable.shim}}
  71: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/boxed.rs:1861:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/boxed.rs:1861:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys/unix/thread.rs:108:17
  72: start_thread
             at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
  73: clone
             at /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95 }', /home/pstoev/jkosh44-revive-tables/src/dataflow-types/src/client/controller/storage.rs:592:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::expect
   4: <mz_dataflow_types::client::controller::storage::Controller<T> as mz_dataflow_types::client::controller::storage::StorageController>::append::{{closure}}::{{closure}}::{{closure}}
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next
   7: <S as futures_core::stream::TryStream>::try_poll_next
   8: <futures_util::stream::try_stream::try_collect::TryCollect<St,C> as core::future::future::Future>::poll
   9: <mz_dataflow_types::client::controller::storage::Controller<T> as mz_dataflow_types::client::controller::storage::StorageController>::append::{{closure}}::{{closure}}
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  12: <mz_dataflow_types::client::controller::storage::Controller<T> as mz_dataflow_types::client::controller::storage::StorageController>::append::{{closure}}
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <core::pin::Pin<P> as core::future::future::Future>::poll
  15: mz_coord::coord::Coordinator<S>::advance_local_input::{{closure}}::{{closure}}
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  17: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  18: mz_coord::coord::Coordinator<S>::advance_local_input::{{closure}}
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  20: mz_coord::coord::Coordinator<S>::serve::{{closure}}
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  22: tokio::park::thread::CachedParkThread::block_on::{{closure}}
  23: tokio::coop::with_budget::{{closure}}
  24: std::thread::local::LocalKey<T>::try_with
  25: std::thread::local::LocalKey<T>::with
  26: tokio::park::thread::CachedParkThread::block_on
  27: tokio::runtime::enter::Enter::block_on
  28: tokio::runtime::handle::Handle::block_on
  29: mz_coord::coord::serve::{{closure}}::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted
```

**Comment by danhhz** [comment]
> any errors indicating that the network connection with Postgres has been disrupted

persist could certainly add more things to the determinate whitelist (and we'll add the ones you list above, thanks for the list!), but I actually think this issue is exposing something else very useful to know. network errors in general are not determinate and retrying within persist would lead to correctness errors. persist is already retrying in literally every possible place where it wouldn't lead to a correctness error (modulo fleshing out the whitelist)

as I see it, there's two possible ways to address the remaining cases:
- storage could gracefully handle indeterminate errors instead of `expect`-ing on them
- we could make an effort to whitelist every relevant determinate error and then also do #12797 to reduce even further the number of indeterminate errors that actually bubble up to storage (to be clear, we should do this regardless). then we could see in practice if this reduces the number of panics to a level that's acceptable

both storage and persist are pretty slammed with higher priority things in the short term, so I don't suspect that much will be done here until more like the alpha or beta timeline. @philip-stoev if it's blocking your testing, i'm happy to expand the whitelist (maybe I'll do it for skunkworks this friday), but heads up that the "network connection" error will be fixed by GA but may be broken for a bit longer in the meantime

**Comment by philip-stoev** [comment]
I would like to test postgres restarts at some point, but maybe not immediately. So the  ' terminating connection due to administrator command" would the the most important error currently. Can I whitelist it myself by copying the code that does the serialization error, or that would still be risky? I guess it depends on whether the error happens within a transaction or outside of it, same as any other network error.

**Comment by philip-stoev** [comment]
This also affects the cargo test -- the error in this case is:

```
thread 'coordinator' panicked at 'cannot append updates: Indeterminate { inner: db error: ERROR: could not access status of transaction 8170\nDETAIL: Could not open file \"pg_serial/0000\": No such file or directory.\n\nCaused by:\n    ERROR: could not access status of transaction 817
```

https://buildkite.com/materialize/tests/builds/37994#018219f6-9301-424b-af95-5820e9e6ed7b

**Comment by uce** [comment]
For storage, we are fine with the availability implications of restarting. Philip has created #13872 for the parts that we do want to address.

**Comment by pH14** [comment]
Yesterday we saw a case of `ADMIN SHUTDOWN` killing `environmentd` through the storage controller: https://materializeinc.slack.com/archives/CL68GT3AT/p1658954774110619

And specifically this `compare_and_append`:

https://github.com/MaterializeInc/materialize/blob/1f9e0ec9a044f06c45a4db06d54f527765db4ff1/src/storage/src/controller.rs#L1391-L1401

On Cockroach, `AdminShutdown` is used in a few places, and we saw it when a node was draining its connections. I spent some time reading to determine whether it's determinate (in that we can be confident upon receiving that error to a write request that the write was _not_ applied), and my read is that this error is indeterminate.

From https://github.com/cockroachdb/cockroach/blob/1764aababf265bccf81307af4e068bdc8099813f/pkg/sql/pgwire/conn.go#L582-L602, CRDB will issue `AdminShutdown` after its command processor closes, and it swallows the processor's error and passes on `AdminShutdown` to the client if the node is already draining.

However the error the processor returns is specifically set to `nil` if it cleanly shutdown and finished processing its open transactions: https://github.com/cockroachdb/cockroach/blob/7c7baebf38eef2b2f104b19b81681396eab12fa9/pkg/sql/conn_executor.go#L1842-L1847

Because the error is swallowed regardless of whether it gracefully terminated or not, we do not know for certain whether or not the command was processed to completion, so `AdminShutdown` must be treated as indeterminate.

**Comment by philip-stoev** [comment]
Straight up killing and restarting the postgres container causes environmentd to panic:

```
thread 'tokio:work-1' panicked at 'cannot append updates: Indeterminate { inner: error connecting to server: failed to lookup address information: Temporary failure in name resolution

Caused by:
    failed to lookup address information: Temporary failure in name resolution

```

This is even with the connection pool already in the codebase.

**Comment by benesch** [comment]
I'm removing the **M-platform-blocker** label here. For EA, we can live with the restarts of `environmentd` if Cockroach crashes.

**Comment by aljoscha** [comment]
@bkirwi another source errors-related thing that you might be interested in.

**Comment by benesch** [comment]
I believe this has all been fixed! Frank wrote some code that allows the storage controller to retry failed writes in nearly all cases. @philip-stoev can you retest?

**Comment by aljoscha** [comment]
Closing this one because a) we no longer use Postgres as a production stash backend and b) we now retry so all these should be fixed.
