### ISSUE TITLE
test_tail_basic flakey

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#13488]
### What version of Materialize are you using?

main

### How did you install Materialize?

Built from source

### What is the issue?

Two separate crashes for this test, which is clearly flakey at this point.

Running `test_tail_basic` under `cargo stress`:

```
thread 'coordinator' panicked at 'Reference to absent collection: IdentifierMissing(User(3))', /home/mjibson/materialize/src/compute-client/src/controller.rs:594:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'coordinator unexpectedly canceled request: RecvError(())', /home/mjibson/materialize/src/adapter/src/client.rs:209:18
thread 'tokio-runtime-worker' panicked at 'coordinator unexpectedly gone: SendError(Terminate { session: Session { conn_id: 2, prepared_statements: {}, portals: {}, transaction: Default, pcx: None, user: "materialize", vars: Vars { application_name: SessionVar { default_value: "", local_value: None, staged_value: None, session_value: None, parent: ServerVar { name: UncasedStr("application_name"), value: "", description: "Sets the application name to be reported in statistics and logs (PostgreSQL)." } }, client_encoding: ServerVar { name: UncasedStr("client_encoding"), value: "UTF8", description: "Sets the client's character set encoding (PostgreSQL)." }, client_min_messages: SessionVar { default_value: Notice, local_value: None, staged_value: None, session_value: None, parent: ServerVar { name: UncasedStr("client_min_messages"), value: Notice, description: "Sets the message levels that are sent to the client (PostgreSQL)." } }, cluster: SessionVar { default_value: "default", local_value: None, staged_value: None, session_value: None, parent: ServerVar { name: UncasedStr("cluster"), value: "default", description: "Sets the current cluster (Materialize)." } }, cluster_replica: SessionVar { default_value: None, local_value: None, staged_value: None, session_value: None, parent: ServerVar { name: UncasedStr("cluster_replica"), value: None, description: "Sets a target cluster replica for SELECT queries (Materialize)." } }, database: SessionVar { default_value: "materialize", local_value: None, staged_value: None, session_value: None, parent: ServerVar { name: UncasedStr("database"), value: "materialize", description: "Sets the current database (CockroachDB)." } }, date_style: ServerVar { name: UncasedStr("DateStyle"), value: "ISO, MDY", description: "Sets the display format for date and time values (PostgreSQL)." }, extra_float_digits: SessionVar { default_value: 3, local_value: None, staged_value: None, session_value: None, parent: ServerVar { name: UncasedStr("extra_float_digits"), value: 3, description: "Adjusts the number of digits displayed for floating-point values (PostgreSQL)." } }, failpoints: ServerVar { name: UncasedStr("failpoints"), value: "", description: "Allows failpoints to be dynamically activated." }, integer_datetimes: ServerVar { name: UncasedStr("integer_datetimes"), value: true, description: "Reports whether the server uses 64-bit-integer dates and times (PostgreSQL)." }, interval_style: ServerVar { name: UncasedStr("IntervalStyle"), value: "postgres", description: "Sets the display format for interval values (PostgreSQL)." }, qgm_optimizations: SessionVar { default_value: false, local_value: None, staged_value: None, session_value: None, parent: ServerVar { name: UncasedStr("qgm_optimizations_experimental"), value: false, description: "Enables optimizations based on a Query Graph Model (QGM) query representation." } }, search_path: SessionVar { default_value: ["public"], local_value: None, staged_value: None, session_value: None, parent: ServerVar { name: UncasedStr("search_path"), value: ["public"], description: "Sets the schema search order for names that are not schema-qualified (PostgreSQL)." } }, server_version: ServerVar { name: UncasedStr("server_version"), value: "9.5.0", description: "Shows the server version (PostgreSQL)." }, server_version_num: ServerVar { name: UncasedStr("server_version_num"), value: 90500, description: "Shows the server version as an integer (PostgreSQL)." }, sql_safe_updates: SessionVar { default_value: false, local_value: None, staged_value: None, session_value: None, parent: ServerVar { name: UncasedStr("sql_safe_updates"), value: false, description: "Prohibits SQL statements that may be overly destructive (CockroachDB)." } }, standard_conforming_strings: ServerVar { name: UncasedStr("standard_conforming_strings"), value: true, description: "Causes '...' strings to treat backslashes literally (PostgreSQL)." }, statement_timeout: SessionVar { default_value: 10s, local_value: None, staged_value: None, session_value: None, parent: ServerVar { name: UncasedStr("statement_timeout"), value: 10s, description: "Sets the maximum allowed duration of INSERT...SELECT, UPDATE, and DELETE operations." } }, timezone: SessionVar { default_value: UTC, local_value: None, staged_value: None, session_value: None, parent: ServerVar { name: UncasedStr("TimeZone"), value: UTC, description: "Sets the time zone for displaying and interpreting time stamps (PostgreSQL)." } }, transaction_isolation: ServerVar { name: UncasedStr("transaction_isolation"), value: "serializable", description: "Sets the current transaction's isolation level (PostgreSQL)." } }, drop_sinks: [] } })', src/adapter/src/client.rs:608:18
thread 'test_tail_basic' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', /home/mjibson/materialize/src/ore/src/thread.rs:28:39
```

From: https://github.com/MaterializeInc/materialize/pull/13428: https://buildkite.com/materialize/tests/builds/37120#0181d4b4-0dac-4478-8d41-b24acde1eb23:

```
{"type":"test","name":"mz-environmentd::test::sql::test_tail_basic","event":"failed","exec_time":5.843426282,"stdout":"\u001b[2m2022-07-06T18:13:31.686661Z\u001b[0m \u001b[32m INFO\u001b[0m \u001b[2mmz_orchestrator_process\u001b[0m\u001b[2m:\u001b[0m Launching compute-cluster-1-replica-1: --listen-addr=127.0.0.1:2103 --internal-http-listen-addr=127.0.0.1:2115 --workers=1 --opentelemetry-resource=instance_id=1 --opentelemetry-resource=replica_id=1 localhost:2106 --process=0 --opentelemetry-resource=replica_index=0 --pid-file-location=/tmp/.tmpKiiKsV/compute-cluster-1-replica-1-0.pid --secrets-path=/tmp/.tmpKiiKsV/secrets...\n\u001b[2m2022-07-06T18:13:31.694700Z\u001b[0m \u001b[32m INFO\u001b[0m \u001b[2mmz_compute_client::controller::replicated\u001b[0m\u001b[2m:\u001b[0m Reconnecting to replica 1 failed (retrying in 2ms): transport error\n\u001b[2m2022-07-06T18:13:31.698735Z\u001b[0m \u001b[32m INFO\u001b[0m \u001b[2mmz_compute_client::controller::replicated\u001b[0m\u001b[2m:\u001b[0m Reconnecting to replica 1 failed (retrying in 4ms): transport error\n\u001b[2m2022-07-06T18:13:31.709234Z\u001b[0m \u001b[32m INFO\u001b[0m \u001b[2mmz_service::grpc\u001b[0m\u001b[2m:\u001b[0m GrpcClient http://localhost:2103: connected\n\u001b[2m2022-07-06T18:13:33.022424Z\u001b[0m \u001b[32m INFO\u001b[0m \u001b[2mmz_adapter::catalog\u001b[0m\u001b[2m:\u001b[0m create table materialize.public.t (u1)\n\u001b[2m2022-07-06T18:13:33.260559Z\u001b[0m \u001b[32m INFO\u001b[0m \u001b[2mmz_adapter::catalog\u001b[0m\u001b[2m:\u001b[0m create index materialize.public.t_primary_idx (u2)\nError: Error { kind: Db, cause: Some(DbError { severity: \"ERROR\", parsed_severity: None, code: SqlState(EXX000), message: \"Timestamp (1657131213672) is not valid for all inputs: [Antichain { elements: [1657131214344] }]\", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: None, line: None, routine: None }) }\nthread 'test_tail_basic' panicked at 'assertion failed: `(left == right)`\n  left: `1`,\n right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/test/src/lib.rs:185:5\nstack backtrace:\nnote: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\n"}
```

**Comment by mjibson** [comment]
```
thread 'coordinator' panicked at 'Reference to absent collection: IdentifierMissing(User(11))', /home/mjibson/materialize/src/compute-client/src/controller.rs:594:18
stack backtrace:
   0:     0x55a34f992cfd - std::backtrace_rs::backtrace::libunwind::trace::hb729d9642bb971eb
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55a34f992cfd - std::backtrace_rs::backtrace::trace_unsynchronized::h373bb774579df5c7
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55a34f992cfd - std::sys_common::backtrace::_print_fmt::hfbd4e92d240c89bb
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55a34f992cfd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8f618991fbf64972
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55a34f9bd35c - core::fmt::write::hc69b5b640d88cce8
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/fmt/mod.rs:1196:17
   5:     0x55a34f98ba81 - std::io::Write::write_fmt::ha26c36dcff4a27b3
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/io/mod.rs:1654:15
   6:     0x55a34f994815 - std::sys_common::backtrace::_print::h368f27cdedea0e52
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55a34f994815 - std::sys_common::backtrace::print::ha105c9cf5a64cd17
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55a34f994815 - std::panicking::default_hook::{{closure}}::h48ed2c3707d5e20e
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:295:22
   9:     0x55a34f9944c0 - std::panicking::default_hook::h8744fc5cea5e3110
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:311:9
  10:     0x55a34f994ef8 - std::panicking::rust_panic_with_hook::hc82286af2030e925
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:698:17
  11:     0x55a34f994da7 - std::panicking::begin_panic_handler::{{closure}}::h1c15057c2f09081f
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:588:13
  12:     0x55a34f9931b4 - std::sys_common::backtrace::__rust_end_short_backtrace::h65de906a5330f8da
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55a34f994ad9 - rust_begin_unwind
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
  14:     0x55a34f9ba763 - core::panicking::panic_fmt::h741cfbfc95bc6112
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
  15:     0x55a34f9baa13 - core::result::unwrap_failed::h995262f85f9c4e2c
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1785:5
  16:     0x55a34b071f72 - core::result::Result<T,E>::expect::h481294d0e0dbad4e
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1035:23
  17:     0x55a34b1ecac7 - mz_compute_client::controller::ComputeControllerMut<T>::update_write_frontiers::{{closure}}::h0ff4a5b3f73a78fe
                               at /home/mjibson/materialize/src/compute-client/src/controller.rs:592:30
  18:     0x55a34aa10da1 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h307da6c3d7e69d06
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  19:     0x55a34b030b38 - mz_controller::Controller<T>::process::{{closure}}::h67d4e796d59b095b
                               at /home/mjibson/materialize/src/controller/src/lib.rs:575:77
  20:     0x55a34aa2bbb1 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::he00741cc09f2f966
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  21:     0x55a34b1cbccd - mz_adapter::coord::Coordinator<S>::serve::{{closure}}::h6a5c4be05841720b
                               at /home/mjibson/materialize/src/adapter/src/coord.rs:1072:68
  22:     0x55a34aa320fc - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hfb743abb461b8162
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  23:     0x55a34a7a0aec - tokio::park::thread::CachedParkThread::block_on::{{closure}}::h3ffa5b2d30bbeb44
                               at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:54
  24:     0x55a34afc8f08 - tokio::coop::with_budget::{{closure}}::hece04034eb116cd6
                               at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:102:9
  25:     0x55a34a66945b - std::thread::local::LocalKey<T>::try_with::h9a30a72856e699e8
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/thread/local.rs:445:16
  26:     0x55a34a664c88 - std::thread::local::LocalKey<T>::with::h27d3e740c6165f3f
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/thread/local.rs:421:9
  27:     0x55a34a79d736 - tokio::coop::with_budget::hc824f498243eeddd
                               at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:95:5
  28:     0x55a34a79d736 - tokio::coop::budget::hfdbbfff4e4523c09
                               at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:72:5
  29:     0x55a34a79d736 - tokio::park::thread::CachedParkThread::block_on::h5ef9c228726f92a8
                               at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:31
  30:     0x55a34afe0691 - tokio::runtime::enter::Enter::block_on::h322ff5b57825d7c9
                               at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/enter.rs:151:13
  31:     0x55a34acfce43 - tokio::runtime::handle::Handle::block_on::haa9664a01950c99e
                               at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/handle.rs:296:9
  32:     0x55a34b1d6366 - mz_adapter::coord::serve::{{closure}}::{{closure}}::h7642e666f74cf239
                               at /home/mjibson/materialize/src/adapter/src/coord.rs:5998:17
  33:     0x55a34b1f3723 - std::sys_common::backtrace::__rust_begin_short_backtrace::h87e460778a134b78
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:122:18
  34:     0x55a34aa5dfd3 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h2d0a7d61c3f811e9
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/thread/mod.rs:501:17
  35:     0x55a34ac463d3 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h98f1285f6002a3de
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panic/unwind_safe.rs:271:9
  36:     0x55a34a68bb34 - std::panicking::try::do_call::h7ce14470b5f43f83
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:492:40
  37:     0x55a34a7275ab - __rust_try
  38:     0x55a34a67f7cf - std::panicking::try::hb184d7e3ffbaae09
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:456:19
  39:     0x55a34b2763f3 - std::panic::catch_unwind::hd44517862f55cd53
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panic.rs:137:14
  40:     0x55a34aa5d903 - std::thread::Builder::spawn_unchecked_::{{closure}}::h1a3eeb80e9c2d562
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/thread/mod.rs:500:30
  41:     0x55a34a7dc6f6 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h437afb6b36a2d509
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:248:5
  42:     0x55a34f99abc3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcbca3baf872b7fe4
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/alloc/src/boxed.rs:1872:9
  43:     0x55a34f99abc3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h18790338ce1743e2
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/alloc/src/boxed.rs:1872:9
  44:     0x55a34f99abc3 - std::sys::unix::thread::Thread::new::thread_start::hb1067183bad48893
                               at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys/unix/thread.rs:108:17
  45:     0x7f0b567c7ff2 - start_thread
  46:     0x7f0b5684abfc - clone3
  47:                0x0 - <unknown>
```

**Comment by mjibson** [comment]
To repro:

1. `cargo install cargo-stress`
2. `cd src/environmentd`
3. `cargo stress test_tail_basic`

**Comment by antiguru** [comment]
Trying to untangle this. The error from CI is a different error than reported by `cargo stress:
* CI: `Timestamp (1657131213672) is not valid for all inputs: [Antichain { elements: [1657131214344] }]`
* `cargo stress`: `Reference to absent collection: IdentifierMissing(User(11))`

I think the error in `cargo stress` comes from the fact that multiple concurrent tests try to run against the same `computed` process, which enters an inconsistent state. This mirrors a situation where we have multiple `environmentd` processes, which should not happen. It seems that the tail response from one test gets forwarded to another test, which is understandably confused about the response and crashes. While I think this is a bug, this is not what the ticket was originally about :)

The original error I can't reproduce and I don't think it comes from compute. Please correct me if I'm wrong. We'll use the other report as input to restructuring the command/response protocol to only reveal responses after the controller finished hydrating a connection, which should make sure that no stale responses are handed out.
