### ISSUE TITLE
regression: thread 'coordinator' panicked at 'could not step forward', src/adapter/src/coord.rs:7130:21

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#13726]
### What version of Materialize are you using?

3928c0a

### How did you install Materialize?

Docker image

### What is the issue?

Starting sometime before revision `3928c0a` the kafka-matrix test has started to fail with a panic:

https://buildkite.com/materialize/nightlies/builds/1003#018206c6-b30e-48ec-969a-0e8beca62018

```
kafka-matrix-schema-registry-1  | [2022-07-18 11:44:04,406] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
kafka-matrix-materialized-1     | thread 'coordinator' panicked at 'could not step forward', src/adapter/src/coord.rs:7130:21
kafka-matrix-materialized-1     | stack backtrace:
kafka-matrix-materialized-1     |    0: rust_begin_unwind
kafka-matrix-materialized-1     |              at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
kafka-matrix-materialized-1     |    1: core::panicking::panic_fmt
kafka-matrix-materialized-1     |              at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
kafka-matrix-materialized-1     |    2: <u64 as mz_adapter::coord::CoordTimestamp>::step_forward_by
kafka-matrix-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ca3896c2aeb6695e-1/materialize/tests/src/adapter/src/coord.rs:7130:21
kafka-matrix-materialized-1     |    3: mz_adapter::coord::timeline::DurableTimestampOracle<T>::maybe_allocate_new_timestamps::{{closure}}
kafka-matrix-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ca3896c2aeb6695e-1/materialize/tests/src/adapter/src/coord.rs:7091:42
kafka-matrix-materialized-1     |    4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
kafka-matrix-materialized-1     |              at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
kafka-matrix-materialized-1     |    5: mz_adapter::coord::timeline::DurableTimestampOracle<T>::fast_forward::{{closure}}
kafka-matrix-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ca3896c2aeb6695e-1/materialize/tests/src/adapter/src/coord.rs:7069:73
kafka-matrix-materialized-1     |    6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
kafka-matrix-materialized-1     |              at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
kafka-matrix-materialized-1     |    7: mz_adapter::coord::Coordinator<S>::message_advance_timelines::{{closure}}::{{closure}}
kafka-matrix-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ca3896c2aeb6695e-1/materialize/tests/src/adapter/src/coord.rs:1631:87
kafka-matrix-materialized-1     |    8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
kafka-matrix-materialized-1     |              at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
kafka-matrix-materialized-1     |    9: mz_adapter::coord::Coordinator<S>::message_advance_timelines::{{closure}}
kafka-matrix-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ca3896c2aeb6695e-1/materialize/tests/src/adapter/src/coord.rs:1599:5
kafka-matrix-materialized-1     |   10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
kafka-matrix-materialized-1     |              at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
kafka-matrix-materialized-1     |   11: mz_adapter::coord::Coordinator<S>::serve::{{closure}}
kafka-matrix-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ca3896c2aeb6695e-1/materialize/tests/src/adapter/src/coord.rs:1155:53
kafka-matrix-materialized-1     |   12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
kafka-matrix-materialized-1     |              at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
kafka-matrix-materialized-1     |   13: tokio::park::thread::CachedParkThread::block_on::{{closure}}
kafka-matrix-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:54
kafka-matrix-materialized-1     |   14: tokio::coop::with_budget::{{closure}}
kafka-matrix-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:102:9
kafka-matrix-materialized-1     |   15: std::thread::local::LocalKey<T>::try_with
kafka-matrix-materialized-1     |              at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/thread/local.rs:445:16
kafka-matrix-materialized-1     |   16: std::thread::local::LocalKey<T>::with
kafka-matrix-materialized-1     |              at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/thread/local.rs:421:9
kafka-matrix-materialized-1     |   17: tokio::coop::with_budget
kafka-matrix-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:95:5
kafka-matrix-materialized-1     |   18: tokio::coop::budget
kafka-matrix-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:72:5
kafka-matrix-materialized-1     |   19: tokio::park::thread::CachedParkThread::block_on
kafka-matrix-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:31
kafka-matrix-materialized-1     |   20: tokio::runtime::enter::Enter::block_on
kafka-matrix-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/enter.rs:151:13
kafka-matrix-materialized-1     |   21: tokio::runtime::handle::Handle::block_on
kafka-matrix-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/handle.rs:296:9
kafka-matrix-materialized-1     |   22: mz_adapter::coord::serve::{{closure}}::{{closure}}
kafka-matrix-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ca3896c2aeb6695e-1/materialize/tests/src/adapter/src/coord.rs:6142:17
kafka-matrix-materialized-1     | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

What the test does is run the testdrive/kafka-* tests against different Kafka releases. However, the environment apparently is not wiped out completely between the Mz restarts, so pgdata and mzdata is leaking between the cycles. So, this seems to me to be a restart/reconciliation-related bug of some sort. 

To reproduce:
1. Use a materialize revision before https://github.com/MaterializeInc/materialize/pull/13727 is merged, as it will wipe mzdata and pgdata across restarts.
2. Run
```
cd test/kafka-matrix
./mzcompose run default
```

materialized will refuse to start when the test reaches the first time it is restarted, ~15 min after the start of the test.

Unfortunately, it does not reproduce with just a couple of kafka sources, so the full test needs to be run.

**Comment by philip-stoev** [comment]
Running just `testdrive/kafka-upsert-sources.td` instead of all `kafka-*.td` tests is not sufficient to reproduce the problem. So my wild guess would be that resources are leaking across the `DROP DATABASE materialize`, so stuff accumulates in mzdata/postgres . Could this cause some operation to take more than 1 second at mz startup time?
