### ISSUE TITLE
coordinator panicked in cloud

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#13768]
Observed the following crash in Materialize:

```
2022-07-21T13:16:27.573259Z  INFO mz_adapter::catalog: create secret materialize.public.registry_ca_cert (u107)
2022-07-21T13:17:21.010398Z ERROR mz_environmentd::tcp_connection: error handling connection in http server: connection closed before message completed
2022-07-21T13:22:11.889459Z  INFO mz_adapter::catalog: drop secret materialize.public.registry_username (u105)
2022-07-21T13:22:15.521927Z  INFO mz_adapter::catalog: drop secret materialize.public.registry_password (u106)
2022-07-21T13:22:22.939294Z  INFO mz_adapter::catalog: drop secret materialize.public.registry_ca_cert (u107)
2022-07-21T13:22:37.494914Z  INFO mz_compute_client::controller::replicated: gracefully stopping replica task for 6
thread 'coordinator' panicked at 'no entry found for key', src/adapter/src/catalog.rs:251:10
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/option.rs:1854:5
   5: core::option::Option<T>::expect
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/option.rs:718:21
   6: <alloc::collections::btree::map::BTreeMap<K,V> as core::ops::index::Index<&Q>>::index
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/alloc/src/collections/btree/map.rs:2056:9
   7: mz_adapter::catalog::CatalogState::get_entry
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-05861050ebb44e9e9-1/materialize/tests/src/adapter/src/catalog.rs:251:10
   8: mz_adapter::catalog::CatalogState::get_indexes_on
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-05861050ebb44e9e9-1/materialize/tests/src/adapter/src/catalog.rs:327:9
   9: mz_adapter::coord::indexes::ComputeInstanceIndexOracle<T>::indexes_on
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-05861050ebb44e9e9-1/materialize/tests/src/adapter/src/coord/indexes.rs:100:9
  10: mz_adapter::coord::indexes::ComputeInstanceIndexOracle<T>::sufficient_collections
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-05861050ebb44e9e9-1/materialize/tests/src/adapter/src/coord/indexes.rs:68:41
  11: mz_adapter::coord::Coordinator<S>::timedomain_for
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-05861050ebb44e9e9-1/materialize/tests/src/adapter/src/coord.rs:3884:49
  12: mz_adapter::coord::Coordinator<S>::sequence_peek::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-05861050ebb44e9e9-1/materialize/tests/src/adapter/src/coord.rs:4034:25
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  14: mz_adapter::coord::Coordinator<S>::sequence_peek::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-05861050ebb44e9e9-1/materialize/tests/src/adapter/src/coord.rs:3919:5
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  16: mz_adapter::coord::Coordinator<S>::sequence_plan::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-05861050ebb44e9e9-1/materialize/tests/src/adapter/src/coord.rs:2529:63
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  18: mz_adapter::coord::Coordinator<S>::sequence_plan::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-05861050ebb44e9e9-1/materialize/tests/src/adapter/src/coord.rs:2381:5
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  20: mz_adapter::coord::Coordinator<S>::handle_execute_inner::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-05861050ebb44e9e9-1/materialize/tests/src/adapter/src/coord.rs:2221:78
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  22: mz_adapter::coord::Coordinator<S>::handle_execute_inner::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-05861050ebb44e9e9-1/materialize/tests/src/adapter/src/coord.rs:2046:5
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  24: mz_adapter::coord::Coordinator<S>::handle_execute::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-05861050ebb44e9e9-1/materialize/tests/src/adapter/src/coord.rs:2043:61
  25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  26: mz_adapter::coord::Coordinator<S>::handle_execute::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-05861050ebb44e9e9-1/materialize/tests/src/adapter/src/coord.rs:2023:5
  27: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  28: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.35/src/instrument.rs:272:9
  29: mz_adapter::coord::Coordinator<S>::message_command::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-05861050ebb44e9e9-1/materialize/tests/src/adapter/src/coord.rs:1789:38
  30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  31: mz_adapter::coord::Coordinator<S>::message_command::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-05861050ebb44e9e9-1/materialize/tests/src/adapter/src/coord.rs:1705:5
  32: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  33: mz_adapter::coord::Coordinator<S>::serve::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-05861050ebb44e9e9-1/materialize/tests/src/adapter/src/coord.rs:1127:67
  34: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  35: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:54
  36: tokio::coop::with_budget::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:102:9
  37: std::thread::local::LocalKey<T>::try_with
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/thread/local.rs:445:16
  38: std::thread::local::LocalKey<T>::with
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/thread/local.rs:421:9
  39: tokio::coop::with_budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:95:5
  40: tokio::coop::budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:72:5
  41: tokio::park::thread::CachedParkThread::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:31
  42: tokio::runtime::enter::Enter::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/enter.rs:151:13
  43: tokio::runtime::handle::Handle::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/handle.rs:296:9
  44: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-05861050ebb44e9e9-1/materialize/tests/src/adapter/src/coord.rs:6184:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Stream closed EOF for environment-01d730c7-5a61-4d7a-9f3c-63ed01f34ebf-0/environmentd-0 (environmentd)
```

Possibly related to the `SHOW SCHEMAS` command that @ruf-io was running at the time—or it could have been a different user doing something at the same time.

Slack context: https://materializeinc.slack.com/archives/CU7ELJ6E9/p1658409983999809

Assigning to @JLDLaughlin for context.

**Comment by benesch** [comment]
This looks a lot like #12760.

**Comment by benesch** [comment]
I'm going to close this in favor of https://github.com/MaterializeInc/materialize/issues/12760, as we have a repro for that issue but not for this one.
