### ISSUE TITLE
Dropping cluster (with `CASCADE`) sometimes causes environmentd to crash

### ISSUE THREAD

**Issue by brennanvincent** [MaterializeInc/materialize#13857]
### What version of Materialize are you using?

unstable-d5cddec91fdd0088783aa2231bb53cd5c78b2efa

### How did you install Materialize?

Materialize Cloud

### What is the issue?

See title.

Seems more likely to happen if the cluster has more replicas, but I haven't verified this.

### Relevant log output

```source
2022-07-25T17:00:21.320303Z  INFO mz_compute_client::controller::replicated: gracefully stopping replica task for 1
2022-07-25T17:00:21.376376Z  INFO mz_compute_client::controller::replicated: gracefully stopping replica task for 3
thread 'coordinator' panicked at 'called `Option::unwrap()` on a `None` value', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0aa935a20439dd293-1/materialize/tests/src/adapter/src/coord/read_policy.rs:299:78
stack backtrace:
2022-07-25T17:00:22.767622Z  WARN mz_compute_client::controller::replicated: error connecting to replica 4, retrying in 32s: transport error
   0: rust_begin_unwind
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/option.rs:755:21
   4: mz_adapter::coord::read_policy::<impl mz_adapter::coord::Coordinator<S>>::update_read_hold::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0aa935a20439dd293-1/materialize/tests/src/adapter/src/coord/read_policy.rs:299:31
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
   6: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_advance_timelines::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0aa935a20439dd293-1/materialize/tests/src/adapter/src/coord/message_handler.rs:332:72
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
   8: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_advance_timelines::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0aa935a20439dd293-1/materialize/tests/src/adapter/src/coord/message_handler.rs:297:5
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  10: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_message::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0aa935a20439dd293-1/materialize/tests/src/adapter/src/coord/message_handler.rs:49:49
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  12: mz_adapter::coord::Coordinator<S>::serve::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0aa935a20439dd293-1/materialize/tests/src/adapter/src/coord.rs:707:37
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/future/mod.rs:91:19
  14: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:54
  15: tokio::coop::with_budget::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:102:9
  16: std::thread::local::LocalKey<T>::try_with
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/thread/local.rs:445:16
  17: std::thread::local::LocalKey<T>::with
             at ./rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/thread/local.rs:421:9
  18: tokio::coop::with_budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:95:5
  19: tokio::coop::budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:72:5
  20: tokio::park::thread::CachedParkThread::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:31
  21: tokio::runtime::enter::Enter::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/enter.rs:151:13
  22: tokio::runtime::handle::Handle::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/handle.rs:296:9
  23: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0aa935a20439dd293-1/materialize/tests/src/adapter/src/coord.rs:856:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Stream closed EOF for environment-b2f1d2b8-16e8-40fc-9872-a8f32f8cbed0-0/environmentd-0 (environmentd)
```

**Comment by benesch** [comment]
This looks sort of similar to #12355.

**Comment by jkosh44** [comment]
The Coordinator maintains a read hold on all objects at the current global timestamp. Periodically the Coordinator will update all of these read holds. This error is happening during those updates.

It seems likely that we are not removing the cluster from the Coordinator's state when it's deleted, so when we try and update the read holds on that cluster it panics. I'll take a look today.

**Comment by jkosh44** [comment]
Ahh, I see the issue. when we drop the cluster we never drop the introspection source indexes. So then we try and update the read holds on the introspection source indexes and panic because the cluster is gone. 

Are introspection source indexes maintained in the catalog anywhere?
