### ISSUE TITLE
K8s is unable to bring back a crashed compute cluster with 16 nodes (size 4xlarge)

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#14301]
### What version of Materialize are you using?

7daf5ae1431fe85ba3f497aa6adc05c4327923fe

### How did you install Materialize?

Docker image

### What is the issue?

If all nodes in a cluster with 16 nodes are killed, K8s is unable to bring them up. All nodes end up crash-looping independently and there is no moment in which they are all up and can form a stable cluster. The `kubectl get all` report looks like this:

```
pstoev@Ubuntu-2004-focal-64-minimal:~/philip-stoev-cloudtest-shared-fate$ kubectl get all
NAME                                   READY   STATUS             RESTARTS        AGE
pod/compute-cluster-1-replica-1-0      1/1     Running            0               24m
pod/compute-cluster-2-replica-2-0      1/1     Running            7 (9m37s ago)   24m
pod/compute-cluster-2-replica-2-1      1/1     Running            7 (9m37s ago)   24m
pod/compute-cluster-2-replica-2-10     0/1     CrashLoopBackOff   6 (4m20s ago)   24m
pod/compute-cluster-2-replica-2-11     0/1     CrashLoopBackOff   6 (4m20s ago)   24m
pod/compute-cluster-2-replica-2-12     0/1     CrashLoopBackOff   7 (4m19s ago)   24m
pod/compute-cluster-2-replica-2-13     0/1     CrashLoopBackOff   7 (4m19s ago)   24m
pod/compute-cluster-2-replica-2-14     0/1     CrashLoopBackOff   7 (4m19s ago)   24m
pod/compute-cluster-2-replica-2-15     0/1     CrashLoopBackOff   7 (4m19s ago)   24m
pod/compute-cluster-2-replica-2-2      1/1     Running            7 (9m37s ago)   24m
pod/compute-cluster-2-replica-2-3      1/1     Running            7 (9m37s ago)   24m
pod/compute-cluster-2-replica-2-4      0/1     CrashLoopBackOff   6 (4m21s ago)   24m
pod/compute-cluster-2-replica-2-5      0/1     CrashLoopBackOff   6 (4m21s ago)   24m
pod/compute-cluster-2-replica-2-6      0/1     CrashLoopBackOff   6 (4m20s ago)   24m
pod/compute-cluster-2-replica-2-7      0/1     CrashLoopBackOff   6 (4m20s ago)   24m
pod/compute-cluster-2-replica-2-8      0/1     CrashLoopBackOff   6 (4m21s ago)   24m
pod/compute-cluster-2-replica-2-9      0/1     CrashLoopBackOff   6 (4m21s ago)   24m
pod/environmentd-0                     1/1     Running            0               24m
...
```

### Relevant log output

```source
thread 'timely:recv-12' panicked at 'assertion failed: read > 0', /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ee65cdc/communication/src/allocator/zero_copy/tcp.rs:67:9
stack backtrace:
thread 'thread 'timely:recv-14' panicked at 'assertion failed: read > 0timely:recv-13', ' panicked at '/cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ee65cdc/communication/src/allocator/zero_copy/tcp.rsassertion failed: read > 0:', 67/cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ee65cdc/communication/src/allocator/zero_copy/tcp.rs::thread '967
timely:recv-15:9' panicked at '
assertion failed: read > 0', /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ee65cdc/communication/src/allocator/zero_copy/tcp.rs:67:9
   0: rust_begin_unwind
             at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:48:5
   3: timely_communication::allocator::zero_copy::tcp::recv_loop
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ee65cdc/communication/src/allocator/zero_copy/tcp.rs:67:9
   4: timely_communication::allocator::zero_copy::initialize::initialize_networking_from_sockets::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/ee65cdc/communication/src/allocator/zero_copy/initialize.rs:120:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by philip-stoev** [comment]
To reproduce, take https://github.com/MaterializeInc/materialize/pull/14302 and then use the setup instructions from `doc/developer/cloudtest.py` to get a KinD environment up and running. Then run this test:

```
cd test/cloudtest
kubectl --context kind-kind delete all --all  ; ./pytest -k test_kill_all_computeds
```

The test will hang here:

```
> INSERT INTO t1 SELECT 345000 + generate_series FROM generate_series(1, 1000);
rows match; continuing at ts 1660908028.5447602
Ingesting data into Kafka topic testdrive-shared-fate-1 with repeat 1000
> SELECT COUNT(*) FROM t1;
```

and time out. Use `kubectl get all` to observe that the computed containers are crash-looping with no end in sight.

**Comment by benesch** [comment]
As mentioned on Slack, I believe this is expected behavior until #13141 gets fixed. Thanks very much for the repro! That'll make it so much easier to get this done.

**Comment by philip-stoev** [comment]
When fixed, please enable the scenarios in test/cloudtest/computed_shared_fate.py
