### ISSUE TITLE
Killing the Kafka sink can cause it to hang

### ISSUE THREAD

**Issue by bkirwi** [MaterializeInc/materialize#14555]
### What version of Materialize are you using?

0.26.1-dev

### How did you install Materialize?

Built from source

### What is the issue?

Repeatedly killing the `storaged` process responsible for a Kafka sink can eventually cause it to enter a state where it will never be able to recover, instead panicking with the error `cannot serve requested as_of: Since(Antichain { elements: [<timestamp>] })`.

I'm not sure how to interpret this one, but it seems like we may be advancing the `since` of the sunk collection faster than is safe.

This has been fairly straightforward for me to reproduce; while running `bin/environmentd` locally, set up a sink in one terminal:

```
materialize=> create table t (a int);
CREATE TABLE
materialize=> create connection k for kafka broker 'localhost:9092';
CREATE CONNECTION
materialize=> create connection csr for confluent schema registry url 'http://localhost:8081';
CREATE CONNECTION
materialize=> create sink s from t into kafka connection k topic 'troublesome-out' format avro using confluent schema registry connection csr;
CREATE SINK
```

And run `watch --interval 10 -- killall -9 storaged` in another. I've usually started seeing errors as above within a few minutes.

### Relevant log output

```source
thread 'timely:work-0' panicked at 'cannot serve requested as_of: Since(Antichain { elements: [1661978565789] })', src/storage/src/source/persist_source.rs:126:24
stack backtrace:
   0:        0x108ccd2e0 - std::backtrace_rs::backtrace::libunwind::trace::hd589abd6c35ac4ad
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x108ccd2e0 - std::backtrace_rs::backtrace::trace_unsynchronized::h98ffcaaa5ca3fa1b
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x108ccd2e0 - std::sys_common::backtrace::_print_fmt::h6d737d3ee2f9b02c
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:66:5
   3:        0x108ccd2e0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h188b7ef1c7993e78
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:45:22
   4:        0x108cee13c - core::fmt::write::he84a3004e7af3f34
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/fmt/mod.rs:1197:17
   5:        0x108cc6444 - std::io::Write::write_fmt::h9370b50affaab0be
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/io/mod.rs:1672:15
   6:        0x108cceef8 - std::sys_common::backtrace::_print::h6a312acaf6239500
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:48:5
   7:        0x108cceef8 - std::sys_common::backtrace::print::h8d70f4e1fc358fa6
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:35:9
   8:        0x108cceef8 - std::panicking::default_hook::{{closure}}::hc074f8023cce83ca
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:295:22
   9:        0x108ccec60 - std::panicking::default_hook::hef854b51b9b79ff2
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:314:9
  10:        0x1080ce5d4 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hfe833e8674806f28
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1965:9
  11:        0x1080c5cf4 - mz_ore::panic::set_abort_on_panic::{{closure}}::h5b2197b5f3156ca7
                               at /Users/bkirwi/Code/materialize/src/ore/src/panic.rs:41:9
  12:        0x108ccf42c - std::panicking::rust_panic_with_hook::h1e59e224d558a492
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:702:17
  13:        0x108ccf2c4 - std::panicking::begin_panic_handler::{{closure}}::he1a9d6ab32bfd8c6
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:588:13
  14:        0x108ccd7bc - std::sys_common::backtrace::__rust_end_short_backtrace::he9b94791b02f48cd
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
  15:        0x108ccf01c - rust_begin_unwind
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
  16:        0x108d67ff4 - core::panicking::panic_fmt::h9fec86f6a9c4146e
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
  17:        0x108d68098 - core::result::unwrap_failed::h04f08301b97a771c
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
  18:        0x105c79cec - core::result::Result<T,E>::expect::h9fd5f47a59c7aff9
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1055:23
  19:        0x105de17f0 - mz_storage::source::persist_source::persist_source_core::{{closure}}::hf3b66185ca79a45c
                               at /Users/bkirwi/.cargo/registry/src/github.com-1ecc6299db9ec823/async-stream-0.3.3/src/lib.rs:237:9
  20:        0x1055eb5f8 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h49dda98800dc9edf
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  21:        0x1057afcf0 - <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next::heeb50fc0c7cb9d83
                               at /Users/bkirwi/.cargo/registry/src/github.com-1ecc6299db9ec823/async-stream-0.3.3/src/async_stream.rs:53:17
  22:        0x105dd9580 - mz_storage::source::persist_source::persist_source_core::{{closure}}::{{closure}}::h076c63824f04ffa0
                               at /Users/bkirwi/Code/materialize/src/storage/src/source/persist_source.rs:174:47
  23:        0x105ddcd84 - mz_storage::source::util::source::{{closure}}::{{closure}}::h575e6cfaeb45d688
                               at /Users/bkirwi/Code/materialize/src/storage/src/source/util.rs:103:17
  24:        0x105770e00 - timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}::h80f5d377703600f5
                               at /Users/bkirwi/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/dataflow/operators/generic/builder_rc.rs:123:31
  25:        0x105749388 - timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}::h60408e4bdde21dca
                               at /Users/bkirwi/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/dataflow/operators/generic/builder_rc.rs:162:26
  26:        0x105cd952c - <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule::h043a44779349b044
                               at /Users/bkirwi/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/dataflow/operators/generic/builder_raw.rs:204:9
  27:        0x1057762f8 - timely::progress::subgraph::PerOperatorState<T>::schedule::hbfac6483a07eef79
                               at /Users/bkirwi/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/progress/subgraph.rs:684:30
  28:        0x105776938 - timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child::hc37dc48b43e1a278
                               at /Users/bkirwi/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/progress/subgraph.rs:344:26
  29:        0x105637b28 - <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule::h291ee8054f3d9615
                               at /Users/bkirwi/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/progress/subgraph.rs:310:17
  30:        0x1057762f8 - timely::progress::subgraph::PerOperatorState<T>::schedule::hbfac6483a07eef79
                               at /Users/bkirwi/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/progress/subgraph.rs:684:30
  31:        0x105776c0c - timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child::hd52587bf81ac29ec
                               at /Users/bkirwi/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/progress/subgraph.rs:344:26
  32:        0x10563783c - <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule::h011e7951a06f9e21
                               at /Users/bkirwi/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/progress/subgraph.rs:310:17
  33:        0x107a94f48 - timely::worker::Wrapper::step::{{closure}}::hddc77fff3d99b573
                               at /Users/bkirwi/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/worker.rs:754:57
  34:        0x107a8baac - core::option::Option<T>::map::hd84e7626ac77b308
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/option.rs:929:29
  35:        0x107a94db0 - timely::worker::Wrapper::step::h29440acc1324bddf
                               at /Users/bkirwi/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/worker.rs:754:26
  36:        0x1058a5380 - timely::worker::Worker<A>::step_or_park::hdda1a477474dd9e9
                               at /Users/bkirwi/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/worker.rs:396:38
  37:        0x105ddd48c - mz_storage::storage_state::Worker<A>::run_client::h2f489400490a89b0
                               at /Users/bkirwi/Code/materialize/src/storage/src/storage_state.rs:134:17
  38:        0x105ddd3a0 - mz_storage::storage_state::Worker<A>::run::hd539e68824e9d663
                               at /Users/bkirwi/Code/materialize/src/storage/src/storage_state.rs:110:33
  39:        0x105c48c48 - mz_storage::protocol::server::serve::{{closure}}::h6e2b3eb8a5f0777f
                               at /Users/bkirwi/Code/materialize/src/storage/src/protocol/server.rs:94:9
  40:        0x105ffae04 - timely::execute::execute::{{closure}}::he0eb42648224fdfd
                               at /Users/bkirwi/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/timely/src/execute.rs:287:22
  41:        0x105a62734 - timely_communication::initialize::initialize_from::{{closure}}::hdd18f28bb9766c96
                               at /Users/bkirwi/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/1f3a315/communication/src/initialize.rs:316:33
  42:        0x105a62e80 - std::sys_common::backtrace::__rust_begin_short_backtrace::hca320d9602658ea1
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:122:18
  43:        0x105d38138 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::hde06c312e739bf85
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/mod.rs:505:17
  44:        0x1051448a8 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h8d5a8b77a15b2ecb
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panic/unwind_safe.rs:271:9
  45:        0x105080760 - std::panicking::try::do_call::ha0cf379ff3f9511e
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
  46:        0x10513aec4 - ___rust_try
  47:        0x105062238 - std::panicking::try::h1eb79f9119176dfb
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
  48:        0x105d2b68c - std::panic::catch_unwind::h40adccb362e21046
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
  49:        0x105d37d14 - std::thread::Builder::spawn_unchecked_::{{closure}}::hc7a3aadcf26d57ff
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/mod.rs:504:30
  50:        0x1058d6d4c - core::ops::function::FnOnce::call_once{{vtable.shim}}::he733031d8214c116
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
  51:        0x108cd40d0 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h89934fef96b83268
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1951:9
  52:        0x108cd40d0 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2c579033340f7d2e
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1951:9
  53:        0x108cd40d0 - std::sys::unix::thread::Thread::new::thread_start::h7b2f9b83fb320a20
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys/unix/thread.rs:108:17
  54:        0x1b996026c - __pthread_deallocate
```

**Comment by benesch** [comment]
Looks very similar to https://github.com/MaterializeInc/materialize/issues/12885#issuecomment-1232726890!

**Comment by aljoscha** [comment]
Might be that there's something fishy with the logic that is holding back compaction (aka the `since`) of the sinked (sunk?) storage collection.

**Comment by bkirwi** [comment]
@cjubb39 and I were chatting through this this morning and have a theory.

The sink chooses its as-of based on a description it receives from the controller. However, this description is cached in the rehydrating storage client, and not updated as the sink makes progress and advances its frontier. Thus - a restarting storaged will be instructed to resume from a timestamp that may be quite old. This is normally ~fine, since the sink will filter out messages that are older than the timestamp it finds in the progress topic... but if it's old enough that persist no longer has the data for it, we'll get an as-of error and storaged will be unable to come back up until environmentd restarts.

We should be able to verify this by looking at the timestamp passed to storaged over grpc, and confirm it's the same one persist complains about. (And that either restarting environmentd fixes things, or that there's some other layer of caching happening somewhere.)

**Comment by cjubb39** [comment]
I'm investigating fixing this in #14785 (currently still in draft mode!)
