### ISSUE TITLE
persist: assertion failure in compaction

### ISSUE THREAD

**Issue by danhhz** [MaterializeInc/materialize#14670]
### What version of Materialize are you using?

v0.27.0-alpha.18

### How did you install Materialize?

Materialize Cloud

### What is the issue?

```
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.len() >= res.output.len', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-032b93d6d7c8edfec-1/materialize/tests/src/persist-client/src/internal/trace.rs:331:9
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:48:5
   3: mz_persist_client::internal::trace::SpineBatch<T>::maybe_replace
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-032b93d6d7c8edfec-1/materialize/tests/src/persist-client/src/internal/trace.rs:331:9
   4: mz_persist_client::internal::trace::Trace<T>::apply_merge_res
   5: mz_persist_client::internal::state::StateCollections<T>::apply_merge_res
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-032b93d6d7c8edfec-1/materialize/tests/src/persist-client/src/internal/state.rs:250:23
   6: mz_persist_client::internal::machine::Machine<K,V,T,D>::merge_res::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-032b93d6d7c8edfec-1/materialize/tests/src/persist-client/src/internal/machine.rs:304:27
   7: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:290:13
   8: mz_persist_client::internal::state::State<K,V,T,D>::clone_apply
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-032b93d6d7c8edfec-1/materialize/tests/src/persist-client/src/internal/state.rs:557:24
   9: mz_persist_client::internal::machine::Machine<K,V,T,D>::apply_unbatched_cmd::{{closure}}::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-032b93d6d7c8edfec-1/materialize/tests/src/persist-client/src/internal/machine.rs:525:55
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  11: mz_persist_client::internal::metrics::CmdMetrics::run_cmd::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-032b93d6d7c8edfec-1/materialize/tests/src/persist-client/src/internal/metrics.rs:396:74
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  13: mz_persist_client::internal::machine::Machine<K,V,T,D>::apply_unbatched_cmd::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-032b93d6d7c8edfec-1/materialize/tests/src/persist-client/src/internal/machine.rs:669:11
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  15: mz_persist_client::internal::machine::Machine<K,V,T,D>::apply_unbatched_idempotent_cmd::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-032b93d6d7c8edfec-1/materialize/tests/src/persist-client/src/internal/machine.rs:493:62
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  17: mz_persist_client::internal::machine::Machine<K,V,T,D>::merge_res::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-032b93d6d7c8edfec-1/materialize/tests/src/persist-client/src/internal/machine.rs:309:15
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  19: mz_persist_client::internal::compact::Compactor::compact_and_apply_background::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-032b93d6d7c8edfec-1/materialize/tests/src/persist-client/src/internal/compact.rs:156:54
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  21: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
  22: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:165:17
  23: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/loom/std/unsafe_cell.rs:14:9
  24: tokio::runtime::task::core::CoreStage<T>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:155:13
  25: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:470:19
  26: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panic/unwind_safe.rs:271:9
  27: std::panicking::try::do_call
             at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
  28: std::panicking::try
             at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
  29: std::panic::catch_unwind
             at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
  30: tokio::runtime::task::harness::poll_future
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:458:18
  31: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:104:27
  32: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:57:15
  33: tokio::runtime::task::raw::RawTask::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/raw.rs:84:18
  34: tokio::runtime::task::LocalNotified<S>::run
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/mod.rs:376:9
  35: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:458:21
  36: tokio::coop::with_budget::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:102:9
  37: std::thread::local::LocalKey<T>::try_with
             at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/local.rs:445:16
  38: std::thread::local::LocalKey<T>::with
             at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/local.rs:421:9
  39: tokio::coop::with_budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:95:5
  40: tokio::coop::budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:72:5
  41: tokio::runtime::thread_pool::worker::Context::run_task
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:434:9
  42: tokio::runtime::thread_pool::worker::Context::run
  43: tokio::runtime::thread_pool::worker::run::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:386:17
  44: tokio::macros::scoped_tls::ScopedKey<T>::set
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/macros/scoped_tls.rs:61:9
  45: tokio::runtime::thread_pool::worker::run
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:383:5
  46: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:362:45
  47: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/task.rs:42:21
  48: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:165:17
  49: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/loom/std/unsafe_cell.rs:14:9
  50: tokio::runtime::task::core::CoreStage<T>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:155:13
  51: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:470:19
  52: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panic/unwind_safe.rs:271:9
  53: std::panicking::try::do_call
             at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
  54: std::panicking::try
             at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
  55: std::panic::catch_unwind
             at ./rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
  56: tokio::runtime::task::harness::poll_future
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:458:18
  57: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:104:27
  58: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:57:15
  59: tokio::runtime::task::raw::RawTask::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/raw.rs:84:18
  60: tokio::runtime::task::UnownedTask<S>::run
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/mod.rs:413:9
  61: tokio::runtime::blocking::pool::Task::run
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/pool.rs:91:9
  62: tokio::runtime::blocking::pool::Inner::run
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/pool.rs:325:17
  63: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/pool.rs:300:13
```

**Comment by danhhz** [comment]
@pH14 you said you had a maelstrom repro of this?

**Comment by pH14** [comment]
Yes, I've seen this before doing a longer Maelstrom run. Thought I made an issue for it, but must have forgotten, whoops! The invocation was:

```
RUST_BACKTRACE=1 cargo build -p mz-persist-client --example persistcli --release && java -Djava.awt.headless=true -jar /path/to/maelstrom-0.2.2-SNAPSHOT-standalone.jar test -w txn-list-append --bin ./target/release/examples/persistcli --rate=300 --time-limit=1200 --node-count=1 --concurrency=2 --log-stderr -- maelstrom --consensus-uri='mem://'consensus --blob-uri='mem://'blob --unreliability 0.1
```

**Comment by pH14** [comment]
Been looking into this one and have run a few hours of Maelstrom using my previous invocation and... no panics. Our recent nightly Maelstrom runs, which also have some longer tests now, have also all looked good.

I searched over our logs in Honeycomb for this error, and we haven't seen it since the 20th (and the 21st we did a release):

<img width="1125" alt="Screen Shot 2022-09-29 at 3 15 32 PM" src="https://user-images.githubusercontent.com/785446/193122328-8a4d4f0c-b24a-4bf8-8bf6-768e6c5e9f54.png">

While there's been a fair bit of code upheaval, this one is a bit spooky to me since the core idea of compaction hasn't changed since the issue was first seen. Without fully understanding how the error could occur, I also don't have a clear idea why it _shouldn't_ occur now. That said, the release on the 21st did contain bounded memory compaction, so it's possible enough pieces moved where this bug is less likely, or no longer possible.

I've added a trigger to Honeycomb to alert us if this error pops up again, and if we don't see it for a while we can close this issue out.

**Comment by aljoscha** [comment]
👻

**Comment by pH14** [comment]
This one still has not reoccurred. I'm keeping our Honeycomb alert for it up, and we can revisit this issue if it does come back

**Comment by pH14** [comment]
https://github.com/MaterializeInc/materialize/issues/15498
