### ISSUE TITLE
Nightly Tests Instance size limits broken

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#14925]
### What version of Materialize are you using?

`main`

### How did you install Materialize?

Docker image

### What is the issue?

The nightly test "Instance size limits" is no longer passing: https://buildkite.com/materialize/nightlies/builds/1181#018361fe-39be-4b68-a7e6-671227ac85ab

### Relevant log output

```source
> CREATE CLUSTER cluster_0 REPLICAS (replica_0_0 (REMOTE ['computed_0_0_0:2100', 'computed_0_0_1:2100', 'computed_0_0_2:2100', 'computed_0_0_3:2100'] COMPUTE ['computed_0_0_0:2100', 'computed_0_0_1:2100', 'computed_0_0_2:2100', 'computed_0_0_3:2100'] WORKERS 2),replica_0_1 (REMOTE ['computed_0_1_0:2100', 'computed_0_1_1:2100', 'computed_0_1_2:2100', 'computed_0_1_3:2100'] COMPUTE ['computed_0_1_0:2100', 'computed_0_1_1:2100', 'computed_0_1_2:2100', 'computed_0_1_3:2100'] WORKERS 2),replica_0_2 (REMOTE ['computed_0_2_0:2100', 'computed_0_2_1:2100', 'computed_0_2_2:2100', 'computed_0_2_3:2100'] COMPUTE ['computed_0_2_0:2100', 'computed_0_2_1:2100', 'computed_0_2_2:2100', 'computed_0_2_3:2100'] WORKERS 2),replica_0_3 (REMOTE ['computed_0_3_0:2100', 'computed_0_3_1:2100', 'computed_0_3_2:2100', 'computed_0_3_3:2100'] COMPUTE ['computed_0_3_0:2100', 'computed_0_3_1:2100', 'computed_0_3_2:2100', 'computed_0_3_3:2100'] WORKERS 2))
mzcompose: test case workflow-instance-size failed:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pg8000/legacy.py", line 251, in execute
    self._context = self._c.execute_simple(operation)
  File "/usr/local/lib/python3.10/dist-packages/pg8000/core.py", line 659, in execute_simple
    self.handle_messages(context)
  File "/usr/local/lib/python3.10/dist-packages/pg8000/core.py", line 813, in handle_messages
    raise context.error
pg8000.exceptions.DatabaseError: {'S': 'ERROR', 'C': '42601', 'M': 'Expected right parenthesis, found COMPUTE', 'P': '149'}
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-055a6a674762d02e3-1/materialize/nightlies/misc/python/materialize/mzcompose/__init__.py", line 381, in test_case
    yield
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-055a6a674762d02e3-1/materialize/nightlies/misc/python/materialize/cli/mzcompose.py", line 578, in handle_composition
    composition.workflow(args.workflow, *args.unknown_subargs[1:])
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-055a6a674762d02e3-1/materialize/nightlies/misc/python/materialize/mzcompose/__init__.py", line 293, in workflow
    func(self, parser)
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-055a6a674762d02e3-1/materialize/nightlies/test/limits/mzcompose.py", line 1383, in workflow_instance_size
    c.sql(
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-055a6a674762d02e3-1/materialize/nightlies/misc/python/materialize/mzcompose/__init__.py", line 420, in sql
    cursor.execute(statement)
  File "/usr/local/lib/python3.10/dist-packages/pg8000/legacy.py", line 281, in execute
    raise cls(msg)
pg8000.dbapi.ProgrammingError: {'S': 'ERROR', 'C': '42601', 'M': 'Expected right parenthesis, found COMPUTE', 'P': '149'}
==> Uploading report for suite 'mzcompose' to Buildkite Test Analytics
202 {'id': 'b9de79ae-ebfe-4b11-bf9c-37e1ac52fd52', 'run_id': 'bcc64f3b-d2e2-4f9f-ba90-09d21aa4ba78', 'queued': 1, 'skipped': 0, 'errors': [], 'run_url': 'https://buildkite.com/organizations/materialize/analytics/suites/mzcompose/runs/bcc64f3b-d2e2-4f9f-ba90-09d21aa4ba78'}
mzcompose: error: at least one test case failed
🚨 Error: The command exited with status 1
user command error: The plugin mzcompose command hook exited with status 1
```

**Comment by teskje** [comment]
Looks like that needs to be adjusted to the syntax change from https://github.com/MaterializeInc/materialize/pull/14379. @lluki can you take a look?

**Comment by philip-stoev** [comment]
Yes thanks, the "unexpected input line" is on @jkosh44 will ping him directly.
