### ISSUE TITLE
Panic on partial CREATE SOURCE

### ISSUE THREAD

**Issue by andrioni** [MaterializeInc/materialize#14946]
### What version of Materialize are you using?

 v0.27.0-alpha.22 (6ce2caea5)

### How did you install Materialize?

Materialize Cloud

### What is the issue?

When trying to create a source with a partial set of parameters, `environmentd` panics:

```sql
CREATE SECRET pw AS 'irrelevant';

CREATE CONNECTION redpanda_connection
  FOR KAFKA
    BROKER '0.rp-b65262e.data.vectorized.cloud:30365',
    SASL MECHANISMS = 'SCRAM-SHA-256',
    SASL USERNAME = 'irrelevant',
    SASL PASSWORD = SECRET pw,
    SSL CERTIFICATE AUTHORITY = 'irrelevant';

CREATE SOURCE panic_source
FROM KAFKA CONNECTION redpanda_connection;

-- Panic here, logs below
```

### Relevant log output

```source
thread 'tokio:work-0' panicked at 'validated topic exists', /Users/alessandro/workspace/mz/materialize/src/sql/src/pure.rs:106:49
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/option.rs:1874:5
   5: core::option::Option<T>::expect
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/option.rs:738:21
   6: mz_sql::pure::purify_create_source::{{closure}}
             at ./src/sql/src/pure.rs:106:25
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
   8: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute_inner::{{closure}}::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:415:44
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/mod.rs:91:19
  10: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/future/future.rs:124:9
  11: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:165:17
  12: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/loom/std/unsafe_cell.rs:14:9
  13: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:155:13
  14: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:470:19
  15: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panic/unwind_safe.rs:271:9
  16: std::panicking::try::do_call
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
  17: ___rust_try
  18: std::panicking::try
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
  19: std::panic::catch_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
  20: tokio::runtime::task::harness::poll_future
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:458:18
  21: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:104:27
  22: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:57:15
  23: tokio::runtime::task::raw::poll
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/raw.rs:144:5
  24: tokio::runtime::task::raw::RawTask::poll
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/raw.rs:84:18
  25: tokio::runtime::task::LocalNotified<S>::run
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/mod.rs:376:9
  26: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:435:13
  27: tokio::coop::with_budget::{{closure}}
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:102:9
  28: std::thread::local::LocalKey<T>::try_with
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/local.rs:445:16
  29: std::thread::local::LocalKey<T>::with
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/thread/local.rs:421:9
  30: tokio::coop::with_budget
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:95:5
  31: tokio::coop::budget
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:72:5
  32: tokio::runtime::thread_pool::worker::Context::run_task
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:434:9
  33: tokio::runtime::thread_pool::worker::Context::run
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:401:24
  34: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:386:17
  35: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/macros/scoped_tls.rs:61:9
  36: tokio::runtime::thread_pool::worker::run
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:383:5
  37: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:362:45
  38: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/task.rs:42:21
  39: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:165:17
  40: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/loom/std/unsafe_cell.rs:14:9
  41: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:155:13
  42: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:470:19
  43: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panic/unwind_safe.rs:271:9
  44: std::panicking::try::do_call
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
  45: ___rust_try
  46: std::panicking::try
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
  47: std::panic::catch_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
  48: tokio::runtime::task::harness::poll_future
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:458:18
  49: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:104:27
  50: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:57:15
  51: tokio::runtime::task::raw::poll
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/raw.rs:144:5
  52: tokio::runtime::task::raw::RawTask::poll
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/raw.rs:84:18
  53: tokio::runtime::task::UnownedTask<S>::run
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/mod.rs:413:9
  54: tokio::runtime::blocking::pool::Task::run
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/pool.rs:91:9
  55: tokio::runtime::blocking::pool::Inner::run
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/pool.rs:325:17
  56: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/alessandro/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/pool.rs:300:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jkosh44** [comment]
Seems like our validations are a little out of order.

During purification we expect that the topic exists: https://github.com/MaterializeInc/materialize/blob/275e39bde34f085b32599d2bddf2bd93b01ee39e/src/sql/src/pure.rs#L106
During planning is where we validate that the topic exists: https://github.com/MaterializeInc/materialize/blob/275e39bde34f085b32599d2bddf2bd93b01ee39e/src/sql/src/plan/statement/ddl.rs#L405-L407

However purification works on statements which happen before planning, so if there's no topic then we just panic instead of return an error.
