### ISSUE TITLE
storaged panic: failed to create a delayed capability, the current set does not have an element less than or equal to

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#15046]
### What version of Materialize are you using?

 v0.27.0-alpha.22.post (06d04f7c3)

### How did you install Materialize?

Docker image

### What is the issue?

A test derived from #15044 repeatedly panicked as follows even before any OOMs have happened

### Relevant log output

```source
thread 'timely:work-0' panicked at 'failed to create a delayed capability, the current set does not have an element less than or equal to 1664364453000', /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/dataflow/operators/capability.rs:446:13
stack backtrace:
compute-cluster-1-replica-1: 2022-09-28T11:27:35.133346Z  INFO mz_persist_client::internal::machine: snapshot se4a2d457-777c-45c8-a406-5f426b4507f9 as of Antichain { elements: [1664364450003] } not yet available for upper Antichain { elements: [1664364448001] } retrying in 4.096s
   0: rust_begin_unwind
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: timely::dataflow::operators::capability::CapabilitySet<T>::delayed::delayed_panic
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/dataflow/operators/capability.rs:446:13
   3: timely::dataflow::operators::capability::CapabilitySet<T>::delayed::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/dataflow/operators/capability.rs:454:32
   4: core::option::Option<T>::unwrap_or_else
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/option.rs:825:21
   5: timely::dataflow::operators::capability::CapabilitySet<T>::delayed
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/dataflow/operators/capability.rs:453:9
   6: mz_storage::source::source_reader_pipeline::handle_message
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0e55a0e1200a25fb5-1/materialize/tests/src/storage/src/source/source_reader_pipeline.rs:1132:18
   7: mz_storage::source::source_reader_pipeline::reclock_operator::{{closure}}::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0e55a0e1200a25fb5-1/materialize/tests/src/storage/src/source/source_reader_pipeline.rs:1013:25
   8: mz_storage::source::reclock::ReclockIter<M>::for_each
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0e55a0e1200a25fb5-1/materialize/tests/src/storage/src/source/reclock.rs:765:17
   9: mz_storage::source::source_reader_pipeline::reclock_operator::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0e55a0e1200a25fb5-1/materialize/tests/src/storage/src/source/source_reader_pipeline.rs:1005:21
  10: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/dataflow/operators/generic/builder_rc.rs:123:31
  11: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/dataflow/operators/generic/builder_rc.rs:162:26
  12: <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/dataflow/operators/generic/builder_raw.rs:204:9
  13: timely::progress::subgraph::PerOperatorState<T>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/progress/subgraph.rs:684:30
  14: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/progress/subgraph.rs:344:26
  15: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/progress/subgraph.rs:310:17
  16: timely::progress::subgraph::PerOperatorState<T>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/progress/subgraph.rs:684:30
  17: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/progress/subgraph.rs:344:26
  18: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/progress/subgraph.rs:310:17
  19: timely::worker::Wrapper::step::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/worker.rs:754:57
  20: core::option::Option<T>::map
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/option.rs:929:29
  21: timely::worker::Wrapper::step
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/worker.rs:754:26
  22: timely::worker::Worker<A>::step_or_park
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/worker.rs:396:38
  23: mz_storage::storage_state::Worker<A>::run_client
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0e55a0e1200a25fb5-1/materialize/tests/src/storage/src/storage_state.rs:134:17
  24: mz_storage::storage_state::Worker<A>::run
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0e55a0e1200a25fb5-1/materialize/tests/src/storage/src/storage_state.rs:110:33
  25: mz_storage::protocol::server::serve::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0e55a0e1200a25fb5-1/materialize/tests/src/storage/src/protocol/server.rs:94:9
  26: timely::execute::execute::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/execute.rs:287:22
  27: timely_communication::initialize::initialize_from::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/communication/src/initialize.rs:316:33
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
environmentd: 2022-09-28T11:27:37.093452Z ERROR mz_orchestrator_process: storage-u3 exited: Ok(ExitStatus(unix_wait_status(134))); relaunching in 5s
```

**Comment by philip-stoev** [comment]
To reproduce, clone the `gh15046` branch from `https://github.com/philip-stoev/materialize` and run

```
cd test/bounded-memory
./mzcompose run default
```

and see with `docker logs bounded-memory-materialized-1` if you have a panic.

**Comment by aljoscha** [comment]
@guswynn I assigned you because this is the thing that your recent PR is fixing, right?

**Comment by guswynn** [comment]
@aljoscha Its a theory that that pr will fix it, or at least fix one outstanding edge case that could cause this; certainly that pr is required to convince ourselves that this is correct

**Comment by guswynn** [comment]
linking here for clarity: https://github.com/MaterializeInc/materialize/pull/15060

**Comment by guswynn** [comment]
@philip-stoev when you have time, can you see if this reproduces after https://github.com/MaterializeInc/materialize/commit/19fd9467b7d651161b1b5ef079292f37f4ce17a9?

**Comment by aljoscha** [comment]
We think this is how the bug "works":
 - we stash batches that we cannot yet timestamp. The messages in those batches can be reclocked to different target times. Say it has messages that reclock to `t1` and `t2` , `t3` with `t1 < t2 < t3`
 - we downgrade the source upper to a frontier `s2`  that reclocks to `t2` (note that we still have that stashed batch because we can't reclock it). We downgrade our output capabilities to `t2`
 - we downgrade the source upper a frontier `s3` that reclocks to `t3` , now we can reclock our batch
we reclock messages to `t1`, try to emit and then ... 💥 

There's a reproducer in https://github.com/aljoscha/materialize/tree/storage-fix-capability-downgrade-in-ingest that makes it easy to tickle this by holding back batches on purpose and only emitting them forward to reclocking once they reach a certain size.

@guswynn thinks this is a likely reason for https://github.com/MaterializeInc/materialize/issues/15350, because it can happen that we downgrade the capability, advance the persist upper, and then make it impossible to ever write the additions to those later retractions that we see show up when that bug hits.

A solution sketch from @petrosagg:

> The held batches should be thought of as containing a source time capability, which must be for the earliest time in the batch, so `s1` (in our example). This implied source capability also implies a held target capability at whatever time `s1` reclocks to

**Comment by danhhz** [comment]
This caused a ci flake in https://buildkite.com/materialize/tests/builds/43160, so I'm going to add the label in case this happens to someone else

**Comment by guswynn** [comment]
@danhhz that would be the first time I (we?) ever saw this on a kafka source! I can't find the panic in either of the failing tests logs in that link, am i looking in the wrong spot?

**Comment by danhhz** [comment]
Ah, sorry my link could have been more targeted. The flake was in "Checks + DROP/CREATE replica" https://buildkite.com/materialize/tests/builds/43160#0183d245-8029-4932-be00-b63635be31c6
