### ISSUE TITLE
environmentd: crash when explaining a `SHOW` query

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#15151]
### What version of Materialize are you using?

fc3d38c55eb3a3e8c6dfff36550877bc24415f85

### How did you install Materialize?

Built from source

### What is the issue?

Explaining a `SHOW` query does not work. Here's an easy example:

```sql
EXPLAIN (SHOW VIEWS);
```

And the backtrace:

```
thread 'coordinator' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`', /Users/benesch/Sites/materialize/materialize/src/repr/src/relation.rs:375:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:181:5
   4: mz_repr::relation::RelationDesc::new
             at ./src/repr/src/relation.rs:375:9
   5: mz_sql::plan::query::plan_root_query
             at ./src/sql/src/plan/query.rs:128:16
   6: mz_sql::plan::statement::dml::describe_select
             at ./src/sql/src/plan/statement/dml.rs:164:9
   7: mz_sql::plan::statement::dml::describe_explain_old
             at ./src/sql/src/plan/statement/dml.rs:274:13
   8: mz_sql::plan::statement::dml::describe_explain
             at ./src/sql/src/plan/statement/dml.rs:192:43
   9: mz_sql::plan::statement::describe
             at ./src/sql/src/plan/statement.rs:198:37
  10: mz_adapter::util::describe
             at ./src/adapter/src/util.rs:218:16
  11: mz_adapter::coord::sql::<impl mz_adapter::coord::Coordinator<S>>::declare
             at ./src/adapter/src/coord/sql.rs:43:20
  12: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_command::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:73:30
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  14: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_command::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:165:33
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  16: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_command::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:162:5
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  18: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_message::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:40:63
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  20: mz_adapter::coord::Coordinator<S>::serve::{{closure}}
             at ./src/adapter/src/coord.rs:796:37
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  22: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /Users/benesch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:54
  23: tokio::coop::with_budget::{{closure}}
             at /Users/benesch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:102:9
  24: std::thread::local::LocalKey<T>::try_with
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:445:16
  25: std::thread::local::LocalKey<T>::with
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:421:9
  26: tokio::coop::with_budget
             at /Users/benesch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:95:5
  27: tokio::coop::budget
             at /Users/benesch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:72:5
  28: tokio::park::thread::CachedParkThread::block_on
             at /Users/benesch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:31
  29: tokio::runtime::enter::Enter::block_on
             at /Users/benesch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/enter.rs:151:13
  30: tokio::runtime::handle::Handle::block_on
             at /Users/benesch/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/handle.rs:296:9
  31: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./src/adapter/src/coord.rs:940:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Abort trap: 6
```

Seems to hold true for all explain variants (e.g., `EXPLAIN TIMESTAMP`) and show variants (e.g., `SHOW TABLES`).

More context on Slack: https://materializeinc.slack.com/archives/CU7ELJ6E9/p1664828650093439

cc @chaas @mjib

**Comment by mjibson** [comment]
Some investigation. This happens on both new and old explain plans. The problem is at https://github.com/MaterializeInc/materialize/blob/3b8ceba49c50fbbf8320bf06e82b7ab525317a4b/src/sql/src/plan/query.rs#L111 where the returned scope and finishing disagree about how many columns there are (the finishing has two things in its `project`, the scope has a single ScopeItem):

```
[src/sql/src/plan/query.rs:122] &scope = Scope {
    items: [
        ScopeItem {
            table_name: None,
            column_name: ColumnName(
                "name",
            ),
            exprs: {},
            from_single_column_function: false,
            allow_unqualified_references: true,
            lateral_error_if_referenced: false,
            is_exists_column_for_a_table_function_that_was_in_the_target_list: false,
            _private: (),
        },
    ],
    lateral_barrier: false,
}
[src/sql/src/plan/query.rs:122] &finishing = RowSetFinishing {
    order_by: [],
    limit: None,
    offset: 0,
    project: [
        0,
        1,
    ],
}
```

**Comment by chaas** [comment]
Dug into this a bit more. It's because the `RelationType` here https://github.com/MaterializeInc/materialize/blob/3b8ceba49c50fbbf8320bf06e82b7ab525317a4b/src/sql/src/plan/query.rs#L120
has an extra entry for the `scalar_type: Record`, which is being included in the `project`, but is not in the column names list.
The full output for the `typ` field is:
```
    RelationType { 
        column_types: [
            ColumnType {
                scalar_type: String, nullable: false 
            }, 
            ColumnType {
                scalar_type: Record {
                    fields: [(ColumnName("name"), ColumnType { scalar_type: String, nullable: false })],
                    custom_id: None },
                nullable: false
            }
        ], keys: []
    }
```
Should the `project` only have one field, thus excluding that `scalar_type: Record `?

**Comment by benesch** [comment]
This is very weird! I think you're right that the scope is correct (`SHOW VIEWS` only has one output column called "name"), and the relation type and expression somehow have an extra column.

**Comment by benesch** [comment]
Current theory is that it's a bug in `ShowSelect::plan_hir`.

**Comment by benesch** [comment]
Ah, of course. `plan_hir` is (incorrectly) ignoring the `finishing` that it gets back from `plan_root_query`, when it needs to apply that finishing.
