### ISSUE TITLE
adapter: panic: `Result::unwrap()` on an `Err` value: InstanceMissing(1)'

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#15179]
1. Started everything locally.
2. In terminal A, run `create table t (); select * from t as of 18446744073709551615;` and let it hang
3. In terminal B, run `drop cluster default`
4. In terminal A, press ctrl^c to cancel the select.

envd panics:

```
thread 'coordinator' panicked at 'called `Result::unwrap()` on an `Err` value: InstanceMissing(1)', /home/mjibson/materialize/src/adapter/src/coord/peek.rs:606:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1814:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1107:23
   4: mz_adapter::coord::peek::<impl mz_adapter::coord::Coordinator<S>>::cancel_pending_peeks::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/peek.rs:602:17
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
   6: mz_adapter::coord::peek::<impl mz_adapter::coord::Coordinator<S>>::cancel_pending_peeks::{{closure}}
             at ./src/adapter/src/coord/peek.rs:592:5
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
   8: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_cancel::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:513:52
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  10: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_command::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:93:56
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  12: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_command::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:165:33
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  14: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_command::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:162:5
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  16: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_message::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:40:63
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  18: mz_adapter::coord::Coordinator<S>::serve::{{closure}}
             at ./src/adapter/src/coord.rs:801:37
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  20: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:54
  21: tokio::coop::with_budget::{{closure}}
             at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:102:9
  22: std::thread::local::LocalKey<T>::try_with
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:445:16
  23: std::thread::local::LocalKey<T>::with
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:421:9
  24: tokio::coop::with_budget
             at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:95:5
  25: tokio::coop::budget
             at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:72:5
  26: tokio::park::thread::CachedParkThread::block_on
             at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/park/thread.rs:263:31
  27: tokio::runtime::enter::Enter::block_on
             at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/enter.rs:151:13
  28: tokio::runtime::handle::Handle::block_on
             at /home/mjibson/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/handle.rs:296:9
  29: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./src/adapter/src/coord.rs:946:17
```

**Comment by jkosh44** [comment]
I've updated https://github.com/MaterializeInc/materialize/issues/16121 to include the peek scenario, which is related to this issue.
