### ISSUE TITLE
Unable to create connection

### ISSUE THREAD

**Issue by mtamrakar** [MaterializeInc/materialize#15201]
### What version of Materialize are you using?

v0.26.4

### How did you install Materialize?

Docker image

### What is the issue?

We are experimenting with the product using the docker image. Our plan is to use Debezium to publish messages into Kafka from MS SQL Server and consume the same into the Materialize framework. While trying to create a connection, we're getting the following error

materialize=> CREATE CONNECTION kafka_connection FOR KAFKA BROKER '172.17.0.3:9092';
ERROR:  Expected DATABASE, SCHEMA, ROLE, USER, TYPE, INDEX, SINK, SOURCE, TABLE, SECRET or [OR REPLACE] [TEMPORARY] [MATERIALIZED] VIEW or VIEWS after CREATE, found CONNECTION
LINE 1: CREATE CONNECTION kafka_connection FOR KAFKA BROKER '172.17....

**Comment by mtamrakar** [comment]
Thank you for the documentation. Looks like the next challenge for me is the schema registry setup. We're trying to set up a confluent schema registry but have been unsuccessful so far. Any ideas?

Docker run command(zookeeper and kafka is running atm):
docker run -it --rm --name schema-registry --link zookeeper    -e SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181   -e SCHEMA_REGISTRY_HOST_NAME=schema-registry   -e SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081  -e SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=PLAINTEXT://172.17.0.3:9092 -p 8181:8181 confluentinc/cp-schema-registry

[2022-10-06 17:31:24,135] ERROR Server died unexpectedly:  (io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain)
java.io.IOException: Failed to bind to schema-registry:8081
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.server.Server.doStart(Server.java:401)
        at io.confluent.rest.ApplicationServer.doStart(ApplicationServer.java:272)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain.main(SchemaRegistryMain.java:44)
Caused by: java.net.SocketException: Unresolved address
        at java.base/sun.nio.ch.Net.translateToSocketException(Net.java:171)
        at java.base/sun.nio.ch.Net.translateException(Net.java:197)
        at java.base/sun.nio.ch.Net.translateException(Net.java:203)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:82)
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344)
        ... 8 more
Caused by: java.nio.channels.UnresolvedAddressException
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:131)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:222)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
        ... 9 more

**Comment by joacoc** [comment]
Mh. Could it be an unavailable port?

I would suggest running one of our [demos](https://github.com/MaterializeInc/demos/tree/main/ecommerce).

**Comment by mtamrakar** [comment]
Found the issue. For some reason we have to decorate the columns names with double quotes.

Eg:
select * from m_test where "WO_Status_ID" = 1
