### ISSUE TITLE
storaged: assertion failed: `(left == right)` in mz_storage::storage_state::Worker<A>::reconcile on environmentd restart

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#15213]
### What version of Materialize are you using?

765a8a11259647aa0acea19a1073cf2cc1ee05fe

### How did you install Materialize?

Docker image

### What is the issue?

In a cloudtest-populated K8s cluster, if an `environmentd` is restarted, 3/4 of the storaged pods will survive intact, but 1/4 will panic as follows and restart successfully.

The difference between the left and the right is in this frgment:
left:
```
as_of: SinkAsOf { frontier: Antichain { elements: [1665042163436] }, strict: false }
```
right:
```
as_of: SinkAsOf { frontier: Antichain { elements: [1665043548001] }, strict: true }
```

So the Antichain value is different as well as the `strict` flag.

To reproduce,

1. Get cloudtest running locally as per the instructions in `doc/developer/cloudtest.md`
2. Run:
```
cd test/cloudtest
./pytest -mlong test_upgrade.py
```

As of this writing, the test does not upgrade anything actually, it uses the "current source" Mz and does not restart it. Once the test is finished, you will be left with a K8s cluster with a bunch of database objects in it.

3. Cause the `environmentd` to be restarted:
```
kubectl delete pod/environmentd-0
```
4. With `kubectl get pods` you can observe a freshly-restarted `environmentd`:
```
environmentd-0                      1/1     Running     0             10s
```

and then some storaged pods that have `RESTARTS` > 0

```
storage-u167-0                      1/1     Running     1 (10m ago)   37m
```

5. Use `docker logs pod storage-u167-0 --previous` to see the log of the pod prior to the restart. This log should have the panic in it.

```



### Relevant log output

```source
thread 'timely:work-0' panicked at 'assertion failed: `(left == right)`
  left: `StorageSinkDesc { from: User(84), from_desc: RelationDesc { typ: RelationType { column_types: [ColumnType { scalar_type: Int32, nullable: false }, ColumnType { scalar_type: String, nullable: true }], keys: [] }, names: [ColumnName("f1"), ColumnName("f2")] }, connection: Kafka(KafkaSinkConnection { connection: KafkaConnection { brokers: ["redpanda:9092"], progress_topic: None, security: None }, options: {"isolation.level": String("read_committed"), "statistics.interval.ms": String("1000")}, topic: "testdrive-sink-large-transaction-sink-1", key_desc_and_indices: None, relation_key_indices: None, value_desc: RelationDesc { typ: RelationType { column_types: [ColumnType { scalar_type: Int32, nullable: false }, ColumnType { scalar_type: String, nullable: true }], keys: [] }, names: [ColumnName("f1"), ColumnName("f2")] }, published_schema_info: Some(PublishedSchemaInfo { key_schema_id: None, value_schema_id: 4 }), progress: KafkaSinkProgressConnection { topic: "_materialize-progress-environment-00000000-0000-0000-0000-000000000000-0-u4" }, exactly_once: true, fuel: 10000 }), envelope: Some(Debezium), as_of: SinkAsOf { frontier: Antichain { elements: [1665042104337] }, strict: false }, from_storage_metadata: CollectionMetadata { persist_location: PersistLocation { blob_uri: "s3://minio:minio123@persist/persist?endpoint=http%3A//minio-service.default%3A9000&region=minio", consensus_uri: "postgres://postgres@postgres.default?options=--search_path=consensus" }, remap_shard: ShardId(7752b8a9-5cd1-482f-a9bd-4353f638922b), data_shard: ShardId(ee1db8ed-5c72-4d8a-bd0b-ce4778641168), status_shard: None } }`,
 right: `StorageSinkDesc { from: User(84), from_desc: RelationDesc { typ: RelationType { column_types: [ColumnType { scalar_type: Int32, nullable: false }, ColumnType { scalar_type: String, nullable: true }], keys: [] }, names: [ColumnName("f1"), ColumnName("f2")] }, connection: Kafka(KafkaSinkConnection { connection: KafkaConnection { brokers: ["redpanda:9092"], progress_topic: None, security: None }, options: {"isolation.level": String("read_committed"), "statistics.interval.ms": String("1000")}, topic: "testdrive-sink-large-transaction-sink-1", key_desc_and_indices: None, relation_key_indices: None, value_desc: RelationDesc { typ: RelationType { column_types: [ColumnType { scalar_type: Int32, nullable: false }, ColumnType { scalar_type: String, nullable: true }], keys: [] }, names: [ColumnName("f1"), ColumnName("f2")] }, published_schema_info: Some(PublishedSchemaInfo { key_schema_id: None, value_schema_id: 4 }), progress: KafkaSinkProgressConnection { topic: "_materialize-progress-environment-00000000-0000-0000-0000-000000000000-0-u4" }, exactly_once: true, fuel: 10000 }), envelope: Some(Debezium), as_of: SinkAsOf { frontier: Antichain { elements: [1665043681427] }, strict: true }, from_storage_metadata: CollectionMetadata { persist_location: PersistLocation { blob_uri: "s3://minio:minio123@persist/persist?endpoint=http%3A//minio-service.default%3A9000&region=minio", consensus_uri: "postgres://postgres@postgres.default?options=--search_path=consensus" }, remap_shard: ShardId(7752b8a9-5cd1-482f-a9bd-4353f638922b), data_shard: ShardId(ee1db8ed-5c72-4d8a-bd0b-ce4778641168), status_shard: None } }`: New export with same ID User(87)', src/storage/src/storage_state.rs:352:29
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:181:5
   4: mz_storage::storage_state::Worker<A>::reconcile::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-08216a46cf23919f1-1/materialize/tests/src/storage/src/storage_state.rs:352:29
   5: alloc::vec::Vec<T,A>::retain_mut::process_loop
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/alloc/src/vec/mod.rs:1574:21
   6: alloc::vec::Vec<T,A>::retain_mut
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/alloc/src/vec/mod.rs:1600:9
   7: mz_storage::storage_state::Worker<A>::reconcile
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-08216a46cf23919f1-1/materialize/tests/src/storage/src/storage_state.rs:346:21
   8: mz_storage::storage_state::Worker<A>::run_client
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-08216a46cf23919f1-1/materialize/tests/src/storage/src/storage_state.rs:118:9
   9: mz_storage::storage_state::Worker<A>::run
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-08216a46cf23919f1-1/materialize/tests/src/storage/src/storage_state.rs:110:33
  10: mz_storage::protocol::server::serve::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-08216a46cf23919f1-1/materialize/tests/src/storage/src/protocol/server.rs:94:9
  11: timely::execute::execute::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/execute.rs:287:22
  12: timely_communication::initialize::initialize_from::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/communication/src/initialize.rs:316:33
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by philip-stoev** [comment]
This happens in the normal CI :+1: 
https://buildkite.com/materialize/tests/builds/61976
https://buildkite.com/materialize/tests/builds/62018

The diff is now entirely in the Sink AsOf Antichain, with the `strict` attribute being identical between the left and the right.
