### ISSUE TITLE
opentel panic: 'Span not found, this is a bug'

### ISSUE THREAD

**Issue by pH14** [MaterializeInc/materialize#15223]
### What version of Materialize are you using?

v.0.27.0-alpha.24

### How did you install Materialize?

Materialize Cloud

### What is the issue?

Enabled tracing for an environment with `mz_adapter=debug,info` targets. A `computed` eventually panicked with the following error

cc @guswynn 

### Relevant log output

```source
thread 'timely:work-0' panicked at 'Span not found, this is a bug', /cargo/git/checkouts/tracing-6b72461fcc9730e6/fa05cdc/tracing-opentelemetry/src/layer.rs:598:41
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/option.rs:1874:5
   5: core::option::Option<T>::expect
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/option.rs:738:21
   6: tracing_opentelemetry::layer::OpenTelemetryLayer<S,T>::parent_context
             at ./cargo/git/checkouts/tracing-6b72461fcc9730e6/fa05cdc/tracing-opentelemetry/src/layer.rs:598:24
   7: <tracing_opentelemetry::layer::OpenTelemetryLayer<S,T> as tracing_subscriber::layer::Layer<S>>::on_new_span
             at ./cargo/git/checkouts/tracing-6b72461fcc9730e6/fa05cdc/tracing-opentelemetry/src/layer.rs:683:25
   8: tracing_subscriber::filter::layer_filters::Filtered<L,F,S>::did_enable::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.3.15/src/filter/layer_filters/mod.rs:471:36
   9: std::thread::local::LocalKey<T>::try_with
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:445:16
  10: std::thread::local::LocalKey<T>::with
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:421:9
  11: tracing_subscriber::filter::layer_filters::Filtered<L,F,S>::did_enable
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.3.15/src/filter/layer_filters/mod.rs:471:9
  12: <tracing_subscriber::filter::layer_filters::Filtered<L,F,S> as tracing_subscriber::layer::Layer<S>>::on_new_span
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.3.15/src/filter/layer_filters/mod.rs:619:9
  13: <core::option::Option<L> as tracing_subscriber::layer::Layer<S>>::on_new_span
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.3.15/src/layer/mod.rs:1469:13
  14: <tracing_subscriber::layer::layered::Layered<L,S> as tracing_core::subscriber::Subscriber>::new_span
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.3.15/src/layer/layered.rs:128:9
  15: <alloc::sync::Arc<S> as tracing_core::subscriber::Subscriber>::new_span
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.29/src/subscriber.rs:787:9
  16: tracing_core::dispatcher::Dispatch::new_span
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.29/src/dispatcher.rs:473:9
  17: tracing::span::Span::make_with
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/span.rs:569:18
  18: tracing::span::Span::child_of_with
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/span.rs:507:9
  19: tracing::span::Span::child_of::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/span.rs:491:13
  20: tracing_core::dispatcher::get_default::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.29/src/dispatcher.rs:337:24
  21: std::thread::local::LocalKey<T>::try_with
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:445:16
  22: tracing_core::dispatcher::get_default
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.29/src/dispatcher.rs:334:5
  23: tracing::span::Span::child_of
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/span.rs:490:9
  24: mz_compute::compute_state::ActiveComputeState<A>::process_peeks
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ac20b0cfecba0b09-1/materialize/tests/src/compute/src/compute_state.rs:612:29
  25: mz_compute::server::Worker<A>::run_client
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ac20b0cfecba0b09-1/materialize/tests/src/compute/src/server.rs:533:17
  26: mz_compute::server::Worker<A>::setup_channel_and_run_client
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ac20b0cfecba0b09-1/materialize/tests/src/compute/src/server.rs:482:9
  27: mz_compute::server::Worker<A>::run
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ac20b0cfecba0b09-1/materialize/tests/src/compute/src/server.rs:347:21
  28: mz_compute::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<mz_compute_client::command::ComputeCommand,mz_compute_client::response::ComputeResponse,timely::scheduling::activate::SyncActivator>,mz_compute_client::command::ComputeCommand,mz_compute_client::response::ComputeResponse>>::build_timely::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ac20b0cfecba0b09-1/materialize/tests/src/compute/src/server.rs:167:17
  29: timely::execute::execute_from::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/execute.rs:388:22
  30: timely_communication::initialize::initialize_from::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/communication/src/initialize.rs:316:33
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
```

**Comment by guswynn** [comment]
I believe https://github.com/tokio-rs/tracing-opentelemetry/pull/86 is the fix
