### ISSUE TITLE
sql: SHOW INDEXES panic when nested

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#15395]
### What version of Materialize are you using?

`main`

### How did you install Materialize?

Built from source

### What is the issue?

When running `SELECT * FROM (SHOW INDEXES)` Materialize panics.

### Relevant log output

```source
thread 'coordinator' panicked at 'internal error: entered unreachable code: Expr::Nested not desugared', src/sql/src/plan/query.rs:3073:28
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: mz_sql::plan::query::plan_expr_inner
             at ./src/sql/src/plan/query.rs:3073:28
   3: mz_sql::plan::query::plan_expr::{{closure}}
             at ./src/sql/src/plan/query.rs:2984:29
   4: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
   5: stacker::maybe_grow
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
   6: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
   7: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
   8: mz_sql::plan::query::plan_expr
             at ./src/sql/src/plan/query.rs:2984:5
   9: mz_sql::plan::query::plan_and
             at ./src/sql/src/plan/query.rs:3149:9
  10: mz_sql::plan::query::plan_expr_inner
             at ./src/sql/src/plan/query.rs:3018:38
  11: mz_sql::plan::query::plan_expr::{{closure}}
             at ./src/sql/src/plan/query.rs:2984:29
  12: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  13: stacker::maybe_grow
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  14: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  15: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  16: mz_sql::plan::query::plan_expr
             at ./src/sql/src/plan/query.rs:2984:5
  17: mz_sql::plan::query::plan_view_select
             at ./src/sql/src/plan/query.rs:1572:20
  18: mz_sql::plan::query::plan_query_inner
             at ./src/sql/src/plan/query.rs:1066:24
  19: mz_sql::plan::query::plan_query::{{closure}}
             at ./src/sql/src/plan/query.rs:1000:33
  20: mz_ore::stack::CheckedRecursion::checked_recur_mut::{{closure}}
             at ./src/ore/src/stack.rs:205:33
  21: stacker::maybe_grow
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  22: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  23: mz_ore::stack::CheckedRecursion::checked_recur_mut
             at ./src/ore/src/stack.rs:205:19
  24: mz_sql::plan::query::plan_query
             at ./src/sql/src/plan/query.rs:1000:5
  25: mz_sql::plan::query::plan_nested_query
             at ./src/sql/src/plan/query.rs:1119:40
  26: mz_sql::plan::query::plan_subquery
             at ./src/sql/src/plan/query.rs:3528:26
  27: mz_sql::plan::query::plan_expr_inner
             at ./src/sql/src/plan/query.rs:3069:34
  28: mz_sql::plan::query::plan_expr::{{closure}}
             at ./src/sql/src/plan/query.rs:2984:29
  29: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  30: stacker::maybe_grow
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  31: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  32: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  33: mz_sql::plan::query::plan_expr
             at ./src/sql/src/plan/query.rs:2984:5
  34: mz_sql::plan::query::plan_view_select
             at ./src/sql/src/plan/query.rs:1774:51
  35: mz_sql::plan::query::plan_query_inner
             at ./src/sql/src/plan/query.rs:1066:24
  36: mz_sql::plan::query::plan_query::{{closure}}
             at ./src/sql/src/plan/query.rs:1000:33
  37: mz_ore::stack::CheckedRecursion::checked_recur_mut::{{closure}}
             at ./src/ore/src/stack.rs:205:33
  38: stacker::maybe_grow
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  39: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  40: mz_ore::stack::CheckedRecursion::checked_recur_mut
             at ./src/ore/src/stack.rs:205:19
  41: mz_sql::plan::query::plan_query
             at ./src/sql/src/plan/query.rs:1000:5
  42: mz_sql::plan::query::plan_nested_query
             at ./src/sql/src/plan/query.rs:1119:40
  43: mz_sql::plan::query::plan_table_factor
             at ./src/sql/src/plan/query.rs:2187:33
  44: mz_sql::plan::query::plan_table_with_joins
             at ./src/sql/src/plan/query.rs:2137:33
  45: mz_sql::plan::query::plan_table_factor
             at ./src/sql/src/plan/query.rs:2193:33
  46: mz_sql::plan::query::plan_join
             at ./src/sql/src/plan/query.rs:2773:32
  47: mz_sql::plan::query::plan_view_select::{{closure}}
             at ./src/sql/src/plan/query.rs:1547:13
  48: core::iter::traits::iterator::Iterator::fold
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/iter/traits/iterator.rs:2414:21
  49: mz_sql::plan::query::plan_view_select
             at ./src/sql/src/plan/query.rs:1545:9
  50: mz_sql::plan::query::plan_query_inner
             at ./src/sql/src/plan/query.rs:1066:24
  51: mz_sql::plan::query::plan_query::{{closure}}
             at ./src/sql/src/plan/query.rs:1000:33
  52: mz_ore::stack::CheckedRecursion::checked_recur_mut::{{closure}}
             at ./src/ore/src/stack.rs:205:33
  53: stacker::maybe_grow
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  54: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  55: mz_ore::stack::CheckedRecursion::checked_recur_mut
             at ./src/ore/src/stack.rs:205:19
  56: mz_sql::plan::query::plan_query
             at ./src/sql/src/plan/query.rs:1000:5
  57: mz_sql::plan::query::plan_nested_query
             at ./src/sql/src/plan/query.rs:1119:40
  58: mz_sql::plan::statement::show::ShowSelect::plan_hir
             at ./src/sql/src/plan/statement/show.rs:659:9
  59: mz_sql::plan::query::plan_set_expr
             at ./src/sql/src/plan/query.rs:1328:21
  60: mz_sql::plan::query::plan_query_inner
             at ./src/sql/src/plan/query.rs:1076:33
  61: mz_sql::plan::query::plan_query::{{closure}}
             at ./src/sql/src/plan/query.rs:1000:33
  62: mz_ore::stack::CheckedRecursion::checked_recur_mut::{{closure}}
             at ./src/ore/src/stack.rs:205:33
  63: stacker::maybe_grow
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  64: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  65: mz_ore::stack::CheckedRecursion::checked_recur_mut
             at ./src/ore/src/stack.rs:205:19
  66: mz_sql::plan::query::plan_query
             at ./src/sql/src/plan/query.rs:1000:5
  67: mz_sql::plan::query::plan_nested_query
             at ./src/sql/src/plan/query.rs:1119:40
  68: mz_sql::plan::query::plan_table_factor
             at ./src/sql/src/plan/query.rs:2187:33
  69: mz_sql::plan::query::plan_table_with_joins
             at ./src/sql/src/plan/query.rs:2137:33
  70: mz_sql::plan::query::plan_table_factor
             at ./src/sql/src/plan/query.rs:2193:33
  71: mz_sql::plan::query::plan_join
             at ./src/sql/src/plan/query.rs:2773:32
  72: mz_sql::plan::query::plan_view_select::{{closure}}
             at ./src/sql/src/plan/query.rs:1547:13
  73: core::iter::traits::iterator::Iterator::fold
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/iter/traits/iterator.rs:2414:21
  74: mz_sql::plan::query::plan_view_select
             at ./src/sql/src/plan/query.rs:1545:9
  75: mz_sql::plan::query::plan_query_inner
             at ./src/sql/src/plan/query.rs:1066:24
  76: mz_sql::plan::query::plan_query::{{closure}}
             at ./src/sql/src/plan/query.rs:1000:33
  77: mz_ore::stack::CheckedRecursion::checked_recur_mut::{{closure}}
             at ./src/ore/src/stack.rs:205:33
  78: stacker::maybe_grow
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  79: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  80: mz_ore::stack::CheckedRecursion::checked_recur_mut
             at ./src/ore/src/stack.rs:205:19
  81: mz_sql::plan::query::plan_query
             at ./src/sql/src/plan/query.rs:1000:5
  82: mz_sql::plan::query::plan_root_query
             at ./src/sql/src/plan/query.rs:113:44
  83: mz_sql::plan::statement::dml::describe_select
             at ./src/sql/src/plan/statement/dml.rs:164:9
  84: mz_sql::plan::statement::describe
             at ./src/sql/src/plan/statement.rs:201:36
  85: mz_adapter::util::describe
             at ./src/adapter/src/util.rs:218:16
  86: mz_adapter::coord::sql::<impl mz_adapter::coord::Coordinator<S>>::declare
             at ./src/adapter/src/coord/sql.rs:43:20
  87: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_command::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:74:30
  88: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  89: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_command::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:149:33
  90: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  91: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_command::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:146:5
  92: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  93: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_message::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:40:63
  94: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  95: mz_adapter::coord::Coordinator<S>::serve::{{closure}}
             at ./src/adapter/src/coord.rs:855:37
  96: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  97: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/park/thread.rs:263:54
  98: tokio::coop::with_budget::{{closure}}
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:102:9
  99: std::thread::local::LocalKey<T>::try_with
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:445:16
 100: std::thread::local::LocalKey<T>::with
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:421:9
 101: tokio::coop::with_budget
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:95:5
 102: tokio::coop::budget
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:72:5
 103: tokio::park::thread::CachedParkThread::block_on
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/park/thread.rs:263:31
 104: tokio::runtime::enter::Enter::block_on
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/enter.rs:152:13
 105: tokio::runtime::handle::Handle::block_on
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/handle.rs:297:9
 106: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./src/adapter/src/coord.rs:1000:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by ggnall** [comment]
@jkosh44 is this completed by https://github.com/MaterializeInc/materialize/pull/15344 ?

**Comment by jkosh44** [comment]
Yep this works fine now on `main`,

```
materialize=> SELECT * FROM (SHOW INDEXES);
 name | on | cluster | key 
------+----+---------+-----
(0 rows)
```
