### ISSUE TITLE
regression: panicked at 'state diff should apply cleanly: "spine delete didn't match: None vs Some(())"

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#15493]
### What version of Materialize are you using?

environmentd v0.28.0-dev (006fff5f3)

### How did you install Materialize?

Docker image

### What is the issue?

Testdrive with `--default-kafka-partitions 5` failed as follows.

https://buildkite.com/materialize/nightlies/builds/1248#0183e9b1-05e2-45fd-bcc3-a63a42dce7dc

### Relevant log output

```source
testdrive-materialized-1     | thread 'tokio:work-0' panicked at 'state diff should apply cleanly: "spine delete didn't match: None vs Some(())"', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07d043da2c32bb5e0-1/materialize/tests/src/persist-client/src/internal/state_diff.rs:205:14
testdrive-materialized-1     | stack backtrace:
testdrive-materialized-1     |    0: rust_begin_unwind
testdrive-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
testdrive-materialized-1     |    1: core::panicking::panic_fmt
testdrive-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
testdrive-materialized-1     |    2: core::result::unwrap_failed
testdrive-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1814:5
testdrive-materialized-1     |    3: core::result::Result<T,E>::expect
testdrive-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1064:23
testdrive-materialized-1     |    4: mz_persist_client::internal::state_diff::<impl mz_persist_client::internal::state::State<K,V,T,D>>::apply_encoded_diffs
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07d043da2c32bb5e0-1/materialize/tests/src/persist-client/src/internal/state_diff.rs:204:9
testdrive-materialized-1     |    5: mz_persist_client::internal::state_versions::StateVersionsIter<K,V,T,D>::next
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07d043da2c32bb5e0-1/materialize/tests/src/persist-client/src/internal/state_versions.rs:677:9
testdrive-materialized-1     |    6: mz_persist_client::internal::gc::GarbageCollector<K,V,T,D>::gc_and_truncate::{{closure}}
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07d043da2c32bb5e0-1/materialize/tests/src/persist-client/src/internal/gc.rs:232:33
testdrive-materialized-1     |    7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
testdrive-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
testdrive-materialized-1     |    8: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
testdrive-materialized-1     |    9: mz_persist_client::internal::gc::GarbageCollector<K,V,T,D>::new::{{closure}}
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07d043da2c32bb5e0-1/materialize/tests/src/persist-client/src/internal/gc.rs:145:41
testdrive-materialized-1     |   10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
testdrive-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
testdrive-materialized-1     |   11: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:165:17
testdrive-materialized-1     |   12: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/loom/std/unsafe_cell.rs:14:9
testdrive-materialized-1     |   13: tokio::runtime::task::core::CoreStage<T>::poll
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:155:13
testdrive-materialized-1     |   14: tokio::runtime::task::harness::poll_future::{{closure}}
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:480:19
testdrive-materialized-1     |   15: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
testdrive-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panic/unwind_safe.rs:271:9
testdrive-materialized-1     |   16: std::panicking::try::do_call
testdrive-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
testdrive-materialized-1     |   17: std::panicking::try
testdrive-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
testdrive-materialized-1     |   18: std::panic::catch_unwind
testdrive-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
testdrive-materialized-1     |   19: tokio::runtime::task::harness::poll_future
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:468:18
testdrive-materialized-1     |   20: tokio::runtime::task::harness::Harness<T,S>::poll_inner
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:104:27
testdrive-materialized-1     |   21: tokio::runtime::task::harness::Harness<T,S>::poll
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:57:15
testdrive-materialized-1     |   22: tokio::runtime::task::raw::RawTask::poll
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/raw.rs:84:18
testdrive-materialized-1     |   23: tokio::runtime::task::LocalNotified<S>::run
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/mod.rs:381:9
testdrive-materialized-1     |   24: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:435:13
testdrive-materialized-1     |   25: tokio::coop::with_budget::{{closure}}
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:102:9
testdrive-materialized-1     |   26: std::thread::local::LocalKey<T>::try_with
testdrive-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:445:16
testdrive-materialized-1     |   27: std::thread::local::LocalKey<T>::with
testdrive-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:421:9
testdrive-materialized-1     |   28: tokio::coop::with_budget
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:95:5
testdrive-materialized-1     |   29: tokio::coop::budget
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:72:5
testdrive-materialized-1     |   30: tokio::runtime::thread_pool::worker::Context::run_task
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:434:9
testdrive-materialized-1     |   31: tokio::runtime::thread_pool::worker::Context::run
testdrive-materialized-1     |   32: tokio::runtime::thread_pool::worker::run::{{closure}}
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:386:17
testdrive-materialized-1     |   33: tokio::macros::scoped_tls::ScopedKey<T>::set
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/macros/scoped_tls.rs:61:9
testdrive-materialized-1     |   34: tokio::runtime::thread_pool::worker::run
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:383:5
testdrive-materialized-1     |   35: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:362:45
testdrive-materialized-1     |   36: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/task.rs:42:21
testdrive-materialized-1     |   37: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:165:17
testdrive-materialized-1     |   38: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/loom/std/unsafe_cell.rs:14:9
testdrive-materialized-1     |   39: tokio::runtime::task::core::CoreStage<T>::poll
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:155:13
testdrive-materialized-1     |   40: tokio::runtime::task::harness::poll_future::{{closure}}
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:480:19
testdrive-materialized-1     |   41: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
testdrive-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panic/unwind_safe.rs:271:9
testdrive-materialized-1     |   42: std::panicking::try::do_call
testdrive-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
testdrive-materialized-1     |   43: std::panicking::try
testdrive-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
testdrive-materialized-1     |   44: std::panic::catch_unwind
testdrive-materialized-1     |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
testdrive-materialized-1     |   45: tokio::runtime::task::harness::poll_future
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:468:18
testdrive-materialized-1     |   46: tokio::runtime::task::harness::Harness<T,S>::poll_inner
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:104:27
testdrive-materialized-1     |   47: tokio::runtime::task::harness::Harness<T,S>::poll
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:57:15
testdrive-materialized-1     |   48: tokio::runtime::task::raw::RawTask::poll
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/raw.rs:84:18
testdrive-materialized-1     |   49: tokio::runtime::task::UnownedTask<S>::run
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/mod.rs:418:9
testdrive-materialized-1     |   50: tokio::runtime::blocking::pool::Task::run
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/pool.rs:91:9
testdrive-materialized-1     |   51: tokio::runtime::blocking::pool::Inner::run
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/pool.rs:325:17
testdrive-materialized-1     |   52: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/pool.rs:300:13
testdrive-materialized-1     | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by aljoscha** [comment]
@danhhz (and maybe @pH14) could you please take a look?

**Comment by philip-stoev** [comment]
I am starting a fresh Nighly run with the jobs that previously caused this to happen in hope that the extra debugging information will be captured.

**Comment by danhhz** [comment]
do we know if this goes away on restart or if sticks around permanently? if the former, it's probably a similar flavor of bug as #14892

**Comment by pH14** [comment]
Still an issue. Here's a gist with the diffs being applied, the trace of the caller, and the reconstructed trace that also didn't match the diff https://gist.github.com/pH14/1d9d6d9e233096d4c448691df271b49d

**Comment by danhhz** [comment]
thinking out loud: the diff of the new failure looks like this ```
delete [0][1667216805359] (empty)
insert [0][1667217083793] (empty)
delete [1667216805359][1667217083793] (empty)
insert [1667217185234][1667217185859] (not empty)
```

notes: 
- the first two deletes line up with the first insert. all 3 are empty
- the second insert's lower lines up with the spine's upper. it actually has data
- so I think this diff is _possible_ to apply
- the in-mem state has an empty HollowBatch for `[0][1667217094664]`, which covers a superset of the first three batches in the diff. I think this is covered by 15745, but that didn't apply because it's looking for a very specific pattern and this diff also has the final insert
- it really feels to me like we're hitting the the limit of reasonable special cases we can/are comfortable with writing here. I'd already been wondering if it's time to take a step back and this is another argument in favor of that

great find @philip-stoev, thanks!

**Comment by philip-stoev** [comment]
Seen again here:

This is CI run that runs everything with SIZE '4-4' for computed and SIZE 4 for storaged.

https://buildkite.com/materialize/nightlies/builds/1310#01842e5c-f101-420c-94ba-52dea294bfb3

**Comment by danhhz** [comment]
amazing, thank you Philip! this second case has the same "shape" as the one from yesterday, so that's good news at least

> it really feels to me like we're hitting the the limit of reasonable special cases we can/are comfortable with writing here. I'd already been wondering if it's time to take a step back and this is another argument in favor of that

we've gone back and forth on this quite a bit internally, and we're going to try one more targeted edge case fix (as paul put it: "three strikes") before we try anything radically different. then if we see anything after that, it's probably time to do something else. 

I think I've figured out a reasonable-ish way to fix these two cases, which I'll type up now

**Comment by danhhz** [comment]
@philip-stoev fixed those two instances with #15837, which just merged. I'm very interested to know if you see this again, please!

**Comment by philip-stoev** [comment]
Jeff Bezos is personally running Nightly like crazy in order to prove or disprove

**Comment by benesch** [comment]
What's the verdict?!

**Comment by philip-stoev** [comment]
I have not seen it over the past several days, and there have been a lot of machine hours expended. So I am closing this.
