### ISSUE TITLE
MZ stopped suddenly after submitting queries

### ISSUE THREAD

**Issue by ozgenbaris1** [MaterializeInc/materialize#15496]
### What version of Materialize are you using?

v0.26.4

### How did you install Materialize?

APT package

### What is the issue?

I'm using MZ as linux systemd service and consuming debezium envelope sources. I submitted some queries in Materialize to my materialized views. Suddenly, service stopped. Syslogs output can be found below. There were some personal data, so I replaced them with XXXXX and YYYYY

### Relevant log output

```source
2022-10-18T08:45:40.975210Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("XXXXXXXXXXXXXX")]}, 224484257)#011value: [Row{[Int64(18149279)]}, Row{[Int64(18149279)]}]#011count: -1
2022-10-18T08:45:40.977636Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("YYYYYYYYYYYYYY")]}, 109985839)#011value: [Row{[Int64(18080830)]}, Row{[Int64(18080830)]}]#011count: -1
2022-10-18T08:45:40.996350Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("XXXXXXXXXXXXXX")]}, 6380449)#011value: [Row{[Int64(18149279)]}, Row{[Int64(18149279)]}]#011count: -1
2022-10-18T08:45:40.997029Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("YYYYYYYYYYYYYY")]}, 9322543)#011value: [Row{[Int64(18080830)]}, Row{[Int64(18080830)]}]#011count: -1
2022-10-18T08:45:41.003159Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("XXXXXXXXXXXXXX")]}, 88993)#011value: [Row{[Int64(18149279)]}, Row{[Int64(18149279)]}]#011count: -1
2022-10-18T08:45:41.003812Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("YYYYYYYYYYYYYY")]}, 933935)#011value: [Row{[Int64(18080830)]}, Row{[Int64(18080830)]}]#011count: -1
2022-10-18T08:45:41.013893Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("XXXXXXXXXXXXXX")]}, 23457)#011value: [Row{[Int64(18149279)]}, Row{[Int64(18149279)]}]#011count: -1
2022-10-18T08:45:41.014682Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("YYYYYYYYYYYYYY")]}, 16431)#011value: [Row{[Int64(18080830)]}, Row{[Int64(18080830)]}]#011count: -1
2022-10-18T08:45:41.018395Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("XXXXXXXXXXXXXX")]}, 2977)#011value: [Row{[Int64(18149279)]}, Row{[Int64(18149279)]}]#011count: -1
2022-10-18T08:45:41.019040Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("YYYYYYYYYYYYYY")]}, 47)#011value: [Row{[Int64(18080830)]}, Row{[Int64(18080830)]}]#011count: -1
2022-10-18T08:45:41.021987Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("XXXXXXXXXXXXXX")]}, 161)#011value: [Row{[Int64(18149279)]}, Row{[Int64(18149279)]}]#011count: -1
2022-10-18T08:45:41.022661Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("YYYYYYYYYYYYYY")]}, 47)#011value: [Row{[Int64(18080830)]}, Row{[Int64(18080830)]}]#011count: -1
2022-10-18T08:45:41.024761Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("XXXXXXXXXXXXXX")]}, 1)#011value: [Row{[Int64(18149279)]}, Row{[Int64(18149279)]}]#011count: -1
2022-10-18T08:45:41.025384Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[String("YYYYYYYYYYYYYY")]}, 15)#011value: [Row{[Int64(18080830)]}, Row{[Int64(18080830)]}]#011count: -1
2022-10-18T08:45:41.026985Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Negative accumulation in ReduceMinsMaxes: [Row{[Int64(18149279)]}, Row{[Int64(18149279)]}] with count -1
2022-10-18T08:45:41.027870Z ERROR mz_dataflow::compute::render::reduce: [customer-data] Negative accumulation in ReduceMinsMaxes: [Row{[Int64(18080830)]}, Row{[Int64(18080830)]}] with count -1
2022-10-18T08:45:43.735913Z ERROR panic: called `Option::unwrap()` on a `None` value
thread: timely:work-0
location: src/dataflow/src/compute/render/reduce.rs:346:65
version: 0.26.5 (8d61044d9fa2ae92e74fca378b6cd7e34dd5ed7e)
backtrace:
   0: materialized::handle_panic
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033030de59e0a1b31-1/materialize/tests/src/materialized/src/bin/materialized/main.rs:1010:21
   1: core::ops::function::Fn::call
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:70:5
   2: std::panicking::rust_panic_with_hook
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:610:17
   3: std::panicking::begin_panic_handler::{{closure}}
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:500:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:139:18
   5: rust_begin_unwind
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   6: core::panicking::panic_fmt
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   7: core::panicking::panic
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:48:5
   8: mz_dataflow::compute::render::reduce::build_collation::{{closure}}
      differential_dataflow::operators::reduce::ReduceCore::reduce_abelian::{{closure}}
             at cargo/git/checkouts/differential-dataflow-d065d23d797aa027/27492f2/src/operators/reduce.rs:291:21
      <differential_dataflow::operators::reduce::history_replay::HistoryReplayer<V1,V2,T,R1,R2> as differential_dataflow::operators::reduce::PerKeyCompute<V1,V2,T,R1,R2>>::compute
             at cargo/git/checkouts/differential-dataflow-d065d23d797aa027/27492f2/src/operators/reduce.rs:946:29
   9: <differential_dataflow::operators::arrange::arrangement::Arranged<G,T1> as differential_dataflow::operators::reduce::ReduceCore<G,K,V,R>>::reduce_core::{{closure}}::{{closure}}
             at cargo/git/checkouts/differential-dataflow-d065d23d797aa027/27492f2/src/operators/reduce.rs:538:49
  10: <timely::dataflow::stream::StreamCore<G,D1> as timely::dataflow::operators::generic::operator::Operator<G,D1>>::unary_frontier::{{closure}}::{{closure}}
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/dataflow/operators/generic/operator.rs:351:17
      timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/dataflow/operators/generic/builder_rc.rs:123:31
      timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/dataflow/operators/generic/builder_rc.rs:162:26
      <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/dataflow/operators/generic/builder_raw.rs:204:9
  11: timely::progress::subgraph::PerOperatorState<T>::schedule
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/progress/subgraph.rs:684:30
  12: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/progress/subgraph.rs:344:26
      <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/progress/subgraph.rs:310:17
  13: timely::progress::subgraph::PerOperatorState<T>::schedule
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/progress/subgraph.rs:684:30
  14: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/progress/subgraph.rs:344:26
      <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/progress/subgraph.rs:310:17
  15: timely::worker::Wrapper::step::{{closure}}
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/worker.rs:754:57
      core::option::Option<T>::map
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/option.rs:883:29
      timely::worker::Wrapper::step
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/worker.rs:754:26
  16: timely::worker::Worker<A>::step_or_park
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/worker.rs:396:38
  17: mz_dataflow::server::Worker<A,SC,CR>::run
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033030de59e0a1b31-1/materialize/tests/src/dataflow/src/server.rs:297:13
  18: mz_dataflow::server::serve_boundary::{{closure}}
             at var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033030de59e0a1b31-1/materialize/tests/src/dataflow/src/server.rs:175:9
      timely::execute::execute::{{closure}}
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/timely/src/execute.rs:287:22
      timely_communication::initialize::initialize_from::{{closure}}
             at cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/c4145f0/communication/src/initialize.rs:316:33
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:123:18
  19: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/mod.rs:477:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
      std::panicking::try
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
      std::panic::catch_unwind
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
      std::thread::Builder::spawn_unchecked::{{closure}}
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/mod.rs:476:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
  20: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/boxed.rs:1854:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/boxed.rs:1854:9
      std::sys::unix::thread::Thread::new::thread_start
             at rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys/unix/thread.rs:108:17
  21: <unknown>
  22: <unknown>
materialized encountered an internal error and crashed.
We rely on bug reports to diagnose and fix these errors. Please
copy and paste the above details and file a report at:
    https://materialize.com/s/bug
```

**Comment by frankmcsherry** [comment]
As a heads up while we investigate, the errors printed almost certainly mean that the DBZ data that arrived included retractions for records that were not added (records present in `before` that were not present previously in `after`). This ... happens with Debezium, and has a few imperfect work arounds. You may be able to use the "debezium upsert" envelope, if you know that your data come with a presented primary key. You can read about that in the LTS docs here (for Kafka): https://materialize.com/docs/lts/sql/create-source/kafka/#syntax.

**Comment by teskje** [comment]
@ozgenbaris1 Any chance you could provide the SQL of your materialized views and the queries you have ran against them, that produced this crash (in an anonymized form)? Staring at the code I can't see how this panic can happen, so it would be great to be able to reproduce it.

**Comment by vmarcos** [comment]
The following reproduction of the error builds on `test/testdrive/negative-multiplicities.td` and requires us to run Materialize with `--unsafe-mode`. Note that the latter is required to make it easy to create the data with too many retractions; it is also possible to trigger the behaviors below if, e.g., too many retractions get into a source outside of unsafe mode.

First, set up the test data:

```sql
CREATE TABLE base (data bigint, diff bigint);
CREATE MATERIALIZED VIEW data AS SELECT data FROM base, repeat_row(diff);
INSERT INTO base VALUES (1, 1);
INSERT INTO base VALUES (1, -1), (1, -1);
```

Now, you should be able to observe the following:

```sql
materialize=> SELECT SUM(data), MAX(data) FROM data;
NOTICE:  cluster replica default.r1 changed status to "not-ready" at 2023-02-03 11:03:55.19994+00
HINT:  The cluster replica may be restarting or going offline.
NOTICE:  cluster replica default.r1 changed status to "ready" at 2023-02-03 11:04:00.205315+00
NOTICE:  cluster replica default.r1 changed status to "not-ready" at 2023-02-03 11:04:03.178106+00
HINT:  The cluster replica may be restarting or going offline.
^CCancel request sent
ERROR:  canceling statement due to user request
Time: 9918.363 ms (00:09.918)
materialize=> SELECT * FROM data;
NOTICE:  cluster replica default.r1 changed status to "ready" at 2023-02-03 11:04:08.183784+00
ERROR:  Invalid data in source, saw retractions (1) for row that does not exist: [Int64(1)]
Time: 13.650 ms
```

The logs show the following:

```
cluster-u1-replica-1: 2023-02-03T11:05:41.251121Z  INFO tokio_postgres::connection: NOTICE: relation "consensus" already exists, skipping    
cluster-u1-replica-1: 2023-02-03T11:05:41.269036Z  WARN mz_compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[]}, 45655161)	value: [Row{[Int64(1)]}]	count: -1 in dataflow temp-view-t2
cluster-u1-replica-1: 2023-02-03T11:05:41.269053Z ERROR mz_compute::render::reduce: Non-positive accumulation in MinsMaxesHierarchical
cluster-u1-replica-1: 2023-02-03T11:05:41.269202Z  WARN mz_compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[]}, 12100729)	value: [Row{[Int64(1)]}]	count: -1 in dataflow temp-view-t2
cluster-u1-replica-1: 2023-02-03T11:05:41.269212Z ERROR mz_compute::render::reduce: Non-positive accumulation in MinsMaxesHierarchical
cluster-u1-replica-1: 2023-02-03T11:05:41.269264Z  WARN mz_compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[]}, 566393)	value: [Row{[Int64(1)]}]	count: -1 in dataflow temp-view-t2
cluster-u1-replica-1: 2023-02-03T11:05:41.269269Z ERROR mz_compute::render::reduce: Non-positive accumulation in MinsMaxesHierarchical
cluster-u1-replica-1: 2023-02-03T11:05:41.269316Z  WARN mz_compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[]}, 42105)	value: [Row{[Int64(1)]}]	count: -1 in dataflow temp-view-t2
cluster-u1-replica-1: 2023-02-03T11:05:41.269319Z ERROR mz_compute::render::reduce: Non-positive accumulation in MinsMaxesHierarchical
cluster-u1-replica-1: 2023-02-03T11:05:41.269360Z  WARN mz_compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[]}, 1145)	value: [Row{[Int64(1)]}]	count: -1 in dataflow temp-view-t2
cluster-u1-replica-1: 2023-02-03T11:05:41.269363Z ERROR mz_compute::render::reduce: Non-positive accumulation in MinsMaxesHierarchical
cluster-u1-replica-1: 2023-02-03T11:05:41.269401Z  WARN mz_compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[]}, 121)	value: [Row{[Int64(1)]}]	count: -1 in dataflow temp-view-t2
cluster-u1-replica-1: 2023-02-03T11:05:41.269405Z ERROR mz_compute::render::reduce: Non-positive accumulation in MinsMaxesHierarchical
cluster-u1-replica-1: 2023-02-03T11:05:41.269443Z  WARN mz_compute::render::reduce: [customer-data] Non-positive accumulation in MinsMaxesHierarchical: key: (Row{[]}, 9)	value: [Row{[Int64(1)]}]	count: -1 in dataflow temp-view-t2
cluster-u1-replica-1: 2023-02-03T11:05:41.269448Z ERROR mz_compute::render::reduce: Non-positive accumulation in MinsMaxesHierarchical
cluster-u1-replica-1: 2023-02-03T11:05:41.269580Z  WARN mz_compute::render::reduce: [customer-data] Negative accumulation in ReduceMinsMaxes: [Row{[Int64(1)]}] with count -1 in dataflow temp-view-t2
cluster-u1-replica-1: 2023-02-03T11:05:41.269584Z ERROR mz_compute::render::reduce: Negative accumulation in ReduceMinsMaxes
thread 'timely:work-0' panicked at '[customer-data] Missing Hierarchical value for key: () in dataflow temp-view-t2', src/compute/src/render/reduce.rs:380:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: <differential_dataflow::operators::reduce::history_replay::HistoryReplayer<V1,V2,T,R1,R2> as differential_dataflow::operators::reduce::PerKeyCompute<V1,V2,T,R1,R2>>::compute
   3: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
   4: <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
   5: timely::progress::subgraph::PerOperatorState<T>::schedule
   6: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
   7: timely::progress::subgraph::PerOperatorState<T>::schedule
   8: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
   9: timely::progress::subgraph::PerOperatorState<T>::schedule
  10: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
  11: timely::worker::Wrapper::step
  12: timely::worker::Worker<A>::step_or_park
  13: mz_compute::server::Worker<A>::run
```
