### ISSUE TITLE
failed: initial_len >= self.len() persist-client/src/internal/trace.rs:414:25

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#15498]
### What version of Materialize are you using?

99c1ede02a2d09bb5de264082d5f3b6cfa2396f0

### How did you install Materialize?

Docker image

### What is the issue?

```
thread 'tokio-runtime-worker' panicked at 'assertion failed: initial_len >= self.len()', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d8ae7a13db495a09-1/materialize/tests/src/persist-client/src/internal/trace.rs:414:25
```

**Comment by philip-stoev** [comment]
To reproduce, clone `gh15498` from `philip-stoev:materialize` and try:

```
cd test/bounded-memory.py
while bash -c -e "./mzcompose down -v ; ./mzcompose run default  " ;  do : ; done
```

The test does not perform restarts and does not restrict memory in any way. The problem is that:
- you need to run the loop 10 times or more to get it to panic
- the panic is survivable, that is, the test succeeds and then mzcompose down -v will tear down the environment.

**Comment by aljoscha** [comment]
@pH14 could you please take a look? This is related to the recent compaction changes, I believe.

cc @danhhz

**Comment by philip-stoev** [comment]
Full stack trace:

```
hread 'tokio-runtime-worker' panicked at 'assertion failed: self.len() >= res.output.len', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d8ae7a13db495a09-1/materialize/tests/src/persist-client/src/internal/trace.rs:370:13
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:48:5
   3: mz_persist_client::internal::trace::SpineBatch<T>::maybe_replace
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d8ae7a13db495a09-1/materialize/tests/src/persist-client/src/internal/trace.rs:370:13
   4: mz_persist_client::internal::trace::Trace<T>::apply_merge_res
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d8ae7a13db495a09-1/materialize/tests/src/persist-client/src/internal/trace.rs:223:34
   5: mz_persist_client::internal::state::StateCollections<T>::apply_merge_res
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d8ae7a13db495a09-1/materialize/tests/src/persist-client/src/internal/state.rs:284:34
   6: mz_persist_client::internal::machine::Machine<K,V,T,D>::merge_res::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d8ae7a13db495a09-1/materialize/tests/src/persist-client/src/internal/machine.rs:307:27
   7: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:290:13
   8: mz_persist_client::internal::state::State<K,V,T,D>::clone_apply
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d8ae7a13db495a09-1/materialize/tests/src/persist-client/src/internal/state.rs:627:24
   9: mz_persist_client::internal::machine::Machine<K,V,T,D>::apply_unbatched_cmd::{{closure}}::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d8ae7a13db495a09-1/materialize/tests/src/persist-client/src/internal/machine.rs:535:55
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  11: mz_persist_client::internal::metrics::CmdMetrics::run_cmd::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d8ae7a13db495a09-1/materialize/tests/src/persist-client/src/internal/metrics.rs:466:74
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  13: mz_persist_client::internal::machine::Machine<K,V,T,D>::apply_unbatched_cmd::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d8ae7a13db495a09-1/materialize/tests/src/persist-client/src/internal/machine.rs:678:11
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  15: mz_persist_client::internal::machine::Machine<K,V,T,D>::apply_unbatched_idempotent_cmd::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d8ae7a13db495a09-1/materialize/tests/src/persist-client/src/internal/machine.rs:503:62
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  17: mz_persist_client::internal::machine::Machine<K,V,T,D>::merge_res::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d8ae7a13db495a09-1/materialize/tests/src/persist-client/src/internal/machine.rs:314:15
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  19: mz_persist_client::internal::compact::Compactor<T,D>::new::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d8ae7a13db495a09-1/materialize/tests/src/persist-client/src/internal/compact.rs:170:58
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  21: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
  22: mz_persist_client::internal::compact::Compactor<T,D>::new::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d8ae7a13db495a09-1/materialize/tests/src/persist-client/src/internal/compact.rs:203:42
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  24: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:165:17
  25: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/loom/std/unsafe_cell.rs:14:9
  26: tokio::runtime::task::core::CoreStage<T>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:155:13
  27: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:480:19
  28: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panic/unwind_safe.rs:271:9
  29: std::panicking::try::do_call
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  30: std::panicking::try
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  31: std::panic::catch_unwind
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  32: tokio::runtime::task::harness::poll_future
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:468:18
  33: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:104:27
  34: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:57:15
  35: tokio::runtime::task::raw::RawTask::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/raw.rs:84:18
  36: tokio::runtime::task::LocalNotified<S>::run
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/mod.rs:381:9
  37: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:458:21
  38: tokio::coop::with_budget::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:102:9
  39: std::thread::local::LocalKey<T>::try_with
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:445:16
  40: std::thread::local::LocalKey<T>::with
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:421:9
  41: tokio::coop::with_budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:95:5
  42: tokio::coop::budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:72:5
  43: tokio::runtime::thread_pool::worker::Context::run_task
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:434:9
  44: tokio::runtime::thread_pool::worker::Context::run
  45: tokio::runtime::thread_pool::worker::run::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:386:17
  46: tokio::macros::scoped_tls::ScopedKey<T>::set
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/macros/scoped_tls.rs:61:9
  47: tokio::runtime::thread_pool::worker::run
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:383:5
  48: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:362:45
  49: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/task.rs:42:21
  50: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:165:17
  51: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/loom/std/unsafe_cell.rs:14:9
  52: tokio::runtime::task::core::CoreStage<T>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:155:13
  53: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:480:19
  54: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panic/unwind_safe.rs:271:9
  55: std::panicking::try::do_call
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  56: std::panicking::try
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  57: std::panic::catch_unwind
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  58: tokio::runtime::task::harness::poll_future
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:468:18
  59: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:104:27
  60: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:57:15
  61: tokio::runtime::task::raw::RawTask::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/raw.rs:84:18
  62: tokio::runtime::task::UnownedTask<S>::run
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/mod.rs:418:9
  63: tokio::runtime::blocking::pool::Task::run
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/pool.rs:91:9
  64: tokio::runtime::blocking::pool::Inner::run
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/pool.rs:325:17
  65: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/pool.rs:300:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by pH14** [comment]
Ah https://github.com/MaterializeInc/materialize/issues/14670 is back! I've tried to trigger this one but haven't succeeded. Thanks for the repro, I'll take a look

**Comment by pH14** [comment]
I was able to repro locally after 20+ test runs and watching the logs... @philip-stoev how did you even see this error since the test survives the panic??

**Comment by danhhz** [comment]
given the timing, I suspect https://github.com/MaterializeInc/materialize/pull/15375

rough sketch for one way this might play out:
- send out compaction request 1 for a,b, starts with A+B updates and reduces down to X updates less than A+B
- send out compaction request 2 for a,b,c, starts with A+B+C updates and reduces down to Y+C, where X < Y <= A+B (and C'<=C). I think this can only happen with bounded mem compaction
- compaction request 1 applies, we have X+C updates in the SpineBatch
- compaction request 2 applies, we have Y+C' updates in the SpineBatch

**Comment by pH14** [comment]
Added some more debugging lines and can confirm Dan's hypothesis. Shouldn't be a hard fix, we can replace the assertion with a no-op for when `maybe_replace` would increase the # of updates in spine

**Comment by philip-stoev** [comment]
> @philip-stoev how did you even see this error since the test survives the panic??

It came to me in a malaria-induced fever dream...

Seriously, I was watching the logs when I saw it fly by -- and it was only because storaged could not be restarted in time because of an impending `computed` OOM. But this does point to a general problem with all the restartable panics -- we may need a special testing mode to the orchestrators where they will not restart stuff on panic so that any panics are made explicit and not survivable.
