### ISSUE TITLE
crash loop panic: cannot downgrade in reclock: DowngradeError(()) with SIZE 4

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#15558]
### What version of Materialize are you using?

53b8e8af6f453667945a38b4c7c50feb9a45726b

### How did you install Materialize?

Docker image

### What is the issue?

Running the entire testdrive with SIZE 4 results in the following failure:

https://buildkite.com/materialize/tests/builds/43580#0183f50a-6f90-4d24-ac6d-837641bae0b7

It is this panic in a **crash loop**:

```
pg-cdc-resumption-materialized-1  | thread 'thread 'timely:work-1timely:work-0' panicked at '' panicked at 'cannot downgrade in reclock: DowngradeError(())cannot downgrade in reclock: DowngradeError(())', ', src/storage/src/source/source_reader_pipeline.rssrc/storage/src/source/source_reader_pipeline.rs::13381338::2626
````

To reproduce, use this PR https://github.com/MaterializeInc/materialize/pull/15553 and then run the pg-cdc-resumption test in a loop?

### Relevant log output

```source
pg-cdc-resumption-materialized-1  | thread 'thread 'timely:work-1timely:work-0' panicked at '' panicked at 'cannot downgrade in reclock: DowngradeError(())cannot downgrade in reclock: DowngradeError(())', ', src/storage/src/source/source_reader_pipeline.rssrc/storage/src/source/source_reader_pipeline.rs::13381338::2626
pg-cdc-resumption-materialized-1  | 
pg-cdc-resumption-materialized-1  | stack backtrace:
pg-cdc-resumption-materialized-1  |    0: rust_begin_unwind
pg-cdc-resumption-materialized-1  |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
pg-cdc-resumption-materialized-1  |    1: core::panicking::panic_fmt
pg-cdc-resumption-materialized-1  |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
pg-cdc-resumption-materialized-1  |    2: core::result::unwrap_failed
pg-cdc-resumption-materialized-1  |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1814:5
pg-cdc-resumption-materialized-1  |    3: core::result::Result<T,E>::expect
pg-cdc-resumption-materialized-1  |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1064:23
pg-cdc-resumption-materialized-1  |    4: mz_storage::source::source_reader_pipeline::reclock_operator::{{closure}}::{{closure}}
pg-cdc-resumption-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-030218af2528edf2b-1/materialize/tests/src/storage/src/source/source_reader_pipeline.rs:1336:21
pg-cdc-resumption-materialized-1  |    5: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}
pg-cdc-resumption-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/dataflow/operators/generic/builder_rc.rs:123:31
pg-cdc-resumption-materialized-1  |    6: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
pg-cdc-resumption-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/dataflow/operators/generic/builder_rc.rs:162:26
pg-cdc-resumption-materialized-1  |    7: <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
pg-cdc-resumption-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/dataflow/operators/generic/builder_raw.rs:204:9
pg-cdc-resumption-materialized-1  |    8: timely::progress::subgraph::PerOperatorState<T>::schedule
pg-cdc-resumption-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/progress/subgraph.rs:684:30
pg-cdc-resumption-materialized-1  |    9: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
pg-cdc-resumption-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/progress/subgraph.rs:344:26
pg-cdc-resumption-materialized-1  |   10: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
pg-cdc-resumption-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/progress/subgraph.rs:310:17
pg-cdc-resumption-materialized-1  |   11: timely::progress::subgraph::PerOperatorState<T>::schedule
pg-cdc-resumption-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/progress/subgraph.rs:684:30
pg-cdc-resumption-materialized-1  |   12: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
pg-cdc-resumption-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/progress/subgraph.rs:344:26
pg-cdc-resumption-materialized-1  |   13: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
pg-cdc-resumption-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/progress/subgraph.rs:310:17
pg-cdc-resumption-materialized-1  |   14: timely::worker::Wrapper::step::{{closure}}
pg-cdc-resumption-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/worker.rs:754:57
pg-cdc-resumption-materialized-1  |   15: core::option::Option<T>::map
pg-cdc-resumption-materialized-1  |              at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/option.rs:929:29
pg-cdc-resumption-materialized-1  |   16: timely::worker::Wrapper::step
pg-cdc-resumption-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/worker.rs:754:26
pg-cdc-resumption-materialized-1  |   17: timely::worker::Worker<A>::step_or_park
pg-cdc-resumption-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/worker.rs:396:38
pg-cdc-resumption-materialized-1  |   18: mz_storage::storage_state::Worker<A>::run_client
pg-cdc-resumption-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-030218af2528edf2b-1/materialize/tests/src/storage/src/storage_state.rs:134:17
pg-cdc-resumption-materialized-1  |   19: mz_storage::storage_state::Worker<A>::run
pg-cdc-resumption-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-030218af2528edf2b-1/materialize/tests/src/storage/src/storage_state.rs:110:33
pg-cdc-resumption-materialized-1  |   20: mz_storage::protocol::server::serve::{{closure}}
pg-cdc-resumption-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-030218af2528edf2b-1/materialize/tests/src/storage/src/protocol/server.rs:94:9
pg-cdc-resumption-materialized-1  |   21: timely::execute::execute::{{closure}}
pg-cdc-resumption-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/timely/src/execute.rs:287:22
pg-cdc-resumption-materialized-1  |   22: timely_communication::initialize::initialize_from::{{closure}}
pg-cdc-resumption-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/communication/src/initialize.rs:316:33
pg-cdc-resumption-materialized-1  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
pg-cdc-resumption-materialized-1  | stack backtrace:
pg-cdc-resumption-materialized-1  |  environmentd: 2022-10-20T11:04:36.815436Z  WARN mz_storage::controller::rehydration: storage host produced error, reconnecting: status: Unknown, message: "error reading a body from connection: broken pipe", details: [], metadata: MetadataMap { headers: {} }
```

**Comment by aljoscha** [comment]
@philip-stoev Leaving this open so you can close when you evaluated the fixes, ok?

**Comment by aljoscha** [comment]
@philip-stoev is at least this bug resolve in your 4-worker testing? 🤞

**Comment by benesch** [comment]
Calling this one closed because CI is now running at SIZE 4 by default.
