### ISSUE TITLE
persist_source: "cannot serve requested as_of Antichain" in `mz_system` cluster in staging environment

### ISSUE THREAD

**Issue by vmarcos** [MaterializeInc/materialize#15566]
### What version of Materialize are you using?

v0.28.4 (200849889)

### How did you install Materialize?

Materialize Cloud

### What is the issue?

After staging upgrade to v0.28.4, we observe one of our environments to experience repeated crashes of the `mz_system` cluster.

The relevant environment and crash period can be found in [Graphana](https://g-2531aff0fb.grafana-workspace.us-east-1.amazonaws.com/d/UT2whmGVk/kube-pod-metrics?orgId=1&var-datasource=cloud-staging+us-east-1&var-namespace=environment-2841fd99-dff9-4dde-be85-4f624dd369de-0&var-pod=All&from=1666190322500&to=1666276722500&viewPanel=2). Additional logs can be found in [Honeycomb](https://ui.honeycomb.io/materialize/datasets/staging.console-logs/result/HPFfL8ZCwYU).

The environment still has persist introspection source active that existed prior to their deactivation by #15422.

Eventually, the `mz_system` cluster was able to come back online, after a few hours. The environment then enters a growing memory allocation pattern, especially in the pods containing `environmentd`, the `mz_system` cluster, and the `mz_introspection` cluster.

The issue may be related to #15426 and to #15354. Unlike the error seen in #15426, the present error happened on a cluster with only one replica.

### Relevant log output

```source
2022-10-20T02:00:07.303815Z  INFO computed: about to bind to 0.0.0.0:2100
2022-10-20T02:00:07.303847Z  INFO computed: serving internal HTTP server on 0.0.0.0:6878
2022-10-20T02:00:07.304652Z  INFO mz_service::grpc: Starting to listen on 0.0.0.0:2100
2022-10-20T02:00:25.050725Z  INFO mz_service::grpc: GrpcServer: remote client connected
2022-10-20T02:00:25.053281Z  INFO mz_compute::communication: initialization complete worker=0
2022-10-20T02:00:25.076550Z  INFO provide_credentials{provider=default_chain}: aws_http::auth: provider returned CredentialsNotLoaded, ignoring
2022-10-20T02:00:25.709735Z  INFO tokio_postgres::connection: NOTICE: relation "consensus" already exists, skipping    
thread 'tokio-runtime-worker' panicked at 's285: cannot serve requested as_of Antichain { elements: [1666230915057] }: Since(Antichain { elements: [1666230972000] })', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/storage/src/source/persist_source.rs:230:24
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: mz_storage::source::persist_source::persist_source_core::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/storage/src/source/persist_source.rs:230:24
   3: core::result::Result<T,E>::unwrap_or_else
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1493:23
   4: mz_storage::source::persist_source::persist_source_core::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/async-stream-0.3.3/src/lib.rs:237:9
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
   6: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/async-stream-0.3.3/src/async_stream.rs:53:17
   7: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.24/src/stream.rs:120:9
   8: futures_util::stream::stream::StreamExt::poll_next_unpin
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.24/src/stream/stream/mod.rs:1626:9
   9: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.24/src/stream/stream/next.rs:32:9
  10: <mz_storage::source::persist_source::DropSafeLeaseStream as core::ops::drop::Drop>::drop::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/storage/src/source/persist_source.rs:147:55
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  12: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:165:17
  13: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/loom/std/unsafe_cell.rs:14:9
  14: tokio::runtime::task::core::CoreStage<T>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:155:13
  15: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:480:19
  16: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panic/unwind_safe.rs:271:9
  17: std::panicking::try::do_call
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  18: std::panicking::try
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  19: std::panic::catch_unwind
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  20: tokio::runtime::task::harness::poll_future
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:468:18
  21: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:104:27
  22: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:57:15
  23: tokio::runtime::task::raw::RawTask::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/raw.rs:84:18
  24: tokio::runtime::task::LocalNotified<S>::run
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/mod.rs:381:9
  25: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:458:21
  26: tokio::coop::with_budget::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:102:9
  27: std::thread::local::LocalKey<T>::try_with
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:445:16
  28: std::thread::local::LocalKey<T>::with
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:421:9
  29: tokio::coop::with_budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:95:5
  30: tokio::coop::budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:72:5
  31: tokio::runtime::thread_pool::worker::Context::run_task
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:434:9
  32: tokio::runtime::thread_pool::worker::Context::run
  33: tokio::runtime::thread_pool::worker::run::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:386:17
  34: tokio::macros::scoped_tls::ScopedKey<T>::set
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/macros/scoped_tls.rs:61:9
  35: tokio::runtime::thread_pool::worker::run
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:383:5
  36: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/thread_pool/worker.rs:362:45
  37: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/task.rs:42:21
  38: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:165:17
  39: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/loom/std/unsafe_cell.rs:14:9
  40: tokio::runtime::task::core::CoreStage<T>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/core.rs:155:13
  41: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:480:19
  42: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panic/unwind_safe.rs:271:9
  43: std::panicking::try::do_call
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  44: std::panicking::try
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  45: std::panic::catch_unwind
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  46: tokio::runtime::task::harness::poll_future
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:468:18
  47: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:104:27
  48: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/harness.rs:57:15
  49: tokio::runtime::task::raw::RawTask::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/raw.rs:84:18
  50: tokio::runtime::task::UnownedTask<S>::run
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/task/mod.rs:418:9
  51: tokio::runtime::blocking::pool::Task::run
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/pool.rs:91:9
  52: tokio::runtime::blocking::pool::Inner::run
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/pool.rs:325:17
  53: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/blocking/pool.rs:300:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by teskje** [comment]
As mentioned in Slack, I think this is a compute issue, not storage. We can handle it as part of #15426.
