### ISSUE TITLE
thread 'coordinator' panicked at 'index out of bounds: the len is 7 but the index is 8', src/expr/src/scalar/mod.rs:1533:41

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#15570]
### What version of Materialize are you using?

0.28.4

### How did you install Materialize?

Materialize Cloud

### What is the issue?

```
thread 'coordinator' panicked at 'index out of bounds: the len is 7 but the index is 8', src/expr/src/scalar/mod.rs:1533:41
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_bounds_check
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:84:5
   3: mz_expr::scalar::MirScalarExpr::typ
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/scalar/mod.rs:1533:41
   4: mz_expr::scalar::MirScalarExpr::typ
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/scalar/mod.rs:1536:73
   5: mz_expr::scalar::MirScalarExpr::reduce::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/scalar/mod.rs:913:66
   6: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::position
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/slice/iter/macros.rs:295:24
   7: mz_expr::scalar::MirScalarExpr::reduce::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/scalar/mod.rs:911:46
   8: <T as mz_expr::visit::Visit>::visit_mut_pre_post_nolimit
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/visit.rs:403:9
   9: mz_expr::scalar::MirScalarExpr::reduce
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/scalar/mod.rs:500:13
  10: mz_transform::column_knowledge::optimize::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/transform/src/column_knowledge.rs:494:25
  11: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/visit.rs:644:13
  12: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:191:33
  13: stacker::maybe_grow
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  14: mz_ore::stack::maybe_grow
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:100:5
  15: mz_ore::stack::CheckedRecursion::checked_recur
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:191:19
  16: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/visit.rs:636:9
  17: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::VisitChildren<mz_expr::scalar::MirScalarExpr>>::try_visit_mut_children
  18: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/visit.rs:642:17
  19: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:191:33
  20: stacker::maybe_grow
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  21: mz_ore::stack::maybe_grow
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:100:5
  22: mz_ore::stack::CheckedRecursion::checked_recur
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:191:19
  23: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/visit.rs:636:9
  24: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/visit.rs:642:54
  25: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::VisitChildren<mz_expr::scalar::MirScalarExpr>>::try_visit_mut_children
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/scalar/mod.rs:1785:17
  26: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/visit.rs:642:17
  27: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:191:33
  28: stacker::maybe_grow
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  29: mz_ore::stack::maybe_grow
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:100:5
  30: mz_ore::stack::CheckedRecursion::checked_recur
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:191:19
  31: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/visit.rs:636:9
  32: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/visit.rs:642:54
  33: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::VisitChildren<mz_expr::scalar::MirScalarExpr>>::try_visit_mut_children
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/scalar/mod.rs:1785:17
  34: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/visit.rs:642:17
  35: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:191:33
  36: stacker::maybe_grow
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  37: mz_ore::stack::maybe_grow
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:100:5
  38: mz_ore::stack::CheckedRecursion::checked_recur
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:191:19
  39: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/visit.rs:636:9
  40: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::VisitChildren<mz_expr::scalar::MirScalarExpr>>::try_visit_mut_children
  41: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/visit.rs:642:17
  42: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:191:33
  43: stacker::maybe_grow
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  44: mz_ore::stack::maybe_grow
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:100:5
  45: mz_ore::stack::CheckedRecursion::checked_recur
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:191:19
  46: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/visit.rs:636:9
  47: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::VisitChildren<mz_expr::scalar::MirScalarExpr>>::try_visit_mut_children
  48: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/visit.rs:642:17
  49: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:191:33
  50: stacker::maybe_grow
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  51: mz_ore::stack::maybe_grow
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:100:5
  52: mz_ore::stack::CheckedRecursion::checked_recur
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:191:19
  53: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/visit.rs:636:9
  54: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/visit.rs:642:54
  55: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::VisitChildren<mz_expr::scalar::MirScalarExpr>>::try_visit_mut_children
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/scalar/mod.rs:1785:17
  56: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/visit.rs:642:17
  57: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:191:33
  58: stacker::maybe_grow
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  59: mz_ore::stack::maybe_grow
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:100:5
  60: mz_ore::stack::CheckedRecursion::checked_recur
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:191:19
  61: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/visit.rs:636:9
  62: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/visit.rs:642:54
  63: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::VisitChildren<mz_expr::scalar::MirScalarExpr>>::try_visit_mut_children
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/scalar/mod.rs:1785:17
  64: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/visit.rs:642:17
  65: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:191:33
  66: stacker::maybe_grow
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  67: mz_ore::stack::maybe_grow
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:100:5
  68: mz_ore::stack::CheckedRecursion::checked_recur
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:191:19
  69: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/visit.rs:636:9
  70: <T as mz_expr::visit::Visit>::visit_mut_pre_post
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/expr/src/visit.rs:395:9
  71: mz_transform::column_knowledge::optimize
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/transform/src/column_knowledge.rs:444:5
  72: mz_transform::column_knowledge::ColumnKnowledge::harvest::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/transform/src/column_knowledge.rs:124:36
  73: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:191:33
  74: stacker::maybe_grow
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  75: mz_ore::stack::maybe_grow
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:100:5
  76: mz_ore::stack::CheckedRecursion::checked_recur
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:191:19
  77: mz_transform::column_knowledge::ColumnKnowledge::harvest
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/transform/src/column_knowledge.rs:77:9
  78: mz_transform::column_knowledge::ColumnKnowledge::harvest::{{closure}}
  79: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:191:33
  80: stacker::maybe_grow
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  81: mz_ore::stack::maybe_grow
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:100:5
  82: mz_ore::stack::CheckedRecursion::checked_recur
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:191:19
  83: mz_transform::column_knowledge::ColumnKnowledge::harvest
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/transform/src/column_knowledge.rs:77:9
  84: mz_transform::column_knowledge::ColumnKnowledge::harvest::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/transform/src/column_knowledge.rs:114:43
  85: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:191:33
  86: stacker::maybe_grow
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  87: mz_ore::stack::maybe_grow
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:100:5
  88: mz_ore::stack::CheckedRecursion::checked_recur
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/ore/src/stack.rs:191:19
  89: mz_transform::column_knowledge::ColumnKnowledge::harvest
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/transform/src/column_knowledge.rs:77:9
  90: <mz_transform::column_knowledge::ColumnKnowledge as mz_transform::Transform>::transform
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/transform/src/column_knowledge.rs:59:22
  91: <mz_transform::Fixpoint as mz_transform::Transform>::transform::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/transform/src/lib.rs:181:25
  92: tracing::span::Span::in_scope
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/span.rs:1102:9
  93: <mz_transform::Fixpoint as mz_transform::Transform>::transform
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/transform/src/lib.rs:179:17
  94: mz_transform::Optimizer::transform
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/transform/src/lib.rs:495:13
  95: mz_transform::Optimizer::optimize
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/transform/src/lib.rs:467:32
  96: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_peek::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/adapter/src/coord/sequencer.rs:2162:22
  97: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
  98: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
  99: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_peek::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/adapter/src/coord/sequencer.rs:2006:5
 100: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
 101: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_plan::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/adapter/src/coord/sequencer.rs:252:63
 102: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
 103: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
 104: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_plan::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/adapter/src/coord/sequencer.rs:83:5
 105: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
 106: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute_inner::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/adapter/src/coord/command_handler.rs:452:78
 107: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
 108: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
 109: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute_inner::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/adapter/src/coord/command_handler.rs:254:5
 110: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
 111: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/adapter/src/coord/command_handler.rs:251:61
 112: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
 113: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
 114: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/adapter/src/coord/command_handler.rs:224:5
 115: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
 116: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
 117: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_command::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/adapter/src/coord/command_handler.rs:63:38
 118: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
 119: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_command::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/adapter/src/coord/message_handler.rs:151:33
 120: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
 121: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
 122: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_command::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/adapter/src/coord/message_handler.rs:148:5
 123: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
 124: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_message::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/adapter/src/coord/message_handler.rs:40:63
 125: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
 126: mz_adapter::coord::Coordinator<S>::serve::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/adapter/src/coord.rs:851:37
 127: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/future/mod.rs:91:19
 128: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/park/thread.rs:263:54
 129: tokio::coop::with_budget::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:102:9
 130: std::thread::local::LocalKey<T>::try_with
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:445:16
 131: std::thread::local::LocalKey<T>::with
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/thread/local.rs:421:9
 132: tokio::coop::with_budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:95:5
 133: tokio::coop::budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:72:5
 134: tokio::park::thread::CachedParkThread::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/park/thread.rs:263:31
 135: tokio::runtime::enter::Enter::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/enter.rs:152:13
 136: tokio::runtime::handle::Handle::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/handle.rs:297:9
 137: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0115e90b3ad66b732-1/materialize/tests/src/adapter/src/coord.rs:1000:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Stream closed EOF for environment-3c4d7891-8a99-4e54-89ae-773690b1c73a-0/environmentd-0 (environmentd)
```

**Comment by benesch** [comment]
I substantially reduced the reproduction that was shared privately with us. Here's an anonymized version:

```
CREATE TABLE events (data jsonb);
SELECT COALESCE(field, '') FROM (SELECT data->>'field' AS field FROM events);
```

**Comment by aalexandrov** [comment]
I will attempt a fix based on @ggevay's comments.
