### ISSUE TITLE
`test_secrets in test.cloudtest.test_secrets` is flaky

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#15579]
### Buildkite link

https://buildkite.com/materialize/tests/builds/43630#0183f6bb-1760-495d-a761-d608401c6811

### Relevant log output

```source
Traceback (most recent call last):
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-025de814e1ccbd4a6-1/materialize/tests/test/cloudtest/test_secrets.py", line 17, in test_secrets
    mz.testdrive.run(
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-025de814e1ccbd4a6-1/materialize/tests/misc/python/materialize/cloudtest/k8s/testdrive.py", line 54, in run
    subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['kubectl', '--context', 'kind-kind', 'exec', '-it', 'testdrive', '--', 'testdrive', '--materialize-url=postgres://materialize:materialize@environmentd:6875/materialize', '--materialize-internal-url=postgres://materialize:materialize@environmentd:6877/materialize', '--kafka-addr=redpanda:9092', '--schema-registry-url=http://redpanda:8081', '--default-timeout=300s', '--var=replicas=1', '--var=size=1', '--aws-region=us-east-2']' returned non-zero exit status 1.
```

**Comment by philip-stoev** [comment]
environmentd appears to have terminated the connection to testdrive during a ` CREATE SOURCE ` statement. No indication in the logs as to why this happened, but such cases where the connection between testdrive and environmentd gets dropped have been seen multiple times in the CI.

**Comment by philip-stoev** [comment]
This has not been seen in a while. Previously, there was a problem in our CI that older containers were left behind which would cause sporadic CI failures that could not be explained otherwise.
