### ISSUE TITLE
`test_crash_storaged` is flaky

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#15613]
### Buildkite link

https://buildkite.com/materialize/tests/builds/43764#018405c4-fb16-4786-8c84-6d65d7b3116c

### Relevant log output

```source
=================================== FAILURES ===================================
_____________________________ test_crash_storaged ______________________________
Traceback (most recent call last):
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-0d97bf0c91ffc50b4-1/materialize/tests/test/cloudtest/test_crash.py", line 93, in test_crash_storaged
    mz.kubectl("exec", pod_name, "--", "bash", "-c", "kill -9 `pidof storaged` || true")
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-0d97bf0c91ffc50b4-1/materialize/tests/misc/python/materialize/cloudtest/application.py", line 60, in kubectl
    return subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['kubectl', '--context', 'kind-kind', 'exec', 'pod/storage-u4-0', '--', 'bash', '-c', 'kill -9 `pidof storaged` || true']' returned non-zero exit status 137.
- generated xml file: /var/lib/buildkite-agent/builds/buildkite-15f2293-i-0d97bf0c91ffc50b4-1/materialize/tests/junit_cloudtest_018405c4-fb16-4786-8c84-6d65d7b3116c.xml -
=========================== short test summary info ============================
FAILED test/cloudtest/test_crash.py::test_crash_storaged - subprocess.CalledP...
====== 1 failed, 17 passed, 3 skipped, 2 deselected in 864.15s (0:14:24) =======
🚨 Error: The command exited with status 1
user command error: The plugin cloudtest command hook exited with status 1
```

### Additional thoughts

Passed after 1 retry.

**Comment by philip-stoev** [comment]
Not seen recently.
