### ISSUE TITLE
CPU profiling a compute pod may cause it to terminate due to an assertion failure

### ISSUE THREAD

**Issue by arusahni** [MaterializeInc/materialize#15864]
### What version of Materialize are you using?

v0.30.1

### How did you install Materialize?

Materialize Cloud

### What is the issue?

When using the CPU profiler exposed by a compute pod's internal HTTP port, the container crashed after I initiated the profile operation.  Logs indicated that it was terminated due to an error with exit code 134, which corresponds to a SIGABRT.  A subsequent attempt succeeded.

[Internal Slack discussion that led to this discovery](https://materializeinc.slack.com/archives/C010UVBK145/p1667483461545539?thread_ts=1667482200.199699&cid=C010UVBK145).

### Relevant log output

```source
2022-11-03T13:42:07.131552Z  INFO pprof::profiler: starting cpu profiler    
Error: Os { code: 4, kind: Interrupted, message: "Interrupted system call" }
thread 'timely:recv-1' panicked at 'assertion failed: read > 0', /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/communication/src/allocator/zero_copy/tcp.rs:67:9
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at ./rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:48:5
   3: timely_communication::allocator::zero_copy::tcp::recv_loop
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/communication/src/allocator/zero_copy/tcp.rs:67:9
   4: timely_communication::allocator::zero_copy::initialize::initialize_networking_from_sockets::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/9548bf9/communication/src/allocator/zero_copy/initialize.rs:120:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Stream closed EOF for environment-[REDACTED]-0/compute-cluster-u10-replica-18-0 (default)
```
```

**Comment by brennanvincent** [comment]
This is the crash log we always get when a timely cluster's peer crashes -- it's not related to the profiler, and that `INFO` log is a red herring.

Is it still possible to grab the log for the other pod? (The one with suffix `-1`)

**Comment by arusahni** [comment]
I've updated this to include the logs from the other pod.
