### ISSUE TITLE
`test_crash_storaged` in `test.cloudtest.test_crash` is flaky

### ISSUE THREAD

**Issue by aalexandrov** [MaterializeInc/materialize#16021]
### Buildkite link

https://buildkite.com/materialize/tests/builds/44936#01846613-e195-462f-b0c1-385dc6be5f8b

### Relevant log output

```
subprocess.CalledProcessError: Command '['kubectl', '--context', 'kind-kind', 'exec', 'pod/storage-u46-0', '--', 'bash', '-c', 'kill -9 `pidof storaged` || true']' returned non-zero exit status 137.

Traceback (most recent call last):
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-0c6ae19baede8c03f-1/materialize/tests/test/cloudtest/test_crash.py", line 93, in test_crash_storaged
    mz.kubectl("exec", pod_name, "--", "bash", "-c", "kill -9 `pidof storaged` || true")
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-0c6ae19baede8c03f-1/materialize/tests/misc/python/materialize/cloudtest/application.py", line 62, in kubectl
    return subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['kubectl', '--context', 'kind-kind', 'exec', 'pod/storage-u46-0', '--', 'bash', '-c', 'kill -9 `pidof storaged` || true']' returned non-zero exit status 137.
```

**Comment by philip-stoev** [comment]
Dup of https://github.com/MaterializeInc/materialize/issues/15613 . I have ran this for hours on end but I am unable to reproduce it :-( It is a kubectl issue of some sort.
