### ISSUE TITLE
panicked at 'Datum::unwrap_float64 called on Int64(0)', src/expr/src/scalar/func.rs:292:15 with aggregate inside a derived table

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#16128]
### What version of Materialize are you using?

v0.33.0-dev (5ff0dacee)

### How did you install Materialize?

Docker image

### What is the issue?

This panics:

```
CREATE TABLE t1 (f1 DOUBLE PRECISION, f2 DOUBLE PRECISION NOT NULL);

CREATE TABLE t2 (f1 DOUBLE PRECISION, f2 DOUBLE PRECISION NOT NULL);

EXPLAIN SELECT *
FROM t2 , 
(
    SELECT AVG(1) AS f1 , COUNT (1) AS f2
    FROM t2
    WHERE f2 IS NULL
) AS a2
WHERE a2.f1 = 1
OR a2.f1 + 4 = 8
AND t2.f2 = 1;
```

~~I am not able to reproduce it with other aggregates except AVG . Can it be because AVG gets decomposed into a SUM / COUNT?~~

### Relevant log output

```source
thread 'coordinator' panicked at 'Datum::unwrap_float64 called on Int64(0)', src/expr/src/scalar/func.rs:292:15
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: mz_repr::scalar::Datum::unwrap_float64
   3: mz_expr::scalar::func::add_float64
   4: mz_expr::scalar::func::BinaryFunc::eval
   5: mz_expr::scalar::MirScalarExpr::eval
   6: mz_expr::scalar::func::BinaryFunc::eval
   7: mz_expr::scalar::MirScalarExpr::eval
   8: mz_expr::scalar::func::VariadicFunc::eval
   9: mz_expr::scalar::MirScalarExpr::eval
  10: mz_transform::reduction::FoldConstants::fold_filter_constant
  11: mz_transform::reduction::FoldConstants::action
  12: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post
  13: <mz_expr::relation::MirRelationExpr as mz_expr::visit::VisitChildren<mz_expr::relation::MirRelationExpr>>::try_visit_mut_children
  14: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post
  15: <mz_expr::relation::MirRelationExpr as mz_expr::visit::VisitChildren<mz_expr::relation::MirRelationExpr>>::try_visit_mut_children
  16: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post
  17: <mz_expr::relation::MirRelationExpr as mz_expr::visit::VisitChildren<mz_expr::relation::MirRelationExpr>>::try_visit_mut_children
  18: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post
  19: <mz_transform::reduction::FoldConstants as mz_transform::Transform>::transform
  20: <mz_transform::FuseAndCollapse as mz_transform::Transform>::transform
  21: tracing::span::Span::in_scope
  22: <mz_transform::Fixpoint as mz_transform::Transform>::transform
  23: mz_transform::Optimizer::optimize
  24: tracing_core::dispatcher::with_default
  25: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_explain
  26: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_plan::{{closure}}::{{closure}}
  27: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  28: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  29: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  31: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  32: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  33: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  34: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_message::{{closure}}
  35: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  36: tokio::park::thread::CachedParkThread::block_on
  37: tokio::runtime::handle::Handle::block_on
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by philip-stoev** [comment]
Just happened without AVG ...

**Comment by teskje** [comment]
The looks like an issue in the optimizer. The most I could reduce the query to was:
```
SELECT *
FROM
    t2,
    (SELECT AVG(1) AS f1, COUNT(1) AS f2 FROM t2) AS a2
WHERE
    a2.f1 = 1
    OR a2.f1 + 4 = 8
    AND t2.f1 = 1;
```

The bug is triggered when we try to constant fold `a2.f1 + 4`. The `+` is planned as a `BinaryFunc::AddFloat64`, and evaluating it expects two `Float64` parameters (and crashes on others). However, the value it actually gets for `a2.f1` is `Int64(0)`. It seems like we get confused with the types somewhere.
