### ISSUE TITLE
thread 'coordinator' panicked at 'Arrangements depended on by delta join alarmingly absent: AvailableCollections { raw: false, arranged: [([], {0: 0}, [0]), ([], {0: 0}, [0])] }

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#16195]
### What version of Materialize are you using?

v0.33.0-dev (2cc59e9fb)

### How did you install Materialize?

Docker image

### What is the issue?

This totally randomly generated query:

```
CREATE TABLE t1 (f1 int, f2 int);
CREATE TABLE t2 (f1 int, f2 int);
```
```
EXPLAIN SELECT  (a1.f1) AS c1, (a2.f1) AS c2, (a1.f2) AS c3, (MIN ( 4 )) AS agg1 , (AVG ( a1 . f2 + 4 )) AS agg2 FROM ( SELECT a1 . f2 + 4 AS f1 , a2 . f2 AS f2 FROM t1 AS a1  JOIN t2 AS a2 ON ( a1 . f1 = a1 . f2 + 8 ) WHERE a1 . f1 + a1 . f2 < a2 . f2 + a1 . f2 AND NOT ( NOT ( a2 . f2 IS NOT NULL ) ) ORDER BY 1 , 2 LIMIT 4  ) AS a1  JOIN ( SELECT AVG ( a2 . f2 + a2 . f2 ) AS f1 , AVG ( a2 . f2 ) AS f2 FROM t2 AS a1  JOIN t2 AS a2 ON ( NOT ( NOT ( a2 . f2 = 5 ) ) ) WHERE a2 . f1 IS NOT NULL AND a2 . f2  IN ( 0 , 3 , 0 , 4 , 9 , 6 ) ORDER BY 1 , 2 LIMIT 2  ) AS a2 ON ( NOT ( 4 = 3 ) ) WHERE a1 . f2 + a2 . f1  IN ( 0 , 7 ) AND 5 NOT IN ( SELECT  c3 AS x1 FROM ( SELECT  (a1.f1) AS c1, (a2.f1) AS c2, (a1.f2) AS c3, (FIRST_VALUE ( a2.f1 ) OVER (  ORDER BY a1.f1 , a2.f1 , a1.f2 )) AS agg1 , (MIN ( 7 )) AS agg2 FROM ( SELECT a2 . f1 AS f1 , COUNT ( 2 ) AS f2 FROM t1 AS a1  JOIN t1 AS a2 ON ( 8 NOT IN ( 3 , 2 ) ) WHERE a1 . f1 + a2 . f2 IS NOT NULL AND a2 . f2  IN ( SELECT DISTINCT agg2 AS x1 FROM ( SELECT  (a1.f1) AS c1, (a2.f1) AS c2, (a1.f2) AS c3, (MIN ( a2 . f1 )) AS agg1 , (MIN ( 2 )) AS agg2 FROM t1 AS a1  JOIN ( SELECT 8 AS f1 , COUNT ( 8 ) AS f2 FROM t2 AS a1 LEFT JOIN t2 AS a2 ON ( 1 < a1 . f2 ) WHERE 2 > 7 AND a2 . f2 + a1 . f2 > a1 . f2 + a1 . f2 AND a2 . f2 + a2 . f1 IS  NULL GROUP BY 1 ORDER BY 1 , 2 LIMIT 5 OFFSET 2 ) AS a2 USING ( f2 , f1 ) WHERE a1 . f1 + a1 . f2 IS NOT NULL AND NOT ( 2  IN ( 8 , 2 ) ) AND 3 > a1 . f1 AND a2 . f2 IS  NULL GROUP BY 1 , 2 , 3  ) AS dt ORDER BY 1 LIMIT 5  ) OR 3 = a1 . f1 GROUP BY 1 ORDER BY 1 , 2 LIMIT 8  ) AS a1 RIGHT JOIN t1 AS a2 ON ( NOT ( 4 NOT IN ( 5 , 3 ) ) ) WHERE NOT ( 8 > a1 . f2 + a1 . f1 ) OR a2 . f2 IS NOT NULL AND 5 NOT IN ( 4 , 4 , 2 , 6 ) GROUP BY 1 , 2 , 3  ) AS dt ORDER BY 1 LIMIT 9 OFFSET 8 ) GROUP BY 1 , 2 , 3 ;
```
Produced the panic below. I am opening this ticket as a placeholder until I have had the time to simplify it.

### Relevant log output

```source
thread 'coordinator' panicked at 'Arrangements depended on by delta join alarmingly absent: AvailableCollections { raw: false, arranged: [([], {0: 0}, [0]), ([], {0: 0}, [0])] }
Dataflow info: Debug name: explanation; id: Explained Query
This is not expected to cause incorrect results, but could indicate a performance issue in Materialize.', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/compute-client/src/plan/mod.rs:1177:29
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/compute-client/src/plan/mod.rs:1177:29
   3: mz_compute_client::plan::Plan<T>::from_mir_inner::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/compute-client/src/plan/mod.rs:935:38
   4: stacker::maybe_grow
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
   5: mz_ore::stack::maybe_grow
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/ore/src/stack.rs:100:5
   6: mz_compute_client::plan::Plan<T>::from_mir_inner
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/compute-client/src/plan/mod.rs:935:9
   7: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/compute-client/src/plan/mod.rs:1211:37
   8: mz_compute_client::plan::Plan<T>::from_mir_inner::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/compute-client/src/plan/mod.rs:935:38
   9: stacker::maybe_grow
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  10: mz_ore::stack::maybe_grow
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/ore/src/stack.rs:100:5
  11: mz_compute_client::plan::Plan<T>::from_mir_inner
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/compute-client/src/plan/mod.rs:935:9
  12: mz_compute_client::plan::Plan<T>::from_mir
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/compute-client/src/plan/mod.rs:918:9
  13: mz_compute_client::plan::Plan<T>::finalize_dataflow
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/compute-client/src/plan/mod.rs:1528:32
  14: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_explain_plan::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/adapter/src/coord/sequencer.rs:2505:37
  15: tracing_core::dispatcher::with_default
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.30/src/dispatcher.rs:257:5
  16: mz_adapter::explain_new::optimizer_trace::OptimizerTrace::collect_trace
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/adapter/src/explain_new/optimizer_trace.rs:81:9
  17: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_explain_plan
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/adapter/src/coord/sequencer.rs:2454:13
  18: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_explain
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/adapter/src/coord/sequencer.rs:2420:18
  19: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_plan::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/adapter/src/coord/sequencer.rs:290:25
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  21: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  22: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_plan::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/adapter/src/coord/sequencer.rs:91:5
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  24: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute_inner::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/adapter/src/coord/command_handler.rs:457:78
  25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  26: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  27: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute_inner::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/adapter/src/coord/command_handler.rs:261:5
  28: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  29: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/adapter/src/coord/command_handler.rs:258:61
  30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  31: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  32: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/adapter/src/coord/command_handler.rs:231:5
  33: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  34: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  35: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_command::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/adapter/src/coord/command_handler.rs:64:21
  36: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  37: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_command::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/adapter/src/coord/message_handler.rs:149:33
  38: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  39: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  40: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_command::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/adapter/src/coord/message_handler.rs:146:5
  41: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  42: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_message::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/adapter/src/coord/message_handler.rs:40:63
  43: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  44: mz_adapter::coord::Coordinator<S>::serve::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/adapter/src/coord.rs:1007:37
  45: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  46: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/park/thread.rs:263:54
  47: tokio::coop::with_budget::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:102:9
  48: std::thread::local::LocalKey<T>::try_with
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/thread/local.rs:445:16
  49: std::thread::local::LocalKey<T>::with
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/thread/local.rs:421:9
  50: tokio::coop::with_budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:95:5
  51: tokio::coop::budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/coop.rs:72:5
  52: tokio::park::thread::CachedParkThread::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/park/thread.rs:263:31
  53: tokio::runtime::enter::Enter::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/enter.rs:152:13
  54: tokio::runtime::handle::Handle::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.2/src/runtime/handle.rs:297:9
  55: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-031345435ea8355bb-1/materialize/tests/src/adapter/src/coord.rs:1153:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by teskje** [comment]
@frankmcsherry points out that this is a soft panic: It panics in debug mode, but in release mode it creates the missing arrangements instead. The goal of this construct is to get a developer to take a look, so we should do that, but it's less critical than a production crash.

**Comment by philip-stoev** [comment]
Our fuzzing tests run in debug mode, so those soft panics would cause such tests to fail which makes it impossible to add them to the CI and makes running them manually a pain. So, some bump in priority would be much appreciated, even if this particular panic is not a problem in production.

**Comment by teskje** [comment]
Noted! @ggevay wants to pick this up soon.

**Comment by ggevay** [comment]
The problem is that constant folding removes the ArrangeBy from a Delta join input.

**Comment by ggevay** [comment]
```
optimize/global/physical/inline_let
Project (#0..=#2, #6, #5) // { arity: 5 }
  Map ((bigint_to_double(#3) / bigint_to_double(case when (#4 = 0) then null else #4 end)), 4) // { arity: 7 }
    Reduce group_by=[#1, #2, #0] aggregates=[sum((#0 + 4)), count((#0 + 4))] // { arity: 5 }
      Project (#0..=#2) // { arity: 3 }
        Filter ((#3 = 0) OR (#3 = 7)) // { arity: 4 }
          Map ((integer_to_double(#0) + #2)) // { arity: 4 }
            CrossJoin type=delta // { arity: 3 }
              implementation
                %0 » %1[×]UA » %2[×]A
                %1 » %0[×]A » %2[×]A
                %2 » %1[×]UA » %0[×]A
              ArrangeBy keys=[[]] // { arity: 2 }
                TopK order_by=[#1 asc nulls_last, #0 asc nulls_last] limit=4 monotonic=false // { arity: 2 }
                  Project (#2, #3) // { arity: 2 }
                    Filter ((#0 + #1) < (#2 + #1)) // { arity: 4 }
                      Map ((#1 + 4)) // { arity: 4 }
                        CrossJoin type=differential // { arity: 3 }
                          implementation
                            %1:t2 » %0:t1[×]Af
                          ArrangeBy keys=[[]] // { arity: 2 }
                            Filter (#0 = (#1 + 8)) // { arity: 2 }
                              Get materialize.public.t1 // { arity: 2 }
                          ArrangeBy keys=[[]] // { arity: 1 }
                            Project (#1) // { arity: 1 }
                              Get materialize.public.t2 // { arity: 2 }
              ArrangeBy keys=[[]] // { arity: 1 }
                Project (#0) // { arity: 1 }
                  TopK order_by=[#0 asc nulls_last, #1 asc nulls_last] limit=2 monotonic=false // { arity: 2 }
                    Project (#4, #5) // { arity: 2 }
                      Map ((bigint_to_double(#0) / bigint_to_double(case when (#1 = 0) then null else #1 end)), (bigint_to_double(#2) / bigint_to_double(case when (#3 = 0) then null else #3 end))) // { arity: 6 }
                        Union // { arity: 4 }
                          Constant <empty>
                          Map (null, 0, null, 0) // { arity: 4 }
                            Union // { arity: 0 }
                              Negate // { arity: 0 }
                                Project () // { arity: 0 }
                                  Constant <empty>
                              Constant // { arity: 0 }
                                - ()
              ArrangeBy keys=[[]] // { arity: 0 }
                Union // { arity: 0 }
                  Negate // { arity: 0 }
                    Distinct // { arity: 0 }
                      Project () // { arity: 0 }
                        Filter ((#0) IS NULL OR (#0 = 5)) // { arity: 1 }
                          TopK order_by=[#0 asc nulls_last] limit=9 offset=8 monotonic=false // { arity: 1 }
                            Project (#2) // { arity: 1 }
                              Map (record_get[2](record_get[1](#1))) // { arity: 3 }
                                FlatMap unnest_list(#0) // { arity: 2 }
                                  Reduce aggregates=[first_value(row(row(row(null, #0, null, 7), #0), null, #0, null))] // { arity: 1 }
                                    Distinct group_by=[#0] // { arity: 1 }
                                      Project (#0) // { arity: 1 }
                                        Filter (null OR (#1) IS NOT NULL) // { arity: 2 }
                                          Get materialize.public.t1 // { arity: 2 }
                  Constant // { arity: 0 }
                    - ()
```
and then after constant folding:
```
optimize/global/physical/fold_constants
Project (#0..=#2, #6, #5) // { arity: 5 }
  Map ((bigint_to_double(#3) / bigint_to_double(case when (#4 = 0) then null else #4 end)), 4) // { arity: 7 }
    Reduce group_by=[#1, #2, #0] aggregates=[sum((#0 + 4)), count((#0 + 4))] // { arity: 5 }
      Project (#0..=#2) // { arity: 3 }
        Filter ((#3 = 0) OR (#3 = 7)) // { arity: 4 }
          Map ((integer_to_double(#0) + #2)) // { arity: 4 }
            CrossJoin type=delta // { arity: 3 }
              implementation
                %0 » %1[×]UA » %2[×]A
                %1 » %0[×]A » %2[×]A
                %2 » %1[×]UA » %0[×]A
              ArrangeBy keys=[[]] // { arity: 2 }
                TopK order_by=[#1 asc nulls_last, #0 asc nulls_last] limit=4 monotonic=false // { arity: 2 }
                  Project (#2, #3) // { arity: 2 }
                    Filter ((#0 + #1) < (#2 + #1)) // { arity: 4 }
                      Map ((#1 + 4)) // { arity: 4 }
                        CrossJoin type=differential // { arity: 3 }
                          implementation
                            %1:t2 » %0:t1[×]Af
                          ArrangeBy keys=[[]] // { arity: 2 }
                            Filter (#0 = (#1 + 8)) // { arity: 2 }
                              Get materialize.public.t1 // { arity: 2 }
                          ArrangeBy keys=[[]] // { arity: 1 }
                            Project (#1) // { arity: 1 }
                              Get materialize.public.t2 // { arity: 2 }
              Constant // { arity: 1 }
                - (null)
              ArrangeBy keys=[[]] // { arity: 0 }
                Union // { arity: 0 }
                  Negate // { arity: 0 }
                    Distinct // { arity: 0 }
                      Project () // { arity: 0 }
                        Filter ((#0) IS NULL OR (#0 = 5)) // { arity: 1 }
                          TopK order_by=[#0 asc nulls_last] limit=9 offset=8 monotonic=false // { arity: 1 }
                            Project (#2) // { arity: 1 }
                              Map (record_get[2](record_get[1](#1))) // { arity: 3 }
                                FlatMap unnest_list(#0) // { arity: 2 }
                                  Reduce aggregates=[first_value(row(row(row(null, #0, null, 7), #0), null, #0, null))] // { arity: 1 }
                                    Distinct group_by=[#0] // { arity: 1 }
                                      Project (#0) // { arity: 1 }
                                        Filter (null OR (#1) IS NOT NULL) // { arity: 2 }
                                          Get materialize.public.t1 // { arity: 2 }
                  Constant // { arity: 0 }
                    - ()
```
