### ISSUE TITLE
thread 'timely:work-0' panicked at 'failed to create a delayed capability, the current set does not have an element less than or equal to

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#16318]
### What version of Materialize are you using?

v0.33.0-dev (ce99778ab)

### How did you install Materialize?

Docker image

### What is the issue?

A Zippy test immediately panics with:
```
thread 'timely:work-0' panicked at 'failed to create a delayed capability, the current set does not have an element less than or equal to 1669620038000', /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/dataflow/operators/capability.rs:446:13
```

and then proceeds to repeatedly panic in the same fashion **tens of thousands of times** per 24h test . The test does make progress though, even though very slowly and eventually it will report that some source never converged to the expected result  even if given 10 min to do so .

To reproduce:

```
cd test/zippy
./mzcompose run default --scenario KafkaSourcesLarge
```

and in a separate console do:

```
docker logs zippy-materialized-1 --follow
```

and observe the panics as they go by. 

### Relevant log output

```source
thread 'timely:work-0' panicked at 'failed to create a delayed capability, the current set does not have an element less than or equal to 1669620038000', /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/dataflow/operators/capability.rs:446:13
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: timely::dataflow::operators::capability::CapabilitySet<T>::delayed::delayed_panic
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/dataflow/operators/capability.rs:446:13
   3: timely::dataflow::operators::capability::CapabilitySet<T>::delayed::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/dataflow/operators/capability.rs:454:32
   4: core::option::Option<T>::unwrap_or_else
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:825:21
   5: timely::dataflow::operators::capability::CapabilitySet<T>::delayed
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/dataflow/operators/capability.rs:453:9
   6: mz_storage::source::source_reader_pipeline::handle_message
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a1897808505617a3-1/materialize/tests/src/storage/src/source/source_reader_pipeline.rs:1623:18
   7: mz_storage::source::source_reader_pipeline::reclock_operator::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a1897808505617a3-1/materialize/tests/src/storage/src/source/source_reader_pipeline.rs:1434:25
   8: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/dataflow/operators/generic/builder_rc.rs:123:31
   9: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/dataflow/operators/generic/builder_rc.rs:162:26
  10: <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/dataflow/operators/generic/builder_raw.rs:204:9
  11: timely::progress::subgraph::PerOperatorState<T>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/progress/subgraph.rs:684:30
  12: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/progress/subgraph.rs:344:26
  13: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/progress/subgraph.rs:310:17
  14: timely::progress::subgraph::PerOperatorState<T>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/progress/subgraph.rs:684:30
  15: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/progress/subgraph.rs:344:26
  16: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/progress/subgraph.rs:310:17
  17: timely::worker::Wrapper::step::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/worker.rs:754:57
  18: core::option::Option<T>::map
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:929:29
  19: timely::worker::Wrapper::step
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/worker.rs:754:26
  20: timely::worker::Worker<A>::step_or_park
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/worker.rs:396:38
  21: mz_storage::storage_state::Worker<A>::run_client
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a1897808505617a3-1/materialize/tests/src/storage/src/storage_state.rs:219:17
  22: mz_storage::storage_state::Worker<A>::run
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a1897808505617a3-1/materialize/tests/src/storage/src/storage_state.rs:195:33
  23: mz_storage::server::serve::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a1897808505617a3-1/materialize/tests/src/storage/src/server.rs:94:9
  24: timely::execute::execute::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/timely/src/execute.rs:287:22
  25: timely_communication::initialize::initialize_from::{{closure}}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/157b80d/communication/src/initialize.rs:316:33
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
environmentd: 2022-11-28T07:20:39.755327Z  WARN mz_storage_client::controller::rehydration: storage host produced error, reconnecting: status: Unknown, message: "error reading a body from connection: broken pipe", details: [], metadata: MetadataMap { headers: {} }
environmentd: 2022-11-28T07:20:39.761795Z ERROR mz_orchestrator_process: storage-u4 exited: Ok(ExitStatus(unix_wait_status(6))); relaunching in 5s
```

**Comment by philip-stoev** [comment]
Also seen with `--scenario=ClusterReplicas`

**Comment by philip-stoev** [comment]
A tortured bisection attempt appears to show that one of those commits has introduced the panic:

```
commit 3b84a6246d9dab7bffd5543a8cf40fff54c94257 (HEAD, refs/bisect/good-3b84a6246d9dab7bffd5543a8cf40fff54c94257, refs/bisect/bad)
Merge: 68f397ce9 e6c5eb8e3
Author: Petros Angelatos <petrosagg@gmail.com>
Date:   Tue Nov 22 01:04:32 2022 +0100

    Merge pull request #15567 from petrosagg/native-timestamp-reclock
    
    storage: timely native timestamp reclock implementation

commit e6c5eb8e32057e3bf38f116f66776375f9c8b890
Author: Petros Angelatos <petrosagg@gmail.com>
Date:   Thu Oct 20 18:56:18 2022 +0200

    storage: timely native reclock implementation
    
    First phase of moving away from the custom source timestamps we have
    been wrestling with in storage. This PR changes the reclocking
    implementation to be generic over any two timely timestamps and provides
    compatibility methods to also work with `OffsetAntichain` frontiers in
    order to keep the diff small and not change everything in one go.
    
    In a future PR the compatiblity layer will be deleted and the whole
    pipeline will be based on `Partitioned<PartitionId, MzOffset>>`
    timestamps and frontiers.
    
    Signed-off-by: Petros Angelatos <petrosagg@gmail.com>

commit e6313cb7a785840ecbe1f395efff32db60f67ab7
Author: Petros Angelatos <petrosagg@gmail.com>
Date:   Wed Oct 19 18:55:15 2022 +0200

    Revert "storage: in reclock.rs, make time control more explicit in tests"
    
    This reverts commit c8d8d1a56f1b66b4f49a566d2089a0f9da701827.

```

The prior commit appears to be able to run Zippy cleanly. @petrosagg FYI
