### ISSUE TITLE
"cargo test" is flaky: `assertion failed: current_suite_maybe.is_none()`

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#16331]
### Buildkite link

https://buildkite.com/materialize/tests/builds/45823#0184bf6d-501a-4b2e-9cb1-3842c76d3298

### Relevant log output

```source
92/93 commands passed
$ cargo2junit
thread 'main' panicked at 'assertion failed: current_suite_maybe.is_none()', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo2junit-0.1.12/src/main.rs:163:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
   3: cargo2junit::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
mzcompose: test case workflow-default failed:
Traceback (most recent call last):
  File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a51c5daac6302bd3-1/materialize/tests/misc/python/materialize/mzcompose/__init__.py", line 231, in invoke
    return subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'compose', '-f/dev/fd/3', '--project-directory', PosixPath('/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a51c5daac6302bd3-1/materialize/tests/ci/test/cargo-test'), 'run', 'ci-cargo-test', 'run-tests']' returned non-zero exit status 1.
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a51c5daac6302bd3-1/materialize/tests/ci/test/cargo-test/mzcompose.py", line 48, in workflow_default
    c.run("ci-cargo-test", "run-tests")
  File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a51c5daac6302bd3-1/materialize/tests/misc/python/materialize/mzcompose/__init__.py", line 492, in run
    return self.invoke(
  File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a51c5daac6302bd3-1/materialize/tests/misc/python/materialize/mzcompose/__init__.py", line 249, in invoke
    raise UIError(f"running docker compose failed (exit status {e.returncode})")
materialize.ui.UIError: running docker compose failed (exit status 1)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a51c5daac6302bd3-1/materialize/tests/misc/python/materialize/mzcompose/__init__.py", line 381, in test_case
    yield
  File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a51c5daac6302bd3-1/materialize/tests/misc/python/materialize/cli/mzcompose.py", line 578, in handle_composition
    composition.workflow(args.workflow, *args.unknown_subargs[1:])
  File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a51c5daac6302bd3-1/materialize/tests/misc/python/materialize/mzcompose/__init__.py", line 299, in workflow
    func(self)
  File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a51c5daac6302bd3-1/materialize/tests/ci/test/cargo-test/mzcompose.py", line 51, in workflow_default
    spawn.runv(
  File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a51c5daac6302bd3-1/materialize/tests/misc/python/materialize/spawn.py", line 71, in runv
    return subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cargo2junit']' returned non-zero exit status 101.
==> Uploading report for suite 'mzcompose' to Buildkite Test Analytics
202 {"id":"dea21b7d-b4fa-4d40-9fd6-c90ba041f1c8","run_id":"a9e59a8f-ef63-4555-8b95-cd7165d94256","queued":1,"skipped":0,"errors":[],"run_url":"https://buildkite.com/organizations/materialize/analytics/suites/mzcompose/runs/a9e59a8f-ef63-4555-8b95-cd7165d94256"}
mzcompose: error: at least one test case failed
```

### Additional thoughts

This has been happening for many months and feels like some bug with some test or CI thing itself.

**Comment by benesch** [comment]
I think the `current_suite_maybe.is_none()` assertion failure is a red herring. I think that assertion failure is just `cargo2junit` getting confused when the test fails so hard that it doesn't produce correctly-formatted JSON output.

I think the real failure is earlier, in one of the test binaries themselves:

```
thread panicked while panicking. aborting.
```

Not sure what to make of that.

I think the right course of action here is to switch to `cargo nextest`. It's a _much_ better test runner that can natively produce junit output, and should be resilient to this sort of unusable output.

I have a draft PR here (https://github.com/MaterializeInc/materialize/pull/13035), but it got blocked on some port reuse stuff. If you have a day to spare on this, @mjibson, I'd be happy to talk through what would need to happen to get it across the line.

**Comment by jkosh44** [comment]
`thread panicked while panicking. aborting.` 
happens because a lot of our `Drop` implementations have panics in them. So a test fails due to a panic and tries to drop all of the in scope objects, then one of the `Drop`s panics and causes that error.

I guess that's one of the advantages of returning an error from a test instead of panicing, you don't have the nested panics.

**Comment by mjibson** [comment]
This should have been fixed by CI's use of `nextest`.
