### ISSUE TITLE
panic: thread 'coordinator' panicked at 'Dataflow temp-view-t251 requested `as_of`

### ISSUE THREAD

**Issue by bobbyiliev** [MaterializeInc/materialize#16469]
### What version of Materialize are you using?

v0.33.3 (2982e6bca)

### How did you install Materialize?

Materialize Cloud

### What is the issue?

Environmentd panics and crashes if you try to select from two different schemas in the same transactions, repro steps:

```sql
materialize=> create table t1 (f1 int);
CREATE TABLE
materialize=> insert into t1 values (1);
INSERT 0 1

materialize=> begin;
BEGIN
materialize=*> select * from t1;
 f1 
----
  1
(1 row)

materialize=*> select * from mz_views;
SSL SYSCALL error: EOF detected
The connection to the server was lost. Attempting reset: Failed.
The connection to the server was lost. Attempting reset: Failed.
!?> 
```

Related log from HC below:

### Relevant log output

```source
thread 'coordinator' panicked at 'Dataflow temp-view-t251 requested as_of (Antichain { elements: [1670242331152] }) not >= since (Antichain { elements: [1670242334000] })', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/dataflows.rs:161:13

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord.rs:1170:17
  45: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/handle.rs:264:9
  44: tokio::runtime::handle::Handle::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/context.rs:255:13
  43: tokio::runtime::context::BlockingRegionGuard::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/park.rs:272:31
  42: tokio::runtime::park::CachedParkThread::block_on
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:68:5
  41: tokio::runtime::coop::budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/coop.rs:102:5
  40: tokio::runtime::coop::with_budget
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.22.0/src/runtime/park.rs:272:63
  39: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  38: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord.rs:1002:37
  37: mz_adapter::coord::Coordinator<S>::serve::{{closure}}
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  36: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/message_handler.rs:40:63
  35: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_message::{{closure}}
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  34: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/message_handler.rs:146:5
  33: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_command::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  32: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  31: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/message_handler.rs:149:33
  30: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_command::{{closure}}::{{closure}}
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  29: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/command_handler.rs:64:21
  28: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_command::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  27: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/command_handler.rs:231:5
  25: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  24: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/command_handler.rs:258:61
  22: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute::{{closure}}::{{closure}}
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/command_handler.rs:261:5
  20: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute_inner::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  19: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/command_handler.rs:457:78
  17: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_execute_inner::{{closure}}::{{closure}}
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/sequencer.rs:94:5
  15: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_plan::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  14: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/sequencer.rs:274:63
  12: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_plan::{{closure}}::{{closure}}
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/sequencer.rs:2089:5
  10: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_peek::{{closure}}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
   9: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/sequencer.rs:2148:29
   7: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::sequence_peek::{{closure}}::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/sequencer.rs:2360:25
   6: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator<S>>::plan_peek
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/peek.rs:264:25
   5: mz_adapter::coord::peek::<impl mz_adapter::coord::Coordinator<S>>::create_peek_plan
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:1023:21
   4: core::option::Option<T>::map_or_else
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/peek.rs:267:32
   3: mz_adapter::coord::peek::<impl mz_adapter::coord::Coordinator<S>>::create_peek_plan::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-09271a685a355f8ce-1/materialize/release-qualification/src/adapter/src/coord/dataflows.rs:161:13
   2: mz_adapter::coord::dataflows::<impl mz_adapter::coord::Coordinator<S>>::finalize_dataflow
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   1: core::panicking::panic_fmt
             at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   0: rust_begin_unwind
```

**Comment by benesch** [comment]
Oh, excellent, we've been seeing this in Sentry but didn't have a repro. Thank you, @bobbyiliev!

**Comment by jkosh44** [comment]
Note: the `INSERT` is not required for reproduction.

The actual panic says that we selected a timestamp for `mz_views` that is less than the `since`. The reason is as follows:
1. Once we perform `select * from t1;` we select a timestamp and obtain a read hold on all objects in the same schema a `t1` (`public`).
2. When we read from `mz_views` we use the same timestamp as the previous read.
3. Since there's no read hold on `mz_views` it's since may have advanced past the selected timestamp, so we see the panic above.

Instead we should be returning an error that `mz_views` is not in the same time domain.

**Comment by jkosh44** [comment]
The issue is due to a recent code change that re-arranged `sequence_peek`. The panic happens in this function: https://github.com/MaterializeInc/materialize/blob/9c9c3fa8d4b347139ff4c5781f3999d0690415f1/src/adapter/src/coord/sequencer.rs#L2153-L2164
However the time domain validation happens after here: https://github.com/MaterializeInc/materialize/blob/9c9c3fa8d4b347139ff4c5781f3999d0690415f1/src/adapter/src/coord/sequencer.rs#L2177-L2221
