### ISSUE TITLE
thread 'coordinator' panicked at 'can't persist timestamp: Error { kind: Stash(StashError { inner: Other("unexpected lower") }) }', 

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#16927]
### What version of Materialize are you using?

77cb26f

### How did you install Materialize?

Docker image

### What is the issue?

Happened in a new Zippy workload that repeatedly kills and restarts Minio and CRDB:

https://buildkite.com/materialize/nightlies/builds/1582#0185779e-3728-415d-b987-f736fc9e88f3

@mjibson FYI, as you worked on the previous occurrence of the same panic 1 month ago.

### Relevant log output

```source
zippy-materialized-1     | thread 'coordinator' panicked at 'can't persist timestamp: Error { kind: Stash(StashError { inner: Other("unexpected lower") }) }', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d97087ff7be59fa2-1/materialize/tests/src/adapter/src/util.rs:254:23
zippy-materialized-1     | stack backtrace:
zippy-materialized-1     |    0: rust_begin_unwind
zippy-materialized-1     |              at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
zippy-materialized-1     |    1: core::panicking::panic_fmt
zippy-materialized-1     |              at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
zippy-materialized-1     |    2: <core::result::Result<T,E> as mz_adapter::util::ResultExt<T>>::unwrap_or_terminate
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d97087ff7be59fa2-1/materialize/tests/src/adapter/src/util.rs:254:23
zippy-materialized-1     |    3: mz_adapter::coord::timeline::DurableTimestampOracle<T>::maybe_allocate_new_timestamps::{{closure}}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d97087ff7be59fa2-1/materialize/tests/src/adapter/src/coord/timeline.rs:295:13
zippy-materialized-1     |    4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
zippy-materialized-1     |              at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
zippy-materialized-1     |    5: mz_adapter::coord::timeline::DurableTimestampOracle<T>::write_ts::{{closure}}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d97087ff7be59fa2-1/materialize/tests/src/adapter/src/coord/timeline.rs:243:13
zippy-materialized-1     |    6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
zippy-materialized-1     |              at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
zippy-materialized-1     |    7: mz_adapter::coord::timeline::<impl mz_adapter::coord::Coordinator<S>>::get_local_write_ts::{{closure}}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d97087ff7be59fa2-1/materialize/tests/src/adapter/src/coord/timeline.rs:370:13
zippy-materialized-1     |    8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
zippy-materialized-1     |              at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
zippy-materialized-1     |    9: mz_adapter::coord::appends::<impl mz_adapter::coord::Coordinator<S>>::group_commit_initiate::{{closure}}::{{closure}}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d97087ff7be59fa2-1/materialize/tests/src/adapter/src/coord/appends.rs:233:38
zippy-materialized-1     |   10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
zippy-materialized-1     |              at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
zippy-materialized-1     |   11: mz_adapter::coord::appends::<impl mz_adapter::coord::Coordinator<S>>::group_commit_initiate::{{closure}}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d97087ff7be59fa2-1/materialize/tests/src/adapter/src/coord/appends.rs:175:5
zippy-materialized-1     |   12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
zippy-materialized-1     |              at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
zippy-materialized-1     |   13: mz_adapter::coord::appends::<impl mz_adapter::coord::Coordinator<S>>::send_builtin_table_updates::{{closure}}::{{closure}}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d97087ff7be59fa2-1/materialize/tests/src/adapter/src/coord/appends.rs:391:41
zippy-materialized-1     |   14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
zippy-materialized-1     |              at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
zippy-materialized-1     |   15: mz_adapter::coord::appends::<impl mz_adapter::coord::Coordinator<S>>::send_builtin_table_updates::{{closure}}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d97087ff7be59fa2-1/materialize/tests/src/adapter/src/coord/appends.rs:377:5
zippy-materialized-1     |   16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
zippy-materialized-1     |              at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
zippy-materialized-1     |   17: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_controller::{{closure}}::{{closure}}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d97087ff7be59fa2-1/materialize/tests/src/adapter/src/coord/message_handler.rs:289:17
zippy-materialized-1     |   18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
zippy-materialized-1     |              at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
zippy-materialized-1     |   19: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::message_controller::{{closure}}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d97087ff7be59fa2-1/materialize/tests/src/adapter/src/coord/message_handler.rs:167:5
zippy-materialized-1     |   20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
zippy-materialized-1     |              at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
zippy-materialized-1     |   21: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator<S>>::handle_message::{{closure}}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d97087ff7be59fa2-1/materialize/tests/src/adapter/src/coord/message_handler.rs:45:47
zippy-materialized-1     |   22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
zippy-materialized-1     |              at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
zippy-materialized-1     |   23: mz_adapter::coord::Coordinator<S>::serve::{{closure}}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d97087ff7be59fa2-1/materialize/tests/src/adapter/src/coord.rs:1066:37
zippy-materialized-1     |   24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
zippy-materialized-1     |              at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
zippy-materialized-1     |   25: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
zippy-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/park.rs:283:63
zippy-materialized-1     |   26: tokio::runtime::coop::with_budget
zippy-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/coop.rs:102:5
zippy-materialized-1     |   27: tokio::runtime::coop::budget
zippy-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/coop.rs:68:5
zippy-materialized-1     |   28: tokio::runtime::park::CachedParkThread::block_on
zippy-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/park.rs:283:31
zippy-materialized-1     |   29: tokio::runtime::context::BlockingRegionGuard::block_on
zippy-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/context.rs:295:13
zippy-materialized-1     |   30: tokio::runtime::handle::Handle::block_on
zippy-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/handle.rs:264:9
zippy-materialized-1     |   31: mz_adapter::coord::serve::{{closure}}::{{closure}}
zippy-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d97087ff7be59fa2-1/materialize/tests/src/adapter/src/coord.rs:1258:17
zippy-materialized-1     | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by mjibson** [comment]
Both of the logged sentry issues for this have logs like:

![ss](https://user-images.githubusercontent.com/41181/210635514-9c6c510a-7938-4ab2-951d-d927563a085d.png)

Here there was a stash reconnect right before this error, so it's probably related to some side effect caused by reconnection.

**Comment by philip-stoev** [comment]
Happened again https://buildkite.com/materialize/nightlies/builds/1618#018596a1-c1aa-44d5-8485-b000eb1865c4

**Comment by mjibson** [comment]
I spent some hours last week looking at this and trying to repro (wrote a custom test that just ran append batch on a single object thing, just like the write_ts function does, and restarted cockroach every 10s), but was unable to repro. Am adding logging this release to get some more details, but I kinda suspect they won't help. This is on my priority list, but not quite at the top yet.

**Comment by philip-stoev** [comment]
@mjibson your extra logging just activated:

```
platform-checks-materialized-1  | environmentd: 2023-01-11T00:58:14.386920Z  INFO mz_stash::postgres: tokio-postgres stash error, retry attempt 3: error connecting to server: failed to lookup address information: Name or service not known
platform-checks-materialized-1  | thread 'coordinator' panicked at 'can't persist timestamp: Error { kind: Stash(StashError { inner: Other("unexpected lower, got Antichain { elements: [-9223372036854775804] }, expected Antichain { elements: [-9223372036854775805] }") }) }', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a061237e2b066b81-1/materialize/tests/src/adapter/src/util.rs:254:23
```

https://buildkite.com/materialize/nightlies/builds/1630#01859e3f-1616-4bac-96e3-8f6d00f70cba

**Comment by philip-stoev** [comment]
One more:

```
thread 'coordinator' panicked at 'can't persist timestamp: Error { kind: Stash(StashError { inner: Other("unexpected lower, got Antichain { elements: [-9223372036854775482] }, expected Antichain { elements: [-9223372036854775483] }") }) }', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0caeb266150de501b-1/materialize/tests/src/adapter/src/util.rs:254:23
```

To reproduce:

```
while bash -c -e "./mzcompose down -v ; ./mzcompose run default --scenario=CrdbMinioRestart --actions=1000"; do : ; done
```

and wait a couple of hours.

**Comment by philip-stoev** [comment]
This now happens several times per Nightly, so should now be quite reproducible. I am afraid that if Cockroach has any downtime of sorts, e.g. an outage or scheduled maintenance, environmentds will be panicking in our cloud.

**Comment by mjibson** [comment]
Yes, I'll look into this more now that it has a repro. Thanks for that.

**Comment by mjibson** [comment]
BTW I noticed while running the command above that it causes my machine to make over 1000 DNS requests per second for `cockroach`. Any ideas what that's about?

**Comment by mjibson** [comment]
Locally I have a pihole, which is responding with NXDOMAIN for this, and something would still very much like a response.

**Comment by mjibson** [comment]
I was not able to repro with the steps above. Maybe I need to let it run longer. I also tried writing a custom test that restarted cockroach in a loop while calling upsert_key_no_consolidate in a loop with exactly the same kinds of arguments as write_ts, but that also failed to produce anything after some hours.

Observation: this is still occurring in the 0.40 branch which has the cache layer removed, so it's not a bug with caching. I think it's very interesting that we've only observed this (in sentry and ci) with coord's `write_ts` function, even though upsert_key_no_consolidate is called in other places, suggesting that there's something going on with write_ts. I've read over its code many times and can't see anything.

The switch to stash txns might just fix this, because the lower is now generated in the same txn as the batch commit. If it doesn't, at least we have more data about things it is not. If it does fix it, then great it's fixed but would be unfortunate that we never figured out the root cause, which I'm worried about because it feels like a possible correctness problem.

I'm going to run the above zippy test and my custom test in the background for the whole day to see if I can repro. But at this point I'm not sure where else to look.

**Comment by mjibson** [comment]
Figured this out while working on the stash txn stuff. The fix I made in https://github.com/MaterializeInc/materialize/pull/16489 was wrong. Very annoyingly, the title and commit message contained the correct diagnosis (verify and seal need to happen in order), but the actual code change moved the compact function, not the seal function. Ugh. Will get fix for sure in an upcoming PR.
