### ISSUE TITLE
regression: implicitly-created cluster left behind after a failed CREATE SINK statement; environmentd panic when attempting to DROP it 

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#17061]
### What version of Materialize are you using?

 v0.40.0-dev (4b8e18e75)

### How did you install Materialize?

Docker image

### What is the issue?

The `kafka-sink-errors.td` attempts to create various sinks and expect them to fail. In particular, it does:

```
! CREATE SINK invalid_acks FROM v1
  INTO KAFKA CONNECTION kafka_conn (ACKS = foo, TOPIC 'testdrive-kafka-sink-errors-${testdrive.seed}')
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY CONNECTION csr_conn
  ENVELOPE DEBEZIUM
contains:Invalid value for configuration property "request.required.acks" acks foo
```

The problem is that the implicitly-created cluster that was created to serve this sink was left behind:

```
materialize=> show clusters;
              name               
---------------------------------
 default
 materialize_public_invalid_acks <- HERE
 mz_introspection
 mz_system
(4 rows)
```

and yet the sink , as expected, does not really exist:

```
materialize=> show sinks;
 name | type | size 
------+------+------
(0 rows)
```

**Comment by philip-stoev** [comment]
Attempting to drop said cluster results in an enviromentd panic:
```
materialize=> drop cluster materialize_public_invalid_acks;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```
```
thread 'coordinator' panicked at 'no entry found for key', src/adapter/src/catalog.rs:347:10
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:65:14
   2: core::panicking::panic_display
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:139:5
   3: core::panicking::panic_str
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/panicking.rs:123:5
   4: core::option::expect_failed
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/option.rs:1879:5
   5: <core::option::Option<&mz_adapter::catalog::CatalogEntry>>::expect
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/option.rs:741:21
   6: <alloc::collections::btree::map::BTreeMap<mz_repr::global_id::GlobalId, mz_adapter::catalog::CatalogEntry> as core::ops::index::Index<&mz_repr::global_id::GlobalId>>::index
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/alloc/src/collections/btree/map.rs:2216:9
   7: <mz_adapter::catalog::CatalogState>::get_entry
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c49f812bbd3358b3-1/materialize/tests/src/adapter/src/catalog.rs:347:10
   8: <mz_adapter::catalog::ConnCatalog as mz_sql::catalog::SessionCatalog>::get_item
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c49f812bbd3358b3-1/materialize/tests/src/adapter/src/catalog.rs:6225:9
   9: mz_sql::plan::statement::ddl::ensure_cluster_is_not_linked
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c49f812bbd3358b3-1/materialize/tests/src/sql/src/plan/statement/ddl.rs:3311:27
  10: mz_sql::plan::statement::ddl::plan_drop_cluster
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c49f812bbd3358b3-1/materialize/tests/src/sql/src/plan/statement/ddl.rs:3288:17
  11: mz_sql::plan::statement::plan
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c49f812bbd3358b3-1/materialize/tests/src/sql/src/plan/statement.rs:277:42
  12: <mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::plan_statement
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c49f812bbd3358b3-1/materialize/tests/src/adapter/src/coord/sql.rs:32:20
  13: <mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::handle_execute_inner::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c49f812bbd3358b3-1/materialize/tests/src/adapter/src/coord/command_handler.rs:469:24
  14: <core::future::from_generator::GenFuture<<mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::handle_execute_inner::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
  15: <mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::handle_execute_inner::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c49f812bbd3358b3-1/materialize/tests/src/adapter/src/coord/command_handler.rs:274:5
  16: <core::future::from_generator::GenFuture<<mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::handle_execute_inner::{closure#0}> as core::future::future::Future>::poll
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
  17: <mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::handle_execute::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c49f812bbd3358b3-1/materialize/tests/src/adapter/src/coord/command_handler.rs:271:61
  18: <core::future::from_generator::GenFuture<<mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::handle_execute::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
  19: <mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::handle_execute::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c49f812bbd3358b3-1/materialize/tests/src/adapter/src/coord/command_handler.rs:230:5
  20: <core::future::from_generator::GenFuture<<mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::handle_execute::{closure#0}> as core::future::future::Future>::poll
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
  21: <tracing::instrument::Instrumented<core::future::from_generator::GenFuture<<mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::handle_execute::{closure#0}>> as core::future::future::Future>::poll
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  22: <mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::handle_command::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c49f812bbd3358b3-1/materialize/tests/src/adapter/src/coord/command_handler.rs:66:21
  23: <core::future::from_generator::GenFuture<<mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::handle_command::{closure#0}> as core::future::future::Future>::poll
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
  24: <mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::message_command::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c49f812bbd3358b3-1/materialize/tests/src/adapter/src/coord/message_handler.rs:204:33
  25: <core::future::from_generator::GenFuture<<mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::message_command::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
  26: <mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::message_command::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c49f812bbd3358b3-1/materialize/tests/src/adapter/src/coord/message_handler.rs:201:5
  27: <core::future::from_generator::GenFuture<<mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::message_command::{closure#0}> as core::future::future::Future>::poll
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
  28: <mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::handle_message::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c49f812bbd3358b3-1/materialize/tests/src/adapter/src/coord/message_handler.rs:43:63
  29: <core::future::from_generator::GenFuture<<mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::handle_message::{closure#0}> as core::future::future::Future>::poll
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
  30: <mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::serve::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c49f812bbd3358b3-1/materialize/tests/src/adapter/src/coord.rs:1142:37
  31: <core::future::from_generator::GenFuture<<mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::serve::{closure#0}> as core::future::future::Future>::poll
             at ./rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library/core/src/future/mod.rs:91:19
  32: <tokio::runtime::park::CachedParkThread>::block_on::<core::future::from_generator::GenFuture<<mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::serve::{closure#0}>>::{closure#0}
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/park.rs:283:63
  33: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<core::future::from_generator::GenFuture<<mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::serve::{closure#0}>>::{closure#0}>
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/coop.rs:102:5
  34: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<core::future::from_generator::GenFuture<<mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::serve::{closure#0}>>::{closure#0}>
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/coop.rs:68:5
  35: <tokio::runtime::park::CachedParkThread>::block_on::<core::future::from_generator::GenFuture<<mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::serve::{closure#0}>>
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/park.rs:283:31
  36: <tokio::runtime::context::BlockingRegionGuard>::block_on::<core::future::from_generator::GenFuture<<mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::serve::{closure#0}>>
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/context.rs:295:13
  37: <tokio::runtime::handle::Handle>::block_on::<core::future::from_generator::GenFuture<<mz_adapter::coord::Coordinator<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>>::serve::{closure#0}>>
             at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.0/src/runtime/handle.rs:264:9
  38: mz_adapter::coord::serve::<mz_stash::cache::Cache<mz_stash::postgres::Postgres>>::{closure#0}::{closure#1}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c49f812bbd3358b3-1/materialize/tests/src/adapter/src/coord.rs:1314:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
The catalog is truly borked.
