### ISSUE TITLE
test_storage_usage_doesnt_update_between_restarts is flaky

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#17457]
### Buildkite link

https://buildkite.com/materialize/tests/builds/49266#01860906-2ab0-4e17-a59c-510c7818f2ad

### Relevant log output

```source
thread 'test_storage_usage_doesnt_update_between_restarts' panicked at 'assertion failed: `(left == right)`
  left: `1675189225.465`,
 right: `1675189245.883`', src/environmentd/tests/server.rs:661:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed::<f64, f64>
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:199:5
   4: server::test_storage_usage_doesnt_update_between_restarts
             at ./tests/server.rs:661:9
   5: server::test_storage_usage_doesnt_update_between_restarts::{closure#0}
             at ./tests/server.rs:624:56
   6: <server::test_storage_usage_doesnt_update_between_restarts::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507:5
```

**Comment by jkosh44** [comment]
I haven't been able to repro this locally, but my guess is that if it takes too long to restart Materialize in the test then another storage usage collection will happen and this will fail.
