### ISSUE TITLE
thread 'timely:work-1' panicked at 'failed to create a delayed capability, the current set does not have an element less than or equal to 1675327556000'

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#17484]
### What version of Materialize are you using?

cfb2b6cfb2ceed01aa0e4c832cad2b1a5cbe6948

### How did you install Materialize?

Docker image

### What is the issue?

Zippy just panicked as follows:

```
thread 'timely:work-1' panicked at 'failed to create a delayed capability, the current set does not have an element less than or equal to 1675327556000'
```

Please stand by for bisection.

### Relevant log output

```source
13
   0: rust_begin_unwind
             at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: <timely::dataflow::operators::capability::CapabilitySet<_>>::delayed::delayed_panic
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/6a73600/timely/src/dataflow/operators/capability.rs:446:13
   3: <timely::dataflow::operators::capability::CapabilitySet<mz_repr::timestamp::Timestamp>>::delayed::{closure#0}
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/6a73600/timely/src/dataflow/operators/capability.rs:454:32
   4: <core::option::Option<timely::dataflow::operators::capability::Capability<mz_repr::timestamp::Timestamp>>>::unwrap_or_else::<<
timely::dataflow::operators::capability::CapabilitySet<mz_repr::timestamp::Timestamp>>::delayed::{closure#0}>
             at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/option.rs:828:21
   5: <timely::dataflow::operators::capability::CapabilitySet<mz_repr::timestamp::Timestamp>>::delayed
             at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/6a73600/timely/src/dataflow/operators/capability.rs:453:9
   6: mz_storage::source::source_reader_pipeline::handle_message::<core::option::Option<alloc::vec::Vec<u8>>, core::option::Option<a
lloc::vec::Vec<u8>>, mz_timely_util::order::Partitioned<i32, mz_storage_client::types::sources::MzOffset>, ()>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0fd7d0fe5da9a5c16-1/materialize/tests/src/storage/src/
source/source_reader_pipeline.rs:1243:18
   7: mz_storage::source::source_reader_pipeline::reclock_operator::<timely::dataflow::scopes::child::Child<timely::dataflow::scopes
::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>, core:
:option::Option<alloc::vec::Vec<u8>>, core::option::Option<alloc::vec::Vec<u8>>, mz_timely_util::order::Partitioned<i32, mz_storage_
client::types::sources::MzOffset>, ()>::{closure#0}::{closure#0}
```

**Comment by philip-stoev** [comment]
Full stack trace is in here somewhere https://buildkite.com/organizations/materialize/pipelines/nightlies/builds/1752/jobs/01860f92-127f-4a60-bfed-51dd8ee92ea3/artifacts/01860f9f-95b2-4fde-b394-1e77202460ca . Multiple threads panicked at the same time, so outputs are overlapped.
