### ISSUE TITLE
regression: thread 'coordinator' panicked at 'reference to absent collection: CollectionMissing(User(343))'

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#17506]
### What version of Materialize are you using?

4e143a7

### How did you install Materialize?

Docker image

### What is the issue?

After being seen with a couple of branches, this panic is now seen on main . 

https://buildkite.com/materialize/nightlies/builds/1760#018614b2-2734-4a9d-9d3e-417fa55dcbc3

I am assigning this to @guswynn because it seems that he has some thoughts on the issue. Feel free to move it as appropriate.

### Relevant log output

```source
testdrive-materialized-1     | thread 'coordinator' panicked at 'reference to absent collection: CollectionMissing(User(343))', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0f05bd368667f1391-1/materialize/tests/src/compute-client/src/controller/instance.rs:847:18
testdrive-materialized-1     | stack backtrace:
testdrive-materialized-1     | environmentd: 2023-02-03T00:46:31.912233Z  INFO mz_storage_client::controller::rehydration: error connecting to storage cluster /tmp/environmentd-mzcompose-test-00000000-0000-0000-0000-000000000000-0/cluster-u1-replica-57/storagectl-0, retrying in 1s: transport error
testdrive-materialized-1     | environmentd: 2023-02-03T00:46:32.912980Z  INFO mz_storage_client::controller::rehydration: error connecting to storage cluster /tmp/environmentd-mzcompose-test-00000000-0000-0000-0000-000000000000-0/cluster-u1-replica-57/storagectl-0, retrying in 1s: transport error
testdrive-materialized-1     |    0: rust_begin_unwind
testdrive-materialized-1     |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
testdrive-materialized-1     |    1: core::panicking::panic_fmt
testdrive-materialized-1     |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
testdrive-materialized-1     |    2: core::result::unwrap_failed
testdrive-materialized-1     |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1791:5
testdrive-materialized-1     |    3: <core::result::Result<&mut mz_compute_client::controller::CollectionState<mz_repr::timestamp::Timestamp>, mz_compute_client::controller::error::CollectionMissing>>::expect
testdrive-materialized-1     |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1070:23
testdrive-materialized-1     |    4: <mz_compute_client::controller::instance::ActiveInstance<mz_repr::timestamp::Timestamp>>::update_write_frontiers
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0f05bd368667f1391-1/materialize/tests/src/compute-client/src/controller/instance.rs:844:30
testdrive-materialized-1     |    5: <mz_compute_client::controller::instance::ActiveInstance<mz_repr::timestamp::Timestamp>>::handle_subscribe_response
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0f05bd368667f1391-1/materialize/tests/src/compute-client/src/controller/instance.rs:1150:9
testdrive-materialized-1     |    6: <mz_compute_client::controller::instance::ActiveInstance<mz_repr::timestamp::Timestamp>>::handle_response
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0f05bd368667f1391-1/materialize/tests/src/compute-client/src/controller/instance.rs:1049:17
testdrive-materialized-1     |    7: <mz_compute_client::controller::ActiveComputeController<mz_repr::timestamp::Timestamp>>::process
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0f05bd368667f1391-1/materialize/tests/src/compute-client/src/controller.rs:603:24
testdrive-materialized-1     |    8: <mz_controller::Controller>::process::{closure#0}
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0f05bd368667f1391-1/materialize/tests/src/controller/src/lib.rs:298:32
testdrive-materialized-1     |    9: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0f05bd368667f1391-1/materialize/tests/src/adapter/src/coord/message_handler.rs:49:21
testdrive-materialized-1     |   10: <mz_adapter::coord::Coordinator>::serve::{closure#0}
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0f05bd368667f1391-1/materialize/tests/src/adapter/src/coord.rs:1179:37
testdrive-materialized-1     |   11: <tokio::runtime::park::CachedParkThread>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:63
testdrive-materialized-1     |   12: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}>
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:102:5
testdrive-materialized-1     |   13: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}>
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:68:5
testdrive-materialized-1     |   14: <tokio::runtime::park::CachedParkThread>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:31
testdrive-materialized-1     |   15: <tokio::runtime::context::BlockingRegionGuard>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/context.rs:315:13
testdrive-materialized-1     |   16: <tokio::runtime::handle::Handle>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/handle.rs:264:9
testdrive-materialized-1     |   17: mz_adapter::coord::serve::{closure#0}::{closure#1}
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0f05bd368667f1391-1/materialize/tests/src/adapter/src/coord.rs:1356:17
testdrive-materialized-1     | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by philip-stoev** [comment]
Previously seen in Sentry, but with a different stack trace - https://github.com/MaterializeInc/materialize/issues/17210

**Comment by philip-stoev** [comment]
Happened twice in the same Nightly- https://buildkite.com/materialize/nightlies/builds/1760#018614b2-272e-4e1b-a608-9973914adc80

**Comment by philip-stoev** [comment]
Also seen in regular testdrive https://buildkite.com/materialize/tests/builds/49434#018616d4-9693-4c48-93b1-c29e47c89174

**Comment by antiguru** [comment]
This is a different problem from #17210. Assigning to compute.

**Comment by teskje** [comment]
This was almost certainly introduced in https://github.com/MaterializeInc/materialize/pull/17473, which was merged on Thursday. So release 0.42 is not affected.

**Comment by jkosh44** [comment]
Just saw this again https://buildkite.com/materialize/tests/builds/49543#01862840-baaa-4fd9-8c33-cc3992427235

I don't think my PR would have any effect on Subscribe. Also the failure went away on retry.

**Comment by teskje** [comment]
Can you try teasing on main?

**Comment by jkosh44** [comment]
> Can you try rebasing on main?

Sure, I'll re-open this if I see it again, otherwise leave it closed.

**Comment by def-** [comment]
This seems to still be occurring: https://buildkite.com/materialize/tests/builds/49882#01864ffc-9532-4889-a3bf-c4b5beb09c15

```
platform-checks-materialized-1  | environmentd: 2023-02-14T13:12:25.440283Z  INFO mz_storage_client::controller::rehydration: error connecting to storage cluster /tmp/environmentd-mzcompose-test-00000000-0000-0000-0000-000000000000-0/cluster-u26-replica-28/storagectl-0, retrying in 1s: transport error
platform-checks-materialized-1  | cluster-u55-replica-57: 2023-02-14T13:12:25.476994Z  INFO mz_storage::source::resumption: resumption(u302) 1/4: calculated new resumption frontier resumption_frontier=Antichain { elements: [1676380345001] }
platform-checks-materialized-1  | cluster-u17-replica-19: 2023-02-14T13:12:25.497456Z  INFO mz_storage::source::resumption: resumption(u100) 0/4: calculated new resumption frontier resumption_frontier=Antichain { elements: [1676380345001] }
```
