### ISSUE TITLE
[SQLancer] thread 'coordinator' panicked at 'internal error: entered unreachable code: Expr::Nested not desugared'

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#17706]
### What version of Materialize are you using?

v0.44.0-dev (3c00b216e)

### How did you install Materialize?

Built from source

### What is the issue?

```
materialize> CREATE TABLE a(b int4range   DEFAULT (0));
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
connection to server was lost
```

### Relevant log output

```source
thread 'coordinator' panicked at 'internal error: entered unreachable code: Expr::Nested not desugared', src/sql/src/plan/query.rs:3239:28
stack backtrace:
   0:     0x5621e4be542a - std::backtrace_rs::backtrace::libunwind::trace::hbdb546ca92cb6d78
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5621e4be542a - std::backtrace_rs::backtrace::trace_unsynchronized::hc6fce42db22bfc5e
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5621e4be542a - std::sys_common::backtrace::_print_fmt::h81df7bc0b23e5237
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x5621e4be542a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc59be13e437abc01
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5621e4c0fcbe - core::fmt::write::h52ae72821e51c26c
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/core/src/fmt/mod.rs:1232:17
   5:     0x5621e4bdeba5 - std::io::Write::write_fmt::hd87c8dd79580982c
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/io/mod.rs:1684:15
   6:     0x5621e4be51f5 - std::sys_common::backtrace::_print::h20f47bfc31ead101
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x5621e4be51f5 - std::sys_common::backtrace::print::ha898201a02f1983d
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x5621e4be73ef - std::panicking::default_hook::{{closure}}::h53f82cfee6bbc6bc
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/panicking.rs:267:22
   9:     0x5621e4be712b - std::panicking::default_hook::ha6709b03b61260ba
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/panicking.rs:286:9
  10:     0x5621e39ad700 - <alloc[db76997d9b7d99b3]::boxed::Box<dyn for<'a, 'b> core[a4f442881c2ef06d]::ops::function::Fn<(&'a core[a4f442881c2ef06d]::panic::panic_info::PanicInfo<'b>,), Output = ()> + core[a4f442881c2ef06d]::marker::Send + core[a4f442881c2ef06d]::marker::Sync> as core[a4f442881c2ef06d]::ops::function::Fn<(&core[a4f442881c2ef06d]::panic::panic_info::PanicInfo,)>>::call
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/alloc/src/boxed.rs:2002:9
  11:     0x5621e38d265e - mz_ore[5a93c312fe4fb827]::panic::set_abort_on_panic::{closure#0}
                               at /home/deen/git/materialize/src/ore/src/panic.rs:57:9
  12:     0x5621e4be7b1a - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h2eed0239097b069b
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/alloc/src/boxed.rs:2002:9
  13:     0x5621e4be7b1a - std::panicking::rust_panic_with_hook::h1feda37d03dc2311
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/panicking.rs:692:13
  14:     0x5621e4be7899 - std::panicking::begin_panic_handler::{{closure}}::h04d1fa7b2fbcb101
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/panicking.rs:579:13
  15:     0x5621e4be58cc - std::sys_common::backtrace::__rust_end_short_backtrace::hd635f2032b0cab87
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/sys_common/backtrace.rs:137:18
  16:     0x5621e4be75a2 - rust_begin_unwind
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/panicking.rs:575:5
  17:     0x5621dca86f63 - core::panicking::panic_fmt::h5d8c50f99f6f87ff
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/core/src/panicking.rs:64:14
  18:     0x5621e06b0fdc - mz_sql[7406924c850828ee]::plan::query::plan_expr_inner
                               at /home/deen/git/materialize/src/sql/src/plan/query.rs:3239:28
  19:     0x5621e06b078d - mz_sql[7406924c850828ee]::plan::query::plan_expr::{closure#0}
                               at /home/deen/git/materialize/src/sql/src/plan/query.rs:3150:29
  20:     0x5621e030460f - <mz_sql[7406924c850828ee]::plan::query::ExprContext as mz_ore[5a93c312fe4fb827]::stack::CheckedRecursion>::checked_recur::<mz_sql[7406924c850828ee]::plan::query::plan_expr::{closure#0}, mz_sql[7406924c850828ee]::plan::expr::CoercibleScalarExpr, mz_sql[7406924c850828ee]::plan::error::PlanError>::{closure#0}
                               at /home/deen/git/materialize/src/ore/src/stack.rs:191:33
  21:     0x5621e06b067a - stacker[a6b7626200997e5b]::maybe_grow::<core[a4f442881c2ef06d]::result::Result<mz_sql[7406924c850828ee]::plan::expr::CoercibleScalarExpr, mz_sql[7406924c850828ee]::plan::error::PlanError>, <mz_sql[7406924c850828ee]::plan::query::ExprContext as mz_ore[5a93c312fe4fb827]::stack::CheckedRecursion>::checked_recur<mz_sql[7406924c850828ee]::plan::query::plan_expr::{closure#0}, mz_sql[7406924c850828ee]::plan::expr::CoercibleScalarExpr, mz_sql[7406924c850828ee]::plan::error::PlanError>::{closure#0}>
                               at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  22:     0x5621e06b067a - mz_ore[5a93c312fe4fb827]::stack::maybe_grow::<<mz_sql[7406924c850828ee]::plan::query::ExprContext as mz_ore[5a93c312fe4fb827]::stack::CheckedRecursion>::checked_recur<mz_sql[7406924c850828ee]::plan::query::plan_expr::{closure#0}, mz_sql[7406924c850828ee]::plan::expr::CoercibleScalarExpr, mz_sql[7406924c850828ee]::plan::error::PlanError>::{closure#0}, core[a4f442881c2ef06d]::result::Result<mz_sql[7406924c850828ee]::plan::expr::CoercibleScalarExpr, mz_sql[7406924c850828ee]::plan::error::PlanError>>
                               at /home/deen/git/materialize/src/ore/src/stack.rs:100:5
  23:     0x5621e06b067a - <mz_sql[7406924c850828ee]::plan::query::ExprContext as mz_ore[5a93c312fe4fb827]::stack::CheckedRecursion>::checked_recur::<mz_sql[7406924c850828ee]::plan::query::plan_expr::{closure#0}, mz_sql[7406924c850828ee]::plan::expr::CoercibleScalarExpr, mz_sql[7406924c850828ee]::plan::error::PlanError>
                               at /home/deen/git/materialize/src/ore/src/stack.rs:191:19
  24:     0x5621e06b067a - mz_sql[7406924c850828ee]::plan::query::plan_expr
                               at /home/deen/git/materialize/src/sql/src/plan/query.rs:3150:5
  25:     0x5621e0681883 - mz_sql[7406924c850828ee]::plan::query::plan_default_expr
                               at /home/deen/git/materialize/src/sql/src/plan/query.rs:909:15
  26:     0x5621e06da5f4 - mz_sql[7406924c850828ee]::plan::statement::ddl::plan_create_table
                               at /home/deen/git/materialize/src/sql/src/plan/statement/ddl.rs:223:29
  27:     0x5621e017483a - mz_sql[7406924c850828ee]::plan::statement::plan
                               at /home/deen/git/materialize/src/sql/src/plan/statement.rs:273:41
  28:     0x5621df0e7c57 - <mz_adapter[113a048ce3afdcb4]::coord::Coordinator>::plan_statement
                               at /home/deen/git/materialize/src/adapter/src/coord/sql.rs:31:20
  29:     0x5621dd0c6239 - <mz_adapter[113a048ce3afdcb4]::coord::Coordinator>::handle_execute_inner::{closure#0}::{closure#0}
                               at /home/deen/git/materialize/src/adapter/src/coord/command_handler.rs:468:24
  30:     0x5621dd101b76 - <mz_adapter[113a048ce3afdcb4]::coord::Coordinator>::handle_execute_inner::{closure#0}
                               at /home/deen/git/materialize/src/adapter/src/coord/command_handler.rs:273:5
  31:     0x5621dd0c52b0 - <mz_adapter[113a048ce3afdcb4]::coord::Coordinator>::handle_execute::{closure#0}::{closure#0}
                               at /home/deen/git/materialize/src/adapter/src/coord/command_handler.rs:270:61
  32:     0x5621dd0feccd - <mz_adapter[113a048ce3afdcb4]::coord::Coordinator>::handle_execute::{closure#0}
                               at /home/deen/git/materialize/src/adapter/src/coord/command_handler.rs:229:5
  33:     0x5621ddea9368 - <tracing[6d2ce0cbdcfad733]::instrument::Instrumented<<mz_adapter[113a048ce3afdcb4]::coord::Coordinator>::handle_execute::{closure#0}> as core[a4f442881c2ef06d]::future::future::Future>::poll
                               at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  34:     0x5621dd0fd769 - <mz_adapter[113a048ce3afdcb4]::coord::Coordinator>::handle_command::{closure#0}
                               at /home/deen/git/materialize/src/adapter/src/coord/command_handler.rs:65:21
  35:     0x5621dcef3951 - <mz_adapter[113a048ce3afdcb4]::coord::Coordinator>::message_command::{closure#0}::{closure#0}
                               at /home/deen/git/materialize/src/adapter/src/coord/message_handler.rs:242:33
  36:     0x5621dcf0f024 - <mz_adapter[113a048ce3afdcb4]::coord::Coordinator>::message_command::{closure#0}
                               at /home/deen/git/materialize/src/adapter/src/coord/message_handler.rs:239:5
  37:     0x5621dcf0e481 - <mz_adapter[113a048ce3afdcb4]::coord::Coordinator>::handle_message::{closure#0}
                               at /home/deen/git/materialize/src/adapter/src/coord/message_handler.rs:44:63
  38:     0x5621dd13a52d - <mz_adapter[113a048ce3afdcb4]::coord::Coordinator>::serve::{closure#0}
                               at /home/deen/git/materialize/src/adapter/src/coord.rs:1179:37
  39:     0x5621dd091654 - <tokio[bfe3514c811b3bf9]::runtime::park::CachedParkThread>::block_on::<<mz_adapter[113a048ce3afdcb4]::coord::Coordinator>::serve::{closure#0}>::{closure#0}
                               at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:63
  40:     0x5621dd0300e1 - tokio[bfe3514c811b3bf9]::runtime::coop::with_budget::<core[a4f442881c2ef06d]::task::poll::Poll<()>, <tokio[bfe3514c811b3bf9]::runtime::park::CachedParkThread>::block_on<<mz_adapter[113a048ce3afdcb4]::coord::Coordinator>::serve::{closure#0}>::{closure#0}>
                               at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:102:5
  41:     0x5621dd0300e1 - tokio[bfe3514c811b3bf9]::runtime::coop::budget::<core[a4f442881c2ef06d]::task::poll::Poll<()>, <tokio[bfe3514c811b3bf9]::runtime::park::CachedParkThread>::block_on<<mz_adapter[113a048ce3afdcb4]::coord::Coordinator>::serve::{closure#0}>::{closure#0}>
                               at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:68:5
  42:     0x5621dd0300e1 - <tokio[bfe3514c811b3bf9]::runtime::park::CachedParkThread>::block_on::<<mz_adapter[113a048ce3afdcb4]::coord::Coordinator>::serve::{closure#0}>
                               at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:31
  43:     0x5621dd030fb6 - <tokio[bfe3514c811b3bf9]::runtime::context::BlockingRegionGuard>::block_on::<<mz_adapter[113a048ce3afdcb4]::coord::Coordinator>::serve::{closure#0}>
                               at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/context.rs:315:13
  44:     0x5621dd1ad3e5 - <tokio[bfe3514c811b3bf9]::runtime::handle::Handle>::block_on::<<mz_adapter[113a048ce3afdcb4]::coord::Coordinator>::serve::{closure#0}>
                               at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/handle.rs:264:9
  45:     0x5621dd0fa464 - mz_adapter[113a048ce3afdcb4]::coord::serve::{closure#0}::{closure#1}
                               at /home/deen/git/materialize/src/adapter/src/coord.rs:1356:17
  46:     0x5621dce5e5a3 - std[c4719229b53c8129]::sys_common::backtrace::__rust_begin_short_backtrace::<mz_adapter[113a048ce3afdcb4]::coord::serve::{closure#0}::{closure#1}, ()>
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/sys_common/backtrace.rs:121:18
  47:     0x5621dd476cb3 - <std[c4719229b53c8129]::thread::Builder>::spawn_unchecked_::<mz_adapter[113a048ce3afdcb4]::coord::serve::{closure#0}::{closure#1}, ()>::{closure#1}::{closure#0}
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/thread/mod.rs:558:17
  48:     0x5621dcff66e3 - <core[a4f442881c2ef06d]::panic::unwind_safe::AssertUnwindSafe<<std[c4719229b53c8129]::thread::Builder>::spawn_unchecked_<mz_adapter[113a048ce3afdcb4]::coord::serve::{closure#0}::{closure#1}, ()>::{closure#1}::{closure#0}> as core[a4f442881c2ef06d]::ops::function::FnOnce<()>>::call_once
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/core/src/panic/unwind_safe.rs:271:9
  49:     0x5621de2d58a5 - std[c4719229b53c8129]::panicking::try::do_call::<core[a4f442881c2ef06d]::panic::unwind_safe::AssertUnwindSafe<<std[c4719229b53c8129]::thread::Builder>::spawn_unchecked_<mz_adapter[113a048ce3afdcb4]::coord::serve::{closure#0}::{closure#1}, ()>::{closure#1}::{closure#0}>, ()>
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/panicking.rs:483:40
  50:     0x5621de301cab - __rust_try
  51:     0x5621de2a9932 - std[c4719229b53c8129]::panicking::try::<(), core[a4f442881c2ef06d]::panic::unwind_safe::AssertUnwindSafe<<std[c4719229b53c8129]::thread::Builder>::spawn_unchecked_<mz_adapter[113a048ce3afdcb4]::coord::serve::{closure#0}::{closure#1}, ()>::{closure#1}::{closure#0}>>
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/panicking.rs:447:19
  52:     0x5621de07373a - std[c4719229b53c8129]::panic::catch_unwind::<core[a4f442881c2ef06d]::panic::unwind_safe::AssertUnwindSafe<<std[c4719229b53c8129]::thread::Builder>::spawn_unchecked_<mz_adapter[113a048ce3afdcb4]::coord::serve::{closure#0}::{closure#1}, ()>::{closure#1}::{closure#0}>, ()>
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/panic.rs:140:14
  53:     0x5621dd45823e - <std[c4719229b53c8129]::thread::Builder>::spawn_unchecked_::<mz_adapter[113a048ce3afdcb4]::coord::serve::{closure#0}::{closure#1}, ()>::{closure#1}
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/thread/mod.rs:557:30
  54:     0x5621dd71e52e - <<std[c4719229b53c8129]::thread::Builder>::spawn_unchecked_<mz_adapter[113a048ce3afdcb4]::coord::serve::{closure#0}::{closure#1}, ()>::{closure#1} as core[a4f442881c2ef06d]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/core/src/ops/function.rs:250:5
  55:     0x5621e4bed8f3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h16d50f6a791b9ecf
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/alloc/src/boxed.rs:1988:9
  56:     0x5621e4bed8f3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hcb8a06476f463180
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/alloc/src/boxed.rs:1988:9
  57:     0x5621e4bed8f3 - std::sys::unix::thread::Thread::new::thread_start::hf9921b6eef74fae1
                               at /rustc/0416b1a6f6d5c42696494e1a3a33580fd3f669d8/library/std/src/sys/unix/thread.rs:108:17
  58:     0x7fce20090402 - <unknown>
  59:     0x7fce2011f590 - <unknown>
  60:                0x0 - <unknown>
```

**Comment by ggevay** [comment]
`(0)` is an `Expr::Nested`, due to the extra parenthesis. `Expr::Nested` should have been desugared (eliminated) before `plan_expr` compiles the expression to HIR.

Specifically, the problem is that `transform_ast::transform_expr` is not called before `plan_expr` in `plan_default_expr`. `transform_ast::transform_expr` would call `Desugarer`, which would eliminate `Expr::Nested` (and other things, e.g., the `BETWEEN` in something like `CREATE TABLE t2(b bool DEFAULT 5 BETWEEN 3 and 7);`, which is currently also failing).

Unfortunately, this same problem might be happening in many other places. All 65 calls to `plan_expr` in `query.rs` are suspect. For example, 
```
CREATE TABLE t4 (a INT, b INT, c INT);
INSERT INTO t4 (a) VALUES (2),(3) RETURNING a, (c);
```
is also failing, due to the same issue at the call to `plan_expr` in `plan_insert_query`, where it tries to handle the `RETURNING` clause.

In MIR, we have an `OptimizedMirRelationExpr` type to prevent similar problems. This is just a marker type on top of an `MirRelationExpr`, indicating that it was optimized. Maybe a similar type could be created for `Expr`, to mark whether `transform_expr` was already called on it. And then `plan_expr` would accept only this new marker type, and then the Rust compiler complains if we forget to call `transform_expr`.

**Comment by benesch** [comment]
> In MIR, we have an `OptimizedMirRelationExpr` type to prevent similar problems. This is just a marker type on top of an `MirRelationExpr`, indicating that it was optimized. Maybe a similar type could be created for `Expr`, to mark whether `transform_expr` was already called on it. And then `plan_expr` would accept only this new marker type, and then the Rust compiler would complain if we forget to call `transform_expr`.

It's unfortunately not so straightforward in SQL land, because the IR consists of 100+ types. Most of those calls to `plan_expr` are safe, because they are called on an `Expr` that is embedded deep inside a `Statement`, and `transform_statement` was called on the root statement.
