### ISSUE TITLE
persist: new storage usage implementation crashes in some environments

### ISSUE THREAD

**Issue by benesch** [MaterializeInc/materialize#17752]
### What version of Materialize are you using?

v0.44.1

### How did you install Materialize?

Materialize Cloud

### What is the issue?

The new persist shard usage computation (added in 212ff8f) appears to crash in some environments. See logs below. Slack conversations:

  * https://materializeinc.slack.com/archives/CM7ATT65S/p1676724816260809
  * https://materializeinc.slack.com/archives/CTESPM7FU/p1676886532146809

### Relevant log output

```source
environmentd thread 'tokio:work-0' panicked at 'blob inputs should be cumulative', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0bb7f49852c7c6d14-1/materialize/tests/src/persist-client/src/usage.rs:409:28
environmentd stack backtrace:
environmentd    0: rust_begin_unwind
environmentd              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
environmentd    1: core::panicking::panic_fmt
environmentd              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
environmentd    2: core::panicking::panic_display
environmentd              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:135:5
environmentd    3: core::panicking::panic_str
environmentd              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:119:5
environmentd    4: core::option::expect_failed
environmentd              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/option.rs:1879:5
environmentd    5: <core::option::Option<u64>>::expect
environmentd              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/option.rs:741:21
environmentd    6: <mz_persist_client::usage::ShardUsage as core::convert::From<mz_persist_client::usage::ShardUsageCumulativeMaybeRacy<mz_persist_client::internal::state::WriterState<u64>>>>::from
environmentd              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0bb7f49852c7c6d14-1/materialize/tests/src/persist-client/src/usage.rs:409:28
environmentd    7: <mz_persist_client::usage::StorageUsageClient>::shard_usage_given_blob_usage::{closure#0}
environmentd              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0bb7f49852c7c6d14-1/materialize/tests/src/persist-client/src/usage.rs:325:19
environmentd    8: <mz_persist_client::usage::StorageUsageClient>::shards_usage::{closure#0}::{closure#0}
environmentd              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0bb7f49852c7c6d14-1/materialize/tests/src/persist-client/src/usage.rs:194:21
environmentd    9: <futures_util::stream::futures_unordered::FuturesUnordered<<mz_persist_client::usage::StorageUsageClient>::shards_usage::{closure#0}::{closure#0}> as futures_core::stream::Stream>::poll_next
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/stream/futures_unordered/mod.rs:515:17
environmentd   10: <futures_util::stream::stream::collect::Collect<futures_util::stream::futures_unordered::FuturesUnordered<<mz_persist_client::usage::StorageUsageClient>::shards_usage::{closure#0}::{closure#0}>, alloc::collections::btree::map::BTreeMap<mz_persist_client::ShardId, mz_persist_client::usage::ShardUsage>> as core::future::future::Future>::poll
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/stream/stream/collect.rs:50:26
environmentd   11: <mz_persist_client::usage::StorageUsageClient>::shards_usage::{closure#0}
environmentd              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0bb7f49852c7c6d14-1/materialize/tests/src/persist-client/src/usage.rs:200:50
environmentd   12: <mz_adapter::coord::Coordinator>::storage_usage_fetch::{closure#0}::{closure#0}::{closure#3}
environmentd              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0bb7f49852c7c6d14-1/materialize/tests/src/adapter/src/coord/message_handler.rs:145:56
environmentd   13: <tokio::runtime::task::core::Core<<mz_adapter::coord::Coordinator>::storage_usage_fetch::{closure#0}::{closure#0}::{closure#3}, alloc::sync::Arc<tokio::runtime::scheduler::current_thread::Handle>>>::poll::{closure#0}
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/core.rs:223:17
environmentd   14: <tokio::loom::std::unsafe_cell::UnsafeCell<tokio::runtime::task::core::Stage<<mz_adapter::coord::Coordinator>::storage_usage_fetch::{closure#0}::{closure#0}::{closure#3}>>>::with_mut::<core::task::poll::Poll<()>, <tokio::runtime::task::core::Core<<mz_adapter::coord::Coordinator>::storage_usage_fetch::{closure#0}::{closure#0}::{closure#3}, alloc::sync::Arc<tokio::runtime::scheduler::current_thread::Handle>>>::poll::{closure#0}>
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/loom/std/unsafe_cell.rs:14:9
environmentd   15: <tokio::runtime::task::core::Core<<mz_adapter::coord::Coordinator>::storage_usage_fetch::{closure#0}::{closure#0}::{closure#3}, alloc::sync::Arc<tokio::runtime::scheduler::current_thread::Handle>>>::poll
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/core.rs:212:13
environmentd   16: tokio::runtime::task::harness::poll_future::<<mz_adapter::coord::Coordinator>::storage_usage_fetch::{closure#0}::{closure#0}::{closure#3}, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>::{closure#0}
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/harness.rs:476:19
environmentd   17: <core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<<mz_adapter::coord::Coordinator>::storage_usage_fetch::{closure#0}::{closure#0}::{closure#3}, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>::{closure#0}> as core::ops::function::FnOnce<()>>::call_once
environmentd              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panic/unwind_safe.rs:271:9
environmentd   18: std::panicking::try::do_call::<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<<mz_adapter::coord::Coordinator>::storage_usage_fetch::{closure#0}::{closure#0}::{closure#3}, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>::{closure#0}>, core::task::poll::Poll<()>>
environmentd              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:483:40
environmentd   19: std::panicking::try::<core::task::poll::Poll<()>, core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<<mz_adapter::coord::Coordinator>::storage_usage_fetch::{closure#0}::{closure#0}::{closure#3}, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>::{closure#0}>>
environmentd              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:447:19
environmentd   20: std::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<<mz_adapter::coord::Coordinator>::storage_usage_fetch::{closure#0}::{closure#0}::{closure#3}, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>::{closure#0}>, core::task::poll::Poll<()>>
environmentd              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panic.rs:137:14
environmentd   21: tokio::runtime::task::harness::poll_future::<<mz_adapter::coord::Coordinator>::storage_usage_fetch::{closure#0}::{closure#0}::{closure#3}, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/harness.rs:464:18
environmentd   22: <tokio::runtime::task::harness::Harness<<mz_adapter::coord::Coordinator>::storage_usage_fetch::{closure#0}::{closure#0}::{closure#3}, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll_inner
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/harness.rs:198:27
environmentd   23: <tokio::runtime::task::harness::Harness<<mz_adapter::coord::Coordinator>::storage_usage_fetch::{closure#0}::{closure#0}::{closure#3}, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/harness.rs:152:15
environmentd   24: <tokio::runtime::task::raw::RawTask>::poll
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/raw.rs:200:18
environmentd   25: <tokio::runtime::task::LocalNotified<alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::run
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/mod.rs:394:9
environmentd   26: <tokio::runtime::scheduler::multi_thread::worker::Context>::run_task::{closure#0}
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/scheduler/multi_thread/worker.rs:487:21
environmentd   27: tokio::runtime::coop::with_budget::<core::result::Result<alloc::boxed::Box<tokio::runtime::scheduler::multi_thread::worker::Core>, ()>, <tokio::runtime::scheduler::multi_thread::worker::Context>::run_task::{closure#0}>
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:102:5
environmentd   28: tokio::runtime::coop::budget::<core::result::Result<alloc::boxed::Box<tokio::runtime::scheduler::multi_thread::worker::Core>, ()>, <tokio::runtime::scheduler::multi_thread::worker::Context>::run_task::{closure#0}>
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:68:5
environmentd   29: <tokio::runtime::scheduler::multi_thread::worker::Context>::run_task
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/scheduler/multi_thread/worker.rs:463:9
environmentd   30: <tokio::runtime::scheduler::multi_thread::worker::Context>::run
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/scheduler/multi_thread/worker.rs:433:24
environmentd   31: tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/scheduler/multi_thread/worker.rs:406:17
environmentd   32: <tokio::macros::scoped_tls::ScopedKey<tokio::runtime::scheduler::multi_thread::worker::Context>>::set::<tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}, ()>
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/macros/scoped_tls.rs:61:9
environmentd   33: tokio::runtime::scheduler::multi_thread::worker::run
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/scheduler/multi_thread/worker.rs:403:5
environmentd   34: <tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/scheduler/multi_thread/worker.rs:365:45
environmentd   35: <tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}> as core::future::future::Future>::poll
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/blocking/task.rs:42:21
environmentd   36: <tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll::{closure#0}
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/core.rs:223:17
environmentd   37: <tokio::loom::std::unsafe_cell::UnsafeCell<tokio::runtime::task::core::Stage<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>>>>::with_mut::<core::task::poll::Poll<()>, <tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll::{closure#0}>
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/loom/std/unsafe_cell.rs:14:9
environmentd   38: <tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/core.rs:212:13
environmentd   39: tokio::runtime::task::harness::poll_future::<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/harness.rs:476:19
environmentd   40: <core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}> as core::ops::function::FnOnce<()>>::call_once
environmentd              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panic/unwind_safe.rs:271:9
environmentd   41: std::panicking::try::do_call::<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}>, core::task::poll::Poll<()>>
environmentd              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:483:40
environmentd   42: std::panicking::try::<core::task::poll::Poll<()>, core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}>>
environmentd              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:447:19
environmentd   43: std::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}>, core::task::poll::Poll<()>>
environmentd              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panic.rs:137:14
environmentd   44: tokio::runtime::task::harness::poll_future::<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/harness.rs:464:18
environmentd   45: <tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll_inner
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/harness.rs:198:27
environmentd   46: <tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/harness.rs:152:15
environmentd   47: <tokio::runtime::task::raw::RawTask>::poll
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/raw.rs:200:18
environmentd   48: <tokio::runtime::task::UnownedTask<tokio::runtime::blocking::schedule::BlockingSchedule>>::run
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/task/mod.rs:431:9
environmentd   49: <tokio::runtime::blocking::pool::Task>::run
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/blocking/pool.rs:159:9
environmentd   50: <tokio::runtime::blocking::pool::Inner>::run
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/blocking/pool.rs:511:17
environmentd   51: <tokio::runtime::blocking::pool::Spawner>::spawn_thread::{closure#0}
environmentd              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/blocking/pool.rs:469:13
environmentd note: Some details are omitted, run with `RUST_


thread 'tokio:work-5' panicked at 'fetch_live_states should only be called on an initialized shard', /home/alexander/workspace/materialize/src/persist-client/src/internal/state_versions.rs:437:25
```

**Comment by bkirwi** [comment]
I suspect this issue actually involves two bugs.

The "fetch_live_states should only be called on an initialized shard" seems relatively straightforward... we're discovering shards by searching through S3 and then passing them to a function that expects them to exist in consensus. We should be able to return option in the function in question instead of panicking, but maybe there's some more clever solution.

The "blob inputs should be cumulative" is a little thornier. The total blob size is calculated directly from S3, and the referenced blob size is calculated by checking for all the blobs referenced in state. There are a few more-or-less-plausible reasons I can imagine for this (in-progress GC having deleted blobs before diffs that reference them, blobs getting added after the scan of S3, slightly different semantics when processing diffs directly vs. state rollups, etc.). There may be some more to look into there, but it does feel like we probably don't want to panic during usage calculations regardless...

**Comment by danhhz** [comment]
I'm just catching up here, so these are my naive initial reactions..

> The "fetch_live_states should only be called on an initialized shard" seems relatively straightforward... we're discovering shards by searching through S3 and then passing them to a function that expects them to exist in consensus. We should be able to return option in the function in question instead of panicking, but maybe there's some more clever solution.

I'm super surprised to find a shard in blob that's not in consensus! Even shard "deletion" leaves an unchanging tombstone in CRDB. It's definitely also worth looking into why this is happening in the first place

> The "blob inputs should be cumulative" is a little thornier. The total blob size is calculated directly from S3, and the referenced blob size is calculated by checking for all the blobs referenced in state. There are a few more-or-less-plausible reasons I can imagine for this (in-progress GC having deleted blobs before diffs that reference them, blobs getting added after the scan of S3, slightly different semantics when processing diffs directly vs. state rollups, etc.). There may be some more to look into there, but it does feel like we probably don't want to panic during usage calculations regardless...

Yeah, that code is tricky but it already tries to account for these sorts of things. My guess is this one is just some programming error on my part

**Comment by danhhz** [comment]
Okay, I'd bet the "blob inputs should be cumulative" bug is this line. Otherwise, it'd be pretty hard to imagine any ways for `total_bytes` to be smaller than `not_leaked_bytes`. If so, should be easy to type up a regression unit test https://github.com/MaterializeInc/materialize/blob/main/src/persist-client/src/usage.rs#L401

**Comment by danhhz** [comment]
First fix is up https://github.com/MaterializeInc/materialize/pull/17765

**Comment by danhhz** [comment]
I have a theory for "fetch_live_states should only be called on an initialized shard". This panic means that we have data in blob for some shard, but nothing in consensus for that shard.

We're pretty careful about not doing that, and the only instance we have of this occurring is a local developer, so my theory is that a `bin/environmentd --reset` got interrupted. We intentionally clear consensus first and then blob (ironically, due to [a previous bug that resulted in a scary-sounding persist panic](https://github.com/MaterializeInc/materialize/pull/16553)). If that process gets interrupted after it has cleared consensus, but while it hasn't yet finished clearing blob, then we'd almost certainly see exactly this.

Now that I can explain how we might have gotten in this situation, I agree that Ben's proposal above to "return option in the function in question instead of panicking" (and thus make persist resilient to it) is the fix.

If it only might happen in response to `bin/environmentd --reset`, then I'd be tempted to explore some other fixes, but along the way, I also hypothesized a different cause: while a shard is being initialized, someone writes the initial rollup but gets interrupted before the initial compare_and_set. By policy, mz writes down shard_ids before using them, so if this did happen it should fix itself, but it's still better to be resilient (and also maybe there's a bug at some point and we don't write down a shard_id before trying to use it).

**Comment by danhhz** [comment]
Second fix is up https://github.com/MaterializeInc/materialize/pull/17773
