### ISSUE TITLE
[SQLancer] thread 'coordinator' panicked at 'byte index 5 is not a char boundary; it is inside '艷' (bytes 3..6) of `栬艷^Ằ[221714110`', src/ore/src/lex.rs:94:13

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#17800]
### What version of Materialize are you using?

v0.45.0-dev (f01773c)

### How did you install Materialize?

Built from source

### What is the issue?

```
$ cat q
CREATE TABLE IF NOT EXISTS t4(c0 int4range);
INSERT INTO t4(c0) VALUES('栬艷^Ằ[');
$ psql postgres://materialize@localhost:6875 -f q
CREATE TABLE
psql:q:2: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
psql:q: fatal: connection to server was lost
```

### Relevant log output

```source
environmentd: 2023-02-23T14:23:36.801205Z  INFO mz_adapter::catalog: create table database1.public.t4 (u9)
thread 'coordinator' panicked at 'byte index 5 is not a char boundary; it is inside '艷' (bytes 3..6) of `栬艷^Ằ[221714110`', src/ore/src/lex.rs:94:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/panicking.rs:64:14
   2: core::str::slice_error_fail_rt
   3: core::str::slice_error_fail
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/str/mod.rs:86:9
   4: core::str::traits::<impl core::slice::index::SliceIndex<str> for core::ops::range::Range<usize>>::index
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/str/traits.rs:218:21
   5: <str as core::ops::index::Index<core::ops::range::Range<usize>>>::index
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/str/traits.rs:65:9
   6: <mz_ore::lex::LexBuf>::consume_str
             at ./src/ore/src/lex.rs:94:13
   7: mz_repr::strconv::parse_range_inner::<mz_repr::scalar::Datum, mz_expr::scalar::EvalError, <mz_expr::scalar::func::impls::string::CastStringToRange as mz_expr::scalar::func::LazyUnaryFunc>::eval::{closure#0}>
             at ./src/repr/src/strconv.rs:1210:8
   8: mz_repr::strconv::parse_range::<mz_repr::scalar::Datum, mz_expr::scalar::EvalError, <mz_expr::scalar::func::impls::string::CastStringToRange as mz_expr::scalar::func::LazyUnaryFunc>::eval::{closure#0}>
             at ./src/repr/src/strconv.rs:1193:16
   9: <mz_expr::scalar::func::impls::string::CastStringToRange as mz_expr::scalar::func::LazyUnaryFunc>::eval
             at ./src/expr/src/scalar/func/impls/string.rs:522:25
  10: <mz_expr::scalar::func::UnaryFunc>::eval
             at ./src/expr/src/scalar/func/macros.rs:289:41
  11: <mz_expr::scalar::MirScalarExpr>::eval
             at ./src/expr/src/scalar/mod.rs:1749:56
  12: <mz_expr::scalar::MirScalarExpr>::reduce::{closure#0}
             at ./src/expr/src/scalar/mod.rs:672:36
  13: <mz_expr::scalar::MirScalarExpr>::reduce::{closure#2}
             at ./src/expr/src/scalar/mod.rs:728:34
  14: stacker::maybe_grow::<(), <mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr>>::visit_mut_pre_post_nolimit<<mz_expr::scalar::MirScalarExpr>::reduce::{closure#1}, <mz_expr::scalar::MirScalarExpr>::reduce::{closure#2}>::{closure#0}>
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  15: mz_ore::stack::maybe_grow::<<mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr>>::visit_mut_pre_post_nolimit<<mz_expr::scalar::MirScalarExpr>::reduce::{closure#1}, <mz_expr::scalar::MirScalarExpr>::reduce::{closure#2}>::{closure#0}, ()>
             at ./src/ore/src/stack.rs:100:5
  16: <mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr>>::visit_mut_pre_post_nolimit::<<mz_expr::scalar::MirScalarExpr>::reduce::{closure#1}, <mz_expr::scalar::MirScalarExpr>::reduce::{closure#2}>
             at ./src/expr/src/visit.rs:711:9
  17: <mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr>>::visit_mut_pre_post_nolimit::<<mz_expr::scalar::MirScalarExpr>::reduce::{closure#1}, <mz_expr::scalar::MirScalarExpr>::reduce::{closure#2}>::{closure#0}::{closure#0}
             at ./src/expr/src/visit.rs:717:50
  18: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::VisitChildren<mz_expr::scalar::MirScalarExpr>>::visit_mut_children::<<mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr>>::visit_mut_pre_post_nolimit<<mz_expr::scalar::MirScalarExpr>::reduce::{closure#1}, <mz_expr::scalar::MirScalarExpr>::reduce::{closure#2}>::{closure#0}::{closure#0}>
             at ./src/expr/src/scalar/mod.rs:1859:17
  19: <mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr>>::visit_mut_pre_post_nolimit::<<mz_expr::scalar::MirScalarExpr>::reduce::{closure#1}, <mz_expr::scalar::MirScalarExpr>::reduce::{closure#2}>::{closure#0}
             at ./src/expr/src/visit.rs:717:17
  20: stacker::maybe_grow::<(), <mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr>>::visit_mut_pre_post_nolimit<<mz_expr::scalar::MirScalarExpr>::reduce::{closure#1}, <mz_expr::scalar::MirScalarExpr>::reduce::{closure#2}>::{closure#0}>
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  21: mz_ore::stack::maybe_grow::<<mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr>>::visit_mut_pre_post_nolimit<<mz_expr::scalar::MirScalarExpr>::reduce::{closure#1}, <mz_expr::scalar::MirScalarExpr>::reduce::{closure#2}>::{closure#0}, ()>
             at ./src/ore/src/stack.rs:100:5
  22: <mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr>>::visit_mut_pre_post_nolimit::<<mz_expr::scalar::MirScalarExpr>::reduce::{closure#1}, <mz_expr::scalar::MirScalarExpr>::reduce::{closure#2}>
             at ./src/expr/src/visit.rs:711:9
  23: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::Visit>::visit_mut_pre_post_nolimit::<<mz_expr::scalar::MirScalarExpr>::reduce::{closure#1}, <mz_expr::scalar::MirScalarExpr>::reduce::{closure#2}>
             at ./src/expr/src/visit.rs:439:9
  24: <mz_expr::scalar::MirScalarExpr>::reduce
             at ./src/expr/src/scalar/mod.rs:680:13
  25: <mz_transform::fold_constants::FoldConstants>::action::<core::iter::adapters::map::Map<core::slice::iter::Iter<mz_repr::relation::RelationType>, <mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform::{closure#0}::{closure#0}>>
             at ./src/transform/src/fold_constants.rs:173:21
  26: <mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform::{closure#0}
             at ./src/transform/src/fold_constants.rs:51:13
  27: <mz_expr::visit::StackSafeVisit<mz_expr::relation::MirRelationExpr>>::try_visit_mut_post::<<mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform::{closure#0}, mz_transform::TransformError>::{closure#0}
             at ./src/expr/src/visit.rs:556:13
  28: <mz_expr::visit::StackSafeVisit<mz_expr::relation::MirRelationExpr> as mz_ore::stack::CheckedRecursion>::checked_recur::<<mz_expr::visit::StackSafeVisit<mz_expr::relation::MirRelationExpr>>::try_visit_mut_post<<mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform::{closure#0}, mz_transform::TransformError>::{closure#0}, (), mz_transform::TransformError>::{closure#0}
             at ./src/ore/src/stack.rs:191:33
  29: stacker::maybe_grow::<core::result::Result<(), mz_transform::TransformError>, <mz_expr::visit::StackSafeVisit<mz_expr::relation::MirRelationExpr> as mz_ore::stack::CheckedRecursion>::checked_recur<<mz_expr::visit::StackSafeVisit<mz_expr::relation::MirRelationExpr>>::try_visit_mut_post<<mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform::{closure#0}, mz_transform::TransformError>::{closure#0}, (), mz_transform::TransformError>::{closure#0}>
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  30: mz_ore::stack::maybe_grow::<<mz_expr::visit::StackSafeVisit<mz_expr::relation::MirRelationExpr> as mz_ore::stack::CheckedRecursion>::checked_recur<<mz_expr::visit::StackSafeVisit<mz_expr::relation::MirRelationExpr>>::try_visit_mut_post<<mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform::{closure#0}, mz_transform::TransformError>::{closure#0}, (), mz_transform::TransformError>::{closure#0}, core::result::Result<(), mz_transform::TransformError>>
             at ./src/ore/src/stack.rs:100:5
  31: <mz_expr::visit::StackSafeVisit<mz_expr::relation::MirRelationExpr> as mz_ore::stack::CheckedRecursion>::checked_recur::<<mz_expr::visit::StackSafeVisit<mz_expr::relation::MirRelationExpr>>::try_visit_mut_post<<mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform::{closure#0}, mz_transform::TransformError>::{closure#0}, (), mz_transform::TransformError>
             at ./src/ore/src/stack.rs:191:19
  32: <mz_expr::visit::StackSafeVisit<mz_expr::relation::MirRelationExpr>>::try_visit_mut_post::<<mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform::{closure#0}, mz_transform::TransformError>
             at ./src/expr/src/visit.rs:554:14
  33: <mz_expr::relation::MirRelationExpr as mz_expr::visit::Visit>::try_visit_mut_post::<<mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform::{closure#0}, mz_transform::TransformError>
             at ./src/expr/src/visit.rs:345:9
  34: <mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform
             at ./src/transform/src/fold_constants.rs:47:22
  35: <mz_transform::FuseAndCollapse as mz_transform::Transform>::transform
             at ./src/transform/src/lib.rs:371:13
  36: <mz_transform::Fixpoint as mz_transform::Transform>::transform::{closure#1}
             at ./src/transform/src/lib.rs:270:29
  37: <tracing::span::Span>::in_scope::<<mz_transform::Fixpoint as mz_transform::Transform>::transform::{closure#1}, core::result::Result<(), mz_transform::TransformError>>
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/span.rs:1102:9
  38: <mz_transform::Fixpoint as mz_transform::Transform>::transform
             at ./src/transform/src/lib.rs:267:17
  39: <mz_transform::Optimizer>::transform
             at ./src/transform/src/lib.rs:581:17
  40: <mz_transform::Optimizer>::optimize
             at ./src/transform/src/lib.rs:552:32
  41: <mz_adapter::coord::Coordinator>::sequence_insert::{closure#0}
             at ./src/adapter/src/coord/sequencer.rs:3222:28
  42: <mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}::{closure#0}
             at ./src/adapter/src/coord/sequencer.rs:318:56
  43: <mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}
             at ./src/adapter/src/coord/sequencer.rs:116:5
  44: <mz_adapter::coord::Coordinator>::handle_execute_inner::{closure#0}::{closure#0}
             at ./src/adapter/src/coord/command_handler.rs:469:78
  45: <mz_adapter::coord::Coordinator>::handle_execute_inner::{closure#0}
             at ./src/adapter/src/coord/command_handler.rs:273:5
  46: <mz_adapter::coord::Coordinator>::handle_execute::{closure#0}::{closure#0}
             at ./src/adapter/src/coord/command_handler.rs:270:61
  47: <mz_adapter::coord::Coordinator>::handle_execute::{closure#0}
             at ./src/adapter/src/coord/command_handler.rs:229:5
  48: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_execute::{closure#0}> as core::future::future::Future>::poll
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  49: <mz_adapter::coord::Coordinator>::handle_command::{closure#0}
             at ./src/adapter/src/coord/command_handler.rs:65:21
  50: <mz_adapter::coord::Coordinator>::message_command::{closure#0}::{closure#0}
             at ./src/adapter/src/coord/message_handler.rs:249:33
  51: <mz_adapter::coord::Coordinator>::message_command::{closure#0}
             at ./src/adapter/src/coord/message_handler.rs:246:5
  52: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
             at ./src/adapter/src/coord/message_handler.rs:44:63
  53: <mz_adapter::coord::Coordinator>::serve::{closure#0}
             at ./src/adapter/src/coord.rs:1229:37
  54: <tokio::runtime::park::CachedParkThread>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:63
  55: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}>
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:102:5
  56: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}>
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:68:5
  57: <tokio::runtime::park::CachedParkThread>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:31
  58: <tokio::runtime::context::BlockingRegionGuard>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/context.rs:315:13
  59: <tokio::runtime::handle::Handle>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/handle.rs:264:9
  60: mz_adapter::coord::serve::{closure#0}::{closure#1}
             at ./src/adapter/src/coord.rs:1408:17
```

**Comment by benesch** [comment]
Nice catch! I put up a fix in https://github.com/MaterializeInc/materialize/pull/17803.
