### ISSUE TITLE
thread 'main' panicked at 'must deserialize: Error("missing field `storagectl_addrs`", line: 0, column: 0)', src/stash/src/lib.rs:1070:58

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#17860]
### What version of Materialize are you using?

v0.43.0

### How did you install Materialize?

Docker image

### What is the issue?

In https://buildkite.com/materialize/nightlies/builds/1869 (with my change https://github.com/MaterializeInc/materialize/pull/17849) we create a 0.43.0 Materialize instance, and then upgrade it to 0.45.0. This means the old `storagectl_addr` gets serialized, but when deserializing we expect the new `storagectl_addrs` instead.
@guswynn This seems to come from https://github.com/MaterializeInc/materialize/pull/17483, can we handle this better or should we just ignore this?

### Relevant log output

```source
platform-checks-materialized-1        | CREATE SCHEMA
platform-checks-materialized-1        | environmentd: 2023-02-28T08:19:28.909154Z  INFO environmentd::run: environmentd: booting os.os_type=Ubuntu os.version=22.04 os.bitness=64-bit build.version="0.45.0-dev" build.sha="917bd33e84ed8c935bfc9567d98b120abcb20d88" build.time="2023-02-26T18:34:50Z" cpus.logical=32 cpus.physical=16 cpu0.brand="AMD EPYC 7R32" cpu0.frequency=3300 memory.total=66706653184 memory.used=9971720192 memory.limit=9223372036854771712 swap.total=0 swap.used=0 swap.limit=0 tracing.max_level=info
platform-checks-materialized-1        | thread 'main' panicked at 'must deserialize: Error("missing field `storagectl_addrs`", line: 0, column: 0)', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-051091e74d022d85c-1/materialize/tests/src/stash/src/lib.rs:1070:58
platform-checks-materialized-1        | stack backtrace:
platform-checks-materialized-1        |    0: rust_begin_unwind
platform-checks-materialized-1        |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
platform-checks-materialized-1        |    1: core::panicking::panic_fmt
platform-checks-materialized-1        |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
platform-checks-materialized-1        |    2: core::result::unwrap_failed
platform-checks-materialized-1        |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1791:5
platform-checks-materialized-1        |    3: <core::result::Result<mz_adapter::catalog::storage::ClusterReplicaValue, serde_json::error::Error>>::expect
platform-checks-materialized-1        |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1070:23
platform-checks-materialized-1        |    4: mz_stash::consolidate_updates_kv::<mz_adapter::catalog::storage::ClusterReplicaKey, mz_adapter::catalog::storage::ClusterReplicaValue, alloc::vec::Vec<((serde_json::value::Value, serde_json::value::Value), i64, i64)>>::{closure#0}
platform-checks-materialized-1        |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-051091e74d022d85c-1/materialize/tests/src/stash/src/lib.rs:1070:28
platform-checks-materialized-1        |    5: core::iter::adapters::map::map_fold::<((serde_json::value::Value, serde_json::value::Value), i64, i64), ((mz_adapter::catalog::storage::ClusterReplicaKey, mz_adapter::catalog::storage::ClusterReplicaValue), i64, i64), (), mz_stash::consolidate_updates_kv<mz_adapter::catalog::storage::ClusterReplicaKey, mz_adapter::catalog::storage::ClusterReplicaValue, alloc::vec::Vec<((serde_json::value::Value, serde_json::value::Value), i64, i64)>>::{closure#0}, core::iter::traits::iterator::Iterator::for_each::call<((mz_adapter::catalog::storage::ClusterReplicaKey, mz_adapter::catalog::storage::ClusterReplicaValue), i64, i64), <alloc::vec::Vec<((mz_adapter::catalog::storage::ClusterReplicaKey, mz_adapter::catalog::storage::ClusterReplicaValue), i64, i64)>>::extend_trusted<core::iter::adapters::map::Map<core::iter::adapters::map::Map<alloc::vec::into_iter::IntoIter<((alloc::vec::Vec<u8>, alloc::vec::Vec<u8>), i64, i64)>, mz_stash::consolidate_updates<alloc::vec::Vec<((serde_json::value::Value, serde_json::value::Value), i64, i64)>>::{closure#1}>, mz_stash::consolidate_updates_kv<mz_adapter::catalog::storage::ClusterReplicaKey, mz_adapter::catalog::storage::ClusterReplicaValue, alloc::vec::Vec<((serde_json::value::Value, serde_json::value::Value), i64, i64)>>::{closure#0}>>::{closure#0}>::{closure#0}>::{closure#0}
platform-checks-materialized-1        |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/iter/adapters/map.rs:84:28
platform-checks-materialized-1        |    6: core::iter::adapters::map::map_fold::<((alloc::vec::Vec<u8>, alloc::vec::Vec<u8>), i64, i64), ((serde_json::value::Value, serde_json::value::Value), i64, i64), (), mz_stash::consolidate_updates<alloc::vec::Vec<((serde_json::value::Value, serde_json::value::Value), i64, i64)>>::{closure#1}, core::iter::adapters::map::map_fold<((serde_json::value::Value, serde_json::value::Value), i64, i64), ((mz_adapter::catalog::storage::ClusterReplicaKey, mz_adapter::catalog::storage::ClusterReplicaValue), i64, i64), (), mz_stash::consolidate_updates_kv<mz_adapter::catalog::storage::ClusterReplicaKey, mz_adapter::catalog::storage::ClusterReplicaValue, alloc::vec::Vec<((serde_json::value::Value, serde_json::value::Value), i64, i64)>>::{closure#0}, core::iter::traits::iterator::Iterator::for_each::call<((mz_adapter::catalog::storage::ClusterReplicaKey, mz_adapter::catalog::storage::ClusterReplicaValue), i64, i64), <alloc::vec::Vec<((mz_adapter::catalog::storage::ClusterReplicaKey, mz_adapter::catalog::storage::ClusterReplicaValue), i64, i64)>>::extend_trusted<core::iter::adapters::map::Map<core::iter::adapters::map::Map<alloc::vec::into_iter::IntoIter<((alloc::vec::Vec<u8>, alloc::vec::Vec<u8>), i64, i64)>, mz_stash::consolidate_updates<alloc::vec::Vec<((serde_json::value::Value, serde_json::value::Value), i64, i64)>>::{closure#1}>, mz_stash::consolidate_updates_kv<mz_adapter::catalog::storage::ClusterReplicaKey, mz_adapter::catalog::storage::ClusterReplicaValue, alloc::vec::Vec<((serde_json::value::Value, serde_json::value::Value), i64, i64)>>::{closure#0}>>::{closure#0}>::{closure#0}>::{closure#0}>::{closure#0}
platform-checks-materialized-1        |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/iter/adapters/map.rs:84:21
platform-checks-materialized-1        |    7: <alloc::vec::into_iter::IntoIter<((alloc::vec::Vec<u8>, alloc::vec::Vec<u8>), i64, i64)> as core::iter::traits::iterator::Iterator>::fold::<(), core::iter::adapters::map::map_fold<((alloc::vec::Vec<u8>, alloc::vec::Vec<u8>), i64, i64), ((serde_json::value::Value, serde_json::value::Value), i64, i64), (), mz_stash::consolidate_updates<alloc::vec::Vec<((serde_json::value::Value, serde_json::value::Value), i64, i64)>>::{closure#1}, core::iter::adapters::map::map_fold<((serde_json::value::Value, serde_json::value::Value), i64, i64), ((mz_adapter::catalog::storage::ClusterReplicaKey, mz_adapter::catalog::storage::ClusterReplicaValue), i64, i64), (), mz_stash::consolidate_updates_kv<mz_adapter::catalog::storage::ClusterReplicaKey, mz_adapter::catalog::storage::ClusterReplicaValue, alloc::vec::Vec<((serde_json::value::Value, serde_json::value::Value), i64, i64)>>::{closure#0}, core::iter::traits::iterator::Iterator::for_each::call<((mz_adapter::catalog::storage::ClusterReplicaKey, mz_adapter::catalog::storage::ClusterReplicaValue), i64, i64), <alloc::vec::Vec<((mz_adapter::catalog::storage::ClusterReplicaKey, mz_adapter::catalog::storage::ClusterReplicaValue), i64, i64)>>::extend_trusted<core::iter::adapters::map::Map<core::iter::adapters::map::Map<alloc::vec::into_iter::IntoIter<((alloc::vec::Vec<u8>, alloc::vec::Vec<u8>), i64, i64)>, mz_stash::consolidate_updates<alloc::vec::Vec<((serde_json::value::Value, serde_json::value::Value), i64, i64)>>::{closure#1}>, mz_stash::consolidate_updates_kv<mz_adapter::catalog::storage::ClusterReplicaKey, mz_adapter::catalog::storage::ClusterReplicaValue, alloc::vec::Vec<((serde_json::value::Value, serde_json::value::Value), i64, i64)>>::{closure#0}>>::{closure#0}>::{closure#0}>::{closure#0}>::{closure#0}>
platform-checks-materialized-1        |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/iter/traits/iterator.rs:2414:21
platform-checks-materialized-1        |    8: <core::iter::adapters::map::Map<alloc::vec::into_iter::IntoIter<((alloc::vec::Vec<u8>, alloc::vec::Vec<u8>), i64, i64)>, mz_stash::consolidate_updates<alloc::vec::Vec<((serde_json::value::Value, serde_json::value::Value), i64, i64)>>::{closure#1}> as core::iter::traits::iterator::Iterator>::fold::<(), core::iter::adapters::map::map_fold<((serde_json::value::Value, serde_json::value::Value), i64, i64), ((mz_adapter::catalog::storage::ClusterReplicaKey, mz_adapter::catalog::storage::ClusterReplicaValue), i64, i64), (), mz_stash::consolidate_updates_kv<mz_adapter::catalog::storage::ClusterReplicaKey, mz_adapter::catalog::storage::ClusterReplicaValue, alloc::vec::Vec<((serde_json::value::Value, serde_json::value::Value), i64, i64)>>::{closure#0}, core::iter::traits::iterator::Iterator::for_each::call<((mz_adapter::catalog::storage::ClusterReplicaKey, mz_adapter::catalog::storage::ClusterReplicaValue), i64, i64), <alloc::vec::Vec<((mz_adapter::catalog::storage::ClusterReplicaKey, mz_adapter::catalog::storage::ClusterReplicaValue), i64, i64)>>::extend_trusted<core::iter::adapters::map::Map<core::iter::adapters::map::Map<alloc::vec::into_iter::IntoIter<((alloc::vec::Vec<u8>, alloc::vec::Vec<u8>), i64, i64)>, mz_stash::consolidate_updates<alloc::vec::Vec<((serde_json::value::Value, serde_json::value::Value), i64, i64)>>::{closure#1}>, mz_stash::consolidate_updates_kv<mz_adapter::catalog::storage::ClusterReplicaKey, mz_adapter::catalog::storage::ClusterReplicaValue, alloc::vec::Vec<((serde_json::value::Value, serde_json::value::Value), i64, i64)>>::{closure#0}>>::{closure#0}>::{closure#0}>::{closure#0}>
```

**Comment by philip-stoev** [comment]
This is because no migration was implemented that rewrites STORAGECTL ADDRESS to STORAGECTL ADDRESSES. I now recall this was because at PR time this was judged to not be an external-facing feature so it was not expected that production Mz instances will ever have it and need to migrate from one form to the other. I should have asked for a migration to be implemented back then, but as the upgrade test was failing at that time due to the Expected ADDRESS, found ADDRESSES syntax error, it never got to the panic itself.

**Comment by guswynn** [comment]
We aren't ever going to see this in an upgrade in production right?

**Comment by mjibson** [comment]
Errrp! Wrong issue in my PR, apologies.
