### ISSUE TITLE
panic: cannot serve requested as_of Antichain in `checks-parallel-restart-entire-mz`

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#17861]
### What version of Materialize are you using?

v0.45.0-dev (1b5b7fe6c)

### How did you install Materialize?

Docker image

### What is the issue?

All previous tickets about that panic are now closed and yet it happened again in Nightly:

https://buildkite.com/materialize/nightlies/builds/1868#01869571-bc21-40a1-8717-dca1fff4eba6

ci-regexp: cannot serve requested as_of Antichain

### Relevant log output

```source
platform-checks-materialized-1  | thread 'timely:work-2' panicked at 'u155: s5041c90e-40f2-4b96-b092-2adb83ad9cb4 cannot serve requested as_of Antichain { elements: [1677544799110] }: Since(Antichain { elements: [1677544934999] })', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0f400d92da09baa09-1/materialize/tests/src/persist-client/src/operators/shard_source.rs:177:24

platform-checks-materialized-1  |    0: rust_begin_unwind
platform-checks-materialized-1  |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
platform-checks-materialized-1  |    1: core::panicking::panic_fmt
platform-checks-materialized-1  |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
platform-checks-materialized-1  |    2: mz_persist_client::operators::shard_source::shard_source_descs::<mz_storage_client::types::sources::SourceData, (), i64, timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>::{closure#1}::{closure#1}
platform-checks-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/async-stream-0.3.3/src/lib.rs:237:9
platform-checks-materialized-1  |    3: <core::result::Result<mz_persist_client::read::Subscribe<mz_storage_client::types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>, mz_persist_client::internal::state::Since<mz_repr::timestamp::Timestamp>>>::unwrap_or_else::<mz_persist_client::operators::shard_source::shard_source_descs<mz_storage_client::types::sources::SourceData, (), i64, timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>::{closure#1}::{closure#1}>
platform-checks-materialized-1  |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1504:23
platform-checks-materialized-1  |    4: mz_persist_client::operators::shard_source::shard_source_descs::<mz_storage_client::types::sources::SourceData, (), i64, timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>::{closure#1}
platform-checks-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/async-stream-0.3.3/src/lib.rs:237:9
platform-checks-materialized-1  |    5: <async_stream::async_stream::AsyncStream<core::result::Result<mz_persist_client::read::ListenEvent<mz_repr::timestamp::Timestamp, mz_persist_client::fetch::LeasedBatchPart<mz_repr::timestamp::Timestamp>>, mz_persist::location::ExternalError>, mz_persist_client::operators::shard_source::shard_source_descs<mz_storage_client::types::sources::SourceData, (), i64, timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>::{closure#1}> as futures_core::stream::Stream>::poll_next
platform-checks-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/async-stream-0.3.3/src/async_stream.rs:53:17
platform-checks-materialized-1  |    6: <core::pin::Pin<alloc::boxed::Box<async_stream::async_stream::AsyncStream<core::result::Result<mz_persist_client::read::ListenEvent<mz_repr::timestamp::Timestamp, mz_persist_client::fetch::LeasedBatchPart<mz_repr::timestamp::Timestamp>>, mz_persist::location::ExternalError>, mz_persist_client::operators::shard_source::shard_source_descs<mz_storage_client::types::sources::SourceData, (), i64, timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>::{closure#1}>>> as futures_core::stream::Stream>::poll_next
platform-checks-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.25/src/stream.rs:120:9
platform-checks-materialized-1  |    7: <core::pin::Pin<alloc::boxed::Box<async_stream::async_stream::AsyncStream<core::result::Result<mz_persist_client::read::ListenEvent<mz_repr::timestamp::Timestamp, mz_persist_client::fetch::LeasedBatchPart<mz_repr::timestamp::Timestamp>>, mz_persist::location::ExternalError>, mz_persist_client::operators::shard_source::shard_source_descs<mz_storage_client::types::sources::SourceData, (), i64, timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>::{closure#1}>>> as futures_util::stream::stream::StreamExt>::poll_next_unpin
platform-checks-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/stream/stream/mod.rs:1626:9
platform-checks-materialized-1  |    8: <futures_util::stream::stream::next::Next<core::pin::Pin<alloc::boxed::Box<async_stream::async_stream::AsyncStream<core::result::Result<mz_persist_client::read::ListenEvent<mz_repr::timestamp::Timestamp, mz_persist_client::fetch::LeasedBatchPart<mz_repr::timestamp::Timestamp>>, mz_persist::location::ExternalError>, mz_persist_client::operators::shard_source::shard_source_descs<mz_storage_client::types::sources::SourceData, (), i64, timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>::{closure#1}>>>> as core::future::future::Future>::poll
platform-checks-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/stream/stream/next.rs:32:9
platform-checks-materialized-1  |    9: mz_persist_client::operators::shard_source::shard_source_descs::<mz_storage_client::types::sources::SourceData, (), i64, timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>::{closure#0}::{closure#0}
platform-checks-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0f400d92da09baa09-1/materialize/tests/src/persist-client/src/operators/shard_source.rs:306:43
platform-checks-materialized-1  |   10: <core::pin::Pin<alloc::boxed::Box<mz_persist_client::operators::shard_source::shard_source_descs<mz_storage_client::types::sources::SourceData, (), i64, timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>::{closure#0}::{closure#0}>> as core::future::future::Future>::poll
platform-checks-materialized-1  |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/future/future.rs:124:9
platform-checks-materialized-1  |   11: <mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>>::build::<mz_persist_client::operators::shard_source::shard_source_descs<mz_storage_client::types::sources::SourceData, (), i64, timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>::{closure#0}, mz_persist_client::operators::shard_source::shard_source_descs<mz_storage_client::types::sources::SourceData, (), i64, timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>::{closure#0}::{closure#0}>::{closure#0}::{closure#0}
platform-checks-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0f400d92da09baa09-1/materialize/tests/src/timely-util/src/builder_async.rs:326:28
platform-checks-materialized-1  |   12: <timely::dataflow::operators::generic::builder_rc::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>>::build_reschedule::<<mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>>::build<mz_persist_client::operators::shard_source::shard_source_descs<mz_storage_client::types::sources::SourceData, (), i64, timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>::{closure#0}, mz_persist_client::operators::shard_source::shard_source_descs<mz_storage_client::types::sources::SourceData, (), i64, timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>::{closure#0}::{closure#0}>::{closure#0}, <mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>>::build<mz_persist_client::operators::shard_source::shard_source_descs<mz_storage_client::types::sources::SourceData, (), i64, timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>::{closure#0}, mz_persist_client::operators::shard_source::shard_source_descs<mz_storage_client::types::sources::SourceData, (), i64, timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>::{closure#0}::{closure#0}>::{closure#0}::{closure#0}>::{closure#0}
platform-checks-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/5b808ff/timely/src/dataflow/operators/generic/builder_rc.rs:172:26
platform-checks-materialized-1  |   13: <timely::dataflow::operators::generic::builder_raw::OperatorCore<mz_repr::timestamp::Timestamp, <timely::dataflow::operators::generic::builder_rc::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>>::build_reschedule<<mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>>::build<mz_persist_client::operators::shard_source::shard_source_descs<mz_storage_client::types::sources::SourceData, (), i64, timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>::{closure#0}, mz_persist_client::operators::shard_source::shard_source_descs<mz_storage_client::types::sources::SourceData, (), i64, timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>::{closure#0}::{closure#0}>::{closure#0}, <mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>>::build<mz_persist_client::operators::shard_source::shard_source_descs<mz_storage_client::types::sources::SourceData, (), i64, timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>::{closure#0}, mz_persist_client::operators::shard_source::shard_source_descs<mz_storage_client::types::sources::SourceData, (), i64, timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>::{closure#0}::{closure#0}>::{closure#0}::{closure#0}>::{closure#0}> as timely::scheduling::Schedule>::schedule
platform-checks-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/5b808ff/timely/src/dataflow/operators/generic/builder_raw.rs:204:9
platform-checks-materialized-1  |   14: <timely::progress::subgraph::PerOperatorState<mz_repr::timestamp::Timestamp>>::schedule
platform-checks-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/5b808ff/timely/src/progress/subgraph.rs:699:30
platform-checks-materialized-1  |   15: <timely::progress::subgraph::Subgraph<mz_repr::timestamp::Timestamp, mz_repr::timestamp::Timestamp>>::activate_child
platform-checks-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/5b808ff/timely/src/progress/subgraph.rs:346:26
platform-checks-materialized-1  |   16: <timely::progress::subgraph::Subgraph<mz_repr::timestamp::Timestamp, mz_repr::timestamp::Timestamp> as timely::scheduling::Schedule>::schedule
platform-checks-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/5b808ff/timely/src/progress/subgraph.rs:312:17
platform-checks-materialized-1  |   17: <timely::progress::subgraph::PerOperatorState<mz_repr::timestamp::Timestamp>>::schedule
platform-checks-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/5b808ff/timely/src/progress/subgraph.rs:699:30
platform-checks-materialized-1  |   18: <timely::progress::subgraph::Subgraph<(), mz_repr::timestamp::Timestamp>>::activate_child
platform-checks-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/5b808ff/timely/src/progress/subgraph.rs:346:26
platform-checks-materialized-1  |   19: <timely::progress::subgraph::Subgraph<(), mz_repr::timestamp::Timestamp> as timely::scheduling::Schedule>::schedule
platform-checks-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/5b808ff/timely/src/progress/subgraph.rs:312:17
platform-checks-materialized-1  |   20: <timely::worker::Wrapper>::step::{closure#0}
platform-checks-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/5b808ff/timely/src/worker.rs:754:57
platform-checks-materialized-1  |   21: <core::option::Option<&mut alloc::boxed::Box<dyn timely::scheduling::Schedule>>>::map::<bool, <timely::worker::Wrapper>::step::{closure#0}>
platform-checks-materialized-1  |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/option.rs:925:29
platform-checks-materialized-1  |   22: <timely::worker::Wrapper>::step
platform-checks-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/5b808ff/timely/src/worker.rs:754:26
platform-checks-materialized-1  |   23: <timely::worker::Worker<timely_communication::allocator::generic::Generic>>::step_or_park
platform-checks-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/5b808ff/timely/src/worker.rs:396:38
platform-checks-materialized-1  |   24: <mz_storage::storage_state::Worker<timely_communication::allocator::generic::Generic>>::run_client
platform-checks-materialized-1  |   25: <mz_storage::storage_state::Worker<timely_communication::allocator::generic::Generic>>::run
platform-checks-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0f400d92da09baa09-1/materialize/tests/src/storage/src/storage_state.rs:394:21
platform-checks-materialized-1  |   26: <mz_storage::server::Config as mz_cluster::types::AsRunnableWorker<mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>>::build_and_run::<timely_communication::allocator::generic::Generic>
platform-checks-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0f400d92da09baa09-1/materialize/tests/src/storage/src/server.rs:105:9
platform-checks-materialized-1  |   27: <mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse, std::thread::Thread>, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>, mz_storage::server::Config, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>>::build_timely::{closure#0}::{closure#1}
platform-checks-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0f400d92da09baa09-1/materialize/tests/src/cluster/src/server.rs:178:13
platform-checks-materialized-1  |   28: timely::execute::execute_from::<timely_communication::allocator::generic::GenericBuilder, (), <mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse, std::thread::Thread>, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>, mz_storage::server::Config, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>>::build_timely::{closure#0}::{closure#1}>::{closure#0}
platform-checks-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/5b808ff/timely/src/execute.rs:388:22
platform-checks-materialized-1  |   29: timely_communication::initialize::initialize_from::<timely_communication::allocator::generic::GenericBuilder, (), timely::execute::execute_from<timely_communication::allocator::generic::GenericBuilder, (), <mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse, std::thread::Thread>, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>, mz_storage::server::Config, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>>::build_timely::{closure#0}::{closure#1}>::{closure#0}>::{closure#0}
platform-checks-materialized-1  |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/5b808ff/communication/src/initialize.rs:316:33
platform-checks-materialized-1  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by philip-stoev** [comment]
Extra logging around the materialized view in question:

```
platform-checks-materialized-1  | environmentd: 2023-02-28T00:39:58.741554Z  INFO mz_storage_client::controller: prepare_export: sink acquired read holds sink_id="u156" from_id="u155" acquired_since=Antichain { elements: [0] }
platform-checks-materialized-1  | environmentd: 2023-02-28T00:39:59.845347Z  INFO mz_storage_client::controller: create_exports: creating sink sink_id="u156" from_id="u155" acquired_since=Antichain { elements: [0] } initial_as_of=SinkAsOf { frontier: Antichain { elements: [1677544799110] }, strict: false }
```
