### ISSUE TITLE
regression:  thread 'coordinator' panicked at 'update ChangeBatch ... would lead to negative read capabilities

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#17879]
### What version of Materialize are you using?

environmentd v0.45.0-dev (345d5ca4a)

### How did you install Materialize?

Docker image

### What is the issue?

Upgrading from `v0.42.4` caused v0.45.0 to panic as follows:

```
platform-checks-materialized-1  | thread 'coordinator' panicked at 'update ChangeBatch { updates: [(1677655752000, -1), (1677655782000, 1)], clean: 2 } for collection u242 would lead to negative read capabilities, read capabilities before applying: MutableAntichain { updates: ChangeBatch { updates: [(1677655755000, 1), (1677655803000, 1), (1677655804000, 3), (1677655803000, -1), (1677655804000, 1), (1677655804000, -1), (1677655805000, 1), (1677655804000, -1), (1677655805000, 1), (1677655804000, -1), (1677655805000, 1), (1677655804000, -1), (1677655805000, 1), (1677655805000, -1), (1677655806000, 1), (1677655805000, -1), (1677655806000, 1), (1677655805000, -1), (1677655806000, 1), (1677655805000, -1), (1677655806000, 1), (1677655806000, -1), (1677655807000, 1), (1677655806000, -1), (1677655807000, 1), (1677655806000, -1), (1677655807000, 1), (1677655806000, -1), (1677655807000, 1)], clean: 3 }, frontier: [1677655755000], changes: ChangeBatch { updates: [], clean: 0 } }', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07807469c10a60596-1/materialize/tests/src/storage-client/src/controller.rs:1923:21
```

to reproduce:

```
cd test/platform-checks
./mzcompose run default --scenario=UpgradeEntireMzPreviousVersion
```

ci-regexp: would lead to negative read capabilities

### Relevant log output

```source
platform-checks-materialized-1  |    0: rust_begin_unwind
platform-checks-materialized-1  |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
platform-checks-materialized-1  |    1: core::panicking::panic_fmt
platform-checks-materialized-1  |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
platform-checks-materialized-1  |    2: <mz_storage_client::controller::Controller<mz_repr::timestamp::Timestamp> as mz_storage_client::controller::StorageController>::update_read_capabilities
platform-checks-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07807469c10a60596-1/materialize/tests/src/storage-client/src/controller.rs:1923:21
platform-checks-materialized-1  |    3: <mz_compute_client::controller::instance::ActiveInstance<mz_repr::timestamp::Timestamp>>::update_write_frontiers
platform-checks-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07807469c10a60596-1/materialize/tests/src/compute-client/src/controller/instance.rs:904:13
platform-checks-materialized-1  |    4: <mz_compute_client::controller::instance::ActiveInstance<mz_repr::timestamp::Timestamp>>::handle_frontier_uppers
platform-checks-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07807469c10a60596-1/materialize/tests/src/compute-client/src/controller/instance.rs:1118:9
platform-checks-materialized-1  |    5: <mz_compute_client::controller::instance::ActiveInstance<mz_repr::timestamp::Timestamp>>::handle_response
platform-checks-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07807469c10a60596-1/materialize/tests/src/compute-client/src/controller/instance.rs:1053:17
platform-checks-materialized-1  |    6: <mz_compute_client::controller::ActiveComputeController<mz_repr::timestamp::Timestamp>>::process
platform-checks-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07807469c10a60596-1/materialize/tests/src/compute-client/src/controller.rs:591:24
platform-checks-materialized-1  |    7: <mz_controller::Controller>::process::{closure#0}
platform-checks-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07807469c10a60596-1/materialize/tests/src/controller/src/lib.rs:298:32
platform-checks-materialized-1  |    8: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
platform-checks-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07807469c10a60596-1/materialize/tests/src/adapter/src/coord/message_handler.rs:49:21
platform-checks-materialized-1  |    9: <mz_adapter::coord::Coordinator>::serve::{closure#0}
platform-checks-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07807469c10a60596-1/materialize/tests/src/adapter/src/coord.rs:1229:37
platform-checks-materialized-1  |   10: <tokio::runtime::park::CachedParkThread>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}
platform-checks-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:63
platform-checks-materialized-1  |   11: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}>
platform-checks-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:102:5
platform-checks-materialized-1  |   12: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}>
platform-checks-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:68:5
platform-checks-materialized-1  |   13: <tokio::runtime::park::CachedParkThread>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
platform-checks-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:31
platform-checks-materialized-1  |   14: <tokio::runtime::context::BlockingRegionGuard>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
platform-checks-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/context.rs:315:13
platform-checks-materialized-1  |   15: <tokio::runtime::handle::Handle>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
platform-checks-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/handle.rs:264:9
platform-checks-materialized-1  |   16: mz_adapter::coord::serve::{closure#0}::{closure#1}
platform-checks-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07807469c10a60596-1/materialize/tests/src/adapter/src/coord.rs:1408:17
platform-checks-materialized-1  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by teskje** [comment]
Looks like maybe a compute bug. I'm taking a look.

**Comment by teskje** [comment]
@philip-stoev is this a flaky repro? I tried running it two times, and both times it instead crashed with:

```
platform-checks-materialized-1  | environmentd: cannot migrate from catalog version 0.42.4 toversion 0.45.0-dev (earlier versions might still work): Expected identifier, found operator "-"
```

Which might be expected considering the version jump.

**Comment by philip-stoev** [comment]
Yes, the `cannot migrate from catalog version ` error is expected . This ticket is about the `would lead to negative read capabilities` panic .

The panic happened twice in a row in CI. Let me see how I can reproduce it locally.

**Comment by philip-stoev** [comment]
@teskje To reproduce, you can apply the following patch:

```
diff --git a/misc/python/materialize/checks/all_checks.py b/misc/python/materialize/checks/all_checks.py
index 58213a824..6030b469b 100644
--- a/misc/python/materialize/checks/all_checks.py
+++ b/misc/python/materialize/checks/all_checks.py
@@ -25,7 +25,6 @@ from materialize.checks.drop_table import *  # noqa: F401 F403
 from materialize.checks.error import *  # noqa: F401 F403
 from materialize.checks.float_types import *  # noqa: F401 F403
 from materialize.checks.having import *  # noqa: F401 F403
-from materialize.checks.identifiers import *  # noqa: F401 F403
 from materialize.checks.insert_select import *  # noqa: F401 F403
 from materialize.checks.join_implementations import *  # noqa: F401 F403
 from materialize.checks.join_types import *  # noqa: F401 F403
@@ -45,7 +44,6 @@ from materialize.checks.rename_source import *  # noqa: F401 F403
 from materialize.checks.rename_table import *  # noqa: F401 F403
 from materialize.checks.rename_view import *  # noqa: F401 F403
 from materialize.checks.replica import *  # noqa: F401 F403
-from materialize.checks.roles import *  # noqa: F401 F403
 from materialize.checks.rollback import *  # noqa: F401 F403
 from materialize.checks.sink import *  # noqa: F401 F403
 from materialize.checks.source_errors import *  # noqa: F401 F403
```
to skip various parts of the test that are problematic. Then, the test will hopefully fail with the panic this ticket is about.

**Comment by teskje** [comment]
Thanks, this works!

**Comment by teskje** [comment]
I've come to the conclusion that this is in fact a storage issue. Here is what I've found out so far:

* The panic occurs when the compute controller updates the frontier for the MV `postgres_mz_now_view`. This results in a read capability update for that MV's dependency `postgres_mz_now_table`, which is a subsource of a postgres source. Updating the read capability of `postgres_mz_now_table` leads to a read capability update of *that* collection's dependency `postgres_mz_now_source_progress`, which is when the assert triggers.
* The compute controller seems to behave correctly here. It never tries to retract a read capability from a storage dependency it hasn't inserted previously, as evidenced by the fact that the panic doesn't occur on `postgres_mz_now_table` but on its dependency. It seems like the storage controller internally gets confused about keeping capabilities between dependencies in sync.

To verify the above suspicious, I made this patch:
```diff
diff --git a/src/storage-client/src/controller.rs b/src/storage-client/src/controller.rs
index 6d012201bf..c56bb4f2fd 100644
--- a/src/storage-client/src/controller.rs
+++ b/src/storage-client/src/controller.rs
@@ -1915,6 +1915,21 @@ where
         // Location to record consequences that we need to act on.
         let mut storage_net = BTreeMap::new();

+        let frontiers: BTreeMap<_, _> = self
+            .collections()
+            .map(|(id, state)| (id, state.read_capabilities.frontier()))
+            .collect();
+        for (id, state) in self.collections() {
+            let frontier = frontiers[id];
+            for dep in &state.storage_dependencies {
+                let dep_frontier = frontiers[dep];
+                assert!(
+                    PartialOrder::less_equal(&dep_frontier, &frontier),
+                    "since of dependency {dep} is beyond since of dependant {id}"
+                );
+            }
+        }
+
         // Repeatedly extract the maximum id, and updates for it.
         while let Some(key) = updates.keys().rev().next().cloned() {
             let mut update = updates.remove(&key).unwrap();
```

... which asserts in the storage controller that read frontiers of dependencies are always less than or equal to the read frontiers of the things depending on them. If I run the above repro with this patch applied, it panics already during coordinator bootstrap:

```
platform-checks-materialized-1  | thread 'coordinator' panicked at 'since of dependency u209 is beyond since of dependant u73', /Users/jan/devel/materialize/src/storage-client/src/controller.rs:1931:17
platform-checks-materialized-1  | stack backtrace:
platform-checks-materialized-1  |    0: rust_begin_unwind
platform-checks-materialized-1  |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
platform-checks-materialized-1  |    1: core::panicking::panic_fmt
platform-checks-materialized-1  |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
platform-checks-materialized-1  |    2: <mz_storage_client::controller::Controller<mz_repr::timestamp::Timestamp> as mz_storage_client::controller::StorageController>::update_read_capabilities
platform-checks-materialized-1  |              at ./Users/jan/devel/materialize/src/storage-client/src/controller.rs:1931:17
platform-checks-materialized-1  |    3: <mz_storage_client::controller::Controller<mz_repr::timestamp::Timestamp>>::install_read_capabilities
platform-checks-materialized-1  |              at ./Users/jan/devel/materialize/src/storage-client/src/controller.rs:2264:9
platform-checks-materialized-1  |    4: <mz_storage_client::controller::Controller<mz_repr::timestamp::Timestamp> as mz_storage_client::controller::StorageController>::create_collections::{closure#0}::{closure#0}
platform-checks-materialized-1  |              at ./Users/jan/devel/materialize/src/storage-client/src/controller.rs:1375:25
platform-checks-materialized-1  |    5: <mz_storage_client::controller::Controller<mz_repr::timestamp::Timestamp> as mz_storage_client::controller::StorageController>::create_collections::{closure#0}
platform-checks-materialized-1  |              at ./Users/jan/devel/materialize/src/storage-client/src/controller.rs:1113:5
platform-checks-materialized-1  |    6: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(), mz_storage_client::controller::StorageError>>>> as core::future::future::Future>::poll
platform-checks-materialized-1  |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/future/future.rs:124:9
platform-checks-materialized-1  |    7: <mz_adapter::coord::Coordinator>::bootstrap::{closure#0}::{closure#0}
platform-checks-materialized-1  |              at ./Users/jan/devel/materialize/src/adapter/src/coord.rs:815:29
platform-checks-materialized-1  |    8: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::bootstrap::{closure#0}::{closure#0}> as core::future::future::Future>::poll
platform-checks-materialized-1  |              at ./Users/jan/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
platform-checks-materialized-1  |    9: <mz_adapter::coord::Coordinator>::bootstrap::{closure#0}
platform-checks-materialized-1  |              at ./Users/jan/devel/materialize/src/adapter/src/coord.rs:523:5
platform-checks-materialized-1  |   10: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::bootstrap::{closure#0}> as core::future::future::Future>::poll
platform-checks-materialized-1  |              at ./Users/jan/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
platform-checks-materialized-1  |   11: mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#1}
platform-checks-materialized-1  |              at ./Users/jan/devel/materialize/src/adapter/src/coord.rs:1395:21
```
