### ISSUE TITLE
[SQLsmith] thread 'timely:work-0' panicked at 'can not convert float seconds to Duration: value is negative', /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/time.rs:742:23

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#17984]
### What version of Materialize are you using?

v0.46.0-dev (659bcc95fb94f8d18cd42c6fabbb81bba90d0b02)

### How did you install Materialize?

Docker image

### What is the issue?

This crashed in clusterd and thus apparently the query didn't return an error, so I'm still hunting for the query. Is it possible to get the SQL query from a clusterd core dump?
Clusterd coredump backtrace: https://gist.github.com/def-/c06fad87b31fb588b00c306138e23230

### Relevant log output

```source
Error logs:
thread 'timely:work-0' panicked at 'can not convert float seconds to Duration: value is negative', /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/time.rs:742:23
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/panicking.rs:147:5
   3: core::time::Duration::from_secs_f64
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/time.rs:742:23
   4: mz_expr::scalar::func::impls::float64::sleep
             at ./src/expr/src/scalar/func/impls/float64.rs:430:24
   5: <mz_expr::scalar::func::impls::float64::Sleep as mz_expr::scalar::func::EagerUnaryFunc>::call
             at ./src/expr/src/scalar/func/macros.rs:105:21
   6: <T as mz_expr::scalar::func::LazyUnaryFunc>::eval
             at ./src/expr/src/scalar/func.rs:3750:26
   7: mz_expr::scalar::func::UnaryFunc::eval
             at ./src/expr/src/scalar/func/macros.rs:289:41
   8: mz_expr::scalar::MirScalarExpr::eval
             at ./src/expr/src/scalar/mod.rs:1749:56
   9: mz_expr::scalar::func::BinaryFunc::eval
             at ./src/expr/src/scalar/func.rs:2124:34
  10: mz_expr::scalar::MirScalarExpr::eval
             at ./src/expr/src/scalar/mod.rs:1751:17
  11: mz_expr::linear::plan::SafeMfpPlan::evaluate_inner
             at ./src/expr/src/linear.rs:1532:20
  12: mz_expr::linear::plan::MfpPlan::evaluate
             at ./src/expr/src/linear.rs:1775:19
  13: mz_compute::render::context::CollectionBundle<S,mz_repr::row::Row,T>::as_collection_core::{{closure}}::{{closure}}
             at ./src/compute/src/render/context.rs:647:17
  14: mz_compute::render::context::CollectionBundle<S,mz_repr::row::Row,T>::flat_map::{{closure}}
             at ./src/compute/src/render/context.rs:508:52
  15: <timely::dataflow::stream::StreamCore<S,alloc::vec::Vec<D>> as timely::dataflow::operators::map::Map<S,D>>::flat_map::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/operators/map.rs:79:83
  16: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/ops/function.rs:310:13
  17: core::option::Option<T>::map
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/option.rs:972:29
  18: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/iter/adapters/map.rs:103:9
  19: <core::iter::adapters::fuse::Fuse<I> as core::iter::adapters::fuse::FuseImpl<I>>::next
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/iter/adapters/fuse.rs:337:9
  20: <core::iter::adapters::fuse::Fuse<I> as core::iter::traits::iterator::Iterator>::next
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/iter/adapters/fuse.rs:43:9
  21: <core::iter::adapters::flatten::FlattenCompat<I,U> as core::iter::traits::iterator::Iterator>::next
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/iter/adapters/flatten.rs:474:29
  22: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/iter/adapters/flatten.rs:51:9
  23: timely::dataflow::channels::pushers::buffer::Session<T,alloc::vec::Vec<D>,P>::give_iterator
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/channels/pushers/buffer.rs:132:21
  24: <timely::dataflow::stream::StreamCore<S,alloc::vec::Vec<D>> as timely::dataflow::operators::map::Map<S,D>>::flat_map::{{closure}}::{{closure}}::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/operators/map.rs:79:17
  25: timely::dataflow::operators::generic::handles::InputHandleCore<T,D,P>::for_each
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/operators/generic/handles.rs:94:13
  26: <timely::dataflow::stream::StreamCore<S,alloc::vec::Vec<D>> as timely::dataflow::operators::map::Map<S,D>>::flat_map::{{closure}}::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/operators/map.rs:77:13
  27: <timely::dataflow::stream::StreamCore<G,D1> as timely::dataflow::operators::generic::operator::Operator<G,D1>>::unary::{{closure}}::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/operators/generic/operator.rs:401:17
  28: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/operators/generic/builder_rc.rs:133:31
  29: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/operators/generic/builder_rc.rs:172:26
  30: <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/operators/generic/builder_raw.rs:204:9
  31: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:699:30
  32: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:346:26
  33: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:312:17
  34: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:699:30
  35: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:346:26
  36: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:312:17
  37: timely::worker::Wrapper::step::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/worker.rs:754:57
  38: core::option::Option<T>::map
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/option.rs:972:29
  39: timely::worker::Wrapper::step
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/worker.rs:754:26
  40: timely::worker::Worker<A>::step_or_park
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/worker.rs:396:38
  41: mz_compute::server::Worker<A>::run_client
             at ./src/compute/src/server.rs:347:13
  42: mz_compute::server::Worker<A>::setup_channel_and_run_client
             at ./src/compute/src/server.rs:321:9
  43: mz_compute::server::Worker<A>::run
             at ./src/compute/src/server.rs:181:21
  44: <mz_compute::server::Config as mz_cluster::types::AsRunnableWorker<mz_compute_client::protocol::command::ComputeCommand,mz_compute_client::protocol::response::ComputeResponse>>::build_and_run
             at ./src/compute/src/server.rs:162:9
  45: mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<C,R,<Worker as mz_cluster::types::AsRunnableWorker<C,R>>::Activatable>,C,R>,Worker,C,R>::build_timely::{{closure}}::{{closure}}
             at ./src/cluster/src/server.rs:178:13
  46: timely::execute::execute_from::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/execute.rs:388:22
  47: timely_communication::initialize::initialize_from::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/communication/src/initialize.rs:316:33
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
environmentd: 2023-03-07T15:11:37.238632Z  WARN mz_storage_client::controller::rehydration: storage cluster produced error, reconnecting: status: Unknown, message: "error reading a body from connection: broken pipe", details: [], metadata: MetadataMap { headers: {} }
environmentd: 2023-03-07T15:11:37.272787Z  WARN mz_compute_client::controller::replica: replica task for 1 failed: status: Unknown, message: "error reading a body from connection: broken pipe", details: [], metadata: MetadataMap { headers: {} }
environmentd: 2023-03-07T15:11:37.437713Z ERROR mz_orchestrator_process: cluster-u1-replica-1-0 exited: ExitStatus(unix_wait_status(134)); relaunching in 5s
```

**Comment by antiguru** [comment]
> Is it possible to get the SQL query from a clusterd core dump?
No because `clusterd` never sees the query. It only gets to see the `LIR` plan.

This seems like a very low priority issue to me because `mz_sleep` is not enabled in production. I agree that it should have better error handling!
