### ISSUE TITLE
[SQLsmith] thread 'timely:work-0' panicked at 'internal error: invalid encoded state: couldn't decode batch at key ...: External format error: File out of specification: A parquet file must containt a header and footer with at least 12 bytes

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18008]
### What version of Materialize are you using?

7f9d9fd35ba06950fed48325389faef77c235d4c (close to main)

### How did you install Materialize?

Built from source

### What is the issue?

@dseisun-materialize Assigned to you since this could be Storage related, could you check who best to assign to?

For the first time I ran 4 SQLsmith instances against generators with a tick interval:
```
  CREATE SOURCE tpch
    FROM LOAD GENERATOR TPCH (SCALE FACTOR 0.00001, TICK INTERVAL '500ms')
    FOR ALL TABLES
    WITH (SIZE = '1');

  CREATE SOURCE auction
    FROM LOAD GENERATOR AUCTION (SCALE FACTOR 0.01, TICK INTERVAL '500ms')
    FOR ALL TABLES
    WITH (SIZE = '1');

  CREATE SOURCE counter
    FROM LOAD GENERATOR COUNTER (SCALE FACTOR 0.0001, TICK INTERVAL '500ms')
    WITH (SIZE = '1');
```
I artificially limited the memory to 40 GB with `ulimit -Sv 40000000` since OoM situations cause loss of interactivity of my entire system, make Cockroach die, etc.

After a while I started seeing panics in timely workers about invalid format (full logs: https://gist.github.com/def-/511e1f5be742f3710b5c03fdb5d0eda8):
```
thread 'timely:work-0' panicked at 'internal error: invalid encoded state: couldn't decode batch at key w186123f8-275f-41e1-a87e-2b4442e4ad2b/p8354e5c7-b93c-4ee3-9cf5-cd583b974581: External format error: File out of specification: A parquet file must containt a header and footer with at least 12 bytes
```

The system is then out of disk space after crashing a few times (many core dumps written), then can't start up anymore with a new failure, even after clearing disk space again:
```
thread 'coordinator' panicked at 'internal error: invalid encoded state: MissingField("trace")', /home/deen/git/materialize3/src/persist-client/src/internal/encoding.rs:656:45
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/result.rs:1750:5
   3: core::result::Result<T,E>::expect
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/result.rs:1047:23
   4: mz_persist_client::internal::encoding::UntypedState<T>::decode
             at ./src/persist-client/src/internal/encoding.rs:656:21
   5: mz_persist_client::internal::state_versions::StateVersions::fetch_rollup_at_key::{{closure}}::{{closure}}::{{closure}}
             at ./src/persist-client/src/internal/state_versions.rs:775:28
   6: mz_persist_client::internal::metrics::CodecMetrics::decode
             at ./src/persist-client/src/internal/metrics.rs:963:17
   7: mz_persist_client::internal::state_versions::StateVersions::fetch_rollup_at_key::{{closure}}::{{closure}}
             at ./src/persist-client/src/internal/state_versions.rs:772:13
   8: core::option::Option<T>::map
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/option.rs:972:29
   9: mz_persist_client::internal::state_versions::StateVersions::fetch_rollup_at_key::{{closure}}
             at ./src/persist-client/src/internal/state_versions.rs:766:9
  10: mz_persist_client::internal::state_versions::StateVersions::fetch_current_state::{{closure}}
             at ./src/persist-client/src/internal/state_versions.rs:344:17
  11: mz_persist_client::internal::state_versions::StateVersions::maybe_init_shard::{{closure}}
             at ./src/persist-client/src/internal/state_versions.rs:157:17
  12: mz_persist_client::internal::metrics::CmdMetrics::run_cmd::{{closure}}
             at ./src/persist-client/src/internal/metrics.rs:501:74
  13: mz_persist_client::internal::apply::Applier<K,V,T,D>::new::{{closure}}
             at ./src/persist-client/src/internal/apply.rs:92:13
  14: mz_persist_client::internal::machine::Machine<K,V,T,D>::new::{{closure}}
             at ./src/persist-client/src/internal/machine.rs:76:75
  15: mz_persist_client::PersistClient::open_writer::{{closure}}::{{closure}}
             at ./src/persist-client/src/lib.rs:553:9
  16: mz_persist_client::PersistClient::open_writer::{{closure}}
             at ./src/persist-client/src/lib.rs:527:5
  17: mz_storage_client::controller::Controller<T>::open_data_handles::{{closure}}
             at ./src/storage-client/src/controller.rs:2330:13
  18: <mz_storage_client::controller::Controller<T> as mz_storage_client::controller::StorageController>::create_collections::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at ./src/storage-client/src/controller.rs:1240:21
  19: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/stream/futures_unordered/mod.rs:515:17
  20: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/stream/stream/mod.rs:1626:9
  21: <futures_util::stream::stream::buffer_unordered::BufferUnordered<St> as futures_core::stream::Stream>::poll_next
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/stream/stream/buffer_unordered.rs:75:15
  22: <S as futures_core::stream::TryStream>::try_poll_next
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.25/src/stream.rs:196:9
  23: <futures_util::stream::try_stream::try_collect::TryCollect<St,C> as core::future::future::Future>::poll
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25/src/stream/try_stream/try_collect.rs:46:26
  24: <mz_storage_client::controller::Controller<T> as mz_storage_client::controller::StorageController>::create_collections::{{closure}}::{{closure}}
             at ./src/storage-client/src/controller.rs:1259:13
  25: <mz_storage_client::controller::Controller<T> as mz_storage_client::controller::StorageController>::create_collections::{{closure}}
             at ./src/storage-client/src/controller.rs:1113:5
  26: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/future/future.rs:125:9
  27: mz_adapter::coord::Coordinator::bootstrap::{{closure}}::{{closure}}
             at ./src/adapter/src/coord.rs:849:13
  28: mz_adapter::coord::Coordinator::bootstrap::{{closure}}
             at ./src/adapter/src/coord.rs:523:5
  29: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  30: mz_adapter::coord::serve::{{closure}}::{{closure}}::{{closure}}
             at ./src/adapter/src/coord.rs:1464:21
  31: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:63
  32: tokio::runtime::coop::with_budget
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:102:5
  33: tokio::runtime::coop::budget
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:68:5
  34: tokio::runtime::park::CachedParkThread::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:31
  35: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/context.rs:315:13
  36: tokio::runtime::handle::Handle::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/handle.rs:264:9
  37: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./src/adapter/src/coord.rs:1460:29
```
mzdata directory in case it helps for understanding what happened here: [mzdata.tar.gz](https://github.com/MaterializeInc/materialize/files/10925368/mzdata.tar.gz)
I'll check now if I can reproduce this. Edit: Queries are here: https://gist.github.com/def-/6cc76e74a3d6914162d2746a1a8e1718, unfortunately couldn't reproduce by rerunning them.

**Comment by danhhz** [comment]
interesting and potentially scary!

I'm initially inclined to guess this is some sort of artifact of the test setup. in particular, because of the "A parquet file must containt a header and footer with at least 12 bytes" bit, maybe the out of disk situation? it certainly sounds like a partial file (blob) got written, which isn't possible in prod (s3 writes are atomic). the one thing that gives me pause about that theory is that our FileBlob implementation does the usual write and rename trick to make them atomic, so we shouldn't have linked anything into state if it didn't succeed.

unfortunately, it's pretty unlikely that this is related to the particular queries or workload you were running, so dunno if we'll get a repro. I'm very interested to hear if we do, though!

cc @pH14 any thoughts?

**Comment by def-** [comment]
It appears that the out of disk situation triggered this. I was writing many core files and thus had full disk. After disabling core files I haven't seen this issue again.

**Comment by danhhz** [comment]
Downloaded your mzdata.tar.gz (HUGE TY) and verified that the blob in question is 0 bytes, which I think supports my truncated write theory. It's definitely a mystery to me why the write didn't fail (I double checked [the impl](https://github.com/MaterializeInc/materialize/blob/d51e13f3c84b3971f32a5f59046173580fa9cc0f/src/persist/src/file.rs#L141-L170) and nothing jumped out at me), but given that prod s3 doesn't have to deal with out of space errors, I'm tempted to call us more gracefully handling them out of spec for now.

**Comment by benesch** [comment]
> given that prod s3 doesn't have to deal with out of space errors, I'm tempted to call us more gracefully handling them out of spec for now.

Agreed!
