### ISSUE TITLE
[SQLsmith] thread 'coordinator' panicked at 'internal error: entered unreachable code: Float8 is not a range element type', src/pgrepr/src/types.rs:728:22

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18017]
### What version of Materialize are you using?

v0.46.0-dev (6b03c7d6f)

### How did you install Materialize?

Built from source

### What is the issue?

```
materialize=> CREATE SOURCE counter
    FROM LOAD GENERATOR COUNTER (SCALE FACTOR 0.0001)
    WITH (SIZE = '1');
CREATE SOURCE
materialize=> CREATE SOURCE tpch
    FROM LOAD GENERATOR TPCH (SCALE FACTOR 0.00001)
    FOR ALL TABLES
    WITH (SIZE = '1');
CREATE SOURCE
materialize=> select     from    (select             (select var_pop("offset") from counter_progress)              c1)       join part      on cast(null as uint4) > mod(             CAST(cast(null as uint4) as uint4),             CAST(cast(null as uint4) as uint4))          or case when cast(null as bpchar) ~ "p_mfgr" then case when numrange(0,0) @> "c1" then end          end        end;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

### Relevant log output

```source
thread 'coordinator' panicked at 'internal error: entered unreachable code: Float8 is not a range element type', src/pgrepr/src/types.rs:728:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/panicking.rs:64:14
   2: mz_pgrepr::types::Type::inner
             at ./src/pgrepr/src/types.rs:728:22
   3: mz_pgrepr::types::Type::name
             at ./src/pgrepr/src/types.rs:743:15
   4: <mz_adapter::catalog::ConnCatalog as mz_repr::explain::ExprHumanizer>::humanize_scalar_type
             at ./src/adapter/src/catalog.rs:6518:21
   5: mz_sql::plan::statement::StatementContext::humanize_scalar_type
             at ./src/sql/src/plan/statement.rs:739:9
   6: mz_sql::plan::query::ExprContext::humanize_scalar_type
             at ./src/sql/src/plan/query.rs:5326:9
   7: mz_sql::plan::typeconv::plan_cast::{{closure}}
             at ./src/sql/src/plan/typeconv.rs:943:13
   8: mz_sql::plan::typeconv::plan_cast
             at ./src/sql/src/plan/typeconv.rs:965:9
   9: mz_sql::plan::expr::CoercibleScalarExpr::cast_to
             at ./src/sql/src/plan/expr.rs:668:9
  10: mz_sql::func::coerce_args_to_types::{{closure}}
             at ./src/sql/src/func.rs:1485:53
  11: mz_sql::func::coerce_args_to_types
             at ./src/sql/src/func.rs:1529:17
  12: mz_sql::func::Operation<R>::variadic::{{closure}}
             at ./src/sql/src/func.rs:312:25
  13: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/alloc/src/boxed.rs:2002:9
  14: mz_sql::func::select_impl
             at ./src/sql/src/func.rs:977:5
  15: mz_sql::plan::query::plan_op
             at ./src/sql/src/plan/query.rs:4309:5
  16: mz_sql::plan::query::plan_expr_inner
             at ./src/sql/src/plan/query.rs:3180:16
  17: mz_sql::plan::query::plan_expr::{{closure}}
             at ./src/sql/src/plan/query.rs:3153:29
  18: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  19: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  20: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  21: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  22: mz_sql::plan::query::plan_expr
             at ./src/sql/src/plan/query.rs:3153:9
  23: mz_sql::plan::query::plan_case
             at ./src/sql/src/plan/query.rs:4537:21
  24: mz_sql::plan::query::plan_expr_inner
             at ./src/sql/src/plan/query.rs:3199:17
  25: mz_sql::plan::query::plan_expr::{{closure}}
             at ./src/sql/src/plan/query.rs:3153:29
  26: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  27: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  28: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  29: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  30: mz_sql::plan::query::plan_expr
             at ./src/sql/src/plan/query.rs:3153:9
  31: mz_sql::plan::query::plan_exprs
             at ./src/sql/src/plan/query.rs:3895:18
  32: mz_sql::plan::query::plan_case
             at ./src/sql/src/plan/query.rs:4547:9
  33: mz_sql::plan::query::plan_expr_inner
             at ./src/sql/src/plan/query.rs:3199:17
  34: mz_sql::plan::query::plan_expr::{{closure}}
             at ./src/sql/src/plan/query.rs:3153:29
  35: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  36: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  37: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  38: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  39: mz_sql::plan::query::plan_expr
             at ./src/sql/src/plan/query.rs:3153:9
  40: mz_sql::plan::query::plan_or
             at ./src/sql/src/plan/query.rs:3331:9
  41: mz_sql::plan::query::plan_expr_inner
             at ./src/sql/src/plan/query.rs:3188:37
  42: mz_sql::plan::query::plan_expr::{{closure}}
             at ./src/sql/src/plan/query.rs:3153:29
  43: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  44: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  45: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  46: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  47: mz_sql::plan::query::plan_expr
             at ./src/sql/src/plan/query.rs:3153:9
  48: mz_sql::plan::query::plan_join
             at ./src/sql/src/plan/query.rs:2960:22
  49: mz_sql::plan::query::plan_table_with_joins
             at ./src/sql/src/plan/query.rs:2266:37
  50: mz_sql::plan::query::plan_table_factor
             at ./src/sql/src/plan/query.rs:2320:33
  51: mz_sql::plan::query::plan_join
             at ./src/sql/src/plan/query.rs:2939:32
  52: mz_sql::plan::query::plan_view_select::{{closure}}
             at ./src/sql/src/plan/query.rs:1674:13
  53: core::iter::traits::iterator::Iterator::fold
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/iter/traits/iterator.rs:2438:21
  54: mz_sql::plan::query::plan_view_select
             at ./src/sql/src/plan/query.rs:1672:9
  55: mz_sql::plan::query::plan_query_inner
             at ./src/sql/src/plan/query.rs:1059:24
  56: mz_sql::plan::query::plan_query::{{closure}}
             at ./src/sql/src/plan/query.rs:1025:33
  57: mz_ore::stack::CheckedRecursion::checked_recur_mut::{{closure}}
             at ./src/ore/src/stack.rs:205:33
  58: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  59: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  60: mz_ore::stack::CheckedRecursion::checked_recur_mut
             at ./src/ore/src/stack.rs:205:19
  61: mz_sql::plan::query::plan_query
             at ./src/sql/src/plan/query.rs:1025:9
  62: mz_sql::plan::query::plan_root_query
             at ./src/sql/src/plan/query.rs:113:44
  63: mz_sql::plan::statement::dml::describe_select
             at ./src/sql/src/plan/statement/dml.rs:163:9
  64: mz_sql::plan::statement::describe
             at ./src/sql/src/plan/statement.rs:201:36
  65: mz_adapter::util::describe
             at ./src/adapter/src/util.rs:234:16
  66: mz_adapter::coord::sql::<impl mz_adapter::coord::Coordinator>::declare
             at ./src/adapter/src/coord/sql.rs:44:20
  67: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_command::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:78:30
  68: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_command::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:249:33
  69: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_command::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:246:5
  70: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::handle_message::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:44:63
  71: mz_adapter::coord::Coordinator::serve::{{closure}}
             at ./src/adapter/src/coord.rs:1298:37
  72: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:63
  73: tokio::runtime::coop::with_budget
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:102:5
  74: tokio::runtime::coop::budget
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:68:5
  75: tokio::runtime::park::CachedParkThread::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:31
  76: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/context.rs:315:13
  77: tokio::runtime::handle::Handle::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/handle.rs:264:9
  78: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./src/adapter/src/coord.rs:1477:17
```

ci-regexp: internal error: entered unreachable code: Float8 is not a range element type

**Comment by def-** [comment]
Easier repro: `select numrange(0,0) @> 2.0::float;`
```
thread 'coordinator' panicked at 'internal error: entered unreachable code: Float8 is not a range element type', src/pgrepr/src/types.rs:728:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/panicking.rs:64:14
   2: mz_pgrepr::types::Type::inner
             at ./src/pgrepr/src/types.rs:728:22
   3: mz_pgrepr::types::Type::name
             at ./src/pgrepr/src/types.rs:743:15
   4: <mz_adapter::catalog::ConnCatalog as mz_repr::explain::ExprHumanizer>::humanize_scalar_type
             at ./src/adapter/src/catalog.rs:6518:21
   5: mz_sql::plan::statement::StatementContext::humanize_scalar_type
             at ./src/sql/src/plan/statement.rs:739:9
   6: mz_sql::plan::query::ExprContext::humanize_scalar_type
             at ./src/sql/src/plan/query.rs:5326:9
   7: mz_sql::plan::typeconv::plan_cast::{{closure}}
             at ./src/sql/src/plan/typeconv.rs:943:13
   8: mz_sql::plan::typeconv::plan_cast
             at ./src/sql/src/plan/typeconv.rs:965:9
   9: mz_sql::plan::expr::CoercibleScalarExpr::cast_to
             at ./src/sql/src/plan/expr.rs:668:9
  10: mz_sql::func::coerce_args_to_types::{{closure}}
             at ./src/sql/src/func.rs:1485:53
  11: mz_sql::func::coerce_args_to_types
             at ./src/sql/src/func.rs:1529:17
  12: mz_sql::func::Operation<R>::variadic::{{closure}}
             at ./src/sql/src/func.rs:312:25
  13: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/alloc/src/boxed.rs:2002:9
  14: mz_sql::func::select_impl
             at ./src/sql/src/func.rs:977:5
  15: mz_sql::plan::query::plan_op
             at ./src/sql/src/plan/query.rs:4309:5
  16: mz_sql::plan::query::plan_expr_inner
             at ./src/sql/src/plan/query.rs:3180:16
  17: mz_sql::plan::query::plan_expr::{{closure}}
             at ./src/sql/src/plan/query.rs:3153:29
  18: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  19: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  20: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  21: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  22: mz_sql::plan::query::plan_expr
             at ./src/sql/src/plan/query.rs:3153:9
  23: mz_sql::plan::query::plan_view_select
             at ./src/sql/src/plan/query.rs:1901:51
  24: mz_sql::plan::query::plan_query_inner
             at ./src/sql/src/plan/query.rs:1059:24
  25: mz_sql::plan::query::plan_query::{{closure}}
             at ./src/sql/src/plan/query.rs:1025:33
  26: mz_ore::stack::CheckedRecursion::checked_recur_mut::{{closure}}
             at ./src/ore/src/stack.rs:205:33
  27: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  28: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  29: mz_ore::stack::CheckedRecursion::checked_recur_mut
             at ./src/ore/src/stack.rs:205:19
  30: mz_sql::plan::query::plan_query
             at ./src/sql/src/plan/query.rs:1025:9
  31: mz_sql::plan::query::plan_root_query
             at ./src/sql/src/plan/query.rs:113:44
  32: mz_sql::plan::statement::dml::describe_select
             at ./src/sql/src/plan/statement/dml.rs:163:9
  33: mz_sql::plan::statement::describe
             at ./src/sql/src/plan/statement.rs:201:36
  34: mz_adapter::util::describe
             at ./src/adapter/src/util.rs:234:16
  35: mz_adapter::coord::sql::<impl mz_adapter::coord::Coordinator>::declare
             at ./src/adapter/src/coord/sql.rs:44:20
  36: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_command::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:78:30
  37: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_command::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:249:33
  38: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_command::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:246:5
  39: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::handle_message::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:44:63
  40: mz_adapter::coord::Coordinator::serve::{{closure}}
             at ./src/adapter/src/coord.rs:1298:37
  41: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:63
  42: tokio::runtime::coop::with_budget
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:102:5
  43: tokio::runtime::coop::budget
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:68:5
  44: tokio::runtime::park::CachedParkThread::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:31
  45: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/context.rs:315:13
  46: tokio::runtime::handle::Handle::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/handle.rs:264:9
  47: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./src/adapter/src/coord.rs:1477:17
```

**Comment by jkosh44** [comment]
I'm still investigating this, but wanted to include some initial findings. When selecting the appropriate function to implement `@>`, we choose the following with parameter types of `(RangeAnyCompatible, AnyCompatible)`:
https://github.com/MaterializeInc/materialize/blob/eb7cfb47107cf6dd0ef194a7439b08dcbc1a4ecd/src/sql/src/func.rs#L3449-L3452

We generate a `PolymorphicSolution` to coerce the args for `@>` to the appropriate types here:
https://github.com/MaterializeInc/materialize/blob/eb7cfb47107cf6dd0ef194a7439b08dcbc1a4ecd/src/sql/src/func.rs#L1481-L1482

The params provided are: `Exact([RangeAnyCompatible, AnyCompatible])`, and the scalar types are: `[Some(Range { element_type: Numeric { max_scale: None } }), Some(Float64)]`.

So far this all makes sense. However, the generated `PolymorphicSolution` looks like this: `PolymorphicSolution { compat: Some(BestCommonAny), seen: [Some(Numeric { max_scale: None }), Some(Float64)], key: Some(Float64) }`, which means that `Float64` was chosen as the common type.

We then try and cast the numeric range to a float range. We don't implement float ranges, which causes the panic we are seeing.

**Comment by jkosh44** [comment]
Apparently `PolymorphicSolution` strips away the range type:
https://github.com/MaterializeInc/materialize/blob/eb7cfb47107cf6dd0ef194a7439b08dcbc1a4ecd/src/sql/src/func.rs#L1326
So the two `ScalarType`s it considers are `Numeric` and `Float64`. Among numeric types, the preferred type is `Float64`:
https://github.com/MaterializeInc/materialize/blob/eb7cfb47107cf6dd0ef194a7439b08dcbc1a4ecd/src/sql/src/func.rs#L193
So we select `Float64` as the target type for `@>`. When checking to make sure that the cast is compatible, we've stripped away the range information so we only consider if `Numeric` can cast to `Float64` and if `Float64` can cast to `Float64`:
https://github.com/MaterializeInc/materialize/blob/eb7cfb47107cf6dd0ef194a7439b08dcbc1a4ecd/src/sql/src/func.rs#L1408-L1415
The answer to both is yes. However when we actually go to apply the cast we try and cast the range expression to a range of floats which is invalid:
https://github.com/MaterializeInc/materialize/blob/eb7cfb47107cf6dd0ef194a7439b08dcbc1a4ecd/src/sql/src/func.rs#L1497-L1513

We actually do try and return an error but panic when trying to format the error message: 
https://github.com/MaterializeInc/materialize/blob/bf5c0cf9f32a4295c3109e5238f0e57bc4cdc326/src/sql/src/plan/typeconv.rs#L934-L943
Specifically `ecx.humanize_scalar_type(to)` panics because there's no way to humanize `to` because it's a range of floats which is an impossible type.

**Comment by jkosh44** [comment]
@sploiselle Any thoughts on this? You're probably the most familiar with ranges.

**Comment by sploiselle** [comment]
Yeah, I know where the bug in this is; will fix tonight.

**Comment by sploiselle** [comment]
Oh, sorry--you already found the bug! I can still fix this evening.

**Comment by sploiselle** [comment]
Fixing this requires refactoring polymorphic type resolution to treat the `Any` parameter as polymorphic. Will get this done tomorrow.
