### ISSUE TITLE
[SQLsmith] thread 'timely:work-0' panicked at 'batch fetcher could not fetch batch part: unexpected missing blob: ... for shard: ...', src/persist-client/src/fetch.rs:205:9

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18038]
### What version of Materialize are you using?

v0.46.0-dev (73941580c)

### How did you install Materialize?

Built from source

### What is the issue?

```
thread 'timely:work-0' panicked at 'batch fetcher could not fetch batch part: unexpected missing blob: w35abce01-4d58-4c20-9ea9-c8e0cd12bc5f/pff584628-39be-47e8-a85d-4b2a7a711943 for shard: s8f060894-d4c0-4c91-81f9-49d039466c8e', /home/deen/git/materialize3/src/persist-client/src/fetch.rs:205:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/panicking.rs:64:14
   2: mz_persist_client::fetch::fetch_leased_part::{{closure}}::{{closure}}
             at ./src/persist-client/src/fetch.rs:205:9
   3: core::result::Result<T,E>::unwrap_or_else
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/result.rs:1465:23
   4: mz_persist_client::fetch::fetch_leased_part::{{closure}}
             at ./src/persist-client/src/fetch.rs:187:24
   5: mz_persist_client::fetch::BatchFetcher<K,V,T,D>::fetch_leased_part::{{closure}}
             at ./src/persist-client/src/fetch.rs:109:9
   6: mz_persist_client::operators::shard_source::shard_source_fetch::{{closure}}::{{closure}}
             at ./src/persist-client/src/operators/shard_source.rs:475:25
   7: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/future/future.rs:125:9
   8: mz_timely_util::builder_async::OperatorBuilder<G>::build::{{closure}}::{{closure}}
             at ./src/timely-util/src/builder_async.rs:373:28
   9: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/operators/generic/builder_rc.rs:172:26
  10: <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/operators/generic/builder_raw.rs:204:9
  11: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:699:30
  12: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:346:26
  13: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:312:17
  14: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:699:30
  15: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:346:26
  16: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:312:17
  17: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:699:30
  18: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:346:26
  19: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:312:17
  20: timely::worker::Wrapper::step::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/worker.rs:754:57
  21: core::option::Option<T>::map
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/option.rs:972:29
  22: timely::worker::Wrapper::step
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/worker.rs:754:26
  23: timely::worker::Worker<A>::step_or_park
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/worker.rs:396:38
  24: mz_compute::server::Worker<A>::run_client
             at ./src/compute/src/server.rs:347:13
  25: mz_compute::server::Worker<A>::setup_channel_and_run_client
             at ./src/compute/src/server.rs:321:9
  26: mz_compute::server::Worker<A>::run
             at ./src/compute/src/server.rs:181:21
  27: <mz_compute::server::Config as mz_cluster::types::AsRunnableWorker<mz_compute_client::protocol::command::ComputeCommand,mz_compute_client::protocol::response::ComputeResponse>>::build_and_run
             at ./src/compute/src/server.rs:162:9
  28: mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<C,R,<Worker as mz_cluster::types::AsRunnableWorker<C,R>>::Activatable>,C,R>,Worker,C,R>::build_timely::{{closure}}::{{closure}}
             at ./src/cluster/src/server.rs:178:13
  29: timely::execute::execute_from::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/execute.rs:388:22
  30: timely_communication::initialize::initialize_from::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/communication/src/initialize.rs:316:33
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
environmentd: 2023-03-09T23:04:38.960722Z ERROR mz_orchestrator_process: cluster-u1-replica-1-0 exited: ExitStatus(unix_wait_status(6)); relaunching in 5s
```
[mzdata.zip](https://github.com/MaterializeInc/materialize/files/10937119/mzdata.zip)

I can't reproduce this, similar to https://github.com/MaterializeInc/materialize/issues/18036, since the query itself didn't return a failure, so I don't know which query caused it. These 5 queries were running at the time, but executing any of them doesn't cause the panic: https://gist.github.com/def-/cbb5a7146785e46115d59e3ba983f9ee
The tables are created via:
```
  CREATE SOURCE tpch
    FROM LOAD GENERATOR TPCH (SCALE FACTOR 0.00001)
    FOR ALL TABLES
    WITH (SIZE = '1');

  CREATE SOURCE auction
    FROM LOAD GENERATOR AUCTION (SCALE FACTOR 0.01)
    FOR ALL TABLES
    WITH (SIZE = '1');

  CREATE SOURCE counter
    FROM LOAD GENERATOR COUNTER (SCALE FACTOR 0.0001)
    WITH (SIZE = '1');
```

ci-regexp: batch fetcher could not fetch batch part: unexpected missing blob

**Comment by def-** [comment]
Might be related to https://github.com/MaterializeInc/materialize/issues/16793 and https://github.com/MaterializeInc/materialize/issues/17338 . If confirmed, I'd close this as a duplicate of https://github.com/MaterializeInc/materialize/issues/17338

**Comment by philip-stoev** [comment]
Consolidating in https://github.com/MaterializeInc/materialize/issues/17338
