### ISSUE TITLE
[SQLsmith] thread 'timely:work-0' panicked at 'Datum::unwrap_string called on Null', src/expr/src/scalar/func.rs:5932:50

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18036]
### What version of Materialize are you using?

v0.46.0-dev (ea8e22a62)

### How did you install Materialize?

Docker image

### What is the issue?

I couldn't find the responsible query for this since only clusterd panicked, but environmentd didn't report this failure:
```
thread 'timely:work-0' panicked at 'Datum::unwrap_string called on Null', src/expr/src/scalar/func.rs:5932:50
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/panicking.rs:64:14
   2: mz_repr::scalar::Datum::unwrap_str
             at ./src/repr/src/scalar.rs:631:18
   3: mz_expr::scalar::func::create_range
             at ./src/expr/src/scalar/func.rs:5932:40
   4: mz_expr::scalar::func::VariadicFunc::eval
             at ./src/expr/src/scalar/func.rs:6522:49
   5: mz_expr::scalar::MirScalarExpr::eval
             at ./src/expr/src/scalar/mod.rs:1753:60
   6: <T as mz_expr::scalar::func::LazyUnaryFunc>::eval
             at ./src/expr/src/scalar/func.rs:3748:41
   7: mz_expr::scalar::func::UnaryFunc::eval
             at ./src/expr/src/scalar/func/macros.rs:289:41
   8: mz_expr::scalar::MirScalarExpr::eval
             at ./src/expr/src/scalar/mod.rs:1749:56
   9: mz_compute_client::plan::join::JoinClosure::apply
             at ./src/compute-client/src/plan/join/mod.rs:136:23
  10: mz_compute::render::join::linear_join::differential_join_inner::{{closure}}
             at ./src/compute/src/render/join/linear_join.rs:290:22
  11: <differential_dataflow::operators::arrange::arrangement::Arranged<G,T1> as differential_dataflow::operators::join::JoinCore<G,<T1 as differential_dataflow::trace::TraceReader>::Key,<T1 as differential_dataflow::trace::TraceReader>::Val,<T1 as differential_dataflow::trace::TraceReader>::R>>::join_core::{{closure}}
             at /home/deen/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/cc88469/src/operators/join.rs:382:13
  12: <differential_dataflow::operators::arrange::arrangement::Arranged<G,T1> as differential_dataflow::operators::join::JoinCore<G,<T1 as differential_dataflow::trace::TraceReader>::Key,<T1 as differential_dataflow::trace::TraceReader>::Val,<T1 as differential_dataflow::trace::TraceReader>::R>>::join_core_internal_unsafe::{{closure}}::{{closure}}::{{closure}}
             at /home/deen/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/cc88469/src/operators/join.rs:578:43
  13: differential_dataflow::operators::join::Deferred<K,T,R,C1,C2,D>::work::{{closure}}
             at /home/deen/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/cc88469/src/operators/join.rs:724:42
  14: differential_dataflow::operators::join::JoinThinker<V1,V2,T,R1,R2>::think::{{closure}}::{{closure}}
             at /home/deen/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/cc88469/src/operators/join.rs:778:21
  15: differential_dataflow::operators::EditList<V,T,R>::map
             at /home/deen/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/cc88469/src/operators/mod.rs:77:17
  16: differential_dataflow::operators::join::JoinThinker<V1,V2,T,R1,R2>::think::{{closure}}
             at /home/deen/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/cc88469/src/operators/join.rs:777:17
  17: differential_dataflow::operators::EditList<V,T,R>::map
             at /home/deen/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/cc88469/src/operators/mod.rs:77:17
  18: differential_dataflow::operators::join::JoinThinker<V1,V2,T,R1,R2>::think
             at /home/deen/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/cc88469/src/operators/join.rs:776:13
  19: differential_dataflow::operators::join::Deferred<K,T,R,C1,C2,D>::work
             at /home/deen/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/cc88469/src/operators/join.rs:722:21
  20: <differential_dataflow::operators::arrange::arrangement::Arranged<G,T1> as differential_dataflow::operators::join::JoinCore<G,<T1 as differential_dataflow::trace::TraceReader>::Key,<T1 as differential_dataflow::trace::TraceReader>::Val,<T1 as differential_dataflow::trace::TraceReader>::R>>::join_core_internal_unsafe::{{closure}}::{{closure}}
             at /home/deen/.cargo/git/checkouts/differential-dataflow-d065d23d797aa027/cc88469/src/operators/join.rs:576:21
  21: <timely::dataflow::stream::StreamCore<G,D1> as timely::dataflow::operators::generic::operator::Operator<G,D1>>::binary_frontier::{{closure}}::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/operators/generic/operator.rs:434:17
  22: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/operators/generic/builder_rc.rs:133:31
  23: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/operators/generic/builder_rc.rs:172:26
  24: <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/operators/generic/builder_raw.rs:204:9
  25: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:699:30
  26: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:346:26
  27: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:312:17
  28: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:699:30
  29: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:346:26
  30: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:312:17
  31: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:699:30
  32: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:346:26
  33: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:312:17
  34: timely::worker::Wrapper::step::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/worker.rs:754:57
  35: core::option::Option<T>::map
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/option.rs:972:29
  36: timely::worker::Wrapper::step
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/worker.rs:754:26
  37: timely::worker::Worker<A>::step_or_park
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/worker.rs:396:38
  38: mz_compute::server::Worker<A>::run_client
             at ./src/compute/src/server.rs:347:13
  39: mz_compute::server::Worker<A>::setup_channel_and_run_client
             at ./src/compute/src/server.rs:321:9
  40: mz_compute::server::Worker<A>::run
             at ./src/compute/src/server.rs:181:21
  41: <mz_compute::server::Config as mz_cluster::types::AsRunnableWorker<mz_compute_client::protocol::command::ComputeCommand,mz_compute_client::protocol::response::ComputeResponse>>::build_and_run
             at ./src/compute/src/server.rs:162:9
  42: mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<C,R,<Worker as mz_cluster::types::AsRunnableWorker<C,R>>::Activatable>,C,R>,Worker,C,R>::build_timely::{{closure}}::{{closure}}
             at ./src/cluster/src/server.rs:178:13
  43: timely::execute::execute_from::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/execute.rs:388:22
  44: timely_communication::initialize::initialize_from::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/communication/src/initialize.rs:316:33
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
environmentd: 2023-03-09T19:18:41.396586Z ERROR mz_orchestrator_process: cluster-u1-replica-1-0 exited: ExitStatus(unix_wait_status(6)); relaunching in 5s
```
Since it happened inside of a join and was in create_range, my guess was something like this:
```
select tstzrange(nullif(now(), now()), null) from users join region on True;
```
It would be easier for me if we could print out the failed query when environmentd restarts clusterd.

ci-regexp: Datum::unwrap_string called on Null

**Comment by def-** [comment]
I recently found out about `--orchestrator-process-propagate-crashes`, let me try to repro with this flag so that I can find the responsible query.

**Comment by def-** [comment]
Reproducer:
```
select where (pg_catalog.tsrange(CAST(cast(null as timestamp) as timestamp), CAST(cast(null as timestamp) as timestamp), CAST(cast(null as text) as text)) is not NULL);
```

**Comment by antiguru** [comment]
@sploiselle this seems to be a bug in `create_range` not checking for `NULL` parameters?

**Comment by def-** [comment]
Other than the `range` functions, this also happens in `mz_error_if_null`:
```
explain raw plan with (join_impls, types) as json for select
  "subq_3"."c0" as c0,
  pg_catalog.hmac(
    CAST((select pg_catalog.min("id") from mz_internal.mz_sink_statistics)
       as text),
    CAST(cast(nullif(case when cast(null as uint4) <= cast(null as uint4) then mz_catalog.mz_environment_id() else mz_catalog.mz_environment_id() end
        ,
      pg_catalog.version()) as text) as text),
    CAST(pg_catalog.current_schema() as text)) as c1,
  "subq_3"."c0" as c2,
  mz_internal.mz_error_if_null(
    pg_catalog.pg_get_userbyid(
      CAST(cast(null as oid) as oid)),
    CAST(cast(null as text) as text)) as c3,
  "subq_3"."c0" as c4,
  "subq_3"."c0" as c5,
  "subq_3"."c0" as c6,
  "subq_3"."c0" as c7
from
  (select
        "subq_2"."c3" as c0
      from
        (select
              "subq_1"."c2" as c0,
              "subq_1"."c2" as c1,
              "subq_0"."c0" as c2,
              "subq_1"."c1" as c3
            from
              (select
                    "ref_0"."replica_id" as c0,
                    "ref_0"."export_id" as c1,
                    "ref_0"."replica_id" as c2,
                    "ref_0"."time" as c3
                  from
                    mz_internal.mz_cluster_replica_frontiers as ref_0
                  where (false)
                    or (cast(null as bpchar) ~* "ref_0"."export_id")
                  limit 33) as subq_0,
              lateral (select
                    (select pg_catalog.sum("enumsortorder") from pg_catalog.pg_enum)
                       as c0,
                    "ref_1"."id" as c1,
                    "ref_1"."local_id" as c2
                  from
                    mz_internal.mz_dataflows as ref_1
                  where "ref_1"."id" is NULL) as subq_1
            where (((cast(null as char) <= cast(null as char))
                  or ((true)
                    and ((array[null, null] = array[null, null])
                      or (cast(null as timestamptz) = (select "occurred_at" from mz_internal.mz_source_status_history limit 1 offset 5)
                          ))))
                or (cast(null as bpchar) !~~* "subq_0"."c1"))
              or (cast(null as char) >= cast(null as char))
            limit 167) as subq_2
      where (select "polpermissive" from pg_catalog.pg_policy limit 1 offset 30)
           <= (select "ready" from mz_internal.mz_show_cluster_replicas limit 1 offset 6)

      limit 74) as subq_3
where (select "conindid" from pg_catalog.pg_constraint limit 1 offset 1)
     = cast(null as oid);
```

**Comment by sploiselle** [comment]
@def- I contend that `mz_error_if_null` should panic with a null argument. This is a bespoke mz function meant for internal use; the second error is meant to generate an error message, so providing a NULL argument there is a fatal programming error.
