### ISSUE TITLE
[SQLsmith] thread 'timely:work-0' panicked at 'Invalid argument to AggregateFunc::Any: Int64(43)', /home/deen/git/materialize3/src/compute/src/render/reduce.rs:1222:22

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18057]
### What version of Materialize are you using?

v0.46.0-dev (ae6c32824)

### How did you install Materialize?

Built from source

### What is the issue?

I guess I'm not supposed to use `mz_all`, but shouldn't panic anyway:
```
materialize=> CREATE SOURCE auction
    FROM LOAD GENERATOR AUCTION (SCALE FACTOR 0.01)
    FOR ALL TABLES
    WITH (SIZE = '1');
CREATE SOURCE
materialize=> SELECT mz_internal.mz_all(id) FROM public.accounts;
 ?column?
----------
 t
(1 row)

materialize=> SELECT mz_internal.mz_all(id) FROM public.accounts;
NOTICE:  cluster replica default.r1 changed status to "not-ready" at 2023-03-10 16:16:59.353885+00
HINT:  The cluster replica may be restarting or going offline.
NOTICE:  cluster replica default.r1 changed status to "ready" at 2023-03-10 16:17:04.355431+00
NOTICE:  cluster replica default.r1 changed status to "not-ready" at 2023-03-10 16:17:05.538927+00
HINT:  The cluster replica may be restarting or going offline.
NOTICE:  cluster replica default.r1 changed status to "ready" at 2023-03-10 16:17:10.54024+00
NOTICE:  cluster replica default.r1 changed status to "not-ready" at 2023-03-10 16:17:11.65362+00
HINT:  The cluster replica may be restarting or going offline.
```

### Relevant log output

```source
environmentd: 2023-03-10T16:15:44.095223Z  WARN mz_storage_client::controller::rehydration: storage cluster produced error, reconnecting: status: Unknown, message: "error reading a body from connection: broken pipe", details: [], metadata: MetadataMap { headers: {} }
environmentd: 2023-03-10T16:15:44.095394Z  WARN mz_compute_client::controller::replica: replica task for 1 failed: status: Unknown, message: "error reading a body from connection: broken pipe", details: [], metadata: MetadataMap { headers: {} }
environmentd: 2023-03-10T16:15:48.024092Z  WARN mz_orchestrator_process: process for cluster-u1-replica-1-0 has crashed; will reboot pid=1766286
thread 'timely:work-0' panicked at 'Invalid argument to AggregateFunc::Any: Int64(43)', /home/deen/git/materialize3/src/compute/src/render/reduce.rs:1222:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/panicking.rs:64:14
   2: mz_compute::render::reduce::build_accumulable::{{closure}}
   3: mz_compute::render::reduce::build_accumulable::{{closure}}
             at ./src/compute/src/render/reduce.rs:1361:51
   4: <differential_dataflow::collection::Collection<G,D1,R> as mz_timely_util::operator::CollectionExt<G,D1,R>>::explode_one::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at ./src/timely-util/src/operator.rs:434:47
   5: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/ops/function.rs:310:13
   6: core::option::Option<T>::map
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/option.rs:972:29
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/iter/adapters/map.rs:103:9
   8: mz_timely_util::buffer::ConsolidateBuffer<T,D,R,P>::give_iterator
             at ./src/timely-util/src/buffer.rs:82:21
   9: <differential_dataflow::collection::Collection<G,D1,R> as mz_timely_util::operator::CollectionExt<G,D1,R>>::explode_one::{{closure}}::{{closure}}::{{closure}}
             at ./src/timely-util/src/operator.rs:431:25
  10: timely::dataflow::operators::generic::handles::InputHandleCore<T,D,P>::for_each
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/operators/generic/handles.rs:94:13
  11: <differential_dataflow::collection::Collection<G,D1,R> as mz_timely_util::operator::CollectionExt<G,D1,R>>::explode_one::{{closure}}::{{closure}}
             at ./src/timely-util/src/operator.rs:429:21
  12: <timely::dataflow::stream::StreamCore<G,D1> as timely::dataflow::operators::generic::operator::Operator<G,D1>>::unary::{{closure}}::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/operators/generic/operator.rs:401:17
  13: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/operators/generic/builder_rc.rs:133:31
  14: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/operators/generic/builder_rc.rs:172:26
  15: <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/operators/generic/builder_raw.rs:204:9
  16: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:699:30
  17: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:346:26
  18: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:312:17
  19: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:699:30
  20: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:346:26
  21: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:312:17
  22: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:699:30
  23: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:346:26
  24: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:312:17
  25: timely::worker::Wrapper::step::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/worker.rs:754:57
  26: core::option::Option<T>::map
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/option.rs:972:29
  27: timely::worker::Wrapper::step
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/worker.rs:754:26
  28: timely::worker::Worker<A>::step_or_park
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/worker.rs:396:38
  29: mz_compute::server::Worker<A>::run_client
             at ./src/compute/src/server.rs:347:13
  30: mz_compute::server::Worker<A>::setup_channel_and_run_client
             at ./src/compute/src/server.rs:321:9
  31: mz_compute::server::Worker<A>::run
             at ./src/compute/src/server.rs:181:21
  32: <mz_compute::server::Config as mz_cluster::types::AsRunnableWorker<mz_compute_client::protocol::command::ComputeCommand,mz_compute_client::protocol::response::ComputeResponse>>::build_and_run
             at ./src/compute/src/server.rs:162:9
  33: mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<C,R,<Worker as mz_cluster::types::AsRunnableWorker<C,R>>::Activatable>,C,R>,Worker,C,R>::build_timely::{{closure}}::{{closure}}
             at ./src/cluster/src/server.rs:178:13
  34: timely::execute::execute_from::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/execute.rs:388:22
  35: timely_communication::initialize::initialize_from::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/communication/src/initialize.rs:316:33
```

ci-regexp: Invalid argument to AggregateFunc::Any:

**Comment by frankmcsherry** [comment]
I think there are two takes here:
1. `mz_internal` is meant to be internal. We should perhaps feature flag them. 
2. This could be better supported as requiring a boolean argument, and the SQL layer should complain rather than ship it as a dataflow.

It does make sense that it panics, because this operator's behavior is to be applied as an infallible aggregation, in the same way that `SumInt64` shouldn't be applied to `Float32` inputs and this results in a panic.

**Comment by benesch** [comment]
> I'm assigning this to @MaterializeInc/surfaces. This issue can be lumped together with #15805 and #18023, for all of which the best fix is probably to prevent user access to `mz_all` and `mz_internal`.

Agree that's the best fix. It's a bit hard to enforce, as the SQL planner rewrites the AST to include calls to these functions if you use the `ALL` or `ANY` operator. It's a bit funny for sure.

I guess we could scan the AST _before_ any AST rewrites, look for any functions that reference the `mz_internal` schema, and reject the query if we see any.

**Comment by benesch** [comment]
Would lump in https://github.com/MaterializeInc/materialize/issues/17984 too.
