### ISSUE TITLE
thread 'test_table' panicked at 'called `Option::unwrap()` on a `None` value', tests/src/ore/src/assert.rs:54:1

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18122]
### What version of Materialize are you using?

https://github.com/MaterializeInc/materialize/pull/18119

### How did you install Materialize?

Docker image

### What is the issue?

With my WIP change https://github.com/MaterializeInc/materialize/pull/18119
```
$ git checkout a142278b2137f700dcf62adfde3cbe22802fe1f0
$ cd src/stash
$ MIRIFLAGS="-Zmiri-disable-isolation" cargo miri nextest run --no-fail-fast
    Starting 1 tests across 2 binaries (1 skipped)
        FAIL [   3.195s] mz-stash::stash test_table

--- STDOUT:              mz-stash::stash test_table ---

running 1 test
test test_table ... FAILED

failures:

failures:
    test_table

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 1 filtered out


--- STDERR:              mz-stash::stash test_table ---
thread 'test_table' panicked at 'called `Option::unwrap()` on a `None` value', /home/deen/git/materialize2/src/ore/src/assert.rs:54:1
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /home/deen/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /home/deen/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /home/deen/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:114:5
   3: std::option::Option::<&std::sync::atomic::AtomicBool>::unwrap
             at /home/deen/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:823:21
   4: <mz_ore::assert::SOFT_ASSERTIONS<std::sync::atomic::AtomicBool> as std::ops::Deref>::deref
             at /home/deen/git/materialize2/src/ore/src/assert.rs:54:1
   5: mz_stash::TableTransaction::<std::vec::Vec<u8>, std::string::String>::insert
             at /home/deen/git/materialize2/src/stash/src/lib.rs:920:9
   6: test_table
             at src/stash/tests/stash.rs:937:5
   7: test_table::{closure#0}
             at src/stash/tests/stash.rs:928:17
   8: <[closure@src/stash/tests/stash.rs:928:1: 943:2] as std::ops::FnOnce<()>>::call_once - shim
             at /home/deen/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
   9: <fn() -> std::result::Result<(), std::string::String> as std::ops::FnOnce<()>>::call_once - shim(fn() -> std::result::Result<(), std::string::String>)
             at /home/deen/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Comes from https://github.com/MaterializeInc/materialize/pull/11837, thus assigned @mjibson

**Comment by mjibson** [comment]
This is a failure in a test that doesn't use the Stash or network at all. It inserts a few entries into a table txn, and the insert runs a debug check verifying that there are no uniqueness violations. That verification is the thing failing here. I only learned about miri just now, and don't know what it's doing to cause this.

**Comment by def-** [comment]
It runs Rust's MIR with an interpreter and single-thraeded, so there could be a timing related problem which we don't see in the usual faster execution.

**Comment by mjibson** [comment]
The code here only uses a single thread. It's a bunch of BTree operations in order.
