### ISSUE TITLE
[SQLsmith] thread 'coordinator' panicked at 'into_element called on collection with more than one element', src/ore/src/collections.rs:72:18

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18144]
### What version of Materialize are you using?

v0.47.0-dev (e019f665e)

### How did you install Materialize?

Built from source

### What is the issue?

```
materialize> WITH a AS (select case when ''::map[text=>text] ?& cast(null as _text) then "c3" end from (select 2 c3 )), b AS (select case when (select "id" from mz_internal.mz_active_peeks ) = (select "id" from mz_internal.mz_active_peeks ) then 0 end ) select array_in( CAST("c0" as text), CAST(case when 0 < cast(cast(null as numeric) as numeric) then 0 end as oid), CAST(case when 0 >= 0 then case when cast(null as oid) > cast(null as oid) then 0 end end as int4)) from (select "shard_id" c0 from mz_internal.mz_storage_usage_by_shard ) where cast(null as bytea) >= case when case when cast(null as timestamp) = cast(null as timestamp) then cast(null as bytea) end > cast(null as bytea) then case when true then cast(null as bytea) end end;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

ci-regexp: into_element called on collection with more than one element

### Relevant log output

```source
thread 'coordinator' panicked at 'into_element called on collection with more than one element', /home/deen/git/materialize3/src/ore/src/collections.rs:72:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/panicking.rs:147:5
   3: <T as mz_ore::collections::CollectionExt<T>>::expect_element
             at ./src/ore/src/collections.rs:72:18
   4: mz_ore::collections::CollectionExt::into_element
             at ./src/ore/src/collections.rs:46:9
   5: mz_sql::func::Operation<R>::unary::{{closure}}
             at ./src/sql/src/func.rs:254:49
   6: mz_sql::func::Operation<R>::variadic::{{closure}}
             at ./src/sql/src/func.rs:313:13
   7: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/alloc/src/boxed.rs:2002:9
   8: mz_sql::func::select_impl
             at ./src/sql/src/func.rs:977:5
   9: mz_sql::plan::query::plan_function
             at ./src/sql/src/plan/query.rs:4428:5
  10: mz_sql::plan::query::plan_expr_inner
             at ./src/sql/src/plan/query.rs:3183:36
  11: mz_sql::plan::query::plan_expr::{{closure}}
             at ./src/sql/src/plan/query.rs:3153:29
  12: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  13: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  14: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  15: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  16: mz_sql::plan::query::plan_expr
             at ./src/sql/src/plan/query.rs:3153:9
  17: mz_sql::plan::query::plan_view_select
             at ./src/sql/src/plan/query.rs:1901:51
  18: mz_sql::plan::query::plan_query_inner
             at ./src/sql/src/plan/query.rs:1059:24
  19: mz_sql::plan::query::plan_query::{{closure}}
             at ./src/sql/src/plan/query.rs:1025:33
  20: mz_ore::stack::CheckedRecursion::checked_recur_mut::{{closure}}
             at ./src/ore/src/stack.rs:205:33
  21: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  22: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  23: mz_ore::stack::CheckedRecursion::checked_recur_mut
             at ./src/ore/src/stack.rs:205:19
  24: mz_sql::plan::query::plan_query
             at ./src/sql/src/plan/query.rs:1025:9
  25: mz_sql::plan::query::plan_root_query
             at ./src/sql/src/plan/query.rs:113:44
  26: mz_sql::plan::statement::dml::describe_select
             at ./src/sql/src/plan/statement/dml.rs:163:9
  27: mz_sql::plan::statement::describe
             at ./src/sql/src/plan/statement.rs:201:36
  28: mz_adapter::util::describe
             at ./src/adapter/src/util.rs:234:16
  29: mz_adapter::coord::sql::<impl mz_adapter::coord::Coordinator>::declare
             at ./src/adapter/src/coord/sql.rs:44:20
  30: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_command::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:82:30
  31: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_command::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:249:33
  32: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_command::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:246:5
  33: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::handle_message::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:44:63
  34: mz_adapter::coord::Coordinator::serve::{{closure}}
             at ./src/adapter/src/coord.rs:1298:37
  35: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:63
  36: tokio::runtime::coop::with_budget
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:102:5
  37: tokio::runtime::coop::budget
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:68:5
  38: tokio::runtime::park::CachedParkThread::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:31
  39: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/context.rs:315:13
  40: tokio::runtime::handle::Handle::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/handle.rs:264:9
  41: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./src/adapter/src/coord.rs:1477:17
```

**Comment by chaas** [comment]
I reduced this down to `select array_in(CAST(null as text), CAST(null as oid), CAST(null as int4));`
