### ISSUE TITLE
thread 'coordinator' panicked at 'attempt to divide with overflow', src/expr/src/scalar/func.rs:953:24

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18181]
### What version of Materialize are you using?

v0.47.0-dev (4e765e19a)

### How did you install Materialize?

Built from source

### What is the issue?

```
materialize=> SELECT (-32768)::int2 / (-1)::int2;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

### Relevant log output

```source
thread 'coordinator' panicked at 'attempt to divide with overflow', src/expr/src/scalar/func.rs:953:24
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/panicking.rs:114:5
   3: mz_expr::scalar::func::div_int16
             at ./src/expr/src/scalar/func.rs:953:24
   4: mz_expr::scalar::func::BinaryFunc::eval
             at ./src/expr/src/scalar/func.rs:2103:37
   5: mz_expr::scalar::MirScalarExpr::eval
             at ./src/expr/src/scalar/mod.rs:1751:17
   6: mz_expr::scalar::MirScalarExpr::reduce::{{closure}}
             at ./src/expr/src/scalar/mod.rs:672:36
   7: mz_expr::scalar::MirScalarExpr::reduce::{{closure}}
             at ./src/expr/src/scalar/mod.rs:741:34
   8: <T as mz_expr::visit::Visit>::visit_mut_pre_post_nolimit
             at ./src/expr/src/visit.rs:439:9
   9: mz_expr::scalar::MirScalarExpr::reduce
             at ./src/expr/src/scalar/mod.rs:680:13
  10: mz_transform::fold_constants::FoldConstants::action
             at ./src/transform/src/fold_constants.rs:173:21
  11: <mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform::{{closure}}
             at ./src/transform/src/fold_constants.rs:51:13
  12: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}
             at ./src/expr/src/visit.rs:556:13
  13: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  14: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  15: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  16: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  17: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post
             at ./src/expr/src/visit.rs:554:14
  18: <T as mz_expr::visit::Visit>::try_visit_mut_post
             at ./src/expr/src/visit.rs:345:9
  19: <mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform
             at ./src/transform/src/fold_constants.rs:47:22
  20: <mz_transform::FuseAndCollapse as mz_transform::Transform>::transform
             at ./src/transform/src/lib.rs:371:13
  21: <mz_transform::Fixpoint as mz_transform::Transform>::transform::{{closure}}
             at ./src/transform/src/lib.rs:270:29
  22: tracing::span::Span::in_scope
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/span.rs:1102:9
  23: <mz_transform::Fixpoint as mz_transform::Transform>::transform
             at ./src/transform/src/lib.rs:267:17
  24: mz_transform::Optimizer::transform
             at ./src/transform/src/lib.rs:592:17
  25: mz_transform::Optimizer::optimize
             at ./src/transform/src/lib.rs:563:32
  26: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::plan_peek
             at ./src/adapter/src/coord/sequencer.rs:2556:22
  27: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_peek_finish::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:2389:29
  28: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_peek_finish::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:2371:5
  29: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_peek_begin::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:2275:21
  30: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_peek_begin::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:2198:5
  31: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_plan::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:303:60
  32: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_plan::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:120:5
  33: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute_inner::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:510:78
  34: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute_inner::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:311:5
  35: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:308:61
  36: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:267:5
  37: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  38: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_command::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:72:21
  39: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_command::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:249:33
  40: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_command::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:246:5
  41: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::handle_message::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:44:63
  42: mz_adapter::coord::Coordinator::serve::{{closure}}
             at ./src/adapter/src/coord.rs:1298:37
  43: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:63
  44: tokio::runtime::coop::with_budget
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:102:5
  45: tokio::runtime::coop::budget
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:68:5
  46: tokio::runtime::park::CachedParkThread::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:31
  47: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/context.rs:315:13
  48: tokio::runtime::handle::Handle::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/handle.rs:264:9
  49: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./src/adapter/src/coord.rs:1477:17
```

**Comment by def-** [comment]
Similar issue with remainder:
```
materialize=> SELECT (-32768)::int2 % (-1)::int2;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```
```
thread 'coordinator' panicked at 'attempt to calculate the remainder with overflow', src/expr/src/scalar/func.rs:1075:24
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/fdbc4329cb781c7768ffa6d76c8fa2d032d3fe20/library/core/src/panicking.rs:114:5
   3: mz_expr::scalar::func::mod_int16
             at ./src/expr/src/scalar/func.rs:1075:24
   4: mz_expr::scalar::func::BinaryFunc::eval
             at ./src/expr/src/scalar/func.rs:2113:37
   5: mz_expr::scalar::MirScalarExpr::eval
             at ./src/expr/src/scalar/mod.rs:1751:17
   6: mz_expr::scalar::MirScalarExpr::reduce::{{closure}}
             at ./src/expr/src/scalar/mod.rs:672:36
   7: mz_expr::scalar::MirScalarExpr::reduce::{{closure}}
             at ./src/expr/src/scalar/mod.rs:741:34
   8: <T as mz_expr::visit::Visit>::visit_mut_pre_post_nolimit
             at ./src/expr/src/visit.rs:439:9
   9: mz_expr::scalar::MirScalarExpr::reduce
             at ./src/expr/src/scalar/mod.rs:680:13
  10: mz_transform::fold_constants::FoldConstants::action
             at ./src/transform/src/fold_constants.rs:173:21
  11: <mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform::{{closure}}
             at ./src/transform/src/fold_constants.rs:51:13
  12: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}
             at ./src/expr/src/visit.rs:556:13
  13: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  14: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  15: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  16: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  17: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post
             at ./src/expr/src/visit.rs:554:14
  18: <T as mz_expr::visit::Visit>::try_visit_mut_post
             at ./src/expr/src/visit.rs:345:9
  19: <mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform
             at ./src/transform/src/fold_constants.rs:47:22
  20: <mz_transform::FuseAndCollapse as mz_transform::Transform>::transform
             at ./src/transform/src/lib.rs:371:13
  21: <mz_transform::Fixpoint as mz_transform::Transform>::transform::{{closure}}
             at ./src/transform/src/lib.rs:270:29
  22: tracing::span::Span::in_scope
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/span.rs:1102:9
  23: <mz_transform::Fixpoint as mz_transform::Transform>::transform
             at ./src/transform/src/lib.rs:267:17
  24: mz_transform::Optimizer::transform
             at ./src/transform/src/lib.rs:592:17
  25: mz_transform::Optimizer::optimize
             at ./src/transform/src/lib.rs:563:32
  26: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::plan_peek
             at ./src/adapter/src/coord/sequencer.rs:2556:22
  27: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_peek_finish::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:2389:29
  28: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_peek_finish::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:2371:5
  29: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_peek_begin::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:2275:21
  30: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_peek_begin::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:2198:5
  31: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_plan::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:303:60
  32: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_plan::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:120:5
  33: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute_inner::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:510:78
  34: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute_inner::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:311:5
  35: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:308:61
  36: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:267:5
  37: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  38: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_command::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:72:21
  39: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_command::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:249:33
  40: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_command::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:246:5
  41: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::handle_message::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:44:63
  42: mz_adapter::coord::Coordinator::serve::{{closure}}
             at ./src/adapter/src/coord.rs:1298:37
  43: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:63
  44: tokio::runtime::coop::with_budget
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:102:5
  45: tokio::runtime::coop::budget
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:68:5
  46: tokio::runtime::park::CachedParkThread::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/park.rs:283:31
  47: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/context.rs:315:13
  48: tokio::runtime::handle::Handle::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/handle.rs:264:9
  49: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./src/adapter/src/coord.rs:1477:17
```

**Comment by ggevay** [comment]
@vmarcos FYI.
I added this to https://github.com/MaterializeInc/materialize/issues/17767
