### ISSUE TITLE
test_client_subject_and_references: thread 'test_client_subject_and_references' panicked at 'assertion failed: `(left == right)`

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18269]
### What version of Materialize are you using?

16410a35dd73ccc3e4a97518bf5654db4f8466f8

### How did you install Materialize?

Docker image

### What is the issue?

Seen one time locally, couldn't reproduce:
```
thread 'test_client_subject_and_references' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', src/ccsr/tests/client.rs:212:5
stack backtrace:
   0: rust_begin_unwind
             at /home/deen/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /home/deen/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /home/deen/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:211:5
   4: client::test_client_subject_and_references::{{closure}}
             at ./tests/client.rs:212:5
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/deen/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:125:9
   6: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/scheduler/current_thread.rs:541:57
   7: tokio::runtime::coop::with_budget
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:102:5
   8: tokio::runtime::coop::budget
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/coop.rs:68:5
   9: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/scheduler/current_thread.rs:541:25
  10: tokio::runtime::scheduler::current_thread::Context::enter
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/scheduler/current_thread.rs:350:19
  11: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/scheduler/current_thread.rs:540:36
  12: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/scheduler/current_thread.rs:615:57
  13: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/macros/scoped_tls.rs:61:9
  14: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/scheduler/current_thread.rs:615:27
  15: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/scheduler/current_thread.rs:530:19
  16: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/scheduler/current_thread.rs:154:24
  17: tokio::runtime::runtime::Runtime::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.2/src/runtime/runtime.rs:282:47
  18: client::test_client_subject_and_references
             at ./tests/client.rs:304:5
  19: client::test_client_subject_and_references::{{closure}}
             at ./tests/client.rs:203:50
  20: core::ops::function::FnOnce::call_once
             at /home/deen/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  21: core::ops::function::FnOnce::call_once
             at /home/deen/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
I did run this on https://github.com/MaterializeInc/materialize/pull/17670 with `RUSTFLAGS="-Zsanitizer=thread" cargo nextest run --release -Zbuild-std --target x86_64-unknown-linux-gnu`, but I'm not sure if that matters, since it's not something that thread sanitizer found, maybe just changed the timing slightly.

ci-regexp: thread 'test_client' panicked at src/ccsr/tests/client.rs

**Comment by def-** [comment]
Happening in main again: https://buildkite.com/materialize/tests/builds/69437

**Comment by sploiselle** [comment]
Ran this locally on Rust 1.74 for 10 minutes without a repro.

We've also experienced schema registry client issues in #23359, which I wasn't able to repro locally, either––maybe totally unrelated but odd that these both crept up in the last few days.

**Comment by def-** [comment]
It took about half an hour to repro locally for me. I can also lend my (Linux) machine if it helps.

**Comment by sploiselle** [comment]
@def- Have we encountered this lately?

**Comment by def-** [comment]
I'm not aware, testing it locally now for a few hours and will report back.
