### ISSUE TITLE
[SQLancer] Wrong results with invalid case insensitive regex match in HAVING

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18346]
### What version of Materialize are you using?

v0.48.0-dev (65bdb3389)

### How did you install Materialize?

Built from source

### What is the issue?

Using SQLancer (now in CI), TLP HAVING is now running:
> TLP partitions a query into three partitioning queries, whose results are composed and compare to the original query's result set. A mismatch in the result sets indicates a bug in the DBMS. In contrast to NoREC and PQS, it can detect bugs in advanced features such as aggregate functions.

This is the reproducer:
```
$ cat database2.log
--java.lang.AssertionError: the size of the result sets mismatch (2 and 0)!
---- SELECT 0.97668456902761058291417839427595026791095733642578125 FROM t1 FULL OUTER JOIN t3 ON NOT (((t1.c2) IN (t1.c0)) IS TRUE) GROUP BY t3.c1;
---- cardinality: 2
---- SELECT ALL 0.97668456902761058291417839427595026791095733642578125 FROM t1 FULL OUTER JOIN t3 ON NOT (((t1.c2) IN (t1.c0)) IS TRUE) GROUP BY t3.c1 HAVING MIN((((((t1.c2)::VARCHAR)||(0.6691758566527444)))||((((TRUE) IS TRUE)AND(((FALSE)OR(TRUE))))))!~*'[.');SELECT 0.97668456902761058291417839427595026791095733642578125 FROM t1 FULL OUTER JOIN t3 ON NOT (((t1.c2) IN (t1.c0)) IS TRUE) GROUP BY t3.c1 HAVING NOT (MIN((((((t1.c2)::VARCHAR)||(0.6691758566527444)))||((((TRUE) IS TRUE)AND(((FALSE)OR(TRUE))))))!~*'[.'));SELECT ALL 0.97668456902761058291417839427595026791095733642578125 FROM t1 FULL OUTER JOIN t3 ON NOT (((t1.c2) IN (t1.c0)) IS TRUE) GROUP BY t3.c1 HAVING (MIN(((((CAST(t1.c2 AS VARCHAR))||(0.6691758566527444)))||((((TRUE) IS TRUE)AND(((FALSE)OR(TRUE))))))!~*'[.')) IS NULL;
---- cardinality: 0
--	at sqlancer.ComparatorHelper.assumeResultSetsAreEqual(ComparatorHelper.java:97)
--	at sqlancer.postgres.oracle.tlp.PostgresTLPHavingOracle.havingCheck(PostgresTLPHavingOracle.java:50)
--	at sqlancer.postgres.oracle.tlp.PostgresTLPHavingOracle.check(PostgresTLPHavingOracle.java:25)
--	at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:61)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:364)
--	at sqlancer.Main$2.run(Main.java:559)
--	at sqlancer.Main$2.runThread(Main.java:541)
--	at sqlancer.Main$2.run(Main.java:532)
--	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
--	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
--	at java.base/java.lang.Thread.run(Thread.java:829)
---- Time: 2023/03/22 20:29:06
-- Database: database2
-- Database version: 9.5.0
-- seed value: 1679508437763
\c test;
DROP DATABASE IF EXISTS database2;
CREATE DATABASE database2 ;
\c database2;
CREATE TABLE t0(c0 INT  , c1 FLOAT );
CREATE TABLE IF NOT EXISTS t1(c0 REAL , c1 FLOAT , c2 INT );
CREATE TABLE t2(c0 boolean    );
CREATE TABLE IF NOT EXISTS t3(c0 DECIMAL , c1 INT );
CREATE TABLE IF NOT EXISTS t4(c0 REAL );
UPDATE t0 SET c0=(t0.c0), c1=(((- (t0.c0))-(t0.c0))) WHERE FALSE;
INSERT INTO t3(c0) VALUES(0.81344722053052576082876612417749129235744476318359375);
INSERT INTO t3(c0) VALUES(0.15850484455751578938276225017034448683261871337890625);
DROP INDEX IF EXISTS i0;
INSERT INTO t3(c1, c0) VALUES(893466749, 0.25558159028326610240355876157991588115692138671875);
INSERT INTO t0(c0) VALUES(10069445);
INSERT INTO t4(c0) VALUES(0.5831085950489614);
DELETE FROM t3 WHERE (((((0.9610806)::VARCHAR)||(t3.c1)))LIKE((((FALSE)OR((0.53311515) IN (0.44173023, t3.c1))))::VARCHAR(198)));
DELETE FROM t0;
INSERT INTO t4(c0) VALUES(0.81593620439402);
--INSERT INTO t4(c0) VALUES(- (CAST(+ (((-1895466517)+(-918951149))) AS INT)));
INSERT INTO t2(c0) VALUES(((CAST(((571075739)-(((1675799115)+(-1801155374)))) AS VARCHAR))LIKE(CAST((('0㨜5m秊')||(1493919240))~(('Jrh0')||('x*	')) AS VARCHAR(359)))));
DELETE FROM t2;
SET SESSION statement_timeout = 5000;
SELECT 0.97668456902761058291417839427595026791095733642578125 FROM t1 FULL OUTER JOIN t3 ON NOT (((t1.c2) IN (t1.c0)) IS TRUE) GROUP BY t3.c1; -- cardinality: 2

SELECT ALL 0.97668456902761058291417839427595026791095733642578125 FROM t1 FULL OUTER JOIN t3 ON NOT (((t1.c2) IN (t1.c0)) IS TRUE) GROUP BY t3.c1 HAVING MIN((((((t1.c2)::VARCHAR)||(0.6691758566527444)))||((((TRUE) IS TRUE)AND(((FALSE)OR(TRUE))))))!~*'[.');
SELECT 0.97668456902761058291417839427595026791095733642578125 FROM t1 FULL OUTER JOIN t3 ON NOT (((t1.c2) IN (t1.c0)) IS TRUE) GROUP BY t3.c1 HAVING NOT (MIN((((((t1.c2)::VARCHAR)||(0.6691758566527444)))||((((TRUE) IS TRUE)AND(((FALSE)OR(TRUE))))))!~*'[.'));
SELECT ALL 0.97668456902761058291417839427595026791095733642578125 FROM t1 FULL OUTER JOIN t3 ON NOT (((t1.c2) IN (t1.c0)) IS TRUE) GROUP BY t3.c1 HAVING (MIN(((((CAST(t1.c2 AS VARCHAR))||(0.6691758566527444)))||((((TRUE) IS TRUE)AND(((FALSE)OR(TRUE))))))!~*'[.')) IS NULL;-- cardinality: 0
$ psql postgres://materialize@localhost:6875 -f database2.log
psql (14.7 (Ubuntu 14.7-0ubuntu0.22.10.1), server 9.5.0)
You are now connected to database "test" as user "materialize".
psql:database2.log:22: NOTICE:  session database "test" does not exist
HINT:  Create the database with CREATE DATABASE or pick an extant database with SET DATABASE = name. List available databases with SHOW DATABASES.
DROP DATABASE
CREATE DATABASE
psql (14.7 (Ubuntu 14.7-0ubuntu0.22.10.1), server 9.5.0)
You are now connected to database "database2" as user "materialize".
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
UPDATE 0
INSERT 0 1
INSERT 0 1
DROP INDEX
INSERT 0 1
INSERT 0 1
INSERT 0 1
DELETE 0
DELETE 1
INSERT 0 1
INSERT 0 1
DELETE 1
SET
                 ?column?
-------------------------------------------
 0.976684569027610582914178394275950267911
 0.976684569027610582914178394275950267911
(2 rows)

 ?column?
----------
(0 rows)

 ?column?
----------
(0 rows)

 ?column?
----------
(0 rows)
```
The expectation is that the last 3 queries should together return the same result as the previous query. The 3 queries are the same, except for adding this HAVING part:
```
HAVING MIN((((((t1.c2)::VARCHAR)||(0.6691758566527444)))||((((TRUE) IS TRUE)AND(((FALSE)OR(TRUE))))))!~*'[.') -- true
HAVING NOT (MIN((((((t1.c2)::VARCHAR)||(0.6691758566527444)))||((((TRUE) IS TRUE)AND(((FALSE)OR(TRUE))))))!~*'[.')) -- false
HAVING (MIN(((((CAST(t1.c2 AS VARCHAR))||(0.6691758566527444)))||((((TRUE) IS TRUE)AND(((FALSE)OR(TRUE))))))!~*'[.')) IS NULL -- null
```
Since the queries are covering that predicate is `true`, `false` or `null` respectively, all rows should appear in them. More details in the paper: https://www.manuelrigger.at/preprints/TLP.pdf

The regex `[.` is not even valid, so these queries should probably fail instead of returning an empty result. With a valid regex I am seeing the expected result:
```
SELECT ALL 0.97668456902761058291417839427595026791095733642578125 FROM t1 FULL OUTER JOIN t3 ON NOT (((t1.c2) IN (t1.c0)) IS TRUE) GROUP BY t3.c1 HAVING MIN((((((t1.c2)::VARCHAR)||(0.6691758566527444)))||((((TRUE) IS TRUE)AND(((FALSE)OR(TRUE))))))!~*'.');
SELECT 0.97668456902761058291417839427595026791095733642578125 FROM t1 FULL OUTER JOIN t3 ON NOT (((t1.c2) IN (t1.c0)) IS TRUE) GROUP BY t3.c1 HAVING NOT (MIN((((((t1.c2)::VARCHAR)||(0.6691758566527444)))||((((TRUE) IS TRUE)AND(((FALSE)OR(TRUE))))))!~*'.'));
SELECT ALL 0.97668456902761058291417839427595026791095733642578125 FROM t1 FULL OUTER JOIN t3 ON NOT (((t1.c2) IN (t1.c0)) IS TRUE) GROUP BY t3.c1 HAVING (MIN(((((CAST(t1.c2 AS VARCHAR))||(0.6691758566527444)))||((((TRUE) IS TRUE)AND(((FALSE)OR(TRUE))))))!~*'.')) IS NULL;
```
```
 ?column?
----------
(0 rows)

 ?column?
----------
(0 rows)

                 ?column?
-------------------------------------------
 0.976684569027610582914178394275950267911
 0.976684569027610582914178394275950267911
(2 rows)
```

**Comment by def-** [comment]
Today's nightly brought up another instance of this, can happen with any kind of failing expression apparently, in this case a `numeric field overflow` in the multiplication. This should be the same issue, I'll just post it here anyway so once this is fixed we can verify that this scenario is fine too:

<details>

```
--- [SQLancer] the size of the result sets mismatch (1 and 0)!
---- SELECT -1360580290 FROM t1 LEFT OUTER JOIN t4 ON t1.c0!~t1.c0 GROUP BY t1.c0!~*t1.c0;
---- cardinality: 1
---- SELECT ALL -1360580290 FROM t1 LEFT OUTER JOIN t4 ON t1.c0!~t1.c0 GROUP BY t1.c0!~*t1.c0 HAVING BOOL_AND(NOT ((((-1069180097)*(-992363836))) IN (t4.c0))) UNION ALL SELECT ALL -1360580290 FROM t1 LEFT OUTER JOIN t4 ON t1.c0!~t1.c0 GROUP BY t1.c0!~*t1.c0 HAVING NOT (BOOL_AND(NOT ((((-1069180097)*(-992363836))) IN (t4.c0)))) UNION ALL SELECT -1360580290 FROM t1 LEFT OUTER JOIN t4 ON t1.c0!~t1.c0 GROUP BY t1.c0!~*t1.c0 HAVING (BOOL_AND(NOT ((((-1069180097)*(-992363836))) IN (t4.c0)))) IS NULL;
---- cardinality: 0
--	at sqlancer.ComparatorHelper.assumeResultSetsAreEqual(ComparatorHelper.java:97)
--	at sqlancer.postgres.oracle.tlp.PostgresTLPHavingOracle.havingCheck(PostgresTLPHavingOracle.java:50)
--	at sqlancer.postgres.oracle.tlp.PostgresTLPHavingOracle.check(PostgresTLPHavingOracle.java:25)
--	at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:61)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:364)
--	at sqlancer.Main$2.run(Main.java:559)
--	at sqlancer.Main$2.runThread(Main.java:541)
--	at sqlancer.Main$2.run(Main.java:532)
--	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
--	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
--	at java.base/java.lang.Thread.run(Thread.java:829)
--
-- Time: 2023/03/23 00:39:10
-- Database: database0
-- Database version: 9.5.0
-- seed value: 501225062
\c test;
DROP DATABASE IF EXISTS database0;
CREATE DATABASE database0 ;
\c database0;
CREATE TABLE IF NOT EXISTS t0(c0 FLOAT   , c1 DECIMAL     DEFAULT (0.0569982301164875249099850407219491899013519287109375));
CREATE TABLE IF NOT EXISTS t1(c0 VARCHAR(270)  );
CREATE TABLE t2(c0 smallint , c1 REAL );
CREATE TABLE t3(c0 boolean  );
CREATE TABLE t4(c0 FLOAT , c1 REAL );
INSERT INTO t1(c0) VALUES('Zg');
DROP INDEX IF EXISTS i2;
UPDATE t2 SET c0=-420767391 WHERE (((- (t2.c0))<(t2.c0))) IS UNKNOWN;
INSERT INTO t1(c0) VALUES('pb|}%X^');
INSERT INTO t4(c1, c0) VALUES(0.19303538852602553, 0.45628047);
DELETE FROM t4;
INSERT INTO t0(c0, c1) VALUES(0.7476933, 0.96875483195170219996583682586788199841976165771484375);
UPDATE t1 SET c0='' WHERE (t1.c0) BETWEEN (t1.c0) AND ('');
INSERT INTO t4(c0, c1) VALUES(0.70185995, 0.8474063787096989);
INSERT INTO t3(c0) VALUES(NOT (NOT ((((-1694898164)%(1694175238)) != 0))));
INSERT INTO t2(c0, c1) VALUES(-271304916, 0.8733818223902593);
INSERT INTO t2(c0) VALUES(589229004);
INSERT INTO t1(c0) VALUES('QU');
INSERT INTO t0(c1) VALUES(0.75345931629461537770708901007310487329959869384765625), (0.633873683059574144493808489642105996608734130859375), (0.4269581501971109194215614479617215692996978759765625);
INSERT INTO t2(c0) VALUES(-1826296804);
INSERT INTO t0(c0) VALUES(3.27907456E8);
UPDATE t2 SET c0=(t2.c0), c1=(0.1972119989463781) WHERE ((0.2771768)>(5.26198392E8));
CREATE INDEX i0 ON t4(c0, c0 ASC);
UPDATE t2 SET c1=(t2.c0), c0=-538040981 WHERE ((((((t2.c0) BETWEEN (t2.c0) AND (t2.c0))AND(((t2.c0)<(t2.c0)))))::VARCHAR(880))LIKE((((t2.c0)*(t2.c0)))::VARCHAR(599)));
CREATE INDEX i0 ON t0(c1 ASC);
CREATE INDEX i0 ON t2(c0);
CREATE INDEX i0 ON t0(c1 ASC);
CREATE INDEX i0 ON t1(c0);
CREATE INDEX i0 ON t0(c0);
CREATE INDEX i1 ON t4(c1 NULLS LAST, c0);
UPDATE t1 SET c0=(t1.c0) WHERE NOT ((0.31050213315419739057432479967246763408184051513671875) IN (0.00033445396349274236769133494817651808261871337890625));
INSERT INTO t0(c0, c1) VALUES(0.063381135, 0.52166326819447927931605590856634080410003662109375), (0.31192216, 0.7071824004298310484273315523751080036163330078125), (9.4953293E8, 0.27848561162209628516706061418517492711544036865234375);
INSERT INTO t1(c0) VALUES('''%');
INSERT INTO t4(c0) VALUES(0.5660831), (0.8632238), (0.60371774);
INSERT INTO t4(c0, c1) VALUES(+ (+ (- (- (2078941054)))), 0.31490633670396684);
INSERT INTO t4(c0, c1) VALUES(-1.39614886E9, 0.09771927574750461);
DROP INDEX IF EXISTS i2 CASCADE;
INSERT INTO t0(c1) VALUES(0.8418467342223621141528155931155197322368621826171875);
COMMIT;
SET SESSION statement_timeout = 5000;
SELECT -1360580290 FROM t1 LEFT OUTER JOIN t4 ON t1.c0!~t1.c0 GROUP BY t1.c0!~*t1.c0;-- cardinality: 1
SELECT ALL -1360580290 FROM t1 LEFT OUTER JOIN t4 ON t1.c0!~t1.c0 GROUP BY t1.c0!~*t1.c0 HAVING BOOL_AND(NOT ((((-1069180097)*(-992363836))) IN (t4.c0))) UNION ALL SELECT ALL -1360580290 FROM t1 LEFT OUTER JOIN t4 ON t1.c0!~t1.c0 GROUP BY t1.c0!~*t1.c0 HAVING NOT (BOOL_AND(NOT ((((-1069180097)*(-992363836))) IN (t4.c0)))) UNION ALL SELECT -1360580290 FROM t1 LEFT OUTER JOIN t4 ON t1.c0!~t1.c0 GROUP BY t1.c0!~*t1.c0 HAVING (BOOL_AND(NOT ((((-1069180097)*(-992363836))) IN (t4.c0)))) IS NULL;-- cardinality: 0;
```

</details>

By changing the `!~*` and `!~` in the final query to `=`, it gets the correct error:
```
psql:sqlancer.sql:67: ERROR:  Evaluation error: numeric field overflow
```

**Comment by philip-stoev** [comment]
My comment above explains the `MIN ... IS NULL` query from the initial report (the third query). The results from the first/second query are due to a related situation:

```
DROP TABLE IF EXISTS t1;
DROP TABLE IF EXISTS t2;
CREATE TABLE t1 (f1 STRING);
INSERT INTO t1 VALUES ('a');
CREATE TABLE t2 (f1 STRING);
SELECT 1 FROM t1 LEFT JOIN t2 ON TRUE GROUP BY t2.f1 HAVING MIN(t2.f1~*'[.'); 
```

Both the `HAVING MIN...` and the `HAVING NOT MIN` queries return no rows. The reason is that the optimizer uses the `HAVING` condition to infer that `t2.f1` must always be non-null and thus the LEFT JOIN into a CROSS JOIN that returns no rows for the inputs in question without evaluating the regexp altogether. If the cross join produced any inputs, an error would have been returned to the user:

```
 Explained Query:                                                    +
   Project (#1)                                                      +
     Map (1)                                                         +
       Distinct group_by=[#0]                                        +
         Filter error("invalid regular expression: regex parse error:+
     [.                                                              +
     ^                                                               +
 error: unclosed character class")                                   +
           CrossJoin type=differential                               +
             ArrangeBy keys=[[]]                                     +
               Project ()                                            +
                 Get materialize.public.t1                           +
             ArrangeBy keys=[[]]                                     +
               Get materialize.public.t2                             +
```

**Comment by ggevay** [comment]
I added this to https://github.com/MaterializeInc/materialize/issues/17189

**Comment by def-** [comment]
This keeps popping up in other checks too, not so easy to fix all of them in SQLancer to ignore this:
```sql
--java.lang.AssertionError: the size of the result sets mismatch (72 and 36)!
---- SELECT t2.c0 FROM t4, t1, t0 FULL OUTER JOIN t2 ON (t4.c0) ISNULL INNER JOIN t3 ON ((('|X)]#r2eC')||(t4.c0))~*(('()')||('#R'))) IN (t4.c0);
---- cardinality: 72
---- SELECT ALL t2.c0 FROM t4, t1, t0 FULL OUTER JOIN t2 ON (t4.c0) ISNULL JOIN t3 ON ((('|X)]#r2eC')||(t4.c0))~*(('()')||('#R'))) IN (t4.c0) WHERE t4.c0 UNION ALL SELECT t2.c0 FROM t4, t1, t0 FULL OUTER JOIN t2 ON (t4.c0) ISNULL INNER JOIN t3 ON ((('|X)]#r2eC')||(t4.c0))~*(('()')||('#R'))) IN (t4.c0) WHERE NOT (t4.c0) UNION ALL SELECT t2.c0 FROM t4, t1, t0 FULL OUTER JOIN t2 ON (t4.c0) ISNULL INNER JOIN t3 ON ((('|X)]#r2eC')||(t4.c0))~*(('()')||('#R'))) IN (t4.c0) WHERE (t4.c0) ISNULL;
---- cardinality: 36
--	at sqlancer.ComparatorHelper.assumeResultSetsAreEqual(ComparatorHelper.java:97)
--	at sqlancer.materialize.oracle.tlp.MaterializeTLPWhereOracle.whereCheck(MaterializeTLPWhereOracle.java:44)
--	at sqlancer.materialize.oracle.tlp.MaterializeTLPWhereOracle.check(MaterializeTLPWhereOracle.java:23)
--	at sqlancer.common.oracle.CompositeTestOracle.check(CompositeTestOracle.java:22)
--	at sqlancer.ProviderAdapter.generateAndTestDatabaseWithQueryPlanGuidance(ProviderAdapter.java:132)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:362)
--	at sqlancer.Main$2.run(Main.java:559)
--	at sqlancer.Main$2.runThread(Main.java:541)
--	at sqlancer.Main$2.run(Main.java:532)
--	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
--	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
--	at java.base/java.lang.Thread.run(Thread.java:829)
---- Time: 2023/04/22 00:35:11
-- Database: database2
-- Database version: 9.5.0
-- seed value: 1682111465115
\c test;
DROP DATABASE IF EXISTS database2;
CREATE DATABASE database2 ;
\c database2;
CREATE TABLE t0(c0 bigint );
CREATE TABLE IF NOT EXISTS t1(c0 INT );
CREATE TABLE IF NOT EXISTS t2(c0 integer );
CREATE TABLE IF NOT EXISTS t3(c0 DECIMAL  DEFAULT (0.47194443805431996));
CREATE TABLE t4(c0 boolean  DEFAULT (NOT ((FALSE) IS FALSE)));
INSERT INTO t3(c0) VALUES(0.8098452234111818);
INSERT INTO t3(c0) VALUES(0.41275782219621193);
INSERT INTO t3(c0) VALUES(0.9418289205880201);
INSERT INTO t3(c0) VALUES(0.7543616821346024);
INSERT INTO t4(c0) VALUES(FALSE);
INSERT INTO t4(c0) VALUES(TRUE);
INSERT INTO t3(c0) VALUES(0.8792753497897587);
INSERT INTO t2(c0) VALUES(794420173);
INSERT INTO t0(c0) VALUES(-2098953076);
INSERT INTO t0(c0) VALUES(-478000933);
INSERT INTO t3(c0) VALUES(0.24414520648717963);
UPDATE t4 SET c0=(t4.c0) WHERE t4.c0;
INSERT INTO t4(c0) VALUES(FALSE);
INSERT INTO t2(c0) VALUES(1841413537);
INSERT INTO t1(c0) VALUES(-204180994);
INSERT INTO t1(c0) VALUES(72244147);
INSERT INTO t2(c0) VALUES(-1187398499);
UPDATE t3 SET c0=0.3621737480453304 WHERE (((t3.c0)<(t3.c0))) IS NOT UNKNOWN;
DELETE FROM t0;
UPDATE t1 SET c0=-478000933 WHERE (0.4046321478983824) IN (NULL);
COMMIT;
SET SESSION statement_timeout = 5000;
SELECT t2.c0 FROM t4, t1, t0 FULL OUTER JOIN t2 ON (t4.c0) ISNULL INNER JOIN t3 ON ((('|X)]#r2eC')||(t4.c0))~*(('()')||('#R'))) IN (t4.c0);-- cardinality: 72
SELECT ALL t2.c0 FROM t4, t1, t0 FULL OUTER JOIN t2 ON (t4.c0) ISNULL JOIN t3 ON ((('|X)]#r2eC')||(t4.c0))~*(('()')||('#R'))) IN (t4.c0) WHERE t4.c0 UNION ALL SELECT t2.c0 FROM t4, t1, t0 FULL OUTER JOIN t2 ON (t4.c0) ISNULL INNER JOIN t3 ON ((('|X)]#r2eC')||(t4.c0))~*(('()')||('#R'))) IN (t4.c0) WHERE NOT (t4.c0) UNION ALL SELECT t2.c0 FROM t4, t1, t0 FULL OUTER JOIN t2 ON (t4.c0) ISNULL INNER JOIN t3 ON ((('|X)]#r2eC')||(t4.c0))~*(('()')||('#R'))) IN (t4.c0) WHERE (t4.c0) ISNULL;-- cardinality: 36;
```
For further testing it would be helpful if this could be fixed.
