### ISSUE TITLE
regression: persist_sink(u1370): invalid upper! Tried to append batch

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#18378]
### What version of Materialize are you using?

f702792

### How did you install Materialize?

Docker image

### What is the issue?

Testdrive with SIZE 8 and Testdrive with 5 partitions by default fail as follows:

```
testdrive-materialized-1     | thread 'timely:work-0' panicked at 'persist_sink(u1357): invalid upper! Tried to append batch (Antichain { elements: [1679617149001] } -> Antichain { elements: [1679617150001] }) but upper is Antichain { elements: [] }. This is not a problem, it just means someone else was faster than us. We will try again with a new batch description.', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-083fc44efe15f5bd4-1/materialize/tests/src/storage/src/render/multi_worker_persist_sink.rs:1111:25
```

https://buildkite.com/materialize/nightlies/builds/2058#018710d6-3431-4191-bf84-0f23d5c18cc5

### Relevant log output

```source
estdrive-materialized-1     |    0: rust_begin_unwind
testdrive-materialized-1     |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
testdrive-materialized-1     |    1: core::panicking::panic_fmt
testdrive-materialized-1     |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
testdrive-materialized-1     |    2: mz_storage::render::multi_worker_persist_sink::append_batches::<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>>::{closure#2}::{closure#0}
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-083fc44efe15f5bd4-1/materialize/tests/src/storage/src/render/multi_worker_persist_sink.rs:1111:25
testdrive-materialized-1     |    3: <core::pin::Pin<alloc::boxed::Box<mz_storage::render::multi_worker_persist_sink::append_batches<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>>::{closure#2}::{closure#0}>> as core::future::future::Future>::poll
testdrive-materialized-1     |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/future/future.rs:124:9
testdrive-materialized-1     |    4: <mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>>>::build::<mz_storage::render::multi_worker_persist_sink::append_batches<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>>::{closure#2}, mz_storage::render::multi_worker_persist_sink::append_batches<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>>::{closure#2}::{closure#0}>::{closure#0}::{closure#0}
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-083fc44efe15f5bd4-1/materialize/tests/src/timely-util/src/builder_async.rs:501:28
testdrive-materialized-1     |    5: <timely::dataflow::operators::generic::builder_rc::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>>>::build_reschedule::<<mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>>>::build<mz_storage::render::multi_worker_persist_sink::append_batches<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>>::{closure#2}, mz_storage::render::multi_worker_persist_sink::append_batches<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>>::{closure#2}::{closure#0}>::{closure#0}, <mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>>>::build<mz_storage::render::multi_worker_persist_sink::append_batches<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>>::{closure#2}, mz_storage::render::multi_worker_persist_sink::append_batches<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>>::{closure#2}::{closure#0}>::{closure#0}::{closure#0}>::{closure#0}
testdrive-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/operators/generic/builder_rc.rs:172:26
testdrive-materialized-1     |    6: <timely::dataflow::operators::generic::builder_raw::OperatorCore<mz_repr::timestamp::Timestamp, <timely::dataflow::operators::generic::builder_rc::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>>>::build_reschedule<<mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>>>::build<mz_storage::render::multi_worker_persist_sink::append_batches<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>>::{closure#2}, mz_storage::render::multi_worker_persist_sink::append_batches<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>>::{closure#2}::{closure#0}>::{closure#0}, <mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>>>::build<mz_storage::render::multi_worker_persist_sink::append_batches<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>>::{closure#2}, mz_storage::render::multi_worker_persist_sink::append_batches<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>>::{closure#2}::{closure#0}>::{closure#0}::{closure#0}>::{closure#0}> as timely::scheduling::Schedule>::schedule
testdrive-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/dataflow/operators/generic/builder_raw.rs:204:9
testdrive-materialized-1     |    7: <timely::progress::subgraph::PerOperatorState<mz_repr::timestamp::Timestamp>>::schedule
testdrive-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:699:30
testdrive-materialized-1     |    8: <timely::progress::subgraph::Subgraph<(), mz_repr::timestamp::Timestamp>>::activate_child
testdrive-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:346:26
testdrive-materialized-1     |    9: <timely::progress::subgraph::Subgraph<(), mz_repr::timestamp::Timestamp> as timely::scheduling::Schedule>::schedule
testdrive-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:312:17
testdrive-materialized-1     |   10: <timely::progress::subgraph::PerOperatorState<()>>::schedule
testdrive-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:699:30
testdrive-materialized-1     |   11: <timely::progress::subgraph::Subgraph<(), ()>>::activate_child
testdrive-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:346:26
testdrive-materialized-1     |   12: <timely::progress::subgraph::Subgraph<(), ()> as timely::scheduling::Schedule>::schedule
testdrive-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/progress/subgraph.rs:312:17
testdrive-materialized-1     |   13: <timely::worker::Wrapper>::step::{closure#0}
testdrive-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/worker.rs:754:57
testdrive-materialized-1     |   14: <core::option::Option<&mut alloc::boxed::Box<dyn timely::scheduling::Schedule>>>::map::<bool, <timely::worker::Wrapper>::step::{closure#0}>
testdrive-materialized-1     |              at ./rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/option.rs:925:29
testdrive-materialized-1     |   15: <timely::worker::Wrapper>::step
testdrive-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/worker.rs:754:26
testdrive-materialized-1     |   16: <timely::worker::Worker<timely_communication::allocator::generic::Generic>>::step_or_park
testdrive-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/worker.rs:396:38
testdrive-materialized-1     |   17: <mz_storage::storage_state::Worker<timely_communication::allocator::generic::Generic>>::run_client
testdrive-materialized-1     |   18: <mz_storage::storage_state::Worker<timely_communication::allocator::generic::Generic>>::run
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-083fc44efe15f5bd4-1/materialize/tests/src/storage/src/storage_state.rs:411:21
testdrive-materialized-1     |   19: <mz_storage::server::Config as mz_cluster::types::AsRunnableWorker<mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>>::build_and_run::<timely_communication::allocator::generic::Generic>
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-083fc44efe15f5bd4-1/materialize/tests/src/storage/src/server.rs:105:9
testdrive-materialized-1     |   20: <mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse, std::thread::Thread>, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>, mz_storage::server::Config, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>>::build_timely::{closure#0}::{closure#1}
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-083fc44efe15f5bd4-1/materialize/tests/src/cluster/src/server.rs:178:13
testdrive-materialized-1     |   21: timely::execute::execute_from::<timely_communication::allocator::generic::GenericBuilder, (), <mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse, std::thread::Thread>, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>, mz_storage::server::Config, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>>::build_timely::{closure#0}::{closure#1}>::{closure#0}
testdrive-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/timely/src/execute.rs:388:22
testdrive-materialized-1     |   22: timely_communication::initialize::initialize_from::<timely_communication::allocator::generic::GenericBuilder, (), timely::execute::execute_from<timely_communication::allocator::generic::GenericBuilder, (), <mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse, std::thread::Thread>, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>, mz_storage::server::Config, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>>::build_timely::{closure#0}::{closure#1}>::{closure#0}>::{closure#0}
testdrive-materialized-1     |              at ./cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/f2ea960/communication/src/initialize.rs:316:33
```

**Comment by philip-stoev** [comment]
Bisection is convering to 
```
commit 94801732b9d03f0351d2dbf7cb6e6c54e256cc35
Author: Sean Loiselle <sean@materialize.io>
Date:   Tue Jan 24 15:53:06 2023 -0500

    storage: finalize persist shards when their collections drop

 src/storage-client/src/controller.rs | 47 ++++++++++++++++++++++++++++++++++++++++-------
 1 file changed, 40 insertions(+), 7 deletions(-)
```

No other commit in the current range appears relevant:

```
pstoev@Ubuntu-2004-focal-64-minimal:~/materialize-bisect$ git bisect log
git bisect start '--first-parent'
# status: waiting for both good and bad commits
# bad: [b868c109f49e1f02a5fb97872db5007626a143e6] Merge pull request #18359 from tokenrove/julian/coverage-for-clusterd
git bisect bad b868c109f49e1f02a5fb97872db5007626a143e6
# status: waiting for good commit(s), bad commit known
# bad: [f7027928ef46c7b423800fb13a98b75883c2e6d2] Merge pull request #18372 from jseldess/fix-link-in-developer-readme
git bisect bad f7027928ef46c7b423800fb13a98b75883c2e6d2
# status: waiting for good commit(s), bad commit known
# good: [c5f1b781184e13b9d91c1944c848bfdc4705c790] Merge pull request #18351 from def-/pr-sqlancer-having
git bisect good c5f1b781184e13b9d91c1944c848bfdc4705c790
# bad: [ea51c1ae280372b55f72d377e3d6107ba68466e5] Merge pull request #18349 from MaterializeInc/scheduler_name_arg
git bisect bad ea51c1ae280372b55f72d377e3d6107ba68466e5
# good: [60f47b7d1a4dbbdad7aba46c663eaa9cdb775365] Remove persisted introspection sources
git bisect good 60f47b7d1a4dbbdad7aba46c663eaa9cdb775365
```

**Comment by philip-stoev** [comment]
@sploiselle FYI

**Comment by philip-stoev** [comment]
Slack thread https://materializeinc.slack.com/archives/CTESPM7FU/p1679661116842569
