### ISSUE TITLE
[SQLancer] Wrong result

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18411]
### What version of Materialize are you using?

v0.48.0-dev (f7027928e)

### How did you install Materialize?

Built from source

### What is the issue?

```
--java.lang.AssertionError: the counts mismatch (0 and 3)!
---- SELECT t0.c0 FROM t0 WHERE NOT ((CAST(t0.c0 AS INT) != 0));
---- count: 0
---- SELECT SUM(count) FROM (SELECT (NOT ((CAST(t0.c0 AS INT) != 0)))::INT as count FROM t0) as res;
---- count: 3
--	at sqlancer.postgres.oracle.PostgresNoRECOracle.check(PostgresNoRECOracle.java:73)
--	at sqlancer.ProviderAdapter.generateAndTestDatabaseWithQueryPlanGuidance(ProviderAdapter.java:132)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:362)
--	at sqlancer.Main$2.run(Main.java:559)
--	at sqlancer.Main$2.runThread(Main.java:541)
--	at sqlancer.Main$2.run(Main.java:532)
--	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
--	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
--	at java.base/java.lang.Thread.run(Thread.java:829)
---- Time: 2023/03/26 21:54:32
-- Database: norec6
-- Database version: 9.5.0
-- seed value: 1679698169097
DROP DATABASE IF EXISTS wrong2;
CREATE DATABASE wrong2;
\c wrong2;
CREATE TABLE IF NOT EXISTS t0(c0 FLOAT    DEFAULT (-2144522625));
CREATE TABLE t1(c0 INT    );
CREATE TABLE IF NOT EXISTS t2(c0 REAL  , c1 boolean , c2 boolean  DEFAULT (NOT ((((0.6027531828706163) IN (0.5400584965738747, 0.3460258957071094, 0.7037548775334533))OR((((FALSE) BETWEEN (FALSE) AND (TRUE))OR((('')LIKE('1791898004'))))))))  );
CREATE TABLE t3(c0 INT  );
UPDATE t3 SET c0=-1658413674 WHERE NOT (((t3.c0)!=(t3.c0)));
CREATE INDEX t0i0 ON t0(c0);
INSERT INTO t0(c0) VALUES(0.19388166);
INSERT INTO t2(c1, c2, c0) VALUES((- (- (- (1773641034)))) BETWEEN (1089157376) AND (0.8433427596919189), FALSE, 0.64256245);
DROP INDEX IF EXISTS t1i0, t1i0 CASCADE;
INSERT INTO t0(c0) VALUES(0.9924859);
INSERT INTO t3(c0) VALUES(1774018282);
INSERT INTO t1(c0) VALUES(-375504097);
DELETE FROM t3;
UPDATE t1 SET c0=(t1.c0) WHERE (0.50318055604694666982368289609439671039581298828125 != 0);
INSERT INTO t0(c0) VALUES(0.22149852), (-1.81686541E9), (-1.48970419E9);
DROP INDEX IF EXISTS t0i0;
DROP INDEX IF EXISTS t3i0;
INSERT INTO t0(c0) VALUES(0.45722908);
INSERT INTO t1(c0) VALUES(1487142088);
CREATE INDEX t0i0 ON t0(c0, c0 ASC NULLS FIRST);
INSERT INTO t2(c2, c0) VALUES(('S81!8俱*'!~*(((2048026239)::VARCHAR)||(NOT (FALSE)))) IS FALSE, -1.359015836E9);
INSERT INTO t0(c0) VALUES(-1.37480768E9), (0.5451994), (0.619936);
CREATE MATERIALIZED VIEW v0(c0) AS (SELECT t2.c1 FROM t1, t0, t2 WHERE t2.c2 LIMIT 6495925019325791466 OFFSET 6170769023984365695);
INSERT INTO t0(c0) VALUES(1.7740183E9);
INSERT INTO t2(c2) VALUES(TRUE);
INSERT INTO t0(c0) VALUES(0.52652276);
INSERT INTO t0(c0) VALUES(0.8327617);
COMMIT;
SET SESSION statement_timeout = 5000;\n;
CREATE INDEX t2i0 ON t2(c2);
COMMIT;
DROP INDEX IF EXISTS t0i0, t0i2 RESTRICT;
DELETE FROM t2;
CREATE INDEX t2i1 ON t2(c2, c2 DESC);
UPDATE t0 SET c0=(t0.c0) WHERE ((((0.35829296177793957)::VARCHAR~*'fz7')AND(((((((''!~*'Tu3\rZ*\ro')AND((-2134232516) BETWEEN (t0.c0) AND (361832142))))AND('i!'!~'?')))AND(((TRUE)AND(TRUE))))))) IS NOT UNKNOWN;
DROP INDEX IF EXISTS t0i0, t0i0 CASCADE;
CREATE INDEX t0i0 ON t0(c0);
SELECT t0.c0 FROM t0 WHERE NOT ((CAST(t0.c0 AS INT) != 0));-- count: 0
SELECT SUM(count) FROM (SELECT (NOT ((CAST(t0.c0 AS INT) != 0)))::INT as count FROM t0) as res;-- count: 3
```
The idea of this NoREC check is that both queries should have the same result, but the second query is harder to optimize.
The subquery `SELECT (NOT ((CAST(t0.c0 AS INT) != 0)))::INT as count FROM t0` shows 3 rows with value 1, which seems correct, since 3 values are between 0 and 0.5:
```
wrong2=> SELECT t0.c0, (NOT ((CAST(t0.c0 AS INT) != 0)))::INT as count FROM t0;
     c0      | count
-------------+-------
 -1374807680 |     0
  1774018300 |     0
 -1489704190 |     0
 -1816865410 |     0
    0.619936 |     0
   0.8327617 |     0
   0.9924859 |     0
  0.22149852 |     1
  0.19388166 |     1
  0.45722908 |     1
  0.52652276 |     0
   0.5451994 |     0
(12 rows)
```
These values are lost in the first query though `SELECT t0.c0 FROM t0 WHERE NOT ((CAST(t0.c0 AS INT) != 0))`
Since this also involves a float to int cast, this could have the same root cause as https://github.com/MaterializeInc/materialize/issues/18410 If someone from compute team can confirm, we can close this as a duplicate.

**Comment by def-** [comment]
Same root cause as https://github.com/MaterializeInc/materialize/issues/18410, verified that it's fixed now.
