### ISSUE TITLE
[SQLsmith] ERROR:  Invalid data in source errors, saw retractions (36) for row that does not exist: Evaluation error: internal error: Negative multiplicities in TopK

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18645]
### What version of Materialize are you using?

v0.50.0-dev (b70288064)

### How did you install Materialize?

Built from source

### What is the issue?

Reproducer:
```
  CREATE SOURCE tpch
    FROM LOAD GENERATOR TPCH (SCALE FACTOR 0.00001)
    FOR ALL TABLES
    WITH (SIZE = '1');

  CREATE SOURCE auction
    FROM LOAD GENERATOR AUCTION (SCALE FACTOR 0.01)
    FOR ALL TABLES
    WITH (SIZE = '1');

  CREATE SOURCE counter
    FROM LOAD GENERATOR COUNTER (SCALE FACTOR 0.0001)
    WITH (SIZE = '1');

select  
  subq_3."c9" as c0, 
  case when cast(coalesce(cast(null as char),
        cast(null as char)) as char) >= case when cast(null as bpchar) !~ subq_3."c2" then cast(null as char) else cast(null as char) end
         then subq_3."c8" else subq_3."c8" end
     as c1, 
  mz_catalog.mz_version() as c2, 
  case when pg_catalog.mod(
        CAST((select "id" from mz_internal.mz_sessions limit 1 offset 4)
           as uint4),
        CAST(cast(nullif((select "id" from mz_internal.mz_sessions limit 1 offset 1)
            ,
          (select pg_catalog.min("id") from mz_internal.mz_sessions)
            ) as uint4) as uint4)) > (select "id" from mz_internal.mz_sessions limit 1 offset 24)
         then subq_3."c6" else subq_3."c6" end
     as c3, 
  subq_3."c1" as c4, 
  subq_3."c8" as c5, 
  subq_3."c5" as c6, 
  subq_3."c13" as c7, 
  subq_3."c6" as c8, 
  subq_3."c4" as c9, 
  subq_3."c0" as c10, 
  subq_3."c2" as c11, 
  subq_3."c0" as c12, 
  pg_catalog.pg_postmaster_start_time() as c13, 
  subq_3."c4" as c14, 
  subq_3."c5" as c15, 
  subq_3."c8" as c16, 
  pg_catalog.jsonb_build_array() as c17, 
  subq_3."c1" as c18
from 
  (select  
        subq_0."c0" as c0, 
        subq_0."c4" as c1, 
        subq_0."c4" as c2, 
        subq_2."c0" as c3, 
        subq_0."c4" as c4, 
        subq_2."c4" as c5, 
        subq_0."c2" as c6, 
        case when cast(null as uuid) = cast(null as uuid) then subq_0."c5" else subq_0."c5" end
           as c7, 
        case when subq_2."c4" is NULL then subq_2."c4" else subq_2."c4" end
           as c8, 
        case when (select "last_status_change_at" from mz_internal.mz_source_statuses limit 1 offset 6)
               = (select "rolvaliduntil" from pg_catalog.pg_roles limit 1 offset 53)
               then subq_2."c1" else subq_2."c1" end
           as c9, 
        subq_2."c0" as c10, 
        (select pg_catalog.var_pop("typlen") from pg_catalog.pg_type)
           as c11, 
        subq_2."c1" as c12, 
        31 as c13, 
        subq_2."c4" as c14, 
        pg_catalog.session_user() as c15, 
        subq_2."c1" as c16, 
        subq_2."c3" as c17
      from 
        (select  
              ref_0."worker_id" as c0, 
              ref_0."time" as c1, 
              ref_0."port" as c2, 
              ref_0."port" as c3, 
              ref_0."update_type" as c4, 
              ref_0."address" as c5
            from 
              mz_internal.mz_dataflow_operator_reachability_raw as ref_0
            where ref_0."worker_id" is not NULL
            limit 106) as subq_0,
        lateral (select  
              (select mz_catalog.list_agg("shard_id") from mz_internal.mz_storage_shards)
                 as c0, 
              subq_1."c9" as c1, 
              subq_1."c5" as c2, 
              subq_0."c5" as c3, 
              (select pg_catalog.var_samp("amount") from public.bids)
                 as c4
            from 
              (select  
                    subq_0."c4" as c0, 
                    (select pg_catalog.jsonb_agg("time") from mz_internal.mz_compute_frontiers)
                       as c1, 
                    ref_1."operator_id" as c2, 
                    ref_1."operator_id" as c3, 
                    subq_0."c4" as c4, 
                    subq_0."c0" as c5, 
                    subq_0."c0" as c6, 
                    ref_1."worker_id" as c7, 
                    subq_0."c4" as c8, 
                    ref_1."worker_id" as c9, 
                    ref_1."operator_id" as c10, 
                    ref_1."operator_id" as c11
                  from 
                    mz_internal.mz_arrangement_sharing_raw as ref_1
                  where true
                  limit 65) as subq_1
            where true
            limit 105) as subq_2
      where subq_0."c4" is not NULL) as subq_3
where case when subq_3."c3" is not NULL then subq_3."c2" else subq_3."c2" end
     !~~ subq_3."c4";
```
The query is a bit annoying to make smaller since the error message is not always the exact same, I'll try to find a way to reduce it.

**Comment by tokenrove** [comment]
Is it possible to reproduce with something that doesn't hit https://github.com/MaterializeInc/materialize/issues/18296 ?

**Comment by def-** [comment]
I'm not sure how to tell if it's the same issue.

**Comment by vmarcos** [comment]
The uncertainty in the queries in the build logs is that they are all using an `mz_dataflow_operator_reachability*` introspection view/source. All of these generate retractions (see https://github.com/MaterializeInc/materialize/issues/17874#issuecomment-1500286436). So I would call this issue a duplicate of #18296 except if we can reproduce without a reachability relation.

The query above also uses `mz_sessions`, but the invalid retraction bug on that relation (https://github.com/MaterializeInc/materialize/issues/18607) got fixed by https://github.com/MaterializeInc/materialize/pull/18611.

@def- Perhaps it would be a good idea to ban all `mz_dataflow_operator_reachability*` from the set of relations SQLsmith is picking up for fuzzing until #18296 is fixed? I think it may take a bit of time for us to devise a fix to that one.

**Comment by def-** [comment]
@vmarcos Is it possible `mz_scheduling_elapsed_raw` is also affected? Seen again with a query containing it: 
```
--- [SQLsmith] Error XX000: ERROR:  Invalid data in source errors, saw retractions (85) for row that does not exist: Evaluation error: internal error: Negative multiplicities in TopK

Query: select  
  mz_catalog.mz_uptime() as c0, 
  pg_catalog.jsonb_build_array() as c1, 
  subq_2."c5" as c2, 
  28 as c3, 
  subq_2."c5" as c4, 
  subq_2."c2" as c5, 
  pg_catalog.now() as c6, 
  mz_internal.is_rbac_enabled() as c7, 
  subq_2."c4" as c8, 
  subq_2."c3" as c9, 
  pg_catalog.uuid_generate_v5(
    CAST((select "id" from mz_internal.mz_active_peeks_per_worker limit 1 offset 4)
       as uuid),
    CAST(pg_catalog.array_to_string(
      array[null, null],
      CAST(subq_2."c1" as text),
      CAST(subq_2."c1" as text)) as text)) as c10, 
  pg_catalog.acosh(
    CAST(cast(null as float8) as float8)) as c11, 
  mz_catalog.mz_version() as c12, 
  69 as c13, 
  subq_2."c0" as c14, 
  pg_catalog.pg_postmaster_start_time() as c15, 
  subq_2."c1" as c16, 
  subq_2."c4" as c17, 
  79 as c18
from 
  (select  
        subq_1."c4" as c0, 
        mz_catalog.mz_version() as c1, 
        subq_1."c2" as c2, 
        subq_1."c0" as c3, 
        subq_1."c0" as c4, 
        subq_1."c1" as c5
      from 
        (select  
              subq_0."c0" as c0, 
              ref_0."worker_id" as c1, 
              ref_0."worker_id" as c2, 
              ref_0."worker_id" as c3, 
              ref_0."id" as c4
            from 
              mz_internal.mz_scheduling_elapsed_raw as ref_0,
              lateral (select  
                    ref_0."worker_id" as c0, 
                    ref_0."id" as c1, 
                    ref_0."id" as c2, 
                    (select "buyer" from public.bids limit 1 offset 5)
                       as c3
                  from 
                    mz_internal.mz_scheduling_elapsed_raw as ref_1
                  where true) as subq_0
            where array[null, null] >= array[null, null]
            limit 84) as subq_1
      where subq_1."c2" is not NULL
      limit 106) as subq_2
where ((select pg_catalog.max("id") from mz_catalog.mz_columns)
       > subq_2."c1") 
  or (subq_2."c1" is NULL)
limit 107;
```
Doesn't reproduce unfortunately (trying in an endless loop), even with
```
CREATE SOURCE auction
              FROM LOAD GENERATOR AUCTION (SCALE FACTOR 0.01)
              FOR ALL TABLES
              WITH (SIZE = '1');
```
If so, I can ignore additional internal tables.

**Comment by tokenrove** [comment]
In theory this could see retractions since it stores the elapsed duration in the diff field, although this would mean a confused view of time, and I'm not sure about other guarantees we have about the order of events this operator sees.

**Comment by vmarcos** [comment]
I discussed this with @tokenrove and he'll try to get a repro to confirm whether `mz_scheduling_elapsed_raw` is implicated here. Was this the only query generating invalid accumulations in the nightly where you caught the problem?

**Comment by def-** [comment]
So far the only one, yes.

**Comment by def-** [comment]
Now also seen with a query without `mz_scheduling_elapsed_raw`:
```sql
SELECT pg_catalog.has_connection_privilege(pg_catalog.current_setting(subq_1.c11,
                                                                      pg_catalog.has_cluster_privilege(subq_1.c11, subq_1.c11, subq_1.c11)),
                                           COALESCE(mz_internal.mz_schema_oid(subq_1.c11),
                                                    mz_internal.mz_database_oid((SELECT NULL
                                                                                 FROM pg_catalog.pg_views))),
                                           subq_1.c11) AS c2
FROM (SELECT (SELECT NULL
              FROM mz_internal.mz_compute_import_frontiers
              OFFSET 99) AS c11
      FROM (SELECT
            FROM mz_catalog.mz_columns AS ref_0
            LIMIT 27) AS subq_0) AS subq_1;
```
```
ERROR:  Invalid data in source errors, saw retractions (1741248686229744672) for row that does not exist: Evaluation error: internal error: unrecognized configuration parameter
```

**Comment by vmarcos** [comment]
> Now also seen with a query without `mz_scheduling_elapsed_raw`:
> 
> ```sql
> SELECT pg_catalog.has_connection_privilege(pg_catalog.current_setting(subq_1.c11,
>                                                                       pg_catalog.has_cluster_privilege(subq_1.c11, subq_1.c11, subq_1.c11)),
>                                            COALESCE(mz_internal.mz_schema_oid(subq_1.c11),
>                                                     mz_internal.mz_database_oid((SELECT NULL
>                                                                                  FROM pg_catalog.pg_views))),
>                                            subq_1.c11) AS c2
> FROM (SELECT (SELECT NULL
>               FROM mz_internal.mz_compute_import_frontiers
>               OFFSET 99) AS c11
>       FROM (SELECT
>             FROM mz_catalog.mz_columns AS ref_0
>             LIMIT 27) AS subq_0) AS subq_1;
> ```
> 
> ```
> ERROR:  Invalid data in source errors, saw retractions (1741248686229744672) for row that does not exist: Evaluation error: internal error: unrecognized configuration parameter
> ```

I think this is a separate issue. It reproduces every time, not being not timing-dependent as in the previous observations in this ticket. Also, the retractions generated are of errors, not of rows. I found at least one mutation of the query that generates another class of internal error. Let's follow up on this case in #20111.

**Comment by vmarcos** [comment]
This repro appears to be unfortunately another manifestation of https://github.com/MaterializeInc/materialize/issues/18738. The query has sufficiently many cross joins that we eventually burst through the `i64` representation of row multiplicities.

The way this manifests in `debug` mode is different than in `release`. The repro in a `debug` build will lead to the following panic:

```
thread 'timely:work-0' panicked at 'attempt to multiply with overflow', /Users/vmarcos/workspace/materialize/src/compute/src/render/join/delta_join.rs:411:28
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:117:5
   3: mz_compute::render::join::delta_join::build_halfjoin::{{closure}}
   4: dogsdogsdogs::operators::half_join::half_join_internal_unsafe::{{closure}}::{{closure}}
   5: <timely::dataflow::stream::StreamCore<G,D1> as timely::dataflow::operators::generic::operator::Operator<G,D1>>::binary_frontier::{{closure}}::{{closure}}
   6: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}
   7: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
   8: <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
   9: timely::progress::subgraph::PerOperatorState<T>::schedule
  10: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
  11: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
  12: timely::progress::subgraph::PerOperatorState<T>::schedule
  13: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
  14: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
  15: timely::progress::subgraph::PerOperatorState<T>::schedule
  16: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
  17: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
  18: timely::progress::subgraph::PerOperatorState<T>::schedule
  19: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
  20: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
  21: timely::worker::Wrapper::step::{{closure}}
  22: core::option::Option<T>::map
  23: timely::worker::Wrapper::step
  24: timely::worker::Worker<A>::step_or_park
  25: mz_compute::server::Worker<A>::run_client
  26: mz_compute::server::Worker<A>::setup_channel_and_run_client
  27: mz_compute::server::Worker<A>::run
  28: <mz_compute::server::Config as mz_cluster::types::AsRunnableWorker<mz_compute_client::protocol::command::ComputeCommand,mz_compute_client::protocol::response::ComputeResponse>>::build_and_run
  29: mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<C,R,<Worker as mz_cluster::types::AsRunnableWorker<C,R>>::Activatable>,C,R>,Worker,C,R>::build_timely::{{closure}}::{{closure}}
  30: timely::execute::execute_from::{{closure}}
  31: timely_communication::initialize::initialize_from::{{closure}}
```

In `release` mode, I got the following error:

```
ERROR:  Invalid data in source, saw retractions (6324628377479151616) for row that does not exist: [Int32(1)]
```

@philip-stoev Just to confirm: Did you get the same error, i.e., without the `Evaluation error: internal error: Negative multiplicities in TopK`? If so, as observed in https://github.com/MaterializeInc/materialize/issues/18738#issuecomment-1507071055, this is a case of "works as designed".

**Comment by philip-stoev** [comment]
@vmarcos with a more complex query it was "negative multiplicies". As I simplified the query, it converted to "invalid data in source".

@vmarcos can we detect and disallow queries that have too many cross joins?

**Comment by vmarcos** [comment]
> @vmarcos with a more complex query it was "negative multiplicies". As I simplified the query, it converted to "invalid data in source".

Perfect, that is expected, because if a top-k operator consumes the negative diffs, then it'd detect the issue. Otherwise, in the simplified query, the detection happen by the code that returns the results. But the root cause in this case is the overflow in the representation of multiplicities.

**Comment by vmarcos** [comment]
> @vmarcos can we detect and disallow queries that have too many cross joins?

I think that it might be a bit tricky in general to avoid hitting this issue episodically with generated test queries and databases, because even queries that are equi-joins can cause blow-ups if they just create a lot of repeated values (e.g., by the underlying data having many copies of the same value on multiple relations being joined). And your `SELECT 1` in the end just transforms all the results computed into copies of `1`, thus summing up all the multiplicities to represent the repeated values. 

Perhaps one of the optimizer folks might have an opinion, though, on whether we should allow a query where we can see at planning time that the query contains more than a threshold number of cross-joins, e.g., >10 in your case. @aalexandrov Do you think that this would be something worth thinking about?

**Comment by aalexandrov** [comment]
> @aalexandrov Do you think that this would be something worth thinking about?

I think this is a product question. A the very least I would start by reporting `tokio::warn!` events and possibly an optimization notice for such queries.

**Comment by philip-stoev** [comment]
Also seen with the RQG, in a WMR workload: https://buildkite.com/materialize/nightlies/builds/6194#018d4ae9-78db-415e-8563-4b6f1074b987

**Comment by def-** [comment]
This just happened again in data ingest: https://buildkite.com/materialize/nightlies/builds/6828 and seem pretty scary to me
```
pg8000.dbapi.ProgrammingError: {'S': 'ERROR', 'C': 'XX000', 'M': 'Invalid data in source, saw retractions (1) for row that does not exist: [Int16(0), Int64(0), Float64(OrderedFloat(0.0)), Int64(0), Int16(23819), Float32(OrderedFloat(1.0)), String("Vp1"), Int64(8417), String("xPc"), Float32(OrderedFloat(57.246616)), Int32(24380)]'}
```

**Comment by teskje** [comment]
@def- This is another case of a single error message that can have multiple causes. Specifically, the causes in this case could be:
* Overflows in diffs during compute computations (https://github.com/MaterializeInc/materialize/issues/18738)
* `mz_dataflow_operator_reachability` being not well behaved
* Some other yet unknown compute bug
* Invalid data in the dataflow sources, which in turn might either be caused by incorrect usage or an unknown storage bug

Ideally we'd have a separate issue for each, but I see how it can be hard to differentiate them.

For the error in `data-ingest`, that's probably caused by invalid data in sources. I wonder if that might be a test issue and one of the workloads is accidentally inserting invalid retractions. I think this can only happen directly with debezium sources, or indirectly with postgres sources when the upstream DB is restored from a snapshot. And I think there is also still an issue with the TPCH load generator where it sometimes produces invalid retractions. @MaterializeInc/storage might have other ideas too!

**Comment by guswynn** [comment]
> And I think there is also still an issue with the TPCH load generator where it sometimes produces invalid retractions.

do we have a tracking issue for this? I would 100% not be surprised if this is still the case

**Comment by teskje** [comment]
I can't find one. My last status is that @petrosagg [was investigating this](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1707193624219619).

**Comment by petrosagg** [comment]
Have we seen invalid TPCH retractions again? The theory was that it was not a TPCH generator bug but a long running source that was active during the period where a bunch of correctness issues due to dataflow shutdown were around

**Comment by teskje** [comment]
Ah, that theory still holds then! No invalid retractions currently in the TPCH subsources, AFAICT.

**Comment by petrosagg** [comment]
@guswynn the test mentioned here https://github.com/MaterializeInc/materialize/issues/18645#issuecomment-1986529178 is an upsert source so either there is a bug in there or there is a more general kafka source bug that misses events (can't be duplication since upsert is immune to that)

**Comment by guswynn** [comment]
I want to make sure I am up-to-date on this:

We see both `Invalid data in source **errors**, saw retractions` and `Invalid data in source **data**, saw retractions`. My reading of `compute_state.rs` (which could be wrong!) is that **source** here is a bit overloaded, and its actually referring to the source of the peek's data, not always a storage source. Are we sure that these peeks are directly on sources?

In data-ingest we see this issue on an upsert source, as @petrosagg mentions here: https://github.com/MaterializeInc/materialize/issues/18645#issuecomment-2051886511. @def- can you help me understand if this is a query on the source itself directly, or some view on top?


Regardless, it seems extremely hard to debug this issue with the information we current have during failures, even if we can reproduce it reliably (it doesn't look like we can?). Would it be worth it to invest in dumping more state when this error occurs?

I am thinking we could dump the full state of the persist shard for all sources (and maybe MV's) involved in the query, specifically if this issue happens. I think this boils down to implementing 2 things, both of which seem relatively useful outside this issue:

- A way to get the `GlobalId`/`ShardId`'s for all sources involved in a given query
- A way to dump a persist shard to a file; I expect some kind of basic consolidation across batches between frontier changes, and json-serialized rows is a good start?

**Comment by def-** [comment]
> can you help me understand if this is a query on the source itself directly, or some view on top?

The query is straight on the source, no view on top. `SELECT * FROM {executor.table} ORDER BY {order_str}`

**Comment by guswynn** [comment]
> Definitely, I can report back when an issue happens again with new details.

thanks!

**Comment by nrainer-materialize** [comment]
This is still observed in the cloud canary: https://buildkite.com/materialize/qa-canary/builds/108

**Comment by nrainer-materialize** [comment]
Further occurrences (multiple in a run): https://buildkite.com/materialize/qa-canary/builds/109
@guswynn, could you take a look?

**Comment by def-** [comment]
This is still occurring a bunch: https://buildkite.com/materialize/qa-canary/builds/194

**Comment by teskje** [comment]
I get a 404 on that link but looking at the compute dashboard for the Prod Sandbox I see errors in `qa_canary_environment.public_tpch.tpch_q18`. So this is the known (but elusive) issue with the TPCH loadgen. Can be confirmed by running this query that looks for negative multiplicities in `lineitem`:

```
SELECT l_orderkey, l_linenumber FROM
   (SELECT l_orderkey::text, l_linenumber::text FROM qa_canary_environment.public_tpch.lineitem)
GROUP BY l_orderkey, l_linenumber
HAVING count(*) < 0;
```

Previous discussions of this that I'm aware of: [thread](https://materializeinc.slack.com/archives/C01LKF361MZ/p1703261861200689), [thread](https://materializeinc.slack.com/archives/C02PPB50ZHS/p1706880878686539), [thread](https://materializeinc.slack.com/archives/C01CFKM1QRF/p1707193624219619).

@petrosagg looked into this, not sure what he concluded though.

Btw, I'm getting confused about the "Negative multiplicities" issues we have. There is https://github.com/MaterializeInc/materialize/issues/22576, which seems to be about the TPCH loadgen as well. Is that a duplicate?

**Comment by def-** [comment]
> I get a 404 on that link

Fixed

**Comment by teskje** [comment]
Thanks! The error in that CI run also points to `tpch_q18`.

**Comment by petrosagg** [comment]
When was that tpch source created in the QA environment? It is a very old source or one that is created every time we test?

**Comment by petrosagg** [comment]
Thanks, that does look like a bug then and my theory doesn't explain what we see

**Comment by petrosagg** [comment]
It's very likely that this is a fix https://github.com/MaterializeInc/materialize/pull/29029

If that turns out to be the case we'll have to re-create all the loadgen sources in the QA environment since any errors will have been durably recorded by now

**Comment by morsapaes** [comment]
@nrainer-materialize, could you confirm whether #29029 fixed this issue?

**Comment by nrainer-materialize** [comment]
@petrosagg, should this have fixed just the "Negative multiplicities in TopK" (as in the title) or also "Non-positive multiplicity in DistinctBy"?
I have not seen any recent occurrences of "Negative multiplicities in TopK" in QA canary. However, "Non-positive multiplicity in DistinctBy" does still occur.
