### ISSUE TITLE
CI: devsite deploy is broken

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#18696]
### What version of Materialize are you using?

v0.51.0-dev

### How did you install Materialize?

Docker image

### What is the issue?

The devsite stage of the deploy CI pipeline has not been working on recent commits.

Ex: https://buildkite.com/materialize/deploy/builds/9671#01876c61-3012-4742-8826-fcc5fe3e62ce

### Relevant log output

```source
[2023-04-10T18:17:26Z] thread 'rustc' panicked at 'no resolutions for a doc link', compiler/rustc_metadata/src/rmeta/encoder.rs:2247:18
[2023-04-10T18:17:26Z] stack backtrace:
[2023-04-10T18:17:26Z]    Compiling bytemuck_derive v1.1.0
[2023-04-10T18:17:26Z]    0: rust_begin_unwind
[2023-04-10T18:17:26Z]              at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/std/src/panicking.rs:577:5
[2023-04-10T18:17:26Z]    1: core::panicking::panic_fmt
[2023-04-10T18:17:26Z]              at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/panicking.rs:67:14
[2023-04-10T18:17:26Z]    2: core::panicking::panic_display
[2023-04-10T18:17:26Z]              at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/panicking.rs:150:5
[2023-04-10T18:17:26Z]    3: core::panicking::panic_str
[2023-04-10T18:17:26Z]              at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/panicking.rs:134:5
[2023-04-10T18:17:26Z]    4: core::option::expect_failed
[2023-04-10T18:17:26Z]              at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/option.rs:2025:5
[2023-04-10T18:17:26Z]    5: <rustc_metadata::rmeta::encoder::provide::{closure#0} as core::ops::function::FnOnce<(rustc_middle::ty::context::TyCtxt, rustc_span::def_id::LocalDefId)>>::call_once
[2023-04-10T18:17:26Z]    6: <std::thread::local::LocalKey<core::cell::Cell<*const ()>>>::with::<rustc_middle::ty::context::tls::enter_context<rustc_query_system::query::plumbing::execute_job_non_incr<rustc_query_impl::queries::doc_link_resolutions, rustc_query_impl::plumbing::QueryCtxt>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>::{closure#0}, rustc_middle::query::erase::Erased<[u8; 8]>>
[2023-04-10T18:17:26Z]    7: rustc_query_system::query::plumbing::try_execute_query::<rustc_query_impl::queries::doc_link_resolutions, rustc_query_impl::plumbing::QueryCtxt>
[2023-04-10T18:17:26Z]    8: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::doc_link_resolutions
[2023-04-10T18:17:26Z]    9: <rustdoc::passes::collect_intra_doc_links::LinkCollector>::resolve_path
[2023-04-10T18:17:26Z]   10: <rustdoc::passes::collect_intra_doc_links::LinkCollector>::resolve
[2023-04-10T18:17:26Z]   11: <rustdoc::passes::collect_intra_doc_links::LinkCollector>::resolve_links
[2023-04-10T18:17:26Z]   12: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_inner_recur
[2023-04-10T18:17:26Z]   13: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::visit::DocVisitor>::visit_inner_recur
[2023-04-10T18:17:26Z]   14: rustdoc::passes::collect_intra_doc_links::collect_intra_doc_links
[2023-04-10T18:17:26Z]   15: <rustc_session::session::Session>::time::<rustdoc::clean::types::Crate, rustdoc::core::run_global_ctxt::{closure#8}>
[2023-04-10T18:17:26Z]   16: rustdoc::core::run_global_ctxt
[2023-04-10T18:17:26Z]   17: <rustc_session::session::Session>::time::<(rustdoc::clean::types::Crate, rustdoc::config::RenderOptions, rustdoc::formats::cache::Cache), rustdoc::main_args::{closure#1}::{closure#0}::{closure#0}::{closure#0}>
[2023-04-10T18:17:26Z]   18: <std::thread::local::LocalKey<core::cell::Cell<*const ()>>>::with::<rustc_middle::ty::context::tls::enter_context<<rustc_middle::ty::context::GlobalCtxt>::enter<rustdoc::main_args::{closure#1}::{closure#0}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
[2023-04-10T18:17:26Z]   19: <rustc_interface::queries::QueryResult<&rustc_middle::ty::context::GlobalCtxt>>::enter::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustdoc::main_args::{closure#1}::{closure#0}::{closure#0}>
[2023-04-10T18:17:26Z]   20: <rustc_interface::interface::Compiler>::enter::<rustdoc::main_args::{closure#1}::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
[2023-04-10T18:17:26Z]   21: rustc_span::set_source_map::<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustdoc::main_args::{closure#1}>::{closure#0}::{closure#0}>
[2023-04-10T18:17:26Z]   22: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_span::ErrorGuaranteed>, rustdoc::main_args::{closure#1}>::{closure#0}, core::result::Result<(), rustc_span::ErrorGuaranteed>>
[2023-04-10T18:17:26Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2023-04-10T18:17:26Z]
[2023-04-10T18:17:26Z]  Documenting lru v0.8.1
[2023-04-10T18:17:26Z] error: the compiler unexpectedly panicked. this is a bug.
[2023-04-10T18:17:26Z]
[2023-04-10T18:17:26Z] note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
[2023-04-10T18:17:26Z]
[2023-04-10T18:17:26Z] note: rustc 1.70.0-nightly (af06dce64 2023-04-08) running on x86_64-unknown-linux-gnu
[2023-04-10T18:17:26Z]
[2023-04-10T18:17:26Z] note: compiler flags: --crate-type lib
[2023-04-10T18:17:26Z]
[2023-04-10T18:17:26Z] note: some of the compiler flags provided by cargo are hidden
[2023-04-10T18:17:26Z]
[2023-04-10T18:17:26Z] query stack during panic:
[2023-04-10T18:17:26Z] #0 [doc_link_resolutions] resolutions for documentation links for a module
[2023-04-10T18:17:26Z] end of query stack
[2023-04-10T18:17:26Z]     Checking futures-executor v0.3.25
[2023-04-10T18:17:26Z] error: could not document `rustix`
[2023-04-10T18:17:26Z]
[2023-04-10T18:17:26Z] Caused by:
[2023-04-10T18:17:26Z]   process didn't exit successfully: `rustdoc --edition=2018 --crate-type lib --crate-name rustix /cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.36.7/src/lib.rs --cap-lints allow -o /mnt/build/doc --cfg 'feature="default"' --cfg 'feature="fs"' --cfg 'feature="io-lifetimes"' --cfg 'feature="libc"' --cfg 'feature="param"' --cfg 'feature="process"' --cfg 'feature="std"' --cfg 'feature="thread"' --cfg 'feature="use-libc-auxv"' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat -C metadata=878a3b2369693324 -L dependency=/mnt/build/debug/deps --extern bitflags=/mnt/build/debug/deps/libbitflags-f75283d3dcd3daad.rmeta --extern io_lifetimes=/mnt/build/debug/deps/libio_lifetimes-5ebaca1dadecd851.rmeta --extern libc=/mnt/build/debug/deps/liblibc-3f64358d3bc61fd2.rmeta --extern linux_raw_sys=/mnt/build/debug/deps/liblinux_raw_sys-a31463b73c270e13.rmeta -D warnings --cfg nightly_doc_features --crate-version 0.36.7 --cfg rustc_attrs --cfg linux_raw --cfg core_intrinsics --cfg asm` (exit status: 101)
```

**Comment by jkosh44** [comment]
It looks like this got fixed, but then broke again on June 15th: https://buildkite.com/materialize/deploy/builds?branch=main&page=5

due to this commit: https://github.com/MaterializeInc/materialize/commit/b3d45b20df21f6d601dc624bfb04ee7e3c39aa58

CC @nrainer-materialize

**Comment by nrainer-materialize** [comment]
> It looks like this got fixed, but then broke again on June 15th: https://buildkite.com/materialize/deploy/builds?branch=main&page=5
> 
> due to this commit: [b3d45b2](https://github.com/MaterializeInc/materialize/commit/b3d45b20df21f6d601dc624bfb04ee7e3c39aa58)
> 
> CC @nrainer-materialize

Sorry for breaking this...
To my understanding, this has been fixed in the mean-time with https://github.com/MaterializeInc/materialize/pull/20140#event-9702267049 (latest: https://buildkite.com/materialize/deploy/builds?branch=main) (I was on holidays).

**Comment by nrainer-materialize** [comment]
Builds are green now: https://buildkite.com/materialize/deploy/builds/10328
