### ISSUE TITLE
[coverage] mz-environmentd::pgwire test_pgtest: thread 'test_pgtest' panicked at 'called `Result::unwrap()` on an `Err` value: Resource temporarily unavailable (os error 11): waiting for ReadyForQuery, saw []

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18895]
### What version of Materialize are you using?

c65dc06c05a5fa438fc68d4daa9d397d603aae38

### How did you install Materialize?

Built from source

### What is the issue?

`cargo llvm-cov nextest --no-clean --workspace test_pgtest` fails, might be timing-related since coverage increases running time.

`cargo install cargo-llvm-cov cargo-nextest` to be able to run it locally.

Noticed as part of enabling unit test coverage.

### Relevant log output

```source
thread 'test_pgtest' panicked at 'called `Result::unwrap()` on an `Err` value: Resource temporarily unavailable (os error 11): waiting for ReadyForQuery, saw []

Stack backtrace:
   0: <anyhow::Error>::msg::<alloc::string::String>
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.66/src/error.rs:83:36
   1: <mz_pgtest::PgConn>::until
             at /home/deen/git/materialize/src/pgtest/src/lib.rs:224:33
   2: <mz_pgtest::PgTest>::until
             at /home/deen/git/materialize/src/pgtest/src/lib.rs:482:9
   3: mz_pgtest::run_test::{closure#0}
             at /home/deen/git/materialize/src/pgtest/src/lib.rs:676:21
   4: <datadriven::TestFile>::run_normal::<mz_pgtest::run_test::{closure#0}>
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/datadriven-0.6.0/src/lib.rs:264:30
   5: <datadriven::TestFile>::run::<mz_pgtest::run_test::{closure#0}>
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/datadriven-0.6.0/src/lib.rs:254:23
   6: mz_pgtest::run_test
             at /home/deen/git/materialize/src/pgtest/src/lib.rs:560:5
   7: pgwire::pg_test_inner::{closure#0}
             at ./tests/pgwire.rs:571:9
   8: datadriven::walk::<pgwire::pg_test_inner::{closure#0}>::{closure#0}
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/datadriven-0.6.0/src/lib.rs:42:9
   9: datadriven::walk::<pgwire::pg_test_inner::{closure#0}>
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/datadriven-0.6.0/src/lib.rs:50:13
  10: pgwire::pg_test_inner
             at ./tests/pgwire.rs:559:5
  11: pgwire::test_pgtest
             at ./tests/pgwire.rs:579:5
  12: pgwire::test_pgtest::{closure#0}
             at ./tests/pgwire.rs:577:18
  13: <pgwire::test_pgtest::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/ops/function.rs:250:5
  14: core::ops::function::FnOnce::call_once
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/ops/function.rs:250:5
  15: test::__rust_begin_short_backtrace
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/test/src/lib.rs:655:18
  16: test::run_test::{{closure}}
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/test/src/lib.rs:646:30
  17: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/ops/function.rs:250:5
  18: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/alloc/src/boxed.rs:1962:9
  19: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/panic/unwind_safe.rs:271:9
  20: std::panicking::try::do_call
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/std/src/panicking.rs:485:40
  21: std::panicking::try
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/std/src/panicking.rs:449:19
  22: std::panic::catch_unwind
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/std/src/panic.rs:140:14
  23: test::run_test_in_process
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/test/src/lib.rs:678:27
  24: test::run_test::run_test_inner::{{closure}}
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/test/src/lib.rs:572:39
  25: test::run_test::run_test_inner::{{closure}}
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/test/src/lib.rs:599:37
  26: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/std/src/sys_common/backtrace.rs:134:18
  27: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/std/src/thread/mod.rs:526:17
  28: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/panic/unwind_safe.rs:271:9
  29: std::panicking::try::do_call
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/std/src/panicking.rs:485:40
  30: std::panicking::try
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/std/src/panicking.rs:449:19
  31: std::panic::catch_unwind
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/std/src/panic.rs:140:14
  32: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/std/src/thread/mod.rs:525:30
  33: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/ops/function.rs:250:5
  34: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/alloc/src/boxed.rs:1962:9
  35: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/alloc/src/boxed.rs:1962:9
  36: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/std/src/sys/unix/thread.rs:108:17
  37: start_thread
             at ./nptl/pthread_create.c:442:8
  38: __GI___clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81', src/pgtest/src/lib.rs:677:26
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/result.rs:1651:5
   3: <core::result::Result<alloc::vec::Vec<alloc::string::String>, anyhow::Error>>::unwrap
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/result.rs:1076:23
   4: mz_pgtest::run_test::{closure#0}
             at /home/deen/git/materialize/src/pgtest/src/lib.rs:676:21
   5: <datadriven::TestFile>::run_normal::<mz_pgtest::run_test::{closure#0}>
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/datadriven-0.6.0/src/lib.rs:264:30
   6: <datadriven::TestFile>::run::<mz_pgtest::run_test::{closure#0}>
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/datadriven-0.6.0/src/lib.rs:254:23
   7: mz_pgtest::run_test
             at /home/deen/git/materialize/src/pgtest/src/lib.rs:560:5
   8: pgwire::pg_test_inner::{closure#0}
             at ./tests/pgwire.rs:571:9
   9: datadriven::walk::<pgwire::pg_test_inner::{closure#0}>::{closure#0}
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/datadriven-0.6.0/src/lib.rs:42:9
  10: datadriven::walk::<pgwire::pg_test_inner::{closure#0}>
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/datadriven-0.6.0/src/lib.rs:50:13
  11: pgwire::pg_test_inner
             at ./tests/pgwire.rs:559:5
  12: pgwire::test_pgtest
             at ./tests/pgwire.rs:579:5
  13: pgwire::test_pgtest::{closure#0}
             at ./tests/pgwire.rs:577:18
  14: <pgwire::test_pgtest::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/ops/function.rs:250:5
  15: core::ops::function::FnOnce::call_once
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by mjibson** [comment]
That error means the test timed out. If you are running with anything that slows down mz, that'd cause this.

**Comment by def-** [comment]
Alright, I'll try increasing the timeout.

**Comment by mjibson** [comment]
This is an internal pgtest timeout, not a test infra timeout! pgtest will wait 5 or 10 seconds or something for an expected message. If mz is running slower than normal, that timeout might need to be doubled, but it's somewhere in the pgtest code itself.

**Comment by def-** [comment]
I know, I doubled it inside pgtest code. with an `if cfg!(coverage)`, test passed now.
