### ISSUE TITLE
[coverage] test_storage_usage_doesnt_update_between_restarts: 

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18896]
### What version of Materialize are you using?

c65dc06c05a5fa438fc68d4daa9d397d603aae38

### How did you install Materialize?

Built from source

### What is the issue?

`cargo llvm-cov nextest --no-clean --workspace test_storage_usage_doesnt_update_between_restarts` fails, might be timing-related since coverage increases running time.

cargo install cargo-llvm-cov to be able to run it locally.

Noticed as part of enabling unit test coverage.

@jkosh44 I saw that you touched the test before, do you have any idea on how best to fix this?

### Relevant log output

```source
thread 'test_storage_usage_doesnt_update_between_restarts' panicked at 'assertion failed: `(left == right)`
  left: `1682085319.833`,
 right: `1682085342.425`', src/environmentd/tests/server.rs:651:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/panicking.rs:67:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed::<f64, f64>
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/panicking.rs:228:5
   4: server::test_storage_usage_doesnt_update_between_restarts
             at ./tests/server.rs:651:9
   5: server::test_storage_usage_doesnt_update_between_restarts::{closure#0}
             at ./tests/server.rs:612:56
   6: <server::test_storage_usage_doesnt_update_between_restarts::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jkosh44** [comment]
> @jkosh44 I saw that you touched the test before, do you have any idea on how best to fix this?

I'll take a look today.

**Comment by jkosh44** [comment]
I'm getting the following error:

```
$ cargo llvm-cov nextest --no-clean --workspace test_storage_usage_doesnt_update_between_restarts
error: no such command: `nextest`

        Did you mean `test`?

        View all installed commands with `cargo --list`
error: process didn't exit successfully: `/home/joe/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo nextest run --manifest-path /home/joe/materialize/Cargo.toml --target-dir /home/joe/materialize/target/llvm-cov-target --workspace test_storage_usage_doesnt_update_between_restarts` (exit status: 101)
```

**Comment by def-** [comment]
Also requires `cargo install cargo-nextest`
