### ISSUE TITLE
[coverage] thread 'test_coord_startup_blocking' panicked at 'called `Result::unwrap()` on an `Err` value: Empty', src/environmentd/tests/sql.rs:2192:10

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18897]
### What version of Materialize are you using?

c65dc06c05a5fa438fc68d4daa9d397d603aae38

### How did you install Materialize?

Built from source

### What is the issue?

`cargo llvm-cov nextest --no-clean --run-ignored=all --workspace test_coord_startup_blocking` fails, might be timing-related since coverage increases running time.

`cargo install cargo-llvm-cov cargo-nextest` to be able to run it locally.

Noticed as part of enabling unit test coverage.

### Relevant log output

```source
thread 'test_coord_startup_blocking' panicked at 'called `Result::unwrap()` on an `Err` value: Empty', src/environmentd/tests/sql.rs:2192:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/result.rs:1651:5
   3: <core::result::Result<(), std::sync::mpsc::TryRecvError>>::unwrap
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/result.rs:1076:23
   4: sql::test_coord_startup_blocking
             at ./tests/sql.rs:2189:5
   5: sql::test_coord_startup_blocking::{closure#0}
             at ./tests/sql.rs:2136:34
   6: <sql::test_coord_startup_blocking::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by def-** [comment]
@jkosh44 I saw that you touched the test before, do you have any idea on how best to fix this?
