### ISSUE TITLE
[coverage] Sporadic failure in stats::tests::test_truncate_string_proptest

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18901]
### What version of Materialize are you using?

c65dc06c05a5fa438fc68d4daa9d397d603aae38

### How did you install Materialize?

Built from source

### What is the issue?

`cargo llvm-cov nextest --no-clean -j 16 --workspace test_client` sometimes fails, might be timing-related since coverage increases running time.

`cargo install cargo-llvm-cov cargo-nextest` to be able to run it locally.

Noticed as part of enabling unit test coverage.

@danhhz I noticed you added this test recently, do you have any idea about this failure?

### Relevant log output

```source
thread 'stats::tests::test_truncate_string_proptest' panicked at 'assertion failed: upper.len() <= max_len', src/persist-types/src/stats.rs:930:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/panicking.rs:117:5
   3: mz_persist_types::stats::tests::test_truncate_string_proptest::testcase
             at ./src/stats.rs:930:21
   4: mz_persist_types::stats::tests::test_truncate_string_proptest::{closure#1}
             at ./src/stats.rs:938:13
   5: <&mz_persist_types::stats::tests::test_truncate_string_proptest::{closure#1} as core::ops::function::Fn<(proptest::sugar::NamedArguments<&str, alloc::string::String>,)>>::call
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/ops/function.rs:262:13
   6: proptest::test_runner::runner::call_test::<proptest::sugar::NamedArguments<&str, alloc::string::String>, &mz_persist_types::stats::tests::test_truncate_string_proptest::{closure#1}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>::{closure#0}
             at /home/deen/.cargo/git/checkouts/proptest-e0d773c2e7a31a11/fc9660f/proptest/src/test_runner/runner.rs:246:49
   7: <core::panic::unwind_safe::AssertUnwindSafe<proptest::test_runner::runner::call_test<proptest::sugar::NamedArguments<&str, alloc::string::String>, &mz_persist_types::stats::tests::test_truncate_string_proptest::{closure#1}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>::{closure#0}> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/panic/unwind_safe.rs:271:9
   8: std::panicking::try::do_call::<core::panic::unwind_safe::AssertUnwindSafe<proptest::test_runner::runner::call_test<proptest::sugar::NamedArguments<&str, alloc::string::String>, &mz_persist_types::stats::tests::test_truncate_string_proptest::{closure#1}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>::{closure#0}>, core::result::Result<(), proptest::test_runner::errors::TestCaseError>>
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/std/src/panicking.rs:485:40
   9: __rust_try
  10: std::panicking::try::<core::result::Result<(), proptest::test_runner::errors::TestCaseError>, core::panic::unwind_safe::AssertUnwindSafe<proptest::test_runner::runner::call_test<proptest::sugar::NamedArguments<&str, alloc::string::String>, &mz_persist_types::stats::tests::test_truncate_string_proptest::{closure#1}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>::{closure#0}>>
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/std/src/panicking.rs:449:19
  11: std::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<proptest::test_runner::runner::call_test<proptest::sugar::NamedArguments<&str, alloc::string::String>, &mz_persist_types::stats::tests::test_truncate_string_proptest::{closure#1}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>::{closure#0}>, core::result::Result<(), proptest::test_runner::errors::TestCaseError>>
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/std/src/panic.rs:140:14
  12: proptest::test_runner::runner::call_test::<proptest::sugar::NamedArguments<&str, alloc::string::String>, &mz_persist_types::stats::tests::test_truncate_string_proptest::{closure#1}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>
             at /home/deen/.cargo/git/checkouts/proptest-e0d773c2e7a31a11/fc9660f/proptest/src/test_runner/runner.rs:246:9
  13: <proptest::test_runner::runner::TestRunner>::run_one_with_replay::<proptest::strategy::map::Map<proptest::string::RegexGeneratorValueTree<alloc::string::String>, mz_persist_types::stats::tests::test_truncate_string_proptest::{closure#0}>, &mz_persist_types::stats::tests::test_truncate_string_proptest::{closure#1}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>
             at /home/deen/.cargo/git/checkouts/proptest-e0d773c2e7a31a11/fc9660f/proptest/src/test_runner/runner.rs:693:22
  14: <proptest::test_runner::runner::TestRunner>::gen_and_run_case::<proptest::strategy::map::Map<&str, mz_persist_types::stats::tests::test_truncate_string_proptest::{closure#0}>, mz_persist_types::stats::tests::test_truncate_string_proptest::{closure#1}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>
             at /home/deen/.cargo/git/checkouts/proptest-e0d773c2e7a31a11/fc9660f/proptest/src/test_runner/runner.rs:649:12
  15: <proptest::test_runner::runner::TestRunner>::run_in_process_with_replay::<proptest::strategy::map::Map<&str, mz_persist_types::stats::tests::test_truncate_string_proptest::{closure#0}>, mz_persist_types::stats::tests::test_truncate_string_proptest::{closure#1}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>
             at /home/deen/.cargo/git/checkouts/proptest-e0d773c2e7a31a11/fc9660f/proptest/src/test_runner/runner.rs:588:13
  16: <proptest::test_runner::runner::TestRunner>::run_in_process::<proptest::strategy::map::Map<&str, mz_persist_types::stats::tests::test_truncate_string_proptest::{closure#0}>, mz_persist_types::stats::tests::test_truncate_string_proptest::{closure#1}>
             at /home/deen/.cargo/git/checkouts/proptest-e0d773c2e7a31a11/fc9660f/proptest/src/test_runner/runner.rs:560:9
  17: <proptest::test_runner::runner::TestRunner>::run::<proptest::strategy::map::Map<&str, mz_persist_types::stats::tests::test_truncate_string_proptest::{closure#0}>, mz_persist_types::stats::tests::test_truncate_string_proptest::{closure#1}>
             at /home/deen/.cargo/git/checkouts/proptest-e0d773c2e7a31a11/fc9660f/proptest/src/test_runner/runner.rs:403:13
  18: mz_persist_types::stats::tests::test_truncate_string_proptest
             at ./src/stats.rs:936:9
  19: mz_persist_types::stats::tests::test_truncate_string_proptest::{closure#0}
             at ./src/stats.rs:921:40
  20: <mz_persist_types::stats::tests::test_truncate_string_proptest::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/ops/function.rs:250:5
  21: core::ops::function::FnOnce::call_once
             at /rustc/8bdcc62cb0362869f0e7b43a6ae4f96b953d3cbc/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by danhhz** [comment]
looks like the test is finding https://github.com/MaterializeInc/materialize/blob/5cc8fb2ae2b1431630c9066d1c5ad223436e9015/src/persist-types/src/stats.rs#L291-L294, which I did before we added a randomized test. can confirm that I can repro this, assigning to myself to fix

**Comment by danhhz** [comment]
Fix up in https://github.com/MaterializeInc/materialize/pull/18902
