### ISSUE TITLE
Creating a materialized view on top of a show command crashes environmentd

### ISSUE THREAD

**Issue by chaas** [MaterializeInc/materialize#18908]
### What version of Materialize are you using?

v0.52.0-dev

### How did you install Materialize?

Built from source

### What is the issue?

Execute `create materialized view v as select * from (show cluster replicas);` and environmentd crashes.
Reproduced with other show commands too, e.g. `SHOW CLUSTERS`.

`select * from (show cluster replicas);` executes fine.

I'm not sure if we're supposed to disallow materialized views on top of show commands, or if it's allowed and broken.

### Relevant log output

```source
environmentd: 2023-04-21T20:12:02.644770Z  INFO mz_adapter::catalog: create materialized view materialize.public.v6 (u4)
thread 'coordinator' panicked at 'Dataflow u1.u3.v6 requested as_of (Antichain { elements: [0] }) not >= since (Antichain { elements: [1682107921000] })', src/adapter/src/coord/dataflows.rs:251:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: mz_adapter::coord::dataflows::<impl mz_adapter::coord::Coordinator>::finalize_dataflow
             at ./src/adapter/src/coord/dataflows.rs:251:13
   3: mz_adapter::coord::dataflows::<impl mz_adapter::coord::Coordinator>::ship_dataflows::{{closure}}
             at ./src/adapter/src/coord/dataflows.rs:160:24
   4: mz_adapter::coord::dataflows::<impl mz_adapter::coord::Coordinator>::must_ship_dataflows::{{closure}}
             at ./src/adapter/src/coord/dataflows.rs:121:13
   5: mz_adapter::coord::dataflows::<impl mz_adapter::coord::Coordinator>::must_ship_dataflow::{{closure}}
             at ./src/adapter/src/coord/dataflows.rs:107:59
   6: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::sequence_create_materialized_view::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer/inner.rs:1274:56
   7: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::sequence_create_materialized_view::{{closure}}
             at ./src/adapter/src/coord/sequencer/inner.rs:1151:5
   8: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_plan::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:164:25
   9: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_plan::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:53:5
  10: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute_inner::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:522:78
  11: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute_inner::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:324:5
  12: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:321:61
  13: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:280:5
  14: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/carahaas/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  15: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_command::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:75:21
  16: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_command::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:250:33
  17: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_command::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:247:5
  18: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::handle_message::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:46:63
  19: mz_adapter::coord::Coordinator::serve::{{closure}}
             at ./src/adapter/src/coord.rs:1290:37
  20: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /Users/carahaas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:63
  21: tokio::runtime::coop::with_budget
             at /Users/carahaas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:107:5
  22: tokio::runtime::coop::budget
             at /Users/carahaas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:73:5
  23: tokio::runtime::park::CachedParkThread::block_on
             at /Users/carahaas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:31
  24: tokio::runtime::context::BlockingRegionGuard::block_on
             at /Users/carahaas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/context.rs:315:13
  25: tokio::runtime::handle::Handle::block_on
             at /Users/carahaas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/handle.rs:264:9
  26: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./src/adapter/src/coord.rs:1505:17
```

**Comment by jkosh44** [comment]
I think I might know what is causing this. The initial `as_of` is selected using the `depends_on` array passed in to the sequencer. This array only contains items that were directly referenced in the query. Since `show cluster replicas` references no other items, `depends_on` is empty, and we select an `as_of` of 0 because we mistakenly think that our query references no other items.

The planner should be extending `depends_on` to include any item that is included in the query as a result of planning, such as `mz_cluster_replicas` in the case of the example query in this issue.
