### ISSUE TITLE
[coverage] Sporadic failure in test_utilization_hold: panicked at 'assertion failed: past_since.less_equal(&since.checked_add(1000).unwrap())', src/environmentd/tests/sql.rs:1371:13

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18934]
### What version of Materialize are you using?

6eaadff6cad3430556aa1d7a5c97f4a706e4d569

### How did you install Materialize?

Docker image

### What is the issue?

```
[2023-04-24T21:11:12Z] 2023-04-24T21:11:02.053042Z  INFO tokio_postgres::connection: NOTICE: relation "consensus" already exists, skipping    
[2023-04-24T21:11:12Z] thread 'test_utilization_hold' panicked at 'assertion failed: past_since.less_equal(&since.checked_add(1000).unwrap())', src/environmentd/tests/sql.rs:1371:13
[2023-04-24T21:11:12Z] stack backtrace:
[2023-04-24T21:11:12Z]    0: rust_begin_unwind
[2023-04-24T21:11:12Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
[2023-04-24T21:11:12Z]    1: core::panicking::panic_fmt
[2023-04-24T21:11:12Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
[2023-04-24T21:11:12Z]    2: core::panicking::panic
[2023-04-24T21:11:12Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:114:5
[2023-04-24T21:11:12Z]    3: sql::test_utilization_hold
[2023-04-24T21:11:12Z]              at ./tests/sql.rs:1371:13
[2023-04-24T21:11:12Z]    4: sql::test_utilization_hold::{closure#0}
[2023-04-24T21:11:12Z]              at ./tests/sql.rs:1300:28
[2023-04-24T21:11:12Z]    5: <sql::test_utilization_hold::{closure#0} as core::ops::function::FnOnce<()>>::call_once
[2023-04-24T21:11:12Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
[2023-04-24T21:11:12Z]    6: core::ops::function::FnOnce::call_once
[2023-04-24T21:11:12Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
[2023-04-24T21:11:12Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
https://buildkite.com/materialize/coverage/builds/55#0187b50c-2cf7-4df0-b474-7a88c590a300

This might be timing-related since coverage increases running time.

`cargo install cargo-llvm-cov cargo-nextest` to be able to run it locally.

Noticed as part of enabling unit test code coverage. @umanwizard I see that you touched the test recently, do you have any idea on how to fix this?

**Comment by def-** [comment]
Had another panic in the same test locally:
```
--- STDERR:              mz-environmentd::sql test_utilization_hold ---
thread 'test_utilization_hold' panicked at 'Since never became non-zero: ()', src/environmentd/tests/sql.rs:1360:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/core/src/result.rs:1651:5
   3: <core::result::Result<mz_adapter::coord::timestamp_selection::TimestampExplanation<mz_repr::timestamp::Timestamp>, ()>>::expect
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/core/src/result.rs:1033:23
   4: sql::test_utilization_hold
             at ./tests/sql.rs:1345:27
   5: sql::test_utilization_hold::{closure#0}
             at ./tests/sql.rs:1301:28
   6: <sql::test_utilization_hold::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by umanwizard** [comment]
Interesting. Can you try increasing the retry limit (right now it is at 10 seconds) and seeing if that fixes it?

**Comment by def-** [comment]
Same with retry limit 50 `max_tries(50)` in src/environmentd/tests/sql.rs:1348

**Comment by ggevay** [comment]
Happened now here: https://buildkite.com/materialize/tests/builds/64172#018ab803-5ddb-491c-85d3-d8a74e7db63c
