### ISSUE TITLE
thread 'tokio:work-2' panicked at 'assertion failed: `(left == right)` in mz_persist_client::internal::state_versions::ReferencedBlobValidator<T>::validate_against_state

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#18974]
### What version of Materialize are you using?

d464d427b804b5fe86c2f9a8f796d49d3e52f7c4

### How did you install Materialize?

Docker image

### What is the issue?

This one is strange. I was running privilege testing locally, and all was good. My notes of what I was running:
```
mz_system=> ALTER SYSTEM SET enable_ld_rbac_checks TO true;
ALTER SYSTEM
mz_system=> ALTER SYSTEM SET enable_rbac_checks TO true;
ALTER SYSTEM
CREATE ROLE regress_priv_user1;
CREATE ROLE
CREATE ROLE regress_priv_user2;
CREATE ROLE
CREATE ROLE regress_priv_user3;
CREATE ROLE
CREATE ROLE regress_priv_user4;
CREATE ROLE
CREATE ROLE regress_priv_user5;
CREATE ROLE
CREATE ROLE regress_priv_user5; -- duplicate
ERROR:  role 'regress_priv_user5' already exists
CREATE ROLE regress_priv_user6;
CREATE ROLE
CREATE ROLE regress_priv_user7;
CREATE ROLE
CREATE ROLE regress_priv_user8;
CREATE ROLE
CREATE ROLE regress_priv_user9;
CREATE ROLE
CREATE ROLE regress_priv_user10;
CREATE ROLE
CREATE ROLE regress_priv_role;
CREATE ROLE
mz_system=> GRANT regress_priv_user2 TO regress_priv_user3;
GRANT ROLE
mz_system=> SELECT * FROM pg_auth_members;
 roleid | member | grantor | admin_option
--------+--------+---------+--------------
(0 rows)
# Bug: https://github.com/MaterializeInc/materialize/issues/18971
mz_system=> alter role regress_priv_user2 CREATEROLE;
ALTER ROLE
mz_system=> alter role regress_priv_user3 CREATEROLE;
ALTER ROLE

psql postgres://regress_priv_user3@localhost:6875
regress_priv_user3=> GRANT regress_priv_user2 TO regress_priv_user4;
GRANT ROLE
regress_priv_user3=> REVOKE regress_priv_user2 FROM regress_priv_user3;
REVOKE ROLE
regress_priv_user3=> begin;
BEGIN
regress_priv_user3=*> REVOKE regress_priv_user2 FROM regress_priv_user4;
ERROR:  REVOKE regress_priv_user2 FROM regress_priv_user4 cannot be run inside a transaction block
regress_priv_user3=!> rollback;
ROLLBACK
regress_priv_user3=> begin;
BEGIN
regress_priv_user3=*> GRANT regress_priv_user2 TO regress_priv_user4;
ERROR:  GRANT regress_priv_user2 TO regress_priv_user4 cannot be run inside a transaction block
regress_priv_user3=!> rollback;
ROLLBACK
regress_priv_user3=> drop role regress_priv_user2;
DROP ROLE
regress_priv_user3=> select * from mz_role_members;
 role_id | member | grantor
---------+--------+---------
(0 rows)
regress_priv_user3=> CREATE ROLE regress_priv_user2;
CREATE ROLE

psql postgres://regress_priv_user1@localhost:6875/materialize
materialize=> CREATE TABLE atest1 ( a int, b text );
CREATE TABLE
materialize=> SELECT * FROM atest1;
 a | b
---+---
(0 rows)

materialize=> INSERT INTO atest1 VALUES (1, 'one');
INSERT 0 1
materialize=> DELETE FROM atest1;
DELETE 1
materialize=> UPDATE atest1 SET a = 1 WHERE b = 'blech';
UPDATE 0
materialize=> REVOKE SELECT, INSERT, UPDATE, DELETE ON atest1 FROM PUBLIC;
REVOKE
materialize=> SELECT * FROM atest1;
 a | b
---+---
(0 rows)

materialize=> GRANT SELECT, INSERT, UPDATE, DELETE ON atest1 TO regress_priv_user2;
GRANT
materialize=> GRANT SELECT ON atest1 TO regress_priv_user3, regress_priv_user4;
ERROR:  Expected end of statement, found comma
# Bug: https://github.com/MaterializeInc/materialize/issues/18972
materialize=> GRANT SELECT ON atest1 TO regress_priv_user3;
GRANT
materialize=> GRANT SELECT ON atest1 TO regress_priv_user4;
GRANT
materialize=> SELECT * FROM atest1;
 a | b
---+---
(0 rows)

materialize=> CREATE TABLE atest2 (col1 varchar(10), col2 boolean);
CREATE TABLE
materialize=> GRANT SELECT ON atest2 TO regress_priv_user2;
GRANT
materialize=> GRANT UPDATE ON atest2 TO regress_priv_user3;
GRANT
materialize=> GRANT INSERT ON atest2 TO regress_priv_user4;
GRANT

psql postgres://regress_priv_user2@localhost:6875/materialize
materialize=> SELECT session_user, current_user;
    session_user    |    current_user
--------------------+--------------------
 regress_priv_user2 | regress_priv_user2
(1 row)

materialize=> SELECT * FROM atest1;
 a | b
---+---
(0 rows)

materialize=> SELECT * FROM atest2;
 col1 | col2
------+------
(0 rows)

materialize=> INSERT INTO atest1 VALUES (2, 'two');
INSERT 0 1
materialize=> INSERT INTO atest2 VALUES ('foo', true);
INSERT 0 1
# TODO: This should fail!
```
Then left the Mz intance running for a while without any activity, and came back to this panic (Debug build). I don't have a way to reproduce it unfortunately. I hope the backtrace helps: https://gist.github.com/def-/0f3c1d729338f6dcdebf090ed1779ec0

### Relevant log output

```source
thread 'tokio:work-2' panicked at 'assertion failed: `(left == right)`
  left: `{HollowBatch ...
 right: `{HollowBatch ...
stack backtrace:
   0: rust_begin_unwind
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/core/src/panicking.rs:67:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/core/src/panicking.rs:228:5
   4: mz_persist_client::internal::state_versions::ReferencedBlobValidator<T>::validate_against_state
             at ./src/persist-client/src/internal/state_versions.rs:1024:9
   5: mz_persist_client::internal::state_versions::StateVersionsIter<T>::next
             at ./src/persist-client/src/internal/state_versions.rs:891:13
   6: mz_persist_client::usage::StorageUsageClient::shard_usage_given_blob_usage::{{closure}}
             at ./src/persist-client/src/usage.rs:317:29
   7: mz_persist_client::usage::StorageUsageClient::shards_usage::{{closure}}::{{closure}}
             at ./src/persist-client/src/usage.rs:194:21
   8: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.25/src/stream/futures_unordered/mod.rs:515:17
   9: <futures_util::stream::stream::collect::Collect<St,C> as core::future::future::Future>::poll
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.25/src/stream/stream/collect.rs:50:26
  10: mz_persist_client::usage::StorageUsageClient::shards_usage::{{closure}}
             at ./src/persist-client/src/usage.rs:200:50
  11: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::storage_usage_fetch::{{closure}}::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:147:56
  12: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/core.rs:223:17
  13: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/loom/std/unsafe_cell.rs:14:9
  14: tokio::runtime::task::core::Core<T,S>::poll
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/core.rs:212:13
  15: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/harness.rs:476:19
  16: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/core/src/panic/unwind_safe.rs:271:9
  17: std::panicking::try::do_call
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/std/src/panicking.rs:485:40
  18: __rust_try
  19: std::panicking::try
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/std/src/panicking.rs:449:19
  20: std::panic::catch_unwind
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/std/src/panic.rs:140:14
  21: tokio::runtime::task::harness::poll_future
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/harness.rs:464:18
  22: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/harness.rs:198:27
  23: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/harness.rs:152:15
  24: tokio::runtime::task::raw::poll
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/raw.rs:255:5
  25: tokio::runtime::task::raw::RawTask::poll
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/raw.rs:200:18
  26: tokio::runtime::task::LocalNotified<S>::run
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/mod.rs:394:9
  27: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:464:13
  28: tokio::runtime::coop::with_budget
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/coop.rs:107:5
  29: tokio::runtime::coop::budget
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/coop.rs:73:5
  30: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
  31: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:433:24
  32: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:406:17
  33: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/macros/scoped_tls.rs:61:9
  34: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:403:5
  35: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
  36: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/blocking/task.rs:42:21
  37: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/core.rs:223:17
  38: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/loom/std/unsafe_cell.rs:14:9
  39: tokio::runtime::task::core::Core<T,S>::poll
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/core.rs:212:13
  40: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/harness.rs:476:19
  41: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/core/src/panic/unwind_safe.rs:271:9
  42: std::panicking::try::do_call
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/std/src/panicking.rs:485:40
  43: __rust_try
  44: std::panicking::try
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/std/src/panicking.rs:449:19
  45: std::panic::catch_unwind
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/std/src/panic.rs:140:14
  46: tokio::runtime::task::harness::poll_future
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/harness.rs:464:18
  47: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/harness.rs:198:27
  48: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/harness.rs:152:15
  49: tokio::runtime::task::raw::poll
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/raw.rs:255:5
  50: tokio::runtime::task::raw::RawTask::poll
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/raw.rs:200:18
  51: tokio::runtime::task::UnownedTask<S>::run
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/task/mod.rs:431:9
  52: tokio::runtime::blocking::pool::Task::run
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/blocking/pool.rs:159:9
  53: tokio::runtime::blocking::pool::Inner::run
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/blocking/pool.rs:513:17
  54: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/blocking/pool.rs:471:13
```

**Comment by bkirwi** [comment]
Closing in favour of https://github.com/MaterializeInc/materialize/issues/20009 - same error and the other issue has seen more discussion.
