### ISSUE TITLE
sql: Casting an `mz_aclitem[]` to `text[]` causes a panic

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#19052]
### What version of Materialize are you using?

0.53.0-dev

### How did you install Materialize?

Docker image

### What is the issue?

Casting an `mz_aclitem[]` to `text[]` causes a panic. 

```
materialize=> SELECT privileges::text[] FROM mz_tables;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
The connection to the server was lost. Attempting reset: Failed.
!?> 
```

### Relevant log output

```source
thread 'tokio:work-0' panicked at 'lower_uncorrelated should not fail given that there is no correlation in the input col_expr: Unstructured("unexpected ScalarExpr in uncorrelated plan: Select(Project { input: Map { input: Join { left: Map { input: Constant { rows: [Row{[]}], typ: RelationType { column_types: [], keys: [] } }, scalars: [CallUnary { func: MzAclItemGrantee(MzAclItemGrantee), expr: Column(ColumnRef { level: 1, column: 0 }) }] }, right: Join { left: Join { left: Map { input: Constant { rows: [Row{[]}], typ: RelationType { column_types: [], keys: [] } }, scalars: [CallUnary { func: MzAclItemGrantor(MzAclItemGrantor), expr: Column(ColumnRef { level: 2, column: 0 }) }] }, right: Get { id: Global(System(320)), typ: RelationType { column_types: [ColumnType { scalar_type: String, nullable: false }, ColumnType { scalar_type: Oid, nullable: false }, ColumnType { scalar_type: String, nullable: false }, ColumnType { scalar_type: Bool, nullable: false }, ColumnType { scalar_type: Bool, nullable: false }, ColumnType { scalar_type: Bool, nullable: false }, ColumnType { scalar_type: Bool, nullable: false }], keys: [] } }, on: CallBinary { func: Eq, expr1: Column(ColumnRef { level: 1, column: 0 }), expr2: Column(ColumnRef { level: 0, column: 1 }) }, kind: LeftOuter }, right: Get { id: Global(System(320)), typ: RelationType { column_types: [ColumnType { scalar_type: String, nullable: false }, ColumnType { scalar_type: Oid, nullable: false }, ColumnType { scalar_type: String, nullable: false }, ColumnType { scalar_type: Bool, nullable: false }, ColumnType { scalar_type: Bool, nullable: false }, ColumnType { scalar_type: Bool, nullable: false }, ColumnType { scalar_type: Bool, nullable: false }], keys: [] } }, on: CallBinary { func: Eq, expr1: Column(ColumnRef { level: 0, column: 0 }), expr2: Column(ColumnRef { level: 0, column: 8 }) }, kind: LeftOuter }, on: Literal(Row{[True]}, ColumnType { scalar_type: Bool, nullable: false }), kind: Inner }, scalars: [CallBinary { func: TextConcat, expr1: CallBinary { func: TextConcat, expr1: CallBinary { func: TextConcat, expr1: CallBinary { func: TextConcat, expr1: If { cond: CallBinary { func: Eq, expr1: Column(ColumnRef { level: 0, column: 0 }), expr2: Literal(Row{[String(\"p\")]}, ColumnType { scalar_type: String, nullable: false }) }, then: Literal(Row{[String(\"\")]}, ColumnType { scalar_type: String, nullable: false }), els: CallVariadic { func: Coalesce, exprs: [Column(ColumnRef { level: 0, column: 4 }), Column(ColumnRef { level: 0, column: 0 })] } }, expr2: Literal(Row{[String(\"=\")]}, ColumnType { scalar_type: String, nullable: false }) }, expr2: CallUnary { func: MzAclItemPrivileges(MzAclItemPrivileges), expr: Column(ColumnRef { level: 1, column: 0 }) } }, expr2: Literal(Row{[String(\"/\")]}, ColumnType { scalar_type: String, nullable: false }) }, expr2: CallVariadic { func: Coalesce, exprs: [Column(ColumnRef { level: 0, column: 11 }), Column(ColumnRef { level: 0, column: 1 })] } }] }, outputs: [16] })")', src/sql/src/plan/typeconv.rs:926:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1790:5
   3: core::result::Result<T,E>::expect
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1069:23
   4: mz_sql::plan::typeconv::plan_hypothetical_cast
             at ./src/sql/src/plan/typeconv.rs:923:9
   5: mz_sql::plan::typeconv::VALID_CASTS::{{closure}}::{{closure}}
             at ./src/sql/src/plan/typeconv.rs:569:29
   6: mz_sql::plan::typeconv::CastTemplate::new::{{closure}}
             at ./src/sql/src/plan/typeconv.rs:67:27
   7: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:2002:9
   8: mz_sql::plan::typeconv::get_cast::{{closure}}
             at ./src/sql/src/plan/typeconv.rs:692:34
   9: core::option::Option<T>::and_then
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/option.rs:1309:24
  10: mz_sql::plan::typeconv::get_cast
             at ./src/sql/src/plan/typeconv.rs:692:5
  11: mz_sql::plan::typeconv::plan_cast::{{closure}}
             at ./src/sql/src/plan/typeconv.rs:952:45
  12: mz_sql::plan::typeconv::plan_cast
             at ./src/sql/src/plan/typeconv.rs:985:9
  13: mz_sql::plan::query::plan_cast
             at ./src/sql/src/plan/query.rs:3350:16
  14: mz_sql::plan::query::plan_expr_inner
             at ./src/sql/src/plan/query.rs:3235:43
  15: mz_sql::plan::query::plan_expr::{{closure}}
             at ./src/sql/src/plan/query.rs:3206:29
  16: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  17: stacker::maybe_grow
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  18: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  19: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  20: mz_sql::plan::query::plan_expr
             at ./src/sql/src/plan/query.rs:3206:5
  21: mz_sql::plan::query::plan_view_select
             at ./src/sql/src/plan/query.rs:1910:51
  22: mz_sql::plan::query::plan_query_inner
             at ./src/sql/src/plan/query.rs:1064:24
  23: mz_sql::plan::query::plan_query::{{closure}}
             at ./src/sql/src/plan/query.rs:1024:33
  24: mz_ore::stack::CheckedRecursion::checked_recur_mut::{{closure}}
             at ./src/ore/src/stack.rs:205:33
  25: stacker::maybe_grow
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  26: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  27: mz_ore::stack::CheckedRecursion::checked_recur_mut
             at ./src/ore/src/stack.rs:205:19
  28: mz_sql::plan::query::plan_query
             at ./src/sql/src/plan/query.rs:1024:5
  29: mz_sql::plan::query::plan_root_query
             at ./src/sql/src/plan/query.rs:112:47
  30: mz_sql::plan::statement::dml::describe_select
             at ./src/sql/src/plan/statement/dml.rs:163:9
  31: mz_sql::plan::statement::describe
             at ./src/sql/src/plan/statement.rs:197:36
  32: mz_adapter::util::describe
             at ./src/adapter/src/util.rs:243:16
  33: mz_adapter::coord::sql::<impl mz_adapter::coord::Coordinator>::declare_inner
             at ./src/adapter/src/coord/sql.rs:65:20
  34: mz_adapter::coord::sql::<impl mz_adapter::coord::Coordinator>::declare::{{closure}}
             at ./src/adapter/src/coord/sql.rs:52:23
  35: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/future/future.rs:125:9
  36: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/core.rs:223:17
  37: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/loom/std/unsafe_cell.rs:14:9
  38: tokio::runtime::task::core::Core<T,S>::poll
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/core.rs:212:13
  39: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:476:19
  40: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panic/unwind_safe.rs:271:9
  41: std::panicking::try::do_call
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
  42: __rust_try
  43: std::panicking::try
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
  44: std::panic::catch_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
  45: tokio::runtime::task::harness::poll_future
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:464:18
  46: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:198:27
  47: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:152:15
  48: tokio::runtime::task::raw::poll
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/raw.rs:255:5
  49: tokio::runtime::task::raw::RawTask::poll
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/raw.rs:200:18
  50: tokio::runtime::task::LocalNotified<S>::run
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/mod.rs:394:9
  51: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:464:13
  52: tokio::runtime::coop::with_budget
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:107:5
  53: tokio::runtime::coop::budget
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:73:5
  54: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
  55: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:426:24
  56: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:406:17
  57: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/macros/scoped_tls.rs:61:9
  58: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:403:5
  59: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
  60: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/blocking/task.rs:42:21
  61: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/core.rs:223:17
  62: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/loom/std/unsafe_cell.rs:14:9
  63: tokio::runtime::task::core::Core<T,S>::poll
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/core.rs:212:13
  64: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:476:19
  65: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panic/unwind_safe.rs:271:9
  66: std::panicking::try::do_call
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
  67: __rust_try
  68: std::panicking::try
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
  69: std::panic::catch_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
  70: tokio::runtime::task::harness::poll_future
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:464:18
  71: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:198:27
  72: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:152:15
  73: tokio::runtime::task::raw::poll
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/raw.rs:255:5
  74: tokio::runtime::task::raw::RawTask::poll
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/raw.rs:200:18
  75: tokio::runtime::task::UnownedTask<S>::run
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/mod.rs:431:9
  76: tokio::runtime::blocking::pool::Task::run
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/blocking/pool.rs:159:9
  77: tokio::runtime::blocking::pool::Inner::run
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/blocking/pool.rs:513:17
  78: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/joe/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/blocking/pool.rs:471:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by jkosh44** [comment]
The panics happens because of the following:

1. When casting an array to array we call `plan_hypothetical_cast`.

https://github.com/MaterializeInc/materialize/blob/fbdb7f015db9c05fb52b15f229c20e43d4c96229/src/sql/src/plan/typeconv.rs#L566-L573

2. `plan_hypothetical_cast` gets the cast implementation as a `HirScalarExpr` from `plan_cast`

https://github.com/MaterializeInc/materialize/blob/fbdb7f015db9c05fb52b15f229c20e43d4c96229/src/sql/src/plan/typeconv.rs#L920-L930

https://github.com/MaterializeInc/materialize/blob/fbdb7f015db9c05fb52b15f229c20e43d4c96229/src/sql/src/plan/typeconv.rs#L933-L987

3. Then `plan_hypothetical_cast` calls `lower_uncorrelated`. `lower_uncorrelated` assumes that the input expression is uncorrelated. I don't actually know what uncorrelated means in this context, but any `SELECT` will fail and cause a panic. 

4. Since casting from `mz_aclitem` to `text` involves a `SELECT` statement, the cast results in a panic.

https://github.com/MaterializeInc/materialize/blob/fbdb7f015db9c05fb52b15f229c20e43d4c96229/src/sql/src/plan/typeconv.rs#L651-L667

Since casts can be implemented with arbitrary SQL, it's not a valid assumption to assume that they won't contain a `SELECT` statement.

This issue actually isn't new and isn't specific to `mz_aclitem`.

This same issue may exists for 
- String to Array casts
- String to List casts
- String to Map casts
- String to Range casts
- Record to Record casts
- Other Array to Array casts
- List to List casts

Here's another example using Lists and `reproc`

```
materialize=> CREATE TABLE t (a regproc list);
CREATE TABLE
materialize=> INSERT INTO t VALUES (LIST[1299::regproc]);
INSERT 0 1
materialize=> SELECT a::text list FROM t;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
The connection to the server was lost. Attempting reset: Failed.
!?> 
```
