### ISSUE TITLE
adapter: `SELECT ... AS OF ...` with different timestamps during txn crashes `environmentd`

### ISSUE THREAD

**Issue by rkrishn7** [MaterializeInc/materialize#19178]
### What version of Materialize are you using?

0.53.0-dev

### What is the issue?

```
materialize=> CREATE TEMP TABLE t (a int);
CREATE TABLE
materialize=> BEGIN;
BEGIN
materialize=*> SELECT * FROM t AS OF AT LEAST 1683131452106;
 a
---
(0 rows)

materialize=*> SELECT * FROM t AS OF AT LEAST 1683131452126;
SSL SYSCALL error: EOF detected
The connection to the server was lost. Attempting reset: Failed.
The connection to the server was lost. Attempting reset: Failed.
```

Relevant stack trace:

```
thread 'coordinator' panicked at 'assertion failed: `(left == right)`
  left: `1683600669261`,
 right: `1683600672261`', src/adapter/src/session.rs:311:37
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:212:5
   4: mz_adapter::session::Session<T>::add_transaction_ops
             at ./src/adapter/src/session.rs:311:37
   5: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::sequence_peek_timestamp
             at ./src/adapter/src/coord/sequencer/inner.rs:2233:13
   6: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::plan_peek
             at ./src/adapter/src/coord/sequencer/inner.rs:2292:33
   7: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::peek_stage_finish::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer/inner.rs:2168:25
   8: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::peek_stage_finish::{{closure}}
             at ./src/adapter/src/coord/sequencer/inner.rs:2141:5
   9: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::sequence_peek_stage::{{closure}}
             at ./src/adapter/src/coord/sequencer/inner.rs:1892:74
```

**Comment by benesch** [comment]
cc @mjibson @jkosh44 @chaas
