### ISSUE TITLE
test_max_connections is flaky

### ISSUE THREAD

**Issue by mjibson** [MaterializeInc/materialize#19194]
### Buildkite link

https://buildkite.com/materialize/tests/builds/55204#018803a9-419d-4a11-8ddb-9c3505faf8fd

### Relevant log output

```source
[2023-05-10T03:30:08Z] thread 'test_max_connections' panicked at 'expect db error: error communicating with the server: Connection reset by peer (os error 104)', src/environmentd/tests/sql.rs:3157:28
[2023-05-10T03:30:08Z] stack backtrace:
[2023-05-10T03:30:08Z]    0: rust_begin_unwind
[2023-05-10T03:30:08Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
[2023-05-10T03:30:08Z]    1: core::panicking::panic_fmt
[2023-05-10T03:30:08Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
[2023-05-10T03:30:08Z]    2: sql::test_max_connections::{closure#1}
[2023-05-10T03:30:08Z]              at ./tests/sql.rs:3157:28
[2023-05-10T03:30:08Z]    3: <core::option::Option<&tokio_postgres::error::DbError>>::unwrap_or_else::<sql::test_max_connections::{closure#1}>
[2023-05-10T03:30:08Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/option.rs:873:21
[2023-05-10T03:30:08Z]    4: sql::test_max_connections
[2023-05-10T03:30:08Z]              at ./tests/sql.rs:3155:13
[2023-05-10T03:30:08Z]    5: sql::test_max_connections::{closure#0}
[2023-05-10T03:30:08Z]              at ./tests/sql.rs:3124:27
[2023-05-10T03:30:08Z]    6: <sql::test_max_connections::{closure#0} as core::ops::function::FnOnce<()>>::call_once
[2023-05-10T03:30:08Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
[2023-05-10T03:30:08Z]    7: core::ops::function::FnOnce::call_once
[2023-05-10T03:30:08Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
[2023-05-10T03:30:08Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by andrewrodriguez-m** [comment]
Current status: there is a race where the client can either receive the postgres error that explains that they've hit the max connections or they can receive a ECONNRESET error. I think it's worth trying to untangle this if we can. Receiving a ECONNRESET from the server is accurate in a sense but not friendly.

Today the client does a postgres connect which [succeeds quickly](https://github.com/MaterializeInc/materialize/blob/68152c798309636d009827a4b7f970ce95f854e1/src/pgwire/src/protocol.rs#L254C1-L264). Next there's a race where the client sends it's query while the server is doing the second half of the connect work, including validating that there aren't too many connections. The server quickly realizes that there are too many connections so it sends the error message and closes the connection. At this point the client has usually sent some data (the query) so when the server closes the connection while there's data in its OS recv buffer which forces a RST instead of a FIN to be sent. Once the client reads all of its incoming network data the next read will produce ECONNRESET instead of the normal 0-length recv indicating that the other side closed. If the client read one postgres protocol message at a time and errored out on fatal postgres errors everything would be okay and the client would only see the postgres error. Initially I thought this was a bug in rust-postgres (in [poll_read](https://github.com/MaterializeInc/rust-postgres/blob/dd70a8b9caec1bb056ff66782a8e8b72d446ffa5/tokio-postgres/src/connection.rs#L97) the client can read from the socket multiple times in a single `poll_read` while it can still send data into `response.sender` so while the consumers of `poll_read` seem to error out as soon as they see a postgres error they don't get the chance because `poll_read` itself errors out with ECONNRESET) but I think the current behavior in materialize doesn't match anything that postgres does. While the postgres protocol allows for sending notices whenever it doesn't seem like there's any real support for sending fatal errors whenever. In the [termination section](https://www.postgresql.org/docs/current/protocol-flow.html#id-1.10.6.7.11) of the protocol docs it mentions that "In rare cases (such as an administrator-commanded database shutdown) the backend might disconnect without any frontend request to do so. In such cases the backend will attempt to send an error or notice message giving the reason for the disconnection before it closes the connection." but it reads to me as more of a best effort basis rather than something that the client has to specifically handle. If we step back a bit it seems weird that we expect the max connection error to appear when we run the query instead of when we connect.

I propose waiting for the adapter to allow the connection so that we can generate an error on connect and avoid the race and the attendant problems. My plan is to introduce a command like Startup, maybe NewConnection, which we'll wait for before returning ok to postgres connect.

**Comment by andrewrodriguez-m** [comment]
From our chat:
 - let's allow admins (super users) + mz_system+mz_introspection & connections on internal ports to bypass limit and not increment limit
 - we don't want to wait on coordinator so let's move this check into the pgwire side. Imagining a arc mutex counter that `alter set max_connections` also touches
 - we want the error to happen on postgres's connect, not on first query which makes for a confusing experience
