### ISSUE TITLE
Flaky test: test_query_on_dropped_source: panicked at 'called `Result::unwrap()` on an `Err` value: "no active query"', src/environmentd/tests/sql.rs:2568:14

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#19202]
### What version of Materialize are you using?

78df026ce95d6f5c5298ed851b0a137bf3f1ee90

### What is the issue?

The test_query_on_dropped_source unit test seems flaky: https://buildkite.com/materialize/tests/builds/55219#01880552-7b9c-4892-a968-510a380e53b7
```
[2023-05-10T11:23:45Z] thread 'test_query_on_dropped_source' panicked at 'called `Result::unwrap()` on an `Err` value: "no active query"', src/environmentd/tests/sql.rs:2568:14
[2023-05-10T11:23:45Z] stack backtrace:
[2023-05-10T11:23:45Z]    0: rust_begin_unwind
[2023-05-10T11:23:45Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
[2023-05-10T11:23:45Z]    1: core::panicking::panic_fmt
[2023-05-10T11:23:45Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
[2023-05-10T11:23:45Z]    2: core::result::unwrap_failed
[2023-05-10T11:23:45Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1790:5
[2023-05-10T11:23:45Z]    3: <core::result::Result<(), &str>>::unwrap
[2023-05-10T11:23:45Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1112:23
[2023-05-10T11:23:45Z]    4: sql::test_query_on_dropped_source::test_query_on_dropped_source_inner::<sql::test_query_on_dropped_source::{closure#0}>
[2023-05-10T11:23:45Z]              at ./tests/sql.rs:2555:9
[2023-05-10T11:23:45Z]    5: sql::test_query_on_dropped_source
[2023-05-10T11:23:45Z]              at ./tests/sql.rs:2615:5
[2023-05-10T11:23:45Z]    6: sql::test_query_on_dropped_source::{closure#0}
[2023-05-10T11:23:45Z]              at ./tests/sql.rs:2522:35
[2023-05-10T11:23:45Z]    7: <sql::test_query_on_dropped_source::{closure#0} as core::ops::function::FnOnce<()>>::call_once
[2023-05-10T11:23:45Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
[2023-05-10T11:23:45Z]    8: core::ops::function::FnOnce::call_once
[2023-05-10T11:23:45Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
[2023-05-10T11:23:45Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
I believe the timing is sometimes off and the thread in line 2550 can be too fast/slow, but I couldn't reproduce this with `cargo nextest run test_query_on_dropped_source` locally. I'll try to see if I can find a way to reproduce it.

The test was introduced in https://github.com/MaterializeInc/materialize/pull/17476

**Comment by def-** [comment]
I could reproduce this by running it 20 times at once with
```
count=20; for i in $(seq $count); do cargo nextest run test_query_on_dropped_source&; done
```

**Comment by jkosh44** [comment]
I'm very confused by the logs at first it says that it timed out:

```
        SLOW [>120.000s]               mz-environmentd::sql test_query_on_dropped_source
 TERMINATING [>240.000s]               mz-environmentd::sql test_query_on_dropped_source
     TIMEOUT [ 240.158s]               mz-environmentd::sql test_query_on_dropped_source
```

but then in the logs it shows the panic:

```
thread 'test_query_on_dropped_source' panicked at 'called `Result::unwrap()` on an `Err` value: "no active query"', src/environmentd/tests/sql.rs:2568:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1790:5
   3: <core::result::Result<(), &str>>::unwrap
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1112:23
   4: sql::test_query_on_dropped_source::test_query_on_dropped_source_inner::<sql::test_query_on_dropped_source::{closure#0}>
             at ./tests/sql.rs:2555:9
   5: sql::test_query_on_dropped_source
             at ./tests/sql.rs:2615:5
   6: sql::test_query_on_dropped_source::{closure#0}
             at ./tests/sql.rs:2522:35
   7: <sql::test_query_on_dropped_source::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

------------
     Summary [ 512.205s] 554 tests run: 552 passed, 1 failed, 1 timed out, 4 skipped
        FAIL [   8.295s]              mz-environmentd::auth test_auth_expiry

--- STDOUT:                           mz-environmentd::auth test_auth_expiry ---

running 1 test
test test_auth_expiry ... FAILED

failures:

failures:
    test_auth_expiry

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 3 filtered out; finished in 8.09s
```

I also see some cockroach errors in the same logs:

```
--- STDERR:                           mz-environmentd::auth test_auth_expiry ---
thread 'test_auth_expiry' panicked at 'called `Result::unwrap()` on an `Err` value: stash error: postgres: db error: ERROR: internal error: deadline below read timestamp is nonsensical; txn has would have no chance to commit. Deadline: 1683717315.269893936,1. Read timestamp: 1683717315.269893936,2 Previous Deadline: 1683717315.269893936,1.
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/kv/txn.go:775: UpdateDeadline()
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/leased_descriptors.go:220: maybeUpdateDeadline()
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/leased_descriptors.go:186: getResult()
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/leased_descriptors.go:108: getByName()
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:496: func6()
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:523: getNonVirtualDescriptorID()
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:328: getDescriptorByName()
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/object.go:53: GetObjectByName()
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/table.go:53: getTableByName()
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/table.go:44: GetImmutableTableByName()
github.com/cockroachdb/cockroach/pkg/sql/syntheticprivilegecache/cache.go:75: Get()
github.com/cockroachdb/cockroach/pkg/sql/grant_revoke_system.go:247: SynthesizePrivilegeDescriptor()
github.com/cockroachdb/cockroach/pkg/sql/syntheticprivilege/vtable_privilege.go:48: GetPrivilegeDescriptor()
github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/table_desc.go:654: GetPrivilegeDescriptor()
github.com/cockroachdb/cockroach/pkg/sql/authorization.go:244: getOwnerOfPrivilegeObject()
github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:626: getOwnerName()
github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:2878: 1()
github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2427: func1()
github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2610: func1()
github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2626: forEachTableDescWithTableLookupInternalFromDescriptors()
github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2548: forEachTableDescWithTableLookupInternal()
github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2493: forEachTableDescWithTableLookup()
github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2421: forEachTableDesc()
github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:2873: func235()
github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:613: 1()
github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:127: func3()
github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:489: func2()
GOROOT/src/runtime/asm_amd64.s:1594: goexit()

HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.
```

**Comment by jkosh44** [comment]
I got a repro locally. What's supposed to happen is the following:
- Asynchronous thread starts a query that never returns (like `SUBSCRIBE t`).
- Main thread waits for up to 10 seconds for `mz_compute_exports` to be updated.

When this test fails, the query successfully starts and never returns, but after 10 seconds there's been no update to `mz_compute_exports`.

**Comment by jkosh44** [comment]
Increasing the wait time to 100 seconds increasing the success rate, but we still have a lot of failures.
