### ISSUE TITLE
[SQLsmith] thread 'coordinator' panicked at 'ScalarType::unwrap_list_nth_layer_type called on Numeric { max_scale: Some(NumericMaxScale(0)) }', src/repr/src/scalar.rs:2082:18

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#19273]
### What version of Materialize are you using?

 v0.55.0-dev (357bc0671)

### What is the issue?

Noticed in nightly: https://buildkite.com/materialize/nightlies/builds/2363#_
```
CREATE SOURCE tpch
              FROM LOAD GENERATOR TPCH (SCALE FACTOR 0.00001)
              FOR ALL TABLES
              WITH (SIZE = '1');
select  
  subq_0."c2" as c0, 
  (select "id" from mz_internal.mz_records_per_dataflow limit 1 offset 62)
     as c1, 
  subq_0."c2" as c2
from 
  (select  
        ref_0."id" as c0, 
        ref_0."name" as c1, 
        (select "count" from mz_internal.mz_scheduling_parks_histogram_per_worker limit 1 offset 3)
           as c2, 
        ref_0."name" as c3, 
        ref_0."records" as c4, 
        ref_0."batches" as c5
      from 
        mz_internal.mz_dataflow_arrangement_sizes as ref_0
      where pg_catalog.date(
          CAST((select "updated_at" from mz_internal.mz_cluster_replica_statuses limit 1 offset 5)
             as timestamptz)) < (select "o_orderdate" from public.orders limit 1 offset 1)
          
      limit 140) as subq_0
where subq_0."c5" > subq_0."c5"
limit 21;
```
Panic from logs:
```
thread 'coordinator' panicked at 'ScalarType::unwrap_list_nth_layer_type called on Numeric { max_scale: Some(NumericMaxScale(0)) }', src/repr/src/scalar.rs:2082:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/core/src/panicking.rs:67:14
   2: mz_repr::scalar::ScalarType::unwrap_list_nth_layer_type
             at ./src/repr/src/scalar.rs:2082:18
   3: mz_expr::scalar::func::VariadicFunc::output_type
             at ./src/expr/src/scalar/func.rs:6792:26
   4: mz_transform::typecheck::Typecheck::typecheck_scalar::{{closure}}
             at ./src/transform/src/typecheck.rs:1074:48
   5: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
   6: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
   7: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
   8: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
   9: mz_transform::typecheck::Typecheck::typecheck_scalar
             at ./src/transform/src/typecheck.rs:1040:9
  10: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:692:41
  11: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  12: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  13: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  14: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  15: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:9
  16: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:544:28
  17: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  18: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  19: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  20: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  21: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:9
  22: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:755:28
  23: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  24: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  25: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  26: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  27: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:9
  28: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:559:32
  29: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  30: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  31: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  32: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  33: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:9
  34: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:544:28
  35: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  36: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  37: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  38: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  39: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:9
  40: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:906:28
  41: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  42: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  43: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  44: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  45: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:9
  46: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:623:33
  47: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  48: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  49: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  50: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  51: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:9
  52: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:583:32
  53: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  54: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  55: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  56: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  57: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:9
  58: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:544:28
  59: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  60: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  61: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  62: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  63: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:9
  64: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:777:28
  65: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  66: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  67: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  68: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  69: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:9
  70: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:583:32
  71: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  72: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  73: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  74: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  75: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:9
  76: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:544:28
  77: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  78: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  79: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  80: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  81: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:9
  82: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:906:28
  83: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  84: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  85: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  86: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  87: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:9
  88: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:623:33
  89: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  90: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  91: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  92: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  93: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:9
  94: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:544:28
  95: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  96: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  97: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  98: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  99: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:9
 100: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:861:17
 101: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
 102: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
 103: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
 104: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
 105: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:9
 106: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:861:17
 107: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
 108: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
 109: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
 110: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
 111: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:9
 112: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:861:17
 113: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
 114: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
 115: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
 116: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
 117: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:9
 118: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:861:17
 119: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
 120: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
 121: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
 122: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
 123: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:9
 124: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:861:17
 125: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
 126: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
 127: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
 128: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
 129: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:9
 130: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:861:17
 131: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
 132: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
 133: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
 134: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
 135: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:9
 136: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:861:17
 137: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
 138: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
 139: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
 140: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
 141: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:9
 142: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:861:17
 143: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
 144: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
 145: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
 146: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
 147: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:9
 148: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:861:17
 149: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
 150: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
 151: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
 152: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
 153: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:9
 154: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:861:17
 155: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
 156: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
 157: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
 158: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
 159: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:9
 160: <mz_transform::typecheck::Typecheck as mz_transform::Transform>::transform
             at ./src/transform/src/typecheck.rs:1178:19
 161: mz_transform::Optimizer::transform
             at ./src/transform/src/lib.rs:696:17
 162: mz_transform::dataflow::optimize_dataflow_relations
             at ./src/transform/src/dataflow.rs:203:9
 163: mz_transform::dataflow::optimize_dataflow
             at ./src/transform/src/dataflow.rs:68:5
 164: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::peek_stage_optimize
             at ./src/adapter/src/coord/sequencer/inner.rs:2168:9
 165: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::sequence_peek_stage::{{closure}}
             at ./src/adapter/src/coord/sequencer/inner.rs:2014:40
 166: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::sequence_peek::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer/inner.rs:1983:9
 167: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::sequence_peek::{{closure}}
             at ./src/adapter/src/coord/sequencer/inner.rs:1965:5
```

@mgree I bisected this back to:
```
68152c798309636d009827a4b7f970ce95f854e1 is the first bad commit
commit 68152c798309636d009827a4b7f970ce95f854e1
Author: Michael Greenberg <michael.greenberg@materialize.com>
Date:   Fri May 12 15:28:58 2023 -0400

    MIR type checking (#18666)

    An MIR typechecker that goes beyond `col_with_input_cols` to do thorough internal consistency checking. As we consider changes to the MIR optimizer, having thorough consistency checking will help us catch corner-case regressions before they manifest as runtime failures.

    The type checker is run at the beginning and end of each phase of the optimizer; as the checker runs, it collects type information for the plans corresponding to every global ID. When the type checker re-encounters a global ID's optimized plan, it checks the optimized plan for consistency and confirms that the new plan's type agrees with the
    old one.

    Note that this type comparison is about the external, visible type of the expression---internally types can change radically, but the visible type of a global ID is treated as stable.

    The typechecker is imprecise in a few ways:

    - Not all globals are accounted for.
    - Some nullability information on local (let-bound) variables is incorrect.
    - Join equivalences should always have at least one non-nullable field, but that invariant isn't upheld by the optimizer and/or the typechecker is not precise enough to notice.

    If you get any type errors, noisy logs, or have other questions about the typechecker, please use https://github.com/MaterializeInc/materialize/issues/19101 to discuss them.

 Cargo.lock                                       |    1 +
 src/adapter/src/catalog.rs                       |    9 +-
 src/adapter/src/coord.rs                         |    4 +-
 src/adapter/src/coord/sequencer/inner.rs         |    6 +-
 src/expr/Cargo.toml                              |    1 +
 src/expr/src/lib.rs                              |    6 +-
 src/expr/src/relation/mod.rs                     |   78 +-
 src/transform/Cargo.toml                         |    2 +-
 src/transform/src/dataflow.rs                    |   19 +-
 src/transform/src/fusion/filter.rs               |    1 +
 src/transform/src/lib.rs                         |   96 +-
 src/transform/src/predicate_pushdown.rs          |    1 +
 src/transform/src/typecheck.rs                   | 1482 ++++++++++++++++++++++
 src/transform/tests/test_runner.rs               |   45 +-
 src/transform/tests/testdata/join-implementation |   16 +-
 src/transform/tests/testdata/keys                |   42 +-
 src/transform/tests/testdata/reduction-pushdown  |   16 +-
 src/transform/tests/testdata/steps               |   14 +-
 18 files changed, 1705 insertions(+), 134 deletions(-)
 create mode 100644 src/transform/src/typecheck.rs
```

Marked as release-blocker since it's a regression and panic.

ci-regexp: ScalarType::unwrap_list_nth_layer_type called on Numeric

**Comment by ggevay** [comment]
The bisected commit is not part of this week's release, so this will be a release blocker for next week's release. I'm removing the tag for now to avoid confusing people that are working on this week's release.

**Comment by ggevay** [comment]
Found the problem: Around [here](https://github.com/MaterializeInc/materialize/blob/68152c798309636d009827a4b7f970ce95f854e1/src/transform/src/typecheck.rs#L692), column indexes in the keys are local to a join input, but `typecheck_scalar` gets the global input column types.
