### ISSUE TITLE
[SQLsmith] thread 'coordinator' panicked at 'called `Result::unwrap()` on an `Err` value: Can't union types: UInt64 and Int32

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#19283]
### What version of Materialize are you using?

v0.55.0-dev (357bc06)

### What is the issue?

Seen in nightlies with SQLsmith, reproducer:
```
CREATE TABLE t (a int, b int);
select
  96 as c0,
  subq_0."c1" as c1
from
  (select
        ref_0."name" as c0,
        21 as c1
      from
        mz_internal.mz_dataflow_operator_dataflows as ref_0
      where (select pg_catalog.count("batches") from mz_internal.mz_arrangement_sizes_per_worker)
           = cast(coalesce((select "a" from public.t limit 1 offset 6)
            ,
          pg_catalog.pg_backend_pid()) as int4)) as subq_0
where (subq_0."c1" <= subq_0."c1")
  or (pg_catalog.mod(
      CAST(cast(null as uint2) as uint2),
      CAST(pg_catalog.mod(
        CAST(pg_catalog.mod(
          CAST(cast(nullif(cast(null as uint2),
            cast(null as uint2)) as uint2) as uint2),
          CAST(cast(nullif(cast(null as uint2),
            cast(null as uint2)) as uint2) as uint2)) as uint2),
        CAST(pg_catalog.mod(
          CAST(case when (cast(null as uuid) <= (select "id" from mz_internal.mz_active_peeks limit 1 offset 1)
                  )
              or ((false)
                and (subq_0."c1" is not NULL)) then cast(null as uint2) else cast(null as uint2) end
             as uint2),
          CAST(cast(null as uint2) as uint2)) as uint2)) as uint2)) <> cast(nullif(cast(nullif(cast(null as uint2),
        pg_catalog.mod(
          CAST(case when (select "count" from mz_internal.mz_compute_operator_durations_histogram limit 1 offset 6)
                 > cast(null as numeric) then cast(null as uint2) else cast(null as uint2) end
             as uint2),
          CAST(cast(null as uint2) as uint2))) as uint2),
      cast(null as uint2)) as uint2))
limit 99;
```
Panic from logs:
```
thread 'coordinator' panicked at 'called `Result::unwrap()` on an `Err` value: Can't union types: UInt64 and Int32

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.66/src/error.rs:83:36
   1: mz_repr::relation::ColumnType::union
             at ./src/repr/src/relation.rs:109:18
   2: mz_expr::scalar::func::VariadicFunc::output_type::{{closure}}
             at ./src/expr/src/scalar/func.rs:6754:32
   3: core::iter::traits::iterator::Iterator::fold
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/core/src/iter/traits/iterator.rs:2481:21
   4: core::iter::traits::iterator::Iterator::reduce
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/core/src/iter/traits/iterator.rs:2518:14
   5: mz_expr::scalar::func::VariadicFunc::output_type
             at ./src/expr/src/scalar/func.rs:6752:44
   6: mz_transform::typecheck::Typecheck::typecheck_scalar::{{closure}}
             at ./src/transform/src/typecheck.rs:1074:48
   7: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
   8: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
   9: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  10: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  11: mz_transform::typecheck::Typecheck::typecheck_scalar
             at ./src/transform/src/typecheck.rs:1040:14
  12: mz_transform::typecheck::Typecheck::typecheck_scalar::{{closure}}
             at ./src/transform/src/typecheck.rs:1068:37
  13: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  14: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  15: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  16: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  17: mz_transform::typecheck::Typecheck::typecheck_scalar
             at ./src/transform/src/typecheck.rs:1040:14
  18: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:698:41
  19: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  20: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  21: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  22: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  23: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:14
  24: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:559:32
  25: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  26: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  27: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  28: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  29: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:14
  30: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:583:32
  31: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  32: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  33: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  34: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  35: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:14
  36: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:544:28
  37: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  38: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  39: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  40: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  41: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:14
  42: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:861:17
  43: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  44: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  45: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  46: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  47: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:14
  48: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:861:17
  49: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  50: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  51: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  52: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  53: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:14
  54: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:861:17
  55: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  56: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  57: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  58: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  59: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:14
  60: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:861:17
  61: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  62: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  63: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  64: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  65: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:14
  66: <mz_transform::typecheck::Typecheck as mz_transform::Transform>::transform
             at ./src/transform/src/typecheck.rs:1178:19
  67: mz_transform::Optimizer::transform
             at ./src/transform/src/lib.rs:696:17
  68: mz_transform::dataflow::optimize_dataflow_relations
             at ./src/transform/src/dataflow.rs:203:9
  69: mz_transform::dataflow::optimize_dataflow
             at ./src/transform/src/dataflow.rs:68:5
  70: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::peek_stage_optimize
             at ./src/adapter/src/coord/sequencer/inner.rs:2168:9
  71: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::sequence_peek_stage::{{closure}}
             at ./src/adapter/src/coord/sequencer/inner.rs:2014:40
  72: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::sequence_peek::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer/inner.rs:1983:9
  73: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::sequence_peek::{{closure}}
             at ./src/adapter/src/coord/sequencer/inner.rs:1965:5
  74: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_plan::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:254:70
  75: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_plan::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:54:5
  76: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute_inner::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:559:78
  77: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute_inner::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:360:5
  78: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:357:61
  79: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:300:5
  80: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  81: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_command::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:79:21
  82: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_command::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:245:33
  83: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_command::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:242:5
  84: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::handle_message::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:45:63
  85: mz_adapter::coord::Coordinator::serve::{{closure}}
             at ./src/adapter/src/coord.rs:1391:37
  86: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/park.rs:283:63
  87: tokio::runtime::coop::with_budget
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/coop.rs:107:5
  88: tokio::runtime::coop::budget
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/coop.rs:73:5
  89: tokio::runtime::park::CachedParkThread::block_on
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/park.rs:283:31
  90: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/context.rs:315:13
  91: tokio::runtime::handle::Handle::block_on
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/handle.rs:264:9
  92: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./src/adapter/src/coord.rs:1608:17
  93: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/std/src/sys_common/backtrace.rs:134:18
  94: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/std/src/thread/mod.rs:526:17
  95: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/core/src/panic/unwind_safe.rs:271:9
  96: std::panicking::try::do_call
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/std/src/panicking.rs:485:40
  97: std::panicking::try
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/std/src/panicking.rs:449:19
  98: std::panic::catch_unwind
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/std/src/panic.rs:140:14
  99: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/std/src/thread/mod.rs:525:30
 100: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/core/src/ops/function.rs:250:5
 101: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/alloc/src/boxed.rs:1962:9
 102: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/alloc/src/boxed.rs:1962:9
 103: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/std/src/sys/unix/thread.rs:108:17
 104: start_thread
             at ./nptl/pthread_create.c:442:8
 105: __GI___clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81', src/expr/src/scalar/func.rs:6754:44
stack backtrace:
   0: rust_begin_unwind
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/core/src/result.rs:1076:23
   4: mz_expr::scalar::func::VariadicFunc::output_type::{{closure}}
             at ./src/expr/src/scalar/func.rs:6754:32
   5: core::iter::traits::iterator::Iterator::fold
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/core/src/iter/traits/iterator.rs:2481:21
   6: core::iter::traits::iterator::Iterator::reduce
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/core/src/iter/traits/iterator.rs:2518:14
   7: mz_expr::scalar::func::VariadicFunc::output_type
             at ./src/expr/src/scalar/func.rs:6752:44
   8: mz_transform::typecheck::Typecheck::typecheck_scalar::{{closure}}
             at ./src/transform/src/typecheck.rs:1074:48
   9: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  10: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  11: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  12: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  13: mz_transform::typecheck::Typecheck::typecheck_scalar
             at ./src/transform/src/typecheck.rs:1040:14
  14: mz_transform::typecheck::Typecheck::typecheck_scalar::{{closure}}
             at ./src/transform/src/typecheck.rs:1068:37
  15: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  16: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  17: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  18: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  19: mz_transform::typecheck::Typecheck::typecheck_scalar
             at ./src/transform/src/typecheck.rs:1040:14
  20: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:698:41
  21: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  22: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  23: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  24: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  25: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:14
  26: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:559:32
  27: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  28: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  29: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  30: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  31: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:14
  32: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:583:32
  33: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  34: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  35: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  36: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  37: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:14
  38: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:544:28
  39: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  40: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  41: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  42: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  43: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:14
  44: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:861:17
  45: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  46: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  47: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  48: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  49: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:14
  50: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:861:17
  51: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  52: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  53: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  54: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  55: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:14
  56: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:861:17
  57: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  58: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  59: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  60: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  61: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:14
  62: mz_transform::typecheck::Typecheck::typecheck::{{closure}}
             at ./src/transform/src/typecheck.rs:861:17
  63: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  64: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  65: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  66: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  67: mz_transform::typecheck::Typecheck::typecheck
             at ./src/transform/src/typecheck.rs:482:14
  68: <mz_transform::typecheck::Typecheck as mz_transform::Transform>::transform
             at ./src/transform/src/typecheck.rs:1178:19
  69: mz_transform::Optimizer::transform
             at ./src/transform/src/lib.rs:696:17
  70: mz_transform::dataflow::optimize_dataflow_relations
             at ./src/transform/src/dataflow.rs:203:9
  71: mz_transform::dataflow::optimize_dataflow
             at ./src/transform/src/dataflow.rs:68:5
  72: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::peek_stage_optimize
             at ./src/adapter/src/coord/sequencer/inner.rs:2168:9
  73: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::sequence_peek_stage::{{closure}}
             at ./src/adapter/src/coord/sequencer/inner.rs:2014:40
  74: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::sequence_peek::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer/inner.rs:1983:9
  75: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::sequence_peek::{{closure}}
             at ./src/adapter/src/coord/sequencer/inner.rs:1965:5
  76: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_plan::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:254:70
  77: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_plan::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:54:5
  78: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute_inner::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:559:78
  79: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute_inner::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:360:5
  80: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:357:61
  81: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:300:5
  82: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  83: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_command::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:79:21
  84: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_command::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:245:33
  85: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_command::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:242:5
  86: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::handle_message::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:45:63
  87: mz_adapter::coord::Coordinator::serve::{{closure}}
             at ./src/adapter/src/coord.rs:1391:37
  88: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/park.rs:283:63
  89: tokio::runtime::coop::with_budget
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/coop.rs:107:5
  90: tokio::runtime::coop::budget
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/coop.rs:73:5
  91: tokio::runtime::park::CachedParkThread::block_on
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/park.rs:283:31
  92: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/context.rs:315:13
  93: tokio::runtime::handle::Handle::block_on
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/handle.rs:264:9
  94: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./src/adapter/src/coord.rs:1608:17
```
This might be related to https://github.com/MaterializeInc/materialize/issues/19273, it also started with 68152c798309636d009827a4b7f970ce95f854e1
@ggevay Can you tell if this has the same root cause or should be considered a separate issue?

**Comment by ggevay** [comment]
I'll fix the other one quickly, and then we'll see.

**Comment by ggevay** [comment]
Yes, same bug, opened PR: https://github.com/MaterializeInc/materialize/pull/19285
