### ISSUE TITLE
test_max_connections is still flaky

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#19395]
### What version of Materialize are you using?

ba9c5d644747326d4355d3a2461c36b84b78137d

### What is the issue?

After https://github.com/MaterializeInc/materialize/issues/19194 has been fixed we are still seeing flakes in test_max_connections: https://buildkite.com/materialize/tests/builds/55937#01883986-ca89-438e-8e71-fe660abf0145
```
[2023-05-20T14:31:14Z] thread 'test_max_connections' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "FATAL", parsed_severity: None, code: SqlState(E53000), message: "creating connection would violate max_connections limit (desired: 2, limit: 1, current: 1)", detail: None, hint: Some("Drop an existing connection or contact sales to request a limit increase."), position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: None, line: None, routine: None }) }', src/environmentd/tests/sql.rs:3179:55
[2023-05-20T14:31:14Z] stack backtrace:
[2023-05-20T14:31:14Z]    0: rust_begin_unwind
[2023-05-20T14:31:14Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
[2023-05-20T14:31:14Z]    1: core::panicking::panic_fmt
[2023-05-20T14:31:14Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
[2023-05-20T14:31:14Z]    2: core::result::unwrap_failed
[2023-05-20T14:31:14Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1790:5
[2023-05-20T14:31:14Z]    3: <core::result::Result<postgres::client::Client, tokio_postgres::error::Error>>::unwrap
[2023-05-20T14:31:14Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1112:23
[2023-05-20T14:31:14Z]    4: sql::test_max_connections
[2023-05-20T14:31:14Z]              at ./tests/sql.rs:3179:23
[2023-05-20T14:31:14Z]    5: sql::test_max_connections::{closure#0}
[2023-05-20T14:31:14Z]              at ./tests/sql.rs:3122:27
[2023-05-20T14:31:14Z]    6: <sql::test_max_connections::{closure#0} as core::ops::function::FnOnce<()>>::call_once
[2023-05-20T14:31:14Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
[2023-05-20T14:31:14Z]    7: core::ops::function::FnOnce::call_once
[2023-05-20T14:31:14Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
[2023-05-20T14:31:14Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
@andrewrodriguez-m

**Comment by def-** [comment]
@andrewrodriguez-m Can you look into this please? I keep getting it even on retries: https://buildkite.com/materialize/tests/builds/56031#0188458c-77f8-4c63-8aa8-7d86d17ccc20
Otherwise would make sense to disable the test so it doesn't block others.
