### ISSUE TITLE
thread 'coordinator' panicked at 'unable to confirm leadership: Catalog(Error { kind: Stash(StashError { inner: Postgres(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42P01), message: "relation \"fence\" does not exist", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("errors.go"), line: Some(172), routine: Some("NewUndefinedRelationError") }) }) }) })', /home/deen/git/materialize2/src/adapter/src/util.rs:280:23

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#19937]
### What version of Materialize are you using?

db659b3aa58a4b9c620b708ada4cb257b63e6920

### What is the issue?

```
$ RUST_BACKTRACE=1 bin/sqllogictest -- test/sqllogictest/arithmetic.slt
[...]
==> test/sqllogictest/autogenerated/char-varchar-comparisons.slt
thread 'coordinator' panicked at 'unable to confirm leadership: Catalog(Error { kind: Stash(StashError { inner: Postgres(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42P01), message: "relation \"fence\" does not exist", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("errors.go"), line: Some(172), routine: Some("NewUndefinedRelationError") }) }) }) })', /home/deen/git/materialize2/src/adapter/src/util.rs:280:23
stack backtrace:
2023-06-14T16:17:43.908332Z  INFO mz_persist_client::internal::machine: external operation fetch_state::scan failed, retrying in 32ms: indeterminate: db error: ERROR: relation "consensus" does not exist
2023-06-14T16:17:43.941186Z  INFO mz_persist_client::internal::machine: external operation fetch_state::scan failed, retrying in 64ms: indeterminate: db error: ERROR: relation "consensus" does not exist
2023-06-14T16:17:44.003389Z  INFO mz_persist_client::internal::machine: external operation fetch_state::scan failed, retrying in 32ms: indeterminate: db error: ERROR: relation "consensus" does not exist
2023-06-14T16:17:44.004889Z  INFO mz_persist_client::internal::machine: external operation fetch_state::scan failed, retrying in 32ms: indeterminate: db error: ERROR: relation "consensus" does not exist
2023-06-14T16:17:44.009647Z  INFO mz_persist_client::internal::machine: external operation fetch_state::scan failed, retrying in 128ms: indeterminate: db error: ERROR: relation "consensus" does not exist
   0: rust_begin_unwind
             at /home/deen/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /home/deen/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:67:14
   2: <core::result::Result<T,E> as mz_adapter::util::ResultExt<T>>::unwrap_or_terminate
             at ./src/adapter/src/util.rs:280:23
2023-06-14T16:17:44.016151Z  INFO mz_persist_client::internal::machine: external operation fetch_state::scan failed, retrying in 32ms: indeterminate: db error: ERROR: relation "consensus" does not exist
2023-06-14T16:17:44.018907Z  INFO mz_persist_client::internal::machine: external operation fetch_state::scan failed, retrying in 32ms: indeterminate: db error: ERROR: relation "consensus" does not exist
2023-06-14T16:17:44.018956Z  INFO mz_persist_client::internal::machine: external operation fetch_state::scan failed, retrying in 32ms: indeterminate: db error: ERROR: relation "consensus" does not exist
2023-06-14T16:17:44.019323Z  INFO mz_persist_client::internal::machine: external operation fetch_state::scan failed, retrying in 32ms: indeterminate: db error: ERROR: relation "consensus" does not exist
2023-06-14T16:17:44.021179Z  INFO mz_persist_client::internal::machine: external operation fetch_state::scan failed, retrying in 32ms: indeterminate: db error: ERROR: relation "consensus" does not exist
2023-06-14T16:17:44.021884Z  INFO mz_persist_client::internal::machine: external operation fetch_state::scan failed, retrying in 32ms: indeterminate: db error: ERROR: relation "consensus" does not exist
   3: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_linearize_reads::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:604:13
   4: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_linearize_reads::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:573:5
   5: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::handle_message::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:78:64
   6: mz_adapter::coord::Coordinator::serve::{{closure}}
             at ./src/adapter/src/coord.rs:1436:37
   7: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/park.rs:283:63
   8: tokio::runtime::coop::with_budget
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/coop.rs:107:5
   9: tokio::runtime::coop::budget
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/coop.rs:73:5
  10: tokio::runtime::park::CachedParkThread::block_on
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/park.rs:283:31
2023-06-14T16:17:44.036586Z  INFO mz_persist_client::internal::machine: external operation fetch_state::scan failed, retrying in 32ms: indeterminate: db error: ERROR: relation "consensus" does not exist
  11: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/context.rs:315:13
  12: tokio::runtime::handle::Handle::block_on
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/handle.rs:264:9
2023-06-14T16:17:44.040908Z  INFO mz_persist_client::internal::machine: external operation fetch_state::scan failed, retrying in 64ms: indeterminate: db error: ERROR: relation "consensus" does not exist
2023-06-14T16:17:44.041521Z  INFO mz_persist_client::internal::machine: external operation fetch_state::scan failed, retrying in 64ms: indeterminate: db error: ERROR: relation "consensus" does not exist
  13: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./src/adapter/src/coord.rs:1657:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
This is part of https://github.com/MaterializeInc/materialize/issues/19934
Happens with ee4c7341ba5396bb4c8bb7b5fa09e9587fd97201

I think this is a timing issue. Would be nice to have it fixed so that we can enable ASan/valgrind testing.

**Comment by def-** [comment]
Same with valgrind on 3c33befedc1ce976a6f657fc4a10a821e3a8ec43 (main state):
```
$ valgrind --tool=memcheck /home/deen/git/materialize/target/release/sqllogictest --postgres-url=postgres://root@localhost:26257/materialize -v test/sqllogictest/*.slt
[...]
thread 'coordinator' panicked at 'can't persist timestamp: Error { kind: Stash(StashError { inner: Postgres(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42P01), message: "relation \"fence\" does not exist", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("errors.go"), line: Some(172), routine: Some("NewUndefinedRelationError") }) }) }) }', /home/deen/git/materialize/src/adapter/src/util.rs:280:23
stack backtrace:
==2294420== Warning: set address range perms: large range [0x59c87000, 0xa1e2e000) (defined)
   0: rust_begin_unwind
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/458d4dae845ec155b285681a5b88305641abb868/library/core/src/panicking.rs:67:14
   2: <core::result::Result<T,E> as mz_adapter::util::ResultExt<T>>::unwrap_or_terminate
             at ./src/adapter/src/util.rs:280:23
   3: mz_adapter::coord::timeline::DurableTimestampOracle<T>::maybe_allocate_new_timestamps::{{closure}}
             at ./src/adapter/src/coord/timeline.rs:340:13
   4: mz_adapter::coord::timeline::DurableTimestampOracle<T>::write_ts::{{closure}}
             at ./src/adapter/src/coord/timeline.rs:288:13
   5: mz_adapter::coord::timeline::<impl mz_adapter::coord::Coordinator>::get_local_write_ts::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/timeline.rs:404:13
   6: mz_adapter::coord::timeline::<impl mz_adapter::coord::Coordinator>::get_local_write_ts::{{closure}}
             at ./src/adapter/src/coord/timeline.rs:394:5
   7: mz_adapter::coord::appends::<impl mz_adapter::coord::Coordinator>::group_commit_initiate::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/appends.rs:244:38
   8: mz_adapter::coord::appends::<impl mz_adapter::coord::Coordinator>::group_commit_initiate::{{closure}}
             at ./src/adapter/src/coord/appends.rs:186:5
   9: mz_adapter::coord::appends::<impl mz_adapter::coord::Coordinator>::try_group_commit::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/appends.rs:170:45
  10: mz_adapter::coord::appends::<impl mz_adapter::coord::Coordinator>::try_group_commit::{{closure}}
             at ./src/adapter/src/coord/appends.rs:150:5
  11: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::handle_message::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:61:40
  12: mz_adapter::coord::Coordinator::serve::{{closure}}
             at ./src/adapter/src/coord.rs:1436:37
  13: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/park.rs:283:63
  14: tokio::runtime::coop::with_budget
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/coop.rs:107:5
  15: tokio::runtime::coop::budget
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/coop.rs:73:5
  16: tokio::runtime::park::CachedParkThread::block_on
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/park.rs:283:31
  17: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/context.rs:315:13
  18: tokio::runtime::handle::Handle::block_on
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/handle.rs:264:9
  19: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./src/adapter/src/coord.rs:1657:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by ParkMyCar** [comment]
This is odd, it seems like the panic is because the "fence" table doesn't exist, which it always should? 

@def- it looks like https://github.com/MaterializeInc/materialize/commit/ee4c7341ba5396bb4c8bb7b5fa09e9587fd97201 introduces more sanitizers (wooo!) but that shouldn't change the order of execution for anything I don't think?

Shot in the dark, maybe the `search_path` is set to the wrong schema?

**Comment by def-** [comment]
Doesn't change the order, just makes everything slower.

**Comment by mjibson** [comment]
Gut thoughts from our team is this is an issue with the test infra and not a bug in the stash or envd code. We aren't planning on looking deeper until there's more evidence that it might be our bug.

**Comment by def-** [comment]
Also seen in restart test: https://buildkite.com/materialize/tests/builds/66080#018b391e-8f27-4d4a-8077-7fe2cd63149d
