### ISSUE TITLE
thread 'timely:work-2' panicked at 'only alter compatible ingestions permitted: InvalidAlterSource { id: User(7) }'

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#19987]
### What version of Materialize are you using?

b761ddc

### What is the issue?

Nightly is showing crashes in Zippy: https://buildkite.com/materialize/nightlies/builds/2606

```
thread 'thread 'thread 'timely:work-1timely:work-0timely:work-3' panicked at '' panicked at '' panicked at 'only alter compatible ingestions permitted: InvalidAlterSource { id: User(7) }only alter compatible ingestions permitted: InvalidAlterSource { id: User(7) }only alter compatible ingestions permitted: InvalidAlterSource { id: User(7) }', ', ', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03de4ed6b11aa039b-1/materialize/tests/src/storage/src/storage_state.rs/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03de4ed6b11aa039b-1/materialize/tests/src/storage/src/storage_state.rs::/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03de4ed6b11aa039b-1/materialize/tests/src/storage/src/storage_state.rs1018:1018:1018:34:34
34

stack backtrace:
thread 'timely:work-2' panicked at 'only alter compatible ingestions permitted: InvalidAlterSource { id: User(7) }', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03de4ed6b11aa039b-1/materialize/tests/src/storage/src/storage_state.rs:1018:34
2023-06-15T23:35:11.615238Z  INFO mz_compute::compute_state: Applying configuration update: ComputeParameters { max_result_size: Some(1073741824), dataflow_max_inflight_bytes: Some(18446744073709551615), enable_mz_join_core: Some(false), persist: PersistParameters { blob_target_size: Some(134217728), blob_cache_mem_limit_bytes: Some(1048576), compaction_minimum_timeout: Some(90s), consensus_connect_timeout: Some(5s), consensus_tcp_user_timeout: Some(30s), next_listen_batch_retryer: Some(RetryParameters { initial_backoff: 4ms, multiplier: 2, clamp: 16s }), sink_minimum_batch_updates: Some(128), storage_sink_minimum_batch_updates: Some(100), stats_audit_percent: Some(100), stats_collection_enabled: Some(true), stats_filter_enabled: Some(true), pubsub_client_enabled: Some(true), pubsub_push_diff_enabled: Some(true), rollup_threshold: Some(128) } }
2023-06-15T23:35:11.615266Z  INFO mz_compute::compute_state: Applying configuration update: ComputeParameters { max_result_size: Some(1073741824), dataflow_max_inflight_bytes: Some(18446744073709551615), enable_mz_join_core: Some(false), persist: PersistParameters { blob_target_size: Some(134217728), blob_cache_mem_limit_bytes: Some(1048576), compaction_minimum_timeout: Some(90s), consensus_connect_timeout: Some(5s), consensus_tcp_user_timeout: Some(30s), next_listen_batch_retryer: Some(RetryParameters { initial_backoff: 4ms, multiplier: 2, clamp: 16s }), sink_minimum_batch_updates: Some(128), storage_sink_minimum_batch_updates: Some(100), stats_audit_percent: Some(100), stats_collection_enabled: Some(true), stats_filter_enabled: Some(true), pubsub_client_enabled: Some(true), pubsub_push_diff_enabled: Some(true), rollup_threshold: Some(128) } }
2023-06-15T23:35:11.615270Z  INFO mz_compute::compute_state: Applying configuration update: ComputeParameters { max_result_size: Some(1073741824), dataflow_max_inflight_bytes: Some(18446744073709551615), enable_mz_join_core: Some(false), persist: PersistParameters { blob_target_size: Some(134217728), blob_cache_mem_limit_bytes: Some(1048576), compaction_minimum_timeout: Some(90s), consensus_connect_timeout: Some(5s), consensus_tcp_user_timeout: Some(30s), next_listen_batch_retryer: Some(RetryParameters { initial_backoff: 4ms, multiplier: 2, clamp: 16s }), sink_minimum_batch_updates: Some(128), storage_sink_minimum_batch_updates: Some(100), stats_audit_percent: Some(100), stats_collection_enabled: Some(true), stats_filter_enabled: Some(true), pubsub_client_enabled: Some(true), pubsub_push_diff_enabled: Some(true), rollup_threshold: Some(128) } }
2023-06-15T23:35:11.615252Z  INFO mz_compute::compute_state: Applying configuration update: ComputeParameters { max_result_size: Some(1073741824), dataflow_max_inflight_bytes: Some(18446744073709551615), enable_mz_join_core: Some(false), persist: PersistParameters { blob_target_size: Some(134217728), blob_cache_mem_limit_bytes: Some(1048576), compaction_minimum_timeout: Some(90s), consensus_connect_timeout: Some(5s), consensus_tcp_user_timeout: Some(30s), next_listen_batch_retryer: Some(RetryParameters { initial_backoff: 4ms, multiplier: 2, clamp: 16s }), sink_minimum_batch_updates: Some(128), storage_sink_minimum_batch_updates: Some(100), stats_audit_percent: Some(100), stats_collection_enabled: Some(true), stats_filter_enabled: Some(true), pubsub_client_enabled: Some(true), pubsub_push_diff_enabled: Some(true), rollup_threshold: Some(128) } }
   0: rust_begin_unwind
             at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1790:5
   3: <core::result::Result<(), mz_storage_client::controller::StorageError>>::expect
             at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1069:23
   4: <mz_storage::storage_state::Worker<timely_communication::allocator::generic::Generic>>::reconcile
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03de4ed6b11aa039b-1/materialize/tests/src/storage/src/storage_state.rs:1016:29
   5: <mz_storage::storage_state::Worker<timely_communication::allocator::generic::Generic>>::run_client
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03de4ed6b11aa039b-1/materialize/tests/src/storage/src/storage_state.rs:495:13
   6: <mz_storage::storage_state::Worker<timely_communication::allocator::generic::Generic>>::run
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03de4ed6b11aa039b-1/materialize/tests/src/storage/src/storage_state.rs:466:21
   7: <mz_storage::server::Config as mz_cluster::types::AsRunnableWorker<mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>>::build_and_run::<timely_communication::allocator::generic::Generic>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03de4ed6b11aa039b-1/materialize/tests/src/storage/src/server.rs:107:9
   8: <mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse, std::thread::Thread>, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>, mz_storage::server::Config, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>>::build_timely::{closure#0}::{closure#1}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03de4ed6b11aa039b-1/materialize/tests/src/cluster/src/server.rs:178:13
   9: timely::execute::execute_from::<timely_communication::allocator::generic::GenericBuilder, (), <mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse, std::thread::Thread>, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>, mz_storage::server::Config, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>>::build_timely::{closure#0}::{closure#1}>::{closure#0}
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/15ac623/timely/src/execute.rs:388:22
  10: timely_communication::initialize::initialize_from::<timely_communication::allocator::generic::GenericBuilder, (), timely::execute::execute_from<timely_communication::allocator::generic::GenericBuilder, (), <mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse, std::thread::Thread>, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>, mz_storage::server::Config, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>>::build_timely::{closure#0}::{closure#1}>::{closure#0}>::{closure#0}
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/15ac623/communication/src/initialize.rs:316:33
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1790:5
   3: <core::result::Result<(), mz_storage_client::controller::StorageError>>::expect
             at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1069:23
   4: <mz_storage::storage_state::Worker<timely_communication::allocator::generic::Generic>>::reconcile
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-03de4ed6b11aa039b-1/materialize/tests/src/storage/src/storage_state.rs:1016:29
   52023-06-15T23:35:22.720380Z  INFO clusterd: booting os.os_type=Ubuntu os.version=22.04 os.bitness=64-bit build.version="0.58.0-dev" build.sha="7d1f6e2830c835ed4d953ac7c29e4e157d31a1ef" build.time="2023-06-15T20:53:08Z" cpus.logical=32 cpus.physical=16 cpu0.brand="AMD EPYC 7R13 Processor" cpu0.frequency=2649 memory.total=66071543808 memory.used=4714688512 memory.limit=9223372036854771712 swap.total=0 swap.used=0 swap.limit=0 tracing.max_level=info
```
Caused by https://github.com/MaterializeInc/materialize/pull/19310
Marked as release blocker as this is a regression.

**Comment by sploiselle** [comment]
I have a definite fix for this locally and am just running tests against it. The problem was that, during a refactor of that PR, I dropped an `==` that used to run elsewhere.
