### ISSUE TITLE
environmentd segfaults in coverage builds

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#20016]
### What version of Materialize are you using?

main

### What is the issue?

But tests still succeed: https://buildkite.com/materialize/coverage/builds/141#0188c589-2b1c-454e-ba83-bc4a65b0e0a1
This has been happening since the first Coverage runs, but we didn't have detection for segfaults.
```
Apr 12 11:35:44 ip-10-61-169-162.ec2.internal kernel: environmentd[22580]: segfault at 7fe36582e090 ip 00007fe36556563b sp 00007fe36582e090 error 6 in libc.so.6[7fe365516000+195000]
Apr 12 11:35:44 ip-10-61-169-162.ec2.internal kernel: Code: 84 24 a6 00 00 00 01 e9 63 db ff ff 0f 1f 00 41 56 41 55 41 54 55 53 48 81 ec 00 10 00 00 48 83 0c 24 00 48 81 ec 00 10 00 00 <48> 83 0c 24 00 48 81 ec 30 01 00 00 64 48 8b 04 25 28 00 00 00 48
```
This could indicate a bug in the code coverage, or a timing related problem since coverage runs are about 2x slower.

**Comment by def-** [comment]
This happens while stopping the program, and appears to be an issue in Rust's coverage profile writing:
```
Core was generated by `/home/deen/git/materialize2/target/debug/environmentd --internal-http-listen-ad'.
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Section `.reg-xstate/2427595' in core file too small.
#0  0x0000563df58ffe9e in _rjem_je_free_default (ptr=0x0) at src/jemalloc.c:2996
2996	free_default(void *ptr) {
[Current thread is 1 (Thread 0x7f3973c7f000 (LWP 2427595))]
warning: Missing auto-load script at offset 0 in section .debug_gdb_scripts
of file /home/deen/git/materialize2/target/debug/environmentd.
Use `info auto-load python-scripts [REGEXP]' to list them.
(gdb) bt
#0  0x0000563df58ffe9e in _rjem_je_free_default (ptr=0x0) at src/jemalloc.c:2996
#1  0x0000563df5915c47 in free (ptr=0x0) at src/jemalloc.c:3162
#2  0x00007f3973687b69 in __GI__IO_free_backup_area (fp=fp@entry=0x7f397335d000) at ./libio/genops.c:190
#3  0x00007f3973684ab0 in _IO_new_file_seekoff (fp=0x7f397335d000, offset=0, dir=0, mode=<optimized out>)
    at ./libio/fileops.c:975
#4  0x00007f3973681c09 in __GI_fseek (fp=fp@entry=0x7f397335d000, offset=offset@entry=0,
    whence=whence@entry=2) at ./libio/fseek.c:36
#5  0x0000563dfd418047 in getProfileFileSizeForMerging (ProfileFile=0x0,
    ProfileFile@entry=0x7f397335d000, ProfileFileSize=ProfileFileSize@entry=0x7f3973c8b0c8)
    at ../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingFile.c:321
#6  0x0000563dfd417e59 in doProfileMerging (ProfileFile=<optimized out>, MergeDone=<optimized out>)
    at ../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingFile.c:378
#7  openFileForMerging (ProfileFileName=0x7f3973c8b110 "default_1626972948584884227_0_2427595.profraw",
    MergeDone=<optimized out>) at ../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingFile.c:440
#8  writeFile (
    OutputName=OutputName@entry=0x7f3973c8b110 "default_1626972948584884227_0_2427595.profraw")
    at ../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingFile.c:469
#9  0x0000563dfd417d12 in __llvm_profile_write_file ()
    at ../../src/llvm-project/compiler-rt/lib/profile/InstrProfilingFile.c:1051
#10 0x0000563df53f2351 in environmentd::sys::handle_termination_signal (signum=2)
    at src/environmentd/src/bin/environmentd/sys.rs:142
#11 <signal handler called>
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```
