### ISSUE TITLE
thread 'coordinator' panicked at 'Expression in join plan is not bound at time of use', src/compute-client/src/plan/join/linear_join.rs:254:34

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#20060]
### What version of Materialize are you using?

74948d8

### What is the issue?

Similar panic to https://github.com/MaterializeInc/materialize/issues/19214
```
select
  from
    (select
          ref_4."schema_id" as c0
        from
          mz_catalog.mz_default_privileges as ref_4
        where current_schemas(
            CAST((select max(atthasdef) from pg_attribute)
               as bool)) = mz_internal.mz_normalize_object_name(
            CAST(ref_4."schema_id" as text))
               ) as subq_7
  where (select "child_id" from mz_internal.mz_view_foreign_keys limit 1)
       = subq_7."c0";
```
```
thread 'coordinator' panicked at 'Expression in join plan is not bound at time of use', src/compute-client/src/plan/join/linear_join.rs:254:34
stack backtrace:
   0: rust_begin_unwind
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/panicking.rs:147:5
   3: core::panicking::panic_str
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/panicking.rs:131:5
   4: core::option::expect_failed
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/option.rs:1926:5
   5: core::option::Option<T>::expect
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/option.rs:786:21
   6: mz_compute_client::plan::join::linear_join::LinearJoinPlan::create_from::{{closure}}::{{closure}}
             at ./src/compute-client/src/plan/join/linear_join.rs:254:34
   7: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/iter/adapters/map.rs:84:28
   8: core::iter::traits::iterator::Iterator::fold
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/iter/traits/iterator.rs:2438:21
   9: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/iter/adapters/map.rs:124:9
  10: core::iter::traits::iterator::Iterator::for_each
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/iter/traits/iterator.rs:837:9
  11: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/alloc/src/vec/mod.rs:2856:17
  12: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/alloc/src/vec/spec_extend.rs:26:9
  13: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  14: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/alloc/src/vec/spec_from_iter.rs:33:9
  15: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/alloc/src/vec/mod.rs:2724:9
  16: core::iter::traits::iterator::Iterator::collect
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/iter/traits/iterator.rs:1860:9
  17: mz_compute_client::plan::join::linear_join::LinearJoinPlan::create_from::{{closure}}
             at ./src/compute-client/src/plan/join/linear_join.rs:259:26
  18: core::option::Option<T>::unwrap_or_else
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/option.rs:873:21
  19: mz_compute_client::plan::join::linear_join::LinearJoinPlan::create_from
             at ./src/compute-client/src/plan/join/linear_join.rs:239:17
  20: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1333:46
  21: mz_compute_client::plan::Plan<T>::from_mir::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:1035:38
  22: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  23: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  24: mz_compute_client::plan::Plan<T>::from_mir
             at ./src/compute-client/src/plan/mod.rs:1035:9
  25: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1147:38
  26: mz_compute_client::plan::Plan<T>::from_mir::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:1035:38
  27: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  28: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  29: mz_compute_client::plan::Plan<T>::from_mir
             at ./src/compute-client/src/plan/mod.rs:1035:9
  30: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1147:38
  31: mz_compute_client::plan::Plan<T>::from_mir::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:1035:38
  32: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  33: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  34: mz_compute_client::plan::Plan<T>::from_mir
             at ./src/compute-client/src/plan/mod.rs:1035:9
  35: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1147:38
  36: mz_compute_client::plan::Plan<T>::from_mir::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:1035:38
  37: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  38: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  39: mz_compute_client::plan::Plan<T>::from_mir
             at ./src/compute-client/src/plan/mod.rs:1035:9
  40: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1147:38
  41: mz_compute_client::plan::Plan<T>::from_mir::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:1035:38
  42: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  43: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  44: mz_compute_client::plan::Plan<T>::from_mir
             at ./src/compute-client/src/plan/mod.rs:1035:9
  45: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1147:38
  46: mz_compute_client::plan::Plan<T>::from_mir::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:1035:38
  47: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  48: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  49: mz_compute_client::plan::Plan<T>::from_mir
             at ./src/compute-client/src/plan/mod.rs:1035:9
  50: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1147:38
  51: mz_compute_client::plan::Plan<T>::from_mir::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:1035:38
  52: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  53: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  54: mz_compute_client::plan::Plan<T>::from_mir
             at ./src/compute-client/src/plan/mod.rs:1035:9
  55: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1147:38
  56: mz_compute_client::plan::Plan<T>::from_mir::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:1035:38
  57: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  58: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  59: mz_compute_client::plan::Plan<T>::from_mir
             at ./src/compute-client/src/plan/mod.rs:1035:9
  60: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1147:38
  61: mz_compute_client::plan::Plan<T>::from_mir::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:1035:38
  62: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  63: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  64: mz_compute_client::plan::Plan<T>::from_mir
             at ./src/compute-client/src/plan/mod.rs:1035:9
  65: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1147:38
  66: mz_compute_client::plan::Plan<T>::from_mir::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:1035:38
  67: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  68: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  69: mz_compute_client::plan::Plan<T>::from_mir
             at ./src/compute-client/src/plan/mod.rs:1035:9
  70: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1147:38
  71: mz_compute_client::plan::Plan<T>::from_mir::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:1035:38
  72: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  73: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  74: mz_compute_client::plan::Plan<T>::from_mir
             at ./src/compute-client/src/plan/mod.rs:1035:9
  75: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1147:38
  76: mz_compute_client::plan::Plan<T>::from_mir::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:1035:38
  77: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  78: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  79: mz_compute_client::plan::Plan<T>::from_mir
             at ./src/compute-client/src/plan/mod.rs:1035:9
  80: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1147:38
  81: mz_compute_client::plan::Plan<T>::from_mir::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:1035:38
  82: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  83: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  84: mz_compute_client::plan::Plan<T>::from_mir
             at ./src/compute-client/src/plan/mod.rs:1035:9
  85: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1147:38
  86: mz_compute_client::plan::Plan<T>::from_mir::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:1035:38
  87: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  88: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  89: mz_compute_client::plan::Plan<T>::from_mir
             at ./src/compute-client/src/plan/mod.rs:1035:9
  90: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1147:38
  91: mz_compute_client::plan::Plan<T>::from_mir::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:1035:38
  92: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  93: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  94: mz_compute_client::plan::Plan<T>::from_mir
             at ./src/compute-client/src/plan/mod.rs:1035:9
  95: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1147:38
  96: mz_compute_client::plan::Plan<T>::from_mir::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:1035:38
  97: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  98: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  99: mz_compute_client::plan::Plan<T>::from_mir
             at ./src/compute-client/src/plan/mod.rs:1035:9
 100: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1147:38
 101: mz_compute_client::plan::Plan<T>::from_mir::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:1035:38
 102: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
 103: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
 104: mz_compute_client::plan::Plan<T>::from_mir
             at ./src/compute-client/src/plan/mod.rs:1035:9
 105: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1147:38
 106: mz_compute_client::plan::Plan<T>::from_mir::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:1035:38
 107: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
 108: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
 109: mz_compute_client::plan::Plan<T>::from_mir
             at ./src/compute-client/src/plan/mod.rs:1035:9
 110: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1147:38
 111: mz_compute_client::plan::Plan<T>::from_mir::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:1035:38
 112: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
 113: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
 114: mz_compute_client::plan::Plan<T>::from_mir
             at ./src/compute-client/src/plan/mod.rs:1035:9
 115: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1147:38
 116: mz_compute_client::plan::Plan<T>::from_mir::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:1035:38
 117: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
 118: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
 119: mz_compute_client::plan::Plan<T>::from_mir
             at ./src/compute-client/src/plan/mod.rs:1035:9
 120: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1147:38
 121: mz_compute_client::plan::Plan<T>::from_mir::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:1035:38
 122: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
 123: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
 124: mz_compute_client::plan::Plan<T>::from_mir
             at ./src/compute-client/src/plan/mod.rs:1035:9
 125: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1147:38
 126: mz_compute_client::plan::Plan<T>::from_mir::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:1035:38
 127: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
 128: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
 129: mz_compute_client::plan::Plan<T>::from_mir
             at ./src/compute-client/src/plan/mod.rs:1035:9
 130: mz_compute_client::plan::Plan<T>::from_mir_stack_safe
             at ./src/compute-client/src/plan/mod.rs:1147:38
 131: mz_compute_client::plan::Plan<T>::from_mir::{{closure}}
             at ./src/compute-client/src/plan/mod.rs:1035:38
 132: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
 133: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
 134: mz_compute_client::plan::Plan<T>::from_mir
             at ./src/compute-client/src/plan/mod.rs:1035:9
 135: mz_compute_client::plan::Plan<T>::lower_dataflow
             at ./src/compute-client/src/plan/mod.rs:1751:32
 136: mz_compute_client::plan::Plan<T>::finalize_dataflow
             at ./src/compute-client/src/plan/mod.rs:1696:28
 137: mz_adapter::coord::dataflows::<impl mz_adapter::coord::Coordinator>::finalize_dataflow
             at ./src/adapter/src/coord/dataflows.rs:278:9
 138: mz_adapter::coord::peek::<impl mz_adapter::coord::Coordinator>::create_peek_plan::{{closure}}
             at ./src/adapter/src/coord/peek.rs:279:28
 139: core::option::Option<T>::map_or_else
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/option.rs:1066:21
 140: mz_adapter::coord::peek::<impl mz_adapter::coord::Coordinator>::create_peek_plan
             at ./src/adapter/src/coord/peek.rs:266:25
 141: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::plan_peek
             at ./src/adapter/src/coord/sequencer/inner.rs:2199:25
 142: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::peek_stage_finish::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer/inner.rs:2046:25
 143: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::peek_stage_finish::{{closure}}
             at ./src/adapter/src/coord/sequencer/inner.rs:2019:5
 144: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::sequence_peek_stage::{{closure}}
             at ./src/adapter/src/coord/sequencer/inner.rs:1775:79
 145: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::sequence_peek::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer/inner.rs:1737:9
 146: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::sequence_peek::{{closure}}
             at ./src/adapter/src/coord/sequencer/inner.rs:1721:5
 147: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_plan::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:252:62
 148: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_plan::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:56:5
 149: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute_inner::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:603:70
 150: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute_inner::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:410:5
 151: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:407:53
 152: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:354:5
 153: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
 154: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_command::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:116:71
 155: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_command::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:237:33
 156: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_command::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:234:5
 157: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::handle_message::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:42:63
 158: mz_adapter::coord::Coordinator::serve::{{closure}}
             at ./src/adapter/src/coord.rs:1514:37
 159: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:63
 160: tokio::runtime::coop::with_budget
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:107:5
 161: tokio::runtime::coop::budget
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:73:5
 162: tokio::runtime::park::CachedParkThread::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:31
 163: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/context.rs:315:13
 164: tokio::runtime::handle::Handle::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/handle.rs:264:9
 165: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./src/adapter/src/coord.rs:1739:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Bisect not really helpful since that's just when the functions/tables were introduced:
```
a961b2c4c5dce34fc801b0fc49f5a8d978e6a37f is the first bad commit
commit a961b2c4c5dce34fc801b0fc49f5a8d978e6a37f
Author: Joseph Koshakow <koshy44@gmail.com>
Date:   Thu Jun 8 15:27:28 2023 -0400

    adapter: Add infrastructure for default privileges (#19793)

    This commit adds default privileges to the stash, system catalog tables,
    and the in memory catalog. When a new object is created, the default
    privileges are automatically applied to the object.

    Currently, there's no way for a user to modify the default privileges,
    it's only pre-populated with some system default privileges. In a later
    commit we will add the `ALTER DEFAULT PRIVILEGE` command to allow users
    to alter these privileges.

    Works towards resolving #19647

 doc/user/content/sql/system-catalog/mz_catalog.md |  14 ++
 src/adapter/src/catalog.rs                        | 294 ++++++++++++++++++++--
 src/adapter/src/catalog/builtin.rs                |  14 ++
 src/adapter/src/catalog/builtin_table_updates.rs  |  54 +++-
 src/adapter/src/catalog/storage.rs                |  31 ++-
 src/adapter/src/catalog/storage/objects.rs        |   6 +-
 src/adapter/src/catalog/storage/stash.rs          |   2 +-
 src/repr/src/adt/mz_acl_item.rs                   |  15 ++
 src/sql/src/names.rs                              |  39 +--
 src/stash/protos/hashes.json                      |   2 +-
 src/stash/protos/objects.proto                    |   9 +-
 test/sqllogictest/default_privileges.slt          |  26 ++
 test/sqllogictest/information_schema_tables.slt   |   4 +
 test/testdrive/catalog.td                         |   3 +-
 14 files changed, 435 insertions(+), 78 deletions(-)
 create mode 100644 test/sqllogictest/default_privileges.slt
```

ci-regexp: Expression in join plan is not bound at time of use

**Comment by ggevay** [comment]
I found the problem: `canonicalize_equivalences` can invalidate a join plan when JoinImplementation is run the second time. I'm not really sure why it's still modifying the equivalences in the second run though. Maybe it's just not idempotent somehow. I think we'll modify `JoinImplementation` to either
- replan the join when `canonicalize_equivalences` does something.
- only call `canonicalize_equivalences` if it was `Unimplemented`, and then it will be planned for sure.
