### ISSUE TITLE
[SQLsmith] thread 'timely:work-0' panicked at 'attempt to negate with overflow', core/src/num/mod.rs:245:5

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#20144]
### What version of Materialize are you using?

2956f03

### What is the issue?

Via https://buildkite.com/materialize/nightlies/builds/2658
```
thread 'timely:work-0' panicked at 'attempt to negate with overflow', /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/num/mod.rs:245:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/panicking.rs:114:5
   3: core::num::<impl i64>::abs
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/num/int_macros.rs:2518:17
   4: mz_expr::scalar::func::jsonb_get_int64
             at ./src/expr/src/scalar/func.rs:1434:56
   5: mz_expr::scalar::func::BinaryFunc::eval
             at ./src/expr/src/scalar/func.rs:2405:20
   6: mz_expr::scalar::MirScalarExpr::eval
             at ./src/expr/src/scalar/mod.rs:1761:17
   7: <T as mz_expr::scalar::func::LazyUnaryFunc>::eval
             at ./src/expr/src/scalar/func.rs:4224:41
   8: mz_expr::scalar::func::UnaryFunc::eval
             at ./src/expr/src/scalar/func/macros.rs:343:41
   9: mz_expr::scalar::MirScalarExpr::eval
             at ./src/expr/src/scalar/mod.rs:1759:56
  10: mz_expr::linear::plan::SafeMfpPlan::evaluate_inner
             at ./src/expr/src/linear.rs:1529:20
  11: mz_expr::linear::plan::MfpPlan::evaluate
             at ./src/expr/src/linear.rs:1772:19
  12: mz_compute::render::context::CollectionBundle<S,mz_repr::row::Row,T>::as_collection_core::{{closure}}::{{closure}}
             at ./src/compute/src/render/context.rs:696:17
  13: mz_compute::render::context::CollectionBundle<S,mz_repr::row::Row,T>::flat_map::{{closure}}
             at ./src/compute/src/render/context.rs:557:52
  14: <timely::dataflow::stream::StreamCore<S,alloc::vec::Vec<D>> as timely::dataflow::operators::map::Map<S,D>>::flat_map::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/15ac623/timely/src/dataflow/operators/map.rs:79:83
  15: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/ops/function.rs:310:13
  16: core::option::Option<T>::map
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/option.rs:972:29
  17: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/iter/adapters/map.rs:103:9
  18: <core::iter::adapters::fuse::Fuse<I> as core::iter::adapters::fuse::FuseImpl<I>>::next
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/iter/adapters/fuse.rs:337:9
  19: <core::iter::adapters::fuse::Fuse<I> as core::iter::traits::iterator::Iterator>::next
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/iter/adapters/fuse.rs:43:9
  20: <core::iter::adapters::flatten::FlattenCompat<I,U> as core::iter::traits::iterator::Iterator>::next
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/iter/adapters/flatten.rs:474:29
  21: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/iter/adapters/flatten.rs:51:9
  22: timely::dataflow::channels::pushers::buffer::Session<T,alloc::vec::Vec<D>,P>::give_iterator
             at /home/deen/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/15ac623/timely/src/dataflow/channels/pushers/buffer.rs:135:21
  23: <timely::dataflow::stream::StreamCore<S,alloc::vec::Vec<D>> as timely::dataflow::operators::map::Map<S,D>>::flat_map::{{closure}}::{{closure}}::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/15ac623/timely/src/dataflow/operators/map.rs:79:17
  24: timely::dataflow::operators::generic::handles::InputHandleCore<T,D,P>::for_each
             at /home/deen/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/15ac623/timely/src/dataflow/operators/generic/handles.rs:94:13
  25: <timely::dataflow::stream::StreamCore<S,alloc::vec::Vec<D>> as timely::dataflow::operators::map::Map<S,D>>::flat_map::{{closure}}::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/15ac623/timely/src/dataflow/operators/map.rs:77:13
  26: <timely::dataflow::stream::StreamCore<G,D1> as timely::dataflow::operators::generic::operator::Operator<G,D1>>::unary::{{closure}}::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/15ac623/timely/src/dataflow/operators/generic/operator.rs:401:17
  27: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build::{{closure}}::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/15ac623/timely/src/dataflow/operators/generic/builder_rc.rs:133:31
  28: timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/15ac623/timely/src/dataflow/operators/generic/builder_rc.rs:172:26
  29: <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/15ac623/timely/src/dataflow/operators/generic/builder_raw.rs:204:9
  30: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/15ac623/timely/src/progress/subgraph.rs:699:30
  31: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /home/deen/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/15ac623/timely/src/progress/subgraph.rs:346:26
  32: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/15ac623/timely/src/progress/subgraph.rs:312:17
  33: timely::progress::subgraph::PerOperatorState<T>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/15ac623/timely/src/progress/subgraph.rs:699:30
  34: timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child
             at /home/deen/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/15ac623/timely/src/progress/subgraph.rs:346:26
  35: <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule
             at /home/deen/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/15ac623/timely/src/progress/subgraph.rs:312:17
  36: timely::worker::Wrapper::step::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/15ac623/timely/src/worker.rs:754:57
  37: core::option::Option<T>::map
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/option.rs:972:29
  38: timely::worker::Wrapper::step
             at /home/deen/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/15ac623/timely/src/worker.rs:754:26
  39: timely::worker::Worker<A>::step_or_park
             at /home/deen/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/15ac623/timely/src/worker.rs:396:38
  40: mz_compute::server::Worker<A>::run_client
             at ./src/compute/src/server.rs:346:13
  41: mz_compute::server::Worker<A>::setup_channel_and_run_client
             at ./src/compute/src/server.rs:320:9
  42: mz_compute::server::Worker<A>::run
             at ./src/compute/src/server.rs:180:21
  43: <mz_compute::server::Config as mz_cluster::types::AsRunnableWorker<mz_compute_client::protocol::command::ComputeCommand,mz_compute_client::protocol::response::ComputeResponse>>::build_and_run
             at ./src/compute/src/server.rs:161:9
  44: mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<C,R,<Worker as mz_cluster::types::AsRunnableWorker<C,R>>::Activatable>,C,R>,Worker,C,R>::build_timely::{{closure}}::{{closure}}
             at ./src/cluster/src/server.rs:178:13
  45: timely::execute::execute_from::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/15ac623/timely/src/execute.rs:388:22
  46: timely_communication::initialize::initialize_from::{{closure}}
             at /home/deen/.cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/15ac623/communication/src/initialize.rs:316:33
```
I'll check if this is a regression and if I can reduce the query.

**Comment by def-** [comment]
Not a regression. Easy reproducer:
```sql
select jsonb_build_array() ->> -9223372036854775808;
```

**Comment by def-** [comment]
This is a fun one:

https://github.com/MaterializeInc/materialize/blob/907c4aaa3fdc54a9fabc95c0fb76c5e421e7d473/src/expr/src/scalar/func.rs#L1434

We convert a minimal negative int64 (-9223372036854775808) with abs to positive, but there is no positive equivalent in int64, since the max is 9223372036854775807. So the conversion fails. It would fit since we later use uint64 to store the value. It seems like Rust doesn't have a function that takes the abs value of an int64 and stores it in an uint64 directly, so we might have to go through int128 or just fail for this huge value, which is larger than any reasonable array anyway (good luck fitting that into memory).
