### ISSUE TITLE
thread 'timely:work-2' panicked at 'known to be positive: TryFromIntError(())', src/expr/src/scalar/func.rs:1670:65

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#20198]
### What version of Materialize are you using?

ddd86f4

### What is the issue?

```
sqlsmith-mz_2-1  | thread 'timely:work-2' panicked at 'known to be positive: TryFromIntError(())', src/expr/src/scalar/func.rs:1670:65
sqlsmith-mz_2-1  | stack backtrace:
sqlsmith-mz_2-1  |    0: rust_begin_unwind
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
sqlsmith-mz_2-1  |    1: core::panicking::panic_fmt
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
sqlsmith-mz_2-1  |    2: core::result::unwrap_failed
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1790:5
sqlsmith-mz_2-1  |    3: <core::result::Result<u64, core::num::error::TryFromIntError>>::expect
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1069:23
sqlsmith-mz_2-1  |    4: mz_expr::scalar::func::jsonb_delete_int64
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c9919fdf0d351bfd-1/materialize/tests/src/expr/src/scalar/func.rs:1670:42
sqlsmith-mz_2-1  |    5: <mz_expr::scalar::func::BinaryFunc>::eval
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c9919fdf0d351bfd-1/materialize/tests/src/expr/src/scalar/func.rs:2416:48
sqlsmith-mz_2-1  |    6: <mz_expr::scalar::MirScalarExpr>::eval
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c9919fdf0d351bfd-1/materialize/tests/src/expr/src/scalar/mod.rs:1761:17
sqlsmith-mz_2-1  |    7: <mz_expr::scalar::func::BinaryFunc>::eval
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c9919fdf0d351bfd-1/materialize/tests/src/expr/src/scalar/func.rs:2227:17
sqlsmith-mz_1-1  | environmentd: 2023-06-28T07:46:42.349866Z  INFO environmentd::run:environmentd::serve:bootstrap: mz_adapter::coord: coordinator init: resetting system table mz_catalog.mz_base_types (s345)
sqlsmith-mz_2-1  |    8: <mz_expr::scalar::MirScalarExpr>::eval
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c9919fdf0d351bfd-1/materialize/tests/src/expr/src/scalar/mod.rs:1761:17
sqlsmith-mz_2-1  |    9: <mz_expr::linear::plan::SafeMfpPlan>::evaluate_inner
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c9919fdf0d351bfd-1/materialize/tests/src/expr/src/linear.rs:1529:20
sqlsmith-mz_2-1  |   10: <mz_expr::linear::plan::MfpPlan>::evaluate::<mz_storage_client::types::errors::DataflowError, <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::as_collection_core::{closure#1}::{closure#0}::{closure#0}>
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c9919fdf0d351bfd-1/materialize/tests/src/expr/src/linear.rs:1772:19
sqlsmith-mz_2-1  |   11: <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::as_collection_core::{closure#1}::{closure#0}
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c9919fdf0d351bfd-1/materialize/tests/src/compute/src/render/context.rs:696:17
sqlsmith-mz_2-1  |   12: <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::flat_map::<core::iter::adapters::map::Map<core::iter::adapters::chain::Chain<core::option::IntoIter<core::result::Result<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64), (mz_storage_client::types::errors::DataflowError, mz_repr::timestamp::Timestamp, i64)>>, core::option::IntoIter<core::result::Result<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64), (mz_storage_client::types::errors::DataflowError, mz_repr::timestamp::Timestamp, i64)>>>, <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::as_collection_core::{closure#1}::{closure#0}::{closure#1}>, <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::as_collection_core::{closure#1}, <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::as_collection_core::{closure#1}::{closure#0}>::{closure#0}
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0c9919fdf0d351bfd-1/materialize/tests/src/compute/src/render/context.rs:557:52
sqlsmith-mz_2-1  |   13: <timely::dataflow::stream::StreamCore<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, alloc::vec::Vec<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64)>> as timely::dataflow::operators::map::Map<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64)>>::flat_map::<core::iter::adapters::map::Map<core::iter::adapters::chain::Chain<core::option::IntoIter<core::result::Result<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64), (mz_storage_client::types::errors::DataflowError, mz_repr::timestamp::Timestamp, i64)>>, core::option::IntoIter<core::result::Result<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64), (mz_storage_client::types::errors::DataflowError, mz_repr::timestamp::Timestamp, i64)>>>, <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::as_collection_core::{closure#1}::{closure#0}::{closure#1}>, <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::flat_map<core::iter::adapters::map::Map<core::iter::adapters::chain::Chain<core::option::IntoIter<core::result::Result<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64), (mz_storage_client::types::errors::DataflowError, mz_repr::timestamp::Timestamp, i64)>>, core::option::IntoIter<core::result::Result<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64), (mz_storage_client::types::errors::DataflowError, mz_repr::timestamp::Timestamp, i64)>>>, <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::as_collection_core::{closure#1}::{closure#0}::{closure#1}>, <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::as_collection_core::{closure#1}, <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::as_collection_core::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}::{closure#0}::{closure#0}
sqlsmith-mz_2-1  |              at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/15ac623/timely/src/dataflow/operators/map.rs:79:83
sqlsmith-mz_2-1  |   14: <&mut <timely::dataflow::stream::StreamCore<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, alloc::vec::Vec<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64)>> as timely::dataflow::operators::map::Map<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64)>>::flat_map<core::iter::adapters::map::Map<core::iter::adapters::chain::Chain<core::option::IntoIter<core::result::Result<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64), (mz_storage_client::types::errors::DataflowError, mz_repr::timestamp::Timestamp, i64)>>, core::option::IntoIter<core::result::Result<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64), (mz_storage_client::types::errors::DataflowError, mz_repr::timestamp::Timestamp, i64)>>>, <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::as_collection_core::{closure#1}::{closure#0}::{closure#1}>, <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::flat_map<core::iter::adapters::map::Map<core::iter::adapters::chain::Chain<core::option::IntoIter<core::result::Result<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64), (mz_storage_client::types::errors::DataflowError, mz_repr::timestamp::Timestamp, i64)>>, core::option::IntoIter<core::result::Result<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64), (mz_storage_client::types::errors::DataflowError, mz_repr::timestamp::Timestamp, i64)>>>, <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::as_collection_core::{closure#1}::{closure#0}::{closure#1}>, <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::as_collection_core::{closure#1}, <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::as_collection_core::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}::{closure#0}::{closure#0} as core::ops::function::FnOnce<((mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64),)>>::call_once
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:310:13
sqlsmith-mz_2-1  |   15: <core::option::Option<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64)>>::map::<core::iter::adapters::map::Map<core::iter::adapters::chain::Chain<core::option::IntoIter<core::result::Result<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64), (mz_storage_client::types::errors::DataflowError, mz_repr::timestamp::Timestamp, i64)>>, core::option::IntoIter<core::result::Result<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64), (mz_storage_client::types::errors::DataflowError, mz_repr::timestamp::Timestamp, i64)>>>, <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::as_collection_core::{closure#1}::{closure#0}::{closure#1}>, &mut <timely::dataflow::stream::StreamCore<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, alloc::vec::Vec<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64)>> as timely::dataflow::operators::map::Map<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64)>>::flat_map<core::iter::adapters::map::Map<core::iter::adapters::chain::Chain<core::option::IntoIter<core::result::Result<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64), (mz_storage_client::types::errors::DataflowError, mz_repr::timestamp::Timestamp, i64)>>, core::option::IntoIter<core::result::Result<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64), (mz_storage_client::types::errors::DataflowError, mz_repr::timestamp::Timestamp, i64)>>>, <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::as_collection_core::{closure#1}::{closure#0}::{closure#1}>, <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::flat_map<core::iter::adapters::map::Map<core::iter::adapters::chain::Chain<core::option::IntoIter<core::result::Result<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64), (mz_storage_client::types::errors::DataflowError, mz_repr::timestamp::Timestamp, i64)>>, core::option::IntoIter<core::result::Result<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64), (mz_storage_client::types::errors::DataflowError, mz_repr::timestamp::Timestamp, i64)>>>, <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::as_collection_core::{closure#1}::{closure#0}::{closure#1}>, <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::as_collection_core::{closure#1}, <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::as_collection_core::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}::{closure#0}::{closure#0}>
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/option.rs:970:29
sqlsmith-mz_2-1  |   16: <core::iter::adapters::map::Map<alloc::vec::drain::Drain<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64)>, <timely::dataflow::stream::StreamCore<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, alloc::vec::Vec<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64)>> as timely::dataflow::operators::map::Map<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64)>>::flat_map<core::iter::adapters::map::Map<core::iter::adapters::chain::Chain<core::option::IntoIter<core::result::Result<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64), (mz_storage_client::types::errors::DataflowError, mz_repr::timestamp::Timestamp, i64)>>, core::option::IntoIter<core::result::Result<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64), (mz_storage_client::types::errors::DataflowError, mz_repr::timestamp::Timestamp, i64)>>>, <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::as_collection_core::{closure#1}::{closure#0}::{closure#1}>, <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::flat_map<core::iter::adapters::map::Map<core::iter::adapters::chain::Chain<core::option::IntoIter<core::result::Result<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64), (mz_storage_client::types::errors::DataflowError, mz_repr::timestamp::Timestamp, i64)>>, core::option::IntoIter<core::result::Result<(mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64), (mz_storage_client::types::errors::DataflowError, mz_repr::timestamp::Timestamp, i64)>>>, <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::as_collection_core::{closure#1}::{closure#0}::{closure#1}>, <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::as_collection_core::{closure#1}, <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::row::Row>>::as_collection_core::{closure#1}::{closure#0}>::{closure#0}>::{closure#0}::{closure#0}::{closure#0}::{closure#0}> as core::iter::traits::iterator::Iterator>::next
```
Via https://buildkite.com/materialize/nightlies/builds/2668#_, but I think it's independent of the change. Can't be reproduced by just running the queries again, so I'll try to find a repro:
```sql
CREATE SOURCE auction
              FROM LOAD GENERATOR AUCTION (SCALE FACTOR 10)
              FOR ALL TABLES
              WITH (SIZE = '1');
CREATE TABLE t (a int, b int);
select
  pg_catalog.current_database() as c0
from
  (select
        subq_0."c0" as c0
      from
        (select
              (select "spcowner" from pg_catalog.pg_tablespace limit 1 offset 5)
                 as c0,
              ref_0."buyer" as c1,
              ref_0."bid_time" as c2,
              ref_0."auction_id" as c3,
              ref_0."amount" as c4
            from
              public.bids as ref_0
            where ref_0."buyer" is not NULL) as subq_0
      where (subq_0."c0" is not NULL)
        or ((((select "cpu_percent" from mz_internal.mz_cluster_replica_utilization limit 1 offset 1)
              ) * ((select pg_catalog.avg("cpu_percent") from mz_internal.mz_cluster_replica_utilization)
              )) = ((select "cpu_percent" from mz_internal.mz_cluster_replica_utilization limit 1 offset 6)
            ))) as subq_1
where ((pg_catalog.jsonb_build_array()) - (((select "sent" from mz_internal.mz_message_counts_per_worker limit 1 offset 2)
        ) << (case when (case when (select "b" from public.t limit 1 offset 1)
                 is not NULL then (select "details" from mz_internal.mz_source_status_history limit 1 offset 5)
               else (select "details" from mz_internal.mz_source_status_history limit 1 offset 5)
               end
            ) = (pg_catalog.jsonb_strip_nulls(
            CAST((select "details" from mz_internal.mz_source_status_history limit 1 offset 1)
               as jsonb))) then (select pg_catalog.max("typtypmod") from pg_catalog.pg_type)
           else (select pg_catalog.max("typtypmod") from pg_catalog.pg_type)
           end
        ))) <= (pg_catalog.jsonb_build_array())
limit 126;
```

**Comment by def-** [comment]
`generate_series(start: timestamptz, stop: timestamptz, step: interval) -> Col<timestamptz>` is also missing in the documentation btw: https://materialize.com/docs/sql/functions/

**Comment by def-** [comment]
I didn't manage to reproduce it since I'm struggling to generate a small enough timestamp. But this is the code in question:

https://github.com/MaterializeInc/materialize/blob/83990f6abe5d9bfc6eeaa3b2703222b73197c024/src/repr/src/adt/timestamp.rs#L162

which will panic for these values of the year: `-2147483647` and `-2147483648`. Small sample Rust code to show this:

```rust
use std::convert::TryFrom;

fn iso_year_ce(year: i32) -> u32 {
    if year < 1 {
        u32::try_from(1 - year).expect("known to be positive")
    } else {
        u32::try_from(year).expect("known to be positive")
    }
}

fn main() {
    iso_year_ce(-2147483647);
    iso_year_ce(-2147483648);
}
```

**Comment by def-** [comment]
Duplicate of https://github.com/MaterializeInc/materialize/issues/20144
