### ISSUE TITLE
persist: dropping subsource wedges persist locally

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#20232]
### What version of Materialize are you using?

v0.59.0-dev (1f5c3ff37)

### What is the issue?

I recently added a feature that enables dropping subsources from PG sources. #20067 This feature is meant to just drop a source like all sources get dropped using `drop_sources` on the storage controller.

Today when I was testing it, I dropped a PG subsource and immediately hit this panic, which is preventing me from booting:

Here it is as it occurred
```
environmentd: 2023-06-28T23:02:05.413055Z  INFO mz_adapter::catalog: drop source materialize.public.enum_table (u37)
environmentd: 2023-06-28T23:02:05.413278Z  INFO mz_adapter::catalog: update source materialize.public.pg_source (u45)
cluster-u4-replica-6: 2023-06-28T23:02:05.525227Z  INFO mz_storage::storage_state: worker 0/1 trying to (re-)start ingestion u45 at resumption frontier Antichain { elements: [1687993325001] }
cluster-u4-replica-6: 2023-06-28T23:02:05.526108Z  INFO mz_storage::source::source_reader_pipeline: timely-0 building source pipeline id=u45 resume_upper={1687993325001}
cluster-u4-replica-6: 2023-06-28T23:02:05.536894Z  INFO mz_storage::render: timely-0 rendering u35 with multi-worker persist_sink
cluster-u4-replica-6: 2023-06-28T23:02:05.537588Z  INFO mz_storage::render: timely-0 rendering u36 with multi-worker persist_sink
cluster-u4-replica-6: 2023-06-28T23:02:05.538189Z  INFO mz_storage::render: timely-0 rendering u38 with multi-worker persist_sink
cluster-u4-replica-6: 2023-06-28T23:02:05.538788Z  INFO mz_storage::render: timely-0 rendering u39 with multi-worker persist_sink
cluster-u4-replica-6: 2023-06-28T23:02:05.539345Z  INFO mz_storage::render: timely-0 rendering u40 with multi-worker persist_sink
cluster-u4-replica-6: 2023-06-28T23:02:05.539941Z  INFO mz_storage::render: timely-0 rendering u41 with multi-worker persist_sink
cluster-u4-replica-6: 2023-06-28T23:02:05.540502Z  INFO mz_storage::render: timely-0 rendering u42 with multi-worker persist_sink
cluster-u4-replica-6: 2023-06-28T23:02:05.541109Z  INFO mz_storage::render: timely-0 rendering u43 with multi-worker persist_sink
cluster-u4-replica-6: 2023-06-28T23:02:05.541703Z  INFO mz_storage::render: timely-0 rendering u45 with multi-worker persist_sink
cluster-u4-replica-6: 2023-06-28T23:02:05.542214Z  INFO mz_storage::source::source_reader_pipeline: Health for source u45 being written to s002ec04f-80b1-4c1d-96c1-55cc919b7522
cluster-u4-replica-6: 2023-06-28T23:02:05.542231Z  INFO mz_storage::source::source_reader_pipeline: Health for source u35 being written to s002ec04f-80b1-4c1d-96c1-55cc919b7522
cluster-u4-replica-6: 2023-06-28T23:02:05.542240Z  INFO mz_storage::source::source_reader_pipeline: Health for source u36 being written to s002ec04f-80b1-4c1d-96c1-55cc919b7522
cluster-u4-replica-6: 2023-06-28T23:02:05.542248Z  INFO mz_storage::source::source_reader_pipeline: Health for source u38 being written to s002ec04f-80b1-4c1d-96c1-55cc919b7522
cluster-u4-replica-6: 2023-06-28T23:02:05.542256Z  INFO mz_storage::source::source_reader_pipeline: Health for source u39 being written to s002ec04f-80b1-4c1d-96c1-55cc919b7522
cluster-u4-replica-6: 2023-06-28T23:02:05.542268Z  INFO mz_storage::source::source_reader_pipeline: Health for source u40 being written to s002ec04f-80b1-4c1d-96c1-55cc919b7522
cluster-u4-replica-6: 2023-06-28T23:02:05.542276Z  INFO mz_storage::source::source_reader_pipeline: Health for source u41 being written to s002ec04f-80b1-4c1d-96c1-55cc919b7522
cluster-u4-replica-6: 2023-06-28T23:02:05.542283Z  INFO mz_storage::source::source_reader_pipeline: Health for source u42 being written to s002ec04f-80b1-4c1d-96c1-55cc919b7522
cluster-u4-replica-6: 2023-06-28T23:02:05.542291Z  INFO mz_storage::source::source_reader_pipeline: Health for source u43 being written to s002ec04f-80b1-4c1d-96c1-55cc919b7522
cluster-u4-replica-6: 2023-06-28T23:02:05.613282Z  INFO mz_storage::source::reclock::compat: remap(u45) 0/1 initializing PersistHandle since=Antichain { elements: [0] } as_of=Antichain { elements: [1687993325000] } upper=Antichain { elements: [1687993325001] }
thread 'tokio:work-0' panicked at 'assertion failed: `(left == right)`
  left: `{HollowBatch { desc: Description { lower: Antichain { elements: [0] }, upper: Antichain { elements: [1687993044262] }, since: Antichain { elements: [1687993036000] } }, parts: [HollowBatchPart { key: PartialBatchKey("w47c597c0-19f3-46fb-a5de-365b76b00489/p8b93f327-1571-48f9-b2b8-231bbe9e4bd4"), encoded_size_bytes: 1052, stats: None }], len: 1, runs: [] }, HollowBatch { desc: Description { lower: Antichain { elements: [1687993044262] }, upper: Antichain { elements: [1687993159591] }, since: Antichain { elements: [1687993128000] } }, parts: [], len: 0, runs: [] }, HollowBatch { desc: Description { lower: Antichain { elements: [1687993044262] }, upper: Antichain { elements: [1687993160592] }, since: Antichain { elements: [1687993128000] } }, parts: [], len: 0, runs: [] }}`,
 right: `{HollowBatch { desc: Description { lower: Antichain { elements: [0] }, upper: Antichain { elements: [1687993044262] }, since: Antichain { elements: [1687993036000] } }, parts: [HollowBatchPart { key: PartialBatchKey("w47c597c0-19f3-46fb-a5de-365b76b00489/p8b93f327-1571-48f9-b2b8-231bbe9e4bd4"), encoded_size_bytes: 1052, stats: None }], len: 1, runs: [] }, HollowBatch { desc: Description { lower: Antichain { elements: [1687993044262] }, upper: Antichain { elements: [1687993159591] }, since: Antichain { elements: [1687993128000] } }, parts: [], len: 0, runs: [] }, HollowBatch { desc: Description { lower: Antichain { elements: [1687993159591] }, upper: Antichain { elements: [1687993160592] }, since: Antichain { elements: [0] } }, parts: [], len: 0, runs: [] }}`', /home/sean/github/sploiselle/materialize/src/persist-client/src/internal/state_versions.rs:976:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Here it is preventing me from booting:

```
environmentd: 2023-06-28T23:03:47.611738Z  INFO environmentd::run:environmentd::serve:bootstrap: mz_adapter::coord: coordinator init: table size 2
environmentd: 2023-06-28T23:03:47.611799Z  INFO environmentd::run:environmentd::serve:bootstrap: mz_adapter::coord: coordinator init: sending builtin table updates
environmentd: 2023-06-28T23:03:47.667778Z  INFO environmentd::run:environmentd::serve:bootstrap: mz_adapter::coord: coordinator init: bootstrap complete
environmentd: 2023-06-28T23:03:47.675578Z  INFO environmentd::run:environmentd::serve: mz_adapter::coord: coordinator init: complete
environmentd v0.59.0-dev (1f5c3ff37) listening...
 SQL address: 127.0.0.1:6875
 HTTP address: 127.0.0.1:6876
 Internal SQL address: 127.0.0.1:6877
 Internal HTTP address: 0.0.0.0:6878
 Internal Persist PubSub address: 127.0.0.1:6879
 Root trace ID: 00000000000000000000000000000000
thread 'tokio:work-30' panicked at 'assertion failed: `(left == right)`
  left: `{HollowBatch { desc: Description { lower: Antichain { elements: [0] }, upper: Antichain { elements: [1687993044262] }, since: Antichain { elements: [1687993036000] } }, parts: [HollowBatchPart { key: PartialBatchKey("w47c597c0-19f3-46fb-a5de-365b76b00489/p8b93f327-1571-48f9-b2b8-231bbe9e4bd4"), encoded_size_bytes: 1052, stats: None }], len: 1, runs: [] }, HollowBatch { desc: Description { lower: Antichain { elements: [1687993044262] }, upper: Antichain { elements: [1687993159591] }, since: Antichain { elements: [1687993128000] } }, parts: [], len: 0, runs: [] }, HollowBatch { desc: Description { lower: Antichain { elements: [1687993044262] }, upper: Antichain { elements: [1687993160592] }, since: Antichain { elements: [1687993128000] } }, parts: [], len: 0, runs: [] }}`,
 right: `{HollowBatch { desc: Description { lower: Antichain { elements: [0] }, upper: Antichain { elements: [1687993044262] }, since: Antichain { elements: [1687993036000] } }, parts: [HollowBatchPart { key: PartialBatchKey("w47c597c0-19f3-46fb-a5de-365b76b00489/p8b93f327-1571-48f9-b2b8-231bbe9e4bd4"), encoded_size_bytes: 1052, stats: None }], len: 1, runs: [] }, HollowBatch { desc: Description { lower: Antichain { elements: [1687993044262] }, upper: Antichain { elements: [1687993159591] }, since: Antichain { elements: [1687993128000] } }, parts: [], len: 0, runs: [] }, HollowBatch { desc: Description { lower: Antichain { elements: [1687993159591] }, upper: Antichain { elements: [1687993160592] }, since: Antichain { elements: [0] } }, parts: [], len: 0, runs: [] }}`', /home/sean/github/sploiselle/materialize/src/persist-client/src/internal/state_versions.rs:976:9
stack backtrace:
thread 'tokio:work-29' panicked at 'assertion failed: `(left == right)`
  left: `{HollowBatch { desc: Description { lower: Antichain { elements: [0] }, upper: Antichain { elements: [1687993044262] }, since: Antichain { elements: [1687993036000] } }, parts: [HollowBatchPart { key: PartialBatchKey("w62472d6b-84b4-478f-abff-0bfcd25ffa1b/p949db049-6354-4e84-8874-c845fafc127c"), encoded_size_bytes: 1004, stats: None }], len: 1, runs: [] }, HollowBatch { desc: Description { lower: Antichain { elements: [1687993044262] }, upper: Antichain { elements: [1687993159591] }, since: Antichain { elements: [1687993128000] } }, parts: [], len: 0, runs: [] }, HollowBatch { desc: Description { lower: Antichain { elements: [1687993044262] }, upper: Antichain { elements: [1687993160592] }, since: Antichain { elements: [1687993128000] } }, parts: [], len: 0, runs: [] }}`,
 right: `{HollowBatch { desc: Description { lower: Antichain { elements: [0] }, upper: Antichain { elements: [1687993044262] }, since: Antichain { elements: [1687993036000] } }, parts: [HollowBatchPart { key: PartialBatchKey("w62472d6b-84b4-478f-abff-0bfcd25ffa1b/p949db049-6354-4e84-8874-c845fafc127c"), encoded_size_bytes: 1004, stats: None }], len: 1, runs: [] }, HollowBatch { desc: Description { lower: Antichain { elements: [1687993044262] }, upper: Antichain { elements: [1687993159591] }, since: Antichain { elements: [1687993128000] } }, parts: [], len: 0, runs: [] }, HollowBatch { desc: Description { lower: Antichain { elements: [1687993159591] }, upper: Antichain { elements: [1687993160592] }, since: Antichain { elements: [0] } }, parts: [], len: 0, runs: [] }}`', /home/sean/github/sploiselle/materialize/src/persist-client/src/internal/state_versions.rs:976:9
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: mz_persist_client::internal::state_versions::ReferencedBlobValidator<T>::validate_against_state
   5: mz_persist_client::internal::state_versions::StateVersionsIter<T>::next
   6: mz_persist_client::internal::gc::GarbageCollector<K,V,T,D>::find_removable_blobs
   7: mz_persist_client::internal::gc::GarbageCollector<K,V,T,D>::incrementally_delete_and_truncate::{{closure}}
   8: mz_persist_client::internal::gc::GarbageCollector<K,V,T,D>::gc_and_truncate::{{closure}}
   9: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  10: mz_persist_client::internal::gc::GarbageCollector<K,V,T,D>::new::{{closure}}
  11: <core::pin::Pin<P> as core::future::future::Future>::poll
  12: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
  13: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  14: tokio::runtime::task::core::Core<T,S>::poll
  15: tokio::runtime::task::harness::poll_future::{{closure}}
  16: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  17: std::panicking::try::do_call
  18: __rust_try
  19: std::panicking::try
  20: std::panic::catch_unwind
  21: tokio::runtime::task::harness::poll_future
  22: tokio::runtime::task::harness::Harness<T,S>::poll_inner
  23: tokio::runtime::task::harness::Harness<T,S>::poll
  24: tokio::runtime::task::raw::poll
  25: tokio::runtime::task::raw::RawTask::poll
  26: tokio::runtime::task::LocalNotified<S>::run
  27: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
  28: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  29: tokio::runtime::scheduler::multi_thread::worker::Context::run
  30: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
  31: tokio::macros::scoped_tls::ScopedKey<T>::set
  32: tokio::runtime::scheduler::multi_thread::worker::run
  33: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
  34: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  35: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
  36: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  37: tokio::runtime::task::core::Core<T,S>::poll
  38: tokio::runtime::task::harness::poll_future::{{closure}}
  39: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  40: std::panicking::try::do_call
  41: __rust_try
  42: std::panicking::try
  43: std::panic::catch_unwind
  44: tokio::runtime::task::harness::poll_future
  45: tokio::runtime::task::harness::Harness<T,S>::poll_inner
  46: tokio::runtime::task::harness::Harness<T,S>::poll
  47: tokio::runtime::task::raw::poll
  48: tokio::runtime::task::raw::RawTask::poll
  49: tokio::runtime::task::UnownedTask<S>::run
  50: tokio::runtime::blocking::pool::Task::run
  51: tokio::runtime::blocking::pool::Inner::run
  52: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
```

I see that the partial batch key and the number of bytes differ:
![Screenshot 2023-06-28 at 7 13 07 PM](https://github.com/MaterializeInc/materialize/assets/19260003/1b996ade-feb4-45cf-9be7-59fccd5fb1d3)

Is it possible that the partial batch key is based off of some kind of hash of the ingestion description and we didn't anticipate those changing?

**Comment by benesch** [comment]
After scrutinizing the error messages, I feel confident this is the same as #20009, so merging this issue into that one.

@sploiselle the way the error message got rendered is quite confusing, but I'm 98% sure that what happened is you had two separate threads panic with the same error at the same time for _different_ shards...

```
thread 'tokio:work-30' panicked at 'assertion failed: `(left == right)`
  left: `{HollowBatch { desc: Description { lower: Antichain { elements: [0] }, upper: Antichain { elements: [1687993044262] }, since: Antichain { elements: [1687993036000] } }, parts: [HollowBatchPart { key: PartialBatchKey("w47c597c0-19f3-46fb-a5de-365b76b00489/p8b93f327-1571-48f9-b2b8-231bbe9e4bd4"), encoded_size_bytes: 1052, stats: None }], len: 1, runs: [] }, HollowBatch { desc: Description { lower: Antichain { elements: [1687993044262] }, upper: Antichain { elements: [1687993159591] }, since: Antichain { elements: [1687993128000] } }, parts: [], len: 0, runs: [] }, HollowBatch { desc: Description { lower: Antichain { elements: [1687993044262] }, upper: Antichain { elements: [1687993160592] }, since: Antichain { elements: [1687993128000] } }, parts: [], len: 0, runs: [] }}`,
 right: `{HollowBatch { desc: Description { lower: Antichain { elements: [0] }, upper: Antichain { elements: [1687993044262] }, since: Antichain { elements: [1687993036000] } }, parts: [HollowBatchPart { key: PartialBatchKey("w47c597c0-19f3-46fb-a5de-365b76b00489/p8b93f327-1571-48f9-b2b8-231bbe9e4bd4"), encoded_size_bytes: 1052, stats: None }], len: 1, runs: [] }, HollowBatch { desc: Description { lower: Antichain { elements: [1687993044262] }, upper: Antichain { elements: [1687993159591] }, since: Antichain { elements: [1687993128000] } }, parts: [], len: 0, runs: [] }, HollowBatch { desc: Description { lower: Antichain { elements: [1687993159591] }, upper: Antichain { elements: [1687993160592] }, since: Antichain { elements: [0] } }, parts: [], len: 0, runs: [] }}`', /home/sean/github/sploiselle/materialize/src/persist-client/src/internal/state_versions.rs:976:9
stack backtrace:
thread 'tokio:work-29' panicked at 'assertion failed: `(left == right)`
  left: `{HollowBatch { desc: Description { lower: Antichain { elements: [0] }, upper: Antichain { elements: [1687993044262] }, since: Antichain { elements: [1687993036000] } }, parts: [HollowBatchPart { key: PartialBatchKey("w62472d6b-84b4-478f-abff-0bfcd25ffa1b/p949db049-6354-4e84-8874-c845fafc127c"), encoded_size_bytes: 1004, stats: None }], len: 1, runs: [] }, HollowBatch { desc: Description { lower: Antichain { elements: [1687993044262] }, upper: Antichain { elements: [1687993159591] }, since: Antichain { elements: [1687993128000] } }, parts: [], len: 0, runs: [] }, HollowBatch { desc: Description { lower: Antichain { elements: [1687993044262] }, upper: Antichain { elements: [1687993160592] }, since: Antichain { elements: [1687993128000] } }, parts: [], len: 0, runs: [] }}`,
 right: `{HollowBatch { desc: Description { lower: Antichain { elements: [0] }, upper: Antichain { elements: [1687993044262] }, since: Antichain { elements: [1687993036000] } }, parts: [HollowBatchPart { key: PartialBatchKey("w62472d6b-84b4-478f-abff-0bfcd25ffa1b/p949db049-6354-4e84-8874-c845fafc127c"), encoded_size_bytes: 1004, stats: None }], len: 1, runs: [] }, HollowBatch { desc: Description { lower: Antichain { elements: [1687993044262] }, upper: Antichain { elements: [1687993159591] }, since: Antichain { elements: [1687993128000] } }, parts: [], len: 0, runs: [] }, HollowBatch { desc: Description { lower: Antichain { elements: [1687993159591] }, upper: Antichain { elements: [1687993160592] }, since: Antichain { elements: [0] } }, parts: [], len: 0, runs: [] }}`', /home/sean/github/sploiselle/materialize/src/persist-client/src/internal/state_versions.rs:976:9
```

If you compare `left` vs `right` for either thread, the start of the values have the same partial batch key; it's just the very last hollow batch that has a difference in the lower and since. It looks like the diff you did compared thread 29's panic to thread 30's panic, which made this _seem_ like a different bug than #20009.

**Comment by sploiselle** [comment]
@benesch ty--had a very long day yesterday

**Comment by benesch** [comment]
No, don't apologize! I'm glad you filed it. To be honest, a bit spooked that so many folks presumably encountered this bug locally and _didn't_ file it!
