### ISSUE TITLE
[SQLsmith] thread 'coordinator' panicked at '`NaiveDateTime - Duration` overflowed' in timezone function

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#20324]
### What version of Materialize are you using?

1a8c38b82508ca495a5f5d582a364fe39921a180

### What is the issue?

```sql
SELECT pg_catalog.timezone(-INTERVAL '1' MINUTE, TIMESTAMP '95143-12-31 23:59:59' + INTERVAL '167 MILLENNIUM');
```
```
thread 'coordinator' panicked at '`NaiveDateTime - Duration` overflowed', /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.25/src/naive/datetime/mod.rs:1583:38
stack backtrace:
   0: rust_begin_unwind
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/panicking.rs:147:5
   3: core::panicking::panic_str
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/panicking.rs:131:5
   4: core::option::expect_failed
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/option.rs:1926:5
   5: core::option::Option<T>::expect
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/option.rs:786:21
   6: <chrono::naive::datetime::NaiveDateTime as core::ops::arith::Sub<chrono::oldtime::Duration>>::sub
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.25/src/naive/datetime/mod.rs:1583:9
   7: <mz_repr::adt::timestamp::CheckedTimestamp<T> as core::ops::arith::Sub<chrono::oldtime::Duration>>::sub
             at ./src/repr/src/adt/timestamp.rs:804:9
   8: mz_expr::scalar::func::timezone_interval_timestamp
             at ./src/expr/src/scalar/func.rs:1908:32
   9: mz_expr::scalar::func::BinaryFunc::eval
             at ./src/expr/src/scalar/func.rs:2408:54
  10: mz_expr::scalar::MirScalarExpr::eval
             at ./src/expr/src/scalar/mod.rs:1761:17
  11: mz_expr::scalar::MirScalarExpr::reduce::{{closure}}
             at ./src/expr/src/scalar/mod.rs:682:36
  12: mz_expr::scalar::MirScalarExpr::reduce::{{closure}}
             at ./src/expr/src/scalar/mod.rs:751:34
  13: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}
             at ./src/expr/src/visit.rs:719:13
  14: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  15: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  16: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit
             at ./src/expr/src/visit.rs:711:9
  17: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:717:50
  18: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::VisitChildren<mz_expr::scalar::MirScalarExpr>>::visit_mut_children
             at ./src/expr/src/scalar/mod.rs:1882:17
  19: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}
             at ./src/expr/src/visit.rs:717:17
  20: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  21: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  22: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit
             at ./src/expr/src/visit.rs:711:9
  23: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:717:50
  24: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::VisitChildren<mz_expr::scalar::MirScalarExpr>>::visit_mut_children
             at ./src/expr/src/scalar/mod.rs:1886:21
  25: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}
             at ./src/expr/src/visit.rs:717:17
  26: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  27: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  28: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit
             at ./src/expr/src/visit.rs:711:9
  29: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:717:50
  30: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::VisitChildren<mz_expr::scalar::MirScalarExpr>>::visit_mut_children
             at ./src/expr/src/scalar/mod.rs:1886:21
  31: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}
             at ./src/expr/src/visit.rs:717:17
  32: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  33: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  34: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit
             at ./src/expr/src/visit.rs:711:9
  35: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:717:50
  36: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::VisitChildren<mz_expr::scalar::MirScalarExpr>>::visit_mut_children
             at ./src/expr/src/scalar/mod.rs:1886:21
  37: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit::{{closure}}
             at ./src/expr/src/visit.rs:717:17
  38: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  39: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  40: mz_expr::visit::StackSafeVisit<T>::visit_mut_pre_post_nolimit
             at ./src/expr/src/visit.rs:711:9
  41: <T as mz_expr::visit::Visit>::visit_mut_pre_post_nolimit
             at ./src/expr/src/visit.rs:439:9
  42: mz_expr::scalar::MirScalarExpr::reduce
             at ./src/expr/src/scalar/mod.rs:690:13
  43: mz_expr::relation::canonicalize::canonicalize_predicates::{{closure}}
             at ./src/expr/src/relation/canonicalize.rs:208:40
  44: <core::slice::iter::IterMut<T> as core::iter::traits::iterator::Iterator>::for_each
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/slice/iter/macros.rs:201:21
  45: mz_expr::relation::canonicalize::canonicalize_predicates
             at ./src/expr/src/relation/canonicalize.rs:208:5
  46: mz_transform::fusion::filter::Filter::action
             at ./src/transform/src/fusion/filter.rs:88:13
  47: mz_transform::fusion::Fusion::action
             at ./src/transform/src/fusion/mod.rs:52:47
  48: <mz_transform::normalize_ops::NormalizeOps as mz_transform::Transform>::transform::{{closure}}
             at ./src/transform/src/normalize_ops.rs:40:17
  49: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}
             at ./src/expr/src/visit.rs:556:13
  50: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  51: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  52: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  53: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  54: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post
             at ./src/expr/src/visit.rs:554:9
  55: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:555:50
  56: <mz_expr::relation::MirRelationExpr as mz_expr::visit::VisitChildren<mz_expr::relation::MirRelationExpr>>::try_visit_mut_children
             at ./src/expr/src/relation/mod.rs:2166:13
  57: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}
             at ./src/expr/src/visit.rs:555:13
  58: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  59: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  60: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  61: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  62: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post
             at ./src/expr/src/visit.rs:554:9
  63: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:555:50
  64: <mz_expr::relation::MirRelationExpr as mz_expr::visit::VisitChildren<mz_expr::relation::MirRelationExpr>>::try_visit_mut_children
             at ./src/expr/src/relation/mod.rs:2166:13
  65: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}
             at ./src/expr/src/visit.rs:555:13
  66: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  67: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  68: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  69: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  70: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post
             at ./src/expr/src/visit.rs:554:9
  71: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:555:50
  72: <mz_expr::relation::MirRelationExpr as mz_expr::visit::VisitChildren<mz_expr::relation::MirRelationExpr>>::try_visit_mut_children
             at ./src/expr/src/relation/mod.rs:2166:13
  73: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}
             at ./src/expr/src/visit.rs:555:13
  74: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  75: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  76: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  77: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  78: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post
             at ./src/expr/src/visit.rs:554:9
  79: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:555:50
  80: <mz_expr::relation::MirRelationExpr as mz_expr::visit::VisitChildren<mz_expr::relation::MirRelationExpr>>::try_visit_mut_children
             at ./src/expr/src/relation/mod.rs:2166:13
  81: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}
             at ./src/expr/src/visit.rs:555:13
  82: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  83: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  84: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  85: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  86: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post
             at ./src/expr/src/visit.rs:554:9
  87: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:555:50
  88: <mz_expr::relation::MirRelationExpr as mz_expr::visit::VisitChildren<mz_expr::relation::MirRelationExpr>>::try_visit_mut_children
             at ./src/expr/src/relation/mod.rs:2166:13
  89: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}
             at ./src/expr/src/visit.rs:555:13
  90: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  91: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  92: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  93: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  94: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post
             at ./src/expr/src/visit.rs:554:9
  95: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:555:50
  96: <mz_expr::relation::MirRelationExpr as mz_expr::visit::VisitChildren<mz_expr::relation::MirRelationExpr>>::try_visit_mut_children
             at ./src/expr/src/relation/mod.rs:2166:13
  97: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}
             at ./src/expr/src/visit.rs:555:13
  98: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  99: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
 100: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
 101: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
 102: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post
             at ./src/expr/src/visit.rs:554:9
 103: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:555:50
 104: <mz_expr::relation::MirRelationExpr as mz_expr::visit::VisitChildren<mz_expr::relation::MirRelationExpr>>::try_visit_mut_children
             at ./src/expr/src/relation/mod.rs:2166:13
 105: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}
             at ./src/expr/src/visit.rs:555:13
 106: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
 107: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
 108: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
 109: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
 110: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post
             at ./src/expr/src/visit.rs:554:9
 111: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:555:50
 112: <mz_expr::relation::MirRelationExpr as mz_expr::visit::VisitChildren<mz_expr::relation::MirRelationExpr>>::try_visit_mut_children
             at ./src/expr/src/relation/mod.rs:2166:13
 113: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}
             at ./src/expr/src/visit.rs:555:13
 114: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
 115: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
 116: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
 117: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
 118: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post
             at ./src/expr/src/visit.rs:554:9
 119: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:555:50
 120: <mz_expr::relation::MirRelationExpr as mz_expr::visit::VisitChildren<mz_expr::relation::MirRelationExpr>>::try_visit_mut_children
             at ./src/expr/src/relation/mod.rs:2166:13
 121: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}
             at ./src/expr/src/visit.rs:555:13
 122: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
 123: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
 124: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
 125: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
 126: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post
             at ./src/expr/src/visit.rs:554:9
 127: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:555:50
 128: <mz_expr::relation::MirRelationExpr as mz_expr::visit::VisitChildren<mz_expr::relation::MirRelationExpr>>::try_visit_mut_children
             at ./src/expr/src/relation/mod.rs:2166:13
 129: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}
             at ./src/expr/src/visit.rs:555:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

```
ci-regexp: panicked at '`NaiveDateTime - Duration` overflowed'
ci-regexp: panicked at '`NaiveDateTime + Duration` overflowed'
```

**Comment by mjibson** [comment]
This is not fixed by the upcoming changes in https://github.com/MaterializeInc/materialize/pull/20283.
