### ISSUE TITLE
parallel-workload: thread 'coordinator' panicked at 'no entry found for key', src/adapter/src/catalog.rs:572:10 

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#20402]
### What version of Materialize are you using?

2e088905e27e7846b94f8b70c19904804c14a411

### What is the issue?

Happened in https://buildkite.com/materialize/nightlies/builds/2755#018930d6-6d4f-4d06-a89b-7ea9df2546d0 with my new parallel-workload: https://github.com/MaterializeInc/materialize/pull/20354
```
parallel-workload-materialized-1  | thread 'coordinator' panicked at 'no entry found for key', src/adapter/src/catalog.rs:572:10
parallel-workload-materialized-1  | stack backtrace:
parallel-workload-materialized-1  |    0: rust_begin_unwind
parallel-workload-materialized-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
parallel-workload-materialized-1  |    1: core::panicking::panic_fmt
parallel-workload-materialized-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
parallel-workload-materialized-1  |    2: core::panicking::panic_display
parallel-workload-materialized-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:147:5
parallel-workload-materialized-1  |    3: core::panicking::panic_str
parallel-workload-materialized-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:131:5
parallel-workload-materialized-1  |    4: core::option::expect_failed
parallel-workload-materialized-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/option.rs:1924:5
parallel-workload-materialized-1  |    5: <core::option::Option<&mz_adapter::catalog::CatalogEntry>>::expect
parallel-workload-materialized-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/option.rs:786:21
parallel-workload-materialized-1  |    6: <alloc::collections::btree::map::BTreeMap<mz_repr::global_id::GlobalId, mz_adapter::catalog::CatalogEntry> as core::ops::index::Index<&mz_repr::global_id::GlobalId>>::index
parallel-workload-materialized-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/collections/btree/map.rs:2216:23
parallel-workload-materialized-1  |    7: <mz_adapter::catalog::CatalogState>::get_entry
parallel-workload-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0096274f7b6df3875-1/materialize/tests/src/adapter/src/catalog.rs:572:10
parallel-workload-materialized-1  |    8: <mz_adapter::catalog::ConnCatalog as mz_sql::catalog::SessionCatalog>::get_item
parallel-workload-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0096274f7b6df3875-1/materialize/tests/src/adapter/src/catalog.rs:8251:9
parallel-workload-materialized-1  |    9: mz_adapter::rbac::generate_required_privileges::<mz_adapter::catalog::ConnCatalog>
parallel-workload-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0096274f7b6df3875-1/materialize/tests/src/adapter/src/rbac.rs:940:39
parallel-workload-materialized-1  |   10: mz_adapter::rbac::check_plan::<mz_adapter::catalog::ConnCatalog>
parallel-workload-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0096274f7b6df3875-1/materialize/tests/src/adapter/src/rbac.rs:203:31
parallel-workload-materialized-1  |   11: <mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}::{closure#0}
parallel-workload-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0096274f7b6df3875-1/materialize/tests/src/adapter/src/coord/sequencer.rs:92:25
parallel-workload-materialized-1  |   12: <mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}
parallel-workload-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0096274f7b6df3875-1/materialize/tests/src/adapter/src/coord/sequencer.rs:57:5
parallel-workload-materialized-1  |   13: <mz_adapter::coord::Coordinator>::message_write_lock_grant::{closure#0}::{closure#0}
parallel-workload-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0096274f7b6df3875-1/materialize/tests/src/adapter/src/coord/message_handler.rs:588:25
parallel-workload-materialized-1  |   14: <mz_adapter::coord::Coordinator>::message_write_lock_grant::{closure#0}
parallel-workload-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0096274f7b6df3875-1/materialize/tests/src/adapter/src/coord/message_handler.rs:573:5
parallel-workload-materialized-1  |   15: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
parallel-workload-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0096274f7b6df3875-1/materialize/tests/src/adapter/src/coord/message_handler.rs:70:64
parallel-workload-materialized-1  |   16: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_message::{closure#0}> as core::future::future::Future>::poll
parallel-workload-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
parallel-workload-materialized-1  |   17: <mz_adapter::coord::Coordinator>::serve::{closure#0}
parallel-workload-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0096274f7b6df3875-1/materialize/tests/src/adapter/src/coord.rs:1515:17
parallel-workload-materialized-1  |   18: <tokio::runtime::park::CachedParkThread>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}
parallel-workload-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:63
parallel-workload-materialized-1  |   19: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}>
parallel-workload-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:107:5
parallel-workload-materialized-1  |   20: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}>
parallel-workload-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:73:5
parallel-workload-materialized-1  |   21: <tokio::runtime::park::CachedParkThread>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
parallel-workload-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:31
parallel-workload-materialized-1  |   22: <tokio::runtime::context::BlockingRegionGuard>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
parallel-workload-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/context.rs:315:13
parallel-workload-materialized-1  |   23: <tokio::runtime::handle::Handle>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
parallel-workload-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/handle.rs:264:9
parallel-workload-materialized-1  |   24: mz_adapter::coord::serve::{closure#0}::{closure#1}
parallel-workload-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0096274f7b6df3875-1/materialize/tests/src/adapter/src/coord.rs:1741:17
parallel-workload-materialized-1  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
I tried running it locally, but didn't get the panic: `bin/parallel-workload-test --threads=100 --runtime=7200 --seed=1688741552 --complexity=ddl`, so probably timing-dependent. I'll try to see if I can reproduce this reliably.

There were similar panics before: https://github.com/MaterializeInc/materialize/issues/18996

**Comment by jkosh44** [comment]
It looks like we were in the process of sequencing a read then write plan but the table we were querying did not exist so we panicked. @def- is there a summary of what this test does somewhere?

**Comment by def-** [comment]
Locally reproduced on first try with the current state of https://github.com/MaterializeInc/materialize/pull/20354:
```bash
$ git checkout b5c23857d7ff9765dfd2948493279061bafbcae5
$ bin/mzcompose --find parallel-workload down && bin/mzcompose --find parallel-workload run default --threads=100 --complexity=ddl --seed=1688741552 --runtime=3000
$ docker logs ... 2>&1 | grep panicked
thread 'coordinator' panicked at 'no entry found for key', src/adapter/src/catalog.rs:572:10
```

**Comment by jkosh44** [comment]
I've been able to reproduce this very consistently. It seems like the panic always occurs on a `ReadThenWrite` plan.

I added some logs statements to the following places to try and piece together a story of what's happening:
- The beginning of parsing.
- The beginning of planning.
- The beginning of RBAC checks (which is really just the beginning of sequencing).
- The end of catalog transactions.


Here is a sample log of the crucial events that lead to this panic:

1. [17:52:59.926380] Parse `CREATE TABLE t2 ...`
2. [17:52:59.945230] Plan `CreateTable(t2)`
3. [17:52:59.946426] RBAC check `CreateTable(t2)`
4. [17:53:00.049799] Catalog transact commit for `CreateTable(t2 [u5])`
5. [17:53:44.583555] Parse `UPDATE t2 SET c1_smallint = -14433 WHERE c0_boolean = FALSE;`
6. [17:53:44.985722] Plan `Update(t2)`
7. [17:53:44.987042] RBAC check `ReadThenWrite(t2 [u5])`
8. [17:58:36.442300] Parse `DROP TABLE t2`
9. [17:58:36.569138] Plan `DropObjects(t2)`
10. [17:58:36.573830] RBAC check `DropObjects(t2 [u5])`
11. [17:58:36.886723] Catalog transact commit for `DropObjects(t2 [u5])`
12. [17:59:40.501302] Parse `CREATE TABLE t2 ...`
13. [17:59:41.154534] Plan `CreateTable(t2)`
14. [17:59:41.156119] RBAC check `CreateTable(t2)`
15. [17:59:41.357164] Catalog transact commit for `CreateTable(t2 [u102])`
16. [18:00:33.467221] RBAC check for `ReadThenWrite(t2 [u5])` and panic because `u5` doesn't exist

Step 16 is very strange. Why are we re-sequencing the update? Additionally it's unclear to me if it matters that a new table with the same name exists.

**Comment by jkosh44** [comment]
One explanation is the Update was deferred due to contention over the write lock. The first sequencing deferred the update, then the second sequencing it was able to acquire the write lock but it didn't re-check that it's dependencies were valid.

**Comment by jkosh44** [comment]
Yep, that's definitely the issue. If I make the following somewhat crude fix:

```
diff --git a/src/adapter/src/coord/message_handler.rs b/src/adapter/src/coord/message_handler.rs
index 2ddf7d6f1f..bbbb2e059b 100644
--- a/src/adapter/src/coord/message_handler.rs
+++ b/src/adapter/src/coord/message_handler.rs
@@ -35,7 +35,7 @@ use crate::coord::{
     PeekStageFinish, PeekValidity, PendingReadTxn, RealTimeRecencyContext, SinkConnectionReady,
 };
 use crate::util::ResultExt;
-use crate::{catalog, AdapterNotice};
+use crate::{catalog, AdapterError, AdapterNotice};
 
 impl Coordinator {
     pub(crate) async fn handle_message(&mut self, msg: Message) {
@@ -584,8 +584,17 @@ impl Coordinator {
                     // Write statements never need to track catalog
                     // dependencies.
                     let resolved_ids = ResolvedIds(BTreeSet::new());
-                    self.sequence_plan(ready.ctx, ready.plan, resolved_ids)
-                        .await;
+                    if ready
+                        .plan
+                        .dependencies()
+                        .iter()
+                        .any(|id| self.catalog().try_get_entry(id).is_none())
+                    {
+                        ready.ctx.retire(Err(AdapterError::Canceled));
+                    } else {
+                        self.sequence_plan(ready.ctx, ready.plan, resolved_ids)
+                            .await;
+                    }
                 }
                 Deferred::GroupCommit => self.group_commit_initiate(Some(write_lock_guard)).await,
             }
diff --git a/src/sql/src/plan.rs b/src/sql/src/plan.rs
index b06c8cd251..b304b12254 100644
--- a/src/sql/src/plan.rs
+++ b/src/sql/src/plan.rs
@@ -258,6 +258,18 @@ impl Plan {
         }
     }
 
+    pub fn dependencies(&self) -> Vec<GlobalId> {
+        match self {
+            Plan::ReadThenWrite(plan) => plan
+                .selection
+                .depends_on()
+                .into_iter()
+                .chain(std::iter::once(plan.id))
+                .collect(),
+            _ => Vec::new(),
+        }
+    }
+
     /// Returns a human readable name of the plan. Meant for use in messages sent back to a user.
     pub fn name(&self) -> &str {
         match self {
```

Then the panic goes away and the logs are filled with messages like: `worker_11 Query failed: UPDATE t6 SET c16_int = -476662299 WHERE c0_boolean = TRUE; {'S': 'ERROR', 'C': '57014', 'M': 'canceling statement due to user request'}`
