### ISSUE TITLE
OSError: [Errno 25] Inappropriate ioctl for device

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#20435]
### What version of Materialize are you using?

7b6c8fd3b1f3cc5ccc81a13f6530c633dd250e4e

### What is the issue?

```
$ /home/deen/git/materialize2/target/debug/environmentd --internal-http-listen-addr=0.0.0.0:6878 --orchestrator=process --orchestrator-process-secrets-directory=/home/deen/git/materialize2/mzdata/secrets --orchestrator-process-tcp-proxy-listen-addr=0.0.0.0 --orchestrator-process-prometheus-service-discovery-directory=/home/deen/git/materialize2/mzdata/prometheus --orchestrator-process-scratch-directory=/home/deen/git/materialize2/scratch --persist-consensus-url=postgres://root@localhost:26257/materialize?options=--search_path=consensus --persist-blob-url=file:///home/deen/git/materialize2/mzdata/persist/blob --adapter-stash-url=postgres://root@localhost:26257/materialize?options=--search_path=adapter --storage-stash-url=postgres://root@localhost:26257/materialize?options=--search_path=storage --environment-id=local-az1-b8b64529-60dc-494c-bfb2-7f99bf85c4aa-0 --bootstrap-role=materialize
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/deen/git/materialize2/misc/python/materialize/cli/run.py", line 352, in <module>
    main()
  File "/home/deen/git/materialize2/misc/python/materialize/cli/run.py", line 244, in main
    _set_foreground_process(os.getpid())
  File "/home/deen/git/materialize2/misc/python/materialize/cli/run.py", line 266, in _set_foreground_process
    os.tcsetpgrp(tty.fileno(), os.getpgrp())
OSError: [Errno 25] Inappropriate ioctl for device
```
It fixed itself on the next restart. Code in question comes from https://github.com/MaterializeInc/materialize/pull/17295

**Comment by tokenrove** [comment]
Yeah, I'll fix this.  The whole dance of setting controlling terminals is notoriously racy and inconsistent, so we shouldn't bail on ENOTTY.  Thanks for catching it.
