### ISSUE TITLE
parallel-workload: thread 'coordinator' panicked at 'unable to cancel peek: InstanceMissing(User(41))', /home/deen/git/materialize/src/adapter/src/util.rs:280:23

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#20468]
### What version of Materialize are you using?

90eab10548572f18e6fdeec6e6165ec532a53e6e

### What is the issue?

Using the new WIP parallel-workload with create/drop/set cluster: https://github.com/MaterializeInc/materialize/pull/20354
```
git checkout 90eab10548572f18e6fdeec6e6165ec532a53e6e
bin/environmentd --release --reset
bin/parallel-workload-test --threads=16 --complexity=ddl --scenario=regression --seed=1688671291
```
Can be reproduced in 1 minute on my system:
```
thread 'coordinator' panicked at 'unable to cancel peek: InstanceMissing(User(41))', /home/deen/git/materialize/src/adapter/src/util.rs:280:23
stack backtrace:
   0: rust_begin_unwind
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/panicking.rs:64:14
   2: <core::result::Result<T,E> as mz_adapter::util::ResultExt<T>>::unwrap_or_terminate
             at ./src/adapter/src/util.rs:280:23
   3: mz_adapter::coord::ddl::<impl mz_adapter::coord::Coordinator>::catalog_transact_with::{{closure}}::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/ddl.rs:378:25
   4: mz_adapter::coord::ddl::<impl mz_adapter::coord::Coordinator>::catalog_transact_with::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/ddl.rs:450:9
   5: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
   6: mz_adapter::coord::ddl::<impl mz_adapter::coord::Coordinator>::catalog_transact_with::{{closure}}
             at ./src/adapter/src/coord/ddl.rs:81:5
   7: mz_adapter::coord::ddl::<impl mz_adapter::coord::Coordinator>::catalog_transact::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/ddl.rs:68:61
   8: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
   9: mz_adapter::coord::ddl::<impl mz_adapter::coord::Coordinator>::catalog_transact::{{closure}}
             at ./src/adapter/src/coord/ddl.rs:62:5
  10: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::sequence_drop_objects::{{closure}}
             at ./src/adapter/src/coord/sequencer/inner.rs:1144:50
  11: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_plan::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:202:81
  12: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  13: mz_adapter::coord::sequencer::<impl mz_adapter::coord::Coordinator>::sequence_plan::{{closure}}
             at ./src/adapter/src/coord/sequencer.rs:57:5
  14: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute_inner::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:671:72
  15: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  16: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute_inner::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:431:5
  17: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:428:53
  18: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  19: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_execute::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:375:5
  20: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  21: mz_adapter::coord::command_handler::<impl mz_adapter::coord::Coordinator>::handle_command::{{closure}}
             at ./src/adapter/src/coord/command_handler.rs:126:71
  22: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_command::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:241:33
  23: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  24: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::message_command::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:238:5
  25: mz_adapter::coord::message_handler::<impl mz_adapter::coord::Coordinator>::handle_message::{{closure}}
             at ./src/adapter/src/coord/message_handler.rs:43:63
  26: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
  27: mz_adapter::coord::Coordinator::serve::{{closure}}
             at ./src/adapter/src/coord.rs:1524:17
  28: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:63
  29: tokio::runtime::coop::with_budget
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:107:5
  30: tokio::runtime::coop::budget
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:73:5
  31: tokio::runtime::park::CachedParkThread::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:31
  32: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/context.rs:315:13
  33: tokio::runtime::handle::Handle::block_on
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/handle.rs:264:9
  34: mz_adapter::coord::serve::{{closure}}::{{closure}}
             at ./src/adapter/src/coord.rs:1752:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by def-** [comment]
This assertion came in via https://github.com/MaterializeInc/materialize/pull/17524

**Comment by def-** [comment]
@mjibson It seems like this panic actually comes in from your wip fix that I included in my branch, I can't reproduce it when `environmentd` is running without it yet: https://github.com/MaterializeInc/materialize/pull/20354/commits/ee5c1e47bbb6317d34ea2717ff5078d7c7569f16

**Comment by jkosh44** [comment]
Here's some backstory on the panic. When we drop some relation, we check if there any outstanding peeks. If we find any then we send a message to the controller to drop that peek, the message includes what cluster is serving that peek. This specific error is saying that the cluster we sent to the controller doesn't exist.
