### ISSUE TITLE
thread 'coordinator' panicked at 'can't persist timestamp: Error { kind: Stash(StashError { inner: Postgres(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42P01), message: "relation \"fence\" does not exist"

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#20510]
### What version of Materialize are you using?

9d6e043d24c762679e07d95f45db403e5a6defd0

### What is the issue?

This fails in my WIP change to test persistence of all objects in mzcompose: https://github.com/MaterializeInc/materialize/pull/20505

https://buildkite.com/materialize/tests/builds/59379#01894ee3-ae80-4b03-93a1-e7064e211fee

The source is created with timeline:
```
> CREATE SOURCE data_foo FROM KAFKA CONNECTION kafka_conn (TOPIC 'testdrive-foo-2174522029') FORMAT AVRO USING SCHEMA '[ {   "type": "array",   "items": {     "type": "record",     "name": "update",     "namespace": "com.materialize.cdc",     "fields": [       {         "name": "data",         "type": {           "type": "record",           "name": "data",           "fields": [             {"name": "a", "type": "long"},             {"name": "b", "type": "long"}           ]         }       },       {         "name": "time",         "type": "long"       },       {         "name": "diff",         "type": "long"       }     ]   } }, {   "type": "record",   "name": "progress",   "namespace": "com.materialize.cdc",   "fields": [     {       "name": "lower",       "type": {         "type": "array",         "items": "long"       }     },     {       "name": "upper",       "type": {         "type": "array",         "items": "long"       }     },     {       "name": "counts",       "type": {         "type": "array",         "items": {           "type": "record",           "name": "counts",           "fields": [             {               "name": "time",               "type": "long"             },             {               "name": "count",               "type": "long"             }           ]         }       }     }   ] } ]' ENVELOPE MATERIALIZE WITH (TIMELINE 'user')
```
And fails when restarting Mz:
```
restart-materialized-1  | thread 'coordinator' panicked at 'can't persist timestamp: Error { kind: Stash(StashError { inner: Postgres(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42P01), message: "relation \"fence\" does not exist", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("errors.go"), line: Some(171), routine: Some("NewUndefinedRelationError") }) }) }) }', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ceb892e68e96c12c-1/materialize/tests/src/adapter/src/util.rs:280:23
restart-materialized-1  | stack backtrace:
restart-materialized-1  |    0: rust_begin_unwind
restart-materialized-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
restart-materialized-1  |    1: core::panicking::panic_fmt
restart-materialized-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
restart-materialized-1  |    2: <core::result::Result<(), mz_adapter::catalog::error::Error> as mz_adapter::util::ResultExt<()>>::unwrap_or_terminate
restart-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ceb892e68e96c12c-1/materialize/tests/src/adapter/src/util.rs:280:23
restart-materialized-1  |    3: <mz_adapter::coord::timeline::DurableTimestampOracle<mz_repr::timestamp::Timestamp>>::maybe_allocate_new_timestamps::<<mz_adapter::catalog::Catalog>::persist_timestamp::{closure#0}, <mz_adapter::coord::Coordinator>::get_local_write_ts::{closure#0}::{closure#0}::{closure#0}>::{closure#0}
restart-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ceb892e68e96c12c-1/materialize/tests/src/adapter/src/coord/timeline.rs:340:13
restart-materialized-1  |    4: <mz_adapter::coord::timeline::DurableTimestampOracle<mz_repr::timestamp::Timestamp>>::write_ts::<<mz_adapter::catalog::Catalog>::persist_timestamp::{closure#0}, <mz_adapter::coord::Coordinator>::get_local_write_ts::{closure#0}::{closure#0}::{closure#0}>::{closure#0}
restart-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ceb892e68e96c12c-1/materialize/tests/src/adapter/src/coord/timeline.rs:288:13
restart-materialized-1  |    5: <mz_adapter::coord::Coordinator>::get_local_write_ts::{closure#0}::{closure#0}
restart-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ceb892e68e96c12c-1/materialize/tests/src/adapter/src/coord/timeline.rs:404:13
restart-materialized-1  |    6: <mz_adapter::coord::Coordinator>::get_local_write_ts::{closure#0}
restart-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ceb892e68e96c12c-1/materialize/tests/src/adapter/src/coord/timeline.rs:394:5
restart-materialized-1  |    7: <mz_adapter::coord::Coordinator>::group_commit_initiate::{closure#0}::{closure#0}
restart-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ceb892e68e96c12c-1/materialize/tests/src/adapter/src/coord/appends.rs:252:38
restart-materialized-1  |    8: <mz_adapter::coord::Coordinator>::group_commit_initiate::{closure#0}
restart-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ceb892e68e96c12c-1/materialize/tests/src/adapter/src/coord/appends.rs:194:5
restart-materialized-1  |    9: <mz_adapter::coord::Coordinator>::try_group_commit::{closure#0}::{closure#0}
restart-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ceb892e68e96c12c-1/materialize/tests/src/adapter/src/coord/appends.rs:178:45
restart-materialized-1  |   10: <mz_adapter::coord::Coordinator>::try_group_commit::{closure#0}
restart-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ceb892e68e96c12c-1/materialize/tests/src/adapter/src/coord/appends.rs:158:5
restart-materialized-1  |   11: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
restart-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ceb892e68e96c12c-1/materialize/tests/src/adapter/src/coord/message_handler.rs:73:40
restart-materialized-1  |   12: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_message::{closure#0}> as core::future::future::Future>::poll
restart-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.37/src/instrument.rs:272:9
restart-materialized-1  |   13: <mz_adapter::coord::Coordinator>::serve::{closure#0}
restart-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ceb892e68e96c12c-1/materialize/tests/src/adapter/src/coord.rs:1524:17
restart-materialized-1  |   14: <tokio::runtime::park::CachedParkThread>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}
restart-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:63
restart-materialized-1  |   15: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}>
restart-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:107:5
restart-materialized-1  |   16: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}>
restart-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:73:5
restart-materialized-1  |   17: <tokio::runtime::park::CachedParkThread>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
restart-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:31
restart-materialized-1  |   18: <tokio::runtime::context::BlockingRegionGuard>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
restart-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/context.rs:315:13
restart-materialized-1  |   19: <tokio::runtime::handle::Handle>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
restart-materialized-1  |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/handle.rs:264:9
restart-materialized-1  |   20: mz_adapter::coord::serve::{closure#0}::{closure#1}
restart-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ceb892e68e96c12c-1/materialize/tests/src/adapter/src/coord.rs:1752:17
restart-materialized-1  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
My interpretation is that we can't persist the `TIMELINE 'user'` part of the source. Fails reliably.

Came in via https://github.com/MaterializeInc/materialize/pull/13385

**Comment by def-** [comment]
Update: This still happens without the timelines workflow: https://buildkite.com/materialize/tests/builds/59399#01894f78-67da-4bd2-887f-9ab9687d15d1 It seems to fail after github-8021.td, I'll try disabling that file and see if that works around it: https://buildkite.com/materialize/tests/builds/59415

**Comment by def-** [comment]
I think you are right, sorry for the noise. Somehow I didn't notice that it came from this workflow.

**Comment by ParkMyCar** [comment]
No problem at all! Glad it was an easy fix 🙂
