### ISSUE TITLE
`retry::tests::test_retry_fail_max_duration` is flaky

### ISSUE THREAD

**Issue by antiguru** [MaterializeInc/materialize#20529]
### Buildkite link

https://buildkite.com/materialize/tests/builds/59442#018950a0-dd7a-4966-bbe7-5c522e8b593e

### Relevant log output

```source
[2023-07-13T19:16:23Z] thread 'retry::tests::test_retry_fail_max_duration' panicked at 'called `Option::unwrap()` on a `None` value', src/ore/src/retry.rs:705:46
[2023-07-13T19:16:23Z] stack backtrace:
[2023-07-13T19:16:23Z]    0: rust_begin_unwind
[2023-07-13T19:16:23Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
[2023-07-13T19:16:23Z]    1: core::panicking::panic_fmt
[2023-07-13T19:16:23Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
[2023-07-13T19:16:23Z]    2: core::panicking::panic
[2023-07-13T19:16:23Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:114:5
[2023-07-13T19:16:23Z]    3: <core::option::Option<core::time::Duration>>::unwrap
[2023-07-13T19:16:23Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/option.rs:823:21
[2023-07-13T19:16:23Z]    4: mz_ore::retry::tests::test_retry_fail_max_duration::test_impl
[2023-07-13T19:16:23Z]              at ./src/retry.rs:705:23
[2023-07-13T19:16:23Z]    5: mz_ore::retry::tests::test_retry_fail_max_duration
[2023-07-13T19:16:23Z]              at ./src/retry.rs:679:5
[2023-07-13T19:16:23Z]    6: mz_ore::retry::tests::test_retry_fail_max_duration::{closure#0}
[2023-07-13T19:16:23Z]              at ./src/retry.rs:679:5
[2023-07-13T19:16:23Z]    7: <mz_ore::retry::tests::test_retry_fail_max_duration::{closure#0} as core::ops::function::FnOnce<()>>::call_once
[2023-07-13T19:16:23Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
[2023-07-13T19:16:23Z]    8: core::ops::function::FnOnce::call_once
[2023-07-13T19:16:23Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
```

**Comment by def-** [comment]
Seen again in https://buildkite.com/materialize/tests/builds/73719#018d3349-63c7-4e87-a35c-63b54b4cbec9
