### ISSUE TITLE
thread 'tokio:work-7' panicked at 'can't serialize 3::List { element_type: Int32, custom_id: None }', src/pgrepr/src/value.rs:204:18

### ISSUE THREAD

**Issue by vmarcos** [MaterializeInc/materialize#20534]
### What version of Materialize are you using?

v0.61.0-dev (33504d503)

### What is the issue?

The following error was detected when using `sqllogictest` to run `test/sqllogicttest/list.slt` with `--auto-index-selects` and observing that failures occur only in view-based execution. The failures in the test manifest as reports of `db error: ERROR: binary encoding of list types is not implemented`.

By creating a reproduction of the issue, I hit, however, a panic. Here is a sequence of SQL statements, taken from `test/sqllogictest/list.slt` that will get the panic to occur:
```sql
CREATE TABLE t3(f1 int, f2 int, f3 int, f4 int, f5 int, f6 int, f7 int, f8 int, n int, m int, l int list);
CREATE VIEW m3 AS SELECT * FROM t3;
CREATE DEFAULT INDEX ON m3;
INSERT INTO t3 VALUES (1, 2, 3, 4, 5, 6, 7, 8, 1, 2, list[42, 43]);
INSERT INTO t3 VALUES (11, 12, 13, 14, 15, 16, 17, 18, 11, 12, list[82, 83]);

SELECT LIST[[[f1, f2], [f3, f4]], [[f5, f6], [f7, f8]]] [n][m][1] from m3;

CREATE VIEW v AS SELECT LIST[[[f1, f2], [f3, f4]], [[f5, f6], [f7, f8]]] [n][m][1] from m3;
SELECT * FROM v;
```
We get the following in `psql` when executing the above:
```
CREATE TABLE
CREATE VIEW
CREATE INDEX
INSERT 0 1
INSERT 0 1
 list 
------
     
    3
(2 rows)

CREATE VIEW
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!?> 
```
The following stack backtrace is produced in the logs:
```
environmentd: 2023-07-13T22:02:18.589958Z  INFO mz_adapter::catalog: create table materialize.public.t3 (u5)
environmentd: 2023-07-13T22:02:18.717382Z  INFO mz_adapter::catalog: create view materialize.public.m3 (u6)
environmentd: 2023-07-13T22:02:18.797369Z  INFO mz_adapter::catalog: create index materialize.public.m3_primary_idx (u7)
environmentd: 2023-07-13T22:02:18.949029Z  INFO mz_adapter::catalog: create view materialize.public.v (u8)
thread 'tokio:work-4' panicked at 'can't serialize 3::List { element_type: Int32, custom_id: None }', src/pgrepr/src/value.rs:204:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: mz_pgrepr::value::Value::from_datum
   3: mz_pgrepr::value::values_from_row::{{closure}}
   4: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   5: core::option::Option<T>::map
   6: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
   7: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
   8: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   9: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
  10: core::iter::traits::iterator::Iterator::collect
  11: mz_pgrepr::value::values_from_row
  12: mz_pgwire::protocol::StateMachine<A>::send_rows::{{closure}}::{{closure}}::{{closure}}
  13: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  14: core::option::Option<T>::map
  15: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
  16: mz_pgwire::protocol::StateMachine<A>::send_all::{{closure}}
  17: mz_pgwire::protocol::StateMachine<A>::send_rows::{{closure}}::{{closure}}
  18: mz_pgwire::protocol::StateMachine<A>::send_rows::{{closure}}
  19: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  20: mz_pgwire::protocol::StateMachine<A>::send_execute_response::{{closure}}
  21: mz_pgwire::protocol::StateMachine<A>::one_query::{{closure}}
  22: mz_pgwire::protocol::StateMachine<A>::query::{{closure}}
  23: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  24: mz_pgwire::protocol::StateMachine<A>::advance_ready::{{closure}}
  25: mz_pgwire::protocol::StateMachine<A>::run::{{closure}}::{{closure}}
  26: mz_pgwire::protocol::StateMachine<A>::run::{{closure}}
  27: mz_pgwire::protocol::run::{{closure}}::{{closure}}::{{closure}}
  28: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  29: mz_pgwire::protocol::run::{{closure}}::{{closure}}
  30: mz_pgwire::protocol::run::{{closure}}
  31: mz_pgwire::server::Server::handle_connection::{{closure}}::{{closure}}::{{closure}}::{{closure}}
  32: mz_pgwire::server::Server::handle_connection::{{closure}}::{{closure}}
  33: mz_pgwire::server::Server::handle_connection::{{closure}}
  34: <core::pin::Pin<P> as core::future::future::Future>::poll
  35: mz_environmentd::server::serve::{{closure}}::{{closure}}
  36: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
  37: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  38: tokio::runtime::task::core::Core<T,S>::poll
  39: tokio::runtime::task::harness::poll_future::{{closure}}
  40: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  41: std::panicking::try::do_call
  42: ___rust_try
  43: std::panicking::try
  44: std::panic::catch_unwind
  45: tokio::runtime::task::harness::poll_future
  46: tokio::runtime::task::harness::Harness<T,S>::poll_inner
  47: tokio::runtime::task::harness::Harness<T,S>::poll
  48: tokio::runtime::task::raw::poll
  49: tokio::runtime::task::raw::RawTask::poll
  50: tokio::runtime::task::LocalNotified<S>::run
  51: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
  52: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  53: tokio::runtime::scheduler::multi_thread::worker::Context::run
  54: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
  55: tokio::macros::scoped_tls::ScopedKey<T>::set
  56: tokio::runtime::scheduler::multi_thread::worker::run
  57: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
  58: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  59: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
  60: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  61: tokio::runtime::task::core::Core<T,S>::poll
  62: tokio::runtime::task::harness::poll_future::{{closure}}
  63: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  64: std::panicking::try::do_call
  65: ___rust_try
  66: std::panicking::try
  67: std::panic::catch_unwind
  68: tokio::runtime::task::harness::poll_future
  69: tokio::runtime::task::harness::Harness<T,S>::poll_inner
  70: tokio::runtime::task::harness::Harness<T,S>::poll
  71: tokio::runtime::task::raw::poll
  72: tokio::runtime::task::raw::RawTask::poll
  73: tokio::runtime::task::UnownedTask<S>::run
  74: tokio::runtime::blocking::pool::Task::run
  75: tokio::runtime::blocking::pool::Inner::run
  76: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
cluster-s1-replica-2: 2023-07-13T22:02:19.490170Z  WARN mz_persist_client::rpc: pubsub client error: Status { code: Unknown, message: "error reading a body from connection: stream closed because of a broken pipe", source: Some(hyper::Error(Body, Error { kind: Io(Custom { kind: BrokenPipe, error: "stream closed because of a broken pipe" }) })) }
```

**Comment by mjibson** [comment]
Lists are known not to have binary encoding. If you ever encounter that error, you need to cast your list to `::text`. The panic is a different story and will be triaged.
