### ISSUE TITLE
[SQLsmith] thread 'tokio:work-2' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:525:5

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#20545]
### What version of Materialize are you using?

ed9e68097fde736d963b9a8de62a194fe361e78f

### What is the issue?

Minimal reproducer:
```sql
select csv_extract(9223372036854775807, '');
```
```
thread 'tokio:work-2' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:525:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/panicking.rs:64:14
   2: alloc::raw_vec::capacity_overflow
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/alloc/src/raw_vec.rs:525:5
   3: alloc::raw_vec::RawVec<T,A>::allocate_in
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/alloc/src/raw_vec.rs:178:27
   4: alloc::raw_vec::RawVec<T,A>::with_capacity_in
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/alloc/src/raw_vec.rs:131:9
   5: alloc::vec::Vec<T,A>::with_capacity_in
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/alloc/src/vec/mod.rs:676:20
   6: alloc::vec::Vec<T>::with_capacity
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/alloc/src/vec/mod.rs:483:9
   7: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/alloc/src/vec/spec_from_iter_nested.rs:54:33
   8: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/alloc/src/vec/spec_from_iter.rs:33:9
   9: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/alloc/src/vec/mod.rs:2724:9
  10: core::iter::traits::iterator::Iterator::collect
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/iter/traits/iterator.rs:1860:9
  11: mz_sql::func::MZ_CATALOG_BUILTINS::{{closure}}::{{closure}}
             at ./src/sql/src/func.rs:3122:86
  12: mz_sql::func::Operation<R>::binary::{{closure}}
             at ./src/sql/src/func.rs:297:13
  13: mz_sql::func::Operation<R>::variadic::{{closure}}
             at ./src/sql/src/func.rs:326:13
  14: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/alloc/src/boxed.rs:2002:9
  15: mz_sql::func::select_impl
             at ./src/sql/src/func.rs:1017:5
  16: mz_sql::plan::query::plan_table_function_internal
             at ./src/sql/src/plan/query.rs:2741:22
  17: mz_sql::plan::query::plan_solitary_table_function
             at ./src/sql/src/plan/query.rs:2642:29
  18: mz_sql::plan::query::plan_scalar_table_funcs
             at ./src/sql/src/plan/query.rs:2210:13
  19: mz_sql::plan::query::plan_view_select
             at ./src/sql/src/plan/query.rs:1839:29
  20: mz_sql::plan::query::plan_query_inner
             at ./src/sql/src/plan/query.rs:1125:24
  21: mz_sql::plan::query::plan_query::{{closure}}
             at ./src/sql/src/plan/query.rs:1085:33
  22: mz_ore::stack::CheckedRecursion::checked_recur_mut::{{closure}}
             at ./src/ore/src/stack.rs:205:33
  23: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/stacker-0.1.15/src/lib.rs:55:9
  24: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  25: mz_ore::stack::CheckedRecursion::checked_recur_mut
             at ./src/ore/src/stack.rs:205:19
  26: mz_sql::plan::query::plan_query
             at ./src/sql/src/plan/query.rs:1085:9
  27: mz_sql::plan::query::plan_root_query
             at ./src/sql/src/plan/query.rs:111:47
  28: mz_sql::plan::statement::dml::describe_select
             at ./src/sql/src/plan/statement/dml.rs:173:9
  29: mz_sql::plan::statement::describe
             at ./src/sql/src/plan/statement.rs:208:36
  30: mz_adapter::util::describe
             at ./src/adapter/src/util.rs:248:16
  31: mz_adapter::coord::sql::<impl mz_adapter::coord::Coordinator>::declare_inner
             at ./src/adapter/src/coord/sql.rs:60:20
  32: mz_adapter::coord::sql::<impl mz_adapter::coord::Coordinator>::declare::{{closure}}
             at ./src/adapter/src/coord/sql.rs:47:26
  33: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/core.rs:223:17
  34: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/loom/std/unsafe_cell.rs:14:9
  35: tokio::runtime::task::core::Core<T,S>::poll
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/core.rs:212:13
  36: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:476:19
  37: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/panic/unwind_safe.rs:271:9
  38: std::panicking::try::do_call
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/panicking.rs:483:40
  39: std::panicking::try
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/panicking.rs:447:19
  40: std::panic::catch_unwind
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/panic.rs:140:14
  41: tokio::runtime::task::harness::poll_future
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:464:18
  42: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:198:27
  43: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:152:15
  44: tokio::runtime::task::raw::RawTask::poll
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/raw.rs:200:18
  45: tokio::runtime::task::LocalNotified<S>::run
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/mod.rs:394:9
  46: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:464:13
  47: tokio::runtime::coop::with_budget
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:107:5
  48: tokio::runtime::coop::budget
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:73:5
  49: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
  50: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:426:24
  51: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:406:17
  52: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/macros/scoped_tls.rs:61:9
  53: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:403:5
  54: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
  55: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/blocking/task.rs:42:21
  56: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/core.rs:223:17
  57: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/loom/std/unsafe_cell.rs:14:9
  58: tokio::runtime::task::core::Core<T,S>::poll
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/core.rs:212:13
  59: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:476:19
  60: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/core/src/panic/unwind_safe.rs:271:9
  61: std::panicking::try::do_call
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/panicking.rs:483:40
  62: std::panicking::try
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/panicking.rs:447:19
  63: std::panic::catch_unwind
             at /rustc/065852def0903296da33a9eaf557f230bcf3a61a/library/std/src/panic.rs:140:14
  64: tokio::runtime::task::harness::poll_future
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:464:18
  65: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:198:27
  66: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:152:15
  67: tokio::runtime::task::raw::RawTask::poll
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/raw.rs:200:18
  68: tokio::runtime::task::UnownedTask<S>::run
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/mod.rs:431:9
  69: tokio::runtime::blocking::pool::Task::run
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/blocking/pool.rs:159:9
  70: tokio::runtime::blocking::pool::Inner::run
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/blocking/pool.rs:513:17
  71: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/deen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/blocking/pool.rs:471:13
```
The panic is reproducible.
@ParkMyCar Since you took a similar one last time, are you interested in looking into this? https://github.com/MaterializeInc/materialize/pull/17968

ci-regexp: panicked at 'capacity overflow'

**Comment by ParkMyCar** [comment]
@def- for sure, I'll take a look at this probably on Monday, since we're starting the Hackathon shortly
