### ISSUE TITLE
thread 'tokio:work-51' panicked at '{accept=>*/*,content-length=>3,host=>materialized:6876}', src/expr/src/scalar/func/impls/string.rs:922:9

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#20544]
### What version of Materialize are you using?

b593673cf052de547664ebf325eea6dc42c21e5e

### What is the issue?

The following panic occurred during "Testdrive 3" in build [tests#59449](https://buildkite.com/materialize/tests/builds/59449) and subsequent builds. It first occurred with the merge of https://github.com/MaterializeInc/materialize/pull/20487.

```
testdrive-materialized-1     | thread 'tokio:work-51' panicked at '{accept=>*/*,content-length=>3,host=>materialized:6876}', src/expr/src/scalar/func/impls/string.rs:922:9
testdrive-materialized-1     | stack backtrace:
testdrive-materialized-1     |    0: rust_begin_unwind
testdrive-materialized-1     |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
testdrive-materialized-1     |    1: core::panicking::panic_fmt
testdrive-materialized-1     |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
testdrive-materialized-1     |    2: core::panicking::panic_display::<&str>
testdrive-materialized-1     |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:147:5
testdrive-materialized-1     |    3: mz_expr::scalar::func::impls::string::panic
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a0e8eae96921b29e-1/materialize/tests/src/expr/src/scalar/func/impls/string.rs:922:9
testdrive-materialized-1     |    4: <mz_expr::scalar::func::impls::string::Panic as mz_expr::scalar::func::EagerUnaryFunc>::call
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a0e8eae96921b29e-1/materialize/tests/src/expr/src/scalar/func/macros.rs:153:21
testdrive-materialized-1     |    5: <mz_expr::scalar::func::impls::string::Panic as mz_expr::scalar::func::LazyUnaryFunc>::eval
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a0e8eae96921b29e-1/materialize/tests/src/expr/src/scalar/func.rs:4239:26
testdrive-materialized-1     |    6: <mz_expr::scalar::func::UnaryFunc>::eval
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a0e8eae96921b29e-1/materialize/tests/src/expr/src/scalar/func/macros.rs:343:41
testdrive-materialized-1     |    7: <mz_expr::scalar::MirScalarExpr>::eval
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a0e8eae96921b29e-1/materialize/tests/src/expr/src/scalar/mod.rs:1759:56
testdrive-materialized-1     |    8: <mz_expr::scalar::func::impls::datum::IsNull as mz_expr::scalar::func::LazyUnaryFunc>::eval
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a0e8eae96921b29e-1/materialize/tests/src/expr/src/scalar/func.rs:4237:41
testdrive-materialized-1     |    9: <mz_expr::scalar::func::UnaryFunc>::eval
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a0e8eae96921b29e-1/materialize/tests/src/expr/src/scalar/func/macros.rs:343:41
testdrive-materialized-1     |   10: <mz_expr::scalar::MirScalarExpr>::eval
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a0e8eae96921b29e-1/materialize/tests/src/expr/src/scalar/mod.rs:1759:56
testdrive-materialized-1     |   11: <mz_adapter::coord::Coordinator>::handle_append_webhook::resolve::{closure#2}::{closure#0}
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a0e8eae96921b29e-1/materialize/tests/src/adapter/src/coord/command_handler.rs:890:45
testdrive-materialized-1     |   12: <<mz_adapter::coord::Coordinator>::handle_append_webhook::resolve::{closure#2}::{closure#0} as core::ops::function::FnOnce<(mz_repr::scalar::Datum, mz_repr::scalar::Datum)>>::call_once::{shim:vtable#0}
testdrive-materialized-1     |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
testdrive-materialized-1     |   13: <alloc::boxed::Box<dyn for<'a, 'b> core::ops::function::FnOnce<(mz_repr::scalar::Datum<'a>, mz_repr::scalar::Datum<'b>), Output = core::result::Result<bool, mz_expr::scalar::EvalError>> + core::panic::unwind_safe::UnwindSafe + core::marker::Send> as core::ops::function::FnOnce<(mz_repr::scalar::Datum, mz_repr::scalar::Datum)>>::call_once
testdrive-materialized-1     |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:1988:9
testdrive-materialized-1     |   14: mz_environmentd::http::webhook::validate_request::{closure#0}::{closure#1}::{closure#1}
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a0e8eae96921b29e-1/materialize/tests/src/environmentd/src/http/webhook.rs:95:55
testdrive-materialized-1     |   15: std::panicking::try::do_call::<mz_environmentd::http::webhook::validate_request::{closure#0}::{closure#1}::{closure#1}, core::result::Result<bool, mz_expr::scalar::EvalError>>
testdrive-materialized-1     |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
testdrive-materialized-1     |   16: std::panicking::try::<core::result::Result<bool, mz_expr::scalar::EvalError>, mz_environmentd::http::webhook::validate_request::{closure#0}::{closure#1}::{closure#1}>
testdrive-materialized-1     |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
testdrive-materialized-1     |   17: std::panic::catch_unwind::<mz_environmentd::http::webhook::validate_request::{closure#0}::{closure#1}::{closure#1}, core::result::Result<bool, mz_expr::scalar::EvalError>>
testdrive-materialized-1     |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
testdrive-materialized-1     |   18: mz_ore::panic::catch_unwind::<mz_environmentd::http::webhook::validate_request::{closure#0}::{closure#1}::{closure#1}, core::result::Result<bool, mz_expr::scalar::EvalError>>::{closure#0}
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a0e8eae96921b29e-1/materialize/tests/src/ore/src/panic.rs:78:19
testdrive-materialized-1     |   19: <std::thread::local::LocalKey<core::cell::RefCell<bool>>>::try_with::<mz_ore::panic::catch_unwind<mz_environmentd::http::webhook::validate_request::{closure#0}::{closure#1}::{closure#1}, core::result::Result<bool, mz_expr::scalar::EvalError>>::{closure#0}, core::result::Result<core::result::Result<bool, mz_expr::scalar::EvalError>, alloc::boxed::Box<dyn core::any::Any + core::marker::Send>>>
testdrive-materialized-1     |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/thread/local.rs:446:16
testdrive-materialized-1     |   20: <std::thread::local::LocalKey<core::cell::RefCell<bool>>>::with::<mz_ore::panic::catch_unwind<mz_environmentd::http::webhook::validate_request::{closure#0}::{closure#1}::{closure#1}, core::result::Result<bool, mz_expr::scalar::EvalError>>::{closure#0}, core::result::Result<core::result::Result<bool, mz_expr::scalar::EvalError>, alloc::boxed::Box<dyn core::any::Any + core::marker::Send>>>
testdrive-materialized-1     |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/thread/local.rs:422:9
testdrive-materialized-1     |   21: mz_ore::panic::catch_unwind::<mz_environmentd::http::webhook::validate_request::{closure#0}::{closure#1}::{closure#1}, core::result::Result<bool, mz_expr::scalar::EvalError>>
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a0e8eae96921b29e-1/materialize/tests/src/ore/src/panic.rs:75:5
testdrive-materialized-1     |   22: mz_environmentd::http::webhook::validate_request::{closure#0}::{closure#1}
testdrive-materialized-1     |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0a0e8eae96921b29e-1/materialize/tests/src/environmentd/src/http/webhook.rs:95:19
testdrive-materialized-1     |   23: <tokio::runtime::blocking::task::BlockingTask<mz_environmentd::http::webhook::validate_request::{closure#0}::{closure#1}> as core::future::future::Future>::poll
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/blocking/task.rs:42:21
testdrive-materialized-1     |   24: <tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<mz_environmentd::http::webhook::validate_request::{closure#0}::{closure#1}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll::{closure#0}
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/core.rs:223:17
testdrive-materialized-1     |   25: <tokio::loom::std::unsafe_cell::UnsafeCell<tokio::runtime::task::core::Stage<tokio::runtime::blocking::task::BlockingTask<mz_environmentd::http::webhook::validate_request::{closure#0}::{closure#1}>>>>::with_mut::<core::task::poll::Poll<core::result::Result<bool, mz_environmentd::http::webhook::WebhookError>>, <tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<mz_environmentd::http::webhook::validate_request::{closure#0}::{closure#1}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll::{closure#0}>
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/loom/std/unsafe_cell.rs:14:9
testdrive-materialized-1     |   26: <tokio::runtime::task::core::Core<tokio::runtime::blocking::task::BlockingTask<mz_environmentd::http::webhook::validate_request::{closure#0}::{closure#1}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/core.rs:212:13
testdrive-materialized-1     |   27: tokio::runtime::task::harness::poll_future::<tokio::runtime::blocking::task::BlockingTask<mz_environmentd::http::webhook::validate_request::{closure#0}::{closure#1}>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:476:19
testdrive-materialized-1     |   28: <core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tokio::runtime::blocking::task::BlockingTask<mz_environmentd::http::webhook::validate_request::{closure#0}::{closure#1}>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}> as core::ops::function::FnOnce<()>>::call_once
testdrive-materialized-1     |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panic/unwind_safe.rs:271:9
testdrive-materialized-1     |   29: std::panicking::try::do_call::<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tokio::runtime::blocking::task::BlockingTask<mz_environmentd::http::webhook::validate_request::{closure#0}::{closure#1}>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}>, core::task::poll::Poll<core::result::Result<bool, mz_environmentd::http::webhook::WebhookError>>>
testdrive-materialized-1     |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
testdrive-materialized-1     |   30: std::panicking::try::<core::task::poll::Poll<core::result::Result<bool, mz_environmentd::http::webhook::WebhookError>>, core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tokio::runtime::blocking::task::BlockingTask<mz_environmentd::http::webhook::validate_request::{closure#0}::{closure#1}>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}>>
testdrive-materialized-1     |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
testdrive-materialized-1     |   31: std::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tokio::runtime::blocking::task::BlockingTask<mz_environmentd::http::webhook::validate_request::{closure#0}::{closure#1}>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}>, core::task::poll::Poll<core::result::Result<bool, mz_environmentd::http::webhook::WebhookError>>>
testdrive-materialized-1     |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
testdrive-materialized-1     |   32: tokio::runtime::task::harness::poll_future::<tokio::runtime::blocking::task::BlockingTask<mz_environmentd::http::webhook::validate_request::{closure#0}::{closure#1}>, tokio::runtime::blocking::schedule::BlockingSchedule>
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:464:18
testdrive-materialized-1     |   33: <tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<mz_environmentd::http::webhook::validate_request::{closure#0}::{closure#1}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll_inner
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:198:27
testdrive-materialized-1     |   34: <tokio::runtime::task::harness::Harness<tokio::runtime::blocking::task::BlockingTask<mz_environmentd::http::webhook::validate_request::{closure#0}::{closure#1}>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/harness.rs:152:15
testdrive-materialized-1     |   35: <tokio::runtime::task::raw::RawTask>::poll
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/raw.rs:200:18
testdrive-materialized-1     |   36: <tokio::runtime::task::UnownedTask<tokio::runtime::blocking::schedule::BlockingSchedule>>::run
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/task/mod.rs:431:9
testdrive-materialized-1     |   37: <tokio::runtime::blocking::pool::Task>::run
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/blocking/pool.rs:159:9
testdrive-materialized-1     |   38: <tokio::runtime::blocking::pool::Inner>::run
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/blocking/pool.rs:513:17
testdrive-materialized-1     |   39: <tokio::runtime::blocking::pool::Spawner>::spawn_thread::{closure#0}
testdrive-materialized-1     |              at ./cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/blocking/pool.rs:471:13
testdrive-materialized-1     | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
testdrive-materialized-1     | environmentd: 2023-07-13T20:13:40.796578Z ERROR mz_environmentd::http::webhook: panic while validating webhook request!
```

Further panics occurred in [nightly#2835](https://buildkite.com/materialize/nightlies/builds/2835):
* testdrive with --kafka-default-partitions 5
* testdrive
* testdrive with SIZE 1
* ...

**Comment by ParkMyCar** [comment]
I believe this panic is expected! As part of `webhook.td` we purposefully panic the validation. We [catch the panic but report it to Sentry](https://github.com/MaterializeInc/materialize/blob/main/src/environmentd/src/http/webhook.rs#L96-L102) and it seems like the test is failing because of the new Sentry error.

@nrainer-materialize is there a way to tell testdrive that this error message being reported to Sentry is expected?

**Comment by nrainer-materialize** [comment]
> I believe this panic is expected! As part of `webhook.td` we purposefully panic the validation. We [catch the panic but report it to Sentry](https://github.com/MaterializeInc/materialize/blob/main/src/environmentd/src/http/webhook.rs#L96-L102) and it seems like the test is failing because of the new Sentry error.
> 
> @nrainer-materialize is there a way to tell testdrive that this error message being reported to Sentry is expected?

I took this error message from the build, which also contains panics and other warnings. We can ignore errors by adding a pattern to the file `./misc/python/materialize/cli/ci_logged_errors_detect.py` (after line 50, whitespaces need to be escaped).

**Comment by ParkMyCar** [comment]
Thanks for the tip! Here's a PR which should special case the error message: https://github.com/MaterializeInc/materialize/pull/20603
