### ISSUE TITLE
[SQLsmith] thread 'tokio:work-12' panicked at 'internal error: entered unreachable code', src/pgrepr/src/types.rs

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#20655]
### What version of Materialize are you using?

v0.62.0-dev (a7a15a9be)

### What is the issue?

The minified statement

```
SELECT 
  (mz_internal.mz_role_oid_memberships())
  ->
  (cast(pg_catalog.current_schemas(NULL) as _text));
```
causes a panic of type `entered unreachable code`:

```
thread 'tokio:work-11' panicked at 'internal error: entered unreachable code', src/pgrepr/src/types.rs:670:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
cluster-s2-replica-3: 2023-07-19T13:14:25.003140Z  WARN mz_persist_client::rpc: pubsub client error: Status { code: Unknown, message: "error reading a body from connection: stream closed because of a broken pipe", source: Some(hyper::Error(Body, Error { kind: Io(Custom { kind: BrokenPipe, error: "stream closed because of a broken pipe" }) })) }
cluster-u14-replica-18: 2023-07-19T13:14:25.003139Z  WARN mz_persist_client::rpc: pubsub client error: Status { code: Unknown, message: "error reading a body from connection: stream closed because of a broken pipe", source: Some(hyper::Error(Body, Error { kind: Io(Custom { kind: BrokenPipe, error: "stream closed because of a broken pipe" }) })) }
cluster-u9-replica-12: 2023-07-19T13:14:25.003257Z  WARN mz_persist_client::rpc: pubsub client error: Status { code: Unknown, message: "error reading a body from connection: stream closed because of a brcluster-u9-replica-13: 2023-07-19T13:14:25.003641Z  WARN mz_persist_client::rpc: pubsub client error: Status { code: Unknown, message: "error reading a body from connection: stream closed because of a broken pipe", source: Some(hyper::Error(Body, Error { kind: Io(Custom { kind: BrokenPipe, error: "stream closed because of a broken pipe" }) })) }
cluster-u13-replica-17: 2023-07-19T13:14:25.004011Z  WARN mz_persist_client::rpc: pubsub client error: Status { code: Unknown, message: "error reading a body from connection: stream closed because of a broken pipe", source: Some(hyper::Error(Body, Error { kind: Io(Custom { kind: BrokenPipe, error: "stream closed because of a broken pipe" }) })) }
cluster-u8-replica-10: 2023-07-19T13:14:25.004132Z  WARN mz_persist_client::rpc: pubsub client error: Status { code: Unknown, message: "error reading a body from connection: stream closed because of a broken pipe", source: Some(hyper::Error(Body, Error { kind: Io(Custom { kind: BrokenPipe, error: "stream closed because of a broken pipe" }) })) }
cluster-s1-replica-2: 2023-07-19T13:14:25.003301Z  WARN mz_persist_client::rpc: pubsub client error: Status { code: Unknown, message: "error reading a body from connection: stream closed because of a broken pipe", source: Some(hyper::Error(Body, Error { kind: Io(Custom { kind: BrokenPipe, error: "stream closed because of a broken pipe" }) })) }
```

For reference, it occurred in [Nightly#2881](https://buildkite.com/materialize/nightlies/builds/2881) with the original query:
```
select  
  mz_internal.mz_role_oid_memberships() as c0, 
  (mz_internal.mz_role_oid_memberships()) -> (cast(nullif(case when (pg_catalog.date_trunc(
            CAST((select "id" from mz_catalog.mz_aws_privatelink_connections limit 1 offset 1)
               as text),
            CAST(INTERVAL '2147483647 MONTHS' as interval))) <> (INTERVAL '2147483647 MONTHS') then cast(coalesce((select "extcondition" from pg_catalog.pg_extension limit 1 offset 5)
            ,
          cast(null as _text)) as _text) else cast(coalesce((select "extcondition" from pg_catalog.pg_extension limit 1 offset 5)
            ,
          cast(null as _text)) as _text) end
        ,
      pg_catalog.current_schemas(
        CAST((select "extrelocatable" from pg_catalog.pg_extension limit 1 offset 6)
           as bool))) as _text)) as c1, 
  subq_1."c1" as c2, 
  18 as c3, 
  subq_1."c0" as c4, 
  pg_catalog.tstzrange(
    CAST(case when ((select "cpu_percent" from mz_internal.mz_cluster_replica_utilization limit 1 offset 5)
          ) < ((select "cpu_percent" from mz_internal.mz_cluster_replica_utilization limit 1 offset 1)
          ) then (select "last_heartbeat" from mz_internal.mz_cluster_replica_heartbeats limit 1 offset 5)
         else (select "last_heartbeat" from mz_internal.mz_cluster_replica_heartbeats limit 1 offset 5)
         end
       as timestamptz),
    CAST(pg_catalog.pg_postmaster_start_time() as timestamptz),
    CAST(pg_catalog.current_database() as text)) as c5, 
  subq_1."c0" as c6, 
  subq_1."c0" as c7, 
  ((select "r_regionkey" from public.region limit 1 offset 6)
      ) & (mz_catalog.datediff(
      CAST((select "col4" from public.mv limit 1 offset 2)
         as text),
      CAST(pg_catalog.current_timestamp() as timestamptz),
      CAST(pg_catalog.pg_postmaster_start_time() as timestamptz))) as c8, 
  subq_1."c0" as c9, 
  mz_internal.mz_role_oid_memberships() as c10
from 
  (select  
        subq_0."c2" as c0, 
        subq_0."c0" as c1
      from 
        (select  
              ref_0."worker_id" as c0, 
              ref_0."worker_id" as c1, 
              72 as c2, 
              ref_0."address" as c3, 
              ref_0."address" as c4
            from 
              mz_internal.mz_dataflow_addresses_per_worker as ref_0
            where ((((false) 
                    and ((('{}'::map[text=>text]) <@ ('{}'::map[text=>text])) 
                      or (((select "enumsortorder" from pg_catalog.pg_enum limit 1 offset 5)
                          ) <= (1E-37)))) 
                  and (true)) 
                and ((65535) <= (cast(null as uint2)))) 
              and (((select "time" from mz_internal.mz_compute_frontiers limit 1 offset 43)
                  ) <= (cast(null as mz_timestamp)))
            limit 87) as subq_0
      where ((false) 
          and ((INTERVAL '1' MINUTE) > (INTERVAL '1' MINUTE))) 
        or ((row(1)) = (row(1)))
      limit 61) as subq_1
where ((cast(null as int2)) >> (case when ((((select "details" from mz_internal.mz_source_statuses limit 1 offset 27)
              ) #>> ((select "key" from mz_internal.mz_show_indexes limit 1 offset 1)
              )) !~~ (pg_catalog.substr(
            CAST(cast(null as text) as text),
            CAST(subq_1."c0" as int4)))) 
        and (true) then subq_1."c0" else subq_1."c0" end
      )) < (case when ((select "evtfoid" from pg_catalog.pg_event_trigger limit 1 offset 2)
        ) >= ((select "nspowner" from pg_catalog.pg_namespace limit 1 offset 4)
        ) then (32767) % ((case when false then pg_catalog.abs(
            CAST(cast(null as int2) as int2)) else pg_catalog.abs(
            CAST(cast(null as int2) as int2)) end
          ) / ((select pg_catalog.max("typlen") from pg_catalog.pg_type)
          )) else (32767) % ((case when false then pg_catalog.abs(
            CAST(cast(null as int2) as int2)) else pg_catalog.abs(
            CAST(cast(null as int2) as int2)) end
          ) / ((select pg_catalog.max("typlen") from pg_catalog.pg_type)
          )) end
    );
```
using setup
```
CREATE SOURCE tpch
              FROM LOAD GENERATOR TPCH (SCALE FACTOR 0.00001)
              FOR ALL TABLES
              WITH (SIZE = '1');
CREATE SOURCE auction
              FROM LOAD GENERATOR AUCTION (SCALE FACTOR 0.01)
              FOR ALL TABLES
              WITH (SIZE = '1');
CREATE SOURCE counter
              FROM LOAD GENERATOR COUNTER (SCALE FACTOR 0.0001)
              WITH (SIZE = '1');
CREATE TABLE t (a int2, b int4, c int8, d uint2, e uint4, f uint8, g text);
INSERT INTO t VALUES (1, 2, 3, 4, 5, 6, '7'), (3, 4, 5, 6, 7, 8, '9'), (5, 6, 7, 8, 9, 10, '11'), (7, 8, 9, 10, 11, 12, '13'), (9, 10, 11, 12, 13, 14, '15'), (11, 12, 13, 14, 15, 16, '17'), (13, 14, 15, 16, 17, 18, '19'), (15, 16, 17, 18, 19, 20, '21');
CREATE MATERIALIZED VIEW mv AS SELECT a + b AS col1, c + d AS col2, e + f AS col3, g AS col4 FROM t;
CREATE MATERIALIZED VIEW mv2 AS SELECT count(*) FROM mv;
CREATE DEFAULT INDEX ON mv;
```

The backtrace in the build was:
```
sqlsmith-mz_1-1  | thread 'tokio:work-12' panicked at 'internal error: entered unreachable code', src/pgrepr/src/types.rs:670:35
sqlsmith-mz_1-1  | stack backtrace:
sqlsmith-mz_1-1  |    0: rust_begin_unwind
sqlsmith-mz_1-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
sqlsmith-mz_1-1  |    1: core::panicking::panic_fmt
sqlsmith-mz_1-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
sqlsmith-mz_1-1  |    2: core::panicking::panic
sqlsmith-mz_1-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:114:5
sqlsmith-mz_1-1  |    3: <mz_pgrepr::types::Type>::inner
sqlsmith-mz_1-1  |    4: <mz_pgrepr::types::Type>::oid
sqlsmith-mz_1-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0e98a297ffb659963-1/materialize/tests/src/pgrepr/src/types.rs:815:9
sqlsmith-mz_1-1  |    5: mz_pgwire::message::encode_row_description::{closure#0}
sqlsmith-mz_1-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0e98a297ffb659963-1/materialize/tests/src/pgwire/src/message.rs:512:27
sqlsmith-mz_1-1  |    6: <&mut mz_pgwire::message::encode_row_description::{closure#0} as core::ops::function::FnOnce<(((&mz_repr::relation::ColumnName, &mz_repr::relation::ColumnType), &mz_pgrepr::format::Format),)>>::call_once
sqlsmith-mz_1-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:310:13
sqlsmith-mz_1-1  |    7: <core::option::Option<((&mz_repr::relation::ColumnName, &mz_repr::relation::ColumnType), &mz_pgrepr::format::Format)>>::map::<mz_pgwire::message::FieldDescription, &mut mz_pgwire::message::encode_row_description::{closure#0}>
```

ci-regexp: panicked at 'internal error: entered unreachable code'
ci-apply-to: sqlsmith

**Comment by jkosh44** [comment]
Here's an even easier repro:

`SELECT '{}'::map[text=>text[]] -> '{}'::text[];`

**Comment by mjibson** [comment]
For whoever works on this: `test_smoketest_all_builtins` could have found this if we had more things in `interesting_datums()` and `enumerate()`.

**Comment by mjibson** [comment]
This is happening because `BinaryFunc::MapGetValues` is being called whose type is array of the inner map type, hence we get an array of array of text. The oid fn that panics here assumes we don't have recursive arrays, so we crash. I don't know much about `MapGetValues`, or if it's ok to have it error if its inner type is an array. Feels like this could be easily tripped on by lots of other stuff too and we should have a more general solution.

**Comment by benesch** [comment]
Mentioned this on Slack, but mentioning here too for posterity. I think we should ban map types with array values. Composite types containing arrays were never meant to be supported. We properly disallow them for lists, IIRC. E.g., we don't let you have a `text[] list`. 

There's no _fundamental_ reason we couldn't allow mixing composite types with arrays, but multidimensional arrays are already really weird conceptually in SQL (most people just use them as a 1D list and get really confused when they try to nest them), and so there are all sorts of weird UX questions to sort out when you mix them when lists and maps.

**Comment by nrainer-materialize** [comment]
This is causing generic SQLsmith warnings ("broken connection") in each nightly build, which requires QA to check the cause to make sure that no other cause resulting in the same error message was introduced.

@chaas: How shall we proceed with this ticket?

**Comment by mjibson** [comment]
> we don't let you have a text[] list

It appears we do allow this:

```
materialize=> select pg_typeof(list[['a', 'b'], ['c']]);
   pg_typeof    
----------------
 text list list
(1 row)

materialize=> select list[['a', 'b'], ['c']];
    list     
-------------
 {{a,b},{c}}
(1 row)
```

**Comment by benesch** [comment]
> It appears we do allow this:

Oy! I really thought we disallowed that. Maybe something regressed at some point? Or maybe I'm crazy.

**Comment by benesch** [comment]
> > It appears we do allow this:
> 
> Oy! I really thought we disallowed that. Maybe something regressed at some point? Or maybe I'm crazy.

Ah, I had it backwards. Arrays of lists are not allowed, but lists of arrays are allowed. I think that means the current definition of the `->` operator for maps with an array RHS is just flawed. Posted a longer writeup here: https://github.com/MaterializeInc/materialize/pull/21620#issuecomment-1709465251
