### ISSUE TITLE
[SQLsmith] thread 'timely:work-1' panicked at 'Datum::unwrap_timestamptz called on Time(23:59:60)

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#20704]
### What version of Materialize are you using?

134799f41c9183a12b95ac775f29cf48a2ef5038

### What is the issue?

```
sqlsmith-mz_2-1  | thread 'timely:work-1' panicked at 'Datum::unwrap_timestamptz called on Time(23:59:60)', src/expr/src/scalar/func.rs:7334:28
sqlsmith-mz_2-1  | stack backtrace:
sqlsmith-mz_2-1  |    0: rust_begin_unwind
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
sqlsmith-mz_2-1  |    1: core::panicking::panic_fmt
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
sqlsmith-mz_2-1  |    2: <mz_repr::scalar::Datum>::unwrap_timestamptz
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ee6065e219dd7cae-1/materialize/tests/src/repr/src/scalar.rs:728:18
sqlsmith-mz_2-1  |    3: <mz_expr::scalar::func::VariadicFunc>::eval::{closure#2}
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ee6065e219dd7cae-1/materialize/tests/src/expr/src/scalar/func.rs:7334:22
sqlsmith-mz_2-1  |    4: <core::result::Result<mz_repr::adt::datetime::Timezone, mz_expr::scalar::EvalError>>::map::<mz_repr::scalar::Datum, <mz_expr::scalar::func::VariadicFunc>::eval::{closure#2}>
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:774:25
sqlsmith-mz_2-1  |    5: <mz_expr::scalar::func::VariadicFunc>::eval
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ee6065e219dd7cae-1/materialize/tests/src/expr/src/scalar/func.rs:7330:43
sqlsmith-mz_2-1  |    6: <mz_expr::scalar::MirScalarExpr>::eval
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ee6065e219dd7cae-1/materialize/tests/src/expr/src/scalar/mod.rs:1769:60
sqlsmith-mz_2-1  |    7: <mz_expr::scalar::func::BinaryFunc>::eval
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ee6065e219dd7cae-1/materialize/tests/src/expr/src/scalar/func.rs:2264:17
sqlsmith-mz_2-1  |    8: <mz_expr::scalar::MirScalarExpr>::eval
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ee6065e219dd7cae-1/materialize/tests/src/expr/src/scalar/mod.rs:1767:17
sqlsmith-mz_2-1  |    9: <mz_expr::scalar::func::BinaryFunc>::eval
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ee6065e219dd7cae-1/materialize/tests/src/expr/src/scalar/func.rs:2263:17
sqlsmith-mz_2-1  |   10: <mz_expr::scalar::MirScalarExpr>::eval
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ee6065e219dd7cae-1/materialize/tests/src/expr/src/scalar/mod.rs:1767:17
sqlsmith-mz_2-1  |   11: <mz_expr::linear::plan::SafeMfpPlan>::evaluate_inner
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ee6065e219dd7cae-1/materialize/tests/src/expr/src/linear.rs:1529:20
sqlsmith-mz_2-1  |   12: <mz_expr::linear::plan::SafeMfpPlan>::evaluate_into
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ee6065e219dd7cae-1/materialize/tests/src/expr/src/linear.rs:1485:37
sqlsmith-mz_2-1  |   13: <mz_compute_client::plan::join::JoinClosure>::apply
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ee6065e219dd7cae-1/materialize/tests/src/compute-client/src/plan/join/mod.rs:142:21
sqlsmith-mz_2-1  |   14: mz_compute::render::join::linear_join::differential_join_inner::<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp, differential_dataflow::trace::wrappers::enter::TraceEnter<differential_dataflow::trace::wrappers::frontier::TraceFrontier<differential_dataflow::operators::arrange::agent::TraceAgent<differential_dataflow::trace::implementations::spine_fueled::Spine<alloc::rc::Rc<differential_dataflow::trace::implementations::ord::OrdValBatch<mz_repr::row::Row, mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64, usize, timely_container::columnation::TimelyStack<mz_repr::row::Row>, timely_container::columnation::TimelyStack<mz_repr::row::Row>>>>>>, mz_repr::timestamp::Timestamp>, differential_dataflow::trace::wrappers::enter::TraceEnter<differential_dataflow::trace::wrappers::frontier::TraceFrontier<differential_dataflow::operators::arrange::agent::TraceAgent<differential_dataflow::trace::implementations::spine_fueled::Spine<alloc::rc::Rc<differential_dataflow::trace::implementations::ord::OrdValBatch<mz_repr::row::Row, mz_repr::row::Row, mz_repr::timestamp::Timestamp, i64, usize, timely_container::columnation::TimelyStack<mz_repr::row::Row>, timely_container::columnation::TimelyStack<mz_repr::row::Row>>>>>>, mz_repr::timestamp::Timestamp>>::{closure#0}
```

occurred in build https://buildkite.com/materialize/nightlies/builds/2915.
I was not able to find the related query; either it is not directly caused by a query or it is shadowed by another panic, which occurred.

ci-regexp: Datum::unwrap_timestamptz called on Time

**Comment by mjibson** [comment]
There's more in the log:

```
sqlsmith-mz_2-1  | thread 'tokio:work-4' panicked at 'internal error: entered unreachable code', src/pgrepr/src/types.rs:670:35
sqlsmith-mz_2-1  | stack backtrace:
sqlsmith-mz_2-1  |    0: rust_begin_unwind
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
sqlsmith-mz_2-1  |    1: core::panicking::panic_fmt
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
sqlsmith-mz_2-1  |    2: core::panicking::panic
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:114:5
sqlsmith-mz_2-1  |    3: <mz_pgrepr::types::Type>::inner
sqlsmith-mz_2-1  |    4: <mz_pgrepr::types::Type>::oid
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ee6065e219dd7cae-1/materialize/tests/src/pgrepr/src/types.rs:815:9
sqlsmith-mz_2-1  |    5: mz_pgwire::message::encode_row_description::{closure#0}
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ee6065e219dd7cae-1/materialize/tests/src/pgwire/src/message.rs:512:27
sqlsmith-mz_2-1  |    6: <&mut mz_pgwire::message::encode_row_description::{closure#0} as core::ops::function::FnOnce<(((&mz_repr::relation::ColumnName, &mz_repr::relation::ColumnType), &mz_pgrepr::format::Format),)>>::call_once
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:310:13
sqlsmith-mz_2-1  |    7: <core::option::Option<((&mz_repr::relation::ColumnName, &mz_repr::relation::ColumnType), &mz_pgrepr::format::Format)>>::map::<mz_pgwire::message::FieldDescription, &mut mz_pgwire::message::encode_row_description::{closure#0}>
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/option.rs:970:29
sqlsmith-mz_2-1  |    8: <core::iter::adapters::map::Map<itertools::zip_eq_impl::ZipEq<core::iter::adapters::zip::Zip<core::slice::iter::Iter<mz_repr::relation::ColumnName>, core::slice::iter::Iter<mz_repr::relation::ColumnType>>, core::slice::iter::Iter<mz_pgrepr::format::Format>>, mz_pgwire::message::encode_row_description::{closure#0}> as core::iter::traits::iterator::Iterator>::next
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/iter/adapters/map.rs:103:9
sqlsmith-mz_2-1  |    9: <alloc::vec::Vec<mz_pgwire::message::FieldDescription>>::extend_desugared::<core::iter::adapters::map::Map<itertools::zip_eq_impl::ZipEq<core::iter::adapters::zip::Zip<core::slice::iter::Iter<mz_repr::relation::ColumnName>, core::slice::iter::Iter<mz_repr::relation::ColumnType>>, core::slice::iter::Iter<mz_pgrepr::format::Format>>, mz_pgwire::message::encode_row_description::{closure#0}>>
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/vec/mod.rs:2853:35
sqlsmith-mz_2-1  |   10: <alloc::vec::Vec<mz_pgwire::message::FieldDescription> as alloc::vec::spec_extend::SpecExtend<mz_pgwire::message::FieldDescription, core::iter::adapters::map::Map<itertools::zip_eq_impl::ZipEq<core::iter::adapters::zip::Zip<core::slice::iter::Iter<mz_repr::relation::ColumnName>, core::slice::iter::Iter<mz_repr::relation::ColumnType>>, core::slice::iter::Iter<mz_pgrepr::format::Format>>, mz_pgwire::message::encode_row_description::{closure#0}>>>::spec_extend
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/vec/spec_extend.rs:17:9
sqlsmith-mz_2-1  |   11: <alloc::vec::Vec<mz_pgwire::message::FieldDescription> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<mz_pgwire::message::FieldDescription, core::iter::adapters::map::Map<itertools::zip_eq_impl::ZipEq<core::iter::adapters::zip::Zip<core::slice::iter::Iter<mz_repr::relation::ColumnName>, core::slice::iter::Iter<mz_repr::relation::ColumnType>>, core::slice::iter::Iter<mz_pgrepr::format::Format>>, mz_pgwire::message::encode_row_description::{closure#0}>>>::from_iter
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/vec/spec_from_iter_nested.rs:43:9
sqlsmith-mz_2-1  |   12: <alloc::vec::Vec<mz_pgwire::message::FieldDescription> as alloc::vec::spec_from_iter::SpecFromIter<mz_pgwire::message::FieldDescription, core::iter::adapters::map::Map<itertools::zip_eq_impl::ZipEq<core::iter::adapters::zip::Zip<core::slice::iter::Iter<mz_repr::relation::ColumnName>, core::slice::iter::Iter<mz_repr::relation::ColumnType>>, core::slice::iter::Iter<mz_pgrepr::format::Format>>, mz_pgwire::message::encode_row_description::{closure#0}>>>::from_iter
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/vec/spec_from_iter.rs:33:9
sqlsmith-mz_2-1  |   13: <alloc::vec::Vec<mz_pgwire::message::FieldDescription> as core::iter::traits::collect::FromIterator<mz_pgwire::message::FieldDescription>>::from_iter::<core::iter::adapters::map::Map<itertools::zip_eq_impl::ZipEq<core::iter::adapters::zip::Zip<core::slice::iter::Iter<mz_repr::relation::ColumnName>, core::slice::iter::Iter<mz_repr::relation::ColumnType>>, core::slice::iter::Iter<mz_pgrepr::format::Format>>, mz_pgwire::message::encode_row_description::{closure#0}>>
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/vec/mod.rs:2753:9
sqlsmith-mz_2-1  |   14: <core::iter::adapters::map::Map<itertools::zip_eq_impl::ZipEq<core::iter::adapters::zip::Zip<core::slice::iter::Iter<mz_repr::relation::ColumnName>, core::slice::iter::Iter<mz_repr::relation::ColumnType>>, core::slice::iter::Iter<mz_pgrepr::format::Format>>, mz_pgwire::message::encode_row_description::{closure#0}> as core::iter::traits::iterator::Iterator>::collect::<alloc::vec::Vec<mz_pgwire::message::FieldDescription>>
sqlsmith-mz_2-1  |              at ./rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/iter/traits/iterator.rs:1860:9
sqlsmith-mz_2-1  |   15: mz_pgwire::message::encode_row_description
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ee6065e219dd7cae-1/materialize/tests/src/pgwire/src/message.rs:518:10
sqlsmith-mz_2-1  |   16: <mz_pgwire::protocol::StateMachine<tokio::net::tcp::stream::TcpStream>>::one_query::{closure#0}
sqlsmith-mz_2-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ee6065e219dd7cae-1/materialize/tests/src/pgwire/src/protocol.rs:614:21
...
```

**Comment by mjibson** [comment]
That location in expr.rs is `VariadicFunc::TimezoneTime` https://github.com/MaterializeInc/materialize/blob/ffb347ed802489d5d20cf7c3f947afad8f5a49ec/src/expr/src/scalar/func.rs#L7334:

```
            VariadicFunc::TimezoneTime => parse_timezone(ds[0].unwrap_str()).map(|tz| {
                timezone_time(
                    tz,
                    ds[1].unwrap_time(),
                    &ds[1].unwrap_timestamptz().naive_utc(),
                )
                .into()
```

This function is only ever called with `HirScalarExpr::CallUnmaterializable(UnmaterializableFunc::CurrentTimestamp)`: https://github.com/MaterializeInc/materialize/blob/ffb347ed802489d5d20cf7c3f947afad8f5a49ec/src/sql/src/func.rs#L2579

I'm also a bit interested to see 60 seconds and wonder if that happens to do trigger anything.

**Comment by mjibson** [comment]
Oh I found it -_-. Wrong index there, and we weren't testing it because the optimizer subs it out if the first and third arguments are literals: https://github.com/MaterializeInc/materialize/blob/ffb347ed802489d5d20cf7c3f947afad8f5a49ec/src/expr/src/scalar/mod.rs#L1144

And we only test when those are literals, so we never tested the unoptimized implementation!

**Comment by mjibson** [comment]
test_smoketest_all_builtins does test all builtins, but because CurrentTimestamp was there, mir.eval failed.
