### ISSUE TITLE
 thread 'webhook_concurrent_actions' panicked at 'assertion failed: saw_atleast_one_success_after_close', src/environmentd/tests/server.rs:2191:5

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#20824]
### What version of Materialize are you using?

v0

### What is the issue?

https://buildkite.com/materialize/tests/builds/60417#018996a7-7780-4e8f-9a4e-d176372c443b

```


[2023-07-27T09:39:34Z] thread 'webhook_concurrent_actions' panicked at 'assertion failed: saw_atleast_one_success_after_close', src/environmentd/tests/server.rs:2191:5
--
  | [2023-07-27T09:39:34Z] stack backtrace:
  | [2023-07-27T09:39:34Z]    0: rust_begin_unwind
  | [2023-07-27T09:39:34Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
  | [2023-07-27T09:39:34Z]    1: core::panicking::panic_fmt
  | [2023-07-27T09:39:34Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
  | [2023-07-27T09:39:34Z]    2: core::panicking::panic
  | [2023-07-27T09:39:34Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:114:5
  | [2023-07-27T09:39:34Z]    3: server::webhook_concurrent_actions::test_impl
  | [2023-07-27T09:39:34Z]              at ./tests/server.rs:2191:5
  | [2023-07-27T09:39:34Z]    4: server::webhook_concurrent_actions
  | [2023-07-27T09:39:34Z]              at ./tests/server.rs:2067:1
  | [2023-07-27T09:39:34Z]    5: server::webhook_concurrent_actions::{closure#0}
  | [2023-07-27T09:39:34Z]              at ./tests/server.rs:2067:1
  | [2023-07-27T09:39:34Z]    6: <server::webhook_concurrent_actions::{closure#0} as core::ops::function::FnOnce<()>>::call_once
  | [2023-07-27T09:39:34Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
  | [2023-07-27T09:39:34Z]    7: core::ops::function::FnOnce::call_once
  | [2023-07-27T09:39:34Z]              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
  | [2023-07-27T09:39:34Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  | [2023-07-27T09:39:34Z]
  | [2023-07-27T09:39:34Z] error: test run failed
  | [2023-07-27T09:39:34Z] mzcompose: test case workflow-default failed:
  | [2023-07-27T09:39:34Z] Traceback (most recent call last):
  | [2023-07-27T09:39:34Z]   File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0302f9fe3f3ca045a-1/materialize/tests/misc/python/materialize/mzcompose/__init__.py", line 419, in test_case
  | [2023-07-27T09:39:34Z]     yield
  | [2023-07-27T09:39:34Z]   File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0302f9fe3f3ca045a-1/materialize/tests/misc/python/materialize/cli/mzcompose.py", line 589, in handle_composition
  | [2023-07-27T09:39:34Z]     composition.workflow(args.workflow, *args.unknown_subargs[1:])
  | [2023-07-27T09:39:34Z]   File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0302f9fe3f3ca045a-1/materialize/tests/misc/python/materialize/mzcompose/__init__.py", line 329, in workflow
  | [2023-07-27T09:39:34Z]     func(self, parser)
  | [2023-07-27T09:39:34Z]   File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0302f9fe3f3ca045a-1/materialize/tests/ci/test/cargo-test/mzcompose.py", line 134, in workflow_default
  | [2023-07-27T09:39:34Z]     spawn.runv(
  | [2023-07-27T09:39:34Z]   File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0302f9fe3f3ca045a-1/materialize/tests/misc/python/materialize/spawn.py", line 71, in runv
  | [2023-07-27T09:39:34Z]     return subprocess.run(
  | [2023-07-27T09:39:34Z]   File "/usr/lib/python3.10/subprocess.py", line 524, in run
  | [2023-07-27T09:39:34Z]     raise CalledProcessError(retcode, process.args,
  | [2023-07-27T09:39:34Z] subprocess.CalledProcessError: Command '['cargo', 'nextest', 'run', '--profile=ci']' returned non-zero exit status 100.
  | [2023-07-27T09:39:34Z] ==> Uploading report for suite 'mzcompose' to Buildkite Test Analytics
  | [2023-07-27T09:39:35Z] 202 {"id":"b525be87-0ebe-4d99-b6d8-a8e4d141858b","run_id":"c5432e2c-824c-4629-8b44-3fdb9e5d081c","queued":1,"skipped":0,"errors":[],"run_url":"https://buildkite.com/organizations/materialize/analytics/suites/mzcompose/runs/c5432e2c-824c-4629-8b44-3fdb9e5d081c"}
  | [2023-07-27T09:39:35Z] mzcompose: error: at least one test case failed

ci-regexp: saw_atleast_one_success_after_close
```

**Comment by danhhz** [comment]
@ParkMyCar heads up that this test just flaked in the release CI run, though with a different message https://buildkite.com/materialize/tests/builds/61091#0189c245-cf50-488e-a564-812dcaada28f

anecdotally, i also saw the same flake in https://buildkite.com/materialize/tests/builds/61074#0189c1f9-97b2-4568-be77-aba947af7f1d

**Comment by ParkMyCar** [comment]
Thanks for the ping @danhhz, sorry for the flake! I just put up #21026 which I think should resolve our issues 🤞

**Comment by ParkMyCar** [comment]
Looks like that is the same flake @bkirwi! I just merged the PR which should fix the flakiness
