### ISSUE TITLE
Trying to rename a webhook source causes a panic

### ISSUE THREAD

**Issue by bobbyiliev** [MaterializeInc/materialize#21311]
### What version of Materialize are you using?

v0.66.0 (647282c5d)

### What is the issue?

Trying to rename a webhook source causes a panic.

Steps to reproduce:

- Enable webhook sources:

```sql
ALTER SYSTEM SET enable_webhook_sources = true; 
```

- Create a cluster:

```sql
CREATE CLUSTER my_cluster  SIZE ='1';  
```

- Create a dummy webhook source:

```sql
CREATE SOURCE my_webhook_source IN CLUSTER my_cluster FROM WEBHOOK                                                                                        
   BODY FORMAT JSON;
```

- Try to rename it:

```sql
ALTER SOURCE my_webhook_source RENAME TO my_webhook_source2;   
```

Log output:

```
environmentd: 2023-08-21T21:04:21.535474Z  INFO advance_ready{otel.name="query"}: mz_adapter::catalog: create source materialize.public.my_webhook_source (u1)
thread 'coordinator' panicked at 'internal error: entered unreachable code: Internal error: only catalog items can be renamed', src/sql/src/ast/transform.rs:58:14
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: mz_sql::ast::transform::create_stmt_rename
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-064798e24f5559f99-1/materialize/tests/src/sql/src/ast/transform.rs:58:14
   3: <mz_adapter::catalog::CatalogItem>::rename_item_refs::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-064798e24f5559f99-1/materialize/tests/src/adapter/src/catalog.rs:2516:17
   4: <mz_adapter::catalog::CatalogItem>::rename_item_refs
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-064798e24f5559f99-1/materialize/tests/src/adapter/src/catalog.rs:2532:32
   5: <mz_adapter::catalog::Catalog>::transact_inner
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-064798e24f5559f99-1/materialize/tests/src/adapter/src/catalog.rs:6867:38
   6: <mz_adapter::catalog::Catalog>::transact::<<mz_adapter::coord::Coordinator>::catalog_transact_with<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#11}, ()>::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-064798e24f5559f99-1/materialize/tests/src/adapter/src/catalog.rs:5396:9
   7: <mz_adapter::catalog::Catalog>::transact::<<mz_adapter::coord::Coordinator>::catalog_transact_with<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0}::{closure#0}::{closure#11}, ()>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-064798e24f5559f99-1/materialize/tests/src/adapter/src/catalog.rs:5353:5
   8: <mz_adapter::coord::Coordinator>::catalog_transact_with::<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-064798e24f5559f99-1/materialize/tests/src/adapter/src/coord/ddl.rs:351:14
   9: <mz_adapter::coord::Coordinator>::catalog_transact_with::<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-064798e24f5559f99-1/materialize/tests/src/adapter/src/coord/ddl.rs:84:5
  10: <mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-064798e24f5559f99-1/materialize/tests/src/adapter/src/coord/ddl.rs:71:62
  11: <mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-064798e24f5559f99-1/materialize/tests/src/adapter/src/coord/ddl.rs:65:5
  12: <mz_adapter::coord::Coordinator>::sequence_alter_item_rename::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-064798e24f5559f99-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:3772:62
  13: <mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-064798e24f5559f99-1/materialize/tests/src/adapter/src/coord/sequencer.rs:336:83
  14: <mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-064798e24f5559f99-1/materialize/tests/src/adapter/src/coord/sequencer.rs:61:5
  15: <mz_adapter::coord::Coordinator>::handle_execute_inner::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-064798e24f5559f99-1/materialize/tests/src/adapter/src/coord/command_handler.rs:732:73
  16: <mz_adapter::coord::Coordinator>::handle_execute_inner::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-064798e24f5559f99-1/materialize/tests/src/adapter/src/coord/command_handler.rs:508:5
  17: <mz_adapter::coord::Coordinator>::handle_execute::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-064798e24f5559f99-1/materialize/tests/src/adapter/src/coord/command_handler.rs:505:54
  18: <mz_adapter::coord::Coordinator>::handle_execute::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-064798e24f5559f99-1/materialize/tests/src/adapter/src/coord/command_handler.rs:406:5
  19: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_execute::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  20: <mz_adapter::coord::Coordinator>::handle_command::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-064798e24f5559f99-1/materialize/tests/src/adapter/src/coord/command_handler.rs:122:22
  21: <mz_adapter::coord::Coordinator>::message_command::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-064798e24f5559f99-1/materialize/tests/src/adapter/src/coord/message_handler.rs:238:34
  22: <mz_adapter::coord::Coordinator>::message_command::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-064798e24f5559f99-1/materialize/tests/src/adapter/src/coord/message_handler.rs:235:5
  23: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-064798e24f5559f99-1/materialize/tests/src/adapter/src/coord/message_handler.rs:43:64
  24: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_message::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  25: <mz_adapter::coord::Coordinator>::serve::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-064798e24f5559f99-1/materialize/tests/src/adapter/src/coord.rs:1832:18
  26: <tokio::runtime::park::CachedParkThread>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/park.rs:283:63
  27: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/coop.rs:107:5
  28: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/coop.rs:73:5
  29: <tokio::runtime::park::CachedParkThread>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/park.rs:283:31
  30: <tokio::runtime::context::BlockingRegionGuard>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/context.rs:315:13
  31: <tokio::runtime::handle::Handle>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.27.0/src/runtime/handle.rs:264:9
  32: mz_adapter::coord::serve::{closure#0}::{closure#1}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-064798e24f5559f99-1/materialize/tests/src/adapter/src/coord.rs:2067:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
cluster-s2-replica-3: 2023-08-21T21:05:17.142234Z  WARN mz_persist_client::rpc: pubsub client error: Status { code: Unknown, message: "h2 protocol error: error reading a body from connection: stream closed because of a broken pipe", source: Some(hyper::Error(Body, Error { kind: Io(Custom { kind: BrokenPipe, error: "stream closed because of a broken pipe" }) })) }
cluster-u2-replica-4: 2023-08-21T21:05:17.145416Z  WARN mz_persist_client::rpc: pubsub client error: Status { code: Unknown, message: "h2 protocol error: error reading a body from connection: stream closed because of a broken pipe", source: Some(hyper::Error(Body, Error { kind: Io(Custom { kind: BrokenPipe, error: "stream closed because of a broken pipe" }) })) }
cluster-u1-replica-1: 2023-08-21T21:05:17.145729Z  WARN mz_persist_client::rpc: pubsub client error: Status { code: Unknown, message: "h2 protocol error: error reading a body from connection: stream closed because of a broken pipe", source: Some(hyper::Error(Body, Error { kind: Io(Custom { kind: BrokenPipe, error: "stream closed because of a broken pipe" }) })) }
```

**Comment by benesch** [comment]
cc @ParkMyCar
