### ISSUE TITLE
test: mzcompose fails to add user

### ISSUE THREAD

**Issue by jkosh44** [MaterializeInc/materialize#21537]
### What version of Materialize are you using?

v0.69.0-dev

### What is the issue?

When trying to run mzcompose locally I get an error that indicates a failure to add a new user:

```
~/materialize/test/testdrive $ ./mzcompose down -v ; ./mzcompose --dev run default indexes.td -- --default-timeout=10s ; ./mzcompose down -v ;
==> Collecting mzbuild images
materialize/ubuntu-base:mzbuild-7IGRVW2AOXKWHWMLVHLQ7VEH4ZVA3Z6E
materialize/materialized:mzbuild-XQ4GGHCJDPBAUDENLM6ZSNBHW3U7LUCH
materialize/testdrive:mzbuild-LQRIDRR4XY7FIQCGSD6EECKT3UXBX62Y
==> Delegating to Docker Compose
$ docker compose down -v --volumes --remove-orphans
[+] Running 4/0
 ⠿ Volume testdrive_mzdata   Removed                                                                                                                                                  0.0s
 ⠿ Volume testdrive_tmp      Removed                                                                                                                                                  0.0s
 ⠿ Volume testdrive_scratch  Removed                                                                                                                                                  0.0s
 ⠿ Volume testdrive_mydata   Removed                                                                                                                                                  0.0s
==> Collecting mzbuild images
materialize/ubuntu-base:mzbuild-7IGRVW2AOXKWHWMLVHLQ7VEH4ZVA3Z6E
materialize/materialized:mzbuild-DT7EL2LVASR67GK5U2NNSL7HA6UUGEL2
materialize/testdrive:mzbuild-ADCJHSCFEOCIRALUKSE5QLAPM5HCJUX3
==> Acquiring materialize/ubuntu-base:mzbuild-7IGRVW2AOXKWHWMLVHLQ7VEH4ZVA3Z6E
==> Acquiring materialize/materialized:mzbuild-DT7EL2LVASR67GK5U2NNSL7HA6UUGEL2
$ docker pull materialize/materialized:mzbuild-DT7EL2LVASR67GK5U2NNSL7HA6UUGEL2
Error response from daemon: manifest for materialize/materialized:mzbuild-DT7EL2LVASR67GK5U2NNSL7HA6UUGEL2 not found: manifest unknown: manifest unknown
==> Acquiring materialize/testdrive:mzbuild-ADCJHSCFEOCIRALUKSE5QLAPM5HCJUX3
$ docker pull materialize/testdrive:mzbuild-ADCJHSCFEOCIRALUKSE5QLAPM5HCJUX3
Error response from daemon: manifest for materialize/testdrive:mzbuild-ADCJHSCFEOCIRALUKSE5QLAPM5HCJUX3 not found: manifest unknown: manifest unknown
Common cargo build for: testdrive, clusterd, environmentd
$ env MZ_DEV_CI_BUILDER_ARCH=x86_64 bin/ci-builder run stable env 'RUSTFLAGS=-Clink-arg=-Wl,--compress-debug-sections=zlib -Csymbol-mangling-version=v0 -Clink-arg=-fuse-ld=lld -L/opt/x-tools/x86_64-unknown-linux-gnu/x86_64-unknown-linux-gnu/sysroot/lib' cargo build --target x86_64-unknown-linux-gnu --bin testdrive --bin clusterd --bin environmentd
useradd: UID 1000 is not unique
autouseradd: /usr/sbin/useradd failed
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/joe/materialize/misc/python/materialize/cli/mzcompose.py", line 699, in <module>
    main(sys.argv[1:])
  File "/home/joe/materialize/misc/python/materialize/cli/mzcompose.py", line 139, in main
    args.command.invoke(args)
  File "/home/joe/materialize/misc/python/materialize/cli/mzcompose.py", line 210, in invoke
    self.run(args)
  File "/home/joe/materialize/misc/python/materialize/cli/mzcompose.py", line 549, in run
    super().run(args)
  File "/home/joe/materialize/misc/python/materialize/cli/mzcompose.py", line 442, in run
    composition.dependencies.acquire()
  File "/home/joe/materialize/misc/python/materialize/mzbuild.py", line 833, in acquire
    self._prepare_batch(deps_to_build)
  File "/home/joe/materialize/misc/python/materialize/mzbuild.py", line 826, in _prepare_batch
    cast(PreImage, cls).prepare_batch(instances)
  File "/home/joe/materialize/misc/python/materialize/mzbuild.py", line 391, in prepare_batch
    spawn.runv(cargo_build, cwd=rd.root)
  File "/home/joe/materialize/misc/python/materialize/spawn.py", line 72, in runv
    return subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['env', 'MZ_DEV_CI_BUILDER_ARCH=x86_64', 'bin/ci-builder', 'run', 'stable', 'env', 'RUSTFLAGS=-Clink-arg=-Wl,--compress-debug-sections=zlib -Csymbol-mangling-version=v0 -Clink-arg=-fuse-ld=lld -L/opt/x-tools/x86_64-unknown-linux-gnu/x86_64-unknown-linux-gnu/sysroot/lib', 'cargo', 'build', '--target', 'x86_64-unknown-linux-gnu', '--bin', 'testdrive', '--bin', 'clusterd', '--bin', 'environmentd']' returned non-zero exit status 1.
==> Collecting mzbuild images
materialize/ubuntu-base:mzbuild-7IGRVW2AOXKWHWMLVHLQ7VEH4ZVA3Z6E
materialize/materialized:mzbuild-XQ4GGHCJDPBAUDENLM6ZSNBHW3U7LUCH
materialize/testdrive:mzbuild-LQRIDRR4XY7FIQCGSD6EECKT3UXBX62Y
==> Delegating to Docker Compose
$ docker compose down -v --volumes --remove-orphans
[+] Running 4/0
 ⠿ Volume testdrive_scratch  Removed                                                                                                                                                  0.0s
 ⠿ Volume testdrive_mydata   Removed                                                                                                                                                  0.0s
 ⠿ Volume testdrive_tmp      Removed                                                                                                                                                  0.0s
 ⠿ Volume testdrive_mzdata   Removed    
```

I believe that the error comes from the Dockerfile here: 
https://github.com/MaterializeInc/materialize/blob/cd4df3edcd5540f4d9a84d053c3de864847b08e8/ci/builder/Dockerfile#L139
I wasn't able to find another usage of `autouseradd`.

The error within `autouseradd` happens when running `useradd`: 
https://github.com/benesch/autouseradd/blob/a5a5dc87601ae4b12227f9bab00a93ee4df91806/autouseradd-suid.c#L129-L131

The UID gets populated here:
https://github.com/benesch/autouseradd/blob/a5a5dc87601ae4b12227f9bab00a93ee4df91806/autouseradd-suid.c#L117C1-L118

FWIW 1000 is the UID of my active OS user:
```
$ awk -F: '/\/home/ {printf "%s:%s\n",$1,$3}' /etc/passwd
syslog:104
cups-pk-helper:113
joe:1000
```

**Comment by nrainer-materialize** [comment]
@necaris: Could you please look into this? More and more people are affected...

**Comment by benesch** [comment]
From the Ubuntu bug @ggevay linked on Slack, the fix is to remove the `Ubuntu` user from the final Docker image by adding this command:

```
RUN userdel -r ubuntu
```

Details here: https://bugs.launchpad.net/cloud-images/+bug/2005129
