### ISSUE TITLE
Empty logs in cluster test

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#21597]
### What version of Materialize are you using?

main

### What is the issue?

```
mzcompose: test case test-invalid-compute-reuse failed: <class 'AssertionError'>: 
Traceback (most recent call last):
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-088802d58c405740b-1/materialize/coverage/misc/python/materialize/mzcompose/__init__.py", line 420, in test_case
    yield
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-088802d58c405740b-1/materialize/coverage/test/cluster/mzcompose.py", line 90, in workflow_default
    c.workflow(name)
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-088802d58c405740b-1/materialize/coverage/misc/python/materialize/mzcompose/__init__.py", line 336, in workflow
    func(self)
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-088802d58c405740b-1/materialize/coverage/test/cluster/mzcompose.py", line 205, in workflow_test_invalid_compute_reuse
    "halting process: new timely configuration does not match existing timely configuration"
AssertionError
```
Seen in coverage run https://buildkite.com/materialize/coverage/builds/218#018a653c-711c-406b-89da-74bf450cc7b8 , so this could be timing dependent.
Upon further investigation the services.log is entirely empty. I haven't investigated further since this issue is not reproducible and hard to debug with the logs being empty.

**Comment by def-** [comment]
Seen again in https://buildkite.com/materialize/coverage/builds/236#018ad8d2-4da7-4f15-b52a-66c29d6d8299

**Comment by nrainer-materialize** [comment]
I observed another occurrence in https://buildkite.com/materialize/coverage/builds/355.

**Comment by def-** [comment]
Also happens without coverage build, so it's just timing-dependent: https://buildkite.com/materialize/tests/builds/76452#018dd120-3f8a-4bc3-89e6-543915ad4283
