### ISSUE TITLE
data-ingest: thread 'timely:work-0' panicked at 'range end index 134 out of range for slice of length 133', src/storage/src/render/upsert/types.rs:254:34 

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#21605]
### What version of Materialize are you using?

b8ceb960cd

### What is the issue?

Happened in https://buildkite.com/materialize/nightlies/builds/3804#_ but seems unrelated to the PR:
```
thread 'timely:work-0' panicked at 'range end index 134 out of range for slice of length 133', src/storage/src/render/upsert/types.rs:254:34 
```
I'm not seeing the backtrace in the logs, which is strange.

**Comment by def-** [comment]
This might be related to https://github.com/MaterializeInc/materialize/issues/7105
