### ISSUE TITLE
`test_auth_intermediate_ca` is flaky

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#21608]
### Buildkite link

https://buildkite.com/materialize/tests/builds/63168#018a65d4-4b59-4802-ad50-ab50dc224650

### Relevant log output

```source
thread 'test_auth_intermediate_ca' panicked at 'called `Result::unwrap()` on an `Err` value: error communicating with the server: bytes remaining on stream
Caused by:
    bytes remaining on stream
Stack backtrace:
   0: <core::result::Result<auth::util::Server, anyhow::Error> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible, tokio_postgres::error::Error>>>::from_residual
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1961:27
   1: <auth::util::Listeners>::serve
             at ./tests/util.rs:302:28
   2: auth::util::start_server
             at ./tests/util.rs:481:5
   3: auth::test_auth_intermediate_ca::test_impl
             at ./tests/auth.rs:1559:18
   4: auth::test_auth_intermediate_ca
             at ./tests/auth.rs:1528:1
   5: auth::test_auth_intermediate_ca::{closure#0}
             at ./tests/auth.rs:1528:1
   6: <auth::test_auth_intermediate_ca::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
      test::__rust_begin_short_backtrace
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/test/src/lib.rs:626:18
   8: test::run_test_in_process::{{closure}}
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/test/src/lib.rs:649:60
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
      std::panicking::try
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
      std::panic::catch_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
      test::run_test_in_process
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/test/src/lib.rs:649:27
      test::run_test::{{closure}}
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/test/src/lib.rs:572:43
   9: test::run_test::{{closure}}
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/test/src/lib.rs:600:41
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:135:18
  10: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/thread/mod.rs:529:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
      std::panicking::try
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
      std::panic::catch_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/thread/mod.rs:528:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
  11: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/alloc/src/boxed.rs:1993:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/alloc/src/boxed.rs:1993:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys/unix/thread.rs:108:17
  12: <unknown>
  13: __clone', src/environmentd/tests/auth.rs:1559:45
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
   3: <core::result::Result<auth::util::Server, anyhow::Error>>::unwrap
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1076:23
   4: auth::test_auth_intermediate_ca::test_impl
             at ./tests/auth.rs:1559:18
   5: auth::test_auth_intermediate_ca
             at ./tests/auth.rs:1528:1
   6: auth::test_auth_intermediate_ca::{closure#0}
             at ./tests/auth.rs:1528:1
   7: <auth::test_auth_intermediate_ca::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Additional thoughts

It passed on a retry.

cc @jkosh44

**Comment by jkosh44** [comment]
Is this common? I'm unable to reproduce it. The error is happening when trying to connect to a PostgreSQL server (CRDB in this case). Specifically here:

https://github.com/MaterializeInc/materialize/blob/66205d028625577c97093c96fce05a650f63fe9b/src/environmentd/tests/util.rs#L302

It's likely unrelated to this specific test and was probably a test env issue.

**Comment by ggevay** [comment]
Happened only once.

> It's likely unrelated to this specific test and was probably a test env issue.

Ok, I didn't realize it was just a connection issue from the error msg, sorry. Then we can close this.
