### ISSUE TITLE
storage: restarting mz 

### ISSUE THREAD

**Issue by guswynn** [MaterializeInc/materialize#21634]
### What version of Materialize are you using?

main

### What is the issue?

As reported by @jkosh44, running:
```
bin/mzcompose --find platform-checks down ; bin/mzcompose --find platform-checks --dev run default --scenario=RestartEntireMz --check=Owners --execution-mode=parallel; bin/mzcompose --find platform-checks logs > out.txt ; bin/mzcompose --find platform-checks down ;
``` 

periodically causes this panic:
```
platform-checks-materialized-1  | thread 'producer polling thread' panicked at 'attempt to subtract with overflow', src/storage/src/sink/kafka.rs:213:9
platform-checks-materialized-1  | stack backtrace:
platform-checks-materialized-1  |    0: rust_begin_unwind
platform-checks-materialized-1  |              at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
platform-checks-materialized-1  |    1: core::panicking::panic_fmt
platform-checks-materialized-1  |              at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
platform-checks-materialized-1  |    2: core::panicking::panic
platform-checks-materialized-1  |              at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:117:5
platform-checks-materialized-1  |    3: <mz_storage::sink::kafka::KafkaSinkSendRetryManager>::record_success
platform-checks-materialized-1  |              at ./home/joe/materialize/src/storage/src/sink/kafka.rs:213:9
platform-checks-materialized-1  |    4: <mz_storage::sink::kafka::SinkProducerContext as rdkafka::producer::ProducerContext>::delivery
platform-checks-materialized-1  |              at ./home/joe/materialize/src/storage/src/sink/kafka.rs:244:22
platform-checks-materialized-1  |    5: <mz_kafka_util::client::BrokerRewritingClientContext<mz_storage::sink::kafka::SinkProducerContext> as rdkafka::producer::ProducerContext>::delivery
platform-checks-materialized-1  |              at ./home/joe/materialize/src/kafka-util/src/client.rs:219:9
platform-checks-materialized-1  |    6: rdkafka::producer::base_producer::delivery_cb::<mz_kafka_util::client::BrokerRewritingClientContext<mz_storage::sink::kafka::SinkProducerContext>>
platform-checks-materialized-1  |              at ./cargo/git/checkouts/rust-rdkafka-545566655b063b24/8ea07c4/src/producer/base_producer.rs:83:5
platform-checks-materialized-1  |    7: rd_kafka_poll_cb
platform-checks-materialized-1  |              at ./cargo/git/checkouts/rust-rdkafka-545566655b063b24/8ea07c4/rdkafka-sys/librdkafka/src/rdkafka.c:3837:33
platform-checks-materialized-1  |    8: rd_kafka_op_handle
platform-checks-materialized-1  |              at ./cargo/git/checkouts/rust-rdkafka-545566655b063b24/8ea07c4/rdkafka-sys/librdkafka/src/rdkafka_op.c:872:23
platform-checks-materialized-1  |    9: rd_kafka_q_serve
platform-checks-materialized-1  |              at ./cargo/git/checkouts/rust-rdkafka-545566655b063b24/8ea07c4/rdkafka-sys/librdkafka/src/rdkafka_queue.c:513:23
platform-checks-materialized-1  |   10: rd_kafka_poll
platform-checks-materialized-1  |              at ./cargo/git/checkouts/rust-rdkafka-545566655b063b24/8ea07c4/rdkafka-sys/librdkafka/src/rdkafka.c:3977:13
platform-checks-materialized-1  |   11: <rdkafka::producer::base_producer::BaseProducer<mz_kafka_util::client::BrokerRewritingClientContext<mz_storage::sink::kafka::SinkProducerContext>>>::poll::<core::time::Duration>
platform-checks-materialized-1  |              at ./cargo/git/checkouts/rust-rdkafka-545566655b063b24/8ea07c4/src/producer/base_producer.rs:297:18
platform-checks-materialized-1  |   12: <rdkafka::producer::base_producer::ThreadedProducer<mz_kafka_util::client::BrokerRewritingClientContext<mz_storage::sink::kafka::SinkProducerContext>> as rdkafka::config::FromClientConfigAndContext<mz_kafka_util::client::BrokerRewritingClientContext<mz_storage::sink::kafka::SinkProducerContext>>>::from_config_and_context::{closure#0}
platform-checks-materialized-1  |              at ./cargo/git/checkouts/rust-rdkafka-545566655b063b24/8ea07c4/src/producer/base_producer.rs:530:33
```

Additional logging was added by joe:
```
platform-checks-materialized-1  | cluster-u6-replica-u6: 2023-08-28T21:03:34.243038Z  INFO mz_storage::sink::kafka: record send, incrementing 0
platform-checks-materialized-1  | cluster-u6-replica-u6: 2023-08-28T21:03:34.247802Z  INFO mz_storage::sink::kafka: record success, decrementing 1
platform-checks-materialized-1  | cluster-u6-replica-u6: 2023-08-28T21:03:34.260607Z  INFO mz_storage::sink::kafka: kafka-u22: downgrading write frontier to: 1693256613877
platform-checks-materialized-1  | environmentd: 2023-08-28T21:03:34.759452Z  INFO mz_adapter::catalog: create connection materialize.public.owner_kafka_conn9 (u71)
platform-checks-materialized-1  | cluster-u6-replica-u6: 2023-08-28T21:03:35.640697Z  INFO mz_storage::sink::kafka: kafka-u22: sending progress for gate ts: 1693256614919
platform-checks-materialized-1  | cluster-u6-replica-u6: 2023-08-28T21:03:35.653091Z  INFO mz_storage::sink::kafka: record success, decrementing 0
platform-checks-materialized-1  | thread 'producer polling thread' panicked at 'attempt to subtract with overflow', src/storage/src/sink/kafka.rs:220:9
```

for posterity, here is the initial thread where this was discussed: https://materializeinc.slack.com/archives/C01CFKM1QRF/p1693253710612369

**Comment by benesch** [comment]
Going to optimistically close as I strongly suspect @petrosagg’s recent sink refactoring fixed this.
