### ISSUE TITLE
`test-concurrent-connections` is flaky

### ISSUE THREAD

**Issue by ggevay** [MaterializeInc/materialize#22004]
### Buildkite link

https://buildkite.com/materialize/tests/builds/64589#018ad696-3abf-47c3-ba67-68a6e5d263f6

### Relevant log output

```source
> SELECT 1
> SELECT 1
min: 0.14s, p50: 4.54s, p99: 9.53s, max: 9.59s
mzcompose: test case test-concurrent-connections failed: <class 'AssertionError'>: p50 is 4.54s, should be less than 1.0s
Traceback (most recent call last):
  File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0265ab89f3d49ed58-1/materialize/tests/misc/python/materialize/mzcompose/composition.py", line 437, in test_case
    yield
  File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0265ab89f3d49ed58-1/materialize/tests/test/cluster/mzcompose.py", line 104, in workflow_default
    c.workflow(name)
  File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0265ab89f3d49ed58-1/materialize/tests/misc/python/materialize/mzcompose/composition.py", line 352, in workflow
    func(self)
  File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0265ab89f3d49ed58-1/materialize/tests/test/cluster/mzcompose.py", line 2451, in workflow_test_concurrent_connections
    assert p[49] < 1.0, f"p50 is {p[49]:.2f}s, should be less than 1.0s"
           ^^^^^^^^^^^
AssertionError: p50 is 4.54s, should be less than 1.0s
```

**Comment by ParkMyCar** [comment]
Argh, @def- looks like this flaked again
