### ISSUE TITLE
Materialize View wrongly increases the count

### ISSUE THREAD

**Issue by aneeshmonn** [MaterializeInc/materialize#2203]
I have two tables subjects, students and a mapping table stud_subs.

A MV is created on stud subjects to track the number of subjects a student has.

On updating the existing record, instead of retaining the subject count, MV increases the count to two.

Steps to Reproduce
**Postgres DB Setup**
```
Create Tables
CREATE TABLE student2(id serial PRIMARY KEY,name TEXT);
CREATE TABLE subjects2(id serial PRIMARY KEY,name TEXT);
CREATE TABLE stud_subs2(id serial PRIMARY KEY,stud_id INTEGER REFERENCES subjects2(id),sub_id INTEGER REFERENCES student2(id));
CREATE VIEW stud_sub_count2 AS select a.id as stud_id,a.name, count(distinct b.sub_id) AS sub_count FROM student2 a INNER JOIN stud_subs2 b ON a.id = b.stud_id GROUP BY a.id,a.name;
```
**Insert Base Data**
```
INSERT INTO student2(name) values('Ram'),('Kiran');
INSERT INTO subjects2(name) values('English'),('Maths');
INSERT INTO stud_subs2(stud_id,sub_id) values(1,1),(1,2),(2,1);
```

**Kafka configured to read from Postgres**
```
confluent local start
curl -H 'Content-Type: application/json' localhost:8083/connectors --data '{
 "name": "pg-connector-collegedb",
 "config": {
   "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
   "database.hostname": "52.66.196.119",
   "database.port": "5432",
   "database.user": "admin",
   "database.password": "admin@123",
   "database.dbname" : "collegedb",
   "database.server.name": "dbserver1",
   "plugin.name": "pgoutput",
   "slot.name" : "test_slot",
   "database.history.kafka.bootstrap.servers": "localhost:9092",
   "database.history.kafka.topic": "collegedb_properties"
 }
}'
```

**Start Streaming**
```
sh kafka-avro-console-consumer --from-beginning --bootstrap-server localhost:9092 --topic dbserver1.public.student2
sh kafka-avro-console-consumer --from-beginning --bootstrap-server localhost:9092 --topic dbserver1.public.subjects2
sh kafka-avro-console-consumer --from-beginning --bootstrap-server localhost:9092 --topic dbserver1.public.stud_subs2
```

**Materialize Configuration**
```
CREATE SOURCE source_student2
FROM KAFKA BROKER 'localhost:9092' TOPIC 'dbserver1.public.student2'
FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081'  ENVELOPE DEBEZIUM;
 
CREATE SOURCE source_subjects2
FROM KAFKA BROKER 'localhost:9092' TOPIC 'dbserver1.public.subjects2'
FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081'  ENVELOPE DEBEZIUM;
 
CREATE SOURCE source_stud_subs2
FROM KAFKA BROKER 'localhost:9092' TOPIC 'dbserver1.public.stud_subs2'
FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY 'http://localhost:8081'  ENVELOPE DEBEZIUM;
 
-- CREATE VIEW IN MATERIALIZE
CREATE MATERIALIZED VIEW stud_sub_count2 AS
select a.id as stud_id,a.name, count(distinct b.sub_id) FROM source_student2 a INNER JOIN source_stud_subs2 b ON a.id = b.stud_id GROUP BY a.id,a.name;
```

**Running tests #1 --All looks Good**
```
--Select count from Postgres
collegedb=# select * from stud_sub_count2;
stud_id | name  | sub_count
---------+-------+-----------
      1 | Ram   |         2
      2 | Kiran |         1
(2 rows)
--View Data from Materialize
materialize=> select * from stud_sub_count2;
stud_id | name  | count
---------+-------+-------
      1 | Ram   |     2
      2 | Kiran |     1
(2 rows)
```

**Running tests #2**
```
--Update a record: No subject count change for Kiran, just a subject change
collegedb=# select * from stud_subs2;
id | stud_id | sub_id
----+---------+--------
 1 |       1 |      1
 2 |       1 |      2
 3 |       2 |      1
(3 rows)
 
collegedb=# update stud_subs2 set sub_id = 2 where id = 3;
UPDATE 1
collegedb=# select * from stud_sub_count2;
stud_id | name  | sub_count
---------+-------+-----------
      1 | Ram   |         2
      2 | Kiran |         1
(2 rows)

--View Data from Materialize[Kiran’s subject count got increased to 2 instead of 1]
materialize=> select * from stud_sub_count2;
stud_id | name  | count
---------+-------+-------
      1 | Ram   |     2
      2 | Kiran |     2--Count is wrong, it should be 1
(2 rows)
```
[Materialize Bug on Updating a data - Google Docs.pdf](https://github.com/MaterializeInc/materialize/files/4286653/Materialize.Bug.on.Updating.a.data.-.Google.Docs.pdf)

**Comment by umanwizard** [comment]
Confirmed that I can reproduce this locally on latest materialized master.

**Comment by umanwizard** [comment]
Debezium is not creating a `"before"` row corresponding to the update, as expected by materialize:

```
~ ❯❯❯ kafka-avro-console-consumer --from-beginning --bootstrap-server localhost:9092 --topic dbserver1.public.stud_subs2
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /usr/bin/../logs/schema-registry.log (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
	at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:207)
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:842)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
	at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:648)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:514)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at org.slf4j.impl.Log4jLoggerFactory.<init>(Log4jLoggerFactory.java:66)
	at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:72)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:45)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at com.typesafe.scalalogging.Logger$.apply(Logger.scala:48)
	at kafka.utils.Log4jControllerRegistration$.<init>(Logging.scala:25)
	at kafka.utils.Log4jControllerRegistration$.<clinit>(Logging.scala)
	at kafka.utils.Logging.$init$(Logging.scala:47)
	at kafka.tools.ConsoleConsumer$.<init>(ConsoleConsumer.scala:45)
	at kafka.tools.ConsoleConsumer$.<clinit>(ConsoleConsumer.scala)
	at kafka.tools.ConsoleConsumer.main(ConsoleConsumer.scala)
{"before":null,"after":{"dbserver1.public.stud_subs2.Value":{"id":1,"stud_id":{"int":1},"sub_id":{"int":1}}},"source":{"version":"1.0.0.Final","connector":"postgresql","name":"dbserver1","ts_ms":1583332764465,"snapshot":{"string":"true"},"db":"brennan","schema":"public","table":"stud_subs2","txId":{"long":2716},"lsn":{"long":35574544},"xmin":null},"op":"r","ts_ms":{"long":1583332764466}}
{"before":null,"after":{"dbserver1.public.stud_subs2.Value":{"id":2,"stud_id":{"int":1},"sub_id":{"int":2}}},"source":{"version":"1.0.0.Final","connector":"postgresql","name":"dbserver1","ts_ms":1583332764468,"snapshot":{"string":"true"},"db":"brennan","schema":"public","table":"stud_subs2","txId":{"long":2716},"lsn":{"long":35574544},"xmin":null},"op":"r","ts_ms":{"long":1583332764468}}
{"before":null,"after":{"dbserver1.public.stud_subs2.Value":{"id":3,"stud_id":{"int":2},"sub_id":{"int":1}}},"source":{"version":"1.0.0.Final","connector":"postgresql","name":"dbserver1","ts_ms":1583332764471,"snapshot":{"string":"true"},"db":"brennan","schema":"public","table":"stud_subs2","txId":{"long":2716},"lsn":{"long":35574544},"xmin":null},"op":"r","ts_ms":{"long":1583332764471}}
{"before":null,"after":{"dbserver1.public.stud_subs2.Value":{"id":3,"stud_id":{"int":2},"sub_id":{"int":2}}},"source":{"version":"1.0.0.Final","connector":"postgresql","name":"dbserver1","ts_ms":1583332858399,"snapshot":{"string":"false"},"db":"brennan","schema":"public","table":"stud_subs2","txId":{"long":2718},"lsn":{"long":35607928},"xmin":null},"op":"u","ts_ms":{"long":1583332858426}}
```

**Comment by umanwizard** [comment]
@aneeshmonn Can you try setting the replication mode to "full" for your tables in Postgres, and try again?

`ALTER TABLE stud_subs2 SET REPLICA IDENTITY FULL`

This will cause Postgres to emit the full before/after row data as required by Materialize.

**Comment by aneeshmonn** [comment]
Thanks @umanwizard for the quick response.

Will test and come back

**Comment by aneeshmonn** [comment]
@umanwizard 

Was reading about Replica Identity
https://www.postgresql.org/docs/10/logical-replication-publication.html

As suggested in the Materialize wiki, we had created primary key and was working for normal aggregations.

Looks setting replica full is performance inefficient as quoted in Postgres Doc. Please confirm in which scenarios we should set replica identity full to the tables, doesn't look like setting this for all the tables is a good idea.

**Comment by quodlibetor** [comment]
@aneeshmonn have you tried `ALTER SYSTEM SET wal_level TO logical;`

**Comment by benesch** [comment]
> @umanwizard
> 
> Was reading about Replica Identity
> https://www.postgresql.org/docs/10/logical-replication-publication.html
> 
> As suggested in the Materialize wiki, we had created primary key and was working for normal aggregations.
> 
> Looks setting replica full is performance inefficient as quoted in Postgres Doc. Please confirm in which scenarios we should set replica identity full to the tables, doesn't look like setting this for all the tables is a good idea.

You need to set it for all tables that you wish to connect to Materialize. There is a performance cost, but it’s a performance cost that would need to be paid by Materialize if it were not paid by PostgreSQL.  (Perhaps making Materialize pay the cost instead would be desirable someday, but it’s not an option we currently offer.)

**Comment by frankmcsherry** [comment]
Is it possible that the setting is only required for tables that will experience updates? I'm very not-clear on the implications, but it might be that for large append-only tables it isn't necessary (but, things break badly if that turns out not to be true, if you update or delete or do whatever it is that causes Debezium to not find the right record to retract).

**Comment by benesch** [comment]
> Is it possible that the setting is only required for tables that will experience updates? I'm very not-clear on the implications, but it might be that for large append-only tables it isn't necessary (but, things break badly if that turns out not to be true, if you update or delete or do whatever it is that causes Debezium to not find the right record to retract).

Yes, that's true, but I'm not comfortable with that being our advice, because things go so badly if you do decide to update that table. It would be a different story if we had guardrails to detect when you did an update to a table you'd claimed was append-only, and could properly warn you about such a thing.

**Comment by frankmcsherry** [comment]
That's fair, but I do think we can (and should) present the trade-off. It seems analogous to telling people about the Debezium envelope format, even if that means that they might accidentally delete something they never inserted (where our advice isn't: "only ever use Debezium").

**Comment by benesch** [comment]
But append-only file sources actually work, whereas I'm pretty sure using Debezium with PostgreSQL in non-FULL REPLICA IDENTITY mode means that you get a bunch of negations of `{pkey, NULL, NULL, NULL, NULL, NULL}` into your stream, which are very very wrong.

**Comment by umanwizard** [comment]
@benesch no, it just doesn't send any retractions at all (i.e., `before` is always just `null`)

**Comment by benesch** [comment]
Are you running with REPLICA IDENTITY NOTHING? Or DEFAULT?

**Comment by umanwizard** [comment]
Whatever the default is. Not sure how I'd check.

**Comment by aneeshmonn** [comment]
@umanwizard view updates as expected after the suggested setting

`ALTER TABLE stud_subs2 SET REPLICA IDENTITY FULL`

@benesch 
Initially it was default and not Nothing

**Comment by aneeshmonn** [comment]
Thanks for the help.
