### ISSUE TITLE
thread 'coordinator' panicked at 'assertion failed: PartialOrder::less_than(&collection.implied_capability,\n        &collection.write_frontier) ||\n    *collection.write_frontier == [T::minimum()]'

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#22055]
### What version of Materialize are you using?

a165cf70c9ed

### What is the issue?

Seen on main in https://buildkite.com/materialize/tests/builds/64756#018ade4b-fe8c-43ae-8b87-edc978416301:
```
platform-checks-materialized-1        | thread 'coordinator' panicked at 'assertion failed: PartialOrder::less_than(&collection.implied_capability,\n        &collection.write_frontier) ||\n    *collection.write_frontier == [T::minimum()]', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0fb1bc0192e2b5618-1/materialize/tests/src/storage-controller/src/lib.rs:2871:13
platform-checks-materialized-1        | stack backtrace:
platform-checks-materialized-1        |    0: rust_begin_unwind
platform-checks-materialized-1        |              at ./rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
platform-checks-materialized-1        |    1: core::panicking::panic_fmt
platform-checks-materialized-1        |              at ./rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
platform-checks-materialized-1        |    2: core::panicking::panic
platform-checks-materialized-1        |              at ./rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:117:5
platform-checks-materialized-1        |    3: <mz_storage_controller::Controller<mz_repr::timestamp::Timestamp>>::install_dependency_read_holds::<core::iter::adapters::cloned::Cloned<alloc::collections::btree::map::Keys<mz_repr::global_id::GlobalId, mz_storage_types::sources::SourceExport>>>
platform-checks-materialized-1        |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0fb1bc0192e2b5618-1/materialize/tests/src/storage-controller/src/lib.rs:2871:13
platform-checks-materialized-1        |    4: <mz_storage_controller::Controller<mz_repr::timestamp::Timestamp> as mz_storage_client::controller::StorageController>::create_collections::{closure#0}::{closure#0}
platform-checks-materialized-1        |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0fb1bc0192e2b5618-1/materialize/tests/src/storage-controller/src/lib.rs:724:21
platform-checks-materialized-1        |    5: <mz_storage_controller::Controller<mz_repr::timestamp::Timestamp> as mz_storage_client::controller::StorageController>::create_collections::{closure#0}
platform-checks-materialized-1        |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0fb1bc0192e2b5618-1/materialize/tests/src/storage-controller/src/lib.rs:465:5
platform-checks-materialized-1        |    6: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(), mz_storage_types::controller::StorageError>>>> as core::future::future::Future>::poll
platform-checks-materialized-1        |              at ./rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/future/future.rs:125:9
platform-checks-materialized-1        |    7: <mz_adapter::coord::Coordinator>::bootstrap::{closure#0}::{closure#0}
platform-checks-materialized-1        |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0fb1bc0192e2b5618-1/materialize/tests/src/adapter/src/coord.rs:1371:30
platform-checks-materialized-1        |    8: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::bootstrap::{closure#0}::{closure#0}> as core::future::future::Future>::poll
platform-checks-materialized-1        |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
platform-checks-materialized-1        |    9: <mz_adapter::coord::Coordinator>::bootstrap::{closure#0}
platform-checks-materialized-1        |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0fb1bc0192e2b5618-1/materialize/tests/src/adapter/src/coord.rs:1050:5
platform-checks-materialized-1        |   10: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::bootstrap::{closure#0}> as core::future::future::Future>::poll
platform-checks-materialized-1        |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
platform-checks-materialized-1        |   11: mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#1}
platform-checks-materialized-1        |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0fb1bc0192e2b5618-1/materialize/tests/src/adapter/src/coord.rs:2196:22
platform-checks-materialized-1        |   12: <tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#1}> as core::future::future::Future>::poll
platform-checks-materialized-1        |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
platform-checks-materialized-1        |   13: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#1}>>::{closure#0}
platform-checks-materialized-1        |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
platform-checks-materialized-1        |   14: tokio::runtime::coop::with_budget::<core::task::poll::Poll<core::result::Result<(), mz_adapter::error::AdapterError>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#1}>>::{closure#0}>
platform-checks-materialized-1        |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
platform-checks-materialized-1        |   15: tokio::runtime::coop::budget::<core::task::poll::Poll<core::result::Result<(), mz_adapter::error::AdapterError>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#1}>>::{closure#0}>
platform-checks-materialized-1        |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
platform-checks-materialized-1        |   16: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#1}>>
platform-checks-materialized-1        |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
platform-checks-materialized-1        |   17: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#1}>>
platform-checks-materialized-1        |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
platform-checks-materialized-1        |   18: <tokio::runtime::handle::Handle>::block_on::<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#1}>::{closure#0}
platform-checks-materialized-1        |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:310:13
platform-checks-materialized-1        |   19: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::handle::Handle>::block_on<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#1}>::{closure#0}, core::result::Result<(), mz_adapter::error::AdapterError>>
platform-checks-materialized-1        |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
platform-checks-materialized-1        |   20: <tokio::runtime::handle::Handle>::block_on::<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#1}>
platform-checks-materialized-1        |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:309:9
platform-checks-materialized-1        |   21: mz_adapter::coord::serve::{closure#0}::{closure#1}
platform-checks-materialized-1        |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0fb1bc0192e2b5618-1/materialize/tests/src/adapter/src/coord.rs:2192:29
platform-checks-materialized-1        | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
I have triggered a rerun of "[Checks + restart of environmentd & storage clusterd](https://buildkite.com/materialize/tests/builds/64756#_)" to see if this is reproducible or a flake.

**Comment by def-** [comment]
It's flaky, but happened twice.

**Comment by def-** [comment]
The assertion comes from c75faea69ed

**Comment by philip-stoev** [comment]
I think this qualifies as a release blocker .

**Comment by def-** [comment]
I just checked and both times this happened it was when running the sanity check [I recently introduced](https://github.com/MaterializeInc/materialize/pull/20505), which restarts Mz at the end of a test. So this might not have been caused by a product change.

**Comment by moulimukherjee** [comment]
This is fixed via https://github.com/MaterializeInc/materialize/issues/22725
