### ISSUE TITLE
storage: soft assert when truncating source/sink status history

### ISSUE THREAD

**Issue by guswynn** [MaterializeInc/materialize#22207]
### What version of Materialize are you using?

main

### What is the issue?

https://github.com/MaterializeInc/materialize/blob/main/src/storage-controller/src/lib.rs#L2447-L2452 
Is not guaranteed. In production we won't hit this assert, and we will end up cleaning up the data over time, but this btreemap should be changed to a sorted vec

### Occurrences in CI
* https://buildkite.com/materialize/tests/builds/65187#018afc65-f5de-4c86-b464-cf8a2e37140f
* "Kafka smoke test against previous Kafka versions" in Nightly build: https://buildkite.com/materialize/nightlies/builds/4636#018b0232-35e4-4d8e-ba1f-47a3b7af890a

ci-regexp: thread 'coordinator' panicked at 'expected only one status at each time, but got multiple at TimestampTz

**Comment by nrainer-materialize** [comment]
Awesome, thank you for addressing this!

It also occured on the last Nightly build in [Kafka smoke test against previous Kafka versions](https://buildkite.com/materialize/nightlies/builds/4636#018b0232-35e4-4d8e-ba1f-47a3b7af890a).

**Comment by def-** [comment]
I'll just add the panic here, makes it easier to search for it:
```
thread 'coordinator' panicked at 'expected only one status at each time, but got multiple at TimestampTz(CheckedTimestamp { t: 2023-10-06T10:39:51.654Z })', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ff2920184c079cf1-1/materialize/tests/src/storage-controller/src/lib.rs:2448:13
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: <mz_storage_controller::Controller<mz_repr::timestamp::Timestamp>>::partially_truncate_status_history::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ff2920184c079cf1-1/materialize/tests/src/storage-controller/src/lib.rs:2448:13
   3: <mz_storage_controller::Controller<mz_repr::timestamp::Timestamp> as mz_storage_client::controller::StorageController>::create_collections::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ff2920184c079cf1-1/materialize/tests/src/storage-controller/src/lib.rs:827:30
   4: <mz_storage_controller::Controller<mz_repr::timestamp::Timestamp> as mz_storage_client::controller::StorageController>::create_collections::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ff2920184c079cf1-1/materialize/tests/src/storage-controller/src/lib.rs:465:5
   5: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(), mz_storage_types::controller::StorageError>>>> as core::future::future::Future>::poll
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/future/future.rs:125:9
   6: <mz_adapter::coord::Coordinator>::bootstrap::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ff2920184c079cf1-1/materialize/tests/src/adapter/src/coord.rs:1350:14
   7: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::bootstrap::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
   8: <mz_adapter::coord::Coordinator>::bootstrap::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ff2920184c079cf1-1/materialize/tests/src/adapter/src/coord.rs:1065:5
   9: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::bootstrap::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  10: mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ff2920184c079cf1-1/materialize/tests/src/adapter/src/coord.rs:2216:22
  11: <tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  12: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#0}>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  13: tokio::runtime::coop::with_budget::<core::task::poll::Poll<core::result::Result<(), mz_adapter::error::AdapterError>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#0}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  14: tokio::runtime::coop::budget::<core::task::poll::Poll<core::result::Result<(), mz_adapter::error::AdapterError>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#0}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  15: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#0}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  16: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#0}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  17: <tokio::runtime::handle::Handle>::block_on::<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#0}>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:310:13
  18: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::handle::Handle>::block_on<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#0}>::{closure#0}, core::result::Result<(), mz_adapter::error::AdapterError>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  19: <tokio::runtime::handle::Handle>::block_on::<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:309:9
  20: mz_adapter::coord::serve::{closure#0}::{closure#1}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0ff2920184c079cf1-1/materialize/tests/src/adapter/src/coord.rs:2212:29
```

**Comment by nrainer-materialize** [comment]
Marked as release-blocker: https://materializeinc.slack.com/archives/CTESPM7FU/p1696591804752709?thread_ts=1696591686.227539&cid=CTESPM7FU
