### ISSUE TITLE
coverage: Flaky failure in test_statement_logging_selects

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#22224]
### What version of Materialize are you using?

main

### What is the issue?

```
thread 'test_statement_logging_selects' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `4`', src/environmentd/tests/server.rs:411:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed::<usize, usize>
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:228:5
   4: server::test_statement_logging_selects::test_impl
             at ./tests/server.rs:411:5
   5: server::test_statement_logging_selects
             at ./tests/server.rs:345:1
   6: server::test_statement_logging_selects::{closure#0}
             at ./tests/server.rs:345:1
   7: <server::test_statement_logging_selects::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Seen in https://buildkite.com/materialize/coverage/builds/259#_, happened with coverage, but probably just timing-dependant. The test comes from https://github.com/MaterializeInc/materialize/pull/20862

**Comment by nrainer-materialize** [comment]
Possibly related: https://github.com/MaterializeInc/materialize/issues/21598
