### ISSUE TITLE
regression: panicked at 'no entry found for key', src/transform/src/predicate_pushdown.rs:1001:70

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#22257]
### What version of Materialize are you using?

46d73a76c90

### What is the issue?

```
thread 'tokio:work-67' panicked at 'no entry found for key', src/transform/src/predicate_pushdown.rs:1001:70
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_display
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:150:5
   3: core::panicking::panic_str
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:134:5
   4: core::option::expect_failed
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/option.rs:1932:5
   5: <core::option::Option<&(mz_expr::scalar::MirScalarExpr, usize)>>::expect
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/option.rs:898:21
   6: <alloc::collections::btree::map::BTreeMap<usize, (mz_expr::scalar::MirScalarExpr, usize)> as core::ops::index::Index<&usize>>::index
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/alloc/src/collections/btree/map.rs:2372:23
   7: <mz_transform::predicate_pushdown::PredicatePushdown>::inline_if_not_too_big::{closure#2}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/transform/src/predicate_pushdown.rs:1001:70
   8: <mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr>>::visit_mut_post::<<mz_transform::predicate_pushdown::PredicatePushdown>::inline_if_not_too_big::{closure#2}>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/expr/src/visit.rs:523:13
   9: <mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr> as mz_ore::stack::CheckedRecursion>::checked_recur::<<mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr>>::visit_mut_post<<mz_transform::predicate_pushdown::PredicatePushdown>::inline_if_not_too_big::{closure#2}>::{closure#0}, (), mz_ore::stack::RecursionLimitError>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/ore/src/stack.rs:191:33
  10: stacker::maybe_grow::<core::result::Result<(), mz_ore::stack::RecursionLimitError>, <mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr> as mz_ore::stack::CheckedRecursion>::checked_recur<<mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr>>::visit_mut_post<<mz_transform::predicate_pushdown::PredicatePushdown>::inline_if_not_too_big::{closure#2}>::{closure#0}, (), mz_ore::stack::RecursionLimitError>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  11: mz_ore::stack::maybe_grow::<<mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr> as mz_ore::stack::CheckedRecursion>::checked_recur<<mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr>>::visit_mut_post<<mz_transform::predicate_pushdown::PredicatePushdown>::inline_if_not_too_big::{closure#2}>::{closure#0}, (), mz_ore::stack::RecursionLimitError>::{closure#0}, core::result::Result<(), mz_ore::stack::RecursionLimitError>>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/ore/src/stack.rs:100:5
  12: <mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr> as mz_ore::stack::CheckedRecursion>::checked_recur::<<mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr>>::visit_mut_post<<mz_transform::predicate_pushdown::PredicatePushdown>::inline_if_not_too_big::{closure#2}>::{closure#0}, (), mz_ore::stack::RecursionLimitError>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/ore/src/stack.rs:191:19
  13: <mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr>>::visit_mut_post::<<mz_transform::predicate_pushdown::PredicatePushdown>::inline_if_not_too_big::{closure#2}>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/expr/src/visit.rs:521:14
  14: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::VisitChildren<mz_expr::scalar::MirScalarExpr>>::try_visit_mut_children::<<mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr>>::visit_mut_post<<mz_transform::predicate_pushdown::PredicatePushdown>::inline_if_not_too_big::{closure#2}>::{closure#0}::{closure#0}, mz_ore::stack::RecursionLimitError>
  15: <mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr>>::visit_mut_post::<<mz_transform::predicate_pushdown::PredicatePushdown>::inline_if_not_too_big::{closure#2}>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/expr/src/visit.rs:522:13
  16: <mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr> as mz_ore::stack::CheckedRecursion>::checked_recur::<<mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr>>::visit_mut_post<<mz_transform::predicate_pushdown::PredicatePushdown>::inline_if_not_too_big::{closure#2}>::{closure#0}, (), mz_ore::stack::RecursionLimitError>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/ore/src/stack.rs:191:33
  17: stacker::maybe_grow::<core::result::Result<(), mz_ore::stack::RecursionLimitError>, <mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr> as mz_ore::stack::CheckedRecursion>::checked_recur<<mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr>>::visit_mut_post<<mz_transform::predicate_pushdown::PredicatePushdown>::inline_if_not_too_big::{closure#2}>::{closure#0}, (), mz_ore::stack::RecursionLimitError>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  18: mz_ore::stack::maybe_grow::<<mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr> as mz_ore::stack::CheckedRecursion>::checked_recur<<mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr>>::visit_mut_post<<mz_transform::predicate_pushdown::PredicatePushdown>::inline_if_not_too_big::{closure#2}>::{closure#0}, (), mz_ore::stack::RecursionLimitError>::{closure#0}, core::result::Result<(), mz_ore::stack::RecursionLimitError>>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/ore/src/stack.rs:100:5
  19: <mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr> as mz_ore::stack::CheckedRecursion>::checked_recur::<<mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr>>::visit_mut_post<<mz_transform::predicate_pushdown::PredicatePushdown>::inline_if_not_too_big::{closure#2}>::{closure#0}, (), mz_ore::stack::RecursionLimitError>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/ore/src/stack.rs:191:19
  20: <mz_expr::visit::StackSafeVisit<mz_expr::scalar::MirScalarExpr>>::visit_mut_post::<<mz_transform::predicate_pushdown::PredicatePushdown>::inline_if_not_too_big::{closure#2}>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/expr/src/visit.rs:521:14
  21: <mz_expr::scalar::MirScalarExpr as mz_expr::visit::Visit>::visit_mut_post::<<mz_transform::predicate_pushdown::PredicatePushdown>::inline_if_not_too_big::{closure#2}>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/expr/src/visit.rs:322:9
  22: <mz_transform::predicate_pushdown::PredicatePushdown>::inline_if_not_too_big
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/transform/src/predicate_pushdown.rs:995:13
  23: <mz_transform::predicate_pushdown::PredicatePushdown>::push_filters_through_map
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/transform/src/predicate_pushdown.rs:918:21
  24: <mz_transform::predicate_pushdown::PredicatePushdown>::action::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/transform/src/predicate_pushdown.rs:410:56
  25: <mz_transform::predicate_pushdown::PredicatePushdown as mz_ore::stack::CheckedRecursion>::checked_recur::<<mz_transform::predicate_pushdown::PredicatePushdown>::action::{closure#0}, (), mz_transform::TransformError>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/ore/src/stack.rs:191:33
  26: stacker::maybe_grow::<core::result::Result<(), mz_transform::TransformError>, <mz_transform::predicate_pushdown::PredicatePushdown as mz_ore::stack::CheckedRecursion>::checked_recur<<mz_transform::predicate_pushdown::PredicatePushdown>::action::{closure#0}, (), mz_transform::TransformError>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  27: mz_ore::stack::maybe_grow::<<mz_transform::predicate_pushdown::PredicatePushdown as mz_ore::stack::CheckedRecursion>::checked_recur<<mz_transform::predicate_pushdown::PredicatePushdown>::action::{closure#0}, (), mz_transform::TransformError>::{closure#0}, core::result::Result<(), mz_transform::TransformError>>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/ore/src/stack.rs:100:5
  28: <mz_transform::predicate_pushdown::PredicatePushdown as mz_ore::stack::CheckedRecursion>::checked_recur::<<mz_transform::predicate_pushdown::PredicatePushdown>::action::{closure#0}, (), mz_transform::TransformError>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/ore/src/stack.rs:191:19
  29: <mz_transform::predicate_pushdown::PredicatePushdown>::action
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/transform/src/predicate_pushdown.rs:153:14
  30: <mz_transform::predicate_pushdown::PredicatePushdown>::action::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/transform/src/predicate_pushdown.rs:446:29
  31: <mz_transform::predicate_pushdown::PredicatePushdown as mz_ore::stack::CheckedRecursion>::checked_recur::<<mz_transform::predicate_pushdown::PredicatePushdown>::action::{closure#0}, (), mz_transform::TransformError>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/ore/src/stack.rs:191:33
  32: stacker::maybe_grow::<core::result::Result<(), mz_transform::TransformError>, <mz_transform::predicate_pushdown::PredicatePushdown as mz_ore::stack::CheckedRecursion>::checked_recur<<mz_transform::predicate_pushdown::PredicatePushdown>::action::{closure#0}, (), mz_transform::TransformError>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  33: mz_ore::stack::maybe_grow::<<mz_transform::predicate_pushdown::PredicatePushdown as mz_ore::stack::CheckedRecursion>::checked_recur<<mz_transform::predicate_pushdown::PredicatePushdown>::action::{closure#0}, (), mz_transform::TransformError>::{closure#0}, core::result::Result<(), mz_transform::TransformError>>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/ore/src/stack.rs:100:5
  34: <mz_transform::predicate_pushdown::PredicatePushdown as mz_ore::stack::CheckedRecursion>::checked_recur::<<mz_transform::predicate_pushdown::PredicatePushdown>::action::{closure#0}, (), mz_transform::TransformError>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/ore/src/stack.rs:191:19
  35: <mz_transform::predicate_pushdown::PredicatePushdown>::action
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/transform/src/predicate_pushdown.rs:153:14
  36: <mz_transform::predicate_pushdown::PredicatePushdown>::action::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/transform/src/predicate_pushdown.rs:768:25
  37: <mz_transform::predicate_pushdown::PredicatePushdown as mz_ore::stack::CheckedRecursion>::checked_recur::<<mz_transform::predicate_pushdown::PredicatePushdown>::action::{closure#0}, (), mz_transform::TransformError>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/ore/src/stack.rs:191:33
  38: stacker::maybe_grow::<core::result::Result<(), mz_transform::TransformError>, <mz_transform::predicate_pushdown::PredicatePushdown as mz_ore::stack::CheckedRecursion>::checked_recur<<mz_transform::predicate_pushdown::PredicatePushdown>::action::{closure#0}, (), mz_transform::TransformError>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  39: mz_ore::stack::maybe_grow::<<mz_transform::predicate_pushdown::PredicatePushdown as mz_ore::stack::CheckedRecursion>::checked_recur<<mz_transform::predicate_pushdown::PredicatePushdown>::action::{closure#0}, (), mz_transform::TransformError>::{closure#0}, core::result::Result<(), mz_transform::TransformError>>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/ore/src/stack.rs:100:5
  40: <mz_transform::predicate_pushdown::PredicatePushdown as mz_ore::stack::CheckedRecursion>::checked_recur::<<mz_transform::predicate_pushdown::PredicatePushdown>::action::{closure#0}, (), mz_transform::TransformError>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/ore/src/stack.rs:191:19
  41: <mz_transform::predicate_pushdown::PredicatePushdown>::action
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/transform/src/predicate_pushdown.rs:153:14
  42: <mz_transform::predicate_pushdown::PredicatePushdown>::action::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/transform/src/predicate_pushdown.rs:509:21
  43: <mz_transform::predicate_pushdown::PredicatePushdown as mz_ore::stack::CheckedRecursion>::checked_recur::<<mz_transform::predicate_pushdown::PredicatePushdown>::action::{closure#0}, (), mz_transform::TransformError>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/ore/src/stack.rs:191:33
  44: stacker::maybe_grow::<core::result::Result<(), mz_transform::TransformError>, <mz_transform::predicate_pushdown::PredicatePushdown as mz_ore::stack::CheckedRecursion>::checked_recur<<mz_transform::predicate_pushdown::PredicatePushdown>::action::{closure#0}, (), mz_transform::TransformError>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  45: mz_ore::stack::maybe_grow::<<mz_transform::predicate_pushdown::PredicatePushdown as mz_ore::stack::CheckedRecursion>::checked_recur<<mz_transform::predicate_pushdown::PredicatePushdown>::action::{closure#0}, (), mz_transform::TransformError>::{closure#0}, core::result::Result<(), mz_transform::TransformError>>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/ore/src/stack.rs:100:5
  46: <mz_transform::predicate_pushdown::PredicatePushdown as mz_ore::stack::CheckedRecursion>::checked_recur::<<mz_transform::predicate_pushdown::PredicatePushdown>::action::{closure#0}, (), mz_transform::TransformError>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/ore/src/stack.rs:191:19
  47: <mz_transform::predicate_pushdown::PredicatePushdown>::action
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/transform/src/predicate_pushdown.rs:153:14
  48: <mz_transform::predicate_pushdown::PredicatePushdown>::action::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/transform/src/predicate_pushdown.rs:501:21
  49: <mz_transform::predicate_pushdown::PredicatePushdown as mz_ore::stack::CheckedRecursion>::checked_recur::<<mz_transform::predicate_pushdown::PredicatePushdown>::action::{closure#0}, (), mz_transform::TransformError>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-008213910ce40aaea-1/materialize/tests/src/ore/src/stack.rs:191:33
  50: stacker::maybe_grow::<core::result::Result<(), mz_transform::TransformError>, <mz_transform::predicate_pushdown::PredicatePushdown as mz_ore::stack::CheckedRecursion>::checked_recur<<mz_transform::predicate_pushdown::PredicatePushdown>::action::{closure#0}, (), mz_transform::TransformError>::{closure#0}>
```

bisection and `git blame` both point to this commit:
```
commit 46d73a76c90d6812149e5c10d1afc533e80a2133 (HEAD)
Author: Gabor Gevay <gabor@materialize.com>
Date:   Mon Oct 2 15:02:39 2023 +0200

    Rewrite the Map to Filter inlining in `PredicatePushdown`
    
    This allows for more inlinings, so that `PredicatePushdown` is more
    robust.
    
    Closes #22040
```

To reproduce:

```
 CREATE SOURCE tpch
              FROM LOAD GENERATOR TPCH (SCALE FACTOR 0.00001)
              FOR ALL TABLES
              WITH (SIZE = '1');
 CREATE SOURCE auction
              FROM LOAD GENERATOR AUCTION (SCALE FACTOR 0.01)
              FOR ALL TABLES
              WITH (SIZE = '1');
 CREATE SOURCE counter
              FROM LOAD GENERATOR COUNTER (SCALE FACTOR 0.0001)
              WITH (SIZE = '1');
 CREATE TABLE t (a int2, b int4, c int8, d uint2, e uint4, f uint8, g text);
 INSERT INTO t VALUES (1, 2, 3, 4, 5, 6, '7'), (3, 4, 5, 6, 7, 8, '9'), (5, 6, 7, 8, 9, 10, '11'), (7, 8, 9, 10, 11, 12, '13'), (9, 10, 11, 12, 13, 14, '15'), (11, 12, 13, 14, 15, 16, '17'), (13, 14, 15, 16, 17, 18, '19'), (15, 16, 17, 18, 19, 20, '21');
 CREATE MATERIALIZED VIEW mv AS SELECT a + b AS col1, c + d AS col2, e + f AS col3, g AS col4 FROM t;
 CREATE MATERIALIZED VIEW mv2 AS SELECT count(*) FROM mv;
 CREATE DEFAULT INDEX ON mv;
 select  
  case when ((cast(1 as bpchar)) !~ (pg_catalog.current_schema())) 
      or (true) then subq_2."c2" else subq_2."c2" end
     as c0, 
  subq_2."c3" as c1, 
  subq_2."c3" as c2, 
  subq_2."c1" as c3, 
  ((cast(null as uint8)) % (case when false then (select "id" from mz_catalog.mz_audit_events limit 1 offset 5)
           else (select "id" from mz_catalog.mz_audit_events limit 1 offset 5)
           end
        )) >= (cast(nullif((case when ((select "created_at" from mz_internal.mz_subscriptions limit 1 offset 6)
              ) >= (TIMESTAMPTZ '2023-01-01 01:23:45+06') then pg_catalog.mod(
            CAST((select pg_catalog.max("region_id") from mz_internal.mz_expected_group_size_advice)
               as uint8),
            CAST(0 as uint8)) else pg_catalog.mod(
            CAST((select pg_catalog.max("region_id") from mz_internal.mz_expected_group_size_advice)
               as uint8),
            CAST(0 as uint8)) end
          ) << ((select pg_catalog.min("replication_factor") from mz_catalog.mz_clusters)
          ),
      ((select "worker_id" from mz_internal.mz_arrangement_heap_capacity_raw limit 1 offset 5)
          ) # ((select pg_catalog.min("duration_ns") from mz_internal.mz_peek_durations_histogram)
          )) as uint8)) as c4
from 
  (select  
        44 as c0, 
        (select pg_catalog.avg("id") from mz_internal.mz_dataflow_operator_dataflows)
           as c1, 
        subq_1."c2" as c2, 
        subq_1."c2" as c3, 
        mz_catalog.mz_version_num() as c4
      from 
        public.tpch_progress as ref_0,
        lateral (select  
              ref_0."offset" as c0, 
              subq_0."c0" as c1, 
              4 as c2, 
              ref_0."offset" as c3, 
              ref_0."offset" as c4
            from 
              (select  
                    ref_0."offset" as c0, 
                    ref_0."offset" as c1, 
                    ref_1."balance" as c2, 
                    (select "last_status_change_at" from mz_internal.mz_source_statuses limit 1 offset 5)
                       as c3, 
                    ref_0."offset" as c4, 
                    ref_1."org_id" as c5
                  from 
                    public.accounts as ref_1
                  where (ref_0."offset" is not NULL) 
                    and (false)) as subq_0
            where (numrange(0,0)) <= (numrange(0,0))) as subq_1
      where (mz_catalog.mz_uptime()) = (cast(coalesce(mz_catalog.mz_uptime(),
          mz_catalog.mz_uptime()) as interval))
      limit 73) as subq_2
where (case when (numrange(0,0)) = (numrange(0,0)) then cast(0 as char) else cast(0 as char) end
    ) <> (case when (select "worker_id" from mz_internal.mz_scheduling_elapsed_raw limit 1 offset 5)
         is NULL then case when ((cast(null as char)) = (cast(null as char))) 
        and (subq_2."c2" is not NULL) then cast(nullif(cast(nullif(case when ((select "data_type" from information_schema.columns limit 1 offset 6)
                ) <= (cast(1 as text)) then cast(0 as char) else cast(0 as char) end
            ,
          case when (cast(null as bpchar)) !~* ((select "typname" from pg_catalog.pg_type limit 1 offset 3)
                ) then cast(null as char) else cast(null as char) end
            ) as char),
        case when true then case when ((select "collection_timestamp" from mz_catalog.mz_storage_usage limit 1 offset 11)
                ) <> (TIMESTAMPTZ '2023-01-01 01:23:45+06') then cast(null as char) else cast(null as char) end
             else case when ((select "collection_timestamp" from mz_catalog.mz_storage_usage limit 1 offset 11)
                ) <> (TIMESTAMPTZ '2023-01-01 01:23:45+06') then cast(null as char) else cast(null as char) end
             end
          ) as char) else cast(nullif(cast(nullif(case when ((select "data_type" from information_schema.columns limit 1 offset 6)
                ) <= (cast(1 as text)) then cast(0 as char) else cast(0 as char) end
            ,
          case when (cast(null as bpchar)) !~* ((select "typname" from pg_catalog.pg_type limit 1 offset 3)
                ) then cast(null as char) else cast(null as char) end
            ) as char),
        case when true then case when ((select "collection_timestamp" from mz_catalog.mz_storage_usage limit 1 offset 11)
                ) <> (TIMESTAMPTZ '2023-01-01 01:23:45+06') then cast(null as char) else cast(null as char) end
             else case when ((select "collection_timestamp" from mz_catalog.mz_storage_usage limit 1 offset 11)
                ) <> (TIMESTAMPTZ '2023-01-01 01:23:45+06') then cast(null as char) else cast(null as char) end
             end
          ) as char) end
       else case when ((cast(null as char)) = (cast(null as char))) 
        and (subq_2."c2" is not NULL) then cast(nullif(cast(nullif(case when ((select "data_type" from information_schema.columns limit 1 offset 6)
                ) <= (cast(1 as text)) then cast(0 as char) else cast(0 as char) end
            ,
          case when (cast(null as bpchar)) !~* ((select "typname" from pg_catalog.pg_type limit 1 offset 3)
                ) then cast(null as char) else cast(null as char) end
            ) as char),
        case when true then case when ((select "collection_timestamp" from mz_catalog.mz_storage_usage limit 1 offset 11)
                ) <> (TIMESTAMPTZ '2023-01-01 01:23:45+06') then cast(null as char) else cast(null as char) end
             else case when ((select "collection_timestamp" from mz_catalog.mz_storage_usage limit 1 offset 11)
                ) <> (TIMESTAMPTZ '2023-01-01 01:23:45+06') then cast(null as char) else cast(null as char) end
             end
          ) as char) else cast(nullif(cast(nullif(case when ((select "data_type" from information_schema.columns limit 1 offset 6)
                ) <= (cast(1 as text)) then cast(0 as char) else cast(0 as char) end
            ,
          case when (cast(null as bpchar)) !~* ((select "typname" from pg_catalog.pg_type limit 1 offset 3)
                ) then cast(null as char) else cast(null as char) end
            ) as char),
        case when true then case when ((select "collection_timestamp" from mz_catalog.mz_storage_usage limit 1 offset 11)
                ) <> (TIMESTAMPTZ '2023-01-01 01:23:45+06') then cast(null as char) else cast(null as char) end
             else case when ((select "collection_timestamp" from mz_catalog.mz_storage_usage limit 1 offset 11)
                ) <> (TIMESTAMPTZ '2023-01-01 01:23:45+06') then cast(null as char) else cast(null as char) end
             end
          ) as char) end
       end
    );
```

**Comment by philip-stoev** [comment]
The problematic commit is present in `v0.72.0` so this is a release-blocker
