### ISSUE TITLE
SQLsmith: thread 'tokio:work-59' panicked at src/expr/src/relation/func.rs:1996:40: Datum::unwrap_mz_acl_item called on Null in mz_aclexplode

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#22275]
### What version of Materialize are you using?

main

### What is the issue?

```sql
select mz_internal.mz_aclexplode(array[null]::mz_aclitem[]);
```
panics:
```
thread 'tokio:work-59' panicked at src/expr/src/relation/func.rs:1996:40:
Datum::unwrap_mz_acl_item called on Null
stack backtrace:
cluster-u3-replica-u3: 2023-10-10T13:19:15.903841Z  INFO mz_storage::healthcheck: Health transition for source u12: Some(HealthStatusUpdate { update: Starting, should_halt: false }) -> HealthStatusUpdate { update: Running, should_halt: false }
   0: rust_begin_unwind
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/panicking.rs:72:14
   2: mz_repr::scalar::Datum::unwrap_mz_acl_item
             at ./src/repr/src/scalar.rs:880:18
   3: mz_expr::relation::func::mz_acl_explode::{{closure}}
             at ./src/expr/src/relation/func.rs:1996:28
   4: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/ops/function.rs:305:13
   5: core::option::Option<T>::map
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/option.rs:1075:29
   6: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/adapters/map.rs:103:26
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/adapters/map.rs:103:9
   8: core::ops::function::FnOnce::call_once
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/ops/function.rs:250:5
   9: core::iter::adapters::fuse::and_then_or_clear
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/adapters/fuse.rs:423:13
  10: <core::iter::adapters::fuse::Fuse<I> as core::iter::adapters::fuse::FuseImpl<I>>::next
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/adapters/fuse.rs:272:9
  11: <core::iter::adapters::fuse::Fuse<I> as core::iter::traits::iterator::Iterator>::next
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/adapters/fuse.rs:43:9
  12: <core::iter::adapters::flatten::FlattenCompat<I,U> as core::iter::traits::iterator::Iterator>::next
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/adapters/flatten.rs:480:29
  13: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/adapters/flatten.rs:52:9
  14: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/adapters/map.rs:103:9
  15: <alloc::boxed::Box<I,A> as core::iter::traits::iterator::Iterator>::next
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/alloc/src/boxed.rs:1941:9
  16: core::ops::function::FnOnce::call_once
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/ops/function.rs:250:5
  17: core::iter::adapters::fuse::and_then_or_clear
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/adapters/fuse.rs:423:13
  18: <core::iter::adapters::fuse::Fuse<I> as core::iter::adapters::fuse::FuseImpl<I>>::next
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/adapters/fuse.rs:272:9
  19: <core::iter::adapters::fuse::Fuse<I> as core::iter::traits::iterator::Iterator>::next
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/adapters/fuse.rs:43:9
  20: <&mut I as core::iter::traits::iterator::Iterator>::next
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/traits/iterator.rs:4168:18
  21: <core::iter::adapters::take::Take<I> as core::iter::traits::iterator::Iterator>::next
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/adapters/take.rs:40:23
  22: mz_transform::fold_constants::FoldConstants::fold_flat_map_constant
             at ./src/transform/src/fold_constants.rs:620:40
  23: mz_transform::fold_constants::FoldConstants::action
             at ./src/transform/src/fold_constants.rs:218:37
  24: <mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform::{{closure}}
             at ./src/transform/src/fold_constants.rs:51:13
  25: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}
             at ./src/expr/src/visit.rs:556:13
  26: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  27: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  28: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  29: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  30: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post
             at ./src/expr/src/visit.rs:554:9
  31: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:555:55
  32: <mz_expr::relation::MirRelationExpr as mz_expr::visit::VisitChildren<mz_expr::relation::MirRelationExpr>>::try_visit_mut_children
             at ./src/expr/src/relation/mod.rs:2232:13
  33: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}
             at ./src/expr/src/visit.rs:555:13
  34: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  35: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  36: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  37: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  38: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post
             at ./src/expr/src/visit.rs:554:9
  39: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:555:55
  40: <mz_expr::relation::MirRelationExpr as mz_expr::visit::VisitChildren<mz_expr::relation::MirRelationExpr>>::try_visit_mut_children
             at ./src/expr/src/relation/mod.rs:2232:13
  41: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}
             at ./src/expr/src/visit.rs:555:13
  42: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  43: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  44: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  45: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  46: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post
             at ./src/expr/src/visit.rs:554:9
  47: <T as mz_expr::visit::Visit>::try_visit_mut_post
             at ./src/expr/src/visit.rs:345:31
  48: <mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform
             at ./src/transform/src/fold_constants.rs:47:22
  49: <mz_transform::FuseAndCollapse as mz_transform::Transform>::transform
             at ./src/transform/src/lib.rs:419:13
  50: <mz_transform::Fixpoint as mz_transform::Transform>::transform::{{closure}}
             at ./src/transform/src/lib.rs:331:25
  51: tracing::span::Span::in_scope
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/span.rs:1102:9
  52: <mz_transform::Fixpoint as mz_transform::Transform>::transform
             at ./src/transform/src/lib.rs:329:17
  53: mz_transform::Optimizer::transform
             at ./src/transform/src/lib.rs:715:13
  54: mz_transform::Optimizer::optimize
             at ./src/transform/src/lib.rs:681:32
  55: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::optimize_peek
             at ./src/adapter/src/coord/sequencer/inner.rs:2294:22
  56: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::peek_stage_optimize::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer/inner.rs:2254:27
  57: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/task.rs:42:21
  58: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:334:17
  59: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/loom/std/unsafe_cell.rs:16:9
  60: tokio::runtime::task::core::Core<T,S>::poll
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:323:13
  61: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:485:19
  62: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/panic/unwind_safe.rs:271:9
  63: std::panicking::try::do_call
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/std/src/panicking.rs:504:40
  64: std::panicking::try
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/std/src/panicking.rs:468:19
  65: std::panic::catch_unwind
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/std/src/panic.rs:142:14
  66: tokio::runtime::task::harness::poll_future
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:473:18
  67: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:208:27
  68: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:153:15
  69: tokio::runtime::task::raw::RawTask::poll
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/raw.rs:200:18
  70: tokio::runtime::task::UnownedTask<S>::run
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/mod.rs:437:9
  71: tokio::runtime::blocking::pool::Task::run
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:159:9
  72: tokio::runtime::blocking::pool::Inner::run
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:513:17
  73: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:471:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

ci-regexp: Datum::unwrap_mz_acl_item called on Null
ci-regexp: Datum::unwrap_acl_item called on Null

**Comment by def-** [comment]
@jkosh44 This was added in https://github.com/MaterializeInc/materialize/pull/20755

**Comment by def-** [comment]
Similar panic in aclexplode too: `select aclexplode(array[null]::aclitem[]);`
```
thread 'tokio:work-9' panicked at src/expr/src/relation/func.rs:1969:34:
Datum::unwrap_acl_item called on Null
stack backtrace:
   0: rust_begin_unwind
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/panicking.rs:72:14
   2: mz_repr::scalar::Datum::unwrap_acl_item
             at ./src/repr/src/scalar.rs:893:18
   3: mz_expr::relation::func::acl_explode::{{closure}}
             at ./src/expr/src/relation/func.rs:1969:25
   4: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/ops/function.rs:305:13
   5: core::option::Option<T>::map
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/option.rs:1075:29
   6: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/adapters/map.rs:103:26
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/adapters/map.rs:103:9
   8: core::ops::function::FnOnce::call_once
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/ops/function.rs:250:5
   9: core::iter::adapters::fuse::and_then_or_clear
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/adapters/fuse.rs:423:13
  10: <core::iter::adapters::fuse::Fuse<I> as core::iter::adapters::fuse::FuseImpl<I>>::next
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/adapters/fuse.rs:272:9
  11: <core::iter::adapters::fuse::Fuse<I> as core::iter::traits::iterator::Iterator>::next
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/adapters/fuse.rs:43:9
  12: <core::iter::adapters::flatten::FlattenCompat<I,U> as core::iter::traits::iterator::Iterator>::next
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/adapters/flatten.rs:480:29
  13: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/adapters/flatten.rs:52:9
  14: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/adapters/map.rs:103:9
  15: <alloc::boxed::Box<I,A> as core::iter::traits::iterator::Iterator>::next
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/alloc/src/boxed.rs:1941:9
  16: core::ops::function::FnOnce::call_once
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/ops/function.rs:250:5
  17: core::iter::adapters::fuse::and_then_or_clear
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/adapters/fuse.rs:423:13
  18: <core::iter::adapters::fuse::Fuse<I> as core::iter::adapters::fuse::FuseImpl<I>>::next
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/adapters/fuse.rs:272:9
  19: <core::iter::adapters::fuse::Fuse<I> as core::iter::traits::iterator::Iterator>::next
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/adapters/fuse.rs:43:9
  20: <&mut I as core::iter::traits::iterator::Iterator>::next
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/traits/iterator.rs:4168:18
  21: <core::iter::adapters::take::Take<I> as core::iter::traits::iterator::Iterator>::next
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/iter/adapters/take.rs:40:23
  22: mz_transform::fold_constants::FoldConstants::fold_flat_map_constant
             at ./src/transform/src/fold_constants.rs:620:40
  23: mz_transform::fold_constants::FoldConstants::action
             at ./src/transform/src/fold_constants.rs:218:37
  24: <mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform::{{closure}}
             at ./src/transform/src/fold_constants.rs:51:13
  25: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}
             at ./src/expr/src/visit.rs:556:13
  26: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  27: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  28: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  29: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  30: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post
             at ./src/expr/src/visit.rs:554:9
  31: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:555:55
  32: <mz_expr::relation::MirRelationExpr as mz_expr::visit::VisitChildren<mz_expr::relation::MirRelationExpr>>::try_visit_mut_children
             at ./src/expr/src/relation/mod.rs:2232:13
  33: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}
             at ./src/expr/src/visit.rs:555:13
  34: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  35: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  36: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  37: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  38: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post
             at ./src/expr/src/visit.rs:554:9
  39: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}::{{closure}}
             at ./src/expr/src/visit.rs:555:55
  40: <mz_expr::relation::MirRelationExpr as mz_expr::visit::VisitChildren<mz_expr::relation::MirRelationExpr>>::try_visit_mut_children
             at ./src/expr/src/relation/mod.rs:2232:13
  41: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post::{{closure}}
             at ./src/expr/src/visit.rs:555:13
  42: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
  43: stacker::maybe_grow
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  44: mz_ore::stack::maybe_grow
             at ./src/ore/src/stack.rs:100:5
  45: mz_ore::stack::CheckedRecursion::checked_recur
             at ./src/ore/src/stack.rs:191:19
  46: mz_expr::visit::StackSafeVisit<T>::try_visit_mut_post
             at ./src/expr/src/visit.rs:554:9
  47: <T as mz_expr::visit::Visit>::try_visit_mut_post
             at ./src/expr/src/visit.rs:345:31
  48: <mz_transform::fold_constants::FoldConstants as mz_transform::Transform>::transform
             at ./src/transform/src/fold_constants.rs:47:22
  49: <mz_transform::FuseAndCollapse as mz_transform::Transform>::transform
             at ./src/transform/src/lib.rs:419:13
  50: <mz_transform::Fixpoint as mz_transform::Transform>::transform::{{closure}}
             at ./src/transform/src/lib.rs:331:25
  51: tracing::span::Span::in_scope
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/span.rs:1102:9
  52: <mz_transform::Fixpoint as mz_transform::Transform>::transform
             at ./src/transform/src/lib.rs:329:17
  53: mz_transform::Optimizer::transform
             at ./src/transform/src/lib.rs:715:13
  54: mz_transform::Optimizer::optimize
             at ./src/transform/src/lib.rs:681:32
  55: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::optimize_peek
             at ./src/adapter/src/coord/sequencer/inner.rs:2294:22
  56: mz_adapter::coord::sequencer::inner::<impl mz_adapter::coord::Coordinator>::peek_stage_optimize::{{closure}}::{{closure}}
             at ./src/adapter/src/coord/sequencer/inner.rs:2254:27
  57: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/task.rs:42:21
  58: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:334:17
  59: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/loom/std/unsafe_cell.rs:16:9
  60: tokio::runtime::task::core::Core<T,S>::poll
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:323:13
  61: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:485:19
  62: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/core/src/panic/unwind_safe.rs:271:9
  63: std::panicking::try::do_call
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/std/src/panicking.rs:504:40
  64: std::panicking::try
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/std/src/panicking.rs:468:19
  65: std::panic::catch_unwind
             at /rustc/187b8131d4f760f856b214fce34534903276f2ef/library/std/src/panic.rs:142:14
  66: tokio::runtime::task::harness::poll_future
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:473:18
  67: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:208:27
  68: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:153:15
  69: tokio::runtime::task::raw::RawTask::poll
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/raw.rs:200:18
  70: tokio::runtime::task::UnownedTask<S>::run
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/mod.rs:437:9
  71: tokio::runtime::blocking::pool::Task::run
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:159:9
  72: tokio::runtime::blocking::pool::Inner::run
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:513:17
  73: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/deen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:471:13
```
