### ISSUE TITLE
SQLsmith: thread 'coordinator' panicked at 'called `Result::unwrap()` on an `Err` value: TryFromIntError(())', src/repr/src/adt/numeric.rs:671:28

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#22340]
### What version of Materialize are you using?

main

### What is the issue?

Seen in SQLsmith with Explain: https://buildkite.com/materialize/nightlies/builds/4677#018b22a2-f58a-4369-9c84-7694de839eab I can't reproduce the panic unfortunately:
```
thread 'coordinator' panicked at 'called `Result::unwrap()` on an `Err` value: TryFromIntError(())', src/repr/src/adt/numeric.rs:671:28
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/result.rs:1651:5
   3: mz_repr::adt::numeric::rescale_within_max_precision
   4: mz_repr::adt::numeric::munge_numeric
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c931bce553db78-1/materialize/tests/src/repr/src/adt/numeric.rs:682:5
   5: <mz_expr::scalar::func::impls::float64::CastFloat64ToNumeric as mz_expr::scalar::func::EagerUnaryFunc>::call
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c931bce553db78-1/materialize/tests/src/expr/src/scalar/func/impls/float64.rs:234:15
   6: <mz_expr::scalar::func::impls::float64::CastFloat64ToNumeric as mz_expr::scalar::func::LazyUnaryFunc>::eval
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c931bce553db78-1/materialize/tests/src/expr/src/scalar/func.rs:4270:26
   7: <mz_expr::scalar::func::UnaryFunc>::eval
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c931bce553db78-1/materialize/tests/src/expr/src/scalar/func/macros.rs:343:41
```
Full stacktrace: https://gist.github.com/def-/2978eddf0b836a3ac6dd7d3423644790

ci-regexp: panicked at 'called `Result::unwrap()` on an `Err` value: TryFromIntError(())', src/repr/src/adt/numeric.rs

**Comment by def-** [comment]
Easy reproducer: `select cast('1e-307'::float8 as numeric);`. I'll provide a fix.
