### ISSUE TITLE
parallel-workload: Err(CoordinatorInconsistencies { catalog_inconsistencies: CatalogInconsistencies { internal_fields: [], roles: [], comments: [], object_dependencies: [], items: [StatementParseFailure { create_sql: "CREATE SINK ...

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#22459]
### What version of Materialize are you using?

main

### What is the issue?

```
thread 'coordinator' panicked at 'assertion failed: `(left == right)`
  left: `Err(CoordinatorInconsistencies { catalog_inconsistencies: CatalogInconsistencies { internal_fields: [], roles: [], comments: [], object_dependencies: [], items: [StatementParseFailure { create_sql: "CREATE SINK \"db_pw_1697583710\".\"public\".\"sink8\" IN CLUSTER [u2] FROM [u7 AS \"db_pw_1697583710\".\"public\".\"t1\"] INTO KAFKA CONNECTION [u1 AS \"db_pw_1697583710\".\"public\".\"kafka_conn\"] (TOPIC = \"sink_topic8\") KEY (\"c35_float4\", \"c29_text\", \"c5_smallint\", \"c27_smallint\", \"c8_float8\", \"c53_map[text=>text]\", \"c51_bigint\", \"c75_int\", \"c23_bytea\", \"c2_boolean\", \"c58_smallint\", \"c59_int\", \"c52_jsonb\", \"c60_bigint\", \"c17_bytea\", \"c32_bytea\", \"c63_smallint\", \"c69_float8\", \"c61_float4\", \"c64_int\", \"c11_smallint\", \"c48_map[text=>text]\", \"c40_smallint\", \"c66_smallint\", \"c16_bigint\", \"c15_jsonb\", \"c25_jsonb\", \"c57_smallint\", \"c45_bytea\", \"c65_jsonb\", \"c56_smallint\", \"c72_int\", \"c55_map[text=>text]\", \"c12_bytea\", \"c54_bigint\", \"c73_bytea\", \"c28_smallint\", \"c47_map[text=>text]\", \"c31_float8\", \"c37_map[text=>text]\", \"c9_jsonb\", \"c42_smallint\", \"c10_int\", \"c43_boolean\", \"c71_jsonb\", \"c26_text\", \"c70_smallint\", \"c46_smallint\", \"c62_text\", \"c38_bytea\", \"c50_jsonb\") NOT ENFORCED FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY CONNECTION [u2 AS \"db_pw_1697583710\".\"public\".\"csr_conn\"] (DOC ON TYPE [u7 AS \"db_pw_1697583710\".\"public\".\"t1\"] = '表ポあA鷗ŒéＢ逍Üßªąñ丂㐀𠀀', DOC ON COLUMN [u7 AS \"db_pw_1697583710\".\"public\".\"t1\"].c36_text = '-97', DOC ON COLUMN [u7 AS \"db_pw_1697583710\".\"public\".\"t1\"].c47_map[text=>text] = '0.0') ENVELOPE UPSERT" }] }, read_capabilities: [] })`,
 right: `Ok(())`', /home/deen/git/materialize/src/adapter/src/coord/ddl.rs:543:9
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed::<core::result::Result<(), mz_adapter::coord::consistency::CoordinatorInconsistencies>, core::result::Result<(), mz_adapter::coord::consistency::CoordinatorInconsistencies>>
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:228:5
cluster-u23-replica-u23: 2023-10-17T23:05:38.512380Z  INFO mz_storage::healthcheck: Health transition for source u131: Some(Starting) -> Some(Running)
   4: <mz_adapter::coord::Coordinator>::catalog_transact_with::<<mz_adapter::coord::Coordinator>::sequence_create_sink::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0}::{closure#0}
             at ./home/deen/git/materialize/src/adapter/src/coord/ddl.rs:543:9
   5: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::catalog_transact_with<<mz_adapter::coord::Coordinator>::sequence_create_sink::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
   6: <mz_adapter::coord::Coordinator>::catalog_transact_with::<<mz_adapter::coord::Coordinator>::sequence_create_sink::{closure#0}::{closure#0}::{closure#0}, ()>::{closure#0}
             at ./home/deen/git/materialize/src/adapter/src/coord/ddl.rs:97:5
   7: <mz_adapter::coord::Coordinator>::sequence_create_sink::{closure#0}::{closure#0}
             at ./home/deen/git/materialize/src/adapter/src/coord/sequencer/inner.rs:764:14
   8: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::sequence_create_sink::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
   9: <mz_adapter::coord::Coordinator>::sequence_create_sink::{closure#0}
             at ./home/deen/git/materialize/src/adapter/src/coord/sequencer/inner.rs:684:5
  10: <mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}::{closure#0}
             at ./home/deen/git/materialize/src/adapter/src/coord/sequencer.rs:185:68
  11: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  12: <mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}
             at ./home/deen/git/materialize/src/adapter/src/coord/sequencer.rs:65:5
  13: <mz_adapter::coord::Coordinator>::message_purified_statement_ready::{closure#0}::{closure#0}
             at ./home/deen/git/materialize/src/adapter/src/coord/message_handler.rs:464:22
  14: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::message_purified_statement_ready::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  15: <mz_adapter::coord::Coordinator>::message_purified_statement_ready::{closure#0}
             at ./home/deen/git/materialize/src/adapter/src/coord/message_handler.rs:351:5
  16: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
             at ./home/deen/git/materialize/src/adapter/src/coord/message_handler.rs:56:62
  17: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_message::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  18: <mz_ore::metrics::WallTimeFuture<tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_message::{closure#0}>, prometheus::histogram::Histogram> as core::future::future::Future>::poll
             at ./home/deen/git/materialize/src/ore/src/metrics.rs:595:28
  19: <mz_adapter::coord::Coordinator>::serve::{closure#0}
             at ./home/deen/git/materialize/src/adapter/src/coord.rs:1993:18
  20: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::serve::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  21: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::serve::{closure#0}>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  22: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::serve::{closure#0}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  23: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::serve::{closure#0}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  24: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::serve::{closure#0}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  25: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::serve::{closure#0}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  26: <tokio::runtime::handle::Handle>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:310:13
  27: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::handle::Handle>::block_on<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}, ()>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  28: <tokio::runtime::handle::Handle>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:309:9
  29: mz_adapter::coord::serve::{closure#0}::{closure#1}
             at ./home/deen/git/materialize/src/adapter/src/coord.rs:2236:17
```
Noticed in my WIP change https://github.com/MaterializeInc/materialize/pull/22299 (run via `bin/mzcompose --find parallel-workload down && bin/mzcompose --find parallel-workload run default --complexity=ddl --threads=25 --seed=1697583710` Edit: Can be reproduced on https://github.com/MaterializeInc/materialize/commit/c266cd9290b5ea8bf1e58a58f383b60c13bc5fb0
The consistency check itself was added in https://github.com/MaterializeInc/materialize/pull/21740

ci-regexp: thread 'coordinator' panicked at 'assertion failed: `(left == right)` 
ci-apply-to: parallel-workload-cancel
ci-apply-to: parallel-workload-ddl

**Comment by def-** [comment]
It would also be nice to improve the output of this assertion failure so that it prints a more unique line than ` parallel-workload-materialized-1     | thread 'coordinator' panicked at 'assertion failed: ``(left == right)`` `
Also reproduced in nightly on my branch: https://buildkite.com/materialize/nightlies/builds/4744

**Comment by philip-stoev** [comment]
> It would also be nice to improve the output of this assertion failure so that it prints a more unique line than parallel-workload-materialized-1     | thread 'coordinator' panicked at 'assertion failed: ``(left == right)``

In other assertions, left and right are printed separately below the text of the assertion and then, for complex nested data structures, one can use a diff-per-byte-coloring website such as https://www.diffchecker.com/text-compare/ to compare.

**Comment by def-** [comment]
@moulimukherjee This is a regression from the docs on sink schemas, reproducer testdrive file:
```
> CREATE CONNECTION kafka_conn TO KAFKA (BROKER '${testdrive.kafka-addr}');
> CREATE CONNECTION csr_conn TO CONFLUENT SCHEMA REGISTRY (URL '${testdrive.schema-registry-url}');
> CREATE TABLE t ("c1_map[text=>text]" map[text=>text]);
> COMMENT ON COLUMN t."c1_map[text=>text]" IS 'comment'
> CREATE SINK sink8 FROM t INTO KAFKA CONNECTION kafka_conn (TOPIC sink_topic8)  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY CONNECTION csr_conn ENVELOPE DEBEZIUM;
```
