### ISSUE TITLE
parallel-workload: thread 'coordinator' panicked at 'internal error: entered unreachable code: Internal error: only catalog items need to update item refs', src/sql/src/ast/transform.rs:67:14 

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#22490]
### What version of Materialize are you using?

00b2e1aaca (https://github.com/MaterializeInc/materialize/pull/22299)

### What is the issue?

Seen in https://buildkite.com/materialize/nightlies/builds/4762 in parallel-workload's rename scenario
```
thread 'coordinator' panicked at 'internal error: entered unreachable code: Internal error: only catalog items need to update item refs', src/sql/src/ast/transform.rs:67:14
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: mz_sql::ast::transform::create_stmt_rename_schema_refs
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c35972939b3b32-1/materialize/tests/src/sql/src/ast/transform.rs:67:14
   3: <mz_adapter::catalog::objects::CatalogItem>::rename_schema_refs::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c35972939b3b32-1/materialize/tests/src/adapter/src/catalog/objects.rs:880:13
   4: <mz_adapter::catalog::objects::CatalogItem>::rename_schema_refs
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c35972939b3b32-1/materialize/tests/src/adapter/src/catalog/objects.rs:898:32
   5: <mz_adapter::catalog::Catalog>::transact_inner::{closure#35}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c35972939b3b32-1/materialize/tests/src/adapter/src/catalog.rs:2868:42
   6: <mz_adapter::catalog::Catalog>::transact_inner
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c35972939b3b32-1/materialize/tests/src/adapter/src/catalog.rs:2889:25
   7: <mz_adapter::catalog::Catalog>::transact::<<mz_adapter::coord::Coordinator>::catalog_transact_with<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#1}, ()>::{closure#0}::{closure#0}::{closure#11}, ()>::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c35972939b3b32-1/materialize/tests/src/adapter/src/catalog.rs:1248:9
   8: <tracing::instrument::Instrumented<<mz_adapter::catalog::Catalog>::transact<<mz_adapter::coord::Coordinator>::catalog_transact_with<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#1}, ()>::{closure#0}::{closure#0}::{closure#11}, ()>::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
   9: <mz_adapter::catalog::Catalog>::transact::<<mz_adapter::coord::Coordinator>::catalog_transact_with<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#1}, ()>::{closure#0}::{closure#0}::{closure#11}, ()>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c35972939b3b32-1/materialize/tests/src/adapter/src/catalog.rs:1205:5
  10: <mz_adapter::coord::Coordinator>::catalog_transact_with::<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#1}, ()>::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c35972939b3b32-1/materialize/tests/src/adapter/src/coord/ddl.rs:382:14
  11: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::catalog_transact_with<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#1}, ()>::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  12: <mz_adapter::coord::Coordinator>::catalog_transact_with::<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#1}, ()>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c35972939b3b32-1/materialize/tests/src/adapter/src/coord/ddl.rs:97:5
  13: <mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c35972939b3b32-1/materialize/tests/src/adapter/src/coord/ddl.rs:74:14
  14: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  15: <mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c35972939b3b32-1/materialize/tests/src/adapter/src/coord/ddl.rs:67:5
  16: <mz_adapter::coord::Coordinator>::sequence_alter_schema_rename::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c35972939b3b32-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:4377:62
  17: <mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c35972939b3b32-1/materialize/tests/src/adapter/src/coord/sequencer.rs:383:85
  18: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  19: <mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c35972939b3b32-1/materialize/tests/src/adapter/src/coord/sequencer.rs:65:5
  20: <mz_adapter::coord::Coordinator>::handle_execute_inner::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c35972939b3b32-1/materialize/tests/src/adapter/src/coord/command_handler.rs:671:73
  21: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_execute_inner::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  22: <mz_adapter::coord::Coordinator>::handle_execute_inner::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c35972939b3b32-1/materialize/tests/src/adapter/src/coord/command_handler.rs:437:5
  23: <mz_adapter::coord::Coordinator>::handle_execute::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c35972939b3b32-1/materialize/tests/src/adapter/src/coord/command_handler.rs:434:54
  24: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_execute::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  25: <mz_adapter::coord::Coordinator>::handle_execute::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c35972939b3b32-1/materialize/tests/src/adapter/src/coord/command_handler.rs:335:5
  26: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_execute::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  27: <mz_adapter::coord::Coordinator>::handle_command::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c35972939b3b32-1/materialize/tests/src/adapter/src/coord/command_handler.rs:101:22
  28: <mz_adapter::coord::Coordinator>::message_command::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c35972939b3b32-1/materialize/tests/src/adapter/src/coord/message_handler.rs:243:34
  29: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::message_command::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  30: <mz_adapter::coord::Coordinator>::message_command::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c35972939b3b32-1/materialize/tests/src/adapter/src/coord/message_handler.rs:240:5
  31: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c35972939b3b32-1/materialize/tests/src/adapter/src/coord/message_handler.rs:43:64
  32: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_message::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  33: <mz_ore::metrics::WallTimeFuture<tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_message::{closure#0}>, prometheus::histogram::Histogram> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c35972939b3b32-1/materialize/tests/src/ore/src/metrics.rs:595:28
  34: <mz_adapter::coord::Coordinator>::serve::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c35972939b3b32-1/materialize/tests/src/adapter/src/coord.rs:1990:18
  35: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::serve::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  36: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::serve::{closure#0}>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  37: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::serve::{closure#0}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  38: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::serve::{closure#0}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  39: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::serve::{closure#0}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  40: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::serve::{closure#0}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  41: <tokio::runtime::handle::Handle>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:310:13
  42: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::handle::Handle>::block_on<<mz_adapter::coord::Coordinator>::serve::{closure#0}>::{closure#0}, ()>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  43: <tokio::runtime::handle::Handle>::block_on::<<mz_adapter::coord::Coordinator>::serve::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:309:9
  44: mz_adapter::coord::serve::{closure#0}::{closure#1}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-033c35972939b3b32-1/materialize/tests/src/adapter/src/coord.rs:2233:17
```
All queries that ran: https://gist.github.com/def-/deef34603fdaa814f7947020f8da1bc7
Reproducer: (works locally for me)
```
git checkout 00b2e1aaca
bin/mzcompose --find parallel-workload down && bin/mzcompose --find parallel-workload run default --seed=1697710745 --threads=32 --runtime=1500 --complexity=ddl --scenario=rename
```
It seems to me that a rename of s0 is happening, and then other queries, which are still running against the old name start to panic:
```
[worker_31] ALTER SCHEMA s0 RENAME TO s0_1;
[worker_17] SELECT * FROM s0.t5 JOIN s0.v5 ON s0.t5.c2_bigint = s0.v5."c27_bigint_s0.t6" LIMIT 1;
[worker_23] SELECT * FROM s0.t2_1 JOIN s0.v0 ON s0.t2_1.c41_bigint = s0.v0."c74_bigint_s0.t5" LIMIT 1;
```
This code just came in, so this is most likely a regression: https://github.com/MaterializeInc/materialize/pull/22365

ci-regexp: Internal error: only catalog items need to update item refs

**Comment by ParkMyCar** [comment]
Going to remove the release blocker tag since the troublesome feature is behind a LaunchDarkly flag

**Comment by ParkMyCar** [comment]
Note: I kicked off a [nightly build](https://buildkite.com/materialize/nightlies/builds/4776) to make sure the fix worked
