### ISSUE TITLE
Flaky restart test storage-managed-collections

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#22495]
### What version of Materialize are you using?

167fb84cc7e9

### What is the issue?

Seems unrelated to the PR where it happened: https://buildkite.com/materialize/tests/builds/66361#018b47cf-6a86-416e-8cd6-7260edb453dd
```
$ docker compose port materialized 6875
mzcompose: test case storage-managed-collections failed: <class 'Exception'>: user shards empty or not equal after restart
initial user shards: ()
user shards after restart: (['s4915ca2d-e5d4-4c72-a0cf-e84097bc9cef'],)
Traceback (most recent call last):
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-0af55545bf8d4068a-1/materialize/tests/misc/python/materialize/mzcompose/composition.py", line 470, in test_case
    yield
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-0af55545bf8d4068a-1/materialize/tests/test/restart/mzcompose.py", line 409, in workflow_default
    c.workflow(name)
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-0af55545bf8d4068a-1/materialize/tests/misc/python/materialize/mzcompose/composition.py", line 366, in workflow
    func(self)
  File "/var/lib/buildkite-agent/builds/buildkite-15f2293-i-0af55545bf8d4068a-1/materialize/tests/test/restart/mzcompose.py", line 212, in workflow_storage_managed_collections
    raise Exception("user shards empty or not equal after restart")
Exception: user shards empty or not equal after restart
```
The test came in via https://github.com/MaterializeInc/materialize/pull/15052

**Comment by def-** [comment]
This flake is not isolated, I've seen it at least 5 times today in main, so I'm assuming there is a regression:
https://buildkite.com/materialize/tests/builds/66425
https://buildkite.com/materialize/tests/builds/66423
https://buildkite.com/materialize/tests/builds/66402
https://buildkite.com/materialize/tests/builds/66392
https://buildkite.com/materialize/tests/builds/66388
The most recent Storage change was https://github.com/MaterializeInc/materialize/pull/22482 cc @guswynn 
@sploiselle @guswynn Is this a potential release blocker?

**Comment by guswynn** [comment]
I don't think my pr was related to this, it didnt change any behavior (the default stayed the same), so not sure if its a release blocker
