### ISSUE TITLE
panicked at 'Reference to absent collection: u3'

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#22644]
### What version of Materialize are you using?

4a8f986b5130f2189be115dea1321d1d1ed99bcd

### What is the issue?

This issue occurred within one day on three different branches in CI in job "Upsert (compaction disabled)".

```
 upsert-clusterd1-1        | ' panicked at 'Reference to absent collection: u3', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0207922171ca4c689-1/materialize/tests/src/storage-client/src/client.rs:630:33 
```

Builds (with retries):
* https://buildkite.com/materialize/tests/builds/66825#018b65cd-f6e8-4396-8d81-b5faac0ac238
* https://buildkite.com/materialize/tests/builds/66814#018b65b5-48e8-40c0-99b2-467bba034829
* https://buildkite.com/materialize/tests/builds/66816#018b65ba-28ad-4edd-9b71-a5e1c13fc012

More logs:
```
upsert-clusterd1-1        | ' panicked at 'Reference to absent collection: u3', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0207922171ca4c689-1/materialize/tests/src/storage-client/src/client.rs:630:33
upsert-kafka-1            | [2023-10-25 07:56:07,146] INFO starting (kafka.server.KafkaServer)
upsert-clusterd1-1        | stack backtrace:
upsert-zookeeper-1        | EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /127.0.0.1:53526, session = 0x0
upsert-materialized-1     | cluster-u1-replica-u1: 2023-10-25T07:59:01.810594Z  INFO mz_cluster::communication: Attempting to connect to process at /tmp/c4910cf98311b4a82c2a6c0bdb35193ebe622b61 process=3
upsert-schema-registry-1  | 529 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.NetworkClient  - [AdminClient clientId=adminclient-1] Node -1 has finalized features epoch: 0, finalized features: [], supported features: [], API versions: (Produce(0): 0 to 9 [usable: 9], Fetch(1): 0 to 12 [usable: 12], ListOffsets(2): 0 to 7 [usable: 7], Metadata(3): 0 to 11 [usable: 11], LeaderAndIsr(4): 0 to 5 [usable: 5], StopReplica(5): 0 to 3 [usable: 3], UpdateMetadata(6): 0 to 7 [usable: 7], ControlledShutdown(7): 0 to 3 [usable: 3], OffsetCommit(8): 0 to 8 [usable: 8], OffsetFetch(9): 0 to 8 [usable: 8], FindCoordinator(10): 0 to 4 [usable: 4], JoinGroup(11): 0 to 7 [usable: 7], Heartbeat(12): 0 to 4 [usable: 4], LeaveGroup(13): 0 to 4 [usable: 4], SyncGroup(14): 0 to 5 [usable: 5], DescribeGroups(15): 0 to 5 [usable: 5], ListGroups(16): 0 to 4 [usable: 4], SaslHandshake(17): 0 to 1 [usable: 1], ApiVersions(18): 0 to 3 [usable: 3], CreateTopics(19): 0 to 7 [usable: 7], DeleteTopics(20): 0 to 6 [usable: 6], DeleteRecords(21): 0 to 2 [usable: 2], InitProducerId(22): 0 to 4 [usable: 4], OffsetForLeaderEpoch(23): 0 to 4 [usable: 4], AddPartitionsToTxn(24): 0 to 3 [usable: 3], AddOffsetsToTxn(25): 0 to 3 [usable: 3], EndTxn(26): 0 to 3 [usable: 3], WriteTxnMarkers(27): 0 to 1 [usable: 1], TxnOffsetCommit(28): 0 to 3 [usable: 3], DescribeAcls(29): 0 to 2 [usable: 2], CreateAcls(30): 0 to 2 [usable: 2], DeleteAcls(31): 0 to 2 [usable: 2], DescribeConfigs(32): 0 to 4 [usable: 4], AlterConfigs(33): 0 to 2 [usable: 2], AlterReplicaLogDirs(34): 0 to 2 [usable: 2], DescribeLogDirs(35): 0 to 2 [usable: 2], SaslAuthenticate(36): 0 to 2 [usable: 2], CreatePartitions(37): 0 to 3 [usable: 3], CreateDelegationToken(38): 0 to 2 [usable: 2], RenewDelegationToken(39): 0 to 2 [usable: 2], ExpireDelegationToken(40): 0 to 2 [usable: 2], DescribeDelegationToken(41): 0 to 2 [usable: 2], DeleteGroups(42): 0 to 2 [usable: 2], ElectLeaders(43): 0 to 2 [usable: 2], IncrementalAlterConfigs(44): 0 to 1 [usable: 1], AlterPartitionReassignments(45): 0 [usable: 0], ListPartitionReassignments(46): 0 [usable: 0], OffsetDelete(47): 0 [usable: 0], DescribeClientQuotas(48): 0 to 1 [usable: 1], AlterClientQuotas(49): 0 to 1 [usable: 1], DescribeUserScramCredentials(50): 0 [usable: 0], AlterUserScramCredentials(51): 0 [usable: 0], AlterIsr(56): 0 [usable: 0], UpdateFeatures(57): 0 [usable: 0], DescribeCluster(60): 0 [usable: 0], DescribeProducers(61): 0 [usable: 0], DescribeTransactions(65): 0 [usable: 0], ListTransactions(66): 0 [usable: 0], AllocateProducerIds(67): 0 [usable: 0]).
upsert-schema-registry-1  | 529 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.admin.KafkaAdminClient  - [AdminClient clientId=adminclient-1] Sending MetadataRequestData(topics=[], allowAutoTopicCreation=true, includeClusterAuthorizedOperations=false, includeTopicAuthorizedOperations=false) to kafka:9092 (id: -1 rack: null). correlationId=1, timeoutMs=29768
upsert-schema-registry-1  | 530 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.NetworkClient  - [AdminClient clientId=adminclient-1] Sending METADATA request with header RequestHeader(apiKey=METADATA, apiVersion=11, clientId=adminclient-1, correlationId=1) and timeout 29768 to node -1: MetadataRequestData(topics=[], allowAutoTopicCreation=true, includeClusterAuthorizedOperations=false, includeTopicAuthorizedOperations=false)
upsert-schema-registry-1  | 537 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.NetworkClient  - [AdminClient clientId=adminclient-1] Received METADATA response from node -1 for request with header RequestHeader(apiKey=METADATA, apiVersion=11, clientId=adminclient-1, correlationId=1): MetadataResponseData(throttleTimeMs=0, brokers=[MetadataResponseBroker(nodeId=1, host='kafka', port=9092, rack=null)], clusterId='vtYjgWINTEuMmoEJWcSnPQ', controllerId=1, topics=[], clusterAuthorizedOperations=-2147483648)
upsert-schema-registry-1  | 538 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.admin.internals.AdminMetadataManager  - [AdminClient clientId=adminclient-1] Updating cluster metadata to Cluster(id = vtYjgWINTEuMmoEJWcSnPQ, nodes = [kafka:9092 (id: 1 rack: null)], partitions = [], controller = kafka:9092 (id: 1 rack: null))
upsert-schema-registry-1  | 539 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.ClientUtils  - Resolved host kafka as 172.16.96.5
upsert-schema-registry-1  | 539 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.NetworkClient  - [AdminClient clientId=adminclient-1] Initiating connection to node kafka:9092 (id: 1 rack: null) using address kafka/172.16.96.5
upsert-schema-registry-1  | 541 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.common.network.Selector  - [AdminClient clientId=adminclient-1] Created socket with SO_RCVBUF = 65536, SO_SNDBUF = 131072, SO_TIMEOUT = 0 to node 1
upsert-schema-registry-1  | 541 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.NetworkClient  - [AdminClient clientId=adminclient-1] Completed connection to node 1. Fetching API versions.
upsert-schema-registry-1  | 541 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.NetworkClient  - [AdminClient clientId=adminclient-1] Initiating API versions fetch from node 1.
upsert-schema-registry-1  | 541 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.NetworkClient  - [AdminClient clientId=adminclient-1] Sending API_VERSIONS request with header RequestHeader(apiKey=API_VERSIONS, apiVersion=3, clientId=adminclient-1, correlationId=2) and timeout 3600000 to node 1: ApiVersionsRequestData(clientSoftwareName='apache-kafka-java', clientSoftwareVersion='7.0.5-ccs')
upsert-schema-registry-1  | 543 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.NetworkClient  - [AdminClient clientId=adminclient-1] Received API_VERSIONS response from node 1 for request with header RequestHeader(apiKey=API_VERSIONS, apiVersion=3, clientId=adminclient-1, correlationId=2): ApiVersionsResponseData(errorCode=0, apiKeys=[ApiVersion(apiKey=0, minVersion=0, maxVersion=9), ApiVersion(apiKey=1, minVersion=0, maxVersion=12), ApiVersion(apiKey=2, minVersion=0, maxVersion=7), ApiVersion(apiKey=3, minVersion=0, maxVersion=11), ApiVersion(apiKey=4, minVersion=0, maxVersion=5), ApiVersion(apiKey=5, minVersion=0, maxVersion=3), ApiVersion(apiKey=6, minVersion=0, maxVersion=7), ApiVersion(apiKey=7, minVersion=0, maxVersion=3), ApiVersion(apiKey=8, minVersion=0, maxVersion=8), ApiVersion(apiKey=9, minVersion=0, maxVersion=8), ApiVersion(apiKey=10, minVersion=0, maxVersion=4), ApiVersion(apiKey=11, minVersion=0, maxVersion=7), ApiVersion(apiKey=12, minVersion=0, maxVersion=4), ApiVersion(apiKey=13, minVersion=0, maxVersion=4), ApiVersion(apiKey=14, minVersion=0, maxVersion=5), ApiVersion(apiKey=15, minVersion=0, maxVersion=5), ApiVersion(apiKey=16, minVersion=0, maxVersion=4), ApiVersion(apiKey=17, minVersion=0, maxVersion=1), ApiVersion(apiKey=18, minVersion=0, maxVersion=3), ApiVersion(apiKey=19, minVersion=0, maxVersion=7), ApiVersion(apiKey=20, minVersion=0, maxVersion=6), ApiVersion(apiKey=21, minVersion=0, maxVersion=2), ApiVersion(apiKey=22, minVersion=0, maxVersion=4), ApiVersion(apiKey=23, minVersion=0, maxVersion=4), ApiVersion(apiKey=24, minVersion=0, maxVersion=3), ApiVersion(apiKey=25, minVersion=0, maxVersion=3), ApiVersion(apiKey=26, minVersion=0, maxVersion=3), ApiVersion(apiKey=27, minVersion=0, maxVersion=1), ApiVersion(apiKey=28, minVersion=0, maxVersion=3), ApiVersion(apiKey=29, minVersion=0, maxVersion=2), ApiVersion(apiKey=30, minVersion=0, maxVersion=2), ApiVersion(apiKey=31, minVersion=0, maxVersion=2), ApiVersion(apiKey=32, minVersion=0, maxVersion=4), ApiVersion(apiKey=33, minVersion=0, maxVersion=2), ApiVersion(apiKey=34, minVersion=0, maxVersion=2), ApiVersion(apiKey=35, minVersion=0, maxVersion=2), ApiVersion(apiKey=36, minVersion=0, maxVersion=2), ApiVersion(apiKey=37, minVersion=0, maxVersion=3), ApiVersion(apiKey=38, minVersion=0, maxVersion=2), ApiVersion(apiKey=39, minVersion=0, maxVersion=2), ApiVersion(apiKey=40, minVersion=0, maxVersion=2), ApiVersion(apiKey=41, minVersion=0, maxVersion=2), ApiVersion(apiKey=42, minVersion=0, maxVersion=2), ApiVersion(apiKey=43, minVersion=0, maxVersion=2), ApiVersion(apiKey=44, minVersion=0, maxVersion=1), ApiVersion(apiKey=45, minVersion=0, maxVersion=0), ApiVersion(apiKey=46, minVersion=0, maxVersion=0), ApiVersion(apiKey=47, minVersion=0, maxVersion=0), ApiVersion(apiKey=48, minVersion=0, maxVersion=1), ApiVersion(apiKey=49, minVersion=0, maxVersion=1), ApiVersion(apiKey=50, minVersion=0, maxVersion=0), ApiVersion(apiKey=51, minVersion=0, maxVersion=0), ApiVersion(apiKey=56, minVersion=0, maxVersion=0), ApiVersion(apiKey=57, minVersion=0, maxVersion=0), ApiVersion(apiKey=60, minVersion=0, maxVersion=0), ApiVersion(apiKey=61, minVersion=0, maxVersion=0), ApiVersion(apiKey=65, minVersion=0, maxVersion=0), ApiVersion(apiKey=66, minVersion=0, maxVersion=0), ApiVersion(apiKey=67, minVersion=0, maxVersion=0)], throttleTimeMs=0, supportedFeatures=[], finalizedFeaturesEpoch=0, finalizedFeatures=[])
upsert-schema-registry-1  | 544 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.NetworkClient  - [AdminClient clientId=adminclient-1] Node 1 has finalized features epoch: 0, finalized features: [], supported features: [], API versions: (Produce(0): 0 to 9 [usable: 9], Fetch(1): 0 to 12 [usable: 12], ListOffsets(2): 0 to 7 [usable: 7], Metadata(3): 0 to 11 [usable: 11], LeaderAndIsr(4): 0 to 5 [usable: 5], StopReplica(5): 0 to 3 [usable: 3], UpdateMetadata(6): 0 to 7 [usable: 7], ControlledShutdown(7): 0 to 3 [usable: 3], OffsetCommit(8): 0 to 8 [usable: 8], OffsetFetch(9): 0 to 8 [usable: 8], FindCoordinator(10): 0 to 4 [usable: 4], JoinGroup(11): 0 to 7 [usable: 7], Heartbeat(12): 0 to 4 [usable: 4], LeaveGroup(13): 0 to 4 [usable: 4], SyncGroup(14): 0 to 5 [usable: 5], DescribeGroups(15): 0 to 5 [usable: 5], ListGroups(16): 0 to 4 [usable: 4], SaslHandshake(17): 0 to 1 [usable: 1], ApiVersions(18): 0 to 3 [usable: 3], CreateTopics(19): 0 to 7 [usable: 7], DeleteTopics(20): 0 to 6 [usable: 6], DeleteRecords(21): 0 to 2 [usable: 2], InitProducerId(22): 0 to 4 [usable: 4], OffsetForLeaderEpoch(23): 0 to 4 [usable: 4], AddPartitionsToTxn(24): 0 to 3 [usable: 3], AddOffsetsToTxn(25): 0 to 3 [usable: 3], EndTxn(26): 0 to 3 [usable: 3], WriteTxnMarkers(27): 0 to 1 [usable: 1], TxnOffsetCommit(28): 0 to 3 [usable: 3], DescribeAcls(29): 0 to 2 [usable: 2], CreateAcls(30): 0 to 2 [usable: 2], DeleteAcls(31): 0 to 2 [usable: 2], DescribeConfigs(32): 0 to 4 [usable: 4], AlterConfigs(33): 0 to 2 [usable: 2], AlterReplicaLogDirs(34): 0 to 2 [usable: 2], DescribeLogDirs(35): 0 to 2 [usable: 2], SaslAuthenticate(36): 0 to 2 [usable: 2], CreatePartitions(37): 0 to 3 [usable: 3], CreateDelegationToken(38): 0 to 2 [usable: 2], RenewDelegationToken(39): 0 to 2 [usable: 2], ExpireDelegationToken(40): 0 to 2 [usable: 2], DescribeDelegationToken(41): 0 to 2 [usable: 2], DeleteGroups(42): 0 to 2 [usable: 2], ElectLeaders(43): 0 to 2 [usable: 2], IncrementalAlterConfigs(44): 0 to 1 [usable: 1], AlterPartitionReassignments(45): 0 [usable: 0], ListPartitionReassignments(46): 0 [usable: 0], OffsetDelete(47): 0 [usable: 0], DescribeClientQuotas(48): 0 to 1 [usable: 1], AlterClientQuotas(49): 0 to 1 [usable: 1], DescribeUserScramCredentials(50): 0 [usable: 0], AlterUserScramCredentials(51): 0 [usable: 0], AlterIsr(56): 0 [usable: 0], UpdateFeatures(57): 0 [usable: 0], DescribeCluster(60): 0 [usable: 0], DescribeProducers(61): 0 [usable: 0], DescribeTransactions(65): 0 [usable: 0], ListTransactions(66): 0 [usable: 0], AllocateProducerIds(67): 0 [usable: 0]).
upsert-materialized-1     | cluster-u1-replica-u1: 2023-10-25T07:59:01.810610Z  INFO mz_cluster::communication: error connecting to process at /tmp/c4910cf98311b4a82c2a6c0bdb35193ebe622b61: No such file or directory (os error 2); will retry process=3
upsert-materialized-1     | cluster-u1-replica-u1: 2023-10-25T07:59:01.810619Z  INFO mz_cluster::communication: Attempting to connect to process at /tmp/fa809fd64ddb017656607558a20feb599a280b03 process=3
upsert-materialized-1     | cluster-u1-replica-u1: 2023-10-25T07:59:01.810632Z  INFO mz_cluster::communication: error connecting to process at /tmp/fa809fd64ddb017656607558a20feb599a280b03: No such file or directory (os error 2); will retry process=3
upsert-zookeeper-1        | 	at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
upsert-materialized-1     | cluster-u1-replica-u1: 2023-10-25T07:59:01.810643Z  INFO mz_cluster::communication: awaiting connection from peer process=3
upsert-zookeeper-1        | 	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326)
upsert-schema-registry-1  | 544 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.admin.KafkaAdminClient  - [AdminClient clientId=adminclient-1] Sending DescribeClusterRequestData(includeClusterAuthorizedOperations=false) to kafka:9092 (id: 1 rack: null). correlationId=3, timeoutMs=29993
upsert-zookeeper-1        | 	at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522)
upsert-schema-registry-1  | 544 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.NetworkClient  - [AdminClient clientId=adminclient-1] Sending DESCRIBE_CLUSTER request with header RequestHeader(apiKey=DESCRIBE_CLUSTER, apiVersion=0, clientId=adminclient-1, correlationId=3) and timeout 29993 to node 1: DescribeClusterRequestData(includeClusterAuthorizedOperations=false)
upsert-materialized-1     | cluster-u1-replica-u1: 2023-10-25T07:59:01.810679Z  INFO mz_cluster::server: Building timely container with config TimelyConfig { workers: 4, process: 3, addresses: ["/tmp/ca4388b6e13e449d6c08f985f109749c5aad124b", "/tmp/921e8b8fd357c6685d99271af8d5900362c54cee", "/tmp/3e11700d619f02e0137f7d1354ff21e3db4adf8b", "/tmp/7653563b08f18979e4f5c8656ca89868a5c68bf8"], idle_arrangement_merge_effort: 1000, variable_length_row_encoding: true }
upsert-schema-registry-1  | 547 [kafka-admin-client-thread | adminclient-1] DEBUG org.apache.kafka.clients.NetworkClient  - [AdminClient clientId=adminclient-1] Received DESCRIBE_CLUSTER response from node 1 for request with header RequestHeader(apiKey=DESCRIBE_CLUSTER, apiVersion=0, clientId=adminclient-1, correlationId=3): DescribeClusterResponseData(throttleTimeMs=0, errorCode=0, errorMessage=null, clusterId='vtYjgWINTEuMmoEJWcSnPQ', controllerId=1, brokers=[DescribeClusterBroker(brokerId=1, host='kafka', port=9092, rack=null)], clusterAuthorizedOperations=-2147483648)
upsert-materialized-1     | cluster-u1-replica-u1: 2023-10-25T07:59:01.810707Z  INFO mz_cluster::communication: initializing network for timely instance, with 4 processes for epoch number (4, 1) process=3 addresses=["/tmp/ca4388b6e13e449d6c08f985f109749c5aad124b", "/tmp/921e8b8fd357c6685d99271af8d5900362c54cee", "/tmp/3e11700d619f02e0137f7d1354ff21e3db4adf8b", "/tmp/7653563b08f18979e4f5c8656ca89868a5c68bf8"]
upsert-materialized-1     | cluster-u1-replica-u1: 2023-10-25T07:59:01.810744Z  INFO mz_cluster::server: Building timely container with config TimelyConfig { workers: 4, process: 2, addresses: ["/tmp/ca4388b6e13e449d6c08f985f109749c5aad124b", "/tmp/921e8b8fd357c6685d99271af8d5900362c54cee", "/tmp/3e11700d619f02e0137f7d1354ff21e3db4adf8b", "/tmp/7653563b08f18979e4f5c8656ca89868a5c68bf8"], idle_arrangement_merge_effort: 1000, variable_length_row_encoding: true }
upsert-materialized-1     | cluster-u1-replica-u1: 2023-10-25T07:59:01.810771Z  INFO mz_cluster::communication: initializing network for timely instance, with 4 processes for epoch number (4, 1) process=2 addresses=["/tmp/ca4388b6e13e449d6c08f985f109749c5aad124b", "/tmp/921e8b8fd357c6685d99271af8d5900362c54cee", "/tmp/3e11700d619f02e0137f7d1354ff21e3db4adf8b", "/tmp/7653563b08f18979e4f5c8656ca89868a5c68bf8"]
upsert-materialized-1     | cluster-u1-replica-u1: 2023-10-25T07:59:01.810793Z  INFO mz_cluster::server: Building timely container with config TimelyConfig { workers: 4, process: 1, addresses: ["/tmp/ca4388b6e13e449d6c08f985f109749c5aad124b", "/tmp/921e8b8fd357c6685d99271af8d5900362c54cee", "/tmp/3e11700d619f02e0137f7d1354ff21e3db4adf8b", "/tmp/7653563b08f18979e4f5c8656ca89868a5c68bf8"], idle_arrangement_merge_effort: 1000, variable_length_row_encoding: true }
upsert-materialized-1     | cluster-u1-replica-u1: 2023-10-25T07:59:01.810813Z  INFO mz_cluster::communication: initializing network for timely instance, with 4 processes for epoch number (4, 1) process=1 addresses=["/tmp/ca4388b6e13e449d6c08f985f109749c5aad124b", "/tmp/921e8b8fd357c6685d99271af8d5900362c54cee", "/tmp/3e11700d619f02e0137f7d1354ff21e3db4adf8b", "/tmp/7653563b08f18979e4f5c8656ca89868a5c68bf8"]
upsert-materialized-1     | cluster-u1-replica-u1: 2023-10-25T07:59:01.810907Z  INFO mz_cluster::communication: awaiting connection from peer process=0
upsert-materialized-1     | cluster-u1-replica-u1: 2023-10-25T07:59:01.810928Z  INFO mz_cluster::communication: Attempting to connect to process at /tmp/c56d04eb19a6230835113885d02856b6a71d0cfe process=1
upsert-materialized-1     | cluster-u1-replica-u1: 2023-10-25T07:59:01.810958Z  INFO mz_cluster::communication: awaiting connection from peer process=1
upsert-materialized-1     | cluster-s2-replica-s2: 2023-10-25T07:59:01.811021Z  INFO mz_cluster::communication: successfully initialized network process=0
upsert-materialized-1     | cluster-u1-replica-u1: 2023-10-25T07:59:01.811033Z  INFO mz_cluster::communication: accepted connection from peer process=0
upsert-materialized-1     | cluster-u1-replica-u1: 2023-10-25T07:59:01.811077Z  INFO mz_cluster::communication: awaiting connection from peer process=0
upsert-materialized-1     | cluster-s1-replica-s1: 2023-10-25T07:59:01.811105Z  INFO mz_cluster::communication: successfully initialized network process=0
upsert-materialized-1     | cluster-s2-replica-s2: 2023-10-25T07:59:01.811059Z  INFO mz_cluster::communication: successfully initialized network process=0
upsert-materialized-1     | cluster-u1-replica-u1: 2023-10-25T07:59:01.811143Z  INFO mz_cluster::communication: Attempting to connect to process at /tmp/c56d04eb19a6230835113885d02856b6a71d0cfe process=2
upsert-materialized-1     | cluster-u1-replica-u1: 2023-10-25T07:59:01.811098Z  INFO mz_cluster::server: Building timely container with config TimelyConfig { workers: 4, process: 0, addresses: ["/tmp/ca4388b6e13e449d6c08f985f109749c5aad124b", "/tmp/921e8b8fd357c6685d99271af8d5900362c54cee", "/tmp/3e11700d619f02e0137f7d1354ff21e3db4adf8b", "/tmp/7653563b08f18979e4f5c8656ca89868a5c68bf8"], idle_arrangement_merge_effort: 1000, variable_length_row_encoding: true }
upsert-materialized-1     | cluster-u1-replica-u1: 2023-10-25T07:59:01.811166Z  INFO mz_cluster::communication: Attempting to connect to process at /tmp/c4910cf98311b4a82c2a6c0bdb35193ebe622b61 process=2
upsert-materialized-1     | cluster-u1-replica-u1: 2023-10-25T07:59:01.811164Z  INFO mz_cluster::communication: Attempting to connect to process at /tmp/ca4388b6e13e449d6c08f985f109749c5aad124b process=1
upsert-materialized-1     | cluster-u1-replica-u1: 2023-10-25T07:59:01.811164Z  INFO mz_cluster::communication: initializing network for timely instance, with 4 processes for epoch number (4, 1) process=0 addresses=["/tmp/ca4388b6e13e449d6c08f985f109749c5aad124b", "/tmp/921e8b8fd357c6685d99271af8d5900362c54cee", "/tmp/3e11700d619f02e0137f7d1354ff21e3db4adf8b", "/tmp/7653563b08f18979e4f5c8656ca89868a5c68bf8"]
upsert-materialized-1     | cluster-u1-replica-u1: 2023-10-25T07:59:01.811192Z  INFO mz_cluster::communication: Attempting to connect to process at /tmp/ca4388b6e13e449d6c08f985f109749c5aad124b process=3
upsert-materialized-1     | cluster-u1-replica-u1: 2023-10-25T07:59:01.811205Z  INFO mz_cluster::communication: error connecting to process at /tmp/ca4388b6e13e449d6c08f985f109749c5aad124b: No such file or directory (os error 2); will retry process=1
upsert-materialized-1     | cluster-u1-replica-u1: 2023-10-25T07:59:01.811217Z  INFO mz_cluster::communication: awaiting connection from peer process=1
upsert-schema-registry-1  | 547 [main] DEBUG io.confluent.admin.utils.ClusterStatus  - Broker list: [kafka:9092 (id: 1 rack: null)]
```

**Comment by nrainer-materialize** [comment]
@sploiselle: Could this be related to recent changes conducted with https://github.com/MaterializeInc/materialize/pull/21852?

**Comment by nrainer-materialize** [comment]
This is already fixed with https://github.com/MaterializeInc/materialize/pull/22632.
