### ISSUE TITLE
panic: the implied capability Antichain should be less than the write_frontier Antichain

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#22725]
### What version of Materialize are you using?

baf628bcafcfd9280c1b8e956c2c5c4b4e8b200a

### What is the issue?

This occurred in [nightly build #4911](https://buildkite.com/materialize/nightlies/builds/4911) in "Checks upgrade across four versions":
 
```
platform-checks-materialized-1  | thread 'coordinator' panicked at 'u486:  the implied capability Antichain { elements: [1698364146000] } should be less than the write_frontier Antichain { elements: [1698363668000] }. Collection state dump: CollectionState {
platform-checks-materialized-1  |     description: CollectionDescription {
platform-checks-materialized-1  |         desc: RelationDesc {
platform-checks-materialized-1  |             typ: RelationType {
platform-checks-materialized-1  |                 column_types: [
platform-checks-materialized-1  |                     ColumnType {
platform-checks-materialized-1  |                         scalar_type: Int32,
platform-checks-materialized-1  |                         nullable: true,
platform-checks-materialized-1  |                     },
platform-checks-materialized-1  |                 ],
platform-checks-materialized-1  |                 keys: [],
platform-checks-materialized-1  |             },
platform-checks-materialized-1  |             names: [
platform-checks-materialized-1  |                 ColumnName(
platform-checks-materialized-1  |                     "f1",
platform-checks-materialized-1  |                 ),
platform-checks-materialized-1  |             ],
platform-checks-materialized-1  |         },
platform-checks-materialized-1  |         data_source: Other(
platform-checks-materialized-1  |             Source,
platform-checks-materialized-1  |         ),
platform-checks-materialized-1  |         since: None,
platform-checks-materialized-1  |         status_collection_id: Some(
platform-checks-materialized-1  |             System(
platform-checks-materialized-1  |                 557,
platform-checks-materialized-1  |             ),
platform-checks-materialized-1  |         ),
platform-checks-materialized-1  |     },
platform-checks-materialized-1  |     read_capabilities: MutableAntichain {
platform-checks-materialized-1  |         updates: ChangeBatch {
platform-checks-materialized-1  |             updates: [
platform-checks-materialized-1  |                 (
platform-checks-materialized-1  |                     1698364146000,
platform-checks-materialized-1  |                     1,
platform-checks-materialized-1  |                 ),
platform-checks-materialized-1  |             ],
platform-checks-materialized-1  |             clean: 1,
platform-checks-materialized-1  |         },
platform-checks-materialized-1  |         frontier: [
platform-checks-materialized-1  |             1698364146000,
platform-checks-materialized-1  |         ],
platform-checks-materialized-1  |         changes: ChangeBatch {
platform-checks-materialized-1  |             updates: [],
platform-checks-materialized-1  |             clean: 0,
platform-checks-materialized-1  |         },
platform-checks-materialized-1  |     },
platform-checks-materialized-1  |     implied_capability: Antichain {
platform-checks-materialized-1  |         elements: [
platform-checks-materialized-1  |             1698364146000,
platform-checks-materialized-1  |         ],
platform-checks-materialized-1  |     },
platform-checks-materialized-1  |     read_policy: NoPolicy {
platform-checks-materialized-1  |         initial_since: Antichain {
platform-checks-materialized-1  |             elements: [
platform-checks-materialized-1  |                 1698364146000,
platform-checks-materialized-1  |             ],
platform-checks-materialized-1  |         },
platform-checks-materialized-1  |     },
platform-checks-materialized-1  |     storage_dependencies: [],
platform-checks-materialized-1  |     write_frontier: Antichain {
platform-checks-materialized-1  |         elements: [
platform-checks-materialized-1  |             1698363668000,
platform-checks-materialized-1  |         ],
platform-checks-materialized-1  |     },
platform-checks-materialized-1  |     collection_metadata: CollectionMetadata {
platform-checks-materialized-1  |         persist_location: PersistLocation {
platform-checks-materialized-1  |             blob_uri: "s3://minioadmin:minioadmin@persist/persist?endpoint=http://minio:9000/&region=minio",
platform-checks-materialized-1  |             consensus_uri: "postgres://root@cockroach:26257?options=--search_path=consensus",
platform-checks-materialized-1  |         },
platform-checks-materialized-1  |         remap_shard: None,
platform-checks-materialized-1  |         data_shard: ShardId(430e682c-1832-4644-93a2-7d9ea921e4a8),
platform-checks-materialized-1  |         status_shard: Some(
platform-checks-materialized-1  |             ShardId(c10cd1b4-11a0-4b50-a3e1-e7449ab48029),
platform-checks-materialized-1  |         ),
platform-checks-materialized-1  |         relation_desc: RelationDesc {
platform-checks-materialized-1  |             typ: RelationType {
platform-checks-materialized-1  |                 column_types: [
platform-checks-materialized-1  |                     ColumnType {
platform-checks-materialized-1  |                         scalar_type: Int32,
platform-checks-materialized-1  |                         nullable: true,
platform-checks-materialized-1  |                     },
platform-checks-materialized-1  |                 ],
platform-checks-materialized-1  |                 keys: [],
platform-checks-materialized-1  |             },
platform-checks-materialized-1  |             names: [
platform-checks-materialized-1  |                 ColumnName(
platform-checks-materialized-1  |                     "f1",
platform-checks-materialized-1  |                 ),
platform-checks-materialized-1  |             ],
platform-checks-materialized-1  |         },
platform-checks-materialized-1  |     },
platform-checks-materialized-1  | }', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-079e8d361cdc4e25e-1/materialize/tests/src/storage-controller/src/lib.rs:2920:13
platform-checks-materialized-1  | stack backtrace:
platform-checks-materialized-1  |    0: rust_begin_unwind
platform-checks-materialized-1  |              at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
platform-checks-materialized-1  |    1: core::panicking::panic_fmt
platform-checks-materialized-1  |              at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
platform-checks-materialized-1  |    2: <mz_storage_controller::Controller<mz_repr::timestamp::Timestamp>>::install_dependency_read_holds::<core::iter::adapters::cloned::Cloned<alloc::collections::btree::map::Keys<mz_repr::global_id::GlobalId, mz_storage_types::sources::SourceExport>>>
platform-checks-materialized-1  |    3: <mz_storage_controller::Controller<mz_repr::timestamp::Timestamp> as mz_storage_client::controller::StorageController>::create_collections::{closure#0}::{closure#0}
platform-checks-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-079e8d361cdc4e25e-1/materialize/tests/src/storage-controller/src/lib.rs:726:21
platform-checks-materialized-1  |    4: <mz_storage_controller::Controller<mz_repr::timestamp::Timestamp> as mz_storage_client::controller::StorageController>::create_collections::{closure#0}
platform-checks-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-079e8d361cdc4e25e-1/materialize/tests/src/storage-controller/src/lib.rs:467:5
platform-checks-materialized-1  |    5: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(), mz_storage_types::controller::StorageError>>>> as core::future::future::Future>::poll
platform-checks-materialized-1  |              at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/future/future.rs:125:9
platform-checks-materialized-1  |    6: <mz_adapter::coord::Coordinator>::bootstrap::{closure#0}::{closure#0}
platform-checks-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-079e8d361cdc4e25e-1/materialize/tests/src/adapter/src/coord.rs:1392:30
platform-checks-materialized-1  |    7: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::bootstrap::{closure#0}::{closure#0}> as core::future::future::Future>::poll
platform-checks-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
platform-checks-materialized-1  |    8: <mz_adapter::coord::Coordinator>::bootstrap::{closure#0}
platform-checks-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-079e8d361cdc4e25e-1/materialize/tests/src/adapter/src/coord.rs:1065:5
platform-checks-materialized-1  |    9: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::bootstrap::{closure#0}> as core::future::future::Future>::poll
platform-checks-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
platform-checks-materialized-1  |   10: mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#0}
platform-checks-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-079e8d361cdc4e25e-1/materialize/tests/src/adapter/src/coord.rs:2223:22
platform-checks-materialized-1  |   11: <tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#0}> as core::future::future::Future>::poll
platform-checks-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
platform-checks-materialized-1  |   12: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#0}>>::{closure#0}
platform-checks-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
platform-checks-materialized-1  |   13: tokio::runtime::coop::with_budget::<core::task::poll::Poll<core::result::Result<(), mz_adapter::error::AdapterError>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#0}>>::{closure#0}>
platform-checks-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
platform-checks-materialized-1  |   14: tokio::runtime::coop::budget::<core::task::poll::Poll<core::result::Result<(), mz_adapter::error::AdapterError>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#0}>>::{closure#0}>
platform-checks-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
platform-checks-materialized-1  |   15: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#0}>>
platform-checks-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
platform-checks-materialized-1  |   16: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#0}>>
platform-checks-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
platform-checks-materialized-1  |   17: <tokio::runtime::handle::Handle>::block_on::<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#0}>::{closure#0}
platform-checks-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:310:13
platform-checks-materialized-1  |   18: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::handle::Handle>::block_on<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#0}>::{closure#0}, core::result::Result<(), mz_adapter::error::AdapterError>>
platform-checks-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
platform-checks-materialized-1  |   19: <tokio::runtime::handle::Handle>::block_on::<mz_adapter::coord::serve::{closure#0}::{closure#1}::{closure#0}>
platform-checks-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:309:9
platform-checks-materialized-1  |   20: mz_adapter::coord::serve::{closure#0}::{closure#1}
platform-checks-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-079e8d361cdc4e25e-1/materialize/tests/src/adapter/src/coord.rs:2219:29
platform-checks-materialized-1  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by guswynn** [comment]
Im gonna let that merged pr stew for a bit before closing this

**Comment by guswynn** [comment]
We believe https://github.com/MaterializeInc/materialize/pull/22740 fixed this!
