### ISSUE TITLE
storage_command_protobuf_roundtrip fails with explaining kafka create sinks

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#22987]
### What version of Materialize are you using?

e5da59fb6856

### What is the issue?

Seen in main: https://buildkite.com/materialize/tests/builds/68011#018ba8df-c076-4557-8199-113c5fd85f40
```
thread 'client::tests::storage_command_protobuf_roundtrip' panicked at 'assertion failed: `(left == right)`
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed::<mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageCommand>
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:228:5
   4: mz_storage_client::client::tests::storage_command_protobuf_roundtrip::test_impl::{closure#1}
             at ./src/client.rs:779:13
   5: <&mz_storage_client::client::tests::storage_command_protobuf_roundtrip::test_impl::{closure#1} as core::ops::function::Fn<(proptest::sugar::NamedArguments<&str, mz_storage_client::client::StorageCommand>,)>>::call
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:262:13
   6: proptest::test_runner::runner::call_test::<proptest::sugar::NamedArguments<&str, mz_storage_client::client::StorageCommand>, &mz_storage_client::client::tests::storage_command_protobuf_roundtrip::test_impl::{closure#1}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>::{closure#0}
             at /cargo/git/checkouts/proptest-e0d773c2e7a31a11/fc9660f/proptest/src/test_runner/runner.rs:246:49
   7: <core::panic::unwind_safe::AssertUnwindSafe<proptest::test_runner::runner::call_test<proptest::sugar::NamedArguments<&str, mz_storage_client::client::StorageCommand>, &mz_storage_client::client::tests::storage_command_protobuf_roundtrip::test_impl::{closure#1}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>::{closure#0}> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panic/unwind_safe.rs:271:9
   8: std::panicking::try::do_call::<core::panic::unwind_safe::AssertUnwindSafe<proptest::test_runner::runner::call_test<proptest::sugar::NamedArguments<&str, mz_storage_client::client::StorageCommand>, &mz_storage_client::client::tests::storage_command_protobuf_roundtrip::test_impl::{closure#1}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>::{closure#0}>, core::result::Result<(), proptest::test_runner::errors::TestCaseError>>
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:500:40
   9: __rust_try
  10: std::panicking::try::<core::result::Result<(), proptest::test_runner::errors::TestCaseError>, core::panic::unwind_safe::AssertUnwindSafe<proptest::test_runner::runner::call_test<proptest::sugar::NamedArguments<&str, mz_storage_client::client::StorageCommand>, &mz_storage_client::client::tests::storage_command_protobuf_roundtrip::test_impl::{closure#1}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>::{closure#0}>>
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:464:19
  11: std::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<proptest::test_runner::runner::call_test<proptest::sugar::NamedArguments<&str, mz_storage_client::client::StorageCommand>, &mz_storage_client::client::tests::storage_command_protobuf_roundtrip::test_impl::{closure#1}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>::{closure#0}>, core::result::Result<(), proptest::test_runner::errors::TestCaseError>>
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panic.rs:142:14
  12: proptest::test_runner::runner::call_test::<proptest::sugar::NamedArguments<&str, mz_storage_client::client::StorageCommand>, &mz_storage_client::client::tests::storage_command_protobuf_roundtrip::test_impl::{closure#1}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>
             at /cargo/git/checkouts/proptest-e0d773c2e7a31a11/fc9660f/proptest/src/test_runner/runner.rs:246:9
  13: <proptest::test_runner::runner::TestRunner>::shrink::<proptest::strategy::map::Map<proptest::strategy::unions::UnionValueTree<proptest::strategy::traits::BoxedStrategy<mz_storage_client::client::StorageCommand>>, mz_storage_client::client::tests::storage_command_protobuf_roundtrip::test_impl::{closure#0}>, &mz_storage_client::client::tests::storage_command_protobuf_roundtrip::test_impl::{closure#1}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>
             at /cargo/git/checkouts/proptest-e0d773c2e7a31a11/fc9660f/proptest/src/test_runner/runner.rs:807:30
  14: <proptest::test_runner::runner::TestRunner>::run_one_with_replay::<proptest::strategy::map::Map<proptest::strategy::unions::UnionValueTree<proptest::strategy::traits::BoxedStrategy<mz_storage_client::client::StorageCommand>>, mz_storage_client::client::tests::storage_command_protobuf_roundtrip::test_impl::{closure#0}>, &mz_storage_client::client::tests::storage_command_protobuf_roundtrip::test_impl::{closure#1}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>
             at /cargo/git/checkouts/proptest-e0d773c2e7a31a11/fc9660f/proptest/src/test_runner/runner.rs:705:27
  15: <proptest::test_runner::runner::TestRunner>::gen_and_run_case::<proptest::strategy::map::Map<proptest::strategy::unions::Union<proptest::strategy::traits::BoxedStrategy<mz_storage_client::client::StorageCommand>>, mz_storage_client::client::tests::storage_command_protobuf_roundtrip::test_impl::{closure#0}>, mz_storage_client::client::tests::storage_command_protobuf_roundtrip::test_impl::{closure#1}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>
             at /cargo/git/checkouts/proptest-e0d773c2e7a31a11/fc9660f/proptest/src/test_runner/runner.rs:649:12
  16: <proptest::test_runner::runner::TestRunner>::run_in_process_with_replay::<proptest::strategy::map::Map<proptest::strategy::unions::Union<proptest::strategy::traits::BoxedStrategy<mz_storage_client::client::StorageCommand>>, mz_storage_client::client::tests::storage_command_protobuf_roundtrip::test_impl::{closure#0}>, mz_storage_client::client::tests::storage_command_protobuf_roundtrip::test_impl::{closure#1}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>
             at /cargo/git/checkouts/proptest-e0d773c2e7a31a11/fc9660f/proptest/src/test_runner/runner.rs:602:26
  17: <proptest::test_runner::runner::TestRunner>::run_in_process::<proptest::strategy::map::Map<proptest::strategy::unions::Union<proptest::strategy::traits::BoxedStrategy<mz_storage_client::client::StorageCommand>>, mz_storage_client::client::tests::storage_command_protobuf_roundtrip::test_impl::{closure#0}>, mz_storage_client::client::tests::storage_command_protobuf_roundtrip::test_impl::{closure#1}>
             at /cargo/git/checkouts/proptest-e0d773c2e7a31a11/fc9660f/proptest/src/test_runner/runner.rs:560:9
  18: <proptest::test_runner::runner::TestRunner>::run::<proptest::strategy::map::Map<proptest::strategy::unions::Union<proptest::strategy::traits::BoxedStrategy<mz_storage_client::client::StorageCommand>>, mz_storage_client::client::tests::storage_command_protobuf_roundtrip::test_impl::{closure#0}>, mz_storage_client::client::tests::storage_command_protobuf_roundtrip::test_impl::{closure#1}>
             at /cargo/git/checkouts/proptest-e0d773c2e7a31a11/fc9660f/proptest/src/test_runner/runner.rs:403:13
  19: mz_storage_client::client::tests::storage_command_protobuf_roundtrip::test_impl
             at ./src/client.rs:771:5
  20: mz_storage_client::client::tests::storage_command_protobuf_roundtrip
             at /cargo/git/checkouts/proptest-e0d773c2e7a31a11/fc9660f/proptest/src/sugar.rs:158:15
  21: mz_storage_client::client::tests::storage_command_protobuf_roundtrip::{closure#0}
             at /cargo/git/checkouts/proptest-e0d773c2e7a31a11/fc9660f/proptest/src/sugar.rs:158:15
  22: <mz_storage_client::client::tests::storage_command_protobuf_roundtrip::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
  23: core::ops::function::FnOnce::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
```
The difference between left and right seems to be `connection_options: None` vs `connection_options: Some({})`, full text on gist: https://gist.github.com/def-/b52f02e929667ed3d7d16a822e1e9554

I think this issue came in from https://github.com/MaterializeInc/materialize/pull/22626, which is included in 0.76.0, so might be a blocker for that. @moulimukherjee Can you please check and remove the release-blocker tag if it's not a blocker.

**Comment by def-** [comment]
Reproduced locally with `while true; do cargo nextest run storage_command_protobuf_roundtrip || break; done`

**Comment by sploiselle** [comment]
This was me in #22907
