### ISSUE TITLE
thread 'test_max_request_size' panicked at 'expected DbError, but got: Error { kind: Closed, cause: None }', src/environmentd/src/test_util.rs:679:21

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#22998]
### What version of Materialize are you using?

c5fee8107dc2

### What is the issue?

```
thread 'test_max_request_size' panicked at 'expected DbError, but got: Error { kind: Closed, cause: None }', src/environmentd/src/test_util.rs:679:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: <tokio_postgres::error::Error as mz_environmentd::test_util::PostgresErrorExt>::unwrap_db_error
             at ./src/test_util.rs:679:21
   3: <core::result::Result<alloc::vec::Vec<tokio_postgres::row::Row>, tokio_postgres::error::Error> as mz_environmentd::test_util::PostgresErrorExt>::unwrap_db_error
             at ./src/test_util.rs:691:23
   4: server::test_max_request_size::test_impl
             at ./tests/server.rs:1592:19
   5: server::test_max_request_size
             at ./tests/server.rs:1580:1
   6: server::test_max_request_size::{closure#0}
             at ./tests/server.rs:1580:1
   7: <server::test_max_request_size::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Seen in https://buildkite.com/materialize/tests/builds/68031#018ba99b-d981-4cd6-b788-7538104ee32b
@sploiselle I'm wondering if this is related to https://github.com/MaterializeInc/materialize/issues/22987 ?

**Comment by sploiselle** [comment]
I just ran this test 30 times on top of #22999 and did not repro the flake.

**Comment by def-** [comment]
Great, marking as duplicate of https://github.com/MaterializeInc/materialize/issues/22987

**Comment by def-** [comment]
@sploiselle Seen this again on main:
```
--- STDERR:              mz-environmentd::server test_max_request_size ---
thread 'test_max_request_size' panicked at src/environmentd/src/test_util.rs:960:21:
expected DbError, but got: Error { kind: Closed, cause: None }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: <tokio_postgres::error::Error as mz_environmentd::test_util::PostgresErrorExt>::unwrap_db_error
             at ./src/test_util.rs:960:21
   3: <core::result::Result<alloc::vec::Vec<tokio_postgres::row::Row>, tokio_postgres::error::Error> as mz_environmentd::test_util::PostgresErrorExt>::unwrap_db_error
             at ./src/test_util.rs:972:23
   4: server::test_max_request_size::test_impl
             at ./tests/server.rs:1537:19
   5: server::test_max_request_size
             at ./tests/server.rs:1525:1
   6: server::test_max_request_size::{closure#0}
             at ./tests/server.rs:1525:1
   7: <server::test_max_request_size::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
```
https://buildkite.com/materialize/tests/builds/70706#018c4614-2c7a-4a9e-bff7-eb34e176714d
So this appears not to be fixed yet.

**Comment by bkirwi** [comment]
This is quite common on `main` - three of the last five builds have failed with it.

**Comment by sploiselle** [comment]
@def- Do you know if this issue has crept back up?

**Comment by nrainer-materialize** [comment]
@sploiselle: It was last observed on main in https://buildkite.com/materialize/tests/builds/78912#annotation-018e6318-3c11-44fb-8f6c-ec4806701902-error on March 21st 2024.

**Comment by sploiselle** [comment]
Dang, ok––thanks @nrainer-materialize.

**Comment by sploiselle** [comment]
Ok, this reliably reproduces in ~1 hour with:

```bash
while true; do cargo nextest run -p mz-environmentd test_max_request_size || break; done
```

This is an issue with tokio-postgres closing the connection instead of returning the error––definitely nothing to do with storage or `CONNECTION` objects.

Assigning to adapter as they are the folks with expertise in this area of the code.

**Comment by nrainer-materialize** [comment]
Further occurrence: https://buildkite.com/materialize/test/builds/84082#019029e4-b100-4054-a682-3075f9722e11

**Comment by jkosh44** [comment]
A couple of interesting errors that I see in the logs. Are these all known issues? The PostgreSQL ones looks especially scary.

**Schema Registry**
```
cargo-test-schema-registry-1  | io.confluent.rest.exceptions.RestNotFoundException: Subject 'ccsr-test-schema' does not have subject-level compatibility configured
cargo-test-schema-registry-1  | 	at io.confluent.kafka.schemaregistry.rest.exceptions.Errors.subjectLevelCompatibilityNotConfiguredException(Errors.java:105)
cargo-test-schema-registry-1  | 	at io.confluent.kafka.schemaregistry.rest.resources.ConfigResource.getSubjectLevelConfig(ConfigResource.java:185)
cargo-test-schema-registry-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
cargo-test-schema-registry-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
cargo-test-schema-registry-1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
cargo-test-schema-registry-1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
cargo-test-schema-registry-1  | 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
cargo-test-schema-registry-1  | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134)
cargo-test-schema-registry-1  | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177)
cargo-test-schema-registry-1  | 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
cargo-test-schema-registry-1  | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81)
cargo-test-schema-registry-1  | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
cargo-test-schema-registry-1  | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
cargo-test-schema-registry-1  | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
cargo-test-schema-registry-1  | 	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
cargo-test-schema-registry-1  | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
cargo-test-schema-registry-1  | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
cargo-test-schema-registry-1  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
cargo-test-schema-registry-1  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
cargo-test-schema-registry-1  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
cargo-test-schema-registry-1  | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
cargo-test-schema-registry-1  | 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
cargo-test-schema-registry-1  | 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
cargo-test-schema-registry-1  | 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
cargo-test-schema-registry-1  | 	at org.glassfish.jersey.servlet.ServletContainer.serviceImpl(ServletContainer.java:378)
cargo-test-schema-registry-1  | 	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:553)
cargo-test-schema-registry-1  | 	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:494)
cargo-test-schema-registry-1  | 	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:431)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
cargo-test-schema-registry-1  | 	at io.confluent.kafka.schemaregistry.rest.RequestIdHandler.handle(RequestIdHandler.java:51)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:181)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:772)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.server.Server.handle(Server.java:516)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
cargo-test-schema-registry-1  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
cargo-test-schema-registry-1  | 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Zookeeper**
```
cargo-test-zookeeper-1        | [2024-06-18 06:18:29,426] INFO Unable to read additional data from client, it probably closed the socket: address = /127.0.0.1:54482, session = 0x0 (org.apache.zookeeper.server.NIOServerCnxn)
```

**Postgres**
```
cargo-test-postgres-1         | 2024-06-18 05:54:01.631 UTC [73] FATAL:  role "root" does not exist

cargo-test-postgres-1         | 2024-06-18 06:15:23.476 UTC [7896] ERROR:  column pg_index.indnullsnotdistinct does not exist at character 184
cargo-test-postgres-1         | 2024-06-18 06:15:23.476 UTC [7896] STATEMENT:  
cargo-test-postgres-1         | 	        SELECT
cargo-test-postgres-1         | 	            pg_constraint.oid,
cargo-test-postgres-1         | 	            pg_constraint.conkey,
cargo-test-postgres-1         | 	            pg_constraint.conname,
cargo-test-postgres-1         | 	            pg_constraint.contype = 'p' AS is_primary,
cargo-test-postgres-1         | 	            pg_index.indnullsnotdistinct AS nulls_not_distinct
cargo-test-postgres-1         | 	        FROM
cargo-test-postgres-1         | 	            pg_constraint
cargo-test-postgres-1         | 	                JOIN
cargo-test-postgres-1         | 	                    pg_index
cargo-test-postgres-1         | 	                    ON pg_index.indexrelid = pg_constraint.conindid
cargo-test-postgres-1         | 	        WHERE
cargo-test-postgres-1         | 	            pg_constraint.conrelid = $1
cargo-test-postgres-1         | 	                AND
cargo-test-postgres-1         | 	            pg_constraint.contype =ANY (ARRAY['p', 'u']);

cargo-test-postgres-1         | 2024-06-18 06:16:45.526 UTC [8440] ERROR:  replication slot "materialize_aa24e3086d20467197056e8522f7db74" already exists
cargo-test-postgres-1         | 2024-06-18 06:16:45.526 UTC [8440] STATEMENT:  CREATE_REPLICATION_SLOT materialize_aa24e3086d20467197056e8522f7db74 LOGICAL "pgoutput" NOEXPORT_SNAPSHOT
```

**Kafka**
```
cargo-test-kafka-1            | [2024-06-18 05:54:09,643] WARN [RequestSendThread controllerId=1] Controller 1's connection to broker kafka:9092 (id: 1 rack: null) was unsuccessful (kafka.controller.RequestSendThread)
cargo-test-kafka-1            | java.io.IOException: Connection to kafka:9092 (id: 1 rack: null) failed.
cargo-test-kafka-1            | 	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:70)
cargo-test-kafka-1            | 	at kafka.controller.RequestSendThread.brokerReady(ControllerChannelManager.scala:296)
cargo-test-kafka-1            | 	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:249)
cargo-test-kafka-1            | 	at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:127)

```

**Comment by jkosh44** [comment]
I am also able to reproduce this by running the test in an infinite loop. One thing I've noticed is that the server doesn't crash, I can catch the error, reconnect to the server and execute a query. It looks like the connection itself is being closed explicitly.

**Comment by jkosh44** [comment]
When running in release mode I've been able to get the bug to repro within 30 seconds. Attached is a full dump of DEBUG logs from one of the failures. There's a suspect log line that I noticed but I'll analyze in more detail next week:

```
2024-07-19T21:08:43.506942Z DEBUG mz_server_core: error handling connection in pgwire: request larger than 2.0 MB
```

[out.txt](https://github.com/user-attachments/files/16317071/out.txt)

**Comment by jkosh44** [comment]
The outer error is coming from here:
https://github.com/MaterializeInc/materialize/blob/1937ca8b444a919e3077843980c97d61fc072252/src/server-core/src/lib.rs#L136-L145

The inner error is coming from here: 
https://github.com/MaterializeInc/materialize/blob/1937ca8b444a919e3077843980c97d61fc072252/src/pgwire/src/codec.rs#L394-L403

Note: `balancerd` has an identical function and error, but so far all of the repros have come from `pgwire`.

**Comment by jkosh44** [comment]
That error message was introduced by https://github.com/MaterializeInc/materialize/pull/17481, which resolved https://github.com/MaterializeInc/materialize/pull/17481.

One interesting aspect of this failure is that it works on batches of messages, not single messages. So that might explain why the failure only happens sometimes. Sometimes enough messages are batched together to trigger an error and sometimes it doesn't. The fix might be to change this check to work on individual messages instead of batches of messages.

**Comment by jkosh44** [comment]
Interestingly that error message is exactly what this test is trying to test. In fact in the original PR, linked above, the connection dropped with no error message. In a later PR, https://github.com/MaterializeInc/materialize/commit/593df956, it was updated so that the connection received an error, then dropped. Maybe there's a race somewhere that causes the connection to be dropped before the error is received.

**Comment by jkosh44** [comment]
Attached is an example of a rejected message when the test fails and an example of a rejected message when a test passes. They are identical other than the statement names. Additionally, in order to get these messages I applied to the following diff:

```
diff --git a/src/environmentd/tests/server.rs b/src/environmentd/tests/server.rs
index 12827f9a6f..c3e7f5cb36 100644
--- a/src/environmentd/tests/server.rs
+++ b/src/environmentd/tests/server.rs
@@ -1534,7 +1534,6 @@ fn test_default_cluster_sizes() {
 }
 
 #[mz_ore::test]
-#[ignore] // TODO: Reenable when #22998 is fixed
 fn test_max_request_size() {
     let statement = "SELECT $1::text";
     let statement_size = statement.bytes().count();
diff --git a/src/pgwire/src/codec.rs b/src/pgwire/src/codec.rs
index 4aa9acd3b0..d01eb1dd45 100644
--- a/src/pgwire/src/codec.rs
+++ b/src/pgwire/src/codec.rs
@@ -26,10 +26,11 @@ use mz_pgwire_common::{
     input_err, parse_frame_len, Conn, Cursor, DecodeState, ErrorResponse, FrontendMessage, Pgbuf,
     MAX_REQUEST_SIZE,
 };
+use std::thread;
 use tokio::io::{self, AsyncRead, AsyncWrite, Interest, Ready};
 use tokio::time::{self, Duration};
 use tokio_util::codec::{Decoder, Encoder, Framed};
-use tracing::trace;
+use tracing::{debug, info, trace};
 
 use crate::message::{BackendMessage, BackendMessageKind};
 
@@ -392,14 +393,17 @@ impl Decoder for Codec {
     type Error = io::Error;
 
     fn decode(&mut self, src: &mut BytesMut) -> Result<Option<FrontendMessage>, io::Error> {
+        let len = src.len();
+        let mut size_error = false;
         if src.len() > MAX_REQUEST_SIZE {
-            return Err(io::Error::new(
-                io::ErrorKind::InvalidData,
-                format!(
-                    "request larger than {}",
-                    ByteSize::b(u64::cast_from(MAX_REQUEST_SIZE))
-                ),
-            ));
+            //     return Err(io::Error::new(
+            //         io::ErrorKind::InvalidData,
+            //         format!(
+            //             "request larger than {}",
+            //             ByteSize::b(u64::cast_from(MAX_REQUEST_SIZE))
+            //         ),
+            //     ));
+            size_error = true;
         }
         loop {
             match self.decode_state {
@@ -454,7 +458,20 @@ impl Decoder for Codec {
                     };
                     src.reserve(5);
                     self.decode_state = DecodeState::Head;
-                    return Ok(Some(msg));
+                    if size_error {
+                        return Err(io::Error::new(
+                            io::ErrorKind::InvalidData,
+                            format!(
+                                "request larger than {} ({}): {:?}",
+                                ByteSize::b(u64::cast_from(MAX_REQUEST_SIZE)),
+                                len,
+                                msg,
+                            ),
+                        ));
+                    } else {
+                        info!("successful msg len {}", len);
+                        return Ok(Some(msg));
+                    }
                 }
             }
         }
diff --git a/src/server-core/src/lib.rs b/src/server-core/src/lib.rs
index 00bb421645..333083e6b7 100644
--- a/src/server-core/src/lib.rs
+++ b/src/server-core/src/lib.rs
@@ -28,7 +28,7 @@ use tokio::net::{TcpListener, TcpStream};
 use tokio::sync::oneshot;
 use tokio::task::JoinSet;
 use tokio_stream::wrappers::{IntervalStream, TcpListenerStream};
-use tracing::{debug, error, warn};
+use tracing::{debug, error, info, warn};
 
 /// TCP keepalive settings. The idle time and interval match CockroachDB [0].
 /// The number of retries matches the Linux default.
@@ -136,7 +136,7 @@ where
                 let fut = server.handle_connection(conn);
                 set.spawn_named(|| &task_name, async {
                     if let Err(e) = fut.await {
-                        debug!(
+                        info!(
                             "error handling connection in {}: {}",
                             S::NAME,
                             e.display_with_causes()

```

When that diff is applied the test fails with a much higher frequency, which is further evidence that there's a race happening somewhere.

[fail.txt](https://github.com/user-attachments/files/16338291/fail.txt)
[pass.txt](https://github.com/user-attachments/files/16338292/pass.txt)

**Comment by jkosh44** [comment]
Another interesting observation, I had accidentally compiled `clusterd` with version `0.110.0-dev` and `environmentd` with version `0.109.0-dev`. Sometimes the test would pass and other times I would get an failure with an error message saying that the `clusterd` version was incompatible.

My hunch is that this is likely the same race condition. Perhaps `clusterd` has a 2MB limit somewhere that doesn't gracefully forward the error while `environmentd`'s limit does gracefully forward the error. Sometimes we hit the `clusterd` limit while other times we hit the `environmentd` limit.

**Comment by jkosh44** [comment]
One idea is that either `send` or `flush` return an `Err` in the below code block:

https://github.com/MaterializeInc/materialize/blob/9876be2cb47ffafd84185889cddb22c498bbdb1e/src/pgwire/src/protocol.rs#L290-L302

However I checked and they both return `Ok(())` when the test fails.

**Comment by jkosh44** [comment]
I'm going to take a step back from this issue. It looks like it's a separate issue from what customers are experiencing because the test actually is expecting the connection to be closed, it's just missing an error message.
