### ISSUE TITLE
thread 'tests::test_pg_regexp_split_array' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "FATAL", parsed_severity: None, code: SqlState(E42501), message: "unauthorized login to user 'postgres'"

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#23067]
### What version of Materialize are you using?

81fd8377b18e

### What is the issue?

```
thread 'tests::test_pg_regexp_split_array' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "FATAL", parsed_severity: None, code: SqlState(E42501), message: "unauthorized login to user 'postgres'", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: None, line: None, routine: None }) }', src/regexp/src/lib.rs:141:84
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/result.rs:1651:5
   3: <core::result::Result<postgres::client::Client, tokio_postgres::error::Error>>::unwrap
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/result.rs:1076:23
   4: mz_regexp::tests::test_pg_regexp_split_array::test_impl
             at ./src/lib.rs:141:26
   5: mz_regexp::tests::test_pg_regexp_split_array
             at ./src/lib.rs:135:5
   6: mz_regexp::tests::test_pg_regexp_split_array::{closure#0}
             at ./src/lib.rs:135:5
   7: <mz_regexp::tests::test_pg_regexp_split_array::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Seen in https://buildkite.com/materialize/tests/builds/68260#018bb46c-6c94-48e7-8798-2bb55e467355

**Comment by mjibson** [comment]
The problem here is "unauthorized login to user 'postgres'" and is something to do with the test harness that is supposed to have a working postgress installation available. This isn't a problem with regexp.

**Comment by def-** [comment]
Just seen again on main: https://buildkite.com/materialize/tests/builds/73613#018d30e8-e2e2-4b9f-9a0b-62f3436fa633

**Comment by teskje** [comment]
Also here: https://buildkite.com/materialize/tests/builds/75166#018d8858-4f68-4914-bd05-8b6f8938c0b3

**Comment by danhhz** [comment]
And here! https://buildkite.com/materialize/tests/builds/78590#018e524e-db4b-4f0a-be3b-5cba8242e071

**Comment by def-** [comment]
I checked the logs and couldn't find anything weir happening to Postgres. It is running fine before, and we are only seeing this issue in cargo-test. I thought maybe another test drops the "postgres" user, or changes its password, but I couldn't find an instance of that (based on the `unauthorized login to user 'postgres'`). So I'm out of ideas with how to progress with this.
