### ISSUE TITLE
thread '<unnamed>' panicked at 'overflow when adding duration to instant', library/std/src/time.rs:408:33 

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#23104]
### What version of Materialize are you using?

ec224d0c8d7d

### What is the issue?

Seen in https://buildkite.com/materialize/tests/builds/68380#018bb94a-9b7c-489b-90f3-7bf5c51b9d37

Rehydration upsert test fails and panics:
```
thread '<unnamed>' panicked at 'overflow when adding duration to instant', library/std/src/time.rs:408:33
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_failed
   3: <lgalloc::BackgroundWorker>::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Since it's the lgalloc background worker, which was just introduced, this is a regression.

**Comment by antiguru** [comment]
Lgalloc didn't make it into yesterday's cut, so it's only a release blocker for next week. Fix in https://github.com/antiguru/rust-lgalloc/pull/19.
