### ISSUE TITLE
parallel-workload: thread 'main' panicked at 'assertion failed: `(left == right)`

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#23146]
### What version of Materialize are you using?

1e19b74517

### What is the issue?

Seen in nightly during the weekend: https://buildkite.com/materialize/nightlies/builds/5150#018bc383-5add-4929-821b-55b1b4d3a09c
I'm not sure if this is a regression, since the failure is flaky:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Transaction { ... }`
 right: `Transaction { ... }`
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed::<mz_catalog::durable::transaction::Transaction, mz_catalog::durable::transaction::Transaction>
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:228:5
   4: <mz_catalog::durable::impls::shadow::ShadowCatalogState as mz_catalog::durable::DurableCatalogState>::transaction::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-017175357bd56887b-1/materialize/tests/src/catalog/src/durable/impls/shadow.rs:202:44
   5: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<mz_catalog::durable::transaction::Transaction, mz_catalog::durable::error::CatalogError>> + core::marker::Send>> as core::future::future::Future>::poll
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/future/future.rs:125:9
   6: <mz_adapter::catalog::Catalog>::open::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-017175357bd56887b-1/materialize/tests/src/adapter/src/catalog/open.rs:258:45
   7: <tracing::instrument::Instrumented<<mz_adapter::catalog::Catalog>::open::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
   8: <mz_adapter::catalog::Catalog>::open::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-017175357bd56887b-1/materialize/tests/src/adapter/src/catalog/open.rs:186:5
   9: mz_adapter::coord::serve::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-017175357bd56887b-1/materialize/tests/src/adapter/src/coord.rs:2078:10
  10: <mz_environmentd::Listeners>::serve::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-017175357bd56887b-1/materialize/tests/src/environmentd/src/lib.rs:567:10
  11: <tracing::instrument::Instrumented<<mz_environmentd::Listeners>::serve::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  12: <mz_environmentd::Listeners>::serve::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-017175357bd56887b-1/materialize/tests/src/environmentd/src/lib.rs:339:5
  13: environmentd::run::{closure#11}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-017175357bd56887b-1/materialize/tests/src/environmentd/src/bin/environmentd/main.rs:1000:14
  14: <tracing::instrument::Instrumented<environmentd::run::{closure#11}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  15: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  16: tokio::runtime::coop::with_budget::<core::task::poll::Poll<core::result::Result<mz_environmentd::Server, anyhow::Error>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  17: tokio::runtime::coop::budget::<core::task::poll::Poll<core::result::Result<mz_environmentd::Server, anyhow::Error>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  18: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  19: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  20: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  21: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::scheduler::multi_thread::MultiThread>::block_on<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}, core::result::Result<mz_environmentd::Server, anyhow::Error>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  22: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  23: <tokio::runtime::runtime::Runtime>::block_on::<environmentd::run::{closure#11}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/runtime.rs:349:50
  24: environmentd::run
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-017175357bd56887b-1/materialize/tests/src/environmentd/src/bin/environmentd/main.rs:930:18
  25: environmentd::main
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-017175357bd56887b-1/materialize/tests/src/environmentd/src/bin/environmentd/main.rs:625:23
  26: <fn() as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
```
Full assertion failure is huge: https://gist.github.com/def-/6e38fe91fa412524d752d66fe8575e11
Using `diff` the replica next_id is different:
```diff
22821c22821
< IdAllocKey { name: "replica" }: IdAllocValue { next_id: 141 },
---
> IdAllocKey { name: "replica" }: IdAllocValue { next_id: 140 },
```
I believe this might be related to the shadow catalog introduced in https://github.com/MaterializeInc/materialize/pull/23086

**Comment by jkosh44** [comment]
@def- Is there a good way of figuring out what queries were being run around the time of the panic?

**Comment by def-** [comment]
The parallel-workload-queries.log contains all queries which were run:
[parallel-workload-queries.log.zip](https://github.com/MaterializeInc/materialize/files/13337596/parallel-workload-queries.log.zip)

But I think the key is that this happened in the Kill scenario which restarts Mz at random times.

**Comment by jkosh44** [comment]
Ah, ok, I think I know the issue. The Shadow catalog does the following on every catalog operation:
1. Execute the operation on catalog A.
2. Execute the operation on catalog B.
3. Compare the results.

So if we are randomly killing materialize then we can end up in a situation where the operation happens on catalog A but not catalog B and we will see an inconsistency between the two catalogs. The shadow catalog is meant to be used to compare two catalog implementations, so it's OK that it has this deficiency. Given that, I don't think we should be using the shadow catalog in this test. Are there other tests where we randomly kill materialize?

**Comment by def-** [comment]
Also happened in cluster test here: https://buildkite.com/materialize/tests/builds/68627#018bcad1-2d9c-461d-9a28-b34fb92586b9 It also kills materialized to trigger a reconciliation on clusterd.
