### ISSUE TITLE
thread 'timely:work-1' panicked at 'index out of bounds: the len is 0 but the index is 0', src/expr/src/scalar/mod.rs:1768:41

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#23160]
### What version of Materialize are you using?

84b34fd42c

### What is the issue?

```
thread 'thread 'timely:work-1timely:work-0' panicked at '' panicked at 'index out of bounds: the len is 0 but the index is 0index out of bounds: the len is 0 but the index is 0', ', src/expr/src/scalar/mod.rssrc/expr/src/scalar/mod.rs::17681768::4141

stack backtrace:
   0: rust_begin_unwind
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_bounds_check
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:162:5
   3: <mz_expr::scalar::MirScalarExpr>::typ
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/expr/src/scalar/mod.rs:1768:41
   4: mz_compute::render::context::derive_key_val_types
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/render/context.rs:1100:28
   0: rust_begin_unwind
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_bounds_check
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:162:5
   3: <mz_expr::scalar::MirScalarExpr>::typ
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/expr/src/scalar/mod.rs:1768:41
   4: mz_compute::render::context::derive_key_val_types
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/render/context.rs:1100:28
   5: <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>>::ensure_collections
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/render/context.rs:1029:21
   6: <mz_compute::render::context::Context<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>>::render_plan
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/render/mod.rs:969:17
   7: <mz_compute::render::context::Context<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>>::build_object
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/render/mod.rs:468:22
   5: <mz_compute::render::context::CollectionBundle<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>>::ensure_collections
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/render/context.rs:1029:21
   6: <mz_compute::render::context::Context<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>>::render_plan
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/render/mod.rs:969:17
   7: <mz_compute::render::context::Context<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>>>::build_object
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/render/mod.rs:468:22
   8: mz_compute::render::build_compute_dataflow::<timely_communication::allocator::generic::Generic>::{closure#3}::{closure#3}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/render/mod.rs:363:21
   9: <timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp> as timely::dataflow::scopes::Scope>::scoped::<mz_repr::timestamp::Timestamp, (), mz_compute::render::build_compute_dataflow<timely_communication::allocator::generic::Generic>::{closure#3}::{closure#3}>
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/timely/src/dataflow/scopes/child.rs:129:13
  10: <timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp> as timely::dataflow::scopes::Scope>::region_named::<(), mz_compute::render::build_compute_dataflow<timely_communication::allocator::generic::Generic>::{closure#3}::{closure#3}>
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/timely/src/dataflow/scopes/mod.rs:187:9
  11: mz_compute::render::build_compute_dataflow::<timely_communication::allocator::generic::Generic>::{closure#3}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/render/mod.rs:330:27
  12: <timely::worker::Worker<timely_communication::allocator::generic::Generic>>::dataflow_core::<mz_repr::timestamp::Timestamp, (), mz_compute::render::build_compute_dataflow<timely_communication::allocator::generic::Generic>::{closure#3}, alloc::boxed::Box<()>>
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/timely/src/worker.rs:639:13
   8: mz_compute::render::build_compute_dataflow::<timely_communication::allocator::generic::Generic>::{closure#3}::{closure#3}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/render/mod.rs:363:21
   9: <timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp> as timely::dataflow::scopes::Scope>::scoped::<mz_repr::timestamp::Timestamp, (), mz_compute::render::build_compute_dataflow<timely_communication::allocator::generic::Generic>::{closure#3}::{closure#3}>
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/timely/src/dataflow/scopes/child.rs:129:13
  10: <timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp> as timely::dataflow::scopes::Scope>::region_named::<(), mz_compute::render::build_compute_dataflow<timely_communication::allocator::generic::Generic>::{closure#3}::{closure#3}>
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/timely/src/dataflow/scopes/mod.rs:187:9
  11: mz_compute::render::build_compute_dataflow::<timely_communication::allocator::generic::Generic>::{closure#3}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/render/mod.rs:330:27
  12: <timely::worker::Worker<timely_communication::allocator::generic::Generic>>::dataflow_core::<mz_repr::timestamp::Timestamp, (), mz_compute::render::build_compute_dataflow<timely_communication::allocator::generic::Generic>::{closure#3}, alloc::boxed::Box<()>>
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/timely/src/worker.rs:639:13
  13: mz_compute::render::build_compute_dataflow::<timely_communication::allocator::generic::Generic>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/render/mod.rs:193:5
  13: mz_compute::render::build_compute_dataflow::<timely_communication::allocator::generic::Generic>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/render/mod.rs:193:5
  14: <mz_compute::compute_state::ActiveComputeState<timely_communication::allocator::generic::Generic>>::handle_create_dataflow
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/compute_state.rs:282:9
  15: <mz_compute::compute_state::ActiveComputeState<timely_communication::allocator::generic::Generic>>::handle_compute_command
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/compute_state.rs:181:41
  16: <mz_compute::server::Worker<timely_communication::allocator::generic::Generic>>::handle_command
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/server.rs:424:9
  17: <mz_compute::server::Worker<timely_communication::allocator::generic::Generic>>::reconcile
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/server.rs:693:13
  18: <mz_compute::server::Worker<timely_communication::allocator::generic::Generic>>::run_client
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/server.rs:364:25
  19: <mz_compute::server::Worker<timely_communication::allocator::generic::Generic>>::setup_channel_and_run_client
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/server.rs:350:9
  14: <mz_compute::compute_state::ActiveComputeState<timely_communication::allocator::generic::Generic>>::handle_create_dataflow
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/compute_state.rs:282:9
  15: <mz_compute::compute_state::ActiveComputeState<timely_communication::allocator::generic::Generic>>::handle_compute_command
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/compute_state.rs:181:41
  16: <mz_compute::server::Worker<timely_communication::allocator::generic::Generic>>::handle_command
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/server.rs:424:9
  17: <mz_compute::server::Worker<timely_communication::allocator::generic::Generic>>::reconcile
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/server.rs:693:13
  18: <mz_compute::server::Worker<timely_communication::allocator::generic::Generic>>::run_client
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/server.rs:364:25
  19: <mz_compute::server::Worker<timely_communication::allocator::generic::Generic>>::setup_channel_and_run_client
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/server.rs:350:9
environmentd: 2023-11-13T18:03:10.379460Z  WARN librdkafka: warning: CONFWARN [thrd:app]: Configuration property isolation.level is a consumer property and will be ignored by this producer instance
  20: <mz_compute::server::Worker<timely_communication::allocator::generic::Generic>>::run
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/server.rs:214:21
  21: <mz_compute::server::Config as mz_cluster::types::AsRunnableWorker<mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse>>::build_and_run::<timely_communication::allocator::generic::Generic>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/server.rs:195:9
  22: <mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse, timely::scheduling::activate::SyncActivator>, mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse>, mz_compute::server::Config, mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse>>::build_timely::{closure#0}::{closure#1}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/cluster/src/server.rs:191:13
  23: timely::execute::execute_from::<timely_communication::allocator::generic::GenericBuilder, (), <mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse, timely::scheduling::activate::SyncActivator>, mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse>, mz_compute::server::Config, mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse>>::build_timely::{closure#0}::{closure#1}>::{closure#0}
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/timely/src/execute.rs:388:22
  24: timely_communication::initialize::initialize_from::<timely_communication::allocator::generic::GenericBuilder, (), timely::execute::execute_from<timely_communication::allocator::generic::GenericBuilder, (), <mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse, timely::scheduling::activate::SyncActivator>, mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse>, mz_compute::server::Config, mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse>>::build_timely::{closure#0}::{closure#1}>::{closure#0}>::{closure#0}
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/communication/src/initialize.rs:316:33
  20: <mz_compute::server::Worker<timely_communication::allocator::generic::Generic>>::run
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/server.rs:214:21
  21: <mz_compute::server::Config as mz_cluster::types::AsRunnableWorker<mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse>>::build_and_run::<timely_communication::allocator::generic::Generic>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/compute/src/server.rs:195:9
  22: <mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse, timely::scheduling::activate::SyncActivator>, mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse>, mz_compute::server::Config, mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse>>::build_timely::{closure#0}::{closure#1}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-063fca55c6ebccdab-1/materialize/tests/src/cluster/src/server.rs:191:13
  23: timely::execute::execute_from::<timely_communication::allocator::generic::GenericBuilder, (), <mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse, timely::scheduling::activate::SyncActivator>, mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse>, mz_compute::server::Config, mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse>>::build_timely::{closure#0}::{closure#1}>::{closure#0}
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/timely/src/execute.rs:388:22
  24: timely_communication::initialize::initialize_from::<timely_communication::allocator::generic::GenericBuilder, (), timely::execute::execute_from<timely_communication::allocator::generic::GenericBuilder, (), <mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse, timely::scheduling::activate::SyncActivator>, mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse>, mz_compute::server::Config, mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse>>::build_timely::{closure#0}::{closure#1}>::{closure#0}>::{closure#0}
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/53adc68/communication/src/initialize.rs:316:33
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
(The interleaved backtraces aren't great)

Seen in https://buildkite.com/materialize/nightlies/builds/5169#018bc9cb-b8a3-4c89-9822-0da2d80c4142, but it might not be related to the PR (https://github.com/MaterializeInc/materialize/pull/22945, retriggered to see if it's a flake). Marking as release blocker since there was work on renaming clusters recently and this failed in rename_cluster.py:23:
```
> ALTER CLUSTER rename_cluster2 RENAME TO rename_cluster_new2;
```

ci-regexp: index out of bounds: the len is 0 but the index is 0

**Comment by def-** [comment]
Happened again in the rerun, which is highly suspicious if this is a flake, never seen the failure before. We did also change stuff in Kafka, so maybe the timing is now slightly different and makes the test hit the error.

But it didn't fail in the rename-cluster test this time, but 10 seconds later. Maybe this is just a compute issue

**Comment by def-** [comment]
@vmarcos do you have any idea since the code in context.rs was introduced in 57b24b6c14a?

**Comment by def-** [comment]
Also seen in another PR (https://buildkite.com/materialize/nightlies/builds/5167), so this seems to have started failing in main recently. If this is not flaky, then those are the changes which could be responsible: https://github.com/MaterializeInc/materialize/compare/412978effe...8f2feab3aca99a875a9b8ddeb2e38ccc28b0e3e0 Oooh, this starts failing because we bumped the version in https://github.com/MaterializeInc/materialize/commit/a590ae2f8df16c78543e020d0bde90ec168efee0

The actual panic happens after we upgrade to v0.75.3:
```
Starting Mz using image materialize/materialized:v0.75.3
```
We just never caught this before, but it's a deterministic failure. One question is if this is already fixed in main.

**Comment by def-** [comment]
This is already fixed in main, as seen in https://buildkite.com/materialize/nightlies/builds/5177
I'll provide a workaround to make the test green.
