### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AlreadyReg'

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#23170]
### What version of Materialize are you using?

65b6070fbb

### What is the issue?

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AlreadyReg', /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02debd5e8d50d52f6-1/materialize/tests/src/ore/src/metrics.rs:229:58
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/result.rs:1651:5
   3: <core::result::Result<(), prometheus::errors::Error>>::unwrap
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/result.rs:1076:23
   4: <mz_ore::metrics::MetricsRegistry>::register::<prometheus::gauge::GenericGauge<prometheus::atomic64::AtomicU64>>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02debd5e8d50d52f6-1/materialize/tests/src/ore/src/metrics.rs:229:9
   5: <mz_adapter::config::Metrics>::register_into
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02debd5e8d50d52f6-1/materialize/tests/src/adapter/src/config/mod.rs:88:36
   6: <mz_adapter::config::SystemParameterSyncFactory>::new
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02debd5e8d50d52f6-1/materialize/tests/src/adapter/src/config/mod.rs:63:22
   7: <mz_adapter::catalog::Catalog>::initialize_state::{closure#0}::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02debd5e8d50d52f6-1/materialize/tests/src/adapter/src/catalog/open.rs:383:21
   8: <core::option::Option<mz_catalog::config::SystemParameterSyncConfig>>::map::<mz_adapter::config::SystemParameterSyncFactory, <mz_adapter::catalog::Catalog>::initialize_state::{closure#0}::{closure#0}::{closure#0}>
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/option.rs:1075:29
   9: <mz_adapter::catalog::Catalog>::initialize_state::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02debd5e8d50d52f6-1/materialize/tests/src/adapter/src/catalog/open.rs:380:13
  10: <tracing::instrument::Instrumented<<mz_adapter::catalog::Catalog>::initialize_state::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  11: <mz_adapter::catalog::Catalog>::initialize_state::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02debd5e8d50d52f6-1/materialize/tests/src/adapter/src/catalog/open.rs:183:5
  12: <mz_adapter::catalog::Catalog>::open::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02debd5e8d50d52f6-1/materialize/tests/src/adapter/src/catalog/open.rs:879:64
  13: <tracing::instrument::Instrumented<<mz_adapter::catalog::Catalog>::open::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  14: <mz_adapter::catalog::Catalog>::open::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02debd5e8d50d52f6-1/materialize/tests/src/adapter/src/catalog/open.rs:865:5
  15: mz_adapter::coord::serve::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02debd5e8d50d52f6-1/materialize/tests/src/adapter/src/coord.rs:2076:10
  16: <mz_environmentd::Listeners>::serve::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02debd5e8d50d52f6-1/materialize/tests/src/environmentd/src/lib.rs:570:10
  17: <tracing::instrument::Instrumented<<mz_environmentd::Listeners>::serve::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  18: <mz_environmentd::Listeners>::serve::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02debd5e8d50d52f6-1/materialize/tests/src/environmentd/src/lib.rs:339:5
  19: environmentd::run::{closure#11}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02debd5e8d50d52f6-1/materialize/tests/src/environmentd/src/bin/environmentd/main.rs:1000:14
  20: <tracing::instrument::Instrumented<environmentd::run::{closure#11}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  21: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  22: tokio::runtime::coop::with_budget::<core::task::poll::Poll<core::result::Result<mz_environmentd::Server, anyhow::Error>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  23: tokio::runtime::coop::budget::<core::task::poll::Poll<core::result::Result<mz_environmentd::Server, anyhow::Error>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  24: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  25: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  26: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  27: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::scheduler::multi_thread::MultiThread>::block_on<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}, core::result::Result<mz_environmentd::Server, anyhow::Error>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  28: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  29: <tokio::runtime::runtime::Runtime>::block_on::<environmentd::run::{closure#11}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/runtime.rs:349:50
  30: environmentd::run
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02debd5e8d50d52f6-1/materialize/tests/src/environmentd/src/bin/environmentd/main.rs:930:18
  31: environmentd::main
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-02debd5e8d50d52f6-1/materialize/tests/src/environmentd/src/bin/environmentd/main.rs:625:23
  32: <fn() as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Seen in https://buildkite.com/materialize/nightlies/builds/5172

ci-regexp: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AlreadyReg'

@aalexandrov Do you understand what's happening here?

**Comment by def-** [comment]
@jkosh44 Using nightly I have verified that this is caused by your change https://github.com/MaterializeInc/materialize/pull/23120
Failing on your PR: https://buildkite.com/materialize/nightlies/builds/5178
Successful on the main state your PR is based on: https://buildkite.com/materialize/nightlies/builds/5179

**Comment by nrainer-materialize** [comment]
Also observed on Sentry.

**Comment by aalexandrov** [comment]
It seems that after #5178 the `Metrics::register_into(registry)` call here

https://github.com/MaterializeInc/materialize/blob/ab61ceeabc95a703f7a699a164213d78111f7463/src/adapter/src/config/mod.rs#L50-L68

started failing. This happens because this helper from `mz_ore::metrics::MetricsRegistry`

https://github.com/MaterializeInc/materialize/blob/ab61ceeabc95a703f7a699a164213d78111f7463/src/ore/src/metrics.rs#L223-L231

expects the `self.inner.register(...)` result to be `Ok`, but for some reason in tests we now register the same metric twice in the same process run, and for the second call we get `Err(AlreadyReg)`.

**Comment by aalexandrov** [comment]
The current code in `main` has two `SystemParameterSyncFactory::new(...)` call sites:

in`Listeners::serve`

https://github.com/MaterializeInc/materialize/blob/ab61ceeabc95a703f7a699a164213d78111f7463/src/environmentd/src/lib.rs#L522-L529

and in `Catalog::initialize_state`

https://github.com/aalexandrov/materialize/blob/ab61ceeabc95a703f7a699a164213d78111f7463/src/adapter/src/catalog/open.rs#L379-L391

With the current `new` implementation we cannot have two instances for the same `MetricsRegistry` instance in the same process.
