### ISSUE TITLE
parallel-workload: environmentd becomes stuck without any load on clusterds

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#23254]
### What version of Materialize are you using?

https://github.com/MaterializeInc/materialize/pull/23251

### What is the issue?

Split out from https://github.com/MaterializeInc/materialize/issues/22717, which is now about environmentd becoming unresponsive when clusterds are overloaded. I can also get envd unresponsive with 0% load:

After 30 seconds of running on my PR https://github.com/MaterializeInc/materialize/pull/23251 with `while true; do bin/mzcompose --find parallel-workload down && bin/mzcompose --find parallel-workload run default --threads=16 --runtime=60 --complexity=ddl --fast-startup || break; done` there is no more progress. All clusterd and environmentd threads are at ~0% cpu usage. `select 1` is stuck.
[parallel-workload-queries.log](https://github.com/MaterializeInc/materialize/files/13380254/parallel-workload-queries.log)
[services.log](https://github.com/MaterializeInc/materialize/files/13380259/services.log)
@ParkMyCar Since you already looked into #22717 a bit, are you interested in picking this?

**Comment by def-** [comment]
Another example seen on https://github.com/MaterializeInc/materialize/pull/23272
```
bin/mzcompose --find parallel-workload down && bin/mzcompose --find parallel-workload run default --threads=200 --runtime=1000 --complexity=ddl --scenario=rename
[...]
worker_0 still running: ALTER SCHEMA "db-pw-1700241728-0"."s-3-1" RENAME TO "s-3-2";
worker_13 still running: DROP SINK "db-pw-1700241728-0"."s-0-5"."sink-6-1";
worker_18 still running: CREATE ROLE role4;
worker_24 still running: ALTER SCHEMA "db-pw-1700241728-0"."s-0-3" RENAME TO "s-0-4";
worker_36 still running: rollback
worker_45 still running: rollback
worker_57 still running: ALTER VIEW "db-pw-1700241728-0"."s-0-3"."v-5-4" RENAME TO "v-5-5";
worker_64 still running: ALTER TABLE "db-pw-1700241728-0"."s-4-5"."t-16" RENAME TO "t-16-1";
worker_106 still running: GRANT SELECT ON "db-pw-1700241728-0"."s-2-5"."t-6-4" TO role2;
worker_111 still running: CREATE SCHEMA "db-pw-1700241728-1"."s-10";
worker_112 still running: CREATE MATERIALIZED VIEW "db-pw-1700241728-0"."s-4-5"."v-33" WITH (ASSERT NOT NULL "key0-""db-pw-1700241728-0"".""s-1-7"".table7", ASSERT NOT NULL "value1-""db-pw-1700241728-0"".""s-1-7"".table7") AS SELECT "db-pw-1700241728-0"."s-1-7".table7.value1 AS "value1-""db-pw-1700241728-0"".""s-1-7"".table7", "db-pw-1700241728-0"."s-1-7".table7.value0 AS "value0-""db-pw-1700241728-0"".""s-1-7"".table7", "db-pw-1700241728-0"."s-1-7".table7.key0 AS "key0-""db-pw-1700241728-0"".""s-1-7"".table7" FROM "db-pw-1700241728-0"."s-1-7".table7;
worker_140 still running: rollback
worker_154 still running: ALTER SINK "db-pw-1700241728-0"."s-1-8"."sink-15" RENAME TO "sink-15-1";
worker_158 still running: ALTER TABLE "db-pw-1700241728-0"."s-0-3"."t-9-3" RENAME TO "t-9-4";
worker_159 still running: ALTER TABLE "db-pw-1700241728-0"."s-0-3"."t-9-2" RENAME TO "t-9-3";
worker_183 still running: REVOKE UPDATE ON "db-pw-1700241728-0"."s-0-4"."v-15-1" FROM role2;
worker_199 still running: ALTER TABLE "db-pw-1700241728-0"."s-0-3"."t-1-4" RENAME TO "t-1-5";
Threads have not stopped within 5 minutes, exiting hard
```
There is a whole lot of renames being stuck, I'm wondering if it's related to renaming.
[parallel-workload-queries.log.zip](https://github.com/MaterializeInc/materialize/files/13395158/parallel-workload-queries.log.zip)
After 15 minutes the coordinator became unstuck on its own again: [services.log](https://github.com/MaterializeInc/materialize/files/13395171/services.log) Not sure if this should be considered the same as the original issue or is another issue.

**Comment by def-** [comment]
This one in #23272 is probably more representative:
```
$ bin/mzcompose --find parallel-workload down && bin/mzcompose --find parallel-workload run default --threads=32 --runtime=1000 --complexity=ddl --scenario=cancel
[...]
worker_0 still running: commit
worker_1 still running: commit
worker_2 still running: commit
worker_3 still running: SELECT "db-pw-1700246369-0"."s-1"."wh-7".timestamp, "db-pw-1700246369-0"."s-1"."wh-7".ih0, "db-pw-1700246369-0"."s-1"."wh-7".body, COUNT("db-pw-1700246369-0"."s-1"."wh-7".ih2) OVER (PARTITION BY "db-pw-1700246369-0"."s-1"."wh-7".timestamp ORDER BY "db-pw-1700246369-0"."s-1"."wh-7".timestamp) FROM "db-pw-1700246369-0"."s-1"."wh-7"  LIMIT 1;
worker_4 still running: POST http://localhost:6976/api/webhook/db-pw-1700246369-1/s-3/wh-10 Headers: ih0: b'"GEgZilSWtfkS08ah18sPtRuqoI5LyRqAjCwl3qAqUqIjUKt81oUy0yNgft37hLlXdajEd6plTSYSJOpCDpmHz1SJazOyjCtiPli5"', ih1: b'"sVPux9CMFMj2kJABY778dMWrkKjYbemMwb9ETZihRpCfeyItQ2TpNrFPfTzZ0CjPeb10anS9cSKXtTFKgUbYNQjRkDwz75geMPxz"', ih2: b'"dhCLq5NwJshHNUi5NvmVSS6Joux9KgTYEYxrE8X3EppHDlwZIjbnWLwL7bhhY8PEvBvl0FuCScZgW4RwUBUic7dc34mFC0P3gjBb"' Body: b'TmKI5NZvQ1qfTQopWskdjAYGLnsJVWK9sBGTQkAakr4VYCftggZbSzkoPPC5UCF2GbKOyS0ctxkFFUAgv76Wvxdu4uwGjhfQTDMV'
worker_5 still running: rollback
worker_6 still running: rollback
worker_7 still running: CREATE TABLE "db-pw-1700246369-8"."s-15"."t-41"("c-0-bytea" bytea DEFAULT 'p7u2f3PmS6QBIFZBOemH9VWzIkzfmvrF2ixw3CwVBPuJsZ5UfnnEfEPRuPPc5UYEFRcuqG4wCKFVGLxhaKLcEQ8KVoQtYkYBrFFe',
    "c-1-map[text=>text]" map[text=>text] DEFAULT '{key0 => 65, key1 => 3, key2 => 19, key3 => 34, key4 => -55, key5 => 95, key6 => 29, key7 => -3, key8 => -13, key9 => -92, key10 => -45, key11 => -21, key12 => -60, key13 => 64, key14 => -27, key15 => -22, key16 => 4, key17 => -2, key18 => -7, key19 => -1}'::map[text=>text] NOT NULL,
    "c-2-float8" float8,
    "c-3-map[text=>text]" map[text=>text] DEFAULT '{key0 => -1, key1 => -6, key2 => -80, key3 => -86, key4 => -47, key5 => -87, key6 => -70, key7 => 38, key8 => -69, key9 => -9, key10 => 4, key11 => -82, key12 => 38, key13 => 5, key14 => 13, key15 => -58, key16 => -39, key17 => 20, key18 => 61, key19 => 99}'::map[text=>text],
    "c-4-bytea" bytea DEFAULT 'rjkpOK5JUy73iig1pAU0QK0CoWtitArkAQvsMP8bUcPIO1tgMN4XTdKswQwh9v9Yc2ZIUq6XuQiWNckk3Zv3IbI1b0E3IJw3EcLG',
    "c-5-int" int DEFAULT -131434909 NOT NULL,
    "c-6-jsonb" jsonb DEFAULT '{"key0": "-94", "key1": "-52", "key2": "2", "key3": "-71", "key4": "-58", "key5": "-28", "key6": "-34", "key7": "-39", "key8": "11", "key9": "-56", "key10": "-89", "key11": "91", "key12": "91", "key13": "49", "key14": "-73", "key15": "88", "key16": "-35", "key17": "36", "key18": "-77", "key19": "-7"}'::jsonb NOT NULL,
    "c-7-float8" float8 DEFAULT 99161317113.77202 NOT NULL,
    "c-8-bytea" bytea DEFAULT 'F6yLiE2VUV5xM53MfDJnQ3ELpGe4GePC2bWLx506BfXzxZcOZuQaS9htd7COgM668YHfRkAu9IU7h0HASylTN8P1K7gpAqf0kqnG' NOT NULL,
    "c-9-jsonb" jsonb);
worker_8 still running: UPDATE "db-pw-1700246369-0"."s-0"."t-13" SET "c-2-bytea" = 'd3QULXZpDrqyZYSc9PUOwGhwNCUNOcbJCscDc2G4YkgDNqx8DLAeQrFZSi3gevwatkUpUnfpGYETuRyFrVRvEW7pwJGCzTER9O2p' WHERE "c-0-float4" = 85760331776.14458;
worker_9 still running: commit
worker_10 still running: commit
worker_11 still running: FETCH ALL c WITH (timeout='5s');
worker_12 still running: commit
worker_13 still running: UPDATE "db-pw-1700246369-0"."s-0"."t-1" SET "c-0-jsonb" = '{"key0": "-37", "key1": "-43", "key2": "-35", "key3": "82", "key4": "29", "key5": "26", "key6": "-83", "key7": "-65", "key8": "-8", "key9": "-64", "key10": "72", "key11": "-39", "key12": "80", "key13": "88", "key14": "-48", "key15": "-52", "key16": "41", "key17": "-10", "key18": "90", "key19": "-29"}'::jsonb WHERE "c-0-jsonb" = '{"key0": "-1", "key1": "-99", "key2": "9", "key3": "96", "key4": "100", "key5": "-26", "key6": "81", "key7": "33", "key8": "-61", "key9": "8", "key10": "-49", "key11": "-34", "key12": "-35", "key13": "37", "key14": "10", "key15": "-42", "key16": "34", "key17": "-44", "key18": "-32", "key19": "36"}'::jsonb;
worker_14 still running: commit
worker_15 still running: commit
worker_16 still running: FETCH ALL c WITH (timeout='9s');
worker_17 still running: SELECT "db-pw-1700246369-0"."s-0"."t-10"."c-6-text", "db-pw-1700246369-0"."s-1"."v-28"."value10-""db-pw-1700246369-0"".""s-0"".table4", "db-pw-1700246369-0"."s-1"."v-28"."value18-""db-pw-1700246369-0"".""s-0"".table4", "db-pw-1700246369-0"."s-1"."v-28"."value7-""db-pw-1700246369-0"".""s-0"".table4", "db-pw-1700246369-0"."s-0"."t-10"."c-3-bytea", "db-pw-1700246369-0"."s-1"."v-28"."value13-""db-pw-1700246369-0"".""s-0"".table4", "db-pw-1700246369-0"."s-1"."v-28"."value6-""db-pw-1700246369-0"".""s-0"".table4", "db-pw-1700246369-0"."s-1"."v-28"."value2-""db-pw-1700246369-0"".""s-0"".table4", "db-pw-1700246369-0"."s-1"."v-28"."value12-""db-pw-1700246369-0"".""s-0"".table4", "db-pw-1700246369-0"."s-1"."v-28"."value1-""db-pw-1700246369-0"".""s-0"".table4", "db-pw-1700246369-0"."s-1"."v-28"."value9-""db-pw-1700246369-0"".""s-0"".table4", "db-pw-1700246369-0"."s-1"."v-28"."value16-""db-pw-1700246369-0"".""s-0"".table4", "db-pw-1700246369-0"."s-1"."v-28"."value8-""db-pw-1700246369-0"".""s-0"".table4", "db-pw-1700246369-0"."s-1"."v-28"."value5-""db-pw-1700246369-0"".""s-0"".table4", "db-pw-1700246369-0"."s-1"."v-28"."value4-""db-pw-1700246369-0"".""s-0"".table4", "db-pw-1700246369-0"."s-1"."v-28"."value3-""db-pw-1700246369-0"".""s-0"".table4", "db-pw-1700246369-0"."s-1"."v-28"."value14-""db-pw-1700246369-0"".""s-0"".table4", "db-pw-1700246369-0"."s-1"."v-28"."value11-""db-pw-1700246369-0"".""s-0"".table4", "db-pw-1700246369-0"."s-0"."t-10"."c-1-bigint", "db-pw-1700246369-0"."s-0"."t-10"."c-2-boolean", "db-pw-1700246369-0"."s-1"."v-28"."value0-""db-pw-1700246369-0"".""s-0"".table4", "db-pw-1700246369-0"."s-1"."v-28"."value15-""db-pw-1700246369-0"".""s-0"".table4" FROM "db-pw-1700246369-0"."s-0"."t-10" JOIN "db-pw-1700246369-0"."s-1"."v-28" ON "db-pw-1700246369-0"."s-0"."t-10"."c-5-bigint" = "db-pw-1700246369-0"."s-1"."v-28"."value15-""db-pw-1700246369-0"".""s-0"".table4" LIMIT 1;
worker_18 still running: FETCH ALL c WITH (timeout='9s');
worker_19 still running: commit
worker_20 still running: POST http://localhost:6976/api/webhook/db-pw-1700246369-0/s-1/wh-11 Headers: signature: b'"vCuSB12nyUHE4WgH4p1mmmRaDGp7Memsjumu58YeF9mh4KpfnX5QONsI5ghX4XZDVEVyG61zemzXvez5fsk0PByRd5ROr7gdf9et"', x-event-type: b'"x4zwxwIRBgVI8DsSK0axZE9t1LnqCMfrjXzPzxJrMNaozXvM5PeCiS0mxeMybEq0oN1XmhXtKwSwa0Wumtoh9K9OhkY8286VtOrX"', x-mz-api-key: b'"LYT52ZDgmUX7DaBsWSdUr0vjMRR7b4XW29mDqeJoo6gmlk5K4KddqaqZsRKrJNCDrElR8w0AdjGlWoWDyAWDx9t2pekEY44v0MYt"', timestamp: 2023-11-17 18:47:57.967406 Body: b'{"key0": "-34", "key1": "-45", "key2": "12", "key3": "46", "key4": "14", "key5": "43", "key6": "41", "key7": "-26", "key8": "22", "key9": "-54", "key10": "97", "key11": "-62", "key12": "-20", "key13": "15", "key14": "87", "key15": "82", "key16": "85", "key17": "9", "key18": "12", "key19": "-100"}'
worker_21 still running: commit
worker_22 still running: commit
worker_23 still running: SELECT "db-pw-1700246369-0"."s-4"."v-42"."c-5-boolean-""db-pw-1700246369-0"".""s-0"".""t-5""", COUNT("db-pw-1700246369-0"."s-4"."v-42"."c-1-smallint-""db-pw-1700246369-0"".""s-0"".""t-5""") OVER (PARTITION BY "db-pw-1700246369-0"."s-4"."v-42"."c-1-smallint-""db-pw-1700246369-0"".""s-0"".""t-5""" ORDER BY "db-pw-1700246369-0"."s-4"."v-42"."c-2-smallint-""db-pw-1700246369-0"".""s-0"".""t-5""") FROM "db-pw-1700246369-0"."s-4"."v-42"  LIMIT 1;
worker_24 still running: rollback
worker_25 still running: select
  (pg_catalog.pg_backend_pid()) & (subq_2."c4") as c0,
  subq_2."c0" as c1,
  subq_2."c2" as c2
from
  (select
        subq_1."c1" as c0,
        case when false then subq_1."c1" else subq_1."c1" end
           as c1,
        subq_1."c0" as c2,
        subq_1."c1" as c3,
        subq_1."c1" as c4,
        subq_1."c0" as c5,
        subq_1."c1" as c6,
        (case when true then TIMESTAMPTZ '2023-01-01 01:23:45+06' else TIMESTAMPTZ '2023-01-01 01:23:45+06' end
            ) - (mz_catalog.mz_uptime()) as c7,
        subq_1."c0" as c8,
        mz_internal.mz_normalize_object_name(
          CAST(
            pg_catalog.max(
              CAST(null::text as text)) over (partition by subq_1."c0" order by subq_1."c0",subq_1."c0") as text)) as c9,
        mz_internal.mz_role_oid_memberships() as c10
      from
        (select
              subq_0."c0" as c0,
              subq_0."c0" as c1
            from
              (select
                    92 as c0,
                    94 as c1
                  from
                    "db-pw-1700246369-0"."s-0"."t-8" as ref_1
                  where ((TIMESTAMP(0) '0001-01-01 00:00:00' - INTERVAL '4713 YEARS')) < (TIMESTAMP '2023-01-01 01:23:45')
                  limit 169) as subq_0
            where (2::uint4) = (null::uint4)
            limit 108) as subq_1
      where (mz_catalog.mz_uptime()) < ((pg_catalog.current_timestamp()) - (TIMESTAMPTZ '2023-01-01 01:23:45+06'))) as subq_2
where (true)
  and ((((case when true then INTERVAL '2147483647 MONTHS' else INTERVAL '2147483647 MONTHS' end
          ) + (TIME '01:23:45')) <= ((cast(nullif(TIME '01:23:45',
          TIME '00:00:00') as time)) + (case when false then INTERVAL '1' MINUTE else INTERVAL '1' MINUTE end
          )))
    and ((case when (null::float8) >= ('1E+307'::float8) then case when ((1::mz_timestamp) <> (2::mz_timestamp))
            or (((null::name) <= (1::name))
              or ((null::numeric) <= (null::numeric))) then numrange(0,0) else numrange(0,0) end
           else case when ((1::mz_timestamp) <> (2::mz_timestamp))
            or (((null::name) <= (1::name))
              or ((null::numeric) <= (null::numeric))) then numrange(0,0) else numrange(0,0) end
           end
        ) && (numrange(0,0))));
worker_26 still running: commit
worker_27 still running: commit
worker_28 still running: SELECT * FROM "db-pw-1700246369-0"."s-0"."wh-1" JOIN "db-pw-1700246369-0"."s-0"."v-4" ON "db-pw-1700246369-0"."s-0"."wh-1".body = "db-pw-1700246369-0"."s-0"."v-4"."c-7-jsonb-""db-pw-1700246369-0"".""s-0"".""t-2""" LIMIT 1;
worker_29 still running: SET TRANSACTION_ISOLATION TO 'SERIALIZABLE';
worker_30 still running: SELECT * FROM "db-pw-1700246369-0"."s-0"."v-9"  LIMIT 1;
worker_31 still running: commit
cancel still running: SELECT pg_cancel_backend(2); (Canceling worker_22)
Threads have not stopped within 5 minutes, exiting hard
```
[parallel-workload-queries.log](https://github.com/MaterializeInc/materialize/files/13395564/parallel-workload-queries.log)
[services.log](https://github.com/MaterializeInc/materialize/files/13395565/services.log)
gdb dump: https://gist.github.com/def-/6cfec03938dea0c89d7d13f190bb8b5f
CPU usage is low and yet environmentd never became usable again (`select 1` is still stuck after 20 min)

**Comment by ParkMyCar** [comment]
@def- I'm trying to run the 
```
bin/mzcompose --find parallel-workload down && bin/mzcompose --find parallel-workload run default --threads=32 --runtime=1000 --complexity=ddl --scenario=cancel
```

scenario, but very quickly I hit this error

```
parsing /dev/fd/3: Top-level object must be a mapping
Retrying ...
parsing /dev/fd/3: Top-level object must be a mapping
parsing /dev/fd/3: Top-level object must be a mapping
parsing /dev/fd/3: Top-level object must be a mapping
Retrying ...
Retrying ...
Retrying ...
parsing /dev/fd/3: Top-level object must be a mapping
Retrying ...
Exception in thread worker_27:
Traceback (most recent call last):
  File "/Users/parker.timmerman/Development/materialize/misc/python/materialize/mzcompose/composition.py", line 282, in invoke
    ret = subprocess.run(
          ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'compose', '-f/dev/fd/3', '--project-directory', PosixPath('/Users/parker.timmerman/Development/materialize/test/parallel-workload'), 'run', '--rm', 'sqlsmith', '--max-joins=0', '--target=host=materialized port=6875 dbname=materialize user=materialize', '--read-state', '--dry-run', '--max-queries=100']' returned non-zero exit status 15.
```

Have you seen this before?

**Comment by ParkMyCar** [comment]
Ahhh, looks like it's a `docker compose` error, and I see it repeatedly for just sqlsmith, it does not show up when running testdrive, nor does it occur when omitting the [sqlsmith action](https://github.com/MaterializeInc/materialize/blob/main/misc/python/materialize/parallel_workload/action.py#L1569), will dig into this!

**Comment by def-** [comment]
Updated https://github.com/MaterializeInc/materialize/pull/23251#issuecomment-1819963488 to make this reproduce on macOS too.
