### ISSUE TITLE
Panic in test_emit_tracing_notice: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#23396]
### What version of Materialize are you using?

2dd95554d3c3

### What is the issue?

```
--- STDERR:              mz-environmentd::sql test_emit_tracing_notice ---
thread 'tokio-runtime-worker' panicked at /cargo/git/checkouts/tracing-opentelemetry-564dca2c5f164918/405437e/src/tracer.rs:73:40:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:127:5
   3: <core::option::Option<opentelemetry_sdk::trace::provider::TracerProvider>>::unwrap
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/option.rs:935:21
   4: <opentelemetry_sdk::trace::tracer::Tracer as tracing_opentelemetry::tracer::PreSampledTracer>::sampled_context
             at /cargo/git/checkouts/tracing-opentelemetry-564dca2c5f164918/405437e/src/tracer.rs:73:24
   5: <tracing_opentelemetry::layer::OpenTelemetryLayer<tracing_subscriber::layer::layered::Layered<tracing_subscriber::filter::layer_filters::Filtered<alloc::boxed::Box<dyn tracing_subscriber::layer::Layer<tracing_subscriber::registry::sharded::Registry> + core::marker::Sync + core::marker::Send>, tracing_subscriber::reload::Layer<tracing_subscriber::filter::env::EnvFilter, tracing_subscriber::registry::sharded::Registry>, tracing_subscriber::registry::sharded::Registry>, tracing_subscriber::registry::sharded::Registry>, opentelemetry_sdk::trace::tracer::Tracer>>::parent_context::{closure#1}::{closure#0}
             at /cargo/git/checkouts/tracing-opentelemetry-564dca2c5f164918/405437e/src/layer.rs:649:40
   6: <core::option::Option<&mut tracing_opentelemetry::OtelData>>::map::<opentelemetry_api::context::Context, <tracing_opentelemetry::layer::OpenTelemetryLayer<tracing_subscriber::layer::layered::Layered<tracing_subscriber::filter::layer_filters::Filtered<alloc::boxed::Box<dyn tracing_subscriber::layer::Layer<tracing_subscriber::registry::sharded::Registry> + core::marker::Sync + core::marker::Send>, tracing_subscriber::reload::Layer<tracing_subscriber::filter::env::EnvFilter, tracing_subscriber::registry::sharded::Registry>, tracing_subscriber::registry::sharded::Registry>, tracing_subscriber::registry::sharded::Registry>, opentelemetry_sdk::trace::tracer::Tracer>>::parent_context::{closure#1}::{closure#0}>
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/option.rs:1075:29
   7: <tracing_opentelemetry::layer::OpenTelemetryLayer<tracing_subscriber::layer::layered::Layered<tracing_subscriber::filter::layer_filters::Filtered<alloc::boxed::Box<dyn tracing_subscriber::layer::Layer<tracing_subscriber::registry::sharded::Registry> + core::marker::Sync + core::marker::Send>, tracing_subscriber::reload::Layer<tracing_subscriber::filter::env::EnvFilter, tracing_subscriber::registry::sharded::Registry>, tracing_subscriber::registry::sharded::Registry>, tracing_subscriber::registry::sharded::Registry>, opentelemetry_sdk::trace::tracer::Tracer>>::parent_context::{closure#1}
             at /cargo/git/checkouts/tracing-opentelemetry-564dca2c5f164918/405437e/src/layer.rs:647:21
   8: <core::option::Option<tracing_subscriber::registry::SpanRef<tracing_subscriber::layer::layered::Layered<tracing_subscriber::filter::layer_filters::Filtered<alloc::boxed::Box<dyn tracing_subscriber::layer::Layer<tracing_subscriber::registry::sharded::Registry> + core::marker::Sync + core::marker::Send>, tracing_subscriber::reload::Layer<tracing_subscriber::filter::env::EnvFilter, tracing_subscriber::registry::sharded::Registry>, tracing_subscriber::registry::sharded::Registry>, tracing_subscriber::registry::sharded::Registry>>>>::and_then::<opentelemetry_api::context::Context, <tracing_opentelemetry::layer::OpenTelemetryLayer<tracing_subscriber::layer::layered::Layered<tracing_subscriber::filter::layer_filters::Filtered<alloc::boxed::Box<dyn tracing_subscriber::layer::Layer<tracing_subscriber::registry::sharded::Registry> + core::marker::Sync + core::marker::Send>, tracing_subscriber::reload::Layer<tracing_subscriber::filter::env::EnvFilter, tracing_subscriber::registry::sharded::Registry>, tracing_subscriber::registry::sharded::Registry>, tracing_subscriber::registry::sharded::Registry>, opentelemetry_sdk::trace::tracer::Tracer>>::parent_context::{closure#1}>
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/option.rs:1414:24
```
Full logs: https://gist.github.com/def-/aeafe5fe12f2898874bbcfb1df98e5f8
Seen in https://buildkite.com/materialize/tests/builds/69428#018bf901-b120-457c-8d4b-0c8b1d68afcc, not sure if it's related to the recent Rust 1.74 upgrade.
I'll try to reproduce it locally, but no success so far.

**Comment by def-** [comment]
Reproduced locally: `while true; do cargo nextest run test_emit_tracing_notice || break; done`

**Comment by mjibson** [comment]
I've been unable to reproduce this with the above command after letting it run for several minutes. The linked stack trace doesn't contain any materialize code, so I'm unable to even get a line number in test_emit_tracing_notice where the failure occurred.

Have you seen this same error before? Has the error occurred in other tests?

**Comment by def-** [comment]
Only seen at the end of last week in test_emit_tracing_notice, not in any other tests. Let me try to reproduce it again, maybe I can figure out something more.

**Comment by ParkMyCar** [comment]
+1 to Matt, I let this run for a while and the test never failed. It looks like the root of the panic is coming from [here](https://github.com/tokio-rs/tracing-opentelemetry/blob/d9b18f2aeddbab1b26c2794503a2c6423a2426e0/src/tracer.rs#L73), I'm not sure what a provider is in this context, or why it might be missing, but I'm leaning towards this being an OpenTelemetry bug

**Comment by def-** [comment]
It now requires `while true; do cargo nextest run test_emit_tracing_notice --run-ignored all || break; done` since I disabled the test to get cargo test green again. I have unfortunately also not seen the error since locally, ran it for a few hours locally. I guess if we can't figure anything else out, I'll enable the test_emit_tracing_notice unit test again.

**Comment by ParkMyCar** [comment]
I tried running `while true; do cargo nextest run test_emit_tracing_notice --run-ignored all || break; done` last week and didn't get a panic. @def- what do you think about re-enabling `test_emit_tracing_notice` for now?

**Comment by def-** [comment]
@ParkMyCar Just failed again: https://buildkite.com/materialize/tests/builds/72678#018cf04b-85e0-4b8d-bba3-d99c6edea94d
