### ISSUE TITLE
thread 'test_linearizability' panicked at src/environmentd/tests/sql.rs:1841:14: called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Custom { kind: Other, error: "bytes remaining on stream" }) }

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#23449]
### What version of Materialize are you using?

0fe7580b8827

### What is the issue?

Seen in https://buildkite.com/materialize/tests/builds/69621#018c08f1-cce9-4323-b09b-934f372fac2a
```
--- STDERR:              mz-environmentd::sql test_linearizability ---
thread 'test_linearizability' panicked at src/environmentd/tests/sql.rs:1841:14:
called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Custom { kind: Other, error: "bytes remaining on stream" }) }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1652:5
   3: <core::result::Result<(tokio_postgres::client::Client, mz_environmentd::test_util::create_postgres_source_with_table::{closure#0}::{closure#3}), alloc::boxed::Box<dyn core::error::Error>>>::unwrap
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1077:23
   4: sql::test_linearizability::{closure#0}::test_impl::{closure#0}
             at ./tests/sql.rs:1839:9
   5: sql::test_linearizability::{closure#0}
             at ./tests/sql.rs:1821:1
   6: <core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>> as core::future::future::Future>::poll
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
   7: <tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
   8: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
   9: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  10: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  11: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  12: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  13: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  14: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::scheduler::multi_thread::MultiThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>::{closure#0}, ()>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  15: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  16: <tokio::runtime::runtime::Runtime>::block_on::<core::pin::Pin<&mut dyn core::future::future::Future<Output = ()>>>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/runtime.rs:349:45
  17: sql::test_linearizability
             at ./tests/sql.rs:1821:1
  18: sql::test_linearizability::{closure#0}
             at ./tests/sql.rs:1821:1
  19: <sql::test_linearizability::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
  20: core::ops::function::FnOnce::call_once
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
ci-regexp: thread 'test_linearizability' panicked at .*"bytes remaining on stream"

**Comment by jkosh44** [comment]
I haven't been able to repro this locally or in CI (via https://github.com/MaterializeInc/materialize/pull/23500). I merged https://github.com/MaterializeInc/materialize/pull/23502 which should give us slightly more information next time this happened. I've seen this same error happen in the past on various cargo tests, so I don't think it's specific to this test. I think the error indicates a connection issue to Materialize or PostgreSQL mid test.

**Comment by jkosh44** [comment]
I haven't seen this again and I'm pretty sure it's just a docker/env issue of being unable to connect to PostgreSQL. I'm going to close this for now and re-open if we see it again with the more informative stack trace.

**Comment by def-** [comment]
Seen again in https://buildkite.com/materialize/tests/builds/73982#018d411d-dac7-4050-bd45-ceec60b9021e:
```
--- STDERR:              mz-regexp tests::test_pg_regexp_split_array ---
thread 'tests::test_pg_regexp_split_array' panicked at src/regexp/src/lib.rs:73:84:
called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Custom { kind: Other, error: "bytes remaining on stream" }) }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1652:5
   3: <core::result::Result<postgres::client::Client, tokio_postgres::error::Error>>::unwrap
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1077:23
   4: mz_regexp::tests::test_pg_regexp_split_array::test_impl
             at ./src/lib.rs:73:26
   5: mz_regexp::tests::test_pg_regexp_split_array
             at ./src/lib.rs:67:5
   6: mz_regexp::tests::test_pg_regexp_split_array::{closure#0}
             at ./src/lib.rs:67:5
   7: <mz_regexp::tests::test_pg_regexp_split_array::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jkosh44** [comment]
I tried to find exactly where this error was coming from. It looks like it's coming from `tokio` in one of these locations:

- https://github.com/tokio-rs/tokio-core/blob/fdba3f18370c67ec0c99c119157ad8e25be99fd9/src/io/frame.rs#L287-L299
- https://github.com/tokio-rs/tokio-io/blob/01784791660129f47c3f70c212301cf0dcfb0147/src/framed_read.rs#L65-L91
- https://github.com/tokio-rs/tokio/blob/131e7b4e49c8849298ba54b4e0c99f4b81d869e3/tokio-util/src/codec/decoder.rs#L126-L155

They're all essentially the same error and it means that there is a non-empty stream of bytes but `decode` returned `Ok(None)`, which means the bytes could not be decoded into a message/frame.

**Comment by jkosh44** [comment]
FWIW, this error always comes from the test itself and not from Materialize. Specifically, it comes from the test trying to communicating with Materialized using the rust-postgres library.

**Comment by def-** [comment]
Also seen in catalog::tests::test_compare_builtins_postgres: https://buildkite.com/materialize/test/builds/83024#018fdb95-0f4c-449f-b06b-16644116b2f9 Added another ci-regexp, indeed happens very rarely and probably a test-only issue.
