### ISSUE TITLE
thread 'main' panicked at src/catalog/src/durable/impls/persist.rs:133:14: invalid usage: CodecMismatch(CodecMismatch { requested: ("protobuf[SourceData]", "()", "u64", "i64", None), actual: ("StateUpdateProto", "()", "u64", "i64", None) })

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#24011]
### What version of Materialize are you using?

002437c496

### What is the issue?

Happens in upgrade tests in nightly: https://buildkite.com/materialize/nightlies/builds/5652
```
thread 'main' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d011f4a0a2ad6205-1/materialize/tests/src/catalog/src/durable/impls/persist.rs:133:14:
invalid usage: CodecMismatch(CodecMismatch { requested: ("protobuf[SourceData]", "()", "u64", "i64", None), actual: ("StateUpdateProto", "()", "u64", "i64", None) })
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1652:5
   3: <core::result::Result<(mz_persist_client::write::WriteHandle<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>, mz_persist_client::read::ReadHandle<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>), mz_persist_client::error::InvalidUsage<mz_repr::timestamp::Timestamp>>>::expect
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/result.rs:1034:23
   4: <mz_catalog::durable::impls::persist::UnopenedPersistCatalogState>::new::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d011f4a0a2ad6205-1/materialize/tests/src/catalog/src/durable/impls/persist.rs:125:51
   5: <mz_catalog::durable::impls::persist::UnopenedPersistCatalogState>::new::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d011f4a0a2ad6205-1/materialize/tests/src/catalog/src/durable/impls/persist.rs:116:5
   6: mz_catalog::durable::persist_backed_catalog_state::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d011f4a0a2ad6205-1/materialize/tests/src/catalog/src/durable.rs:309:80
   7: mz_catalog::durable::test_persist_backed_catalog_state::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d011f4a0a2ad6205-1/materialize/tests/src/catalog/src/durable.rs:319:76
   8: mz_catalog::durable::shadow_catalog_state::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d011f4a0a2ad6205-1/materialize/tests/src/catalog/src/durable.rs:333:85
   9: mz_environmentd::catalog_opener::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d011f4a0a2ad6205-1/materialize/tests/src/environmentd/src/lib.rs:782:18
  10: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<alloc::boxed::Box<dyn mz_catalog::durable::OpenableDurableCatalogState>, anyhow::Error>> + core::marker::Send>> as core::future::future::Future>::poll
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
  11: <mz_environmentd::Listeners>::serve::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d011f4a0a2ad6205-1/materialize/tests/src/environmentd/src/lib.rs:466:10
  12: <tracing::instrument::Instrumented<<mz_environmentd::Listeners>::serve::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  13: <mz_environmentd::Listeners>::serve::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d011f4a0a2ad6205-1/materialize/tests/src/environmentd/src/lib.rs:339:5
  14: environmentd::run::{closure#11}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d011f4a0a2ad6205-1/materialize/tests/src/environmentd/src/bin/environmentd/main.rs:1015:14
  15: <tracing::instrument::Instrumented<environmentd::run::{closure#11}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  16: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  17: tokio::runtime::coop::with_budget::<core::task::poll::Poll<core::result::Result<mz_environmentd::Server, anyhow::Error>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  18: tokio::runtime::coop::budget::<core::task::poll::Poll<core::result::Result<mz_environmentd::Server, anyhow::Error>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  19: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  20: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  21: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  22: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::scheduler::multi_thread::MultiThread>::block_on<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}, core::result::Result<mz_environmentd::Server, anyhow::Error>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  23: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  24: <tokio::runtime::runtime::Runtime>::block_on::<environmentd::run::{closure#11}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/runtime.rs:349:50
  25: environmentd::run
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d011f4a0a2ad6205-1/materialize/tests/src/environmentd/src/bin/environmentd/main.rs:947:18
  26: environmentd::main
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0d011f4a0a2ad6205-1/materialize/tests/src/environmentd/src/bin/environmentd/main.rs:633:23
  27: <fn() as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Started in https://github.com/MaterializeInc/materialize/compare/d4524d75bf...002437c496
@danhhz I think this might come from https://github.com/MaterializeInc/materialize/pull/23878 I'll try to verify if that is the case in the meantime.

**Comment by def-** [comment]
This revert being green will prove that it's the PR: https://buildkite.com/materialize/nightlies/builds/5655
I think the catalog change is not being handled properly for the upgrade.

**Comment by danhhz** [comment]
Ah whoops, I was under the incorrect impression that we weren't using this yet in CI. This has never been turned on in prod or staging, so we should be allowed to make backward incompatible changes. Is there a way to version gate the new "persist/shadow" impl in this test?

Also given that this isn't on in staging or prod, I'll remove the release-blocker label.

**Comment by danhhz** [comment]
Ah, @jkosh44 pointed me at https://github.com/MaterializeInc/materialize/blob/0fe9ac088ab488afe4d5ad669a6f40a4cad70bed/misc/python/materialize/checks/mzcompose_actions.py#L43-L47. I'll send a PR to update!

**Comment by danhhz** [comment]
And done. Sorry for the disruption! https://github.com/MaterializeInc/materialize/pull/24018
