### ISSUE TITLE
thread 'test_statement_logging_immediate' panicked at src/environmentd/tests/server.rs:304:5: 	assertion `left == right` failed

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#24041]
### What version of Materialize are you using?

143acc7a429f 

### What is the issue?

Seen in https://buildkite.com/materialize/tests/builds/71590#018c836e-1ceb-4196-8b00-3d56266a78c4
```
thread 'test_statement_logging_immediate' panicked at src/environmentd/tests/server.rs:304:5:
assertion `left == right` failed
  left: 20
 right: 21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed::<usize, usize>
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:270:5
   4: server::test_statement_logging_immediate::test_impl
             at ./tests/server.rs:304:5
   5: server::test_statement_logging_immediate
             at ./tests/server.rs:237:1
   6: server::test_statement_logging_immediate::{closure#0}
             at ./tests/server.rs:237:1
   7: <server::test_statement_logging_immediate::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
```
@umanwizard Since you fixed https://github.com/MaterializeInc/materialize/issues/21598 before, do you want to take a look at this too?

**Comment by umanwizard** [comment]
Please reopen if this is not fixed by https://github.com/MaterializeInc/materialize/pull/24185
