### ISSUE TITLE
thread 'timely:work-0' panicked at src/storage/src/storage_state.rs:1026:34: only alter compatible ingestions permitted: InvalidAlter { id: User(26) }

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#24125]
### What version of Materialize are you using?

acd130882d

### What is the issue?

This happened in my PR https://github.com/MaterializeInc/materialize/pull/24111 and I believe it could be related to it: https://buildkite.com/materialize/nightlies/builds/5731#018cac5d-f5d5-4f24-b298-0afc6a09eeb4

The PR introduces jitter in the CRDB and S3 connections in order to expose issues with persist-txn.

```
2023-12-27T18:05:25.280010Z  WARN mz_storage_types::sources: IngestionDescription incompatible at ingestion_metadata:
self:
IngestionDescription {
    desc: SourceDesc {
        connection: Kafka(
            KafkaSourceConnection {
                connection: KafkaConnection {
                    brokers: [
                        KafkaBroker {
                            address: "kafka:9092",
                            tunnel: Direct,
                        },
                    ],
                    default_tunnel: Direct,
                    progress_topic: Some(
                        "zippy-sink_2-1",
                    ),
                    options: {},
                    tls: None,
                    sasl: None,
                },
                connection_id: User(
                    22,
                ),
                topic: "sink-sink_2",
                start_offsets: {},
                group_id_prefix: None,
                metadata_columns: [],
                topic_metadata_refresh_interval: 30s,
            },
        ),
        encoding: Single(
            DataEncoding {
                force_nullable_columns: false,
                inner: Avro(
                    AvroEncoding {
                        schema: "{\"type\":\"record\",\"name\":\"envelope\",\"fields\":[{\"name\":\"before\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"row\",\"fields\":[{\"name\":\"count_all\",\"type\":[\"null\",\"int\"]},{\"name\":\"count_distinct\",\"type\":[\"null\",\"int\"]},{\"name\":\"min_value\",\"type\":[\"null\",\"int\"]},{\"name\":\"max_value\",\"type\":[\"null\",\"int\"]}]}]},{\"name\":\"after\",\"type\":[\"null\",\"row\"]}]}",
                        csr_connection: Some(
                            CsrConnection {
                                url: Url {
                                    scheme: "http",
                                    cannot_be_a_base: false,
                                    username: "",
                                    password: None,
                                    host: Some(
                                        Domain(
                                            "schema-registry",
                                        ),
                                    ),
                                    port: Some(
                                        8081,
                                    ),
                                    path: "/",
                                    query: None,
                                    fragment: None,
                                },
                                tls_root_cert: None,
                                tls_identity: None,
                                http_auth: None,
                                tunnel: Direct,
                            },
                        ),
                        confluent_wire_format: true,
                    },
                ),
            },
        ),
        envelope: None(
            NoneEnvelope {
                key_envelope: None,
                key_arity: 0,
            },
        ),
        timestamp_interval: 1s,
    },
    source_imports: {},
    ingestion_metadata: CollectionMetadata {
        persist_location: PersistLocation {
            blob_uri: "s3://minioadmin:minioadmin@persist/persist?endpoint=http://toxiproxy:9000/&region=minio",
            consensus_uri: "postgres://root@toxiproxy:26257?options=--search_path=consensus",
        },
        remap_shard: Some(
            ShardId(9b0cfd63-80b3-44e1-aceb-8bd876450729),
        ),
        data_shard: ShardId(0a3275b9-cbe3-4848-a418-819d2a662a66),
        status_shard: Some(
            ShardId(a1e7c991-d305-4799-9456-1307500101fd),
        ),
        relation_desc: RelationDesc {
            typ: RelationType {
                column_types: [
                    ColumnType {
                        scalar_type: Record {
                            fields: [
                                (
                                    ColumnName(
                                        "count_all",
                                    ),
                                    ColumnType {
                                        scalar_type: Int32,
                                        nullable: true,
                                    },
                                ),
                                (
                                    ColumnName(
                                        "count_distinct",
                                    ),
                                    ColumnType {
                                        scalar_type: Int32,
                                        nullable: true,
                                    },
                                ),
                                (
                                    ColumnName(
                                        "min_value",
                                    ),
                                    ColumnType {
                                        scalar_type: Int32,
                                        nullable: true,
                                    },
                                ),
                                (
                                    ColumnName(
                                        "max_value",
                                    ),
                                    ColumnType {
                                        scalar_type: Int32,
                                        nullable: true,
                                    },
                                ),
                            ],
                            custom_id: None,
                        },
                        nullable: true,
                    },
                    ColumnType {
                        scalar_type: Record {
                            fields: [
                                (
                                    ColumnName(
                                        "count_all",
                                    ),
                                    ColumnType {
                                        scalar_type: Int32,
                                        nullable: true,
                                    },
                                ),
                                (
                                    ColumnName(
                                        "count_distinct",
                                    ),
                                    ColumnType {
                                        scalar_type: Int32,
                                        nullable: true,
                                    },
                                ),
                                (
                                    ColumnName(
                                        "min_value",
                                    ),
                                    ColumnType {
                                        scalar_type: Int32,
                                        nullable: true,
                                    },
                                ),
                                (
                                    ColumnName(
                                        "max_value",
                                    ),
                                    ColumnType {
                                        scalar_type: Int32,
                                        nullable: true,
                                    },
                                ),
                            ],
                            custom_id: None,
                        },
                        nullable: true,
                    },
                ],
                keys: [],
            },
            names: [
                ColumnName(
                    "before",
                ),
                ColumnName(
                    "after",
                ),
            ],
        },
        txns_shard: None,
    },
    source_exports: {
        User(
            26,
        ): SourceExport {
            output_index: 0,
            storage_metadata: CollectionMetadata {
                persist_location: PersistLocation {
                    blob_uri: "s3://minioadmin:minioadmin@persist/persist?endpoint=http://toxiproxy:9000/&region=minio",
                    consensus_uri: "postgres://root@toxiproxy:26257?options=--search_path=consensus",
                },
                remap_shard: Some(
                    ShardId(9b0cfd63-80b3-44e1-aceb-8bd876450729),
                ),
                data_shard: ShardId(0a3275b9-cbe3-4848-a418-819d2a662a66),
                status_shard: Some(
                    ShardId(a1e7c991-d305-4799-9456-1307500101fd),
                ),
                relation_desc: RelationDesc {
                    typ: RelationType {
                        column_types: [
                            ColumnType {
                                scalar_type: Record {
                                    fields: [
                                        (
                                            ColumnName(
                                                "count_all",
                                            ),
                                            ColumnType {
                                                scalar_type: Int32,
                                                nullable: true,
                                            },
                                        ),
                                        (
                                            ColumnName(
                                                "count_distinct",
                                            ),
                                            ColumnType {
                                                scalar_type: Int32,
                                                nullable: true,
                                            },
                                        ),
                                        (
                                            ColumnName(
                                                "min_value",
                                            ),
                                            ColumnType {
                                                scalar_type: Int32,
                                                nullable: true,
                                            },
                                        ),
                                        (
                                            ColumnName(
                                                "max_value",
                                            ),
                                            ColumnType {
                                                scalar_type: Int32,
                                                nullable: true,
                                            },
                                        ),
                                    ],
                                    custom_id: None,
                                },
                                nullable: true,
                            },
                            ColumnType {
                                scalar_type: Record {
                                    fields: [
                                        (
                                            ColumnName(
                                                "count_all",
                                            ),
                                            ColumnType {
                                                scalar_type: Int32,
                                                nullable: true,
                                            },
                                        ),
                                        (
                                            ColumnName(
                                                "count_distinct",
                                            ),
                                            ColumnType {
                                                scalar_type: Int32,
                                                nullable: true,
                                            },
                                        ),
                                        (
                                            ColumnName(
                                                "min_value",
                                            ),
                                            ColumnType {
                                                scalar_type: Int32,
                                                nullable: true,
                                            },
                                        ),
                                        (
                                            ColumnName(
                                                "max_value",
                                            ),
                                            ColumnType {
                                                scalar_type: Int32,
                                                nullable: true,
                                            },
                                        ),
                                    ],
                                    custom_id: None,
                                },
                                nullable: true,
                            },
                        ],
                        keys: [],
                    },
                    names: [
                        ColumnName(
                            "before",
                        ),
                        ColumnName(
                            "after",
                        ),
                    ],
                },
                txns_shard: None,
            },
        },
    },
    instance_id: User(
        2,
    ),
    remap_collection_id: User(
        25,
    ),
}

other
IngestionDescription {
    desc: SourceDesc {
        connection: Kafka(
            KafkaSourceConnection {
                connection: KafkaConnection {
                    brokers: [
                        KafkaBroker {
                            address: "kafka:9092",
                            tunnel: Direct,
                        },
                    ],
                    default_tunnel: Direct,
                    progress_topic: Some(
                        "zippy-sink_2-1",
                    ),
                    options: {},
                    tls: None,
                    sasl: None,
                },
                connection_id: User(
                    22,
                ),
                topic: "sink-sink_2",
                start_offsets: {},
                group_id_prefix: None,
                metadata_columns: [],
                topic_metadata_refresh_interval: 30s,
            },
        ),
        encoding: Single(
            DataEncoding {
                force_nullable_columns: false,
                inner: Avro(
                    AvroEncoding {
                        schema: "{\"type\":\"record\",\"name\":\"envelope\",\"fields\":[{\"name\":\"before\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"row\",\"fields\":[{\"name\":\"count_all\",\"type\":[\"null\",\"int\"]},{\"name\":\"count_distinct\",\"type\":[\"null\",\"int\"]},{\"name\":\"min_value\",\"type\":[\"null\",\"int\"]},{\"name\":\"max_value\",\"type\":[\"null\",\"int\"]}]}]},{\"name\":\"after\",\"type\":[\"null\",\"row\"]}]}",
                        csr_connection: Some(
                            CsrConnection {
                                url: Url {
                                    scheme: "http",
                                    cannot_be_a_base: false,
                                    username: "",
                                    password: None,
                                    host: Some(
                                        Domain(
                                            "schema-registry",
                                        ),
                                    ),
                                    port: Some(
                                        8081,
                                    ),
                                    path: "/",
                                    query: None,
                                    fragment: None,
                                },
                                tls_root_cert: None,
                                tls_identity: None,
                                http_auth: None,
                                tunnel: Direct,
                            },
                        ),
                        confluent_wire_format: true,
                    },
                ),
            },
        ),
        envelope: None(
            NoneEnvelope {
                key_envelope: None,
                key_arity: 0,
            },
        ),
        timestamp_interval: 1s,
    },
    source_imports: {},
    ingestion_metadata: CollectionMetadata {
        persist_location: PersistLocation {
            blob_uri: "s3://minioadmin:minioadmin@persist/persist?endpoint=http://minio:9000/&region=minio",
            consensus_uri: "postgres://root@cockroach:26257?options=--search_path=consensus",
        },
        remap_shard: Some(
            ShardId(9b0cfd63-80b3-44e1-aceb-8bd876450729),
        ),
        data_shard: ShardId(0a3275b9-cbe3-4848-a418-819d2a662a66),
        status_shard: Some(
            ShardId(a1e7c991-d305-4799-9456-1307500101fd),
        ),
        relation_desc: RelationDesc {
            typ: RelationType {
                column_types: [
                    ColumnType {
                        scalar_type: Record {
                            fields: [
                                (
                                    ColumnName(
                                        "count_all",
                                    ),
                                    ColumnType {
                                        scalar_type: Int32,
                                        nullable: true,
                                    },
                                ),
                                (
                                    ColumnName(
                                        "count_distinct",
                                    ),
                                    ColumnType {
                                        scalar_type: Int32,
                                        nullable: true,
                                    },
                                ),
                                (
                                    ColumnName(
                                        "min_value",
                                    ),
                                    ColumnType {
                                        scalar_type: Int32,
                                        nullable: true,
                                    },
                                ),
                                (
                                    ColumnName(
                                        "max_value",
                                    ),
                                    ColumnType {
                                        scalar_type: Int32,
                                        nullable: true,
                                    },
                                ),
                            ],
                            custom_id: None,
                        },
                        nullable: true,
                    },
                    ColumnType {
                        scalar_type: Record {
                            fields: [
                                (
                                    ColumnName(
                                        "count_all",
                                    ),
                                    ColumnType {
                                        scalar_type: Int32,
                                        nullable: true,
                                    },
                                ),
                                (
                                    ColumnName(
                                        "count_distinct",
                                    ),
                                    ColumnType {
                                        scalar_type: Int32,
                                        nullable: true,
                                    },
                                ),
                                (
                                    ColumnName(
                                        "min_value",
                                    ),
                                    ColumnType {
                                        scalar_type: Int32,
                                        nullable: true,
                                    },
                                ),
                                (
                                    ColumnName(
                                        "max_value",
                                    ),
                                    ColumnType {
                                        scalar_type: Int32,
                                        nullable: true,
                                    },
                                ),
                            ],
                            custom_id: None,
                        },
                        nullable: true,
                    },
                ],
                keys: [],
            },
            names: [
                ColumnName(
                    "before",
                ),
                ColumnName(
                    "after",
                ),
            ],
        },
        txns_shard: None,
    },
    source_exports: {
        User(
            26,
        ): SourceExport {
            output_index: 0,
            storage_metadata: CollectionMetadata {
                persist_location: PersistLocation {
                    blob_uri: "s3://minioadmin:minioadmin@persist/persist?endpoint=http://minio:9000/&region=minio",
                    consensus_uri: "postgres://root@cockroach:26257?options=--search_path=consensus",
                },
                remap_shard: Some(
                    ShardId(9b0cfd63-80b3-44e1-aceb-8bd876450729),
                ),
                data_shard: ShardId(0a3275b9-cbe3-4848-a418-819d2a662a66),
                status_shard: Some(
                    ShardId(a1e7c991-d305-4799-9456-1307500101fd),
                ),
                relation_desc: RelationDesc {
                    typ: RelationType {
                        column_types: [
                            ColumnType {
                                scalar_type: Record {
                                    fields: [
                                        (
                                            ColumnName(
                                                "count_all",
                                            ),
                                            ColumnType {
                                                scalar_type: Int32,
                                                nullable: true,
                                            },
                                        ),
                                        (
                                            ColumnName(
                                                "count_distinct",
                                            ),
                                            ColumnType {
                                                scalar_type: Int32,
                                                nullable: true,
                                            },
                                        ),
                                        (
                                            ColumnName(
                                                "min_value",
                                            ),
                                            ColumnType {
                                                scalar_type: Int32,
                                                nullable: true,
                                            },
                                        ),
                                        (
                                            ColumnName(
                                                "max_value",
                                            ),
                                            ColumnType {
                                                scalar_type: Int32,
                                                nullable: true,
                                            },
                                        ),
                                    ],
                                    custom_id: None,
                                },
                                nullable: true,
                            },
                            ColumnType {
                                scalar_type: Record {
                                    fields: [
                                        (
                                            ColumnName(
                                                "count_all",
                                            ),
                                            ColumnType {
                                                scalar_type: Int32,
                                                nullable: true,
                                            },
                                        ),
                                        (
                                            ColumnName(
                                                "count_distinct",
                                            ),
                                            ColumnType {
                                                scalar_type: Int32,
                                                nullable: true,
                                            },
                                        ),
                                        (
                                            ColumnName(
                                                "min_value",
                                            ),
                                            ColumnType {
                                                scalar_type: Int32,
                                                nullable: true,
                                            },
                                        ),
                                        (
                                            ColumnName(
                                                "max_value",
                                            ),
                                            ColumnType {
                                                scalar_type: Int32,
                                                nullable: true,
                                            },
                                        ),
                                    ],
                                    custom_id: None,
                                },
                                nullable: true,
                            },
                        ],
                        keys: [],
                    },
                    names: [
                        ColumnName(
                            "before",
                        ),
                        ColumnName(
                            "after",
                        ),
                    ],
                },
                txns_shard: None,
            },
        },
    },
    instance_id: User(
        2,
    ),
    remap_collection_id: User(
        25,
    ),
}
stack backtrace:
thread 'timely:work-2' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-00aa75ce5257aa81f-1/materialize/tests/src/storage/src/storage_state.rs:1026:34:
only alter compatible ingestions permitted: InvalidAlter { id: User(26) }
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: <mz_storage::storage_state::Worker<timely_communication::allocator::generic::Generic>>::reconcile
   4: <mz_storage::storage_state::Worker<timely_communication::allocator::generic::Generic>>::run_client
   5: <mz_storage::storage_state::Worker<timely_communication::allocator::generic::Generic>>::run
   6: <mz_storage::server::Config as mz_cluster::types::AsRunnableWorker<mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>>::build_and_run::<timely_communication::allocator::generic::Generic>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

My interpretation is that we expect a user to already exist, but it hasn't been written to CRDB yet because of the network jitter. I have restarted the run to see if it's a flake. Edit: seems reproducible

Previous occurrence of this assertion failure: https://github.com/MaterializeInc/materialize/issues/19987

ci-regexp: only alter compatible ingestions permitted: InvalidAlter

**Comment by sploiselle** [comment]
The issue here is that the ingestion metdata `PersistLocation` changes:

```rust
PersistLocation {
  blob_uri: "s3://minioadmin:minioadmin@persist/persist?endpoint=http://minio:9000/&region=minio",
  consensus_uri: "postgres://root@cockroach:26257?options=--search_path=consensus",
}
```

vs.

```rust
PersistLocation {
  blob_uri: "s3://minioadmin:minioadmin@persist/persist?endpoint=http://toxiproxy:9000/&region=minio",
  consensus_uri: "postgres://root@toxiproxy:26257?options=--search_path=consensus",
}
```

Using `toxiproxy` has the host that gets persisted in the metadata is what's causing the issue.

**Comment by def-** [comment]
Ok, so a test problem. I'll fix my PR. Sorry for the noise!

**Comment by sploiselle** [comment]
@def- If this isn't fixable in your test, this is something we can change in the assertion--we've run into this before and reasoned our way into being OK with the URLs changing (the cockroach URL, e.g. doesn't have to be stable to connect to the same cluster). lmk if it's still an issue for you

**Comment by def-** [comment]
Already fixed in the test.
