### ISSUE TITLE
scalability-benchmark:     assert len(comparison_outcome.endpoints_with_regressions) == len( fails in case of a regression

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#24147]
### What version of Materialize are you using?

v0.81.0

### What is the issue?

The scalability benchmark asserts in the CI, I think it does that if there is a performance regression and the workload was retried. Maybe two retries count as two regressions so that the assert is no longer valid:

```
Replacing result entry for endpoint (v0.81.0 (1bf5dd1a8)) and workload SelectOneWorkload
Writing results of v0.80.2 (dedd3e0c3) to /home/pstoev/materialize-bisect/test/scalability/results/v0.80.2 (dedd3e0c3)/results.csv
Writing results of v0.81.0 (1bf5dd1a8) to /home/pstoev/materialize-bisect/test/scalability/results/v0.81.0 (1bf5dd1a8)/results.csv
--- mzcompose: test case workflow-default failed: <class 'AssertionError'>: 
Traceback (most recent call last):
  File "/home/pstoev/materialize-bisect/misc/python/materialize/mzcompose/composition.py", line 475, in test_case
    yield
  File "/home/pstoev/materialize-bisect/misc/python/materialize/cli/mzcompose.py", line 598, in handle_composition
    composition.workflow(args.workflow, *args.unknown_subargs[1:])
  File "/home/pstoev/materialize-bisect/misc/python/materialize/mzcompose/composition.py", line 365, in workflow
    func(self, parser)
  File "/home/pstoev/materialize-bisect/test/scalability/mzcompose.py", line 215, in workflow_default
    regression_assessment = RegressionAssessment(
                            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pstoev/materialize-bisect/misc/python/materialize/scalability/regression_assessment.py", line 36, in __init__
    assert len(comparison_outcome.endpoints_with_regressions) == len(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
mzcompose: error: at least one test case failed
```

To reproduce:

```
git fetch --all --tags
git checkout v0.81.0
./mzcompose --ignore-docker-version down -v ; ./mzcompose --ignore-docker-version run default --workload=SelectOneWorkload --target HEAD --target common-ancestor --regression-against common-ancestor --max-concurrency 256
```

I am going to try to disable the assertion temporarily until it can be reworked.

**Comment by philip-stoev** [comment]
Disabling the assertion causes the proper output to be printed:

```
+++ Scalability changes
ERROR: The following scalability changes were detected (threshold: 0.2, baseline: v0.80.2 (dedd3e0c3) - release: bump to version v0.80.2):
Regressions:
* Regression in workload 'SelectOneWorkload' at concurrency 1 with MaterializeContainer (None specified as <bound method Endpoint.specified_target of <materialize.scalability.endpoints.MaterializeContainer object at 0x7f44d482b090>>): 43.02 tps vs. 78.9 tps (-35.87 tps; -45.47%)
* Regression in workload 'SelectOneWorkload' at concurrency 2 with MaterializeContainer (None specified as <bound method Endpoint.specified_target of <materialize.scalability.endpoints.MaterializeContainer object at 0x7f44d482b090>>): 56.14 tps vs. 79.45 tps (-23.32 tps; -29.34%)
* Regression in workload 'SelectOneWorkload' at concurrency 4 with MaterializeContainer (None specified as <bound method Endpoint.specified_target of <materialize.scalability.endpoints.MaterializeContainer object at 0x7f44d482b090>>): 63.17 tps vs. 154.58 tps (-91.41 tps; -59.14%)
* Regression in workload 'SelectOneWorkload' at concurrency 8 with MaterializeContainer (None specified as <bound method Endpoint.specified_target of <materialize.scalability.endpoints.MaterializeContainer object at 0x7f44d482b090>>): 161.72 tps vs. 332.64 tps (-170.93 tps; -51.38%)
* Regression in workload 'SelectOneWorkload' at concurrency 16 with MaterializeContainer (None specified as <bound method Endpoint.specified_target of <materialize.scalability.endpoints.MaterializeContainer object at 0x7f44d482b090>>): 619.83 tps vs. 868.95 tps (-249.13 tps; -28.67%)
```

**Comment by nrainer-materialize** [comment]
I will have a look at it!

**Comment by philip-stoev** [comment]
This is fixed apparently.

**Comment by nrainer-materialize** [comment]
Yes, thanks for closing it.
