### ISSUE TITLE
assertion `left == right` failed: stash and persist result variant do not match when fencing

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#24159]
### What version of Materialize are you using?

 v0.82.0-dev (144d6ab72)

### What is the issue?

In certain circumstances, when fencing kicks in, the old Mz instance panicks instead of exiting more gracefully:

```
persist-txn-fencing-mz_first-1   | environmentd: 2023-12-30T12:38:50.340257Z  INFO group_commit_notify: mz_stash::postgres: tokio-postgres stash error, retry attempt 1: stash error: unexpected fence epoch 3, expected Some(2), code: None
persist-txn-fencing-mz_first-1   | thread 'coordinator' panicked at src/catalog/src/durable/impls/shadow.rs:518:9:
persist-txn-fencing-mz_first-1   | assertion `left == right` failed: stash and persist result variant do not match. stash: Err(Durable(Fence("unexpected fence epoch 3, expected Some(2)"))). persist: Ok(())
persist-txn-fencing-mz_first-1   |   left: false
persist-txn-fencing-mz_first-1   |  right: true
persist-txn-fencing-mz_first-1   | stack backtrace:
persist-txn-fencing-mz_first-1   |    0: rust_begin_unwind
persist-txn-fencing-mz_first-1   |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
persist-txn-fencing-mz_first-1   |    1: core::panicking::panic_fmt
persist-txn-fencing-mz_first-1   |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
persist-txn-fencing-mz_first-1   |    2: core::panicking::assert_failed_inner
persist-txn-fencing-mz_first-1   |    3: core::panicking::assert_failed::<bool, bool>
persist-txn-fencing-mz_first-1   |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:270:5
persist-txn-fencing-mz_first-1   |    4: <mz_catalog::durable::impls::shadow::ShadowCatalogState as mz_catalog::durable::DurableCatalogState>::confirm_leadership::{closure#0}
persist-txn-fencing-mz_first-1   |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07c7d627b4e3399ae-1/materialize/tests/src/catalog/src/durable/impls/shadow.rs:518:9
persist-txn-fencing-mz_first-1   |    5: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(), mz_catalog::durable::error::CatalogError>> + core::marker::Send>> as core::future::future::Future>::poll
persist-txn-fencing-mz_first-1   |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
persist-txn-fencing-mz_first-1   |    6: <mz_adapter::catalog::Catalog>::confirm_leadership::{closure#0}::{closure#0}
persist-txn-fencing-mz_first-1   |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07c7d627b4e3399ae-1/materialize/tests/src/adapter/src/catalog.rs:3425:54
persist-txn-fencing-mz_first-1   |    7: <mz_adapter::catalog::Catalog>::confirm_leadership::{closure#0}
persist-txn-fencing-mz_first-1   |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07c7d627b4e3399ae-1/materialize/tests/src/adapter/src/catalog.rs:3423:5
persist-txn-fencing-mz_first-1   |    8: <mz_adapter::coord::Coordinator>::group_commit_initiate::{closure#0}::{closure#0}
persist-txn-fencing-mz_first-1   |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07c7d627b4e3399ae-1/materialize/tests/src/adapter/src/coord/appends.rs:284:14
persist-txn-fencing-mz_first-1   |    9: <mz_adapter::coord::Coordinator>::group_commit_initiate::{closure#0}
persist-txn-fencing-mz_first-1   |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07c7d627b4e3399ae-1/materialize/tests/src/adapter/src/coord/appends.rs:212:5
persist-txn-fencing-mz_first-1   |   10: <mz_adapter::coord::Coordinator>::try_group_commit::{closure#0}::{closure#0}
persist-txn-fencing-mz_first-1   |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07c7d627b4e3399ae-1/materialize/tests/src/adapter/src/coord/appends.rs:196:54
persist-txn-fencing-mz_first-1   |   11: <mz_adapter::coord::Coordinator>::try_group_commit::{closure#0}
persist-txn-fencing-mz_first-1   |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07c7d627b4e3399ae-1/materialize/tests/src/adapter/src/coord/appends.rs:159:5
persist-txn-fencing-mz_first-1   |   12: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::try_group_commit::{closure#0}> as core::future::future::Future>::poll
persist-txn-fencing-mz_first-1   |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
persist-txn-fencing-mz_first-1   |   13: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
persist-txn-fencing-mz_first-1   |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07c7d627b4e3399ae-1/materialize/tests/src/adapter/src/coord/message_handler.rs:91:68
persist-txn-fencing-mz_first-1   |   14: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_message::{closure#0}> as core::future::future::Future>::poll
persist-txn-fencing-mz_first-1   |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
persist-txn-fencing-mz_first-1   |   15: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
persist-txn-fencing-mz_first-1   |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
persist-txn-fencing-mz_first-1   |   16: <mz_adapter::coord::Coordinator>::serve::{closure#0}
persist-txn-fencing-mz_first-1   |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07c7d627b4e3399ae-1/materialize/tests/src/adapter/src/coord.rs:2400:48
persist-txn-fencing-mz_first-1   |   17: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
persist-txn-fencing-mz_first-1   |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
persist-txn-fencing-mz_first-1   |   18: <tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>> as core::future::future::Future>::poll
persist-txn-fencing-mz_first-1   |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
persist-txn-fencing-mz_first-1   |   19: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}
persist-txn-fencing-mz_first-1   |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
persist-txn-fencing-mz_first-1   |   20: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}>
persist-txn-fencing-mz_first-1   |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
persist-txn-fencing-mz_first-1   |   21: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}>
persist-txn-fencing-mz_first-1   |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
persist-txn-fencing-mz_first-1   |   22: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>
persist-txn-fencing-mz_first-1   |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
persist-txn-fencing-mz_first-1   |   23: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>
persist-txn-fencing-mz_first-1   |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
persist-txn-fencing-mz_first-1   |   24: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>::{closure#0}
persist-txn-fencing-mz_first-1   |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:310:13
persist-txn-fencing-mz_first-1   |   25: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::handle::Handle>::block_on<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>::{closure#0}, ()>
persist-txn-fencing-mz_first-1   |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
persist-txn-fencing-mz_first-1   |   26: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>
persist-txn-fencing-mz_first-1   |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:309:9
persist-txn-fencing-mz_first-1   |   27: mz_adapter::coord::serve::{closure#0}::{closure#2}
persist-txn-fencing-mz_first-1   |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-07c7d627b4e3399ae-1/materialize/tests/src/adapter/src/coord.rs:2768:21
persist-txn-fencing-mz_first-1   | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

There does not seem to be any ill effects -- the new Mz instance is still able to take over and the committed transactions are all safe.

To reproduce:

```
cd test/perisist-txn-fencing
./mzcompose run default
```

And then examine the logs of the `mz_first` instance. 

Currently, the panic above is allowed and does not cause the test to fail. See mzcompose.py line 232

**Comment by philip-stoev** [comment]
Here is another example of a panic as opposed to a more orderly exit:

```
persist-txn-fencing-mz_first-1   | thread 'coordinator' panicked at src/catalog/src/durable/impls/shadow.rs:518:9: assertion `left == right` failed: stash and persist result variant do not match. stash: Ok(()). persist: Err(Durable(Fence("current catalog upper 17 fenced by new catalog upper 18")))
```
