### ISSUE TITLE
"index out of bounds" when EXPLAIN-ing a query containing arithmetic expressions + INDEX

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#24301]
### What version of Materialize are you using?

 v0.83.0-dev (a76ab8e79)

### What is the issue?

This panics. I tried to simplify this as much as I can, so I think both the index and the arithmetic expressions in the SELECT list and the WHERE clause are required:

```
DROP TABLE IF EXISTS t1 CASCADE;
CREATE TABLE t1 (f1 DOUBLE PRECISION, f2 DOUBLE PRECISION NOT NULL);
-- CREATE INDEX t1i1 ON t1(f1);
CREATE INDEX t1i2 ON t1(f2, f1);


EXPLAIN SELECT * 
FROM ( SELECT * FROM (VALUES (1, 2)) t2 (f1, f2))
JOIN (
    SELECT 
      a1.f2 AS f1, 
      a1.f1 + a1.f2 AS f2 
    FROM t1 AS a1
  ) AS a2
USING (f1) 
WHERE 
  (a2.f2 < a2.f2) 
  AND a2.f2 + a2.f2 = 7
;
```

```
thread 'coordinator' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-050d6627d85866748-1/materialize/tests/src/expr/src/explain/text.rs:1177:32:
index out of bounds: the len is 2 but the index is 2
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_bounds_check
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:180:5
   3: <usize as core::slice::index::SliceIndex<[alloc::string::String]>>::index
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/slice/index.rs:261:10
   4: <[alloc::string::String] as core::ops::index::Index<usize>>::index
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/slice/index.rs:18:9
   5: <alloc::vec::Vec<alloc::string::String> as core::ops::index::Index<usize>>::index
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/vec/mod.rs:2728:9
   6: <mz_expr::explain::text::HumanizedExpr<usize, mz_expr::explain::text::HumanizedNotice> as core::fmt::Display>::fmt
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-050d6627d85866748-1/materialize/tests/src/expr/src/explain/text.rs:1177:32
   7: <mz_expr::explain::text::HumanizedExpr<mz_expr::scalar::MirScalarExpr, mz_expr::explain::text::HumanizedNotice> as core::fmt::Display>::fmt
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-050d6627d85866748-1/materialize/tests/src/expr/src/explain/text.rs:1212:17
   8: core::fmt::rt::Argument::fmt
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/rt.rs:138:9
   9: core::fmt::write
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/mod.rs:1114:21
  10: <mz_expr::explain::text::HumanizedExpr<mz_expr::scalar::MirScalarExpr, mz_expr::explain::text::HumanizedNotice> as core::fmt::Display>::fmt
  11: core::fmt::rt::Argument::fmt
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/rt.rs:138:9
  12: core::fmt::write
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/mod.rs:1114:21
  13: core::fmt::Formatter::write_fmt
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/mod.rs:1580:9
  14: <mz_ore::str::separated::Separated<core::iter::adapters::map::Map<core::slice::iter::Iter<mz_expr::scalar::MirScalarExpr>, <mz_expr::explain::text::HumanizedNotice>::seq<mz_expr::scalar::MirScalarExpr>::{closure#0}>> as core::fmt::Display>::fmt
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-050d6627d85866748-1/materialize/tests/src/ore/src/str.rs:158:17
  15: core::fmt::rt::Argument::fmt
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/rt.rs:138:9
  16: core::fmt::write
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/mod.rs:1114:21
  17: core::fmt::Formatter::write_fmt
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/mod.rs:1580:9
  18: <mz_transform::notice::index_too_wide_for_literal_constraints::IndexTooWideForLiteralConstraints as mz_transform::notice::OptimizerNoticeApi>::fmt_hint
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-050d6627d85866748-1/materialize/tests/src/transform/src/notice/index_too_wide_for_literal_constraints.rs:127:9
  19: core::fmt::rt::Argument::fmt
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/rt.rs:138:9
  20: core::fmt::write
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/mod.rs:1114:21
  21: <&mut alloc::string::String as core::fmt::Write::write_fmt::SpecWriteFmt>::spec_write_fmt
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/mod.rs:208:17
  22: <alloc::string::String as core::fmt::Write>::write_fmt
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/fmt/mod.rs:212:14
  23: <mz_transform::notice::RawOptimizerNotice>::explain
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/macros/mod.rs:606:14
  24: <mz_adapter::explain::optimizer_trace::OptimizerTrace>::drain_all
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-050d6627d85866748-1/materialize/tests/src/adapter/src/explain/optimizer_trace.rs:107:32
  25: <mz_adapter::coord::Coordinator>::explain_statement::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-050d6627d85866748-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:2839:21
  26: <mz_adapter::coord::Coordinator>::sequence_explain_plan::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-050d6627d85866748-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:2575:24
  27: <mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-050d6627d85866748-1/materialize/tests/src/adapter/src/coord/sequencer.rs:320:75
  28: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  29: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
  30: <mz_adapter::coord::Coordinator>::handle_execute_inner::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-050d6627d85866748-1/materialize/tests/src/adapter/src/coord/command_handler.rs:771:73
  31: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_execute_inner::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  32: <mz_adapter::coord::Coordinator>::handle_execute_inner::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-050d6627d85866748-1/materialize/tests/src/adapter/src/coord/command_handler.rs:447:5
  33: <mz_adapter::coord::Coordinator>::handle_execute::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-050d6627d85866748-1/materialize/tests/src/adapter/src/coord/command_handler.rs:444:54
  34: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_execute::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  35: <mz_adapter::coord::Coordinator>::handle_execute::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-050d6627d85866748-1/materialize/tests/src/adapter/src/coord/command_handler.rs:345:5
  36: <mz_adapter::coord::Coordinator>::handle_command::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-050d6627d85866748-1/materialize/tests/src/adapter/src/coord/command_handler.rs:111:26
  37: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_command::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  38: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
  39: <mz_adapter::coord::Coordinator>::message_command::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-050d6627d85866748-1/materialize/tests/src/adapter/src/coord/message_handler.rs:340:34
  40: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::message_command::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  41: <mz_adapter::coord::Coordinator>::message_command::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-050d6627d85866748-1/materialize/tests/src/adapter/src/coord/message_handler.rs:337:5
  42: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-050d6627d85866748-1/materialize/tests/src/adapter/src/coord/message_handler.rs:66:47
  43: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_message::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  44: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
  45: <mz_adapter::coord::Coordinator>::serve::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-050d6627d85866748-1/materialize/tests/src/adapter/src/coord.rs:2436:48
  46: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
  47: <tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  48: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  49: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  50: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  51: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  52: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  53: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:310:13
  54: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::handle::Handle>::block_on<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>::{closure#0}, ()>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  55: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:309:9
  56: mz_adapter::coord::serve::{closure#0}::{closure#2}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-050d6627d85866748-1/materialize/tests/src/adapter/src/coord.rs:2804:21
```

**Comment by aalexandrov** [comment]
This is because the query ends up recommending an index key (#2 + #2) that is based on a column derived from a `Map`.

```
Explained Query:
  Project (#4, #5, #3) // { arity: 3 }
    Filter (#1{f2} = 1) AND (#2 < #2) AND (7 = (#2 + #2)) // { arity: 6 }
      Map ((#0{f1} + #1{f2}), (#0{f1} + 1), 1, 2) // { arity: 6 }
        ReadIndex on=t1 t1i2=[*** full scan ***] // { arity: 2 }

Used Indexes:
  - materialize.public.t1i2 (*** full scan ***)

Notices:
  - Notice: Index materialize.public.t1i2 on t1(f2, f1) is too wide to use for literal equalities `f2 = 1`.
    Hint: If your literal equalities filter out many rows, create an index whose key exactly matches your literal equalities: (f2, (#2 + #2)).
```

I'll open a PR that fixes the panic shortly. 

@ggevay There is a more general question whether we want to hints with such recommendations. Options are:

1. Allow such hints and do nothing besides fixing the panic.
2. Allow such hints, but work hard to inline `Map` scalars in the `recommended_key` (instead of `#2 + #2` we will save `#0 + #1 + #0 + #1`).
3. Don't allow hints where the `recommended_key` support is not directly referencing the indexed `GlobalId`.

**Comment by aalexandrov** [comment]
As a side note, it's also kind of weird how in

```sql
EXPLAIN WITH(humanized_exprs)
SELECT * 
  FROM (SELECT * FROM (VALUES (1, 2))) AS t2 (f1, f2)
WHERE 
  t2.f2 < t2.f2;
```

the `t2.f2 < t2.f2` is simplified to `false`, but in the query above it isn't.

**Comment by ggevay** [comment]
> the t2.f2 < t2.f2 predicate is simplified to false, but in the query above it isn't.

This is because in the above query it's `a2.f2 * 2 < a2.f2 + 2`: one side is `*`, while the other is `+`.

> Overall it also seems that the notice emitted here is wrong - the literal equalities in the top line are `f2 = 1`, but in the recommended literal equalities are `(f2, (#2 + #2))`.

Actually, the hint part can sometimes legitimately recommend more columns then the top line mentions. (See [here in the code](https://github.com/MaterializeInc/materialize/blob/1c491c9ada3a2022ba4f56d1b6bab3577a62e167/src/transform/src/literal_constraints.rs#L312-L314) and an [example](https://github.com/MaterializeInc/materialize/blob/cb201a57af4e4d453a63a3995f400d835e90e761/test/sqllogictest/transform/notice/index_too_wide_for_literal_constraints.slt#L299).) This is because the top line always mentions a subset of an existing index key, while the recommended index key is not necessarily a subset of any existing index key. (And we couldn't simply mention the extra columns in the top line, because then the "is too wide to use for" part of the text message wouldn't match reality: it's not just that it's too wide, but also missing some cols. In theory, we could add a branch here that would change the text message in the top line in such a case to something like "is not optimal for", but I didn't want to complicate this even more.)

> There is a more general question whether we want to hints with such recommendations. Options are:

I think we should go with Option 2: try to inline until we reach the GlobalId's cols. (But not urgently, as this is probably a niche situation. It was important to fix the panic, but I'd say a notice that is hard to read in this case is ok for now.)

**Comment by ggevay** [comment]
I created an issue for implementing Option 2: https://github.com/MaterializeInc/materialize/issues/24321

**Comment by aalexandrov** [comment]
> This is because in the above query it's `a2.f2 * 2 < a2.f2 + 2`: one side is `*`, while the other is `+`.
> 

I was talking about the original query which has a predicate `a2.f2 < a2.f2` which expands to `t1.f1 + t1.f2 < t1.f1 + t1.f2`. I changed this slightly in the regression test in my PR to `a2.f2 * 2 < a2.f2 + 2` in order to not break the test once we figure out why this is not simplifying to `false`.
