### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#24451]
### What version of Materialize are you using?

06c410ed8ca7632991d73c64da5dc90abe4cbb5b

### What is the issue?

```
06c410ed8ca7632991d73c64da5dc90abe4cbb5b is the first bad commit
commit 06c410ed8ca7632991d73c64da5dc90abe4cbb5b
Author: Gabor Gevay <gabor@materialize.com>
Date:   Tue Aug 1 17:00:06 2023 +0200

    Deprecate some old join code with a `soft_panic_or_log`
```

After this commit, the following panics:

```
CREATE TABLE "materialize"."public"."t1" ("f1" "pg_catalog"."int4", "f2" "pg_catalog"."int4" NOT NULL, "f3" "pg_catalog"."int4");
EXPLAIN WITH MUTUALLY RECURSIVE c1 (f1 INTEGER, f2 INTEGER, f3 INTEGER) AS (
  SELECT 
* 
  FROM 
    t1 
  UNION ALL 
    (
      SELECT 
        a1.f2 + 2 AS f1, 
        a1.f1 + a1.f2 AS f2, 
        a1.f3 + a1.f2 AS f3 
      FROM 
        c2 AS a1 
        JOIN c2 AS a2 USING (f3)
       WHERE 
        a1.f3 < 100 
    )
), 
c2 (f1 INTEGER, f2 INTEGER, f3 INTEGER) AS (
  SELECT 
0,0,0  
  UNION ALL 
    (
      SELECT 
        * 
      FROM 
        c2 WHERE 
        f3 < 100 
    )
)
SELECT 
  * 
FROM 
  c1;
```

```
thread 'coordinator' panicked at src/transform/src/dataflow.rs:1158:13:
CollectIndexRequests encountered a dangling ArrangeBy
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: <mz_transform::dataflow::IndexUsageContext>::add_keys
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0f174a9c99badb372-1/materialize/tests/src/transform/src/dataflow.rs:1158:13
   3: <mz_transform::dataflow::CollectIndexRequests>::collect_index_reqs_inner::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0f174a9c99badb372-1/materialize/tests/src/transform/src/dataflow.rs:931:59
   4: <mz_transform::dataflow::CollectIndexRequests as mz_ore::stack::CheckedRecursion>::checked_recur_mut::<<mz_transform::dataflow::CollectIndexRequests>::collect_index_reqs_inner::{closure#0}, (), mz_ore::stack::RecursionLimitError>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0f174a9c99badb372-1/materialize/tests/src/ore/src/stack.rs:205:33
   5: stacker::maybe_grow::<core::result::Result<(), mz_ore::stack::RecursionLimitError>, <mz_transform::dataflow::CollectIndexRequests as mz_ore::stack::CheckedRecursion>::checked_recur_mut<<mz_transform::dataflow::CollectIndexRequests>::collect_index_reqs_inner::{closure#0}, (), mz_ore::stack::RecursionLimitError>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
   6: mz_ore::stack::maybe_grow::<<mz_transform::dataflow::CollectIndexRequests as mz_ore::stack::CheckedRecursion>::checked_recur_mut<<mz_transform::dataflow::CollectIndexRequests>::collect_index_reqs_inner::{closure#0}, (), mz_ore::stack::RecursionLimitError>::{closure#0}, core::result::Result<(), mz_ore::stack::RecursionLimitError>>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0f174a9c99badb372-1/materialize/tests/src/ore/src/stack.rs:100:5
```

**Comment by philip-stoev** [comment]
This affects any query that the RQG grammar is generating that has an expression in the SELECT list, that involves:
- an aggregate function
- more than 1 column
- more than 1 arithmetic operator , even if most of their arguments are constants (`f1 + 1 + 1`)

**Comment by philip-stoev** [comment]
Once this is fixed, please re-enable all the commented-out parts of `conf/mz/with-mutually-recursive.yy` in the `MaterializeInc/RQG` repository and then update `test/rqg/Dockerfile` in the Materialize repository.

**Comment by ggevay** [comment]
I debugged this, and it turns out that this is a bug in `NormalizeLets`: For the query in the issue description, just before a certain `NormalizeLets` run, this is the plan:
```
  Return
    Get l0
  With Mutually Recursive
    cte l1 =
      Union
        Get l1
        Map (0, 0, 0)
          Constant
            - ()
   cte l0 =
     Union
       Get materialize.public.t1
       Map (2, 0, 0)
         CrossJoin type=differential
           implementation
             %0:l1[×] » %1:l1[×]
           ArrangeBy keys=[[]]
             Project ()
               Get l1
           ArrangeBy keys=[[]]
             Project ()
               Get l1
 
 Target cluster: mz_catalog_server
```
Then after `NormalizeLets`:
```
Return
  Union
    Get materialize.public.t1
    Map (2, 0, 0)
      CrossJoin type=differential
        implementation
          %0:l0[×] » %1:l0[×]
        Get l0
        Get l0
With Mutually Recursive
  cte l1 =
    Union
      Get l1
      Map (0, 0, 0)
        Constant
          - ()
  cte l0 =
    ArrangeBy keys=[[]]
      Project ()
        Get l1

Target cluster: mz_catalog_server
```
The problem here is that when there is an `ArrangeBy` at the top of a cte inside a `LetRec`, but the `Join` that the `ArrangeBy` belongs to is in the body of the `LetRec`, then we don't use the arrangement (because we can't export it from the WMR scope), and just sneakily build a new arrangement during the join rendering. (This is what happens in production, but in CI we crash on 2 `soft_assert`s in this situation, frustrating test frameworks.)

The `soft_assert`s:
- Dangling `ArrangeBy`, i.e. an `ArrangeBy` that nobody will use: https://github.com/MaterializeInc/materialize/blob/d7d553fef0f2efb1f701c2c9a2016dd7c5ac0eb2/src/transform/src/dataflow.rs#L1138
- https://github.com/MaterializeInc/materialize/blob/d7d553fef0f2efb1f701c2c9a2016dd7c5ac0eb2/src/compute-types/src/plan/lowering.rs#L510

**Comment by ggevay** [comment]
I can see 2 ways how this happens in `NormalizeLets`:
1. (This is what happens in the query in the issue description.) `inline_lets` can move a Join from a cte to the body, when the body had a Get, and that's the only Get of this cte. However, if this join has an input where the `ArrangeBy` is hidden behind a `Get`, then the cte of the `ArrangeBy` can remain in the `LetRec`.
2. `harvest_nonrec_suffix` might also make the same mistake of pulling out a `Join`, but not pulling out the cte that has the `Join`'s `ArrangeBy`.

We could separately fix 1. and 2. to not make this bad situation arise. However, `NormalizeLets` moves around stuff quite a bit, so it seems hard to make sure that there are no 3. and 4. and ... ways in which `NormalizeLets` can make this situation arise. So maybe it's better to just do an extra pass at the end where we detect this situation after it is already there, and quickly fix it by moving out the `ArrangeBy` from the cte to the body. Notes on how to do this :
- We need to be careful that if the `ArrangeBy` is used also by a cte that remained inside the `LetRec`, then don't remove the original `ArrangeBy`, but just copy it to the body.
- If the join refers to the same cte more than once, then we'll want to introduce a new cte _in the body_ for this `ArrangeBy`, in order to keep `NormalizeLets` idempotent.
