### ISSUE TITLE
regression: panic with LATERAL JOIN after optimizer: Flag for controlling join planning (#23318)

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#24511]
ci-regexp: join with only one input

### What version of Materialize are you using?

a45e0aa38e8041b814a1b7a0357db6669187d104

### What is the issue?

This panics and was bisected to the commit in the title . The query is simplified as much as possible, though the schema may contain unnecessary items:

```
SET cluster=default;

DROP SCHEMA public CASCADE;

CREATE SCHEMA public;

DROP TABLE IF EXISTS t1 CASCADE;
DROP TABLE IF EXISTS t2 CASCADE;
DROP TABLE IF EXISTS t3 CASCADE;

CREATE TABLE t1 (f1 DOUBLE PRECISION, f2 DOUBLE PRECISION NOT NULL);
CREATE INDEX t1i1 ON t1(f1);
CREATE INDEX t1i2 ON t1(f2, f1);

-- one NULL row in t1

INSERT INTO t1 VALUES (NULL, 0);

-- values 1 and 2 have 2 rows each in t1

INSERT INTO t1 VALUES (1, 1);
INSERT INTO t1 VALUES (1, 1);
INSERT INTO t1 VALUES (2, 2);
INSERT INTO t1 VALUES (2, 2);
INSERT INTO t1 VALUES (3, 3);
INSERT INTO t1 VALUES (4, 4);
INSERT INTO t1 VALUES (5, 5);
INSERT INTO t1 VALUES (6, 6);
INSERT INTO t1 VALUES (7, 7);
INSERT INTO t1 VALUES (8, 8);

-- value 9 not present in either table

CREATE TABLE t2 (f1 DOUBLE PRECISION, f2 DOUBLE PRECISION NOT NULL);
CREATE INDEX t2i1 ON t2(f1);
CREATE INDEX i2i2 ON t2(f2, f1);

-- two NULL rows in t2

INSERT INTO t2 VALUES (NULL, 0);
INSERT INTO t2 VALUES (NULL, 0);

INSERT INTO t2 VALUES (1, 1);

-- value 2 has 2 rows in t2
INSERT INTO t2 VALUES (2, 2);
INSERT INTO t2 VALUES (2, 2);

-- value 3 has no rows in t2
INSERT INTO t2 VALUES (4, 4);
INSERT INTO t2 VALUES (5, 5);
INSERT INTO t2 VALUES (6, 6);
INSERT INTO t2 VALUES (7, 7);
INSERT INTO t2 VALUES (8, 8);

-- value 9 not present in either table

CREATE TABLE t3 (f1 DOUBLE PRECISION, f2 DOUBLE PRECISION NOT NULL);
CREATE INDEX t3i1 ON t2(f1);
CREATE INDEX i3i2 ON t2(f2, f1);


CREATE MATERIALIZED VIEW pk1 AS SELECT DISTINCT ON (f1) f1 , f2 FROM t1 WHERE f1 IS NOT NULL AND f2 IS NOT NULL;
CREATE MATERIALIZED VIEW pk2 AS SELECT DISTINCT ON (f1) f1 , f2 FROM t2 WHERE f1 IS NOT NULL AND f2 IS NOT NULL;
CREATE MATERIALIZED VIEW pk3 AS SELECT DISTINCT ON (f1) f1 , f2 FROM t3 WHERE f1 IS NOT NULL AND f2 IS NOT NULL;



 SELECT 
      left_object.f1 AS f1, 
      left_object.f1 AS f2 
    FROM 
      (
        SELECT 
          DISTINCT f2 AS f1, 
          f2 AS f2 
        FROM 
          t1
      ) AS left_object 
      LEFT JOIN pk1 AS before ON (left_object.f1 = before.f1) 
       JOIN LATERAL (
        SELECT 
          f2 AS f1, 
          f1 AS f2 
        FROM 
          t2 
        LIMIT 
          left_object.f1
      ) AS right_object ON (left_object.f2 = right_object.f1) ;
```

Note that the feature flag for the PR is **OFF** and the issue is still reproducible.

```
hread 'coordinator' panicked at src/transform/src/join_implementation.rs:480:17:
join with only one input (should be filter)
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: <mz_transform::join_implementation::JoinImplementation>::action
   3: <mz_transform::join_implementation::JoinImplementation>::action_recursive::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/transform/src/join_implementation.rs:120:17
   4: <mz_transform::join_implementation::JoinImplementation as mz_ore::stack::CheckedRecursion>::checked_recur::<<mz_transform::join_implementation::JoinImplementation>::action_recursive::{closure#0}, (), mz_transform::TransformError>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/ore/src/stack.rs:191:33
   5: stacker::maybe_grow::<core::result::Result<(), mz_transform::TransformError>, <mz_transform::join_implementation::JoinImplementation as mz_ore::stack::CheckedRecursion>::checked_recur<<mz_transform::join_implementation::JoinImplementation>::action_recursive::{closure#0}, (), mz_transform::TransformError>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
   6: mz_ore::stack::maybe_grow::<<mz_transform::join_implementation::JoinImplementation as mz_ore::stack::CheckedRecursion>::checked_recur<<mz_transform::join_implementation::JoinImplementation>::action_recursive::{closure#0}, (), mz_transform::TransformError>::{closure#0}, core::result::Result<(), mz_transform::TransformError>>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/ore/src/stack.rs:100:5
   7: <mz_transform::join_implementation::JoinImplementation as mz_ore::stack::CheckedRecursion>::checked_recur::<<mz_transform::join_implementation::JoinImplementation>::action_recursive::{closure#0}, (), mz_transform::TransformError>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/ore/src/stack.rs:191:19
   8: <mz_transform::join_implementation::JoinImplementation>::action_recursive
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/transform/src/join_implementation.rs:94:9
   9: <mz_transform::join_implementation::JoinImplementation as mz_transform::Transform>::transform
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/transform/src/join_implementation.rs:71:22
  10: <mz_transform::Fixpoint as mz_transform::Transform>::transform::{closure#1}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/transform/src/lib.rs:277:25
  11: <tracing::span::Span>::in_scope::<<mz_transform::Fixpoint as mz_transform::Transform>::transform::{closure#1}, core::result::Result<(), mz_transform::TransformError>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/span.rs:1102:9
  12: <mz_transform::Fixpoint as mz_transform::Transform>::transform
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/transform/src/lib.rs:275:17
  13: <mz_transform::Optimizer>::transform
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/transform/src/lib.rs:660:13
  14: mz_transform::dataflow::optimize_dataflow_relations
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/transform/src/dataflow.rs:235:9
  15: mz_transform::dataflow::optimize_dataflow
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/transform/src/dataflow.rs:90:5
  16: <mz_adapter::optimize::peek::Optimizer as mz_adapter::optimize::Optimize<mz_adapter::optimize::peek::LocalMirPlan<mz_adapter::optimize::peek::ResolvedLocal>>>::optimize
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/adapter/src/optimize/peek.rs:302:23
  17: <mz_adapter::coord::Coordinator>::explain_query_optimizer_pipeline::{closure#0}::{closure#0}::{closure#3}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:2315:35
  18: mz_adapter::coord::sequencer::inner::catch_unwind::<(mz_repr::explain::UsedIndexes, core::option::Option<mz_adapter::coord::peek::FastPathPlan>, mz_transform::dataflow::DataflowMetainfo), mz_adapter::error::AdapterError, <mz_adapter::coord::Coordinator>::explain_query_optimizer_pipeline::{closure#0}::{closure#0}::{closure#3}>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:4969:9
  19: <mz_adapter::coord::Coordinator>::explain_query_optimizer_pipeline::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:2312:55
  20: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::explain_query_optimizer_pipeline::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  21: <mz_adapter::coord::Coordinator>::explain_query_optimizer_pipeline::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:2185:5
  22: <tracing::instrument::WithDispatch<<mz_adapter::coord::Coordinator>::explain_query_optimizer_pipeline::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:329:9
  23: <mz_adapter::coord::Coordinator>::explain_statement::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:2032:18
  24: <mz_adapter::coord::Coordinator>::sequence_explain_plan::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:1822:88
  25: <mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/adapter/src/coord/sequencer.rs:324:75
  26: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  27: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
  28: <mz_adapter::coord::Coordinator>::handle_execute_inner::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/adapter/src/coord/command_handler.rs:771:73
  29: <mz_adapter::coord::Coordinator>::handle_execute_inner::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/adapter/src/coord/command_handler.rs:447:5
  30: <mz_adapter::coord::Coordinator>::handle_execute::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/adapter/src/coord/command_handler.rs:444:54
  31: <mz_adapter::coord::Coordinator>::handle_execute::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/adapter/src/coord/command_handler.rs:345:5
  32: <mz_adapter::coord::Coordinator>::handle_command::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/adapter/src/coord/command_handler.rs:111:26
  33: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_command::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  34: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
  35: <mz_adapter::coord::Coordinator>::message_command::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/adapter/src/coord/message_handler.rs:344:34
  36: <mz_adapter::coord::Coordinator>::message_command::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/adapter/src/coord/message_handler.rs:341:5
  37: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::message_command::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  38: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/adapter/src/coord/message_handler.rs:70:64
  39: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_message::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  40: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
  41: <mz_adapter::coord::Coordinator>::serve::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/adapter/src/coord.rs:2500:48
  42: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
  43: <tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  44: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  45: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  46: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  47: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  48: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  49: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:310:13
  50: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::handle::Handle>::block_on<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>::{closure#0}, ()>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  51: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:309:9
  52: mz_adapter::coord::serve::{closure#0}::{closure#2}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-04cd5523f38f360c9-1/materialize/tests/src/adapter/src/coord.rs:2901:21

```

**Comment by ggevay** [comment]
I'll look at this now.

**Comment by ggevay** [comment]
Btw. I'm somehow getting a slightly different panic:
```
thread 'tokio:work-56' panicked at src/transform/src/join_implementation.rs:849:36:
attempt to subtract with overflow
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:127:5
   3: mz_transform::join_implementation::differential::plan
             at ./src/transform/src/join_implementation.rs:849:36
   4: mz_transform::join_implementation::JoinImplementation::action
             at ./src/transform/src/join_implementation.rs:458:76
   5: mz_transform::join_implementation::JoinImplementation::action_recursive::{{closure}}
             at ./src/transform/src/join_implementation.rs:120:17
   6: mz_ore::stack::CheckedRecursion::checked_recur::{{closure}}
             at ./src/ore/src/stack.rs:191:33
   7: stacker::maybe_grow
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/l
```
This is for the expression `inputs.len() - 2`, so the root cause is probably the same.

**Comment by ggevay** [comment]
I used to think that a 1-input join probably can't occur by the time we reach `JoinImplementation`, but I was never sure, and I never dared to put in a soft_assert for this. But https://github.com/MaterializeInc/materialize/pull/23318 sneaked in a soft_assert, so now we know that this can actually occur :)

Opened a PR to fix it: https://github.com/MaterializeInc/materialize/pull/24513

**Comment by mgree** [comment]
Well, that's one way to clear up whether it's an invariant! 💀

Thank you, @ggevay, for attending to this when I'm OoO!
