### ISSUE TITLE
thread 'main' panicked at src/catalog/src/durable/impls/shadow.rs:562:13: assertion `left == right` failed

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#24523]
### What version of Materialize are you using?

69cd724a76a6

### What is the issue?

Happened in https://buildkite.com/materialize/tests/builds/73365#018d1cff-9f4c-46b4-9e5b-820229c6f2d4
```
storage-usage-materialized-1  | thread 'main' panicked at src/catalog/src/durable/impls/shadow.rs:562:13:
storage-usage-materialized-1  | assertion `left == right` failed
[...]
storage-usage-materialized-1  | stack backtrace:
storage-usage-materialized-1  |    0: rust_begin_unwind
storage-usage-materialized-1  |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
storage-usage-materialized-1  |    1: core::panicking::panic_fmt
storage-usage-materialized-1  |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
storage-usage-materialized-1  |    2: core::panicking::assert_failed_inner
storage-usage-materialized-1  |    3: core::panicking::assert_failed::<alloc::vec::Vec<mz_audit_log::VersionedStorageUsage>, alloc::vec::Vec<mz_audit_log::VersionedStorageUsage>>
storage-usage-materialized-1  |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:270:5
storage-usage-materialized-1  |    4: <mz_catalog::durable::impls::shadow::ShadowCatalogState as mz_catalog::durable::DurableCatalogState>::get_and_prune_storage_usage::{closure#0}
storage-usage-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-099cbedbd592430ab-1/materialize/tests/src/catalog/src/durable/impls/shadow.rs:562:13
storage-usage-materialized-1  |    5: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<alloc::vec::Vec<mz_audit_log::VersionedStorageUsage>, mz_catalog::durable::error::CatalogError>> + core::marker::Send>> as core::future::future::Future>::poll
storage-usage-materialized-1  |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
storage-usage-materialized-1  |    6: <mz_adapter::catalog::Catalog>::open::{closure#0}
storage-usage-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-099cbedbd592430ab-1/materialize/tests/src/adapter/src/catalog/open.rs:1059:18
storage-usage-materialized-1  |    7: <tracing::instrument::Instrumented<<mz_adapter::catalog::Catalog>::open::{closure#0}> as core::future::future::Future>::poll
storage-usage-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
storage-usage-materialized-1  |    8: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(mz_adapter::catalog::Catalog, mz_adapter::catalog::open::BuiltinMigrationMetadata, alloc::vec::Vec<mz_adapter::catalog::builtin_table_updates::BuiltinTableUpdate>, alloc::string::String), mz_adapter::error::AdapterError>> + core::marker::Send>> as core::future::future::Future>::poll
storage-usage-materialized-1  |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
storage-usage-materialized-1  |    9: mz_adapter::coord::serve::{closure#0}
storage-usage-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-099cbedbd592430ab-1/materialize/tests/src/adapter/src/coord.rs:2776:14
storage-usage-materialized-1  |   10: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(mz_adapter::client::Handle, mz_adapter::client::Client), mz_adapter::error::AdapterError>> + core::marker::Send>> as core::future::future::Future>::poll
storage-usage-materialized-1  |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
storage-usage-materialized-1  |   11: <mz_environmentd::Listeners>::serve::{closure#0}::{closure#0}
storage-usage-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-099cbedbd592430ab-1/materialize/tests/src/environmentd/src/lib.rs:613:10
storage-usage-materialized-1  |   12: <tracing::instrument::Instrumented<<mz_environmentd::Listeners>::serve::{closure#0}::{closure#0}> as core::future::future::Future>::poll
storage-usage-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
storage-usage-materialized-1  |   13: <mz_environmentd::Listeners>::serve::{closure#0}
storage-usage-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-099cbedbd592430ab-1/materialize/tests/src/environmentd/src/lib.rs:298:5
storage-usage-materialized-1  |   14: environmentd::run::{closure#11}
storage-usage-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-099cbedbd592430ab-1/materialize/tests/src/environmentd/src/bin/environmentd/main.rs:948:14
storage-usage-materialized-1  |   15: <tracing::instrument::Instrumented<environmentd::run::{closure#11}> as core::future::future::Future>::poll
storage-usage-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
storage-usage-materialized-1  |   16: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}
storage-usage-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
storage-usage-materialized-1  |   17: tokio::runtime::coop::with_budget::<core::task::poll::Poll<core::result::Result<mz_environmentd::Server, anyhow::Error>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}>
storage-usage-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
storage-usage-materialized-1  |   18: tokio::runtime::coop::budget::<core::task::poll::Poll<core::result::Result<mz_environmentd::Server, anyhow::Error>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}>
storage-usage-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
storage-usage-materialized-1  |   19: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>
storage-usage-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
storage-usage-materialized-1  |   20: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>
storage-usage-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
storage-usage-materialized-1  |   21: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}
storage-usage-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
storage-usage-materialized-1  |   22: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::scheduler::multi_thread::MultiThread>::block_on<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}, core::result::Result<mz_environmentd::Server, anyhow::Error>>
storage-usage-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
storage-usage-materialized-1  |   23: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>
storage-usage-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
storage-usage-materialized-1  |   24: <tokio::runtime::runtime::Runtime>::block_on::<environmentd::run::{closure#11}>
storage-usage-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/runtime.rs:349:50
storage-usage-materialized-1  |   25: environmentd::run
storage-usage-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-099cbedbd592430ab-1/materialize/tests/src/environmentd/src/bin/environmentd/main.rs:870:18
storage-usage-materialized-1  |   26: environmentd::main
storage-usage-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-099cbedbd592430ab-1/materialize/tests/src/environmentd/src/bin/environmentd/main.rs:561:23
storage-usage-materialized-1  |   27: <fn() as core::ops::function::FnOnce<()>>::call_once
storage-usage-materialized-1  |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
storage-usage-materialized-1  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
The actual difference is:
```
1844a1845,1846
> V1(StorageUsageV1 { id: 923, shard_id: Some("s005fb90d-2a56-4430-9ee5-a1f7577ef5c2"),
> size_bytes: 15939, collection_timestamp: 1705588892021 }),
```

I see that there is a restart in this test, so probably the shadow catalog doesn't make sense. @jkosh44 does that sound right? I'll disable it.

**Comment by jkosh44** [comment]
> I see that there is a restart in this test, so probably the shadow catalog doesn't make sense. @jkosh44 does that sound right?

This actually looks like something else. Restarts should be OK as long as it's not killed in the middle of an operation.

**Comment by jkosh44** [comment]
I have a repro of this locally, it looks like it's just a bug in the shadow catalog itself, not in either of the underlying catalogs. I'll have a fix shortly.
