### ISSUE TITLE
panic in src/runtime/task/state.rs when using Kafka with SSH in CI

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#24858]
### What version of Materialize are you using?

cecc217da9c296e7f0a2f10cc420c702d8f17b00

### What is the issue?

```
platform-checks-materialized-1      | thread '<unnamed>' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/state.rs:377:13:
platform-checks-materialized-1      | assertion failed: curr.is_join_interested()
platform-checks-materialized-1      | stack backtrace:
platform-checks-materialized-1      |    0: rust_begin_unwind
platform-checks-materialized-1      |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
platform-checks-materialized-1      |    1: core::panicking::panic_fmt
platform-checks-materialized-1      |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
platform-checks-materialized-1      |    2: core::panicking::panic
platform-checks-materialized-1      |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:127:5
platform-checks-materialized-1      |    3: <tokio::runtime::task::state::State>::unset_join_interested::{closure#0}
platform-checks-materialized-1      |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/state.rs:377:13
platform-checks-materialized-1      |    4: <tokio::runtime::task::state::State>::fetch_update::<<tokio::runtime::task::state::State>::unset_join_interested::{closure#0}>
platform-checks-materialized-1      |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/state.rs:496:30
platform-checks-materialized-1      |    5: <tokio::runtime::task::state::State>::unset_join_interested
platform-checks-materialized-1      |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/state.rs:376:9
platform-checks-materialized-1      |    6: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<<mz_ssh_util::tunnel::SshTunnelConfig>::connect::{closure#0}::{closure#1}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::drop_join_handle_slow
platform-checks-materialized-1      |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:288:12
platform-checks-materialized-1      |    7: tokio::runtime::task::raw::drop_join_handle_slow::<tracing::instrument::Instrumented<<mz_ssh_util::tunnel::SshTunnelConfig>::connect::{closure#0}::{closure#1}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>
platform-checks-materialized-1      |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/raw.rs:306:5
platform-checks-materialized-1      |    8: <tokio::runtime::task::raw::RawTask>::drop_join_handle_slow
platform-checks-materialized-1      |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/raw.rs:224:18
platform-checks-materialized-1      |    9: <tokio::runtime::task::join::JoinHandle<()> as core::ops::drop::Drop>::drop
platform-checks-materialized-1      |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/join.rs:352:9
platform-checks-materialized-1      |   10: core::ptr::drop_in_place::<tokio::runtime::task::join::JoinHandle<()>>
platform-checks-materialized-1      |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ptr/mod.rs:497:1
platform-checks-materialized-1      |   11: core::ptr::drop_in_place::<mz_ore::task::AbortOnDropHandle<()>>
platform-checks-materialized-1      |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ptr/mod.rs:497:1
platform-checks-materialized-1      |   12: core::ptr::drop_in_place::<mz_ssh_util::tunnel::SshTunnelHandle>
platform-checks-materialized-1      |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ptr/mod.rs:497:1
platform-checks-materialized-1      |   13: <alloc::sync::Arc<mz_ssh_util::tunnel::SshTunnelHandle>>::drop_slow
platform-checks-materialized-1      |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/sync.rs:1751:18
platform-checks-materialized-1      | environmentd: 2024-01-31T12:43:38.534713Z  INFO mz_adapter::catalog::state: create materialized view materialize.public.window_functions_view1 (u431)
platform-checks-materialized-1      |   14: <alloc::sync::Arc<mz_ssh_util::tunnel::SshTunnelHandle> as core::ops::drop::Drop>::drop
platform-checks-materialized-1      |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/sync.rs:2407:13
platform-checks-materialized-1      |   15: core::ptr::drop_in_place::<alloc::sync::Arc<mz_ssh_util::tunnel::SshTunnelHandle>>
platform-checks-materialized-1      |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ptr/mod.rs:497:1
platform-checks-materialized-1      |   16: core::ptr::drop_in_place::<mz_ssh_util::tunnel_manager::ManagedSshTunnelHandle>
platform-checks-materialized-1      |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ptr/mod.rs:497:1
platform-checks-materialized-1      |   17: core::ptr::drop_in_place::<mz_kafka_util::client::BrokerRewriteHandle>
platform-checks-materialized-1      |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ptr/mod.rs:497:1
platform-checks-materialized-1      |   18: <mz_kafka_util::client::TunnelingClientContext<mz_storage::source::kafka::GlueConsumerContext> as rdkafka::client::ClientContext>::rewrite_broker_addr
platform-checks-materialized-1      |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0b06f5d1ff2e87579-1/materialize/tests/src/kafka-util/src/client.rs:493:53
platform-checks-materialized-1      | cluster-u1-replica-u1: 2024-01-31T12:43:38.583562Z  INFO mz_storage::sink::kafka: kafka-u235-sink: committing transaction for {1706705018561}
platform-checks-materialized-1      |   19: rdkafka::client::native_resolve_cb::<mz_kafka_util::client::TunnelingClientContext<mz_storage::source::kafka::GlueConsumerContext>>
platform-checks-materialized-1      |              at ./cargo/git/checkouts/rust-rdkafka-545566655b063b24/c729f89/src/client.rs:540:16
platform-checks-materialized-1      |   20: rd_getaddrinfo
platform-checks-materialized-1      |              at ./cargo/git/checkouts/rust-rdkafka-545566655b063b24/c729f89/rdkafka-sys/librdkafka/src/rdaddr.c:193:21
platform-checks-materialized-1      |   21: rd_kafka_broker_resolve
platform-checks-materialized-1      |              at ./cargo/git/checkouts/rust-rdkafka-545566655b063b24/c729f89/rdkafka-sys/librdkafka/src/rdkafka_broker.c:983:33
platform-checks-materialized-1      |   22: rd_kafka_broker_connect
platform-checks-materialized-1      |              at ./cargo/git/checkouts/rust-rdkafka-545566655b063b24/c729f89/rdkafka-sys/librdkafka/src/rdkafka_broker.c:2128:13
platform-checks-materialized-1      |   23: rd_kafka_broker_thread_main
platform-checks-materialized-1      |              at ./cargo/git/checkouts/rust-rdkafka-545566655b063b24/c729f89/rdkafka-sys/librdkafka/src/rdkafka_broker.c:5323:29
platform-checks-materialized-1      |   24: _thrd_wrapper_function
platform-checks-materialized-1      |              at ./cargo/git/checkouts/rust-rdkafka-545566655b063b24/c729f89/rdkafka-sys/librdkafka/src/tinycthread.c:576:9
platform-checks-materialized-1      |   25: <unknown>
platform-checks-materialized-1      |   26: <unknown>
platform-checks-materialized-1      | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

occurred in "Checks + Toggle persist catalog" of https://buildkite.com/materialize/nightlies/builds/6254#018d5f80-a75d-497b-a6bb-c46fe4882f33. Seems to be related to Kafka.
Note that a retry succeeded in CI.

ci-regexp: assertion failed: curr.is_join_interested()

**Comment by def-** [comment]
This might be related to the recent rdkafka segfaults!

**Comment by benesch** [comment]
Going to track this on the storage board; seems very closely related to https://github.com/MaterializeInc/materialize/issues/24864 even though this failed before https://github.com/MaterializeInc/materialize/pull/24784 AFAICT.

**Comment by def-** [comment]
Another occurrence: https://buildkite.com/materialize/nightlies/builds/6278#018d64be-ef11-42ba-9493-b0720c165cce

**Comment by guswynn** [comment]
This is wild, we are seeing a panic inside the `tokio` runtime, while dropping, an ssh tunnel handle?

**Comment by guswynn** [comment]
@benesch is it possible this is related to the new `Rdkafka` drop logic?

**Comment by benesch** [comment]
Likely, I'd say!

**Comment by def-** [comment]
Also seen in https://buildkite.com/materialize/nightlies/builds/6283#018d65dd-3ccf-412a-a9e9-d7b82d61fc3c with x86-64, so this is a regression and not related to switching to aarch64 on CI.

**Comment by nrainer-materialize** [comment]
Could https://github.com/MaterializeInc/materialize/issues/24901 be related?

**Comment by guswynn** [comment]
I suspect this is related to the segfaults we see in version 2.3.0 of librdkafka

**Comment by benesch** [comment]
> Could #24901 be related?

Almost surely.

**Comment by benesch** [comment]
Should be fixed by https://github.com/MaterializeInc/materialize/pull/24919.
