### ISSUE TITLE
segfault when running "Canary Deploy in Staging Cloud"

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#24869]
### What version of Materialize are you using?

22e95be1d98a8d305e80070058befdb78441a172

### What is the issue?

https://buildkite.com/materialize/nightlies/builds/6267#018d63b6-2de4-4a4f-98f5-c5c5bdb7fdf8

```
[New LWP 23]
[New LWP 9]
[New LWP 13]
[New LWP 7]
[New LWP 14]
[New LWP 10]
[New LWP 21]
[New LWP 12]
[New LWP 30]
[New LWP 11]
[New LWP 15]
[New LWP 8]
Core was generated by `testdrive --kafka-addr=pkc-n00kk.us-east-1.aws.confluent.cloud:9092 --schema-re'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055a03dc03675 in ?? ()
[Current thread is 1 (LWP 23)]
#0  0x000055a03dc03675 in ?? ()
No symbol table info available.
#1  0x00007fac759f6940 in ?? ()
No symbol table info available.
#2  0x00007fac759f6900 in ?? ()
No symbol table info available.
#3  0x00007fac759f6940 in ?? ()
No symbol table info available.
#4  0x00007fac759f68a8 in ?? ()
No symbol table info available.
#5  0x00000000000000fe in ?? ()
No symbol table info available.
#6  0x00007fac759f6e20 in ?? ()
No symbol table info available.
#7  0x00007fac759f6e20 in ?? ()
No symbol table info available.
#8  0x000055a03dbfc403 in ?? ()
No symbol table info available.
#9  0x00007fac759f6d10 in ?? ()
No symbol table info available.
#10 0x0000000000000000 in ?? ()
No symbol table info available.

Thread 12 (LWP 8):
#0  0x00007fac7f71c197 in ?? ()
#1  0x00007fac7edfa960 in ?? ()
#2  0x000001893f49e3c9 in ?? ()
#3  0x00007fac7f416630 in ?? ()
#4  0x00007fac7edfab20 in ?? ()
#5  0x0000000000000000 in ?? ()

Thread 11 (LWP 15):
#0  0x00007fac7f71c197 in ?? ()
#1  0x00007fac7b3f9970 in ?? ()
#2  0x000001893f49e3c9 in ?? ()
#3  0x00007fac7f4168a4 in ?? ()
#4  0x00007fac7b3f9b20 in ?? ()
#5  0x0000000000000000 in ?? ()

Thread 10 (LWP 11):
#0  0x00007fac7f7a9a3d in ?? ()
#1  0x000055a03ee9b1bc in ?? ()
#2  0x00007fac7dbfb3f0 in ?? ()
#3  0x00007fac7dbfbef8 in ?? ()
#4  0x3b9aca007dbfb3f0 in ?? ()
#5  0x00007fac7f21c1d8 in ?? ()
#6  0x00007fac7f21c1d0 in ?? ()
#7  0x0000000000000000 in ?? ()

Thread 9 (LWP 30):
#0  0x00007fac7f71c197 in ?? ()
#1  0x00007fac74ff78f8 in ?? ()
#2  0x0000010974ff83f0 in ?? ()
#3  0x00007fac76dff910 in ?? ()
#4  0x0000000000000000 in ?? ()

Thread 8 (LWP 12):
#0  0x00007fac7f7b0fde in ?? ()
#1  0x00007fac7f8c9488 in ?? ()
#2  0x0000000300000000 in ?? ()
#3  0x00007fac7f247000 in ?? ()
#4  0x0000004500000400 in ?? ()
#5  0x00007fac7f35bc00 in ?? ()
#6  0x000055a03cb0e9e3 in ?? ()
#7  0x00007fac7d9f9798 in ?? ()
#8  0x0000000000000000 in ?? ()

Thread 7 (LWP 21):
#0  0x00007fac7f71c197 in ?? ()
#1  0x0000000000000000 in ?? ()

Thread 6 (LWP 10):
#0  0x00007fac7f7a9a3d in ?? ()
#1  0x000055a03ee9b1bc in ?? ()
#2  0x00007fac7e1f93f0 in ?? ()
#3  0x00007fac7e1f9ef8 in ?? ()
#4  0x3b9aca007e1f93f0 in ?? ()
#5  0x00007fac7f21c118 in ?? ()
#6  0x00007fac7f21c110 in ?? ()
#7  0x0000000000000000 in ?? ()

Thread 5 (LWP 14):
#0  0x00007fac7f71c197 in ?? ()
#1  0x0000000000000000 in ?? ()

Thread 4 (LWP 7):
#0  0x000055a03f72fe51 in ?? ()
#1  0x00007ffed82b7a50 in ?? ()
#2  0x00007ffed82b70a8 in ?? ()
#3  0x00007ffed82b70a0 in ?? ()
#4  0x0000000000000000 in ?? ()

Thread 3 (LWP 13):
#0  0x00007fac7f71c197 in ?? ()
#1  0x00007fac7d1fa970 in ?? ()
#2  0x000001893f49e3c9 in ?? ()
#3  0x00007fac7f416704 in ?? ()
#4  0x00007fac7d1fab20 in ?? ()
#5  0x0000000000000000 in ?? ()

Thread 2 (LWP 9):
#0  0x00007fac7f7a9a3d in ?? ()
#1  0x000055a03ee9b1bc in ?? ()
#2  0x000000000000000d in ?? ()
#3  0x00007fac7e3faef8 in ?? ()
#4  0x3b9aca007f29f1a8 in ?? ()
#5  0x00007fac7f21c0b8 in ?? ()
#6  0x00007fac7f21c0b0 in ?? ()
#7  0x0000000000000000 in ?? ()

Thread 1 (LWP 23):
#0  0x000055a03dc03675 in ?? ()
#1  0x00007fac759f6940 in ?? ()
#2  0x00007fac759f6900 in ?? ()
#3  0x00007fac759f6940 in ?? ()
#4  0x00007fac759f68a8 in ?? ()
#5  0x00000000000000fe in ?? ()
#6  0x00007fac759f6e20 in ?? ()
#7  0x00007fac759f6e20 in ?? ()
#8  0x000055a03dbfc403 in ?? ()
#9  0x00007fac759f6d10 in ?? ()
#10 0x0000000000000000 in ?? ()
```

**Comment by nrainer-materialize** [comment]
Bisecting the cause...

**Comment by nrainer-materialize** [comment]
Caused by: https://github.com/MaterializeInc/materialize/commit/22387837d7ea7702775d59468394de778e5c83b7

**Comment by nrainer-materialize** [comment]
This was caused by https://github.com/MaterializeInc/materialize/pull/24784; it was reverted.
