### ISSUE TITLE
thread 'coordinator' panicked at src/adapter/src/catalog.rs: all dropped_notices entries have `Arc::strong_count(_) == 1

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#24884]
### What version of Materialize are you using?

97ff6eb84ad1d04759a4b69100f469a420461fa4

### What is the issue?

SQLancer QueryPartitioning in [builds/6270](https://buildkite.com/materialize/nightlies/builds/6270#018d63bb-4323-4a55-9bb6-ca02b2601df2):

```
$ docker compose run --detach sqlancer --random-seed 2056923865 --host materialized --port 6875 --username materialize --timeout-seconds 1500 --num-tries 100000 --num-threads 4 --qpg-enable True --random-string-generation ALPHANUMERIC_SPECIALCHAR materialize --oracle QUERY_PARTITIONING
```

```
sqlancer-materialized-1  | environmentd: 2024-02-01T08:30:42.419801Z  INFO message_command: mz_adapter::catalog::state: drop index database3.public.i0 (u21)
sqlancer-materialized-1  | thread 'coordinator' panicked at src/adapter/src/catalog.rs:293:9:
sqlancer-materialized-1  | all dropped_notices entries have `Arc::strong_count(_) == 1`
sqlancer-materialized-1  | stack backtrace:
sqlancer-materialized-1  |    0: rust_begin_unwind
sqlancer-materialized-1  |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
sqlancer-materialized-1  |    1: core::panicking::panic_fmt
sqlancer-materialized-1  |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
sqlancer-materialized-1  |    2: <mz_adapter::catalog::Catalog>::drop_plans_and_metainfos
sqlancer-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e76f3cb7ce326512-1/materialize/tests/src/adapter/src/catalog.rs:293:9
sqlancer-materialized-1  |    3: <mz_adapter::catalog::Catalog>::transact::<<mz_adapter::coord::Coordinator>::catalog_transact_with<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#1}, ()>::{closure#0}::{closure#0}::{closure#10}, ()>::{closure#0}::{closure#0}
sqlancer-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e76f3cb7ce326512-1/materialize/tests/src/adapter/src/catalog.rs:1248:31
sqlancer-materialized-1  |    4: <mz_adapter::catalog::Catalog>::transact::<<mz_adapter::coord::Coordinator>::catalog_transact_with<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#1}, ()>::{closure#0}::{closure#0}::{closure#10}, ()>::{closure#0}
sqlancer-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e76f3cb7ce326512-1/materialize/tests/src/adapter/src/catalog.rs:1177:5
sqlancer-materialized-1  |    5: <mz_adapter::coord::Coordinator>::catalog_transact_with::<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#1}, ()>::{closure#0}::{closure#0}
sqlancer-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e76f3cb7ce326512-1/materialize/tests/src/adapter/src/coord/ddl.rs:520:14
sqlancer-materialized-1  |    6: <mz_adapter::coord::Coordinator>::catalog_transact_with::<<mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}::{closure#1}, ()>::{closure#0}
sqlancer-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e76f3cb7ce326512-1/materialize/tests/src/adapter/src/coord/ddl.rs:192:5
sqlancer-materialized-1  |    7: <mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}::{closure#0}
sqlancer-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e76f3cb7ce326512-1/materialize/tests/src/adapter/src/coord/ddl.rs:81:14
sqlancer-materialized-1  |    8: <mz_adapter::coord::Coordinator>::catalog_transact::{closure#0}
sqlancer-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e76f3cb7ce326512-1/materialize/tests/src/adapter/src/coord/ddl.rs:73:5
sqlancer-materialized-1  |    9: <mz_adapter::coord::Coordinator>::sequence_drop_objects::{closure#0}
sqlancer-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e76f3cb7ce326512-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:895:51
sqlancer-materialized-1  |   10: <mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}
sqlancer-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e76f3cb7ce326512-1/materialize/tests/src/adapter/src/coord/sequencer.rs:228:86
sqlancer-materialized-1  |   11: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::sequence_plan::{closure#0}> as core::future::future::Future>::poll
sqlancer-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
sqlancer-materialized-1  |   12: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
sqlancer-materialized-1  |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
sqlancer-materialized-1  |   13: <mz_adapter::coord::Coordinator>::handle_execute_inner::{closure#0}::{closure#0}
sqlancer-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e76f3cb7ce326512-1/materialize/tests/src/adapter/src/coord/command_handler.rs:771:73
sqlancer-materialized-1  |   14: <mz_adapter::coord::Coordinator>::handle_execute_inner::{closure#0}
sqlancer-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e76f3cb7ce326512-1/materialize/tests/src/adapter/src/coord/command_handler.rs:449:5
sqlancer-materialized-1  |   15: <mz_adapter::coord::Coordinator>::handle_execute::{closure#0}::{closure#0}
sqlancer-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e76f3cb7ce326512-1/materialize/tests/src/adapter/src/coord/command_handler.rs:446:54
sqlancer-materialized-1  |   16: <mz_adapter::coord::Coordinator>::handle_execute::{closure#0}
sqlancer-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e76f3cb7ce326512-1/materialize/tests/src/adapter/src/coord/command_handler.rs:347:5
sqlancer-materialized-1  |   17: <mz_adapter::coord::Coordinator>::handle_command::{closure#0}
sqlancer-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e76f3cb7ce326512-1/materialize/tests/src/adapter/src/coord/command_handler.rs:113:26
sqlancer-materialized-1  |   18: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_command::{closure#0}> as core::future::future::Future>::poll
sqlancer-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
sqlancer-materialized-1  |   19: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
sqlancer-materialized-1  |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
sqlancer-materialized-1  |   20: <mz_adapter::coord::Coordinator>::message_command::{closure#0}::{closure#0}
sqlancer-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e76f3cb7ce326512-1/materialize/tests/src/adapter/src/coord/message_handler.rs:344:34
sqlancer-materialized-1  |   21: <mz_adapter::coord::Coordinator>::message_command::{closure#0}
sqlancer-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e76f3cb7ce326512-1/materialize/tests/src/adapter/src/coord/message_handler.rs:341:5
sqlancer-materialized-1  |   22: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::message_command::{closure#0}> as core::future::future::Future>::poll
sqlancer-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
sqlancer-materialized-1  |   23: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
sqlancer-materialized-1  |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e76f3cb7ce326512-1/materialize/tests/src/adapter/src/coord/message_handler.rs:70:64
sqlancer-materialized-1  |   24: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_message::{closure#0}> as core::future::future::Future>::poll
sqlancer-materialized-1  |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
sqlancer-materialized-1  |   25: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
sqlancer-materialized-1  |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
```

ci-regexp: all dropped_notices entries have

**Comment by def-** [comment]
I tried running the queries from SQLancer but that didn't cause the panic: https://gist.github.com/def-/67bb918263ff52d71ddcffb8fd429041

**Comment by nrainer-materialize** [comment]
CC @danhhz

**Comment by aalexandrov** [comment]
It seems that my notice cleanup logic fails to clean up everything in some extreme situations. By itself, this should not be very urgent (we should at most spent a few more KBs of memory in every release cycle).

It would be interesting to track if this happens only on ARM, or also on Intel machines.

**Comment by def-** [comment]
This is now happening in production on 0.85.2! ^

**Comment by def-** [comment]
From SQLancer PQS: https://buildkite.com/materialize/nightlies/builds/6368#018d8b33-d151-4fbe-9beb-8c4da858503c
```
sqlancer-materialized-1  | environmentd: 2024-02-08T23:36:15.603145Z  INFO message_command:coord::handle_execute{session="57ddbed7-8de3-40ed-b710-5d893eae103f"}:coord::handle_execute_inner{stmt="CREATE TABLE IF NOT EXISTS t0 (c0 bool)"}:sequence_create_table:coord::catalog_transact_with_side_effects:coord::catalog_transact_with:catalog::transact:catalog::transact_inner: mz_adapter::catalog::state: create table database1.public.t0 (u29)
sqlancer-materialized-1  | cluster-u1-replica-u1: 2024-02-08T23:36:15.645090Z  INFO mz_persist_client::internal::machine: snapshot sf0925e8b-7c2d-48e1-a1e8-2dea4a71003e as of [1707435371577] now available
sqlancer-materialized-1  | cluster-u1-replica-u1: 2024-02-08T23:36:15.645317Z  INFO mz_persist_client::internal::machine: snapshot sf0925e8b-7c2d-48e1-a1e8-2dea4a71003e as of [1707435372633] now available
sqlancer-materialized-1  | cluster-u1-replica-u1: 2024-02-08T23:36:15.791519Z  INFO mz_persist_client::internal::machine: snapshot s5637f98c-edd3-4556-8d30-30e1c5cec831 as of [1707435372633] not yet available for v2062 upper [1707435367567]
sqlancer-materialized-1  | cluster-u1-replica-u1: 2024-02-08T23:36:15.807981Z  INFO mz_persist_client::internal::machine: snapshot saab25a5a-2f0b-4396-b045-3af27ac9909f as of [1707435371577] now available
sqlancer-materialized-1  | cluster-u1-replica-u1: 2024-02-08T23:36:15.808082Z  INFO mz_persist_client::internal::machine: snapshot saab25a5a-2f0b-4396-b045-3af27ac9909f as of [1707435372633] now available
sqlancer-materialized-1  | cluster-u1-replica-u1: 2024-02-08T23:36:16.175146Z  INFO mz_persist_client::internal::machine: snapshot sf77ef0f7-ac35-4ba7-9032-28937c23c677 as of [1707435372633] now available
sqlancer-materialized-1  | cluster-u1-replica-u1: 2024-02-08T23:36:16.208879Z  INFO mz_persist_client::internal::machine: snapshot s5637f98c-edd3-4556-8d30-30e1c5cec831 as of [1707435371577] now available
sqlancer-materialized-1  | cluster-u1-replica-u1: 2024-02-08T23:36:16.208942Z  INFO mz_persist_client::internal::machine: snapshot s5637f98c-edd3-4556-8d30-30e1c5cec831 as of [1707435372633] now available
sqlancer-materialized-1  | environmentd: 2024-02-08T23:36:16.493725Z  INFO message_command:coord::handle_execute{session="e6561875-8dc0-4d73-b18b-b1d7b1442890"}:coord::handle_execute_inner{stmt="DROP DATABASE IF EXISTS database0"}:sequence_drop_objects:coord::catalog_transact:coord::catalog_transact_with:catalog::transact:catalog::transact_inner: mz_adapter::catalog::state: drop index database0.public.i18 (u25)
sqlancer-materialized-1  | environmentd: 2024-02-08T23:36:16.493981Z  INFO message_command:coord::handle_execute{session="e6561875-8dc0-4d73-b18b-b1d7b1442890"}:coord::handle_execute_inner{stmt="DROP DATABASE IF EXISTS database0"}:sequence_drop_objects:coord::catalog_transact:coord::catalog_transact_with:catalog::transact:catalog::transact_inner: mz_adapter::catalog::state: drop index database0.public.i33 (u24)
sqlancer-materialized-1  | environmentd: 2024-02-08T23:36:16.494183Z  INFO message_command:coord::handle_execute{session="e6561875-8dc0-4d73-b18b-b1d7b1442890"}:coord::handle_execute_inner{stmt="DROP DATABASE IF EXISTS database0"}:sequence_drop_objects:coord::catalog_transact:coord::catalog_transact_with:catalog::transact:catalog::transact_inner: mz_adapter::catalog::state: drop table database0.public.t0 (u4)
sqlancer-materialized-1  | environmentd: 2024-02-08T23:36:16.494336Z  INFO message_command:coord::handle_execute{session="e6561875-8dc0-4d73-b18b-b1d7b1442890"}:coord::handle_execute_inner{stmt="DROP DATABASE IF EXISTS database0"}:sequence_drop_objects:coord::catalog_transact:coord::catalog_transact_with:catalog::transact:catalog::transact_inner: mz_adapter::catalog::state: drop table database0.public.t1 (u8)
sqlancer-materialized-1  | environmentd: 2024-02-08T23:36:16.494474Z  INFO message_command:coord::handle_execute{session="e6561875-8dc0-4d73-b18b-b1d7b1442890"}:coord::handle_execute_inner{stmt="DROP DATABASE IF EXISTS database0"}:sequence_drop_objects:coord::catalog_transact:coord::catalog_transact_with:catalog::transact:catalog::transact_inner: mz_adapter::catalog::state: drop table database0.public.t2 (u12)
sqlancer-materialized-1  | environmentd: 2024-02-08T23:36:16.494663Z  INFO message_command:coord::handle_execute{session="e6561875-8dc0-4d73-b18b-b1d7b1442890"}:coord::handle_execute_inner{stmt="DROP DATABASE IF EXISTS database0"}:sequence_drop_objects:coord::catalog_transact:coord::catalog_transact_with:catalog::transact:catalog::transact_inner: mz_adapter::catalog::state: drop table database0.public.t3 (u14)
sqlancer-materialized-1  | thread 'coordinator' panicked at src/adapter/src/catalog.rs:306:13:
sqlancer-materialized-1  | all dropped_notices entries have `Arc::strong_count(_) == 1`; bad_notices = {(id = t940, kind = IndexAlreadyExists, deps = {User(14), User(24)}, strong_count = 4)}; drop_ids = {User(4), User(8), User(12), User(14), User(24), User(25)}
```

**Comment by aalexandrov** [comment]
I have extracted a timeline of the involved objects from the above, but I cannot reproduce it locally. It seems to be some concurrency issue. @def- does SQLancer run its queries from different clients / sessions?

<details>
<summary>Timeline</summary>

```sql
-- drop everything
DROP DATABASE IF EXISTS database0 CASCADE;

-- 2024-02-08T23:22:11.271681Z
-- create schema database0.public
CREATE DATABASE database0;

-- 2024-02-08T23:22:18.819435Z
-- 6a7ed82b-1183-41f2-8899-c96800796f1f
-- create table database0.public.t0 (u4)
CREATE TABLE IF NOT EXISTS t0 (c0 bool);

-- 2024-02-08T23:22:33.725777Z
-- a732c905-d8dc-45aa-8847-e644af31de00
-- create table database0.public.t1 (u8)
CREATE TABLE t1 (c0 bool);

-- 2024-02-08T23:23:01.368804Z
-- a732c905-d8dc-45aa-8847-e644af31de00
-- create table database0.public.t2 (u12)
CREATE TABLE t2 (c0 bool);

-- 2024-02-08T23:23:37.714427Z
-- a732c905-d8dc-45aa-8847-e644af31de00
-- create table database0.public.t3 (u14)
CREATE TABLE t3 (c0 int2);

-- 2024-02-08T23:28:23.805426Z
-- ???
-- create index database0.public.i33 (u24)
CREATE DEfAULT INDEX i33 ON t3;

-- 2024-02-08T23:28:24.610971Z
-- ???
-- create index database0.public.i18 (u25)
CREATE DEfAULT INDEX i18 ON t3;

-- 2024-02-08T23:36:16.493725Z
-- drop everything
-- e6561875-8dc0-4d73-b18b-b1d7b1442890
DROP DATABASE IF EXISTS database0;
```

</details>

**Comment by def-** [comment]
Yes, SQLancer runs with 4 parallel threads in our testing by default. But that means there are 4 separate databases (`CREATE DATABASE`, not Mz instances), which don't interact with each other at all.

**Comment by def-** [comment]
Happened again in Sentry with more information:
```
all dropped_notices entries have `Arc::strong_count(_) == 1`; bad_notices = {(id = t7843026, kind = IndexTooWideForLiteralConstraints, deps = {User(63911), User(63912)}, strong_count = 4), (id = t7843133, kind = IndexTooWideForLiteralConstraints, deps = {User(63911), User(63912)}, strong_count = 4), (id = t7843300, kind = IndexTooWideForLiteralConstraints, deps = {User(63911), User(63912)}, strong_count = 4)}; drop_ids = {User(63857), User(63858), User(63907), User(63908), User(63911), User(63912), User(63923), User(63924), User(63927), User(63928), User(63931), User(63932)}
```

**Comment by nrainer-materialize** [comment]
Further occurrence in an instance classified as production: https://materializeinc.sentry.io/issues/5023826865/?project=6780145

**Comment by aalexandrov** [comment]
I'll try to find some time in the next weeks to rework the logic so it is based on `GlobalId` references and not on `Arc<OptimizerNotice>` objects.

**Comment by nrainer-materialize** [comment]
Any news on this topic?

**Comment by aalexandrov** [comment]
No. @ggevay is going to be adding more notices in the coming weeks and I will discuss with him—maybe he has ideas how to troubleshoot this.

I want to re-iterate that observing this soft_assert is only indicative of a memory leaks that is in the order of `KiB * O(n)` where `n` is the number of catalog objects producing notices within a single week. So far we have not seen any other evidence of `environmentd` leaking enough memory to warrant allocating immediate cycles for investigating this.

If we see such evidence feel free to drop a notice in this issue and I will discuss with @lfest to put this on the roadmap. The importance of fixing this might change once we start rolling more notices (especially notices that are more likely to occur for catalog items).

**Comment by nrainer-materialize** [comment]
@aalexandrov: Thanks for the update and the information about the severity!

**Comment by aalexandrov** [comment]
Here are all augmented error logs that can be seen in Sentry:

```
all dropped_notices entries have `Arc::strong_count(_) == 1`; bad_notices = {(id = t10480680, kind = IndexTooWideForLiteralConstraints, deps = {User(12335), User(12336)}, strong_count = 4), (id = t10480687, kind = IndexTooWideForLiteralConstraints, deps = {User(12335), User(12336)}, strong_count = 4)}; drop_ids = {User(12273), User(12274), User(12342), User(12343), User(12344), User(12345)}
all dropped_notices entries have `Arc::strong_count(_) == 1`; bad_notices = {(id = t10480691, kind = IndexTooWideForLiteralConstraints, deps = {User(12335), User(12336)}, strong_count = 4), (id = t10480701, kind = IndexTooWideForLiteralConstraints, deps = {User(12335), User(12336)}, strong_count = 4), (id = t10480743, kind = IndexTooWideForLiteralConstraints, deps = {User(12335), User(12336)}, strong_count = 4), (id = t10480759, kind = IndexTooWideForLiteralConstraints, deps = {User(12335), User(12336)}, strong_count = 4)}; drop_ids = {User(12279), User(12280), User(12329), User(12330), User(12331), User(12332), User(12335), User(12336), User(12346), User(12347), User(12348), User(12349), User(12354), User(12355), User(12356), User(12357)}
all dropped_notices entries have `Arc::strong_count(_) == 1`; bad_notices = {(id = t10480726, kind = IndexTooWideForLiteralConstraints, deps = {User(12335), User(12336)}, strong_count = 7), (id = t10480733, kind = IndexTooWideForLiteralConstraints, deps = {User(12335), User(12336)}, strong_count = 7)}; drop_ids = {User(12275), User(12276), User(12350), User(12351), User(12352), User(12353)}
all dropped_notices entries have `Arc::strong_count(_) == 1`; bad_notices = {(id = t11015812, kind = IndexTooWideForLiteralConstraints, deps = {User(13174), User(13175)}, strong_count = 7), (id = t11015825, kind = IndexTooWideForLiteralConstraints, deps = {User(13174), User(13175)}, strong_count = 7)}; drop_ids = {User(12948), User(12949), User(13273), User(13276), User(13277), User(13279)}
all dropped_notices entries have `Arc::strong_count(_) == 1`; bad_notices = {(id = t11428385, kind = IndexTooWideForLiteralConstraints, deps = {User(13888), User(13889)}, strong_count = 10), (id = t11428398, kind = IndexTooWideForLiteralConstraints, deps = {User(13888), User(13889)}, strong_count = 10), (id = t11428489, kind = IndexTooWideForLiteralConstraints, deps = {User(13888), User(13889)}, strong_count = 10), (id = t11428499, kind = IndexTooWideForLiteralConstraints, deps = {User(13888), User(13889)}, strong_count = 10), (id = t11428568, kind = IndexTooWideForLiteralConstraints, deps = {User(13888), User(13889)}, strong_count = 10), (id = t11428599, kind = IndexTooWideForLiteralConstraints, deps = {User(13888), User(13889)}, strong_count = 10)}; drop_ids = {User(13659), User(13660), User(13873), User(13876), User(13878), User(13879), User(13888), User(13889), User(13953), User(13954), User(13957), User(13958), User(13968), User(13970), User(13972), User(13973), User(13983), User(13984), User(13985), User(13987)}
all dropped_notices entries have `Arc::strong_count(_) == 1`; bad_notices = {(id = t11432882, kind = IndexTooWideForLiteralConstraints, deps = {User(14295), User(14297)}, strong_count = 4), (id = t11432913, kind = IndexTooWideForLiteralConstraints, deps = {User(14295), User(14297)}, strong_count = 4), (id = t11432970, kind = IndexTooWideForLiteralConstraints, deps = {User(14295), User(14297)}, strong_count = 4), (id = t11432995, kind = IndexTooWideForLiteralConstraints, deps = {User(14295), User(14297)}, strong_count = 4), (id = t11433034, kind = IndexTooWideForLiteralConstraints, deps = {User(14295), User(14297)}, strong_count = 4), (id = t11433050, kind = IndexTooWideForLiteralConstraints, deps = {User(14295), User(14297)}, strong_count = 4)}; drop_ids = {User(14103), User(14107), User(14282), User(14285), User(14287), User(14289), User(14295), User(14297), User(14351), User(14354), User(14357), User(14358), User(14369), User(14370), User(14371), User(14374), User(14379), User(14380), User(14381), User(14382)}
all dropped_notices entries have `Arc::strong_count(_) == 1`; bad_notices = {(id = t11432935, kind = IndexTooWideForLiteralConstraints, deps = {User(14295), User(14297)}, strong_count = 4), (id = t11432951, kind = IndexTooWideForLiteralConstraints, deps = {User(14295), User(14297)}, strong_count = 4)}; drop_ids = {User(14087), User(14090), User(14361), User(14362), User(14365), User(14366)}
all dropped_notices entries have `Arc::strong_count(_) == 1`; bad_notices = {(id = t11554838, kind = IndexTooWideForLiteralConstraints, deps = {User(17127), User(17129)}, strong_count = 4), (id = t11554851, kind = IndexTooWideForLiteralConstraints, deps = {User(17127), User(17129)}, strong_count = 4)}; drop_ids = {User(16904), User(16905), User(17203), User(17205), User(17208), User(17209)}
all dropped_notices entries have `Arc::strong_count(_) == 1`; bad_notices = {(id = t2757551, kind = IndexTooWideForLiteralConstraints, deps = {User(7899), User(7900)}, strong_count = 4), (id = t2757602, kind = IndexTooWideForLiteralConstraints, deps = {User(7899), User(7900)}, strong_count = 4)}; drop_ids = {User(7895), User(7896), User(7899), User(7900), User(7910), User(7911), User(7912), User(7913), User(7914), User(7915), User(7920), User(7923), User(7924), User(7925), User(7926), User(7927), User(7928)}
all dropped_notices entries have `Arc::strong_count(_) == 1`; bad_notices = {(id = t2879275, kind = IndexTooWideForLiteralConstraints, deps = {User(8515), User(8516)}, strong_count = 4), (id = t2879416, kind = IndexTooWideForLiteralConstraints, deps = {User(8515), User(8516)}, strong_count = 4)}; drop_ids = {User(8511), User(8512), User(8515), User(8516), User(8526), User(8527), User(8528), User(8529), User(8530), User(8531), User(8536), User(8539), User(8540), User(8541), User(8542), User(8543), User(8544)}
all dropped_notices entries have `Arc::strong_count(_) == 1`; bad_notices = {(id = t7843026, kind = IndexTooWideForLiteralConstraints, deps = {User(63911), User(63912)}, strong_count = 4), (id = t7843133, kind = IndexTooWideForLiteralConstraints, deps = {User(63911), User(63912)}, strong_count = 4), (id = t7843300, kind = IndexTooWideForLiteralConstraints, deps = {User(63911), User(63912)}, strong_count = 4)}; drop_ids = {User(63857), User(63858), User(63907), User(63908), User(63911), User(63912), User(63923), User(63924), User(63927), User(63928), User(63931), User(63932)}
```

**Comment by def-** [comment]
Occurred again in [Parallel Workload (rename)](https://buildkite.com/materialize/nightly/builds/8916#019112de-0e7a-42da-8ace-17719f87f7be)

**Comment by def-** [comment]
@ggevay Happened again with your extra logging: https://buildkite.com/materialize/nightly/builds/9184#01916bb1-26b8-4ff5-ae57-122814130603

**Comment by ggevay** [comment]
So, I'm really hoping that https://github.com/MaterializeInc/materialize/pull/29174 has solved this! But if it happens again on a branch that includes the commit from that PR, then please reopen this issue.

**Comment by def-** [comment]
Seen in https://buildkite.com/materialize/nightly/builds/9235#0191804c-a49a-4708-847d-a059e8ddcfab

**Comment by ggevay** [comment]
Oh no... Will look into it, thanks!

**Comment by def-** [comment]
@ggevay Anything we should do in tests to silence this error? It's been flaking for a while already.

**Comment by ggevay** [comment]
I'm gonna just comment out the `soft_assert!` for now...
