### ISSUE TITLE
asan: CI is supposed to run this test but something has gone wrong!

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#24995]
### What version of Materialize are you using?

a9ec35a3ef3a (Pull Request #24888)

### What is the issue?

Seen when running CI with ASan: https://github.com/MaterializeInc/materialize/pull/24888 https://buildkite.com/materialize/tests/builds/74892#018d7b77-85ba-4aba-8522-ce33058eddb1
```
thread 's3::tests::s3_blob' panicked at src/persist/src/s3.rs:219:21:
CI is supposed to run this test but something has gone wrong!
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4cb3beec86178baff601529389306a4949b077ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/4cb3beec86178baff601529389306a4949b077ce/library/core/src/panicking.rs:72:14
   2: <mz_persist::s3::S3BlobConfig>::new_for_test::{closure#0}
             at ./src/s3.rs:219:21
   3: mz_persist::s3::tests::s3_blob::{closure#0}::test_impl::{closure#0}
             at ./src/s3.rs:984:57
   4: mz_persist::s3::tests::s3_blob::{closure#0}
             at ./src/s3.rs:979:5
   5: <core::pin::Pin<&mut dyn core::future::future::Future<Output = core::result::Result<(), mz_persist::location::ExternalError>>> as core::future::future::Future>::poll
             at /rustc/4cb3beec86178baff601529389306a4949b077ce/library/core/src/future/future.rs:125:9
   6: <tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = core::result::Result<(), mz_persist::location::ExternalError>>>> as core::future::future::Future>::poll
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
   7: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = core::result::Result<(), mz_persist::location::ExternalError>>>>>::{closure#0}
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
   8: tokio::runtime::coop::with_budget::<core::task::poll::Poll<core::result::Result<(), mz_persist::location::ExternalError>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = core::result::Result<(), mz_persist::location::ExternalError>>>>>::{closure#0}>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
   9: tokio::runtime::coop::budget::<core::task::poll::Poll<core::result::Result<(), mz_persist::location::ExternalError>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = core::result::Result<(), mz_persist::location::ExternalError>>>>>::{closure#0}>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  10: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = core::result::Result<(), mz_persist::location::ExternalError>>>>>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  11: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = core::result::Result<(), mz_persist::location::ExternalError>>>>>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  12: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = core::result::Result<(), mz_persist::location::ExternalError>>>>>::{closure#0}
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  13: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::scheduler::multi_thread::MultiThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = core::result::Result<(), mz_persist::location::ExternalError>>>>>::{closure#0}, core::result::Result<(), mz_persist::location::ExternalError>>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  14: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = core::result::Result<(), mz_persist::location::ExternalError>>>>>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  15: <tokio::runtime::runtime::Runtime>::block_on::<core::pin::Pin<&mut dyn core::future::future::Future<Output = core::result::Result<(), mz_persist::location::ExternalError>>>>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/runtime.rs:349:45
  16: mz_persist::s3::tests::s3_blob
             at ./src/s3.rs:979:5
  17: mz_persist::s3::tests::s3_blob::{closure#0}
             at ./src/s3.rs:983:27
  18: <mz_persist::s3::tests::s3_blob::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/4cb3beec86178baff601529389306a4949b077ce/library/core/src/ops/function.rs:250:5
  19: core::ops::function::FnOnce::call_once
             at /rustc/4cb3beec86178baff601529389306a4949b077ce/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by benesch** [comment]
@def- this happens when the `CI` environment variable is true but the `MZ_PERSIST_EXTERNAL_STORAGE_TEST_S3_BUCKET` environment variable is not set.

https://github.com/MaterializeInc/materialize/blob/1f791e112c8288ec47b100bf87dcee6ac2b9a741/src/persist/src/s3.rs#L218-L220

**Comment by benesch** [comment]
@def- kicking this one over to you since I suspect it's an issue with the new ASAN pipeline. Feel free to kick it back to me/storage if I've misdiagnosed.

**Comment by def-** [comment]
Indeed, my fault! Have to pass through some more variables through ci-builder.
