### ISSUE TITLE
asan: thread 'persist:0027' panicked at src/persist-client/src/internal/state_versions.rs:1100:13: assertion `left == right` failed

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#25015]
### What version of Materialize are you using?

5e04d9b4f095 (Pull Request #24888)

### What is the issue?

```
testdrive-materialized-1     | thread 'persist:0027' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-06dbe7bacc51248ae-1/materialize/tests/src/persist-client/src/internal/state_versions.rs:1100:13:
testdrive-materialized-1     | assertion `left == right` failed
testdrive-materialized-1     |   left: Antichain { elements: [1707235072131] }
testdrive-materialized-1     |  right: Antichain { elements: [1707236275288] }
testdrive-materialized-1     | stack backtrace:
testdrive-materialized-1     | thread 'persist:0011' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-06dbe7bacc51248ae-1/materialize/tests/src/persist-client/src/internal/state_versions.rs:1100:13:
testdrive-materialized-1     | assertion `left == right` failed
testdrive-materialized-1     |   left: Antichain { elements: [1707235072131] }
testdrive-materialized-1     |  right: Antichain { elements: [1707236275288] }
```
Seen in https://buildkite.com/materialize/tests/builds/74947#018d7e9c-ba0d-41de-a2bf-f7d9ce4df507 with Address Sanitizer on, so the run is probably slower than normal Release builds. I'm not sure why the backtrace is missing.

The code comes from https://github.com/MaterializeInc/materialize/pull/20241 CC @pH14 @danhhz Maybe this is related to https://github.com/MaterializeInc/materialize/issues/24994 which is pretty close in the code.

ci-regexp: internal/state_versions.rs:1100

**Comment by danhhz** [comment]
Hmm this one seems potentially more concerning than #24994

**Comment by ggevay** [comment]
I've seen this today twice when running Materialize locally. I was testing various things, and then left the system running in the background for some time, and when I looked at it again, I saw that this panic had happened.
```
environmentd: 2024-02-07T12:34:40.784386Z  INFO mz_persist_client::internal::state: Force expiring reader (rd28e76ca-4650-445c-8858-ba86289d7e7d) of shard (s6a14953a-90c6-4721-b267-da5aa2ab508e) due to inactivity
cluster-u1-replica-u1: 2024-02-07T12:36:38.724650Z  INFO mz_persist_client::internal::machine: snapshot s37be51c7-112a-40fe-9c76-69388ad09c5a as of [1707309398502] now available
thread 'persist:000d' panicked at /home/gabor/materialize/src/persist-client/src/internal/state_versions.rs:1100:13:
assertion `left == right` failed
  left: Antichain { elements: [1707310196696] }
 right: Antichain { elements: [1707310195695] }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:279:5
   4: mz_persist_client::internal::state_versions::ReferencedBlobValidator<T>::validate_against_state
             at ./src/persist-client/src/internal/state_versions.rs:1100:13
   5: mz_persist_client::internal::state_versions::StateVersionsIter<T>::next
             at ./src/persist-client/src/internal/state_versions.rs:994:13
   6: mz_persist_client::internal::gc::GarbageCollector<K,V,T,D>::find_removable_blobs
             at ./src/persist-client/src/internal/gc.rs:518:33
   7: mz_persist_client::internal::gc::GarbageCollector<K,V,T,D>::incrementally_delete_and_truncate::{{closure}}
             at ./src/persist-client/src/internal/gc.rs:431:13
   8: mz_persist_client::internal::gc::GarbageCollector<K,V,T,D>::gc_and_truncate::{{closure}}
             at ./src/persist-client/src/internal/gc.rs:301:10
   9: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  10: mz_persist_client::internal::gc::GarbageCollector<K,V,T,D>::new::{{closure}}::{{closure}}
             at ./src/persist-client/src/internal/gc.rs:164:34
  11: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/future/future.rs:125:9
  12: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:334:17
  13: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/loom/std/unsafe_cell.rs:16:9
  14: tokio::runtime::task::core::Core<T,S>::poll
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:323:13
  15: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:485:19
  16: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panic/unwind_safe.rs:272:9
  17: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  18: __rust_try
  19: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  20: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  21: tokio::runtime::task::harness::poll_future
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:473:18
  22: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:208:27
  23: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:153:15
  24: tokio::runtime::task::raw::poll
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/raw.rs:276:5
  25: tokio::runtime::task::raw::RawTask::poll
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/raw.rs:200:18
  26: tokio::runtime::task::LocalNotified<S>::run
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/mod.rs:400:9
  27: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:639:17
  28: tokio::runtime::coop::with_budget
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  29: tokio::runtime::coop::budget
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  30: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:575:9
  31: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:526:24
  32: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:491:21
  33: tokio::runtime::context::scoped::Scoped<T>::set
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/scoped.rs:40:9
  34: tokio::runtime::context::set_scheduler::{{closure}}
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context.rs:176:26
  35: std::thread::local::LocalKey<T>::try_with
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/thread/local.rs:270:16
  36: std::thread::local::LocalKey<T>::with
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/thread/local.rs:246:9
  37: tokio::runtime::context::set_scheduler
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context.rs:176:9
  38: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:486:9
  39: tokio::runtime::context::runtime::enter_runtime
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  40: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:478:5
  41: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:447:45
  42: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/task.rs:42:21
  43: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:334:17
  44: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/loom/std/unsafe_cell.rs:16:9
  45: tokio::runtime::task::core::Core<T,S>::poll
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:323:13
  46: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:485:19
  47: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panic/unwind_safe.rs:272:9
  48: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  49: __rust_try
  50: std::panicking::try
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  51: std::panic::catch_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  52: tokio::runtime::task::harness::poll_future
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:473:18
  53: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:208:27
  54: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:153:15
  55: tokio::runtime::task::raw::poll
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/raw.rs:276:5
  56: tokio::runtime::task::raw::RawTask::poll
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/raw.rs:200:18
  57: tokio::runtime::task::UnownedTask<S>::run
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/mod.rs:437:9
  58: tokio::runtime::blocking::pool::Task::run
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:159:9
  59: tokio::runtime::blocking::pool::Inner::run
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:513:17
  60: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:471:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I think for the second one I didn't even create any objects:
```
cluster-s2-replica-s2: 2024-02-07T17:04:32.860395Z  INFO mz_compute::compute_state: creating dataflow name=mz_internal.mz_frontiers_ind import_ids=[s634] export_ids=[s678] as_of=[0] until=[]
cluster-s2-replica-s2: 2024-02-07T17:04:32.862541Z  INFO mz_compute::compute_state: creating dataflow name=mz_internal.mz_notices_ind import_ids=[s679] export_ids=[s682] as_of=[1707325471882] until=[]
cluster-s2-replica-s2: 2024-02-07T17:04:32.918876Z  INFO tokio_postgres::connection: NOTICE: relation "consensus" already exists, skipping    
environmentd: 2024-02-07T17:04:33.080843Z  INFO environmentd::run:environmentd::serve:bootstrap: mz_adapter::coord: coordinator init: bootstrap complete
environmentd: 2024-02-07T17:04:33.096511Z  INFO environmentd::run:environmentd::serve: mz_adapter::coord: coordinator init: complete
environmentd v0.87.0-dev (a3cfa7fd6) listening...
 SQL address: 127.0.0.1:6875
 HTTP address: 127.0.0.1:6876
 Internal SQL address: 127.0.0.1:6877
 Internal HTTP address: 0.0.0.0:6878
 Balancerd SQL address: 127.0.0.1:6880
 Balancerd HTTP address: 127.0.0.1:6881
 Internal Persist PubSub address: 127.0.0.1:6879
 Root trace ID: 00000000000000000000000000000000
thread 'persist:0008' panicked at /home/gabor/materialize/src/persist-client/src/internal/state_versions.rs:1100:13:
assertion `left == right` failed
  left: Antichain { elements: [1707327276463] }
 right: Antichain { elements: [1707327275463] }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:279:5
   4: mz_persist_client::internal::state_versions::ReferencedBlobValidator<T>::validate_against_state
             at ./src/persist-client/src/internal/state_versions.rs:1100:13
   5: mz_persist_client::internal::state_versions::StateVersionsIter<T>::next
             at ./src/persist-client/src/internal/state_versions.rs:994:13
   6: mz_persist_client::internal::gc::GarbageCollector<K,V,T,D>::find_removable_blobs
             at ./src/persist-client/src/internal/gc.rs:518:33
   7: mz_persist_client::internal::gc::GarbageCollector<K,V,T,D>::incrementally_delete_and_truncate::{{closure}}
             at ./src/persist-client/src/internal/gc.rs:431:13
   8: mz_persist_client::internal::gc::GarbageCollector<K,V,T,D>::gc_and_truncate::{{closure}}
             at ./src/persist-client/src/internal/gc.rs:301:10
   9: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  10: mz_persist_client::internal::gc::GarbageCollector<K,V,T,D>::new::{{closure}}::{{closure}}
             at ./src/persist-client/src/internal/gc.rs:164:34
  11: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/future/future.rs:125:9
  12: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:334:17
  13: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/loom/std/unsafe_cell.rs:16:9
  14: tokio::runtime::task::core::Core<T,S>::poll
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:323:13
  15: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/gabor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:485:19
  16: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panic/unwind_safe.rs:272:9
  17: std::panicking::try::do_call
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
...
```

I think neither was on the current main, but while I was testing various PRs. The second one was on a3cfa7fd6fd7ebeeca3db2426e4c9b3a045d555f in https://github.com/MaterializeInc/materialize/pull/25026

**Comment by danhhz** [comment]
@bkirwi Think you'd have a chance to do a quick triage here before you're ooo? If this is happening outside of asan, then maybe something really has changed

**Comment by bkirwi** [comment]
Hopefully! I'll aim to either follow up or hand this back by EOD tomorrow.

**Comment by bkirwi** [comment]
I didn't have time to get to the bottom of these particular errors today, but I looked into it enough to have pretty low confidence in the correctness of the assertions. (To the point where I'd probably rework the assertions before investigating further.)

In particular, these assertions are comparing the two largest batches using this ordering:

https://github.com/MaterializeInc/materialize/blob/13571b1600fca507d26c9e58586b59684683dbff/src/persist-client/src/internal/state.rs#L259-L292

Possible issues include:
- A frontier of the empty antichain will sort smaller than any other frontier. (So, for example, if i have two incremental batches `{1}-{2}` and `{1}-{}`, the first will sort _larger_ than the second.
- In general, the since of the largest batch in this ordering is not typically the largest since of the shard. (All else equal, compaction will make the largest batch in the shard have a smaller lower (as the formerly-largest batch merges into a smaller one) but a higher since (as the since advances).)

I did produce a draft that checks that the meet(uppers) of both sets of batches are identical, which I think ought to be true. https://github.com/MaterializeInc/materialize/pull/25090 But I won't have time to polish it up today, and also it's unclear how to reproduce.

Since this assertion seems to have a pretty high likelihood of false positives, I think it's probably okay if this waits until I get back. But if anyone's feeling passionate feel free to take it over!

**Comment by def-** [comment]
Could we disable the assertion if it's wrong? It's enabled in debug mode and easy to hit, see for example https://materializeinc.slack.com/archives/C01CFKM1QRF/p1709137409821889

**Comment by bkirwi** [comment]
I've merged the linked PR. If this appears again in a version that includes https://github.com/MaterializeInc/materialize/commit/2bd46246cc31566ea3659111bfe58e1831d915bc - that will be very interesting to me, at least!

**Comment by def-** [comment]
There is a new run with debug assertions in https://buildkite.com/materialize/tests/builds/77062 and https://buildkite.com/materialize/nightlies/builds/6662, let's see if it pops up again.
