### ISSUE TITLE
lsan: detected memory leaks in rdkafka::client::native_resolve_cb::<rdkafka::producer::future_producer::FutureProducerContext<mz_kafka_util::client::MzClientContext>>

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#25078]
### What version of Materialize are you using?

b9eb9a506de4 (Pull Request #24888)

### What is the issue?

```
=================================================================
==2979==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 28 byte(s) in 1 object(s) allocated from:
    #0 0xaaaae497625c in malloc.part.9 (/usr/local/bin/testdrive+0x28e625c) (BuildId: 45bec31f5b513518)
    #1 0xffff8159c2f8 in __res_context_send (/lib/aarch64-linux-gnu/libc.so.6+0x10c2f8) (BuildId: 3ba44e06b9dc66aeeb2651db4dd015ffaf6e0849)
    #2 0xffff81599c54 in __res_context_query (/lib/aarch64-linux-gnu/libc.so.6+0x109c54) (BuildId: 3ba44e06b9dc66aeeb2651db4dd015ffaf6e0849)
    #3 0xffff8159a4a8 in __res_context_search (/lib/aarch64-linux-gnu/libc.so.6+0x10a4a8) (BuildId: 3ba44e06b9dc66aeeb2651db4dd015ffaf6e0849)
    #4 0xffff81594304  (/lib/aarch64-linux-gnu/libc.so.6+0x104304) (BuildId: 3ba44e06b9dc66aeeb2651db4dd015ffaf6e0849)
    #5 0xffff815945ac in _nss_dns_gethostbyname2_r (/lib/aarch64-linux-gnu/libc.so.6+0x1045ac) (BuildId: 3ba44e06b9dc66aeeb2651db4dd015ffaf6e0849)
    #6 0xffff815869b0 in gethostbyname2_r (/lib/aarch64-linux-gnu/libc.so.6+0xf69b0) (BuildId: 3ba44e06b9dc66aeeb2651db4dd015ffaf6e0849)
    #7 0xffff81561838 in getaddrinfo (/lib/aarch64-linux-gnu/libc.so.6+0xd1838) (BuildId: 3ba44e06b9dc66aeeb2651db4dd015ffaf6e0849)
    #8 0xaaaae492eaac in getaddrinfo.part.85 (/usr/local/bin/testdrive+0x289eaac) (BuildId: 45bec31f5b513518)
    #9 0xaaaaeab6fd10 in rdkafka::client::native_resolve_cb::<rdkafka::producer::future_producer::FutureProducerContext<mz_kafka_util::client::MzClientContext>> (/usr/local/bin/testdrive+0x8adfd10) (BuildId: 45bec31f5b513518)
    #10 0xaaaaeb0bf500 in rd_kafka_broker_thread_main (/usr/local/bin/testdrive+0x902f500) (BuildId: 45bec31f5b513518)
    #11 0xaaaaeb14d5c8 in _thrd_wrapper_function (/usr/local/bin/testdrive+0x90bd5c8) (BuildId: 45bec31f5b513518)
    #12 0xaaaae48c8438 in asan_thread_start(void*) (/usr/local/bin/testdrive+0x2838438) (BuildId: 45bec31f5b513518)
    #13 0xffff81575ed8  (/lib/aarch64-linux-gnu/libc.so.6+0xe5ed8) (BuildId: 3ba44e06b9dc66aeeb2651db4dd015ffaf6e0849)

SUMMARY: AddressSanitizer: 28 byte(s) leaked in 1 allocation(s)
```
Seen in https://buildkite.com/materialize/tests/builds/75180#018d8914-d1af-42e6-bb90-3ca9d2046c3b (via https://github.com/MaterializeInc/materialize/pull/24888)
This is in the testdrive binary, but maybe it's an rdkafka problem? getaddrinfo requires a freeaddrinfo.

**Comment by benesch** [comment]
As with https://github.com/MaterializeInc/materialize/issues/25070#issuecomment-1937060648:

> I've added this to the storage mega tracker under a new "Sanitizer issue" heading. It's tough to know how seriously to take these issues because the sanitizers all seem to have a fair number of false positives.
