### ISSUE TITLE
lsan: detected memory leaks in rd_kafka_new

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#25079]
### What version of Materialize are you using?

b9eb9a5 (Pull Request #24888)

### What is the issue?

```
=================================================================
==7==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 3096 byte(s) in 1 object(s) allocated from:
    #0 0xaaaad0cd6398 in calloc.part.10 (/usr/local/bin/testdrive+0x28e6398) (BuildId: 45bec31f5b513518)
    #1 0xaaaad741ae90 in rd_kafka_broker_add (/usr/local/bin/testdrive+0x902ae90) (BuildId: 45bec31f5b513518)
    #2 0xaaaad741b8e8 in rd_kafka_brokers_add0 (/usr/local/bin/testdrive+0x902b8e8) (BuildId: 45bec31f5b513518)
    #3 0xaaaad7408650 in rd_kafka_new (/usr/local/bin/testdrive+0x9018650) (BuildId: 45bec31f5b513518)
    #4 0xaaaad62304a0 in <rdkafka::client::Client<rdkafka::consumer::DefaultConsumerContext>>::new (/usr/local/bin/testdrive+0x7e404a0) (BuildId: 45bec31f5b513518)

Indirect leak of 512 byte(s) in 1 object(s) allocated from:
    #0 0xaaaad0cd6398 in calloc.part.10 (/usr/local/bin/testdrive+0x28e6398) (BuildId: 45bec31f5b513518)
    #1 0xaaaad7420634 in rd_kafka_buf_new0 (/usr/local/bin/testdrive+0x9030634) (BuildId: 45bec31f5b513518)
    #2 0xaaaad74206c4 in rd_kafka_buf_new_request0 (/usr/local/bin/testdrive+0x90306c4) (BuildId: 45bec31f5b513518)
    #3 0xaaaad746289c in rd_kafka_MetadataRequest (/usr/local/bin/testdrive+0x907289c) (BuildId: 45bec31f5b513518)
    #4 0xaaaad743a4d0 in rd_kafka_metadata_refresh_topics (/usr/local/bin/testdrive+0x904a4d0) (BuildId: 45bec31f5b513518)
    #5 0xaaaad743a900 in rd_kafka_metadata_refresh_known_topics (/usr/local/bin/testdrive+0x904a900) (BuildId: 45bec31f5b513518)
    #6 0xaaaad74109a0 in rd_kafka_broker_fail (/usr/local/bin/testdrive+0x90209a0) (BuildId: 45bec31f5b513518)
    #7 0xaaaad741bd70 in rd_kafka_broker_op_serve (/usr/local/bin/testdrive+0x902bd70) (BuildId: 45bec31f5b513518)
    #8 0xaaaad741d1f8 in rd_kafka_broker_ops_io_serve (/usr/local/bin/testdrive+0x902d1f8) (BuildId: 45bec31f5b513518)
    #9 0xaaaad741d8c4 in rd_kafka_broker_consumer_serve (/usr/local/bin/testdrive+0x902d8c4) (BuildId: 45bec31f5b513518)
    #10 0xaaaad741ea4c in rd_kafka_broker_serve (/usr/local/bin/testdrive+0x902ea4c) (BuildId: 45bec31f5b513518)
    #11 0xaaaad741f3c8 in rd_kafka_broker_thread_main (/usr/local/bin/testdrive+0x902f3c8) (BuildId: 45bec31f5b513518)
    #12 0xaaaad74ad5c8 in _thrd_wrapper_function (/usr/local/bin/testdrive+0x90bd5c8) (BuildId: 45bec31f5b513518)
    #13 0xaaaad0c28438 in asan_thread_start(void*) (/usr/local/bin/testdrive+0x2838438) (BuildId: 45bec31f5b513518)
    #14 0xffff85c75ed8  (/lib/aarch64-linux-gnu/libc.so.6+0xe5ed8) (BuildId: 3ba44e06b9dc66aeeb2651db4dd015ffaf6e0849)

Indirect leak of 360 byte(s) in 1 object(s) allocated from:
    #0 0xaaaad0cd625c in malloc.part.9 (/usr/local/bin/testdrive+0x28e625c) (BuildId: 45bec31f5b513518)
    #1 0xaaaad7462ff4 in rd_kafka_handle_ApiVersion (/usr/local/bin/testdrive+0x9072ff4) (BuildId: 45bec31f5b513518)
    #2 0xaaaad7412764 in rd_kafka_broker_handle_ApiVersion (/usr/local/bin/testdrive+0x9022764) (BuildId: 45bec31f5b513518)
    #3 0xaaaad7421204 in rd_kafka_buf_callback (/usr/local/bin/testdrive+0x9031204) (BuildId: 45bec31f5b513518)
    #4 0xaaaad7414cc8 in rd_kafka_recv (/usr/local/bin/testdrive+0x9024cc8) (BuildId: 45bec31f5b513518)
    #5 0xaaaad74795ac in rd_kafka_transport_io_event.constprop.0 (/usr/local/bin/testdrive+0x90895ac) (BuildId: 45bec31f5b513518)
    #6 0xaaaad7479f50 in rd_kafka_transport_io_serve (/usr/local/bin/testdrive+0x9089f50) (BuildId: 45bec31f5b513518)
    #7 0xaaaad741d43c in rd_kafka_broker_ops_io_serve (/usr/local/bin/testdrive+0x902d43c) (BuildId: 45bec31f5b513518)
    #8 0xaaaad741d8c4 in rd_kafka_broker_consumer_serve (/usr/local/bin/testdrive+0x902d8c4) (BuildId: 45bec31f5b513518)
    #9 0xaaaad741ea4c in rd_kafka_broker_serve (/usr/local/bin/testdrive+0x902ea4c) (BuildId: 45bec31f5b513518)
    #10 0xaaaad741f304 in rd_kafka_broker_thread_main (/usr/local/bin/testdrive+0x902f304) (BuildId: 45bec31f5b513518)
    #11 0xaaaad74ad5c8 in _thrd_wrapper_function (/usr/local/bin/testdrive+0x90bd5c8) (BuildId: 45bec31f5b513518)
    #12 0xaaaad0c28438 in asan_thread_start(void*) (/usr/local/bin/testdrive+0x2838438) (BuildId: 45bec31f5b513518)
    #13 0xffff85c75ed8  (/lib/aarch64-linux-gnu/libc.so.6+0xe5ed8) (BuildId: 3ba44e06b9dc66aeeb2651db4dd015ffaf6e0849)

Indirect leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0xaaaad0cd625c in malloc.part.9 (/usr/local/bin/testdrive+0x28e625c) (BuildId: 45bec31f5b513518)
    #1 0xaaaad740be74 in rd_buf_alloc_segment0 (/usr/local/bin/testdrive+0x901be74) (BuildId: 45bec31f5b513518)
    #2 0xaaaad740c0d8 in rd_buf_write_ensure (/usr/local/bin/testdrive+0x901c0d8) (BuildId: 45bec31f5b513518)
    #3 0xaaaad740c320 in rd_buf_write (/usr/local/bin/testdrive+0x901c320) (BuildId: 45bec31f5b513518)
    #4 0xaaaad7420708 in rd_kafka_buf_new_request0 (/usr/local/bin/testdrive+0x9030708) (BuildId: 45bec31f5b513518)
    #5 0xaaaad746289c in rd_kafka_MetadataRequest (/usr/local/bin/testdrive+0x907289c) (BuildId: 45bec31f5b513518)
    #6 0xaaaad743a4d0 in rd_kafka_metadata_refresh_topics (/usr/local/bin/testdrive+0x904a4d0) (BuildId: 45bec31f5b513518)
    #7 0xaaaad743a900 in rd_kafka_metadata_refresh_known_topics (/usr/local/bin/testdrive+0x904a900) (BuildId: 45bec31f5b513518)
    #8 0xaaaad74109a0 in rd_kafka_broker_fail (/usr/local/bin/testdrive+0x90209a0) (BuildId: 45bec31f5b513518)
    #9 0xaaaad741bd70 in rd_kafka_broker_op_serve (/usr/local/bin/testdrive+0x902bd70) (BuildId: 45bec31f5b513518)
    #10 0xaaaad741d1f8 in rd_kafka_broker_ops_io_serve (/usr/local/bin/testdrive+0x902d1f8) (BuildId: 45bec31f5b513518)
    #11 0xaaaad741d8c4 in rd_kafka_broker_consumer_serve (/usr/local/bin/testdrive+0x902d8c4) (BuildId: 45bec31f5b513518)
    #12 0xaaaad741ea4c in rd_kafka_broker_serve (/usr/local/bin/testdrive+0x902ea4c) (BuildId: 45bec31f5b513518)
    #13 0xaaaad741f3c8 in rd_kafka_broker_thread_main (/usr/local/bin/testdrive+0x902f3c8) (BuildId: 45bec31f5b513518)
    #14 0xaaaad74ad5c8 in _thrd_wrapper_function (/usr/local/bin/testdrive+0x90bd5c8) (BuildId: 45bec31f5b513518)
    #15 0xaaaad0c28438 in asan_thread_start(void*) (/usr/local/bin/testdrive+0x2838438) (BuildId: 45bec31f5b513518)
    #16 0xffff85c75ed8  (/lib/aarch64-linux-gnu/libc.so.6+0xe5ed8) (BuildId: 3ba44e06b9dc66aeeb2651db4dd015ffaf6e0849)

Indirect leak of 204 byte(s) in 1 object(s) allocated from:
    #0 0xaaaad0cd625c in malloc.part.9 (/usr/local/bin/testdrive+0x28e625c) (BuildId: 45bec31f5b513518)
    #1 0xaaaad740c260 in rd_buf_init (/usr/local/bin/testdrive+0x901c260) (BuildId: 45bec31f5b513518)
    #2 0xaaaad742064c in rd_kafka_buf_new0 (/usr/local/bin/testdrive+0x903064c) (BuildId: 45bec31f5b513518)
    #3 0xaaaad74206c4 in rd_kafka_buf_new_request0 (/usr/local/bin/testdrive+0x90306c4) (BuildId: 45bec31f5b513518)
    #4 0xaaaad746289c in rd_kafka_MetadataRequest (/usr/local/bin/testdrive+0x907289c) (BuildId: 45bec31f5b513518)
    #5 0xaaaad743a4d0 in rd_kafka_metadata_refresh_topics (/usr/local/bin/testdrive+0x904a4d0) (BuildId: 45bec31f5b513518)
    #6 0xaaaad743a900 in rd_kafka_metadata_refresh_known_topics (/usr/local/bin/testdrive+0x904a900) (BuildId: 45bec31f5b513518)
    #7 0xaaaad74109a0 in rd_kafka_broker_fail (/usr/local/bin/testdrive+0x90209a0) (BuildId: 45bec31f5b513518)
    #8 0xaaaad741bd70 in rd_kafka_broker_op_serve (/usr/local/bin/testdrive+0x902bd70) (BuildId: 45bec31f5b513518)
    #9 0xaaaad741d1f8 in rd_kafka_broker_ops_io_serve (/usr/local/bin/testdrive+0x902d1f8) (BuildId: 45bec31f5b513518)
    #10 0xaaaad741d8c4 in rd_kafka_broker_consumer_serve (/usr/local/bin/testdrive+0x902d8c4) (BuildId: 45bec31f5b513518)
    #11 0xaaaad741ea4c in rd_kafka_broker_serve (/usr/local/bin/testdrive+0x902ea4c) (BuildId: 45bec31f5b513518)
    #12 0xaaaad741f3c8 in rd_kafka_broker_thread_main (/usr/local/bin/testdrive+0x902f3c8) (BuildId: 45bec31f5b513518)
    #13 0xaaaad74ad5c8 in _thrd_wrapper_function (/usr/local/bin/testdrive+0x90bd5c8) (BuildId: 45bec31f5b513518)
    #14 0xaaaad0c28438 in asan_thread_start(void*) (/usr/local/bin/testdrive+0x2838438) (BuildId: 45bec31f5b513518)
    #15 0xffff85c75ed8  (/lib/aarch64-linux-gnu/libc.so.6+0xe5ed8) (BuildId: 3ba44e06b9dc66aeeb2651db4dd015ffaf6e0849)

Indirect leak of 184 byte(s) in 1 object(s) allocated from:
    #0 0xaaaad0cd625c in malloc.part.9 (/usr/local/bin/testdrive+0x28e625c) (BuildId: 45bec31f5b513518)
    #1 0xaaaad745338c in rd_kafka_q_new0 (/usr/local/bin/testdrive+0x906338c) (BuildId: 45bec31f5b513518)
    #2 0xaaaad741afb4 in rd_kafka_broker_add (/usr/local/bin/testdrive+0x902afb4) (BuildId: 45bec31f5b513518)
    #3 0xaaaad741b8e8 in rd_kafka_brokers_add0 (/usr/local/bin/testdrive+0x902b8e8) (BuildId: 45bec31f5b513518)
    #4 0xaaaad7408650 in rd_kafka_new (/usr/local/bin/testdrive+0x9018650) (BuildId: 45bec31f5b513518)
    #5 0xaaaad62304a0 in <rdkafka::client::Client<rdkafka::consumer::DefaultConsumerContext>>::new (/usr/local/bin/testdrive+0x7e404a0) (BuildId: 45bec31f5b513518)

Indirect leak of 184 byte(s) in 1 object(s) allocated from:
    #0 0xaaaad0cd625c in malloc.part.9 (/usr/local/bin/testdrive+0x28e625c) (BuildId: 45bec31f5b513518)
    #1 0xaaaad745338c in rd_kafka_q_new0 (/usr/local/bin/testdrive+0x906338c) (BuildId: 45bec31f5b513518)
    #2 0xaaaad74082cc in rd_kafka_new (/usr/local/bin/testdrive+0x90182cc) (BuildId: 45bec31f5b513518)
    #3 0xaaaad62304a0 in <rdkafka::client::Client<rdkafka::consumer::DefaultConsumerContext>>::new (/usr/local/bin/testdrive+0x7e404a0) (BuildId: 45bec31f5b513518)

Indirect leak of 49 byte(s) in 1 object(s) allocated from:
    #0 0xaaaad0cd625c in malloc.part.9 (/usr/local/bin/testdrive+0x28e625c) (BuildId: 45bec31f5b513518)
    #1 0xaaaad7454704 in rd_kafka_q_io_event_enable (/usr/local/bin/testdrive+0x9064704) (BuildId: 45bec31f5b513518)
    #2 0xaaaad741b330 in rd_kafka_broker_add (/usr/local/bin/testdrive+0x902b330) (BuildId: 45bec31f5b513518)
    #3 0xaaaad741b8e8 in rd_kafka_brokers_add0 (/usr/local/bin/testdrive+0x902b8e8) (BuildId: 45bec31f5b513518)
    #4 0xaaaad7408650 in rd_kafka_new (/usr/local/bin/testdrive+0x9018650) (BuildId: 45bec31f5b513518)
    #5 0xaaaad62304a0 in <rdkafka::client::Client<rdkafka::consumer::DefaultConsumerContext>>::new (/usr/local/bin/testdrive+0x7e404a0) (BuildId: 45bec31f5b513518)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0xaaaad0cd625c in malloc.part.9 (/usr/local/bin/testdrive+0x28e625c) (BuildId: 45bec31f5b513518)
    #1 0xaaaad74aa7ac in rd_list_new (/usr/local/bin/testdrive+0x90ba7ac) (BuildId: 45bec31f5b513518)
    #2 0xaaaad74aaff4 in rd_list_copy (/usr/local/bin/testdrive+0x90baff4) (BuildId: 45bec31f5b513518)
    #3 0xaaaad7462aa8 in rd_kafka_MetadataRequest (/usr/local/bin/testdrive+0x9072aa8) (BuildId: 45bec31f5b513518)
    #4 0xaaaad743a4d0 in rd_kafka_metadata_refresh_topics (/usr/local/bin/testdrive+0x904a4d0) (BuildId: 45bec31f5b513518)
    #5 0xaaaad743a900 in rd_kafka_metadata_refresh_known_topics (/usr/local/bin/testdrive+0x904a900) (BuildId: 45bec31f5b513518)
    #6 0xaaaad74109a0 in rd_kafka_broker_fail (/usr/local/bin/testdrive+0x90209a0) (BuildId: 45bec31f5b513518)
    #7 0xaaaad741bd70 in rd_kafka_broker_op_serve (/usr/local/bin/testdrive+0x902bd70) (BuildId: 45bec31f5b513518)
    #8 0xaaaad741d1f8 in rd_kafka_broker_ops_io_serve (/usr/local/bin/testdrive+0x902d1f8) (BuildId: 45bec31f5b513518)
    #9 0xaaaad741d8c4 in rd_kafka_broker_consumer_serve (/usr/local/bin/testdrive+0x902d8c4) (BuildId: 45bec31f5b513518)
    #10 0xaaaad741ea4c in rd_kafka_broker_serve (/usr/local/bin/testdrive+0x902ea4c) (BuildId: 45bec31f5b513518)
    #11 0xaaaad741f3c8 in rd_kafka_broker_thread_main (/usr/local/bin/testdrive+0x902f3c8) (BuildId: 45bec31f5b513518)
    #12 0xaaaad74ad5c8 in _thrd_wrapper_function (/usr/local/bin/testdrive+0x90bd5c8) (BuildId: 45bec31f5b513518)
    #13 0xaaaad0c28438 in asan_thread_start(void*) (/usr/local/bin/testdrive+0x2838438) (BuildId: 45bec31f5b513518)
    #14 0xffff85c75ed8  (/lib/aarch64-linux-gnu/libc.so.6+0xe5ed8) (BuildId: 3ba44e06b9dc66aeeb2651db4dd015ffaf6e0849)

Indirect leak of 36 byte(s) in 1 object(s) allocated from:
    #0 0xaaaad0cba558 in __strdup (/usr/local/bin/testdrive+0x28ca558) (BuildId: 45bec31f5b513518)
    #1 0xaaaad74aaf90 in rd_list_copy_to (/usr/local/bin/testdrive+0x90baf90) (BuildId: 45bec31f5b513518)
    #2 0xaaaad74ab008 in rd_list_copy (/usr/local/bin/testdrive+0x90bb008) (BuildId: 45bec31f5b513518)
    #3 0xaaaad7462aa8 in rd_kafka_MetadataRequest (/usr/local/bin/testdrive+0x9072aa8) (BuildId: 45bec31f5b513518)
    #4 0xaaaad743a4d0 in rd_kafka_metadata_refresh_topics (/usr/local/bin/testdrive+0x904a4d0) (BuildId: 45bec31f5b513518)
    #5 0xaaaad743a900 in rd_kafka_metadata_refresh_known_topics (/usr/local/bin/testdrive+0x904a900) (BuildId: 45bec31f5b513518)
    #6 0xaaaad74109a0 in rd_kafka_broker_fail (/usr/local/bin/testdrive+0x90209a0) (BuildId: 45bec31f5b513518)
    #7 0xaaaad741bd70 in rd_kafka_broker_op_serve (/usr/local/bin/testdrive+0x902bd70) (BuildId: 45bec31f5b513518)
    #8 0xaaaad741d1f8 in rd_kafka_broker_ops_io_serve (/usr/local/bin/testdrive+0x902d1f8) (BuildId: 45bec31f5b513518)
    #9 0xaaaad741d8c4 in rd_kafka_broker_consumer_serve (/usr/local/bin/testdrive+0x902d8c4) (BuildId: 45bec31f5b513518)
    #10 0xaaaad741ea4c in rd_kafka_broker_serve (/usr/local/bin/testdrive+0x902ea4c) (BuildId: 45bec31f5b513518)
    #11 0xaaaad741f3c8 in rd_kafka_broker_thread_main (/usr/local/bin/testdrive+0x902f3c8) (BuildId: 45bec31f5b513518)
    #12 0xaaaad74ad5c8 in _thrd_wrapper_function (/usr/local/bin/testdrive+0x90bd5c8) (BuildId: 45bec31f5b513518)
    #13 0xaaaad0c28438 in asan_thread_start(void*) (/usr/local/bin/testdrive+0x2838438) (BuildId: 45bec31f5b513518)
    #14 0xffff85c75ed8  (/lib/aarch64-linux-gnu/libc.so.6+0xe5ed8) (BuildId: 3ba44e06b9dc66aeeb2651db4dd015ffaf6e0849)

Indirect leak of 36 byte(s) in 1 object(s) allocated from:
    #0 0xaaaad0cd6398 in calloc.part.10 (/usr/local/bin/testdrive+0x28e6398) (BuildId: 45bec31f5b513518)
    #1 0xaaaad7420040 in rd_getaddrinfo (/usr/local/bin/testdrive+0x9030040) (BuildId: 45bec31f5b513518)
    #2 0xaaaad741f500 in rd_kafka_broker_thread_main (/usr/local/bin/testdrive+0x902f500) (BuildId: 45bec31f5b513518)
    #3 0xaaaad74ad5c8 in _thrd_wrapper_function (/usr/local/bin/testdrive+0x90bd5c8) (BuildId: 45bec31f5b513518)
    #4 0xaaaad0c28438 in asan_thread_start(void*) (/usr/local/bin/testdrive+0x2838438) (BuildId: 45bec31f5b513518)
    #5 0xffff85c75ed8  (/lib/aarch64-linux-gnu/libc.so.6+0xe5ed8) (BuildId: 3ba44e06b9dc66aeeb2651db4dd015ffaf6e0849)

Indirect leak of 14 byte(s) in 1 object(s) allocated from:
    #0 0xaaaad0cba558 in __strdup (/usr/local/bin/testdrive+0x28ca558) (BuildId: 45bec31f5b513518)
    #1 0xaaaad741c678 in rd_kafka_broker_op_serve (/usr/local/bin/testdrive+0x902c678) (BuildId: 45bec31f5b513518)
    #2 0xaaaad741d1f8 in rd_kafka_broker_ops_io_serve (/usr/local/bin/testdrive+0x902d1f8) (BuildId: 45bec31f5b513518)
    #3 0xaaaad741d8c4 in rd_kafka_broker_consumer_serve (/usr/local/bin/testdrive+0x902d8c4) (BuildId: 45bec31f5b513518)
    #4 0xaaaad741ea4c in rd_kafka_broker_serve (/usr/local/bin/testdrive+0x902ea4c) (BuildId: 45bec31f5b513518)
    #5 0xaaaad741f3c8 in rd_kafka_broker_thread_main (/usr/local/bin/testdrive+0x902f3c8) (BuildId: 45bec31f5b513518)
    #6 0xaaaad74ad5c8 in _thrd_wrapper_function (/usr/local/bin/testdrive+0x90bd5c8) (BuildId: 45bec31f5b513518)
    #7 0xaaaad0c28438 in asan_thread_start(void*) (/usr/local/bin/testdrive+0x2838438) (BuildId: 45bec31f5b513518)
    #8 0xffff85c75ed8  (/lib/aarch64-linux-gnu/libc.so.6+0xe5ed8) (BuildId: 3ba44e06b9dc66aeeb2651db4dd015ffaf6e0849)

Indirect leak of 12 byte(s) in 1 object(s) allocated from:
    #0 0xaaaad0cba558 in __strdup (/usr/local/bin/testdrive+0x28ca558) (BuildId: 45bec31f5b513518)
    #1 0xaaaad74628ac in rd_kafka_MetadataRequest (/usr/local/bin/testdrive+0x90728ac) (BuildId: 45bec31f5b513518)
    #2 0xaaaad743a4d0 in rd_kafka_metadata_refresh_topics (/usr/local/bin/testdrive+0x904a4d0) (BuildId: 45bec31f5b513518)
    #3 0xaaaad743a900 in rd_kafka_metadata_refresh_known_topics (/usr/local/bin/testdrive+0x904a900) (BuildId: 45bec31f5b513518)
    #4 0xaaaad74109a0 in rd_kafka_broker_fail (/usr/local/bin/testdrive+0x90209a0) (BuildId: 45bec31f5b513518)
    #5 0xaaaad741bd70 in rd_kafka_broker_op_serve (/usr/local/bin/testdrive+0x902bd70) (BuildId: 45bec31f5b513518)
    #6 0xaaaad741d1f8 in rd_kafka_broker_ops_io_serve (/usr/local/bin/testdrive+0x902d1f8) (BuildId: 45bec31f5b513518)
    #7 0xaaaad741d8c4 in rd_kafka_broker_consumer_serve (/usr/local/bin/testdrive+0x902d8c4) (BuildId: 45bec31f5b513518)
    #8 0xaaaad741ea4c in rd_kafka_broker_serve (/usr/local/bin/testdrive+0x902ea4c) (BuildId: 45bec31f5b513518)
    #9 0xaaaad741f3c8 in rd_kafka_broker_thread_main (/usr/local/bin/testdrive+0x902f3c8) (BuildId: 45bec31f5b513518)
    #10 0xaaaad74ad5c8 in _thrd_wrapper_function (/usr/local/bin/testdrive+0x90bd5c8) (BuildId: 45bec31f5b513518)
    #11 0xaaaad0c28438 in asan_thread_start(void*) (/usr/local/bin/testdrive+0x2838438) (BuildId: 45bec31f5b513518)
    #12 0xffff85c75ed8  (/lib/aarch64-linux-gnu/libc.so.6+0xe5ed8) (BuildId: 3ba44e06b9dc66aeeb2651db4dd015ffaf6e0849)

Indirect leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0xaaaad0cd64b0 in realloc.part.12 (/usr/local/bin/testdrive+0x28e64b0) (BuildId: 45bec31f5b513518)
    #1 0xaaaad74aa728 in rd_list_grow (/usr/local/bin/testdrive+0x90ba728) (BuildId: 45bec31f5b513518)
    #2 0xaaaad74aa76c in rd_list_init (/usr/local/bin/testdrive+0x90ba76c) (BuildId: 45bec31f5b513518)
    #3 0xaaaad74aa7bc in rd_list_new (/usr/local/bin/testdrive+0x90ba7bc) (BuildId: 45bec31f5b513518)
    #4 0xaaaad74aaff4 in rd_list_copy (/usr/local/bin/testdrive+0x90baff4) (BuildId: 45bec31f5b513518)
    #5 0xaaaad7462aa8 in rd_kafka_MetadataRequest (/usr/local/bin/testdrive+0x9072aa8) (BuildId: 45bec31f5b513518)
    #6 0xaaaad743a4d0 in rd_kafka_metadata_refresh_topics (/usr/local/bin/testdrive+0x904a4d0) (BuildId: 45bec31f5b513518)
    #7 0xaaaad743a900 in rd_kafka_metadata_refresh_known_topics (/usr/local/bin/testdrive+0x904a900) (BuildId: 45bec31f5b513518)
    #8 0xaaaad74109a0 in rd_kafka_broker_fail (/usr/local/bin/testdrive+0x90209a0) (BuildId: 45bec31f5b513518)
    #9 0xaaaad741bd70 in rd_kafka_broker_op_serve (/usr/local/bin/testdrive+0x902bd70) (BuildId: 45bec31f5b513518)
    #10 0xaaaad741d1f8 in rd_kafka_broker_ops_io_serve (/usr/local/bin/testdrive+0x902d1f8) (BuildId: 45bec31f5b513518)
    #11 0xaaaad741d8c4 in rd_kafka_broker_consumer_serve (/usr/local/bin/testdrive+0x902d8c4) (BuildId: 45bec31f5b513518)
    #12 0xaaaad741ea4c in rd_kafka_broker_serve (/usr/local/bin/testdrive+0x902ea4c) (BuildId: 45bec31f5b513518)
    #13 0xaaaad741f3c8 in rd_kafka_broker_thread_main (/usr/local/bin/testdrive+0x902f3c8) (BuildId: 45bec31f5b513518)
    #14 0xaaaad74ad5c8 in _thrd_wrapper_function (/usr/local/bin/testdrive+0x90bd5c8) (BuildId: 45bec31f5b513518)
    #15 0xaaaad0c28438 in asan_thread_start(void*) (/usr/local/bin/testdrive+0x2838438) (BuildId: 45bec31f5b513518)
    #16 0xffff85c75ed8  (/lib/aarch64-linux-gnu/libc.so.6+0xe5ed8) (BuildId: 3ba44e06b9dc66aeeb2651db4dd015ffaf6e0849)

Indirect leak of 7 byte(s) in 1 object(s) allocated from:
    #0 0xaaaad0cba558 in __strdup (/usr/local/bin/testdrive+0x28ca558) (BuildId: 45bec31f5b513518)
    #1 0xaaaad741af40 in rd_kafka_broker_add (/usr/local/bin/testdrive+0x902af40) (BuildId: 45bec31f5b513518)
    #2 0xaaaad741b8e8 in rd_kafka_brokers_add0 (/usr/local/bin/testdrive+0x902b8e8) (BuildId: 45bec31f5b513518)
    #3 0xaaaad7408650 in rd_kafka_new (/usr/local/bin/testdrive+0x9018650) (BuildId: 45bec31f5b513518)
    #4 0xaaaad62304a0 in <rdkafka::client::Client<rdkafka::consumer::DefaultConsumerContext>>::new (/usr/local/bin/testdrive+0x7e404a0) (BuildId: 45bec31f5b513518)

SUMMARY: AddressSanitizer: 4998 byte(s) leaked in 15 allocation(s).
```

Similar to https://github.com/MaterializeInc/materialize/issues/25078, seen in testdrive binary in https://buildkite.com/materialize/nightlies/builds/6358#018d8916-ec85-4c69-8393-ca7ea2861bfa (via https://github.com/MaterializeInc/materialize/pull/24888).

**Comment by benesch** [comment]
As with https://github.com/MaterializeInc/materialize/issues/25070#issuecomment-1937060648:

I've added this to the storage mega tracker under a new "Sanitizer issue" heading. It's tough to know how seriously to take these issues because the sanitizers all seem to have a fair number of false positives.
