### ISSUE TITLE
lsan: thread 'tokio:work-52' panicked at src/transform/src/dataflow.rs:1165:13: CollectIndexRequests encountered a dangling ArrangeBy

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#25074]
### What version of Materialize are you using?

87b5813731 (Pull Request #25030)

### What is the issue?

```
thread 'tokio:work-52' panicked at src/transform/src/dataflow.rs:1165:13:
CollectIndexRequests encountered a dangling ArrangeBy
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/4cb3beec86178baff601529389306a4949b077ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at ./rustc/4cb3beec86178baff601529389306a4949b077ce/library/core/src/panicking.rs:72:14
   2: <mz_transform::dataflow::IndexUsageContext>::add_keys
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0874988e18ed036ce-1/materialize/tests/src/transform/src/dataflow.rs:1165:13
   3: <mz_transform::dataflow::CollectIndexRequests>::collect_index_reqs_inner::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0874988e18ed036ce-1/materialize/tests/src/transform/src/dataflow.rs:938:59
   4: <mz_transform::dataflow::CollectIndexRequests as mz_ore::stack::CheckedRecursion>::checked_recur_mut::<<mz_transform::dataflow::CollectIndexRequests>::collect_index_reqs_inner::{closure#0}, (), mz_ore::stack::RecursionLimitError>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0874988e18ed036ce-1/materialize/tests/src/ore/src/stack.rs:205:33
   5: stacker::maybe_grow::<core::result::Result<(), mz_ore::stack::RecursionLimitError>, <mz_transform::dataflow::CollectIndexRequests as mz_ore::stack::CheckedRecursion>::checked_recur_mut<<mz_transform::dataflow::CollectIndexRequests>::collect_index_reqs_inner::{closure#0}, (), mz_ore::stack::RecursionLimitError>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
   6: mz_ore::stack::maybe_grow::<<mz_transform::dataflow::CollectIndexRequests as mz_ore::stack::CheckedRecursion>::checked_recur_mut<<mz_transform::dataflow::CollectIndexRequests>::collect_index_reqs_inner::{closure#0}, (), mz_ore::stack::RecursionLimitError>::{closure#0}, core::result::Result<(), mz_ore::stack::RecursionLimitError>>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0874988e18ed036ce-1/materialize/tests/src/ore/src/stack.rs:100:5
   7: <mz_transform::dataflow::CollectIndexRequests as mz_ore::stack::CheckedRecursion>::checked_recur_mut::<<mz_transform::dataflow::CollectIndexRequests>::collect_index_reqs_inner::{closure#0}, (), mz_ore::stack::RecursionLimitError>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0874988e18ed036ce-1/materialize/tests/src/ore/src/stack.rs:205:19
   8: <mz_transform::dataflow::CollectIndexRequests>::collect_index_reqs_inner
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0874988e18ed036ce-1/materialize/tests/src/transform/src/dataflow.rs:873:9
   9: <mz_transform::dataflow::CollectIndexRequests>::collect_index_reqs_inner::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0874988e18ed036ce-1/materialize/tests/src/transform/src/dataflow.rs:1105:25
  10: <mz_transform::dataflow::CollectIndexRequests as mz_ore::stack::CheckedRecursion>::checked_recur_mut::<<mz_transform::dataflow::CollectIndexRequests>::collect_index_reqs_inner::{closure#0}, (), mz_ore::stack::RecursionLimitError>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0874988e18ed036ce-1/materialize/tests/src/ore/src/stack.rs:205:33
  11: stacker::maybe_grow::<core::result::Result<(), mz_ore::stack::RecursionLimitError>, <mz_transform::dataflow::CollectIndexRequests as mz_ore::stack::CheckedRecursion>::checked_recur_mut<<mz_transform::dataflow::CollectIndexRequests>::collect_index_reqs_inner::{closure#0}, (), mz_ore::stack::RecursionLimitError>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/stacker-0.1.15/src/lib.rs:55:9
  12: mz_ore::stack::maybe_grow::<<mz_transform::dataflow::CollectIndexRequests as mz_ore::stack::CheckedRecursion>::checked_recur_mut<<mz_transform::dataflow::CollectIndexRequests>::collect_index_reqs_inner::{closure#0}, (), mz_ore::stack::RecursionLimitError>::{closure#0}, core::result::Result<(), mz_ore::stack::RecursionLimitError>>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0874988e18ed036ce-1/materialize/tests/src/ore/src/stack.rs:100:5
  13: <mz_transform::dataflow::CollectIndexRequests as mz_ore::stack::CheckedRecursion>::checked_recur_mut::<<mz_transform::dataflow::CollectIndexRequests>::collect_index_reqs_inner::{closure#0}, (), mz_ore::stack::RecursionLimitError>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0874988e18ed036ce-1/materialize/tests/src/ore/src/stack.rs:205:19
  14: <mz_transform::dataflow::CollectIndexRequests>::collect_index_reqs_inner
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0874988e18ed036ce-1/materialize/tests/src/transform/src/dataflow.rs:873:9
  15: <mz_transform::dataflow::CollectIndexRequests>::collect_index_reqs
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0874988e18ed036ce-1/materialize/tests/src/transform/src/dataflow.rs:860:9
  16: mz_transform::dataflow::prune_and_annotate_dataflow_index_imports
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0874988e18ed036ce-1/materialize/tests/src/transform/src/dataflow.rs:530:9
  17: mz_transform::dataflow::optimize_dataflow
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0874988e18ed036ce-1/materialize/tests/src/transform/src/dataflow.rs:101:5
  18: <mz_adapter::optimize::peek::Optimizer as mz_adapter::optimize::Optimize<mz_adapter::optimize::peek::LocalMirPlan<mz_adapter::optimize::peek::ResolvedLocal>>>::optimize
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0874988e18ed036ce-1/materialize/tests/src/adapter/src/optimize/peek.rs:296:23
  19: <mz_adapter::optimize::peek::Optimizer as mz_adapter::optimize::Optimize<mz_adapter::optimize::peek::LocalMirPlan<mz_adapter::optimize::peek::ResolvedLocal>>>::catch_unwind_optimize::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0874988e18ed036ce-1/materialize/tests/src/adapter/src/optimize/mod.rs:105:63
  20: <core::panic::unwind_safe::AssertUnwindSafe<<mz_adapter::optimize::peek::Optimizer as mz_adapter::optimize::Optimize<mz_adapter::optimize::peek::LocalMirPlan<mz_adapter::optimize::peek::ResolvedLocal>>>::catch_unwind_optimize::{closure#0}> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/4cb3beec86178baff601529389306a4949b077ce/library/core/src/panic/unwind_safe.rs:272:9
  21: std::panicking::try::do_call::<core::panic::unwind_safe::AssertUnwindSafe<<mz_adapter::optimize::peek::Optimizer as mz_adapter::optimize::Optimize<mz_adapter::optimize::peek::LocalMirPlan<mz_adapter::optimize::peek::ResolvedLocal>>>::catch_unwind_optimize::{closure#0}>, core::result::Result<mz_adapter::optimize::peek::GlobalMirPlan, mz_adapter::optimize::OptimizerError>>
             at ./rustc/4cb3beec86178baff601529389306a4949b077ce/library/std/src/panicking.rs:552:40
  22: std::panicking::try::<core::result::Result<mz_adapter::optimize::peek::GlobalMirPlan, mz_adapter::optimize::OptimizerError>, core::panic::unwind_safe::AssertUnwindSafe<<mz_adapter::optimize::peek::Optimizer as mz_adapter::optimize::Optimize<mz_adapter::optimize::peek::LocalMirPlan<mz_adapter::optimize::peek::ResolvedLocal>>>::catch_unwind_optimize::{closure#0}>>
             at ./rustc/4cb3beec86178baff601529389306a4949b077ce/library/std/src/panicking.rs:516:19
  23: std::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<<mz_adapter::optimize::peek::Optimizer as mz_adapter::optimize::Optimize<mz_adapter::optimize::peek::LocalMirPlan<mz_adapter::optimize::peek::ResolvedLocal>>>::catch_unwind_optimize::{closure#0}>, core::result::Result<mz_adapter::optimize::peek::GlobalMirPlan, mz_adapter::optimize::OptimizerError>>
             at ./rustc/4cb3beec86178baff601529389306a4949b077ce/library/std/src/panic.rs:142:14
  24: mz_ore::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<<mz_adapter::optimize::peek::Optimizer as mz_adapter::optimize::Optimize<mz_adapter::optimize::peek::LocalMirPlan<mz_adapter::optimize::peek::ResolvedLocal>>>::catch_unwind_optimize::{closure#0}>, core::result::Result<mz_adapter::optimize::peek::GlobalMirPlan, mz_adapter::optimize::OptimizerError>>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0874988e18ed036ce-1/materialize/tests/src/ore/src/panic.rs:78:19
  25: <std::thread::local::LocalKey<core::cell::RefCell<bool>>>::try_with::<mz_ore::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<<mz_adapter::optimize::peek::Optimizer as mz_adapter::optimize::Optimize<mz_adapter::optimize::peek::LocalMirPlan<mz_adapter::optimize::peek::ResolvedLocal>>>::catch_unwind_optimize::{closure#0}>, core::result::Result<mz_adapter::optimize::peek::GlobalMirPlan, mz_adapter::optimize::OptimizerError>>::{closure#0}, core::result::Result<core::result::Result<mz_adapter::optimize::peek::GlobalMirPlan, mz_adapter::optimize::OptimizerError>, alloc::boxed::Box<dyn core::any::Any + core::marker::Send>>>
             at ./rustc/4cb3beec86178baff601529389306a4949b077ce/library/std/src/thread/local.rs:270:16
  26: <std::thread::local::LocalKey<core::cell::RefCell<bool>>>::with::<mz_ore::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<<mz_adapter::optimize::peek::Optimizer as mz_adapter::optimize::Optimize<mz_adapter::optimize::peek::LocalMirPlan<mz_adapter::optimize::peek::ResolvedLocal>>>::catch_unwind_optimize::{closure#0}>, core::result::Result<mz_adapter::optimize::peek::GlobalMirPlan, mz_adapter::optimize::OptimizerError>>::{closure#0}, core::result::Result<core::result::Result<mz_adapter::optimize::peek::GlobalMirPlan, mz_adapter::optimize::OptimizerError>, alloc::boxed::Box<dyn core::any::Any + core::marker::Send>>>
             at ./rustc/4cb3beec86178baff601529389306a4949b077ce/library/std/src/thread/local.rs:246:9
  27: mz_ore::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<<mz_adapter::optimize::peek::Optimizer as mz_adapter::optimize::Optimize<mz_adapter::optimize::peek::LocalMirPlan<mz_adapter::optimize::peek::ResolvedLocal>>>::catch_unwind_optimize::{closure#0}>, core::result::Result<mz_adapter::optimize::peek::GlobalMirPlan, mz_adapter::optimize::OptimizerError>>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0874988e18ed036ce-1/materialize/tests/src/ore/src/panic.rs:75:21
  28: <mz_adapter::optimize::peek::Optimizer as mz_adapter::optimize::Optimize<mz_adapter::optimize::peek::LocalMirPlan<mz_adapter::optimize::peek::ResolvedLocal>>>::catch_unwind_optimize
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0874988e18ed036ce-1/materialize/tests/src/adapter/src/optimize/mod.rs:105:15
  29: <mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0874988e18ed036ce-1/materialize/tests/src/adapter/src/coord/sequencer/inner/peek.rs:586:33
  30: <mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0874988e18ed036ce-1/materialize/tests/src/adapter/src/coord/sequencer/inner/peek.rs:603:35
  31: <tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/task.rs:42:21
  32: <tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  33: <tokio::runtime::task::core::Core<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:334:17
  34: <tokio::loom::std::unsafe_cell::UnsafeCell<tokio::runtime::task::core::Stage<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>>>>>::with_mut::<core::task::poll::Poll<()>, <tokio::runtime::task::core::Core<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/loom/std/unsafe_cell.rs:16:9
  35: <tokio::runtime::task::core::Core<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:323:13
  36: tokio::runtime::task::harness::poll_future::<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:485:19
  37: <core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/4cb3beec86178baff601529389306a4949b077ce/library/core/src/panic/unwind_safe.rs:272:9
  38: std::panicking::try::do_call::<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}>, core::task::poll::Poll<()>>
             at ./rustc/4cb3beec86178baff601529389306a4949b077ce/library/std/src/panicking.rs:552:40
  39: std::panicking::try::<core::task::poll::Poll<()>, core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}>>
             at ./rustc/4cb3beec86178baff601529389306a4949b077ce/library/std/src/panicking.rs:516:19
  40: std::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}>, core::task::poll::Poll<()>>
             at ./rustc/4cb3beec86178baff601529389306a4949b077ce/library/std/src/panic.rs:142:14
  41: tokio::runtime::task::harness::poll_future::<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>>, tokio::runtime::blocking::schedule::BlockingSchedule>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:473:18
  42: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll_inner
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:208:27
  43: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<mz_adapter::coord::Coordinator>::peek_stage_optimize_mir::{closure#0}::{closure#0}::{closure#2}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:153:15
  44: <tokio::runtime::task::raw::RawTask>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/raw.rs:200:18
  45: <tokio::runtime::task::UnownedTask<tokio::runtime::blocking::schedule::BlockingSchedule>>::run
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/mod.rs:437:9
  46: <tokio::runtime::blocking::pool::Task>::run
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:159:9
  47: <tokio::runtime::blocking::pool::Inner>::run
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:513:17
  48: <tokio::runtime::blocking::pool::Spawner>::spawn_thread::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:471:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Seen in RQG with WMR: https://buildkite.com/materialize/nightlies/builds/6357#018d8908-383f-4e3f-8876-051284838d66 using leak sanitizer (https://github.com/MaterializeInc/materialize/pull/25030)
This is a soft panic.

ci-regexp: CollectIndexRequests encountered a dangling ArrangeBy

**Comment by def-** [comment]
Probably duplicate of https://github.com/MaterializeInc/materialize/issues/24451
