### ISSUE TITLE
debug panic: Attempt to add with overflow in truncate_low_fields

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#25182]
### What version of Materialize are you using?

main

### What is the issue?

```
thread 'timely:work-0' panicked at src/repr/src/adt/interval.rs:489:21:
attempt to add with overflow
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/4cb3beec86178baff601529389306a4949b077ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at ./rustc/4cb3beec86178baff601529389306a4949b077ce/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at ./rustc/4cb3beec86178baff601529389306a4949b077ce/library/core/src/panicking.rs:127:5
   3: <mz_repr::adt::interval::Interval>::truncate_low_fields
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0a64d05c687e98f0e-1/materialize/tests/src/repr/src/adt/interval.rs:489:21
   4: mz_expr::scalar::func::date_trunc_interval
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0a64d05c687e98f0e-1/materialize/tests/src/expr/src/scalar/func.rs:1828:5
   5: <mz_expr::scalar::func::BinaryFunc>::eval
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0a64d05c687e98f0e-1/materialize/tests/src/expr/src/scalar/func.rs:2516:46
   6: <mz_expr::scalar::func::impls::interval::CastIntervalToString as mz_expr::scalar::func::LazyUnaryFunc>::eval
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0a64d05c687e98f0e-1/materialize/tests/src/expr/src/scalar/func.rs:4372:41
   7: <mz_expr::linear::plan::SafeMfpPlan>::evaluate_inner
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0a64d05c687e98f0e-1/materialize/tests/src/expr/src/linear.rs:1538:29
   8: <mz_expr::linear::plan::MfpPlan>::evaluate::<mz_storage_types::errors::DataflowError, <mz_storage_operators::persist_source::PendingWork>::do_work<timely::dataflow::channels::pushers::tee::TeeCore<(mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime), alloc::vec::Vec<(core::result::Result<mz_repr::row::Row, mz_storage_types::errors::DataflowError>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime), i64)>>, mz_storage_operators::persist_source::decode_and_mfp<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}::{closure#0}::{closure#1}>::{closure#0}>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0a64d05c687e98f0e-1/materialize/tests/src/expr/src/linear.rs:1781:19
   9: <mz_storage_operators::persist_source::PendingWork>::do_work::<timely::dataflow::channels::pushers::tee::TeeCore<(mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime), alloc::vec::Vec<(core::result::Result<mz_repr::row::Row, mz_storage_types::errors::DataflowError>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime), i64)>>, mz_storage_operators::persist_source::decode_and_mfp<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}::{closure#0}::{closure#1}>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0a64d05c687e98f0e-1/materialize/tests/src/storage-operators/src/persist_source.rs:538:39
  10: mz_storage_operators::persist_source::decode_and_mfp::<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0a64d05c687e98f0e-1/materialize/tests/src/storage-operators/src/persist_source.rs:435:28
  11: <timely::dataflow::operators::generic::builder_rc::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>>::build::<mz_storage_operators::persist_source::decode_and_mfp<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}, mz_storage_operators::persist_source::decode_and_mfp<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}::{closure#0}>::{closure#0}::{closure#0}
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/dataflow/operators/generic/builder_rc.rs:133:31
  12: <timely::dataflow::operators::generic::builder_rc::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>>::build_reschedule::<<timely::dataflow::operators::generic::builder_rc::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>>::build<mz_storage_operators::persist_source::decode_and_mfp<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}, mz_storage_operators::persist_source::decode_and_mfp<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}::{closure#0}>::{closure#0}, <timely::dataflow::operators::generic::builder_rc::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>>::build<mz_storage_operators::persist_source::decode_and_mfp<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}, mz_storage_operators::persist_source::decode_and_mfp<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}::{closure#0}>::{closure#0}::{closure#0}>::{closure#0}
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/dataflow/operators/generic/builder_rc.rs:172:26
  13: <timely::dataflow::operators::generic::builder_raw::OperatorCore<(mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime), <timely::dataflow::operators::generic::builder_rc::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>>::build_reschedule<<timely::dataflow::operators::generic::builder_rc::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>>::build<mz_storage_operators::persist_source::decode_and_mfp<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}, mz_storage_operators::persist_source::decode_and_mfp<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}::{closure#0}>::{closure#0}, <timely::dataflow::operators::generic::builder_rc::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>>::build<mz_storage_operators::persist_source::decode_and_mfp<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}, mz_storage_operators::persist_source::decode_and_mfp<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, mz_repr::timestamp::Timestamp>, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::{closure#1}::{closure#0}>::{closure#0}::{closure#0}>::{closure#0}> as timely::scheduling::Schedule>::schedule
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/dataflow/operators/generic/builder_raw.rs:204:9
  14: <timely::progress::subgraph::PerOperatorState<(mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::schedule
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/progress/subgraph.rs:699:30
  15: <timely::progress::subgraph::Subgraph<mz_repr::timestamp::Timestamp, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)>>::activate_child
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/progress/subgraph.rs:346:26
  16: <timely::progress::subgraph::Subgraph<mz_repr::timestamp::Timestamp, (mz_repr::timestamp::Timestamp, mz_storage_operators::persist_source::Subtime)> as timely::scheduling::Schedule>::schedule
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/progress/subgraph.rs:312:17
  17: <timely::progress::subgraph::PerOperatorState<mz_repr::timestamp::Timestamp>>::schedule
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/progress/subgraph.rs:699:30
  18: <timely::progress::subgraph::Subgraph<mz_repr::timestamp::Timestamp, mz_repr::timestamp::Timestamp>>::activate_child
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/progress/subgraph.rs:346:26
  19: <timely::progress::subgraph::Subgraph<mz_repr::timestamp::Timestamp, mz_repr::timestamp::Timestamp> as timely::scheduling::Schedule>::schedule
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/progress/subgraph.rs:312:17
  20: <timely::progress::subgraph::PerOperatorState<mz_repr::timestamp::Timestamp>>::schedule
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/progress/subgraph.rs:699:30
  21: <timely::progress::subgraph::Subgraph<mz_repr::timestamp::Timestamp, mz_repr::timestamp::Timestamp>>::activate_child
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/progress/subgraph.rs:346:26
  22: <timely::progress::subgraph::Subgraph<mz_repr::timestamp::Timestamp, mz_repr::timestamp::Timestamp> as timely::scheduling::Schedule>::schedule
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/progress/subgraph.rs:312:17
  23: <timely::progress::subgraph::PerOperatorState<mz_repr::timestamp::Timestamp>>::schedule
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/progress/subgraph.rs:699:30
  24: <timely::progress::subgraph::Subgraph<(), mz_repr::timestamp::Timestamp>>::activate_child
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/progress/subgraph.rs:346:26
  25: <timely::progress::subgraph::Subgraph<(), mz_repr::timestamp::Timestamp> as timely::scheduling::Schedule>::schedule
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/progress/subgraph.rs:312:17
  26: <timely::worker::Wrapper>::step::{closure#0}
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/worker.rs:754:57
  27: <core::option::Option<&mut alloc::boxed::Box<dyn timely::scheduling::Schedule>>>::map::<bool, <timely::worker::Wrapper>::step::{closure#0}>
             at ./rustc/4cb3beec86178baff601529389306a4949b077ce/library/core/src/option.rs:1072:29
  28: <timely::worker::Wrapper>::step
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/worker.rs:754:48
  29: <timely::worker::Worker<timely_communication::allocator::generic::Generic>>::step_or_park
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/worker.rs:396:38
  30: <mz_compute::server::Worker<timely_communication::allocator::generic::Generic>>::run_client
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0a64d05c687e98f0e-1/materialize/tests/src/compute/src/server.rs:447:13
  31: <mz_compute::server::Worker<timely_communication::allocator::generic::Generic>>::setup_channel_and_run_client
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0a64d05c687e98f0e-1/materialize/tests/src/compute/src/server.rs:420:9
  32: <mz_compute::server::Worker<timely_communication::allocator::generic::Generic>>::run
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0a64d05c687e98f0e-1/materialize/tests/src/compute/src/server.rs:277:21
  33: <mz_compute::server::Config as mz_cluster::types::AsRunnableWorker<mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse>>::build_and_run::<timely_communication::allocator::generic::Generic>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0a64d05c687e98f0e-1/materialize/tests/src/compute/src/server.rs:213:9
  34: <mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse, timely::scheduling::activate::SyncActivator>, mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse>, mz_compute::server::Config, mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse>>::build_timely::{closure#0}::{closure#2}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0a64d05c687e98f0e-1/materialize/tests/src/cluster/src/server.rs:235:13
  35: timely::execute::execute_from::<timely_communication::allocator::generic::GenericBuilder, (), <mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse, timely::scheduling::activate::SyncActivator>, mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse>, mz_compute::server::Config, mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse>>::build_timely::{closure#0}::{closure#2}>::{closure#0}
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/execute.rs:388:22
  36: timely_communication::initialize::initialize_from::<timely_communication::allocator::generic::GenericBuilder, (), timely::execute::execute_from<timely_communication::allocator::generic::GenericBuilder, (), <mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse, timely::scheduling::activate::SyncActivator>, mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse>, mz_compute::server::Config, mz_compute_client::protocol::command::ComputeCommand, mz_compute_client::protocol::response::ComputeResponse>>::build_timely::{closure#0}::{closure#2}>::{closure#0}>::{closure#0}
             at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/communication/src/initialize.rs:316:33
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Seen in https://buildkite.com/materialize/nightlies/builds/6412#018d9fb4-3ed3-416b-b4f8-d6837a8449d4 (with release build but debug assertions). Reproducer:

```sql
SELECT date_trunc('second', '2562047788:00:54.775807'::INTERVAL);
```

In Release mode the result is wrong:
```
        date_trunc
--------------------------
 -2562047788:00:54.551616
(1 row)
```

The code in question was introduced in https://github.com/MaterializeInc/materialize/pull/10749

**Comment by jkosh44** [comment]
The issue here is that we don't check for overflow when rounding up. However, while looking at the code I've found two more issues.

1. We do not handle negative round correctly at all.

```
materialize=> SELECT date_trunc('second', '-1.999'::INTERVAL);
 date_trunc 
------------
 -00:00:01
(1 row)

materialize=> SELECT date_trunc('second', '1.999'::INTERVAL);
 date_trunc 
------------
 00:00:02
(1 row)

```

We do not match PostgreSQL's behavior with rounding. Though to be honest, I cannot make sense of how they decide to round. I'll probably have to look into the code itself.

```
postgres=# SELECT date_trunc('second', '1.999'::INTERVAL);
 date_trunc 
------------
 00:00:01
(1 row)

postgres=# SELECT date_trunc('second', '1.999999'::INTERVAL);
 date_trunc 
------------
 00:00:01
(1 row)

postgres=# SELECT date_trunc('second', '1.9999999'::INTERVAL);
 date_trunc 
------------
 00:00:02
(1 row)

postgres=# SELECT date_trunc('second', '1.77777'::INTERVAL);
 date_trunc 
------------
 00:00:01
(1 row)

postgres=# SELECT date_trunc('second', '1.777777'::INTERVAL);
 date_trunc 
------------
 00:00:01
(1 row)

postgres=# SELECT date_trunc('second', '1.7777777'::INTERVAL);
 date_trunc 
------------
 00:00:01
(1 row)

postgres=# SELECT date_trunc('second', '1.77777777'::INTERVAL);
 date_trunc 
------------
 00:00:01
(1 row)


```

**Comment by jkosh44** [comment]
> Though to be honest, I cannot make sense of how they decide to round. I'll probably have to look into the code itself.

Ok I think I remember this now. `date_trunc` does not do any rounding in PostgreSQL (https://github.com/postgres/postgres/blob/c1fc502f595bc843a603bddd267b249272de485f/src/backend/utils/adt/timestamp.c#L4962-L5057). Any rounding we see comes from the Interval parsing stage.

**Comment by jkosh44** [comment]
We may have found another PostgreSQL Interval bug:

```
postgres=# SELECT INTERVAL '2562047788:00:54.775807' SECOND(2);
       interval       
----------------------
 -2562047788:00:54.77
(1 row)

postgres=# SELECT version();
                                                              version                                                              
-----------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 16.2 (Ubuntu 16.2-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit
(1 row)

```

There's some updates to Intervals coming in v17, so I'll have to check this against their `master` branch too.

**Comment by jkosh44** [comment]
> We may have found another PostgreSQL Interval bug:
> 
> ```
> postgres=# SELECT INTERVAL '2562047788:00:54.775807' SECOND(2);
>        interval       
> ----------------------
>  -2562047788:00:54.77
> (1 row)
> 
> postgres=# SELECT version();
>                                                               version                                                              
> -----------------------------------------------------------------------------------------------------------------------------------
>  PostgreSQL 16.2 (Ubuntu 16.2-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit
> (1 row)
> ```
> 
> There's some updates to Intervals coming in v17, so I'll have to check this against their `master` branch too.
> 
> EDIT: This bug still exists on `master` as of this comment.

This was during my lunch break, I promise: https://www.postgresql.org/message-id/CAAvxfHfpuLgqJYzkUcher466Z1LpmE%2B5Sm%2Bzc8L6zKCOQ%2B6TDQ%40mail.gmail.com
