### ISSUE TITLE
test_internal_console_proxy fails

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#25294]
### Buildkite link

https://buildkite.com/materialize/tests/builds/75860#018dadd6-2774-4a3b-a09d-aeb49651fa1c

### Relevant log output

```source
thread 'test_internal_console_proxy' panicked at src/environmentd/tests/server.rs:2015:5:
assertion failed: `left.contains(right)`:
  left: `"text/html; charset=utf-8"`
 right: `"text/css"`
stack backtrace:
   0: rust_begin_unwind
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: test_impl
             at ./tests/server.rs:2015:5
   3: server::test_internal_console_proxy
             at ./tests/server.rs:1997:1
   4: server::test_internal_console_proxy::{closure#0}
             at ./tests/server.rs:1997:1
   5: <server::test_internal_console_proxy::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by nrainer-materialize** [comment]
See: https://materializeinc.slack.com/archives/C06GZ7GBKB5/p1708026434867429
