### ISSUE TITLE
mysql: MySQL source bricked after restart when dropped a table

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#25365]
### What version of Materialize are you using?

ef1fe8032e

### What is the issue?

```
$ mysql-execute name=mysql
CREATE TABLE drop_table (f1 int, f2 int);
INSERT INTO drop_table (f1, f2) VALUES (1, 1);

> SELECT * from drop_table;
1 1

$ mysql-execute name=mysql
DROP TABLE drop_table;

> SELECT status FROM mz_internal.mz_source_statuses WHERE name = 'drop_table';
ceased

# this should not brick the whole source
> SELECT status FROM mz_internal.mz_source_statuses WHERE name = 'mz_source';
running
```

This works so far. However, if `mzcompose` conducts its sanity restart at the end of the test (`validate_sources_sinks_clusters` in `misc/python/materialize/mzcompose/composition.py`), it reports that the whole is stalled:

```
==> mzcompose: test case workflow-cdc failed: <class 'ValueError'>: Source mz_source is expected to be running/created, but is stalled, error: mysql: issue when decoding, details: {'namespaced': {'mysql': 'issue when decoding'}}
Traceback (most recent call last):
  File "/Users/nrainer/Workspaces/mz-repo/misc/python/materialize/mzcompose/composition.py", line 541, in test_case
    yield
  File "/Users/nrainer/Workspaces/mz-repo/misc/python/materialize/cli/mzcompose.py", line 619, in handle_composition
    composition.workflow(args.workflow, *args.unknown_subargs[1:])
  File "/Users/nrainer/Workspaces/mz-repo/misc/python/materialize/mzcompose/composition.py", line 438, in workflow
    self.sanity_restart_mz()
  File "/Users/nrainer/Workspaces/mz-repo/misc/python/materialize/mzcompose/composition.py", line 987, in sanity_restart_mz
    raise ValueError(error)
ValueError: Source mz_source is expected to be running/created, but is stalled, error: mysql: issue when decoding, details: {'namespaced': {'mysql': 'issue when decoding'}}
```

**Comment by nrainer-materialize** [comment]
https://github.com/MaterializeInc/materialize/blob/0d501a6ecbf8561a5ff49be57590bde511b39a00/test/mysql-cdc/alter-table-after-source.td#L415
