### ISSUE TITLE
thread 'timely:work-0' panicked at src/mysql-util/src/schemas.rs:114:13: assertion failed: !tables.is_empty()

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#25370]
### What version of Materialize are you using?

9d7408eeb3cb (Pull Request #25367)

### What is the issue?

```
mysql-cdc-materialized-1   | thread 'timely:work-0' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0b2e06f072c73d998-1/materialize/tests/src/mysql-util/src/schemas.rs:114:13:
mysql-cdc-materialized-1   | assertion failed: !tables.is_empty()
mysql-cdc-materialized-1   | stack backtrace:
mysql-cdc-materialized-1   | cluster-u1-replica-u1: 2024-02-19T12:41:08.185111Z  INFO mz_persist_client::internal::machine: snapshot s4a9051ec-98a0-42fa-b499-16bcc5953a98 as of [1708346466961] not yet available for v6 upper [0]
mysql-cdc-materialized-1   |    0: rust_begin_unwind
mysql-cdc-materialized-1   |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
mysql-cdc-materialized-1   |    1: core::panicking::panic_fmt
mysql-cdc-materialized-1   |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
mysql-cdc-materialized-1   |    2: core::panicking::panic
mysql-cdc-materialized-1   |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:127:5
mysql-cdc-materialized-1   |    3: mz_mysql_util::schemas::schema_info::<mysql_async::conn::Conn>::{closure#0}
mysql-cdc-materialized-1   |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0b2e06f072c73d998-1/materialize/tests/src/mysql-util/src/schemas.rs:114:13
mysql-cdc-materialized-1   |    4: mz_storage::source::mysql::schemas::verify_schemas::<mysql_async::conn::Conn>::{closure#0}
mysql-cdc-materialized-1   |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0b2e06f072c73d998-1/materialize/tests/src/storage/src/source/mysql/schemas.rs:40:6
mysql-cdc-materialized-1   |    5: mz_storage::source::mysql::replication::events::handle_query_event::{closure#0}
mysql-cdc-materialized-1   |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0b2e06f072c73d998-1/materialize/tests/src/storage/src/source/mysql/replication/events.rs:115:71
mysql-cdc-materialized-1   |    6: mz_storage::source::mysql::replication::render::<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>::{closure#2}::{closure#0}
mysql-cdc-materialized-1   |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0b2e06f072c73d998-1/materialize/tests/src/storage/src/source/mysql/replication.rs:385:88
mysql-cdc-materialized-1   |    7: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(), mz_storage::source::mysql::TransientError>>>> as core::future::future::Future>::poll
mysql-cdc-materialized-1   |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
mysql-cdc-materialized-1   |    8: <mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>>::build_fallible::<mz_storage::source::mysql::TransientError, mz_storage::source::mysql::replication::render<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>::{closure#2}>::{closure#0}::{closure#0}
mysql-cdc-materialized-1   |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0b2e06f072c73d998-1/materialize/tests/src/timely-util/src/builder_async.rs:650:55
mysql-cdc-materialized-1   |    9: <core::pin::Pin<alloc::boxed::Box<<mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>>::build_fallible<mz_storage::source::mysql::TransientError, mz_storage::source::mysql::replication::render<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>::{closure#2}>::{closure#0}::{closure#0}>> as core::future::future::Future>::poll
mysql-cdc-materialized-1   |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
mysql-cdc-materialized-1   |   10: <mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>>::build::<<mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>>::build_fallible<mz_storage::source::mysql::TransientError, mz_storage::source::mysql::replication::render<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>::{closure#2}>::{closure#0}, <mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>>::build_fallible<mz_storage::source::mysql::TransientError, mz_storage::source::mysql::replication::render<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>::{closure#2}>::{closure#0}::{closure#0}>::{closure#0}::{closure#0}
mysql-cdc-materialized-1   |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0b2e06f072c73d998-1/materialize/tests/src/timely-util/src/builder_async.rs:568:32
mysql-cdc-materialized-1   |   11: <timely::dataflow::operators::generic::builder_rc::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>>::build_reschedule::<<mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>>::build<<mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>>::build_fallible<mz_storage::source::mysql::TransientError, mz_storage::source::mysql::replication::render<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>::{closure#2}>::{closure#0}, <mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>>::build_fallible<mz_storage::source::mysql::TransientError, mz_storage::source::mysql::replication::render<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>::{closure#2}>::{closure#0}::{closure#0}>::{closure#0}, <mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>>::build<<mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>>::build_fallible<mz_storage::source::mysql::TransientError, mz_storage::source::mysql::replication::render<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>::{closure#2}>::{closure#0}, <mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>>::build_fallible<mz_storage::source::mysql::TransientError, mz_storage::source::mysql::replication::render<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>::{closure#2}>::{closure#0}::{closure#0}>::{closure#0}::{closure#0}>::{closure#0}
mysql-cdc-materialized-1   |              at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/dataflow/operators/generic/builder_rc.rs:172:26
mysql-cdc-materialized-1   |   12: <timely::dataflow::operators::generic::builder_raw::OperatorCore<mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>, <timely::dataflow::operators::generic::builder_rc::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>>::build_reschedule<<mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>>::build<<mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>>::build_fallible<mz_storage::source::mysql::TransientError, mz_storage::source::mysql::replication::render<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>::{closure#2}>::{closure#0}, <mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>>::build_fallible<mz_storage::source::mysql::TransientError, mz_storage::source::mysql::replication::render<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>::{closure#2}>::{closure#0}::{closure#0}>::{closure#0}, <mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>>::build<<mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>>::build_fallible<mz_storage::source::mysql::TransientError, mz_storage::source::mysql::replication::render<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>::{closure#2}>::{closure#0}, <mz_timely_util::builder_async::OperatorBuilder<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>>::build_fallible<mz_storage::source::mysql::TransientError, mz_storage::source::mysql::replication::render<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>::{closure#2}>::{closure#0}::{closure#0}>::{closure#0}::{closure#0}>::{closure#0}> as timely::scheduling::Schedule>::schedule
mysql-cdc-materialized-1   |              at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/dataflow/operators/generic/builder_raw.rs:204:9
mysql-cdc-materialized-1   |   13: <timely::progress::subgraph::PerOperatorState<mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>::schedule
mysql-cdc-materialized-1   |              at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/progress/subgraph.rs:699:30
mysql-cdc-materialized-1   |   14: <timely::progress::subgraph::Subgraph<(), mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>>>::activate_child
mysql-cdc-materialized-1   |              at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/progress/subgraph.rs:346:26
mysql-cdc-materialized-1   |   15: <timely::progress::subgraph::Subgraph<(), mz_timely_util::order::Partitioned<uuid::Uuid, mz_storage_types::sources::mysql::GtidState>> as timely::scheduling::Schedule>::schedule
mysql-cdc-materialized-1   |              at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/progress/subgraph.rs:312:17
mysql-cdc-materialized-1   |   16: <timely::progress::subgraph::PerOperatorState<()>>::schedule
mysql-cdc-materialized-1   |              at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/progress/subgraph.rs:699:30
mysql-cdc-materialized-1   |   17: <timely::progress::subgraph::Subgraph<(), ()>>::activate_child
mysql-cdc-materialized-1   |              at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/progress/subgraph.rs:346:26
mysql-cdc-materialized-1   |   18: <timely::progress::subgraph::Subgraph<(), ()> as timely::scheduling::Schedule>::schedule
mysql-cdc-materialized-1   |              at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/progress/subgraph.rs:312:17
mysql-cdc-materialized-1   |   19: <timely::worker::Wrapper>::step::{closure#0}
mysql-cdc-materialized-1   |              at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/worker.rs:754:57
mysql-cdc-materialized-1   |   20: <core::option::Option<&mut alloc::boxed::Box<dyn timely::scheduling::Schedule>>>::map::<bool, <timely::worker::Wrapper>::step::{closure#0}>
mysql-cdc-materialized-1   |              at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/option.rs:1075:29
mysql-cdc-materialized-1   |   21: <timely::worker::Wrapper>::step
mysql-cdc-materialized-1   |              at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/worker.rs:754:48
mysql-cdc-materialized-1   |   22: <timely::worker::Worker<timely_communication::allocator::generic::Generic>>::step_or_park
mysql-cdc-materialized-1   |              at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/worker.rs:396:38
mysql-cdc-materialized-1   |   23: <mz_storage::storage_state::Worker<timely_communication::allocator::generic::Generic>>::run_client
mysql-cdc-materialized-1   |   24: <mz_storage::storage_state::Worker<timely_communication::allocator::generic::Generic>>::run
mysql-cdc-materialized-1   |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0b2e06f072c73d998-1/materialize/tests/src/storage/src/storage_state.rs:467:21
mysql-cdc-materialized-1   |   25: <mz_storage::server::Config as mz_cluster::types::AsRunnableWorker<mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>>::build_and_run::<timely_communication::allocator::generic::Generic>
mysql-cdc-materialized-1   |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0b2e06f072c73d998-1/materialize/tests/src/storage/src/server.rs:107:9
mysql-cdc-materialized-1   |   26: <mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse, std::thread::Thread>, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>, mz_storage::server::Config, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>>::build_timely::{closure#0}::{closure#2}
mysql-cdc-materialized-1   |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0b2e06f072c73d998-1/materialize/tests/src/cluster/src/server.rs:235:13
mysql-cdc-materialized-1   |   27: timely::execute::execute_from::<timely_communication::allocator::generic::GenericBuilder, (), <mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse, std::thread::Thread>, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>, mz_storage::server::Config, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>>::build_timely::{closure#0}::{closure#2}>::{closure#0}
mysql-cdc-materialized-1   |              at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/timely/src/execute.rs:388:22
mysql-cdc-materialized-1   |   28: timely_communication::initialize::initialize_from::<timely_communication::allocator::generic::GenericBuilder, (), timely::execute::execute_from<timely_communication::allocator::generic::GenericBuilder, (), <mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse, std::thread::Thread>, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>, mz_storage::server::Config, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>>::build_timely::{closure#0}::{closure#2}>::{closure#0}>::{closure#0}
mysql-cdc-materialized-1   |              at ./cargo/git/checkouts/timely-dataflow-70b80d81d6cabd62/de20aa8/communication/src/initialize.rs:316:33
mysql-cdc-materialized-1   | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Seen in https://buildkite.com/materialize/tests/builds/76125#_

ci-regexp: assertion failed: !tables.is_empty()

**Comment by nrainer-materialize** [comment]
Another instance: https://buildkite.com/materialize/tests/builds/76057
