### ISSUE TITLE
`SinceViolation` in SUBSCRIBE sequencing

### ISSUE THREAD

**Issue by teskje** [MaterializeInc/materialize#25375]
### What version of Materialize are you using?

main

### What is the issue?

Bumping the compute controller's maintenance tick interval from 1s to 10s makes the Parallel Workload nightly job encounter a `SinceViolation` panic sometimes.

```
thread 'coordinator' panicked at src/adapter/src/util.rs:277:23:
dataflow creation cannot fail: SinceViolation(User(46))
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/panicking.rs:72:14
   2: <core::result::Result<(), mz_compute_client::controller::error::DataflowCreationError> as mz_adapter::util::ResultExt<()>>::unwrap_or_terminate
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05207a1d8149a36ff-1/materialize/tests/src/adapter/src/util.rs:277:23
   3: <mz_adapter::coord::Coordinator>::ship_dataflow::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05207a1d8149a36ff-1/materialize/tests/src/adapter/src/coord.rs:2661:9
   4: <futures_util::future::maybe_done::MaybeDone<<mz_adapter::coord::Coordinator>::ship_dataflow::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/maybe_done.rs:95:38
   5: <futures_util::future::join::Join<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()> + core::marker::Send>>, <mz_adapter::coord::Coordinator>::ship_dataflow::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/join.rs:55:33
   6: <mz_adapter::coord::Coordinator>::subscribe_finish::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05207a1d8149a36ff-1/materialize/tests/src/adapter/src/coord/sequencer/inner/subscribe.rs:322:83
   7: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::subscribe_finish::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
   8: <mz_adapter::coord::Coordinator>::subscribe_finish::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05207a1d8149a36ff-1/materialize/tests/src/adapter/src/coord/sequencer/inner/subscribe.rs:273:5
   9: <mz_adapter::coord::SubscribeStage as mz_adapter::coord::Staged>::stage::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05207a1d8149a36ff-1/materialize/tests/src/adapter/src/coord/sequencer/inner/subscribe.rs:50:81
  10: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<mz_adapter::coord::StageResult<alloc::boxed::Box<mz_adapter::coord::SubscribeStage>>, mz_adapter::error::AdapterError>>>> as core::future::future::Future>::poll
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
  11: <tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<mz_adapter::coord::StageResult<alloc::boxed::Box<mz_adapter::coord::SubscribeStage>>, mz_adapter::error::AdapterError>>>>> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  12: <mz_adapter::coord::Coordinator>::sequence_staged::<mz_adapter::coord::SubscribeStage>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05207a1d8149a36ff-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:147:14
  13: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05207a1d8149a36ff-1/materialize/tests/src/adapter/src/coord/message_handler.rs:184:60
  14: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_message::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  15: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
  16: <mz_adapter::coord::Coordinator>::serve::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05207a1d8149a36ff-1/materialize/tests/src/adapter/src/coord.rs:2538:48
  17: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/core/src/future/future.rs:125:9
  18: <tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  19: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  20: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  21: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  22: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  23: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  24: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:310:13
  25: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::handle::Handle>::block_on<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>::{closure#0}, ()>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  26: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:309:9
  27: mz_adapter::coord::serve::{closure#0}::{closure#3}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05207a1d8149a36ff-1/materialize/tests/src/adapter/src/coord.rs:2991:21
```

https://buildkite.com/materialize/nightlies/builds/6530#_

From the backtrace we see that this happens during SUBSCRIBE sequencing. It seems like adapter doesn't collect appropriate read holds and then when it wants to install the subscribe dataflow the sources are not readable anymore.

ci-regexp: dataflow creation cannot fail: SinceViolation

**Comment by teskje** [comment]
This is how you can reproduce this locally:

* Apply this diff:

```diff
diff --git a/src/adapter/src/coord/sequencer/inner/subscribe.rs b/src/adapter/src/coord/sequencer/inner/subscribe.rs
index cd3d56eed0..46511af1c0 100644
--- a/src/adapter/src/coord/sequencer/inner/subscribe.rs
+++ b/src/adapter/src/coord/sequencer/inner/subscribe.rs
@@ -253,6 +253,7 @@ impl Coordinator {
         Ok(StageResult::Handle(mz_ore::task::spawn_blocking(
             || "optimize subscribe (lir)",
             move || {
+                std::thread::sleep(std::time::Duration::from_secs(10));
                 span.in_scope(|| {
                     // MIR ⇒ LIR lowering and LIR ⇒ LIR optimization (global)
                     let global_lir_plan =
diff --git a/src/compute-client/src/controller.rs b/src/compute-client/src/controller.rs
index 7c33e5c64c..21a5be9f8a 100644
--- a/src/compute-client/src/controller.rs
+++ b/src/compute-client/src/controller.rs
@@ -182,7 +182,7 @@ impl<T: Timestamp> ComputeController<T> {
         let (response_tx, response_rx) = crossbeam_channel::unbounded();
         let (introspection_tx, introspection_rx) = crossbeam_channel::unbounded();

-        let mut maintenance_ticker = time::interval(Duration::from_secs(1));
+        let mut maintenance_ticker = time::interval(Duration::from_secs(30));
         maintenance_ticker.set_missed_tick_behavior(MissedTickBehavior::Skip);

         Self {
```

* Run these commands in a psql session:

```sql
create table t (a int);
create index idx on t (a);
subscribe t;
```

* While the subscribe is hanging in the sleep, drop the index in another psql session:

```sql
drop index idx;
```

This may not work every time because the sequencing needs to be right:
1. sequencer sleep starts
2. index is dropped
3. sequencer sleep ends and dataflow is created _before_ compute controller maintenance runs

**Comment by def-** [comment]
@mjibson This is still happening in main: https://buildkite.com/materialize/nightlies/builds/6616#018de6b1-5cea-41f4-84d1-1f574b207d72
```
thread 'coordinator' panicked at src/adapter/src/util.rs:277:23:
dataflow creation cannot fail: SinceViolation(User(183))
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at ./rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: <core::result::Result<(), mz_compute_client::controller::error::DataflowCreationError> as mz_adapter::util::ResultExt<()>>::unwrap_or_terminate
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0614c5059b4d274a6-1/materialize/tests/src/adapter/src/util.rs:277:23
   3: <mz_adapter::coord::Coordinator>::ship_dataflow::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0614c5059b4d274a6-1/materialize/tests/src/adapter/src/coord.rs:2659:9
   4: <futures_util::future::maybe_done::MaybeDone<<mz_adapter::coord::Coordinator>::ship_dataflow::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/maybe_done.rs:95:38
   5: <futures_util::future::join::Join<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()> + core::marker::Send>>, <mz_adapter::coord::Coordinator>::ship_dataflow::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/join.rs:55:33
time="2024-02-26T19:06:59Z" level="warning" msg="Source terminated" name="minio" bytes=0 err=read tcp 172.16.16.2:9000->172.16.16.8:42210: use of closed network connection 
cluster-u2-replica-u2: 2024-02-26T18:47:25.302364Z  INFO mz_storage::sink::kafka: kafka-u91-sink: committing transaction for {1708973246001}
   6: <mz_adapter::coord::Coordinator>::subscribe_finish::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0614c5059b4d274a6-1/materialize/tests/src/adapter/src/coord/sequencer/inner/subscribe.rs:342:83
   7: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::subscribe_finish::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
   8: <mz_adapter::coord::Coordinator>::subscribe_finish::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0614c5059b4d274a6-1/materialize/tests/src/adapter/src/coord/sequencer/inner/subscribe.rs:282:5
   9: <mz_adapter::coord::SubscribeStage as mz_adapter::coord::Staged>::stage::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0614c5059b4d274a6-1/materialize/tests/src/adapter/src/coord/sequencer/inner/subscribe.rs:49:81
  10: <tracing::instrument::Instrumented<<mz_adapter::coord::SubscribeStage as mz_adapter::coord::Staged>::stage::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  11: <mz_adapter::coord::Coordinator>::sequence_staged::<mz_adapter::coord::SubscribeStage>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0614c5059b4d274a6-1/materialize/tests/src/adapter/src/coord/sequencer/inner.rs:147:14
  12: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0614c5059b4d274a6-1/materialize/tests/src/adapter/src/coord/message_handler.rs:184:60
  13: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_message::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
cluster-u3-replica-u3: 2024-02-26T18:47:25.325693Z  INFO mz_storage::sink::kafka: kafka-u152-sink: committing transaction for {1708973245227}
  14: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/future/future.rs:124:9
  15: <mz_adapter::coord::Coordinator>::serve::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0614c5059b4d274a6-1/materialize/tests/src/adapter/src/coord.rs:2539:48
  16: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/future/future.rs:124:9
  17: <tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  18: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  19: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  20: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  21: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  22: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  23: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:310:13
  24: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::handle::Handle>::block_on<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>::{closure#0}, ()>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  25: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:309:9
  26: mz_adapter::coord::serve::{closure#0}::{closure#3}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0614c5059b4d274a6-1/materialize/tests/src/adapter/src/coord.rs:2989:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
CC @nrainer-materialize

**Comment by def-** [comment]
@mjibson This is occurring often in CI, so we'd appreciate if this can get fixed (versus us disabling many tests where it occurs and thus reducing code coverage).

**Comment by mjibson** [comment]
Ah! Ok, I'll bump up priority on this. Thanks for letting me know.

**Comment by ggevay** [comment]
Happened again on here on a [PR](https://github.com/MaterializeInc/materialize/pull/24155): https://buildkite.com/materialize/nightlies/builds/6753#018e0a9a-57c3-439f-8a71-381ca8729f55
