### ISSUE TITLE
thread 'coordinator' panicked at src/persist-txn/src/txn_cache.rs:590:9: assertion `left == right` failed left: Err("register ts 1708369579667 not less_equal forget ts 1708368679940")  right: Ok(())

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#25384]
### What version of Materialize are you using?

90c7b97fe2 (Pull Request #25167)

### What is the issue?

```
thread 'coordinator' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-07463c2495b761316-1/materialize/tests/src/persist-txn/src/txn_cache.rs:590:9:
assertion `left == right` failed
  left: Err("register ts 1708369579667 not less_equal forget ts 1708368679940")
 right: Ok(())
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/4cb3beec86178baff601529389306a4949b077ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at ./rustc/4cb3beec86178baff601529389306a4949b077ce/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed::<core::result::Result<(), alloc::string::String>, core::result::Result<(), alloc::string::String>>
             at ./rustc/4cb3beec86178baff601529389306a4949b077ce/library/core/src/panicking.rs:278:5
   4: <mz_persist_txn::txn_cache::TxnsCacheState<mz_repr::timestamp::Timestamp>>::compact_data_times
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-07463c2495b761316-1/materialize/tests/src/persist-txn/src/txn_cache.rs:590:9
   5: <mz_persist_txn::txn_cache::TxnsCacheState<mz_repr::timestamp::Timestamp>>::push_append
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-07463c2495b761316-1/materialize/tests/src/persist-txn/src/txn_cache.rs:487:13
   6: <mz_persist_txn::txn_cache::TxnsCacheState<mz_repr::timestamp::Timestamp>>::push_entries
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-07463c2495b761316-1/materialize/tests/src/persist-txn/src/txn_cache.rs:400:21
   7: <mz_persist_txn::txn_cache::TxnsCache<mz_repr::timestamp::Timestamp, mz_storage_types::controller::TxnsCodecRow>>::update::<<mz_persist_txn::txn_cache::TxnsCache<mz_repr::timestamp::Timestamp, mz_storage_types::controller::TxnsCodecRow>>::update_gt::{closure#0}::{closure#0}::{closure#0}>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-07463c2495b761316-1/materialize/tests/src/persist-txn/src/txn_cache.rs:777:25
   8: <mz_persist_txn::txn_cache::TxnsCache<mz_repr::timestamp::Timestamp, mz_storage_types::controller::TxnsCodecRow>>::update_gt::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-07463c2495b761316-1/materialize/tests/src/persist-txn/src/txn_cache.rs:754:14
   9: <mz_persist_txn::txn_cache::TxnsCache<mz_repr::timestamp::Timestamp, mz_storage_types::controller::TxnsCodecRow>>::update_gt::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-07463c2495b761316-1/materialize/tests/src/persist-txn/src/txn_cache.rs:751:5
  10: <mz_persist_txn::txn_cache::TxnsCache<mz_repr::timestamp::Timestamp, mz_storage_types::controller::TxnsCodecRow>>::init::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-07463c2495b761316-1/materialize/tests/src/persist-txn/src/txn_cache.rs:700:33
  11: <mz_persist_txn::txns::TxnsHandle<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64, mz_storage_controller::PersistEpoch, mz_storage_types::controller::TxnsCodecRow>>::open::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-07463c2495b761316-1/materialize/tests/src/persist-txn/src/txns.rs:169:79
  12: <mz_storage_controller::Controller<mz_repr::timestamp::Timestamp>>::new::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-07463c2495b761316-1/materialize/tests/src/storage-controller/src/lib.rs:2219:10
  13: <mz_controller::Controller>::new::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-07463c2495b761316-1/materialize/tests/src/controller/src/lib.rs:442:10
  14: <tracing::instrument::Instrumented<<mz_controller::Controller>::new::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  15: <mz_controller::Controller>::new::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-07463c2495b761316-1/materialize/tests/src/controller/src/lib.rs:422:5
  16: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = mz_controller::Controller> + core::marker::Send>> as core::future::future::Future>::poll
             at ./rustc/4cb3beec86178baff601529389306a4949b077ce/library/core/src/future/future.rs:125:9
  17: <tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = mz_controller::Controller> + core::marker::Send>>> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  18: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = mz_controller::Controller> + core::marker::Send>>>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  19: tokio::runtime::coop::with_budget::<core::task::poll::Poll<mz_controller::Controller>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = mz_controller::Controller> + core::marker::Send>>>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  20: tokio::runtime::coop::budget::<core::task::poll::Poll<mz_controller::Controller>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = mz_controller::Controller> + core::marker::Send>>>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  21: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = mz_controller::Controller> + core::marker::Send>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  22: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = mz_controller::Controller> + core::marker::Send>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  23: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = mz_controller::Controller> + core::marker::Send>>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:310:13
  24: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::handle::Handle>::block_on<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = mz_controller::Controller> + core::marker::Send>>>::{closure#0}, mz_controller::Controller>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  25: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = mz_controller::Controller> + core::marker::Send>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:309:9
  26: mz_adapter::coord::serve::{closure#0}::{closure#3}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-07463c2495b761316-1/materialize/tests/src/adapter/src/coord.rs:2925:34
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Seen in https://buildkite.com/materialize/nightlies/builds/6537#018dc280-8ba3-49fe-8a82-5a91fc0ca53e with "careful mode" (debug assertions), so timing is probably different, exposing this flake.

ci-regexp: not less_equal forget ts

**Comment by danhhz** [comment]
Looks like this is an existing issue in persist-txn that was made more likely by https://github.com/MaterializeInc/materialize/pull/25173. Looking into it this week
