### ISSUE TITLE
thread 'timely:work-0' panicked at src/persist-txn/src/lib.rs:425: txns shard should not be closed

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#25387]
### What version of Materialize are you using?

b543e73cb0db

### What is the issue?

```
testdrive-materialized-1     | thread 'timely:work-0' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-053202237e756a2ad-1/materialize/tests/src/persist-txn/src/lib.rs:425environmentd: 2024-02-20T01:34:42.528837Z  WARN mz_storage_controller: error during background finalization: FinalizationError { since: Antichain { elements: [1708392871072] }, upper: Antichain { elements: [] } }
testdrive-materialized-1     | :18:
testdrive-materialized-1     | txns shard should not be closed
testdrive-materialized-1     | stack backtrace:
```
Seen in https://buildkite.com/materialize/tests/builds/76199#018dc406-9c9e-4b43-a139-471b11ae2382 on main, so probably a flake

ci-regexp: txns shard should not be closed

**Comment by danhhz** [comment]
At first glance, I thought this was another instance of the "much wait for forget to finish before writing to the shard directly (via finalize)" bug that parker fixed in #25173, but the thread name `timely:work-0` makes me think this is happening in clusterd, which would be new and interesting. The stacktrace on this one seems oddly truncated, so hopefully we can catch another one.
