### ISSUE TITLE
Persist Catalog Migration fails: AssertionError: skipping versions should fail

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#25499]
### What version of Materialize are you using?

bec12da2b9e7

### What is the issue?

```
2024-02-22 22:48:11 UTC	==> mzcompose: test case test-version-skips failed: <class 'AssertionError'>: skipping versions should fail
2024-02-22 22:48:11 UTC	Traceback (most recent call last):
2024-02-22 22:48:11 UTC	  File "/var/lib/buildkite-agent/builds/buildkite-aarch64-small-d306b64-i-0c8d21fc2a9ad673f-1/materialize/tests/misc/python/materialize/mzcompose/composition.py", line 559, in test_case
2024-02-22 22:48:11 UTC	    yield
2024-02-22 22:48:11 UTC	  File "/var/lib/buildkite-agent/builds/buildkite-aarch64-small-d306b64-i-0c8d21fc2a9ad673f-1/materialize/tests/test/persist-catalog-migration/mzcompose.py", line 32, in workflow_default
2024-02-22 22:48:11 UTC	    c.workflow(name)
2024-02-22 22:48:11 UTC	  File "/var/lib/buildkite-agent/builds/buildkite-aarch64-small-d306b64-i-0c8d21fc2a9ad673f-1/materialize/tests/misc/python/materialize/mzcompose/composition.py", line 452, in workflow
2024-02-22 22:48:11 UTC	    func(self)
2024-02-22 22:48:11 UTC	  File "/var/lib/buildkite-agent/builds/buildkite-aarch64-small-d306b64-i-0c8d21fc2a9ad673f-1/materialize/tests/test/persist-catalog-migration/mzcompose.py", line 443, in workflow_test_version_skips
2024-02-22 22:48:11 UTC	    assert False, "skipping versions should fail"
2024-02-22 22:48:11 UTC	AssertionError: skipping versions should fail
```
I'll disable the test for now to make tests pipeline green again.

Build: https://buildkite.com/materialize/tests/builds/76521#018dd2d4-7a5b-42ce-9c56-ce598d578097

**Comment by jkosh44** [comment]
Is this not fixed by https://github.com/MaterializeInc/materialize/pull/25578/files?
