### ISSUE TITLE
soft panic: panicked at src/storage-client/src/statistics.rs:532:67: attempt to multiply with overflow

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#25633]
### What version of Materialize are you using?

main

### What is the issue?

```
thread 'tokio:work-37' panicked at src/storage-client/src/statistics.rs:532:67:
attempt to multiply with overflow
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at ./rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at ./rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/core/src/panicking.rs:144:5
   3: <mz_storage_client::statistics::SourceStatisticsUpdate as mz_storage_client::statistics::PackableStats>::pack::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-02cdae36432baabe9-1/materialize/tests/src/storage-client/src/statistics.rs:532:67
   4: core::option::Option<T>::map
             at ./rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/core/src/option.rs:1072:29
   5: <mz_storage_client::statistics::SourceStatisticsUpdate as mz_storage_client::statistics::PackableStats>::pack
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-02cdae36432baabe9-1/materialize/tests/src/storage-client/src/statistics.rs:532:14
   6: mz_storage_controller::statistics::spawn_statistics_scraper::{{closure}}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-02cdae36432baabe9-1/materialize/tests/src/storage-controller/src/statistics.rs:99:33
   7: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:334:17
   8: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/loom/std/unsafe_cell.rs:16:9
   9: tokio::runtime::task::core::Core<T,S>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:323:13
  10: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:485:19
  11: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/core/src/panic/unwind_safe.rs:272:9
  12: std::panicking::try::do_call
             at ./rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panicking.rs:552:40
  13: __rust_try.llvm.825852031030961103
  14: std::panicking::try
             at ./rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panicking.rs:516:19
  15: std::panic::catch_unwind
             at ./rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panic.rs:142:14
  16: tokio::runtime::task::harness::poll_future
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:473:18
  17: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:208:27
  18: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:153:15
  19: tokio::runtime::task::raw::RawTask::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/raw.rs:200:18
  20: tokio::runtime::task::LocalNotified<S>::run
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/mod.rs:400:9
  21: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:576:18
  22: tokio::runtime::coop::with_budget
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  23: tokio::runtime::coop::budget
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  24: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:575:9
  25: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:526:24
  26: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:491:21
  27: tokio::runtime::context::scoped::Scoped<T>::set
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/scoped.rs:40:9
  28: tokio::runtime::context::set_scheduler::{{closure}}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context.rs:176:26
  29: std::thread::local::LocalKey<T>::try_with
             at ./rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/thread/local.rs:270:16
  30: std::thread::local::LocalKey<T>::with
             at ./rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/thread/local.rs:246:9
  31: tokio::runtime::context::set_scheduler
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context.rs:176:17
  32: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:486:9
  33: tokio::runtime::context::runtime::enter_runtime
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  34: tokio::runtime::scheduler::multi_thread::worker::run
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:478:5
  35: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:447:45
  36: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/task.rs:42:21
  37: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:334:17
  38: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/loom/std/unsafe_cell.rs:16:9
  39: tokio::runtime::task::core::Core<T,S>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:323:13
  40: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:485:19
  41: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/core/src/panic/unwind_safe.rs:272:9
  42: std::panicking::try::do_call
             at ./rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panicking.rs:552:40
  43: __rust_try.llvm.11982430526253458164
  44: std::panicking::try
             at ./rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panicking.rs:516:19
  45: std::panic::catch_unwind
             at ./rustc/e51e98dde6a60637b6a71b8105245b629ac3fe77/library/std/src/panic.rs:142:14
  46: tokio::runtime::task::harness::poll_future
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:473:18
  47: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:208:27
  48: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:153:15
  49: tokio::runtime::task::raw::RawTask::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/raw.rs:200:18
  50: tokio::runtime::task::UnownedTask<S>::run
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/mod.rs:437:9
  51: tokio::runtime::blocking::pool::Task::run
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:159:9
  52: tokio::runtime::blocking::pool::Inner::run
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:513:17
  53: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:471:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Seen in https://buildkite.com/materialize/nightlies/builds/6662#018df3dc-cb9a-46b6-a62d-163f25aacf11 with debug assertions turned on. I'm afraid this might lead to wrong statistics in release builds. This comes from https://github.com/MaterializeInc/materialize/pull/25218

ci-regexp: panicked at src/storage-client/src/statistics.rs.*attempt to multiply with overflow

**Comment by guswynn** [comment]
This would require that an i64 value * 100 overflows, which means its like 2^60? We do check that the milliseconds of rehydration in storage does not overflow an i64 (https://doc.rust-lang.org/std/time/struct.Instant.html#method.elapsed), which is like 584 million years, so I'm tempted to consider this issue an asan issue?

That said I can add an assert that the rehydration time as microseconds fits inside a i64 in clusterd because it really really should!

Btw the worst case this soft assert would do in production would be report an inaccurate rehydration latency, for one restart of a source; this will be overwritten on the next restart!

**Comment by guswynn** [comment]
oh actually I found the bug
