### ISSUE TITLE
storage/sources: source is expected to be running/created, but is paused

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#25821]
### What version of Materialize are you using?

b6ca24dbb165

### What is the issue?

Seen in https://buildkite.com/materialize/tests/builds/77762#018e1482-d184-48c5-b638-8e49fb78c7dd
```
2024-03-06 16:46:41 UTC	==> mzcompose: test case test-refresh-mv-restart failed: builtins.ValueError: Source src is expected to be running/created, but is paused, error: None, details: {'hints': ['There is currently no replica running this source']}
2024-03-06 16:46:41 UTC	Traceback (most recent call last):
2024-03-06 16:46:41 UTC	  File "/var/lib/buildkite-agent/builds/buildkite-aarch64-b9f4a11-i-079086b6104290b92-1/materialize/tests/misc/python/materialize/mzcompose/composition.py", line 560, in test_case
2024-03-06 16:46:41 UTC	    yield
2024-03-06 16:46:41 UTC	  File "/var/lib/buildkite-agent/builds/buildkite-aarch64-b9f4a11-i-079086b6104290b92-1/materialize/tests/test/cluster/mzcompose.py", line 78, in workflow_default
2024-03-06 16:46:41 UTC	    c.workflow(name)
2024-03-06 16:46:41 UTC	  File "/var/lib/buildkite-agent/builds/buildkite-aarch64-b9f4a11-i-079086b6104290b92-1/materialize/tests/misc/python/materialize/mzcompose/composition.py", line 447, in workflow
2024-03-06 16:46:41 UTC	    func(self, parser)
2024-03-06 16:46:41 UTC	  File "/var/lib/buildkite-agent/builds/buildkite-aarch64-b9f4a11-i-079086b6104290b92-1/materialize/tests/test/cluster/mzcompose.py", line 3230, in workflow_test_refresh_mv_restart
2024-03-06 16:46:41 UTC	    c.down(destroy_volumes=True)
2024-03-06 16:46:41 UTC	  File "/var/lib/buildkite-agent/builds/buildkite-aarch64-b9f4a11-i-079086b6104290b92-1/materialize/tests/misc/python/materialize/mzcompose/composition.py", line 1045, in down
2024-03-06 16:46:41 UTC	    self.sanity_restart_mz()
2024-03-06 16:46:41 UTC	  File "/var/lib/buildkite-agent/builds/buildkite-aarch64-b9f4a11-i-079086b6104290b92-1/materialize/tests/misc/python/materialize/mzcompose/composition.py", line 1011, in sanity_restart_mz
2024-03-06 16:46:41 UTC	    raise ValueError(error)
2024-03-06 16:46:41 UTC	ValueError: Source src is expected to be running/created, but is paused, error: None, details: {'hints': ['There is currently no replica running this source']}
```
@ggevay This seems to be a flake. Testdrive recently became faster, so maybe that caused it to happen?
What happens is that after the `test-refresh-mv-restart` test case finished we restart Materialize and check if the source is running, but in this test it fails.

ci-regexp: Source src is expected to be running/created, but is paused

**Comment by ggevay** [comment]
Happened again: https://buildkite.com/materialize/tests/builds/77854#018e1957-c300-4322-ac1e-c8d231707d1f

**Comment by benesch** [comment]
Added to storage mega tracker as a p2.

**Comment by ggevay** [comment]
These tests have been disabled for a long time. PR to re-enable them to see whether the bug has been fixed in the meantime: https://github.com/MaterializeInc/materialize/pull/27515

**Comment by def-** [comment]
I assume this hasn't happened again
