### ISSUE TITLE
builtins.AssertionError: expected a single dataflow in replica history in test-github-15531

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#25917]
### What version of Materialize are you using?

86020b4ad008 (Pull Request #25913)

### What is the issue?

Seen in https://buildkite.com/materialize/tests/builds/78036#018e2cd2-b8d7-4297-a168-1aeb76ea5b69, but unrelated to my PR:
```
2024-03-11 09:33:15 UTC	==> mzcompose: test case test-github-15531 failed: builtins.AssertionError: expected a single dataflow in replica history
2024-03-11 09:33:15 UTC	Traceback (most recent call last):
2024-03-11 09:33:15 UTC	  File "/var/lib/buildkite-agent/builds/buildkite-aarch64-b9f4a11-i-09dd878d6cd2a8159-1/materialize/tests/misc/python/materialize/mzcompose/composition.py", line 560, in test_case
2024-03-11 09:33:15 UTC	    yield
2024-03-11 09:33:15 UTC	  File "/var/lib/buildkite-agent/builds/buildkite-aarch64-b9f4a11-i-09dd878d6cd2a8159-1/materialize/tests/test/cluster/mzcompose.py", line 81, in workflow_default
2024-03-11 09:33:15 UTC	    c.workflow(name)
2024-03-11 09:33:15 UTC	  File "/var/lib/buildkite-agent/builds/buildkite-aarch64-b9f4a11-i-09dd878d6cd2a8159-1/materialize/tests/misc/python/materialize/mzcompose/composition.py", line 453, in workflow
2024-03-11 09:33:15 UTC	    func(self)
2024-03-11 09:33:15 UTC	  File "/var/lib/buildkite-agent/builds/buildkite-aarch64-b9f4a11-i-09dd878d6cd2a8159-1/materialize/tests/test/cluster/mzcompose.py", line 353, in workflow_test_github_15531
2024-03-11 09:33:15 UTC	    assert replica_dataflow_count == 1, "expected a single dataflow in replica history"
2024-03-11 09:33:15 UTC	           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-11 09:33:15 UTC	AssertionError: expected a single dataflow in replica history
```
@teskje Since you last touched the test (in https://github.com/MaterializeInc/materialize/pull/25876), could you take a look and check if it's expected that there are multiple dataflows?

ci-regexp: AssertionError: expected a single dataflow in replica history

**Comment by teskje** [comment]
Yes, the new `SELECT * FROM t2` creates a new dataflow that's not accounted for by the current check.
