### ISSUE TITLE
HWAsan: tag-mismatch in mz_persist::postgres::tests::postgres_consensus_blocking

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#26145]
### What version of Materialize are you using?

528da00916e9 (Pull Request #26047)

### What is the issue?

Seen in https://buildkite.com/materialize/tests/builds/78703#018e5821-5cc0-490b-bdf0-f26b4b89561e
```
==406==ERROR: HWAddressSanitizer: tag-mismatch on address 0xffffae4fb1a0 at pc 0xaaaad7039f14
READ of size 8 at 0xffffae4fb1a0 tags: ed/00 (ptr/mem) in thread T1
    #0 0xaaaad7039f14 in <tracing::span::Entered as core::ops::drop::Drop>::drop /cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/span.rs:1568:9
    #1 0xaaaad7039f14 in core::ptr::drop_in_place::<tracing::span::Entered> /usr/local/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:507:1
    #2 0xaaaad436115c in <tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = core::result::Result<(), mz_persist::location::ExternalError>>>> as core::future::future::Future>::poll /cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:273:5
    #3 0xaaaad434f330 in <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = core::result::Result<(), mz_persist::location::ExternalError>>>>>::{closure#0} /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
    #4 0xaaaad434679c in tokio::runtime::coop::with_budget::<core::task::poll::Poll<core::result::Result<(), mz_persist::location::ExternalError>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = core::result::Result<(), mz_persist::location::ExternalError>>>>>::{closure#0}> /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
    #5 0xaaaad434679c in tokio::runtime::coop::budget::<core::task::poll::Poll<core::result::Result<(), mz_persist::location::ExternalError>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = core::result::Result<(), mz_persist::location::ExternalError>>>>>::{closure#0}> /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
    #6 0xaaaad434679c in <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = core::result::Result<(), mz_persist::location::ExternalError>>>>> /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
    #7 0xaaaad42ab528 in <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = core::result::Result<(), mz_persist::location::ExternalError>>>>> /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
    #8 0xaaaad44642a4 in <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = core::result::Result<(), mz_persist::location::ExternalError>>>>>::{closure#0} /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
    #9 0xaaaad434cf04 in tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::scheduler::multi_thread::MultiThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = core::result::Result<(), mz_persist::location::ExternalError>>>>>::{closure#0}, core::result::Result<(), mz_persist::location::ExternalError>> /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
    #10 0xaaaad4458510 in <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output = core::result::Result<(), mz_persist::location::ExternalError>>>>> /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
    #11 0xaaaad42aac64 in <tokio::runtime::runtime::Runtime>::block_on::<core::pin::Pin<&mut dyn core::future::future::Future<Output = core::result::Result<(), mz_persist::location::ExternalError>>>> /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/runtime.rs:349:45
    #12 0xaaaad449af90 in mz_persist::postgres::tests::postgres_consensus_blocking /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0353a830a370bd1e7-1/materialize/tests/src/persist/src/postgres.rs:447:5
    #13 0xaaaad449ad00 in mz_persist::postgres::tests::postgres_consensus_blocking::{closure#0} /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0353a830a370bd1e7-1/materialize/tests/src/persist/src/postgres.rs:449:47
    #14 0xaaaad41115ec in <mz_persist::postgres::tests::postgres_consensus_blocking::{closure#0} as core::ops::function::FnOnce<()>>::call_once /usr/local/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
    #15 0xaaaad483548c in <fn() -> core::result::Result<(), alloc::string::String> as core::ops::function::FnOnce<()>>::call_once /usr/local/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
    #16 0xaaaad48a280c in test::__rust_begin_short_backtrace::<core::result::Result<(), alloc::string::String>, fn() -> core::result::Result<(), alloc::string::String>> /usr/local/lib/rustlib/src/rust/library/test/src/lib.rs:627:18
    #17 0xaaaad48d65bc in <test::types::RunnableTest>::run /usr/local/lib/rustlib/src/rust/library/test/src/types.rs:146:40
    #18 0xaaaad48a35e0 in test::run_test_in_process::{closure#0} /usr/local/lib/rustlib/src/rust/library/test/src/lib.rs:650:60
    #19 0xaaaad486be80 in <core::panic::unwind_safe::AssertUnwindSafe<test::run_test_in_process::{closure#0}> as core::ops::function::FnOnce<()>>::call_once /usr/local/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
    #20 0xaaaad484e2a0 in std::panicking::try::do_call::<core::panic::unwind_safe::AssertUnwindSafe<test::run_test_in_process::{closure#0}>, core::result::Result<(), alloc::string::String>> /usr/local/lib/rustlib/src/rust/library/std/src/panicking.rs:552:40
    #21 0xaaaad485fc98 in __rust_try test.5f05b447a33bf2d-cgu.06
    #22 0xaaaad484ca4c in std::panicking::try::<core::result::Result<(), alloc::string::String>, core::panic::unwind_safe::AssertUnwindSafe<test::run_test_in_process::{closure#0}>> /usr/local/lib/rustlib/src/rust/library/std/src/panicking.rs:516:19
    #23 0xaaaad48b49a4 in std::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<test::run_test_in_process::{closure#0}>, core::result::Result<(), alloc::string::String>> /usr/local/lib/rustlib/src/rust/library/std/src/panic.rs:142:14
    #24 0xaaaad48a2ef4 in test::run_test_in_process /usr/local/lib/rustlib/src/rust/library/test/src/lib.rs:650:27
    #25 0xaaaad48a2224 in test::run_test::{closure#0} /usr/local/lib/rustlib/src/rust/library/test/src/lib.rs:573:43
    #26 0xaaaad48a2664 in test::run_test::{closure#1} /usr/local/lib/rustlib/src/rust/library/test/src/lib.rs:601:41
    #27 0xaaaad484dee0 in std::sys_common::backtrace::__rust_begin_short_backtrace::<test::run_test::{closure#1}, ()> /usr/local/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:155:18
    #28 0xaaaad48912d0 in <std::thread::Builder>::spawn_unchecked_::<test::run_test::{closure#1}, ()>::{closure#1}::{closure#0} /usr/local/lib/rustlib/src/rust/library/std/src/thread/mod.rs:529:17
    #29 0xaaaad486bde0 in <core::panic::unwind_safe::AssertUnwindSafe<<std::thread::Builder>::spawn_unchecked_<test::run_test::{closure#1}, ()>::{closure#1}::{closure#0}> as core::ops::function::FnOnce<()>>::call_once /usr/local/lib/rustlib/src/rust/library/core/src/panic/unwind_safe.rs:272:9
    #30 0xaaaad484e1cc in std::panicking::try::do_call::<core::panic::unwind_safe::AssertUnwindSafe<<std::thread::Builder>::spawn_unchecked_<test::run_test::{closure#1}, ()>::{closure#1}::{closure#0}>, ()> /usr/local/lib/rustlib/src/rust/library/std/src/panicking.rs:552:40
    #31 0xaaaad485fc98 in __rust_try test.5f05b447a33bf2d-cgu.06
    #32 0xaaaad484cbc8 in std::panicking::try::<(), core::panic::unwind_safe::AssertUnwindSafe<<std::thread::Builder>::spawn_unchecked_<test::run_test::{closure#1}, ()>::{closure#1}::{closure#0}>> /usr/local/lib/rustlib/src/rust/library/std/src/panicking.rs:516:19
    #33 0xaaaad48b4990 in std::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<<std::thread::Builder>::spawn_unchecked_<test::run_test::{closure#1}, ()>::{closure#1}::{closure#0}>, ()> /usr/local/lib/rustlib/src/rust/library/std/src/panic.rs:142:14
    #34 0xaaaad4891094 in <std::thread::Builder>::spawn_unchecked_::<test::run_test::{closure#1}, ()>::{closure#1} /usr/local/lib/rustlib/src/rust/library/std/src/thread/mod.rs:528:30
    #35 0xaaaad482eb30 in <<std::thread::Builder>::spawn_unchecked_<test::run_test::{closure#1}, ()>::{closure#1} as core::ops::function::FnOnce<()>>::call_once::{shim:vtable#0} /usr/local/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
    #36 0xaaaad7402adc in <alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output = ()>> as core::ops::function::FnOnce<()>>::call_once /usr/local/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2015:9
    #37 0xaaaad7402c18 in <alloc::boxed::Box<alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output = ()>>> as core::ops::function::FnOnce<()>>::call_once /usr/local/lib/rustlib/src/rust/library/alloc/src/boxed.rs:2015:9
    #38 0xaaaad740d280 in <std::sys::unix::thread::Thread>::new::thread_start /usr/local/lib/rustlib/src/rust/library/std/src/sys/unix/thread.rs:108:17
    #39 0xaaaad3ee397c in HwasanThreadStartFunc(void*) /checkout/src/llvm-project/compiler-rt/lib/hwasan/hwasan_interceptors.cpp:260:33
    #40 0xffffb09ee810 in start_thread nptl/pthread_create.c:444:8
    #41 0xffffb0a57d58 in thread_start misc/../sysdeps/unix/sysv/linux/aarch64/clone.S:79
[...]
```
Full log: https://gist.github.com/def-/e7981816b5be9f25f179255bb01f67b8
@bkirwi Since you wrote the test, can you take a look?
Edit: This is actually occurring in 10 different tests, not just this one.

**Comment by benesch** [comment]
Added as a bug to the persist mega tracker: https://github.com/MaterializeInc/materialize/issues/24829.

**Comment by danhhz** [comment]
@def- Is there still anything for us to look into here? This stacktrace looks be in some tokio and tracing stuff, and the persist usage of it seems pretty normal. Plus, this sort of thing isn't possible in safe rust and at the time this happened, persist didn't have any unsafe code

**Comment by def-** [comment]
The HWAsan build is currently failing with esoteric linking errors: https://buildkite.com/materialize/test/builds/86399#0190db6c-4c68-40f8-bb39-0b1f5c7edd57
```
  = note: aarch64-unknown-linux-gnu-ld.lld: error: /mnt/build/release/deps/libopenssl_sys-4425c528a5ac1c22.rlib(libcrypto-lib-armv8-mont.o):(function bn_mul_mont: .text+0x10): relocation R_AARCH64_ADR_PREL_PG_HI21 out of range: -7133701809748119552 is not in [-4294967296, 4294967295]; references OPENSSL_armv8_rsa_neonized
```
So I can't investigate further. I also don't have enough experience with HWAsan to know how high its quality of output is.
