### ISSUE TITLE
cargo-test failure in test_storage_usage_collection_interval: assertion `left == right` failed   left: 2929  right: 0

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#26551]
### What version of Materialize are you using?

a7112be6d468

### What is the issue?

```
thread 'test_storage_usage_collection_interval' panicked at src/environmentd/tests/server.rs:1228:5:
assertion `left == right` failed
  left: 2929
 right: 0
stack backtrace:
   0: rust_begin_unwind
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed::<u64, u64>
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/panicking.rs:297:5
   4: test_impl
             at ./tests/server.rs:1228:5
   5: server::test_storage_usage_collection_interval
             at ./tests/server.rs:1110:1
   6: server::test_storage_usage_collection_interval::{closure#0}
             at ./tests/server.rs:1110:16
   7: <server::test_storage_usage_collection_interval::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Seen in https://buildkite.com/materialize/test/builds/80300

@jkosh44 Are you the right assignee for this?

ci-regexp: thread 'test_storage_usage_collection_interval' panicked

**Comment by jkosh44** [comment]
> @jkosh44 Are you the right assignee for this?

Yeah, I'll take a look and if there's someone who knows more I can re-assign.
