### ISSUE TITLE
thread 'persist:0001' panicked at src/persist-client/src/internal/gc.rs:425:13: rollups = GcRollups { ... }, state seqno = v97

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#26695]
### What version of Materialize are you using?

54c3d77265cb

### What is the issue?

```
thread 'persist:0001' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-03780b024043f7f44-1/materialize/test/src/persist-client/src/internal/gc.rs:425:13:
rollups = GcRollups { rollups_lte_seqno_since: [(SeqNo(1), PartialRollupKey("v1/r2dbe85f6-53bf-4d73-8167-07bec4bd1fe7")), (SeqNo(49), PartialRollupKey("v49/r57f49fb8-4694-45f7-9015-81b5cd6c563d")), (SeqNo(51), PartialRollupKey("v51/rd00e9d6f-ea0e-4b17-909d-8b2555f65b9e")), (SeqNo(52), PartialRollupKey("v52/rded2934f-813d-476c-8d3c-bbdd2a040d51")), (SeqNo(53), PartialRollupKey("v53/rab81d1f4-f092-4808-bf72-794c069569e5")), (SeqNo(54), PartialRollupKey("v54/rfe51c325-d59f-47ed-835c-ec322c68de40")), (SeqNo(55), PartialRollupKey("v55/r0c9fe35e-8d8e-4e15-b4be-5fe263b6d947")), (SeqNo(56), PartialRollupKey("v56/r1210789f-17c1-467d-8bc0-db54b35ca8d4")), (SeqNo(57), PartialRollupKey("v57/r6def4a78-044d-4eac-88a3-7c92c70e7c06")), (SeqNo(58), PartialRollupKey("v58/raa4eb550-1136-43a1-8b5b-b4934c5d2ae1")), (SeqNo(59), PartialRollupKey("v59/r34f54bd0-023c-4199-90e5-26ff9989ed3b")), (SeqNo(60), PartialRollupKey("v60/rbc09e4b6-cff1-41f7-bb1b-1d3929d7289f")), (SeqNo(61), PartialRollupKey("v61/rb0cab0dd-dc22-4200-90cd-6098b97b3112")), (SeqNo(62), PartialRollupKey("v62/r588ecd69-8966-4153-9d5c-e1c1bcae6ea0")), (SeqNo(63), PartialRollupKey("v63/r06e93beb-2473-4db2-a24e-7244e5adfb61")), (SeqNo(64), PartialRollupKey("v64/rdbd6aca4-0302-45c2-9ff7-d402d369f55f")), (SeqNo(65), PartialRollupKey("v65/ra4304fd5-7d04-47f7-bc46-ffb514211bcf")), (SeqNo(66), PartialRollupKey("v66/r0ba43b3f-1d47-4c2a-925a-ce010f225047")), (SeqNo(67), PartialRollupKey("v67/rb33c8a50-989e-4dea-950e-51eede9aefa4")), (SeqNo(68), PartialRollupKey("v68/r360c2485-336d-414b-8246-7eae84b580c0")), (SeqNo(69), PartialRollupKey("v69/r90d5602f-7cae-4ddc-8257-ed0a63b421b9")), (SeqNo(70), PartialRollupKey("v70/rbe1782c0-5744-417e-b01c-1b9036a6d9ba")), (SeqNo(71), PartialRollupKey("v71/rc3d9d2f6-25db-401f-9cc7-dd10e6d81055")), (SeqNo(72), PartialRollupKey("v72/r56e7ae31-96af-4208-9aea-44b84175e0b1")), (SeqNo(73), PartialRollupKey("v73/r5fcbdccb-0f55-4e09-b1d8-8524c2566109")), (SeqNo(74), PartialRollupKey("v74/r87707a00-de73-4633-b580-eaac6ae73657")), (SeqNo(75), PartialRollupKey("v75/rec17a920-eab5-4f7b-a462-ebd863d86a50")), (SeqNo(76), PartialRollupKey("v76/ra46f572f-539d-4159-822f-e2b942ca3cbb")), (SeqNo(77), PartialRollupKey("v77/rc13e046d-1f2e-4d30-8bd8-a6e8fab02dd4")), (SeqNo(78), PartialRollupKey("v78/r285d43b6-63f7-42a3-aa37-25f10895fcee")), (SeqNo(79), PartialRollupKey("v79/r66ba8e7f-2f82-4509-a831-ff1b9f592511")), (SeqNo(80), PartialRollupKey("v80/r0130a55a-8b94-4456-89f6-7cbc8fa6f8cd")), (SeqNo(81), PartialRollupKey("v81/r4aac1f65-c6c6-4b89-a166-a27319622d38")), (SeqNo(82), PartialRollupKey("v82/rfda737a5-e072-4a3b-8f88-e471a81d0d57")), (SeqNo(83), PartialRollupKey("v83/r34c34949-fc57-4fe4-9a85-1bc407653e6b")), (SeqNo(84), PartialRollupKey("v84/rf7efbaa7-1fd6-4577-bc64-3bbeef8c19df")), (SeqNo(85), PartialRollupKey("v85/r36d965f2-f5e0-4507-8fc4-31938e7471fd")), (SeqNo(86), PartialRollupKey("v86/r383785a6-e6ce-4eae-a780-481418a056dc")), (SeqNo(87), PartialRollupKey("v87/r6c0f68d3-9c55-4433-a2b6-926554e97409")), (SeqNo(88), PartialRollupKey("v88/r5d0cb051-bf59-495b-a3e4-b41fadd09f6a")), (SeqNo(89), PartialRollupKey("v89/r94ba8163-c50c-4ea5-9bda-e48b49d06914")), (SeqNo(90), PartialRollupKey("v90/r732965b7-6b0e-4bd0-a06f-f767bbc7f303")), (SeqNo(91), PartialRollupKey("v91/r0461bc51-df37-4562-b98e-fabfdf6dc6c9")), (SeqNo(92), PartialRollupKey("v92/r4f605163-8b77-4946-b389-90853e456f69")), (SeqNo(93), PartialRollupKey("v93/r8a523e23-208d-41e1-91a8-eedd2599ff1e")), (SeqNo(94), PartialRollupKey("v94/r0776199d-0b30-41d8-94fc-92a62576f0c7")), (SeqNo(95), PartialRollupKey("v95/r07452a1f-600d-41df-9b02-0bbd0e41c414")), (SeqNo(96), PartialRollupKey("v96/r999dd594-63cd-440b-a1ec-890637b6c068")), (SeqNo(98), PartialRollupKey("v98/rd7c65ed0-7dcf-4a42-b36f-fee08b9952be"))], rollup_seqnos: HashSet({SeqNo(55), SeqNo(68), SeqNo(54), SeqNo(86), SeqNo(91), SeqNo(89), SeqNo(98), SeqNo(80), SeqNo(52), SeqNo(60), SeqNo(63), SeqNo(85), SeqNo(64), SeqNo(84), SeqNo(88), SeqNo(70), SeqNo(66), SeqNo(71), SeqNo(49), SeqNo(67), SeqNo(65), SeqNo(74), SeqNo(90), SeqNo(62), SeqNo(95), SeqNo(53), SeqNo(72), SeqNo(58), SeqNo(77), SeqNo(78), SeqNo(75), SeqNo(61), SeqNo(56), SeqNo(81), SeqNo(73), SeqNo(76), SeqNo(92), SeqNo(94), SeqNo(87), SeqNo(1), SeqNo(57), SeqNo(83), SeqNo(69), SeqNo(82), SeqNo(79), SeqNo(93), SeqNo(96), SeqNo(59), SeqNo(51)}) }, state seqno = v97
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at ./rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/panicking.rs:72:14
   2: <mz_persist_client::internal::gc::GarbageCollector<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::incrementally_delete_and_truncate::<<mz_persist_client::internal::gc::GarbageCollector<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::gc_and_truncate::{closure#0}::{closure#0}>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-03780b024043f7f44-1/materialize/test/src/persist-client/src/internal/gc.rs:425:13
   3: <mz_persist_client::internal::gc::GarbageCollector<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::gc_and_truncate::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-03780b024043f7f44-1/materialize/test/src/persist-client/src/internal/gc.rs:302:10
   4: <tracing::instrument::Instrumented<<mz_persist_client::internal::gc::GarbageCollector<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::gc_and_truncate::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
   5: <mz_persist_client::internal::gc::GarbageCollector<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::new::{closure#1}::{closure#1}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-03780b024043f7f44-1/materialize/test/src/persist-client/src/internal/gc.rs:165:34
   6: <tracing::instrument::Instrumented<<mz_persist_client::internal::gc::GarbageCollector<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::new::{closure#1}::{closure#1}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
   7: <tokio::runtime::task::core::Core<tracing::instrument::Instrumented<<mz_persist_client::internal::gc::GarbageCollector<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::new::{closure#1}::{closure#1}>, alloc::sync::Arc<tokio::runtime::scheduler::current_thread::Handle>>>::poll::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:334:17
   8: <tokio::loom::std::unsafe_cell::UnsafeCell<tokio::runtime::task::core::Stage<tracing::instrument::Instrumented<<mz_persist_client::internal::gc::GarbageCollector<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::new::{closure#1}::{closure#1}>>>>::with_mut::<core::task::poll::Poll<(mz_persist_client::internal::maintenance::RoutineMaintenance, mz_persist_client::internal::gc::GcResults)>, <tokio::runtime::task::core::Core<tracing::instrument::Instrumented<<mz_persist_client::internal::gc::GarbageCollector<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::new::{closure#1}::{closure#1}>, alloc::sync::Arc<tokio::runtime::scheduler::current_thread::Handle>>>::poll::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/loom/std/unsafe_cell.rs:16:9
   9: <tokio::runtime::task::core::Core<tracing::instrument::Instrumented<<mz_persist_client::internal::gc::GarbageCollector<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::new::{closure#1}::{closure#1}>, alloc::sync::Arc<tokio::runtime::scheduler::current_thread::Handle>>>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:323:30
  10: tokio::runtime::task::harness::poll_future::<tracing::instrument::Instrumented<<mz_persist_client::internal::gc::GarbageCollector<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::new::{closure#1}::{closure#1}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:485:19
  11: <core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tracing::instrument::Instrumented<<mz_persist_client::internal::gc::GarbageCollector<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::new::{closure#1}::{closure#1}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>::{closure#0}> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/panic/unwind_safe.rs:272:9
  12: std::panicking::try::do_call::<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tracing::instrument::Instrumented<<mz_persist_client::internal::gc::GarbageCollector<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::new::{closure#1}::{closure#1}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>::{closure#0}>, core::task::poll::Poll<(mz_persist_client::internal::maintenance::RoutineMaintenance, mz_persist_client::internal::gc::GcResults)>>
             at ./rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:554:40
  13: std::panicking::try::<core::task::poll::Poll<(mz_persist_client::internal::maintenance::RoutineMaintenance, mz_persist_client::internal::gc::GcResults)>, core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tracing::instrument::Instrumented<<mz_persist_client::internal::gc::GarbageCollector<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::new::{closure#1}::{closure#1}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>::{closure#0}>>
             at ./rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:518:19
  14: std::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tracing::instrument::Instrumented<<mz_persist_client::internal::gc::GarbageCollector<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::new::{closure#1}::{closure#1}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>::{closure#0}>, core::task::poll::Poll<(mz_persist_client::internal::maintenance::RoutineMaintenance, mz_persist_client::internal::gc::GcResults)>>
             at ./rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panic.rs:142:14
  15: tokio::runtime::task::harness::poll_future::<tracing::instrument::Instrumented<<mz_persist_client::internal::gc::GarbageCollector<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::new::{closure#1}::{closure#1}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:473:18
  16: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<<mz_persist_client::internal::gc::GarbageCollector<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::new::{closure#1}::{closure#1}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll_inner
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:208:27
  17: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<<mz_persist_client::internal::gc::GarbageCollector<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::new::{closure#1}::{closure#1}>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:153:15
  18: <tokio::runtime::task::raw::RawTask>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/raw.rs:200:18
  19: <tokio::runtime::task::LocalNotified<alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>>::run
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/mod.rs:400:9
  20: <tokio::runtime::scheduler::multi_thread::worker::Context>::run_task::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:639:22
  21: tokio::runtime::coop::with_budget::<core::result::Result<alloc::boxed::Box<tokio::runtime::scheduler::multi_thread::worker::Core>, ()>, <tokio::runtime::scheduler::multi_thread::worker::Context>::run_task::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  22: tokio::runtime::coop::budget::<core::result::Result<alloc::boxed::Box<tokio::runtime::scheduler::multi_thread::worker::Core>, ()>, <tokio::runtime::scheduler::multi_thread::worker::Context>::run_task::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  23: <tokio::runtime::scheduler::multi_thread::worker::Context>::run_task
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:575:9
  24: <tokio::runtime::scheduler::multi_thread::worker::Context>::run
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:526:24
  25: tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:491:21
  26: <tokio::runtime::context::scoped::Scoped<tokio::runtime::scheduler::Context>>::set::<tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}::{closure#0}, ()>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/scoped.rs:40:9
  27: tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:486:9
  28: tokio::runtime::context::runtime::enter_runtime::<tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}, ()>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  29: tokio::runtime::scheduler::multi_thread::worker::run
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:478:5
  30: <tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/scheduler/multi_thread/worker.rs:447:45
  31: <tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/task.rs:42:21
  32: <tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  33: <tokio::runtime::task::core::Core<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:334:17
  34: <tokio::loom::std::unsafe_cell::UnsafeCell<tokio::runtime::task::core::Stage<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>>>>>::with_mut::<core::task::poll::Poll<()>, <tokio::runtime::task::core::Core<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/loom/std/unsafe_cell.rs:16:9
  35: <tokio::runtime::task::core::Core<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/core.rs:323:30
  36: tokio::runtime::task::harness::poll_future::<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:485:19
  37: <core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/core/src/panic/unwind_safe.rs:272:9
  38: std::panicking::try::do_call::<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}>, core::task::poll::Poll<()>>
             at ./rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:554:40
  39: std::panicking::try::<core::task::poll::Poll<()>, core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}>>
             at ./rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panicking.rs:518:19
  40: std::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>::{closure#0}>, core::task::poll::Poll<()>>
             at ./rustc/aedd173a2c086e558c2b66d3743b344f977621a7/library/std/src/panic.rs:142:14
  41: tokio::runtime::task::harness::poll_future::<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:473:18
  42: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll_inner
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:208:27
  43: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/harness.rs:153:15
  44: <tokio::runtime::task::raw::RawTask>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/raw.rs:200:18
  45: <tokio::runtime::task::UnownedTask<tokio::runtime::blocking::schedule::BlockingSchedule>>::run
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/task/mod.rs:437:9
  46: <tokio::runtime::blocking::pool::Task>::run
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:159:9
  47: <tokio::runtime::blocking::pool::Inner>::run
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:513:17
  48: <tokio::runtime::blocking::pool::Spawner>::spawn_thread::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/blocking/pool.rs:471:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Seen in https://buildkite.com/materialize/test/builds/80833#018eecbf-7de1-41a0-9304-37be2ea21817
This GC code seems to have been touched in https://github.com/MaterializeInc/materialize/pull/19384
CC @danhhz @bkirwi 
ci-regexp: "rollups = GcRollups"

**Comment by ggevay** [comment]
Happened again in https://buildkite.com/materialize/test/builds/82459#018fa10e-a10d-4723-bc00-da1369cc66e7
