### ISSUE TITLE
thread 'coordinator' panicked at src/adapter/src/coord.rs:2324:13: error bootstrapping dataflow `as_of`

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#26976]
### What version of Materialize are you using?

1243449ea4118f9deb512c8f0a9f7117a6bd40ef

### What is the issue?

Checks upgrade across four versions failed in [nightly build #7697](https://buildkite.com/materialize/nightly/builds/7697#018f5565-d7e6-4d28-84e4-e83085ba29ec).

```
platform-checks-materialized-1     | thread 'coordinator' panicked at src/adapter/src/coord.rs:2324:13: error bootstrapping dataflow `as_of`: `min_as_of` [1715125812000] greater than `max_as_of` [1715125755001] (import_ids=[u692], export_ids=[u711], storage_constraints=StorageConstraints { dependencies: {User(692)}, dependants: {User(711)} })
```

**Comment by nrainer-materialize** [comment]
Bisecting https://github.com/MaterializeInc/materialize/compare/fc061c1f1b42bca346cef2e925a221e2576beff1...4f91d6612f7f4843d5fbc572dfbf91c477de8a9d

**Comment by nrainer-materialize** [comment]
This occurs since the merge of https://github.com/MaterializeInc/materialize/pull/26826.
