### ISSUE TITLE
cargo test "test_linearizability" is flaky due to panic

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#27220]
### Buildkite link

https://buildkite.com/materialize/test/builds/82417#018f9f1b-a8de-4e67-8eb7-49d3b07edf77

### Relevant log output

```source
thread 'test_linearizability' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0371aefe0bc2dda44-1/materialize/test/src/environmentd/src/test_util.rs:1100:10:
called `Result::unwrap()` on an `Err` value: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: None, code: SqlState(E42601), message: "Expected one of TABLE or VIEW or MATERIALIZED or SOURCE or SINK or INDEX or TYPE or ROLE or USER or CLUSTER or SECRET or CONNECTION or DATABASE or SCHEMA or FUNCTION, found PUBLICATION", detail: None, hint: None, position: Some(Original(6)), where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: None, line: None, routine: None }) }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1654:5
   3: unwrap<u64, tokio_postgres::error::Error>
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1077:23
   4: {async_fn#0}
             at ./src/test_util.rs:1097:13
   5: {async_fn#0}
             at ./tests/sql.rs:1839:6
   6: {async_fn#0}
             at ./tests/sql.rs:1806:57
   7: {async_block#0}
             at ./tests/sql.rs:1803:1
   8: poll<&mut dyn core::future::future::Future<Output=()>>
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/future/future.rs:123:9
   9: poll<core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  10: {closure#0}<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  11: with_budget<core::task::poll::Poll<()>, tokio::runtime::park::{impl#4}::block_on::{closure_env#0}<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  12: budget<core::task::poll::Poll<()>, tokio::runtime::park::{impl#4}::block_on::{closure_env#0}<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  13: block_on<tracing::instrument::Instrumented<core::pin::Pin<&mut dyn core::future::future::Future<Output=()>>>>
             at /cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
```

**Comment by jkosh44** [comment]
Hmm, that's interesting. The failed SQL statement can be found here: https://github.com/MaterializeInc/materialize/blob/24956db0ca456652fa22a048798b8380d28b9fab/src/environmentd/src/test_util.rs#L1097-L1100, it's `DROP PUBLICATION IF EXISTS _`. This statement is meant to be run on a PostgreSQL database, however it the error indicates that it was run on a Materialize database, which has no notion of publications.

The `pg_client` used is initialized here: https://github.com/MaterializeInc/materialize/blob/24956db0ca456652fa22a048798b8380d28b9fab/src/environmentd/src/test_util.rs#L1062-L1068. The URL is taken directly from the `POSTGRES_URL` environment variable.

So this implies that somewhere in CI we are setting the `POSTGRES_URL` environment variable to a Materialize database instead of a PostgreSQL database.

**Comment by jkosh44** [comment]
@nrainer-materialize How do default ports get configured in `mzcompose`? My guess is that somehow this had the wrong port:
https://github.com/MaterializeInc/materialize/blob/24956db0ca456652fa22a048798b8380d28b9fab/ci/test/cargo-test/mzcompose.py#L61-L65

**Comment by nrainer-materialize** [comment]
Ok, I am not aware of any previous occurrence...

> @nrainer-materialize How do default ports get configured in mzcompose?

In mzcompose, each service specifies its private ports, for example, `Environmentd` in https://github.com/MaterializeInc/materialize/blob/0ee46b3fb5d0128ce23ff445654d1285b2d7d143/misc/python/materialize/mzcompose/services/materialized.py#L213

and `default_port` uses `docker compose port` to resolve the corresponding public port in 
https://github.com/MaterializeInc/materialize/blob/0ee46b3fb5d0128ce23ff445654d1285b2d7d143/misc/python/materialize/mzcompose/composition.py#L415-L432

Does this help you?
