### ISSUE TITLE
panic in cargo test "test_mz_sessions"

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#27221]
### Buildkite link

https://buildkite.com/materialize/test/builds/82417#018f9f1b-a8de-4e67-8eb7-49d3b07edf77

### Relevant log output

```source
thread 'test_mz_sessions' panicked at src/environmentd/tests/sql.rs:2796:14:
called `Result::unwrap()` on an `Err` value: Error { kind: RowCount, cause: None }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1654:5
   3: unwrap<tokio_postgres::row::Row, tokio_postgres::error::Error>
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1077:23
   4: test_impl
             at ./tests/sql.rs:2794:9
   5: sql::test_mz_sessions
             at ./tests/sql.rs:2722:1
   6: sql::test_mz_sessions::{closure#0}
             at ./tests/sql.rs:2722:16
   7: <sql::test_mz_sessions::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Additional thoughts

https://github.com/MaterializeInc/materialize/issues/27220 occurred in the same build.

**Comment by nrainer-materialize** [comment]
Closing as duplicate of https://github.com/MaterializeInc/materialize/issues/22998.
