### ISSUE TITLE
thread 'timely:work-0' panicked at src/storage/src/render/sinks.rs:75:49: already borrowed: BorrowMutError

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#27445]
### What version of Materialize are you using?

d280543eee9d

### What is the issue?

Seen in https://buildkite.com/materialize/test/builds/83142#018fe3d0-4522-4729-ab68-aa56ed29eab9, seems related to sinks
```
thread 'timely:work-0' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05b30dfdebc26b7a0-1/materialize/test/src/storage/src/render/sinks.rs:75:49:
already borrowed: BorrowMutError
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at ./rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   2: core::cell::panic_already_borrowed
             at ./rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/cell.rs:770:5
   3: <core::cell::RefCell<dyn mz_storage::internal_control::InternalCommandSender>>::borrow_mut
             at ./rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/cell.rs:1061:25
   4: mz_storage::render::sinks::render_sink::<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#1}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05b30dfdebc26b7a0-1/materialize/test/src/storage/src/render/sinks.rs:75:38
   5: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/future/future.rs:123:9
   6: <mz_persist_client::operators::shard_source::shard_source_descs::ErrorHandler<mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#1}>>::report_and_stop::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05b30dfdebc26b7a0-1/materialize/test/src/persist-client/src/operators/shard_source.rs:282:33
   7: mz_persist_client::operators::shard_source::shard_source_descs::<mz_storage_types::sources::SourceData, (), i64, mz_storage_operators::persist_source::persist_source_core<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>, mz_storage_operators::persist_source::persist_source<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>, mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#0}, mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#1}>::{closure#0}::{closure#0}, mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#0}, mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#1}>::{closure#4}, timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>, mz_storage_operators::persist_source::persist_source_core<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>, mz_storage_operators::persist_source::persist_source<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>, mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#0}, mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#1}>::{closure#0}::{closure#0}, mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#0}, mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#1}>::{closure#3}::{closure#0}, mz_storage_operators::persist_source::persist_source<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>, mz_repr::timestamp::Timestamp>, mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#0}, mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#1}>::{closure#0}::{closure#0}, mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#0}, mz_storage::render::sinks::render_sink<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>, ()>>::{closure#1}>::{closure#1}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05b30dfdebc26b7a0-1/materialize/test/src/persist-client/src/operators/shard_source.rs:375:26
```
Full backtrace: https://gist.github.com/def-/3b464bd0734696d4724afe38b23b9748
Previously there was a similar panic: https://github.com/MaterializeInc/materialize/issues/5983

There recently was a timely/differential update, could that be related? CC @antiguru

ci-regexp: already borrowed: BorrowMutError

**Comment by aljoscha** [comment]
ha! @petrosagg, I'd thought that since we basically use timely as the async scheduler this would work, but we must be borrowing across an await point? I also have a feeling that maybe https://github.com/MaterializeInc/materialize/pull/27380 made this possible because it made the error handler itself async?

Feels like if we want to keep this we have to put the internal command sender behind a real lock/mutex. But I don't know if you want to go there.

**Comment by def-** [comment]
Just occurred again: https://buildkite.com/materialize/test/builds/83188#018fe71e-001e-428e-a8b5-8681b561b54f
This seems like it should be fixed before the next release to me. Should we mark it as release blocker?

**Comment by petrosagg** [comment]
Right, so if you observe the backtrace you'll see that the stack contains the `build_export_dataflow` function. In other words this panic happened exactly at the point where the dataflow was rendered. When timely renders a dataflow it schedules all the operators once **synchronously**. I think this is done to learn about all the summaries (see the `set_external_summary` calls).

`build_export_dataflow` is called from `handle_internal_storage_command` which gets passed a mutable reference to the command sender, and when the sink tries to borrow the same thing mutably, it panics.

**Comment by petrosagg** [comment]
This also means that a synchronous `Mutex` would lead to a deadlock here
