### ISSUE TITLE
thread 'coordinator' panicked at src/compute-client/src/controller/instance.rs:1591:17: replica input frontier regression: Antichain { elements: [1717665416000] } -> Antichain { elements: [1717665408001] }, collection=u33, replica=u1

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#27484]
### What version of Materialize are you using?

59148a9e7e (Pull Request #27482)

### What is the issue?

Seen in https://buildkite.com/materialize/release-qualification/builds/507#018fec15-e055-4f13-8ef3-76d900850325 ([Longer Zippy Kafka Parallel Insert](https://buildkite.com/materialize/release-qualification/builds/507#018fec15-e055-4f13-8ef3-76d900850325))
```
thread 'coordinator' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0fcc9e4e4d504a051-1/materialize/test/src/compute-client/src/controller/instance.rs:1591:17:
replica input frontier regression: Antichain { elements: [1717665416000] } -> Antichain { elements: [1717665408001] }, collection=u33, replica=u1
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at ./rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   2: <mz_compute_client::controller::instance::ActiveInstance<mz_repr::timestamp::Timestamp>>::update_replica_input_frontiers
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0fcc9e4e4d504a051-1/materialize/test/src/compute-client/src/controller/instance.rs:1591:17
   3: <mz_compute_client::controller::instance::ActiveInstance<mz_repr::timestamp::Timestamp>>::handle_frontiers_response
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0fcc9e4e4d504a051-1/materialize/test/src/compute-client/src/controller/instance.rs:1887:13
   4: <mz_compute_client::controller::instance::ActiveInstance<mz_repr::timestamp::Timestamp>>::handle_response
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0fcc9e4e4d504a051-1/materialize/test/src/compute-client/src/controller/instance.rs:1813:17
   5: <mz_compute_client::controller::ActiveComputeController<mz_repr::timestamp::Timestamp>>::process::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0fcc9e4e4d504a051-1/materialize/test/src/compute-client/src/controller.rs:732:24
   6: <mz_compute_client::controller::ActiveComputeController<mz_repr::timestamp::Timestamp>>::process::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0fcc9e4e4d504a051-1/materialize/test/src/compute-client/src/controller.rs:707:5
   7: <mz_controller::Controller>::process_compute_response::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0fcc9e4e4d504a051-1/materialize/test/src/controller/src/lib.rs:466:56
   8: <mz_controller::Controller>::process::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0fcc9e4e4d504a051-1/materialize/test/src/controller/src/lib.rs:500:67
   9: <mz_controller::Controller>::process::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0fcc9e4e4d504a051-1/materialize/test/src/controller/src/lib.rs:492:5
  10: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0fcc9e4e4d504a051-1/materialize/test/src/adapter/src/coord/message_handler.rs:85:26
  11: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_message::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  12: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/future/future.rs:123:9
  13: <mz_adapter::coord::Coordinator>::serve::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0fcc9e4e4d504a051-1/materialize/test/src/adapter/src/coord.rs:2598:48
  14: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/future/future.rs:123:9
  15: <tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  16: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:63
  17: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:107:5
  18: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/coop.rs:73:5
  19: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/park.rs:282:31
  20: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/blocking.rs:66:9
  21: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:310:22
  22: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::handle::Handle>::block_on<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>::{closure#0}, ()>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/context/runtime.rs:65:16
  23: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.0/src/runtime/handle.rs:309:9
  24: mz_adapter::coord::serve::{closure#0}::{closure#2}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0fcc9e4e4d504a051-1/materialize/test/src/adapter/src/coord.rs:3180:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
The assertion comes from https://github.com/MaterializeInc/materialize/pull/26665

Release Qualification pipeline has been pretty red recently, and in this PR I'm trying to clear it up, so this might not be a recent regression.

ci-regexp: replica input frontier regression

**Comment by teskje** [comment]
I haven't be able to reproduce this yet, but the logs from that failed CI run are interesting. The `u1` replica is killed and restarted over and over again and at one point there is a regression in the `as_of` with which the dataflow of `u33` is installed. This is unexpected given that envd has not restarted in between.

```
zippy-materialized-1      | cluster-u1-replica-u1: 2024-06-06T09:15:04.964171Z  INFO mz_compute::compute_state: creating dataflow name=materialize.public.view_0 import_ids=[u9] export_ids=[u33] as_of=[1717665292000] until=[]
zippy-materialized-1      | cluster-u1-replica-u1: 2024-06-06T09:15:58.234738Z  INFO mz_compute::compute_state: creating dataflow name=materialize.public.view_0 import_ids=[u9] export_ids=[u33] as_of=[1717665343000] until=[]
zippy-materialized-1      | cluster-u1-replica-u1: 2024-06-06T09:16:23.808309Z  INFO mz_compute::compute_state: creating dataflow name=materialize.public.view_0 import_ids=[u9] export_ids=[u33] as_of=[1717665343000] until=[]
zippy-materialized-1      | cluster-u1-replica-u1: 2024-06-06T09:17:06.838401Z  INFO mz_compute::compute_state: creating dataflow name=materialize.public.view_0 import_ids=[u9] export_ids=[u33] as_of=[1717665416000] until=[]
zippy-materialized-1      | cluster-u1-replica-u1: 2024-06-06T09:17:30.187629Z  INFO mz_compute::compute_state: creating dataflow name=materialize.public.view_0 import_ids=[u9] export_ids=[u33] as_of=[1717665343429] until=[]
```

**Comment by teskje** [comment]
I still wasn't able to reproduce this, but based on reviewing the code I think I know what happened:

* There is [a bug](https://github.com/MaterializeInc/materialize/pull/27529) in `ComputeCommandHistory::reduce` where pending fast-path peeks on materialized views can make the as-of of the MV dataflow regress.
* The `KafkaParallelInsert` zippy scenario creates both MVs and `SELECT ... LIMIT ...` queries on them, so it is able to trigger this bug.
* If there is a persist peek targeting an MV in the `ComputeCommandHistory` at the same time a replica restarts, and that persist peek is at a time that's before the MV dataflow's read frontier, the bug will make the controller instruct the replica to install the MV dataflow with an as-of that's before the read frontier known to the controller.
* When a replica is (re-)started, the controller initializes its per-collection input frontiers with the read frontiers of the respective collections.
* Because the dataflow was installed with an as-of before the read frontier, and therefore the initial input frontier, tracked by the controller, the replica may emit frontier updates to frontiers that are also before that initial input frontier. The controller registers that as an input frontier regression and panics.

Based on this I expect that #27529 is a full fix for the panic reported here.
