### ISSUE TITLE
thread 'main' panicked at src/adapter/src/catalog/open.rs:551:17: unexpected update kinds: [StateUpdate ...

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#28055]
### What version of Materialize are you using?

54720abd7f

### What is the issue?

Seen in https://buildkite.com/materialize/nightly/builds/8373#01907ecf-54e1-4898-89ed-12dcc10ed299
```
thread 'main' panicked at src/adapter/src/catalog/open.rs:551:17:
unexpected update kinds: [StateUpdate { kind: UnfinalizedShard(UnfinalizedShard { shard: ShardId(08fa7d22-fa62-400d-a985-56009a4ad4d9) }), ts: 7457, diff: Retraction }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 1, shard_id: Some("s000c27d2-14a2-499d-8982-da38b15201ce"), size_bytes: 48349, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 2, shard_id: Some("s016855cf-ef30-4782-a0a4-3fbc37cb1925"), size_bytes: 1226, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 3, shard_id: Some("s0224b624-5201-4f48-ba7f-71fe39ad483f"), size_bytes: 343465, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 4, shard_id: Some("s040fc636-de2a-46f2-ba89-aaaf736c5afd"), size_bytes: 1, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 5, shard_id: Some("s05fe2435-a943-4834-8a7d-961b99993e03"), size_bytes: 472596, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 6, shard_id: Some("s08def38f-68f8-42d4-a279-aaee1f09a151"), size_bytes: 12153, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 7, shard_id: Some("s0abd841b-8a3e-4fe3-8199-3c98f1a7d456"), size_bytes: 24851, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 8, shard_id: Some("s0cc03bac-79f2-4fc5-b610-03b145d39519"), size_bytes: 1226, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 9, shard_id: Some("s0d8b0558-04b1-49af-a4b8-4135ac9171a1"), size_bytes: 3501, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 10, shard_id: Some("s107efdea-2c28-47bb-bd64-7f622d86df8a"), size_bytes: 455, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 11, shard_id: Some("s1337e6d1-95a0-4df0-a344-950a9fee54e3"), size_bytes: 612210, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 12, shard_id: Some("s162b8532-55dc-452d-9525-a4a484c7c470"), size_bytes: 130497, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 13, shard_id: Some("s1a3bb760-c5b6-4d9b-aedf-952ed5430378"), size_bytes: 34483, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 14, shard_id: Some("s1a855f56-920b-4366-b317-3106cb1fcd2d"), size_bytes: 658792, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 15, shard_id: Some("s1ab90b30-c9d0-460a-a253-c5cf6e28e5b4"), size_bytes: 214, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 16, shard_id: Some("s25ee1dab-4497-4026-9541-ae09a3b158aa"), size_bytes: 2181, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 17, shard_id: Some("s2819332b-d0d3-484f-a30f-0c89c17a546a"), size_bytes: 1694, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 18, shard_id: Some("s288c2900-7997-45fb-98c7-bf845f78ae26"), size_bytes: 1226, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 19, shard_id: Some("s2fedd3d4-7e80-46a3-a7f2-6de64b34665b"), size_bytes: 74915, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 20, shard_id: Some("s31c319d6-1088-4684-85e7-da55551936e7"), size_bytes: 194176, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 21, shard_id: Some("s32d6c330-8e5c-4447-b54a-082b482cd642"), size_bytes: 53950, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 22, shard_id: Some("s34e268ce-5e92-4f88-a750-a21df330d59c"), size_bytes: 54614, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 23, shard_id: Some("s354f42d9-e1d3-48e5-93c8-d564af193cf1"), size_bytes: 2216, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 24, shard_id: Some("s3584bf68-a513-4321-9ead-0568c255502e"), size_bytes: 1, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 25, shard_id: Some("s38ec6fab-7977-4a7e-9313-1fa353e07cd6"), size_bytes: 285, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 26, shard_id: Some("s3ca0bafb-7dcf-4c0b-99c7-65b509f58f15"), size_bytes: 282607, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 27, shard_id: Some("s44ec4d38-37b3-436f-be0d-6fbc509d6978"), size_bytes: 504656, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 28, shard_id: Some("s44f87f26-0a22-495b-84d1-b5b1c1f04c62"), size_bytes: 269114, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 29, shard_id: Some("s4d4cad38-55d9-479a-9971-63cd99011b7e"), size_bytes: 603646, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 30, shard_id: Some("s4e5da721-91b2-4239-bde7-e3485394c3c1"), size_bytes: 37430, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 31, shard_id: Some("s570b19c9-a132-444a-93f7-90144907c83c"), size_bytes: 524968, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 32, shard_id: Some("s573a7ad2-60c5-4727-ae5c-625c26c42f9f"), size_bytes: 2252, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 33, shard_id: Some("s5a33241a-9e1c-4279-93df-a1ebea0ff482"), size_bytes: 484693, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 34, shard_id: Some("s5bd8dc79-e76f-42c7-a645-20a8b92679c0"), size_bytes: 677093, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 35, shard_id: Some("s5e14e42e-4623-43c2-b9fc-9e3f078b77f1"), size_bytes: 47324, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 36, shard_id: Some("s5ecaea95-f80b-41de-88db-535a7e6b05e4"), size_bytes: 318, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 37, shard_id: Some("s60c5d6c2-0d9e-4838-a54b-7c13603f6732"), size_bytes: 1, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 38, shard_id: Some("s65ecdc53-31f2-49b2-8e9d-d94493c26487"), size_bytes: 34863, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 39, shard_id: Some("s663e3cf8-ba9b-44e0-a838-8141b7120e90"), size_bytes: 148477, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 40, shard_id: Some("s67a8e7a3-c626-4885-98c2-9ba2bd1c4309"), size_bytes: 502099, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 41, shard_id: Some("s7209a59e-000e-4a3b-9ca4-1a407980f8c4"), size_bytes: 495914, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 42, shard_id: Some("s763d5fd7-2c7a-4b4a-b3a4-8ca51bc6ca81"), size_bytes: 1122161, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 43, shard_id: Some("s78e7ecca-9eb6-41d8-b885-f03a5cbabe07"), size_bytes: 136050, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 44, shard_id: Some("s7bab9fbe-9400-459d-9c78-48dcd5a2e5f6"), size_bytes: 1, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 45, shard_id: Some("s82cc1a45-62a3-450c-bb82-2d64e62f9a34"), size_bytes: 1897097, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 46, shard_id: Some("s8fd893cc-e0a7-4ba4-83f6-30dea09995e1"), size_bytes: 793786, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 47, shard_id: Some("s95feacc3-5010-4ce4-9b95-9032047579d8"), size_bytes: 1, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 48, shard_id: Some("s99a41f31-6a32-45f8-96e8-917995793978"), size_bytes: 1999, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 49, shard_id: Some("s9b13d297-6fc8-413f-8a75-edc9093053e8"), size_bytes: 371554, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 50, shard_id: Some("sa0b34f59-e0cc-4d3f-948b-fc524968da3f"), size_bytes: 29343764, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 51, shard_id: Some("sa24fdd6c-9e97-42e1-94eb-fca0b89cea29"), size_bytes: 326859, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 52, shard_id: Some("sa5611e87-990a-4c62-a2ae-693772639228"), size_bytes: 3546331, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 53, shard_id: Some("sa7651352-7621-42bf-b453-6e9218ceecae"), size_bytes: 2190, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 54, shard_id: Some("saf532e34-6597-428a-ba47-8a9186cb7b8d"), size_bytes: 156800, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 55, shard_id: Some("sb2f39d67-a005-48bc-b338-c400263e8b4e"), size_bytes: 440006, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 56, shard_id: Some("sb6443702-b2c6-455a-aa59-c5246a376d59"), size_bytes: 1, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 57, shard_id: Some("sb651381d-e999-47fc-9da6-bbca9cea07a0"), size_bytes: 621593, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 58, shard_id: Some("sb7f2e951-fa94-4bcb-9e6f-1b21f3ceebfa"), size_bytes: 1, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 59, shard_id: Some("sbcc02e03-b161-405b-a4d7-3e611d512835"), size_bytes: 309411, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 60, shard_id: Some("sbe8a76f2-59c3-487c-abed-a7fee2875d80"), size_bytes: 901037, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 61, shard_id: Some("sc0a75bec-a454-44bd-9dbe-8cfa80cb60f1"), size_bytes: 376138, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 62, shard_id: Some("sc1d0bcff-18b2-4d72-b609-f7182dbed7df"), size_bytes: 135286, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 63, shard_id: Some("sc5507bc6-018d-4502-a744-c68af71b0f87"), size_bytes: 1907874, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 64, shard_id: Some("sc59bfa53-2967-46e1-a60a-243b2afd126d"), size_bytes: 319102, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 65, shard_id: Some("scb5d2026-be4a-4687-8618-013dbd32f211"), size_bytes: 254627, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 66, shard_id: Some("sce3590b5-be4c-4104-8289-fd88dd2163bd"), size_bytes: 495284, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 67, shard_id: Some("sd9fe2c81-e32c-42af-a787-011bf0827e87"), size_bytes: 38785, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 68, shard_id: Some("sdff8e42d-8c5f-4385-a627-8f9d20496b82"), size_bytes: 1347075, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 69, shard_id: Some("se13ab529-f1b7-4e65-a26d-a808d76b0c6d"), size_bytes: 2617174, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 70, shard_id: Some("se30186b7-7781-44f1-8cad-258e7ab9cb59"), size_bytes: 153234, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 71, shard_id: Some("se554e54c-fbd8-40a1-9874-4e2f4940878a"), size_bytes: 289286, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 72, shard_id: Some("sf082b4d9-3c21-425f-9af6-7044963ff929"), size_bytes: 7378934, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 73, shard_id: Some("sf5248faf-d9d9-458c-b134-3c70894357fb"), size_bytes: 464, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 74, shard_id: Some("sf5902add-fc31-4dfe-86ab-2e893a89a5c5"), size_bytes: 1829591, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 75, shard_id: Some("sf646a1c3-a8da-44dd-9bb4-22cd0861be58"), size_bytes: 2402845, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 76, shard_id: Some("sf689535c-5ab1-4065-bc3d-f5e011e8dd38"), size_bytes: 151953, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 77, shard_id: Some("sf76f54a4-4384-404e-80be-f5741a76f3eb"), size_bytes: 1, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 78, shard_id: Some("sfc08c455-168c-4b2f-8785-b41f5b054774"), size_bytes: 451958, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 79, shard_id: Some("sfc792384-7e10-4c13-bd7f-f70ac35f4aa0"), size_bytes: 355934, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }, StateUpdate { kind: StorageUsage(StorageUsage { metric: V1(StorageUsageV1 { id: 80, shard_id: Some("sfff57cbe-6bdb-4ec3-bb55-920f7470346b"), size_bytes: 41325, collection_timestamp: 1720117376466 }) }), ts: 7457, diff: Addition }]
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: <tracing::instrument::Instrumented<<mz_adapter::catalog::Catalog>::open::{closure#0}> as core::future::future::Future>::poll
   3: <mz_testdrive::action::State>::with_catalog_copy::<mz_testdrive::action::consistency::check_catalog_state::{closure#0}::{closure#1}, mz_adapter::catalog::state::CatalogState>::{closure#0}
   4: mz_testdrive::run_line_reader::{closure#0}
   5: mz_testdrive::run_string::{closure#0}
   6: testdrive::main::{closure#0}
   7: <tracing::instrument::Instrumented<testdrive::main::{closure#0}> as core::future::future::Future>::poll
   8: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<testdrive::main::{closure#0}>>
   9: <tokio::runtime::runtime::Runtime>::block_on::<testdrive::main::{closure#0}>
  10: testdrive::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
==> Uploading report for suite 'testdrive' to Buildkite Test Analytics
422 {
  "message": "`data` is required"
}
```
Maybe just a testdrive issue?

The code comes from https://github.com/MaterializeInc/materialize/pull/27872

ci-regexp: unexpected update kinds

**Comment by jkosh44** [comment]
This looks like a real issue, but I have a good idea of what's going on. I'll take a look today.

**Comment by jkosh44** [comment]
> This looks like a real issue, but I have a good idea of what's going on. I'll take a look today.

I take that back, I found the issue and it is a test issue. I'll push a fix shortly.
