### ISSUE TITLE
0dt: thread 'coordinator' panicked at src/adapter/src/util.rs:286:23: cannot fail to fetch snapshot: ReadBeforeSince(System(479))

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#28339]
### What version of Materialize are you using?

9844044e2b (Pull Request #28191)

### What is the issue?

With the freshly merged https://github.com/MaterializeInc/materialize/pull/28324 we are now running into another new set of panics: [Checks 0dt upgrade across four versions](https://buildkite.com/materialize/nightly/builds/8632#0190c4c0-56b0-4a71-9c3a-99ad73b779f4)
```
platform-checks-mz_2-1              | thread 'coordinator' panicked at src/adapter/src/util.rs:286:23: cannot fail to fetch snapshot: ReadBeforeSince(System(479))
platform-checks-mz_2-1              | thread 'timely:work-3' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-021e3b57519a1f97a-1/materialize/test/src/persist-client/src/read.rs:689:9: ReadHandle::snapshot called with as_of Antichain { elements: [1721290682000] } not past the handle's since Antichain { elements: [1721290712000] }, though the read has succeeded. This implies the since is not being held back correctly.
```
ci-regexp: cannot fail to fetch snapshot: ReadBeforeSince

**Comment by def-** [comment]
Not seen again, closing
