### ISSUE TITLE
parallel-workload: 0dt: thread 'coordinator' panicked at src/timestamp-oracle/src/postgres_oracle.rs:567:13: attempting write_ts in read-only mode

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#28338]
### What version of Materialize are you using?

9844044e2b (Pull Request #28191)

### What is the issue?

With the freshly merged https://github.com/MaterializeInc/materialize/pull/28324 we are now running into a new panic: [Parallel Workload (0dt deploy)](https://buildkite.com/materialize/nightly/builds/8632#0190c4c0-56f5-45a4-a928-7a08f4ebfa39)
```
thread 'coordinator' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a13d047ceb28877-1/materialize/test/src/timestamp-oracle/src/postgres_oracle.rs:567:13:
attempting write_ts in read-only mode
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: <mz_timestamp_oracle::postgres_oracle::PostgresTimestampOracle<mz_ore::now::NowFn>>::fallible_write_ts::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a13d047ceb28877-1/materialize/test/src/timestamp-oracle/src/postgres_oracle.rs:567:13
   3: <tracing::instrument::Instrumented<<mz_timestamp_oracle::postgres_oracle::PostgresTimestampOracle<mz_ore::now::NowFn>>::fallible_write_ts::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
   4: <mz_timestamp_oracle::postgres_oracle::PostgresTimestampOracle<mz_ore::now::NowFn>>::fallible_write_ts::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a13d047ceb28877-1/materialize/test/src/timestamp-oracle/src/postgres_oracle.rs:564:5
   5: <mz_timestamp_oracle::metrics::ExternalOpMetrics>::run_op::<mz_timestamp_oracle::WriteTimestamp, <mz_timestamp_oracle::postgres_oracle::PostgresTimestampOracle<mz_ore::now::NowFn>>::fallible_write_ts::{closure#0}, <mz_timestamp_oracle::postgres_oracle::PostgresTimestampOracle<mz_ore::now::NowFn> as mz_timestamp_oracle::TimestampOracle<mz_repr::timestamp::Timestamp>>::write_ts::{closure#0}::{closure#0}::{closure#0}::{closure#0}>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a13d047ceb28877-1/materialize/test/src/timestamp-oracle/src/metrics.rs:209:27
   6: mz_timestamp_oracle::postgres_oracle::retry_fallible::<mz_timestamp_oracle::WriteTimestamp, <mz_timestamp_oracle::metrics::ExternalOpMetrics>::run_op<mz_timestamp_oracle::WriteTimestamp, <mz_timestamp_oracle::postgres_oracle::PostgresTimestampOracle<mz_ore::now::NowFn>>::fallible_write_ts::{closure#0}, <mz_timestamp_oracle::postgres_oracle::PostgresTimestampOracle<mz_ore::now::NowFn> as mz_timestamp_oracle::TimestampOracle<mz_repr::timestamp::Timestamp>>::write_ts::{closure#0}::{closure#0}::{closure#0}::{closure#0}>::{closure#0}, <mz_timestamp_oracle::postgres_oracle::PostgresTimestampOracle<mz_ore::now::NowFn> as mz_timestamp_oracle::TimestampOracle<mz_repr::timestamp::Timestamp>>::write_ts::{closure#0}::{closure#0}::{closure#0}>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a13d047ceb28877-1/materialize/test/src/timestamp-oracle/src/postgres_oracle.rs:765:25
   7: <mz_timestamp_oracle::postgres_oracle::PostgresTimestampOracle<mz_ore::now::NowFn> as mz_timestamp_oracle::TimestampOracle<mz_repr::timestamp::Timestamp>>::write_ts::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a13d047ceb28877-1/materialize/test/src/timestamp-oracle/src/postgres_oracle.rs:705:10
   8: <tracing::instrument::Instrumented<<mz_timestamp_oracle::postgres_oracle::PostgresTimestampOracle<mz_ore::now::NowFn> as mz_timestamp_oracle::TimestampOracle<mz_repr::timestamp::Timestamp>>::write_ts::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
   9: <mz_timestamp_oracle::postgres_oracle::PostgresTimestampOracle<mz_ore::now::NowFn> as mz_timestamp_oracle::TimestampOracle<mz_repr::timestamp::Timestamp>>::write_ts::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a13d047ceb28877-1/materialize/test/src/timestamp-oracle/src/postgres_oracle.rs:695:5
  10: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = mz_timestamp_oracle::WriteTimestamp> + core::marker::Send>> as core::future::future::Future>::poll
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
  11: <mz_timestamp_oracle::batching_oracle::BatchingTimestampOracle<mz_repr::timestamp::Timestamp> as mz_timestamp_oracle::TimestampOracle<mz_repr::timestamp::Timestamp>>::write_ts::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a13d047ceb28877-1/materialize/test/src/timestamp-oracle/src/batching_oracle.rs:105:31
  12: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = mz_timestamp_oracle::WriteTimestamp> + core::marker::Send>> as core::future::future::Future>::poll
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
  13: <mz_adapter::coord::Coordinator>::get_local_write_ts::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a13d047ceb28877-1/materialize/test/src/adapter/src/coord/timeline.rs:139:14
  14: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::get_local_write_ts::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  15: <mz_adapter::coord::Coordinator>::get_local_write_ts::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a13d047ceb28877-1/materialize/test/src/adapter/src/coord/timeline.rs:132:5
  16: <mz_adapter::coord::Coordinator>::storage_usage_update::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a13d047ceb28877-1/materialize/test/src/adapter/src/coord/message_handler.rs:298:75
  17: <mz_adapter::coord::Coordinator>::storage_usage_update::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a13d047ceb28877-1/materialize/test/src/adapter/src/coord/message_handler.rs:292:5
  18: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a13d047ceb28877-1/materialize/test/src/adapter/src/coord/message_handler.rs:129:54
  19: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_message::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  20: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
  21: <mz_adapter::coord::Coordinator>::serve::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a13d047ceb28877-1/materialize/test/src/adapter/src/coord.rs:2956:48
  22: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
  23: <tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  24: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:63
  25: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:107:5
  26: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:73:5
  27: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:31
  28: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/blocking.rs:66:9
  29: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/handle.rs:310:22
  30: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::handle::Handle>::block_on<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>::{closure#0}, ()>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/runtime.rs:65:16
  31: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/handle.rs:309:9
  32: mz_adapter::coord::serve::{closure#0}::{closure#2}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a13d047ceb28877-1/materialize/test/src/adapter/src/coord.rs:3564:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
I want to say I'm very happy we have this many assertions in the code! Much appreciated over figuring out mysteriously wrong results.
ci-regexp: attempting write_ts in read-only mode

**Comment by aljoscha** [comment]
@def- I believe this is fixed with the version that I ended up merging. I specifically fixed the place where we try and call the disallowed write_ts operation. You might want to double check before closing this issue? It was only ever occuring in your in-progress PR, right?

**Comment by def-** [comment]
True, running: https://buildkite.com/materialize/nightly/builds/8745

**Comment by def-** [comment]
Haven't seen the panic in that run, so closing.
