### ISSUE TITLE
thread 'main' panicked at src/adapter/src/catalog/open/builtin_item_migration.rs:431:30: updated bound should match expected

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#28511]
### What version of Materialize are you using?

5dae72a417 (Pull Request #28191)

### What is the issue?

Seen in [Checks 0dt upgrade across three versions](https://buildkite.com/materialize/nightly/builds/8771#0190e633-ec0c-4acb-8dfb-2582c7f08e73):
```
platform-checks-mz_3-1              | thread 'main' panicked at src/adapter/src/catalog/open/builtin_item_migration.rs:431:30:
platform-checks-mz_3-1              | updated bound should match expected
platform-checks-mz_3-1              | stack backtrace:
platform-checks-mz_3-1              |    0: rust_begin_unwind
platform-checks-mz_3-1              |              at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
platform-checks-mz_3-1              |    1: core::panicking::panic_fmt
platform-checks-mz_3-1              |              at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
platform-checks-mz_3-1              |    2: mz_adapter::catalog::open::builtin_item_migration::write_to_migration_shard::{closure#0}
platform-checks-mz_3-1              |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a88afb3b337ab65-1/materialize/test/src/adapter/src/catalog/open/builtin_item_migration.rs:431:30
platform-checks-mz_3-1              |    3: mz_adapter::catalog::open::builtin_item_migration::migrate_builtin_items_0dt::{closure#0}
platform-checks-mz_3-1              |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a88afb3b337ab65-1/materialize/test/src/adapter/src/catalog/open/builtin_item_migration.rs:322:6
platform-checks-mz_3-1              |    4: mz_adapter::catalog::open::builtin_item_migration::migrate_builtin_items::{closure#0}
platform-checks-mz_3-1              |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a88afb3b337ab65-1/materialize/test/src/adapter/src/catalog/open/builtin_item_migration.rs:71:14
platform-checks-mz_3-1              |    5: <mz_adapter::catalog::Catalog>::initialize_state::{closure#0}
platform-checks-mz_3-1              |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a88afb3b337ab65-1/materialize/test/src/adapter/src/catalog/open.rs:435:10
platform-checks-mz_3-1              |    6: <tracing::instrument::Instrumented<<mz_adapter::catalog::Catalog>::initialize_state::{closure#0}> as core::future::future::Future>::poll
platform-checks-mz_3-1              |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
platform-checks-mz_3-1              |    7: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(mz_adapter::catalog::state::CatalogState, alloc::collections::btree::set::BTreeSet<mz_repr::global_id::GlobalId>, alloc::vec::Vec<mz_adapter::catalog::builtin_table_updates::BuiltinTableUpdate>, alloc::string::String), mz_adapter::error::AdapterError>> + core::marker::Send>> as core::future::future::Future>::poll
platform-checks-mz_3-1              |              at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
platform-checks-mz_3-1              |    8: <mz_adapter::catalog::Catalog>::open::{closure#0}
platform-checks-mz_3-1              |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a88afb3b337ab65-1/materialize/test/src/adapter/src/catalog/open.rs:478:22
platform-checks-mz_3-1              |    9: <tracing::instrument::Instrumented<<mz_adapter::catalog::Catalog>::open::{closure#0}> as core::future::future::Future>::poll
platform-checks-mz_3-1              |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
platform-checks-mz_3-1              |   10: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(mz_adapter::catalog::Catalog, alloc::collections::btree::set::BTreeSet<mz_repr::global_id::GlobalId>, alloc::vec::Vec<mz_adapter::catalog::builtin_table_updates::BuiltinTableUpdate>, alloc::string::String), mz_adapter::error::AdapterError>> + core::marker::Send>> as core::future::future::Future>::poll
platform-checks-mz_3-1              |              at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
platform-checks-mz_3-1              |   11: mz_adapter::coord::serve::{closure#0}
platform-checks-mz_3-1              |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a88afb3b337ab65-1/materialize/test/src/adapter/src/coord.rs:3399:10
platform-checks-mz_3-1              |   12: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(mz_adapter::client::Handle, mz_adapter::client::Client), mz_adapter::error::AdapterError>> + core::marker::Send>> as core::future::future::Future>::poll
platform-checks-mz_3-1              |              at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
platform-checks-mz_3-1              |   13: <tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<(mz_adapter::client::Handle, mz_adapter::client::Client), mz_adapter::error::AdapterError>> + core::marker::Send>>> as core::future::future::Future>::poll
platform-checks-mz_3-1              |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
platform-checks-mz_3-1              |   14: <mz_environmentd::Listeners>::serve::{closure#0}::{closure#0}
platform-checks-mz_3-1              |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a88afb3b337ab65-1/materialize/test/src/environmentd/src/lib.rs:500:10
platform-checks-mz_3-1              |   15: <tracing::instrument::Instrumented<<mz_environmentd::Listeners>::serve::{closure#0}::{closure#0}> as core::future::future::Future>::poll
platform-checks-mz_3-1              |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
platform-checks-mz_3-1              |   16: <mz_environmentd::Listeners>::serve::{closure#0}
platform-checks-mz_3-1              |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a88afb3b337ab65-1/materialize/test/src/environmentd/src/lib.rs:269:5
platform-checks-mz_3-1              |   17: environmentd::run::{closure#11}
platform-checks-mz_3-1              |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a88afb3b337ab65-1/materialize/test/src/environmentd/src/bin/environmentd/main.rs:958:14
platform-checks-mz_3-1              |   18: <tracing::instrument::Instrumented<environmentd::run::{closure#11}> as core::future::future::Future>::poll
platform-checks-mz_3-1              |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
platform-checks-mz_3-1              |   19: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}
platform-checks-mz_3-1              |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:63
platform-checks-mz_3-1              |   20: tokio::runtime::coop::with_budget::<core::task::poll::Poll<core::result::Result<mz_environmentd::Server, anyhow::Error>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}>
platform-checks-mz_3-1              |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:107:5
platform-checks-mz_3-1              |   21: tokio::runtime::coop::budget::<core::task::poll::Poll<core::result::Result<mz_environmentd::Server, anyhow::Error>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}>
platform-checks-mz_3-1              |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:73:5
platform-checks-mz_3-1              |   22: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>
platform-checks-mz_3-1              |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:31
platform-checks-mz_3-1              |   23: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>
platform-checks-mz_3-1              |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/blocking.rs:66:9
platform-checks-mz_3-1              |   24: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}
platform-checks-mz_3-1              |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:87:22
platform-checks-mz_3-1              |   25: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::scheduler::multi_thread::MultiThread>::block_on<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}, core::result::Result<mz_environmentd::Server, anyhow::Error>>
platform-checks-mz_3-1              |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/runtime.rs:65:16
platform-checks-mz_3-1              |   26: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>
platform-checks-mz_3-1              |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
platform-checks-mz_3-1              |   27: <tokio::runtime::runtime::Runtime>::block_on::<environmentd::run::{closure#11}>
platform-checks-mz_3-1              |              at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/runtime.rs:349:50
platform-checks-mz_3-1              |   28: environmentd::run
platform-checks-mz_3-1              |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a88afb3b337ab65-1/materialize/test/src/environmentd/src/bin/environmentd/main.rs:884:18
platform-checks-mz_3-1              |   29: environmentd::main
platform-checks-mz_3-1              |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-09a88afb3b337ab65-1/materialize/test/src/environmentd/src/bin/environmentd/main.rs:568:23
platform-checks-mz_3-1              |   30: <fn() as core::ops::function::FnOnce<()>>::call_once
platform-checks-mz_3-1              |              at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
platform-checks-mz_3-1              | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
ci-regexp: updated bound should match expected

**Comment by jkosh44** [comment]
This is a soft assert that is saying, we tried to downgrade the since of the migration shard to some timestamp `ts`, but the actual since of the migration shard is some timestamp `ts'`, s.t. `ts < ts'`.

It implies that two instances are running through migrations at the same time.

**Comment by jkosh44** [comment]
@def- Am I understanding the output correctly? It looks like the test actually completed successfully, but after it completed there was an unexpected error in the logs which triggered the failure?

**Comment by jkosh44** [comment]
I think I understand what happened. First some background pieces of information:

- When Materialize boots up in read-only mode it will perform some updates to the migration shard and then downgrade the since of the migration shard twice.
- When Materialize is promoted to leader (i.e. restarts and boots up outside of read-only mode) then it will not write to the migration shard, but it will downgrade the since twice.

The test that fails looks something like this:

1. Start `mz_1` as a leader.
2. Initialize `mz_1`.
3. Start `mz_2` in read only mode.
4. Manipulate `mz_1`.
5. Wait for `mz_2` to be ready to promote.
7. Promote `mz_2`.
8. Start `mz_3` in read only mode.
9. Manipulate `mz_2`.
10. Wait for `mz_3` to be ready to promote.
11. Promote `mz_3`.
12. Start `mz_4` in read only mode.
13. Validate `mz_3`.
14. Wait for `mz_4` to be ready to promote.
15. Promote `mz_4`.
16. Validate `mz_4`.

This specific error is happening between steps (11) and (12), but it could theoretically happen in multiple spots. So let's zoom in on steps (11) and (12).

1. Send promote message to `mz_3`.
2. `mz_3` starts booting outside of read only mode.
3. Start booting `mz_4` in read only mode.
4. `mz_3` gets the current upper of the migration shard, `upper`.
5. `mz_4` gets the current upper of the migration shard, `upper`.
6. `mz_4` writes some updates to the migration shard at `upper`.
7. `mz_4` downgrades the since to `upper - 1`.
8. `mz_4` writes some updates to the migration shard at `upper + 1`.
9. `mz_4` downgrades the since to `upper`.
10. `mz_3` tries and fails to downgrade the since to `upper - 1` since it's already downgraded to `upper`.
11. `mz_3` panics.

**Comment by def-** [comment]
> @def- Am I understanding the output correctly? It looks like the test actually completed successfully, but after it completed there was an unexpected error in the logs which triggered the failure?

Correct!

**Comment by jkosh44** [comment]
I don't think this is a release blocker or even a blocker for 0dt. `mz_3` was just fenced earlier than expected and it was able to reboot and recover. I'll think about how to avoid the `soft_assert` in tests.

**Comment by def-** [comment]
If it's just this one panic, then we I add an ignore for it for 0dt tests.

**Comment by jkosh44** [comment]
I have another idea. After promoting instance `mz_n`, we execute and wait for `SELECT 1` on `mz_n` before starting `mz_{n+1}`. That will guarantee that we don't interleave the startup of the two instances.

**Comment by jkosh44** [comment]
Maybe we can add a separate more targeted test that tests booting one instance in read-only mode at the same time as booting another instance outside of read-only mode, but that will be a rare case in practice.

**Comment by def-** [comment]
> I have another idea. After promoting instance `mz_n`, we execute and wait for `SELECT 1` on `mz_n` before starting `mz_{n+1}`. That will guarantee that we don't interleave the startup of the two instances.

I think this is now happening implicitly since we have https://github.com/MaterializeInc/materialize/pull/28540 and my tests will use it: https://github.com/MaterializeInc/materialize/pull/28556

**Comment by jkosh44** [comment]
> > I have another idea. After promoting instance `mz_n`, we execute and wait for `SELECT 1` on `mz_n` before starting `mz_{n+1}`. That will guarantee that we don't interleave the startup of the two instances.
> 
> I think this is now happening implicitly since we have #28540 and my tests will use it: #28556

Ah OK, has this error gone away then? I think we can probably close this issue if so.

**Comment by def-** [comment]
Yes, haven't seen it again. I'll reopen if it happens again.
