### ISSUE TITLE
0dt upgrade: thread 'main' panicked at src/environmentd/src/bin/environmentd/main.rs:569:9: environmentd: fatal: Catalog fenced during builtin table migrations

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#28605]
### What version of Materialize are you using?

37472f451d

### What is the issue?

Failed in [Checks 0dt upgrade across two versions](https://buildkite.com/materialize/nightly/builds/8846#0190f3f7-fb7d-406b-9b54-24d3bebfc3d5):
```
environmentd: 2024-07-27T11:48:59.801504Z  INFO mz_environmentd::deployment::preflight: all clusters hydrated
environmentd: 2024-07-27T11:48:59.801528Z  INFO mz_environmentd::deployment::preflight: announced as ready to promote; waiting for promotion
thread 'main' panicked at src/environmentd/src/bin/environmentd/main.rs:569:9:
environmentd: fatal: Catalog fenced during builtin table migrations
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: environmentd::main
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-021d940ac906aeda5-1/materialize/test/src/environmentd/src/bin/environmentd/main.rs:569:9
   3: <fn() as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Is this something we should ignore? The test still succeeded:
```
==> mzcompose: test case workflow-default succeeded
```
cc @aljoscha 
ci-regexp: Catalog fenced during builtin table migrations

**Comment by jkosh44** [comment]
I looked at the logs and something like the following happened:

```
1. `mz_2` is promoted and starts in writeable mode.
2. `mz_3` starts in read-only mode.
3. `mz_3` gets the migration shard upper, `upper`.
4. `mz_2` gets the migration shard upper, `upper`.
5. `mz_2` writes to the migration shard, advancing the upper to `upper + 1`.
6. `mz_3` tries to write to the migration shard at `upper` and fails.
7. `mz_3` reboots and tries again.
```

It's fine, but I have a PR incoming to make this less likely.
