### ISSUE TITLE
parallel-workload: thread 'coordinator' panicked at src/adapter/src/catalog/apply.rs:825:30: invalid persisted SQL: {create_sql}: PlanError(Catalog(UnknownItem("db-pw-1722343493-0_\"`'><script>\\xE2.s-0-45_<img\\x13src=x on.v-119-3_\u{321}\u{353}\u{31e}\u{345}I\u{317}\u{318}\u{326}")))

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#28660]
### What version of Materialize are you using?

0b982e207c (Pull Request #28630)

### What is the issue?

Seen in [Parallel Workload (rename + naughty identifiers)](https://buildkite.com/materialize/nightly/builds/8867#019103a7-e1f7-406f-8c65-d778b9912adb), but unrelated to the PR this test ran for:
```
thread 'coordinator' panicked at src/adapter/src/catalog/apply.rs:825:30:
invalid persisted SQL: {create_sql}: PlanError(Catalog(UnknownItem("db-pw-1722343493-0_\"`'><script>\\xE2.s-0-45_<img\\x13src=x on.v-119-3_\u{321}\u{353}\u{31e}\u{345}I\u{317}\u{318}\u{326}")))
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1654:5
   3: <core::result::Result<mz_catalog::memory::objects::CatalogItem, mz_adapter::error::AdapterError>>::expect
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1034:23
   4: <mz_adapter::catalog::state::CatalogState>::apply_item_update
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d1fbd955f28d6168-1/materialize/test/src/adapter/src/catalog/apply.rs:823:44
   5: <mz_adapter::catalog::state::CatalogState>::apply_update
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d1fbd955f28d6168-1/materialize/test/src/adapter/src/catalog/apply.rs:228:17
   6: <mz_adapter::catalog::state::CatalogState>::apply_updates_inner
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d1fbd955f28d6168-1/materialize/test/src/adapter/src/catalog/apply.rs:171:21
   7: <mz_adapter::catalog::state::CatalogState>::apply_updates
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d1fbd955f28d6168-1/materialize/test/src/adapter/src/catalog/apply.rs:141:17
   8: <mz_adapter::catalog::Catalog>::transact_inner::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d1fbd955f28d6168-1/materialize/test/src/adapter/src/catalog/transact.rs:511:44
   9: <tracing::instrument::Instrumented<<mz_adapter::catalog::Catalog>::transact_inner::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  10: <mz_adapter::catalog::Catalog>::transact_inner::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d1fbd955f28d6168-1/materialize/test/src/adapter/src/catalog/transact.rs:443:5
  11: <mz_adapter::catalog::Catalog>::transact::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d1fbd955f28d6168-1/materialize/test/src/adapter/src/catalog/transact.rs:404:10
  12: <tracing::instrument::Instrumented<<mz_adapter::catalog::Catalog>::transact::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  13: <mz_adapter::catalog::Catalog>::transact::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d1fbd955f28d6168-1/materialize/test/src/adapter/src/catalog/transact.rs:340:5
  14: <mz_adapter::coord::Coordinator>::catalog_transact_inner::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d1fbd955f28d6168-1/materialize/test/src/adapter/src/coord/ddl.rs:517:14
  15: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::catalog_transact_inner::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  16: <mz_adapter::coord::Coordinator>::catalog_transact_inner::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d1fbd955f28d6168-1/materialize/test/src/adapter/src/coord/ddl.rs:182:5
  17: <mz_adapter::coord::Coordinator>::catalog_transact_with_side_effects::<<mz_adapter::coord::Coordinator>::create_index_finish::{closure#0}::{closure#0}::{closure#1}, <mz_adapter::coord::Coordinator>::create_index_finish::{closure#0}::{closure#0}::{closure#1}::{closure#0}>::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d1fbd955f28d6168-1/materialize/test/src/adapter/src/coord/ddl.rs:96:14
  18: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::catalog_transact_with_side_effects<<mz_adapter::coord::Coordinator>::create_index_finish::{closure#0}::{closure#0}::{closure#1}, <mz_adapter::coord::Coordinator>::create_index_finish::{closure#0}::{closure#0}::{closure#1}::{closure#0}>::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  19: <mz_adapter::coord::Coordinator>::catalog_transact_with_side_effects::<<mz_adapter::coord::Coordinator>::create_index_finish::{closure#0}::{closure#0}::{closure#1}, <mz_adapter::coord::Coordinator>::create_index_finish::{closure#0}::{closure#0}::{closure#1}::{closure#0}>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d1fbd955f28d6168-1/materialize/test/src/adapter/src/coord/ddl.rs:83:5
  20: <mz_adapter::coord::Coordinator>::create_index_finish::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d1fbd955f28d6168-1/materialize/test/src/adapter/src/coord/sequencer/inner/create_index.rs:516:14
  21: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::create_index_finish::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  22: <mz_adapter::coord::Coordinator>::create_index_finish::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d1fbd955f28d6168-1/materialize/test/src/adapter/src/coord/sequencer/inner/create_index.rs:399:5
  23: <mz_adapter::coord::CreateIndexStage as mz_adapter::coord::Staged>::stage::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d1fbd955f28d6168-1/materialize/test/src/adapter/src/coord/sequencer/inner/create_index.rs:57:65
  24: <tracing::instrument::Instrumented<<mz_adapter::coord::CreateIndexStage as mz_adapter::coord::Staged>::stage::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  25: <mz_adapter::coord::Coordinator>::sequence_staged::<mz_adapter::coord::CreateIndexStage>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d1fbd955f28d6168-1/materialize/test/src/adapter/src/coord/sequencer/inner.rs:199:18
  26: <mz_adapter::coord::Coordinator>::handle_message::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d1fbd955f28d6168-1/materialize/test/src/adapter/src/coord/message_handler.rs:161:60
  27: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::handle_message::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  28: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
  29: <mz_adapter::coord::Coordinator>::serve::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d1fbd955f28d6168-1/materialize/test/src/adapter/src/coord.rs:2975:48
  30: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>> as core::future::future::Future>::poll
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
  31: <tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  32: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:63
  33: tokio::runtime::coop::with_budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:107:5
  34: tokio::runtime::coop::budget::<core::task::poll::Poll<()>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:73:5
  35: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:31
  36: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/blocking.rs:66:9
  37: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/handle.rs:310:22
  38: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::handle::Handle>::block_on<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>::{closure#0}, ()>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/runtime.rs:65:16
  39: <tokio::runtime::handle::Handle>::block_on::<core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = ()>>>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/handle.rs:309:9
  40: mz_adapter::coord::serve::{closure#0}::{closure#2}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0d1fbd955f28d6168-1/materialize/test/src/adapter/src/coord.rs:3606:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
This is slightly different from https://github.com/MaterializeInc/materialize/issues/28640 since here the view is unknown, not the schema. We don't rename views. But maybe renaming the schema of the view has this effect, or the naughty identifiers do?
```
ci-regexp: invalid persisted SQL: {create_sql}: PlanError\(Catalog\(UnknownItem
```

**Comment by jkosh44** [comment]
> We don't rename views.

What about Materialized Views? In the logs right before the panic are these two lines

```
parallel-workload-materialized-1     | environmentd: 2024-07-30T13:07:22.682563Z  INFO coord::handle_message{kind="command-execute"}:message_command:coord::handle_execute{session="3d64ffd0-2b99-4d91-ba45-099bcbe7cea9"}:coord::handle_execute_inner{stmt="ALTER MATERIALIZED VIEW \"db-pw-1722343493-0_\"\"`'><script>\\xE2\".\"s-0-45_<img\\x13src=x on\".\"v-119-3_\u{321}\u{353}\u{31e}\u{345}I\u{317}\u{318}\u{326}\" RENAME TO \"v-119-4_<a href=\"\"\\x20jav\""}:sequence_alter_item_rename:coord::catalog_transact_with_ddl_transaction:coord::catalog_transact:coord::catalog_transact_conn:coord::catalog_transact_inner:catalog::transact:catalog::transact_inner:transact_op: mz_adapter::catalog::transact: update materialized view db-pw-1722343493-0_"`'><script>\xE2.s-0-45_<img\x13src=x on.v-119-3_̡͓̞ͅI̗̘̦ (u317)
parallel-workload-materialized-1     | environmentd: 2024-07-30T13:07:22.704669Z  INFO mz_environmentd::http::webhook: fetching webhook appender database="db-pw-1722343493-0_\"`'><script>\\xE2" schema="s-1-36_<<SCRIPT>alert(\"" name="wh-5_0/0"

parallel-workload-materialized-1     | environmentd: 2024-07-30T13:07:22.934223Z  INFO coord::handle_message{kind="deferred_statement_ready"}:handle_deferred_statement:coord::handle_execute_inner{stmt="CREATE INDEX \"idx_v-119-3_\u{321}\u{353}\u{31e}\u{345}I\u{317}\u{318}\u{326}_3018707171559665206\" ON \"db-pw-1722343493-0_\"\"`'><script>\\xE2\".\"s-0-45_<img\\x13src=x on\".\"v-119-3_\u{321}\u{353}\u{31e}\u{345}I\u{317}\u{318}\u{326}\" (\"value7-table3\", \"value1-table3\", \"key0-table3\", \"value8-table3\", \"value9-table3\", \"key3-table3\")"}:sequence_create_index:create_index_finish:coord::catalog_transact_with_side_effects:coord::catalog_transact_inner:catalog::transact:catalog::transact_inner:transact_op: mz_adapter::catalog::transact: create index db-pw-1722343493-0_"`'><script>\xE2.s-0-45_<img\x13src=x on.idx_v-119-3_̡͓̞ͅI̗̘̦_3018707171559665206 (u343)


parallel-workload-materialized-1     | thread 'coordinator' panicked at src/adapter/src/catalog/apply.rs:825:30:
parallel-workload-materialized-1     | invalid persisted SQL: {create_sql}: PlanError(Catalog(UnknownItem("db-pw-1722343493-0_\"`'><script>\\xE2.s-0-45_<img\\x13src=x on.v-119-3_\u{321}\u{353}\u{31e}\u{345}I\u{317}\u{318}\u{326}")))
```

To translate that into something more readable it looks something like:

1. Rename materialized view `a` to `b`.
2. Finish creating index on materialized view `a`.
3. Panic, unknown item `a`.

The fundamental issue is the same as https://github.com/MaterializeInc/materialize/issues/28640, DDLs are acquiring the lock too late and are still able to commit invalid SQL. IMO we can close this and focus discussion on the other issue.

**Comment by def-** [comment]
Sorry, I misspoke, we don't swap views.
