### ISSUE TITLE
0dt: thread 'tokio-runtime-worker' panicked at src/persist-client/src/internal/encoding.rs:291:44: internal error: invalid encoded state: UnknownEnumVariant("ProtoStateField(12)")

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#28712]
### What version of Materialize are you using?

a054e95b8f

### What is the issue?

Seen in [Checks 0dt upgrade across four versions](https://buildkite.com/materialize/nightly/builds/8911#01911067-93c2-4ebf-8af9-e2afb460857a), so it might be related to an older version not having a fix yet:
```
thread 'tokio-runtime-worker' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05d9db7c0d1a01203-1/materialize/test/src/persist-client/src/internal/encoding.rs:291:44:
internal error: invalid encoded state: UnknownEnumVariant("ProtoStateField(12)")
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1654:5
   3: <core::result::Result<mz_persist_client::internal::state_diff::StateDiff<mz_repr::timestamp::Timestamp>, mz_proto::TryFromProtoError>>::expect
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1034:23
   4: <mz_persist_client::internal::state_diff::StateDiff<mz_repr::timestamp::Timestamp>>::decode
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05d9db7c0d1a01203-1/materialize/test/src/persist-client/src/internal/encoding.rs:291:20
   5: <mz_persist_client::internal::state::State<mz_repr::timestamp::Timestamp>>::apply_encoded_diffs::<core::iter::sources::once::Once<&mz_persist::location::VersionedData>>::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05d9db7c0d1a01203-1/materialize/test/src/persist-client/src/internal/state_diff.rs:324:28
   6: <mz_persist_client::internal::metrics::CodecMetrics>::decode::<mz_persist_client::internal::state_diff::StateDiff<mz_repr::timestamp::Timestamp>, <mz_persist_client::internal::state::State<mz_repr::timestamp::Timestamp>>::apply_encoded_diffs<core::iter::sources::once::Once<&mz_persist::location::VersionedData>>::{closure#0}::{closure#0}>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05d9db7c0d1a01203-1/materialize/test/src/persist-client/src/internal/metrics.rs:1065:17
   7: <mz_persist_client::internal::state::State<mz_repr::timestamp::Timestamp>>::apply_encoded_diffs::<&alloc::vec::Vec<mz_persist::location::VersionedData>>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05d9db7c0d1a01203-1/materialize/test/src/persist-client/src/internal/state_diff.rs:320:24
   8: <&mut <mz_persist_client::internal::state::State<mz_repr::timestamp::Timestamp>>::apply_encoded_diffs<&alloc::vec::Vec<mz_persist::location::VersionedData>>::{closure#0} as core::ops::function::FnMut<(&mz_persist::location::VersionedData,)>>::call_mut
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:294:13
   9: <core::slice::iter::Iter<mz_persist::location::VersionedData> as core::iter::traits::iterator::Iterator>::find_map::<(mz_persist_client::internal::state_diff::StateDiff<mz_repr::timestamp::Timestamp>, bytes::bytes::Bytes), &mut <mz_persist_client::internal::state::State<mz_repr::timestamp::Timestamp>>::apply_encoded_diffs<&alloc::vec::Vec<mz_persist::location::VersionedData>>::{closure#0}>
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/slice/iter/macros.rs:317:38
  10: <core::iter::adapters::filter_map::FilterMap<core::slice::iter::Iter<mz_persist::location::VersionedData>, <mz_persist_client::internal::state::State<mz_repr::timestamp::Timestamp>>::apply_encoded_diffs<&alloc::vec::Vec<mz_persist::location::VersionedData>>::{closure#0}> as core::iter::traits::iterator::Iterator>::next
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/iter/adapters/filter_map.rs:64:9
  11: <mz_persist_client::internal::state::State<mz_repr::timestamp::Timestamp>>::apply_diffs::<core::iter::adapters::filter_map::FilterMap<core::slice::iter::Iter<mz_persist::location::VersionedData>, <mz_persist_client::internal::state::State<mz_repr::timestamp::Timestamp>>::apply_encoded_diffs<&alloc::vec::Vec<mz_persist::location::VersionedData>>::{closure#0}>>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05d9db7c0d1a01203-1/materialize/test/src/persist-client/src/internal/state_diff.rs:339:29
  12: <mz_persist_client::internal::state::State<mz_repr::timestamp::Timestamp>>::apply_encoded_diffs::<&alloc::vec::Vec<mz_persist::location::VersionedData>>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05d9db7c0d1a01203-1/materialize/test/src/persist-client/src/internal/state_diff.rs:329:9
  13: <mz_persist_client::internal::apply::Applier<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::fetch_and_update_state::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05d9db7c0d1a01203-1/materialize/test/src/persist-client/src/internal/apply.rs:572:17
  14: <mz_persist_client::cache::LockingTypedState<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::write_lock::<mz_persist::location::SeqNo, <mz_persist_client::internal::apply::Applier<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::fetch_and_update_state::{closure#0}::{closure#0}>
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05d9db7c0d1a01203-1/materialize/test/src/persist-client/src/cache.rs:658:19
  15: <mz_persist_client::internal::apply::Applier<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::fetch_and_update_state::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05d9db7c0d1a01203-1/materialize/test/src/persist-client/src/internal/apply.rs:569:25
  16: <mz_persist_client::internal::apply::Applier<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::apply_unbatched_cmd::<(mz_persist_client::internal::state::LeasedReaderState<mz_repr::timestamp::Timestamp>, mz_persist::location::SeqNo), mz_persist_client::internal::state::NoOpStateTransition<(mz_persist_client::internal::state::LeasedReaderState<mz_repr::timestamp::Timestamp>, mz_persist::location::SeqNo)>, &mut <mz_persist_client::internal::machine::Machine<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::register_leased_reader::{closure#0}::{closure#0}>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05d9db7c0d1a01203-1/materialize/test/src/persist-client/src/internal/apply.rs:345:62
  17: <mz_persist_client::internal::machine::Machine<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::apply_unbatched_idempotent_cmd::<(mz_persist_client::internal::state::LeasedReaderState<mz_repr::timestamp::Timestamp>, mz_persist::location::SeqNo), <mz_persist_client::internal::machine::Machine<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::register_leased_reader::{closure#0}::{closure#0}>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05d9db7c0d1a01203-1/materialize/test/src/persist-client/src/internal/machine.rs:1020:71
  18: <mz_persist_client::internal::machine::Machine<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>>::register_leased_reader::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05d9db7c0d1a01203-1/materialize/test/src/persist-client/src/internal/machine.rs:203:14
  19: <mz_persist_client::PersistClient>::open_leased_reader::<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05d9db7c0d1a01203-1/materialize/test/src/persist-client/src/lib.rs:364:14
  20: <mz_persist_client::PersistClient>::open_leased_reader::<mz_storage_types::sources::SourceData, (), mz_repr::timestamp::Timestamp, i64>::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05d9db7c0d1a01203-1/materialize/test/src/persist-client/src/lib.rs:336:5
  21: <mz_storage_controller::Controller<mz_repr::timestamp::Timestamp>>::read_handle_for_snapshot::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05d9db7c0d1a01203-1/materialize/test/src/storage-controller/src/lib.rs:3416:14
  22: <mz_storage_controller::Controller<mz_repr::timestamp::Timestamp> as mz_storage_client::controller::StorageController>::snapshot::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05d9db7c0d1a01203-1/materialize/test/src/storage-controller/src/lib.rs:1554:73
  23: <core::pin::Pin<alloc::boxed::Box<dyn core::future::future::Future<Output = core::result::Result<alloc::vec::Vec<(mz_repr::row::Row, i64)>, mz_storage_types::controller::StorageError<mz_repr::timestamp::Timestamp>>>>> as core::future::future::Future>::poll
             at ./rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
  24: <mz_adapter::coord::Coordinator>::bootstrap_tables::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05d9db7c0d1a01203-1/materialize/test/src/adapter/src/coord.rs:2208:18
  25: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::bootstrap_tables::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  26: <mz_adapter::coord::Coordinator>::bootstrap_tables::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05d9db7c0d1a01203-1/materialize/test/src/adapter/src/coord.rs:2166:5
  27: <mz_adapter::coord::Coordinator>::bootstrap::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05d9db7c0d1a01203-1/materialize/test/src/adapter/src/coord.rs:2117:68
  28: <tracing::instrument::Instrumented<<mz_adapter::coord::Coordinator>::bootstrap::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  29: <mz_adapter::coord::Coordinator>::bootstrap::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05d9db7c0d1a01203-1/materialize/test/src/adapter/src/coord.rs:1725:5
  30: mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05d9db7c0d1a01203-1/materialize/test/src/adapter/src/coord.rs:3589:60
  31: <tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  32: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:63
  33: tokio::runtime::coop::with_budget::<core::task::poll::Poll<core::result::Result<(), mz_adapter::error::AdapterError>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:107:5
  34: tokio::runtime::coop::budget::<core::task::poll::Poll<core::result::Result<(), mz_adapter::error::AdapterError>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:73:5
  35: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:31
  36: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/blocking.rs:66:9
  37: <tokio::runtime::handle::Handle>::block_on::<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/handle.rs:310:22
  38: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::handle::Handle>::block_on<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}>::{closure#0}, core::result::Result<(), mz_adapter::error::AdapterError>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/runtime.rs:65:16
  39: <tokio::runtime::handle::Handle>::block_on::<mz_adapter::coord::serve::{closure#0}::{closure#2}::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/handle.rs:309:9
  40: mz_adapter::coord::serve::{closure#0}::{closure#2}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-05d9db7c0d1a01203-1/materialize/test/src/adapter/src/coord.rs:3588:33
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
mz_4 is at v0.110.1, so the last version before current:
```
Upgrade path: v0.107.5 -> v0.108.4 -> v0.109.1 -> v0.110.1 -> current
```
Can you please check if this should block the release or be ignored?
ci-regexp: internal error: invalid encoded state: UnknownEnumVariant

**Comment by antiguru** [comment]
Potentially related: #28454
