### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at src/cluster/src/communication.rs:216:32: someone claimed to be us

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#28997]
### What version of Materialize are you using?

eddd6923419b (Pull Request #28996)

### What is the issue?

Seen in [Replica isolation](https://buildkite.com/materialize/test/builds/88267#0191510f-adfc-4b63-8e59-a600ac6a746b)
```
thread 'tokio-runtime-worker' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-092d578492aa35fdd-1/materialize/test/src/cluster/src/communication.rs:216:32:
someone claimed to be us
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: mz_cluster::communication::initialize_networking::{closure#0}
   3: <mz_cluster::server::ClusterClient<mz_service::client::Partitioned<mz_service::local::LocalClient<mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse, std::thread::Thread>, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>, mz_storage::server::Config, mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse> as mz_service::client::GenericClient<mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>>::send::{closure#0}
   4: <alloc::boxed::Box<dyn mz_storage_client::client::StorageClient> as mz_service::client::GenericClient<mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse>>::send::{closure#0}
   5: <async_stream::async_stream::AsyncStream<core::result::Result<mz_storage_client::client::ProtoStorageResponse, tonic::status::Status>, <mz_service::grpc::GrpcServer<mz_storage::server::serve::{closure#0}>>::forward_bidi_stream<mz_storage_client::client::StorageCommand, mz_storage_client::client::StorageResponse, mz_storage_client::client::ProtoStorageCommand, mz_storage_client::client::ProtoStorageResponse>::{closure#0}::{closure#1}> as futures_core::stream::Stream>::poll_next
   6: <tonic::codec::encode::EncodeBody<tonic::codec::encode::EncodedBytes<tonic::codec::prost::ProstEncoder<mz_storage_client::client::ProtoStorageResponse>, tokio_stream::stream_ext::fuse::Fuse<mz_service::grpc::ResponseStream<mz_storage_client::client::ProtoStorageResponse>>>> as http_body::Body>::poll_frame
   7: <http_body_util::combinators::map_err::MapErr<http_body_util::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes, tonic::status::Status>, <tonic::status::Status>::map_error<tonic::status::Status>> as http_body::Body>::poll_frame
   8: <http_body_util::combinators::map_err::MapErr<http_body_util::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes, tonic::status::Status>, <axum_core::error::Error>::new<tonic::status::Status>> as http_body::Body>::poll_frame
   9: <http_body_util::combinators::map_err::MapErr<axum_core::body::Body, <tonic::status::Status>::map_error<axum_core::error::Error>> as http_body::Body>::poll_frame
  10: <http_body_util::combinators::map_err::MapErr<http_body_util::combinators::map_err::MapErr<tonic::transport::server::service::recover_error::MaybeEmptyBody<http_body_util::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes, tonic::status::Status>>, <tonic::status::Status as core::convert::Into<alloc::boxed::Box<dyn core::error::Error + core::marker::Send + core::marker::Sync>>>::into>, <tonic::status::Status>::map_error<alloc::boxed::Box<dyn core::error::Error + core::marker::Send + core::marker::Sync>>> as http_body::Body>::poll_frame
  11: <hyper::proto::h2::PipeToSendStream<http_body_util::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes, tonic::status::Status>> as core::future::future::Future>::poll
  12: <tracing::instrument::Instrumented<hyper::proto::h2::server::H2Stream<hyper_util::service::TowerToHyperServiceFuture<tower::util::map_request::MapRequest<tower::util::boxed_clone::BoxCloneService<http::request::Request<http_body_util::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes, tonic::status::Status>>, http::response::Response<http_body_util::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes, tonic::status::Status>>, alloc::boxed::Box<dyn core::error::Error + core::marker::Send + core::marker::Sync>>, <tonic::transport::server::Server>::serve_with_shutdown<tonic::service::router::Routes, mz_ore::netio::socket::Listener, core::future::ready::Ready<()>, mz_ore::netio::socket::Stream, std::io::error::Error, http_body_util::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes, tonic::status::Status>>::{closure#0}::{closure#3}>, http::request::Request<hyper::body::incoming::Incoming>>, http_body_util::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes, tonic::status::Status>>> as core::future::future::Future>::poll
  13: <tokio::runtime::task::core::Core<tracing::instrument::Instrumented<hyper::proto::h2::server::H2Stream<hyper_util::service::TowerToHyperServiceFuture<tower::util::map_request::MapRequest<tower::util::boxed_clone::BoxCloneService<http::request::Request<http_body_util::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes, tonic::status::Status>>, http::response::Response<http_body_util::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes, tonic::status::Status>>, alloc::boxed::Box<dyn core::error::Error + core::marker::Send + core::marker::Sync>>, <tonic::transport::server::Server>::serve_with_shutdown<tonic::service::router::Routes, mz_ore::netio::socket::Listener, core::future::ready::Ready<()>, mz_ore::netio::socket::Stream, std::io::error::Error, http_body_util::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes, tonic::status::Status>>::{closure#0}::{closure#3}>, http::request::Request<hyper::body::incoming::Incoming>>, http_body_util::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes, tonic::status::Status>>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread_alt::handle::Handle>>>::poll
  14: tokio::runtime::task::raw::poll::<tracing::instrument::Instrumented<hyper::proto::h2::server::H2Stream<hyper_util::service::TowerToHyperServiceFuture<tower::util::map_request::MapRequest<tower::util::boxed_clone::BoxCloneService<http::request::Request<http_body_util::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes, tonic::status::Status>>, http::response::Response<http_body_util::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes, tonic::status::Status>>, alloc::boxed::Box<dyn core::error::Error + core::marker::Send + core::marker::Sync>>, <tonic::transport::server::Server>::serve_with_shutdown<tonic::service::router::Routes, mz_ore::netio::socket::Listener, core::future::ready::Ready<()>, mz_ore::netio::socket::Stream, std::io::error::Error, http_body_util::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes, tonic::status::Status>>::{closure#0}::{closure#3}>, http::request::Request<hyper::body::incoming::Incoming>>, http_body_util::combinators::box_body::UnsyncBoxBody<bytes::bytes::Bytes, tonic::status::Status>>>, alloc::sync::Arc<tokio::runtime::scheduler::multi_thread::handle::Handle>>
  15: <tokio::runtime::scheduler::multi_thread::worker::Context>::run_task
  16: <tokio::runtime::context::scoped::Scoped<tokio::runtime::scheduler::Context>>::set::<tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}::{closure#0}, ()>
  17: tokio::runtime::context::runtime::enter_runtime::<tokio::runtime::scheduler::multi_thread::worker::run::{closure#0}, ()>
  18: tokio::runtime::scheduler::multi_thread::worker::run
  19: <tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}> as core::future::future::Future>::poll
  20: <tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>> as core::future::future::Future>::poll
  21: <tokio::runtime::task::core::Core<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll
  22: <tokio::runtime::task::harness::Harness<tracing::instrument::Instrumented<tokio::runtime::blocking::task::BlockingTask<<tokio::runtime::scheduler::multi_thread::worker::Launch>::launch::{closure#0}>>, tokio::runtime::blocking::schedule::BlockingSchedule>>::poll
  23: <tokio::runtime::blocking::pool::Inner>::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
ci-regexp: someone claimed to be us

**Comment by def-** [comment]
Seen again in CI: https://ci-failures.dev.materialize.com/?key=test-failures&tfFilters=%5B%7B%22id%22%3A%22branch%22%2C%22value%22%3A%22main%22%7D%2C%7B%22id%22%3A%22build_date%22%2C%22value%22%3A%5Bnull%2Cnull%5D%7D%2C%7B%22id%22%3A%22issue%22%2C%22value%22%3A%2228997%22%7D%5D
I'll try to repro locally.

**Comment by def-** [comment]
Before #28380 I got this failure instead:
```
replica-isolation-materialized-1     | environmentd: 2024-08-15T13:36:34.862548Z  INFO mz_compute_client::controller::replica: error connecting to replica, retrying in 1s: transport error: dns error: failed to lookup address information: Temporary failure in name resolution: dns error: failed to lookup address information: Temporary failure in name resolution: failed to lookup address information: Temporary failure in name resolution replica=User(2)
```
So something was weird there too, but never this panic.

**Comment by teskje** [comment]
That looks like https://github.com/MaterializeInc/materialize/issues/28046, one of the two issues that #28380 was intended to fix.

**Comment by teskje** [comment]
The immediate cause for the panic is that we somehow mix up the Timely cluster addresses:

```
replica-isolation-clusterd_1_1-1     | 2024-08-14T13:37:36.787476Z  INFO mz_cluster::communication: initializing network for timely instance, with 2 processes for epoch number (2, 3) process=1 addresses=["clusterd_1_1:2103", "clusterd_1_2:2103"]
replica-isolation-clusterd_1_2-1     | 2024-08-14T13:37:36.787210Z  INFO mz_cluster::communication: initializing network for timely instance, with 2 processes for epoch number (2, 3) process=0 addresses=["clusterd_1_1:2103", "clusterd_1_2:2103"]
```

Note how the `process` configs say that `clusterd_1_1` is process 1 and `clusterd_1_2` is process 0, but the `addresses` say the exact opposite.

When `clusterd_1_1` comes up, it identifies as process 1 and tries to connect to process 0. It looks up the address of process 0, which is `clusterd_1_1:2103`, i.e. it's own address. It therefore connects to itself and rightly panics.

**Comment by teskje** [comment]
Here is a faster way to repro:

```python
def workflow_replica_restart(c: Composition) -> None:
    c.down(destroy_volumes=True)

    c.up("materialized", "clusterd1", "clusterd2")

    c.sql(
        "ALTER SYSTEM SET enable_unorchestrated_cluster_replicas = true",
        port=6877,
        user="mz_system",
    )

    c.sql(
        """
        CREATE CLUSTER cluster1 REPLICAS (
            replica1 (
                STORAGECTL ADDRESSES ['clusterd1:2100', 'clusterd2:2100'],
                STORAGE ADDRESSES ['clusterd1:2103', 'clusterd2:2103'],
                COMPUTECTL ADDRESSES ['clusterd1:2101', 'clusterd2:2101'],
                COMPUTE ADDRESSES ['clusterd1:2102', 'clusterd2:2102'],
                WORKERS 2
            )
        );
        CREATE TABLE t (a int);
        """
    )

    while True:
        c.kill("clusterd1", "clusterd2")
        c.up("clusterd1", "clusterd2")

        c.sql(
            """
            SET cluster = cluster1;
            SELECT * FROM t;
            """
        )
```

**Comment by teskje** [comment]
I've tracked this down to what is likely an issue with networking in Docker. All the configuration sent by the controller is correct. With the above quick repro, it sends:

* `TimelyConfig { process: 0, addresses: ["clusterd1:2103", "clusterd2:2103"], .. }` to `clusterd1`
* `TimelyConfig { process: 1, addresses: ["clusterd1:2103", "clusterd2:2103"], .. }` to `clusterd2`

The issue is that when the controller tries to connect with `clusterd1`, the connection is actually established with `clusterd2`, and vice versa. My best guess is that the two containers have swapped IPs and the (cached) DNS entries still have the old mapping. But I don't know enough about Docker networking to confirm this.

**Comment by def-** [comment]
How did that never break tests for us before?! Can we disable DNS caching?
