### ISSUE TITLE
0dt: thread 'main' panicked at src/catalog/src/durable/persist.rs:1677:5: snapshot_and_fetch guarantees a consolidated result

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#29293]
### What version of Materialize are you using?

6dd964bd20

### What is the issue?

Seen in [Parallel Workload (0dt deploy)](https://buildkite.com/materialize/nightly/builds/9324#0191a07a-3d9a-458a-b820-a28b52ce64a6):
```
 2024-08-29 23:56:02 UTC	Awaiting materialized2 deployment status ReadyToPromote for 900s.....
2024-08-29 23:56:08 UTC	.....Query failed: CREATE SECRET pgpass2 AS 'postgres' {'S': 'ERROR', 'C': '25006', 'M': 'cannot write in read-only mode'}
2024-08-29 23:56:08 UTC	Query failed: CREATE SECRET pgpass3 AS 'postgres' {'S': 'ERROR', 'C': '25006', 'M': 'cannot write in read-only mode'}
2024-08-29 23:56:09 UTC	 Reached!
2024-08-29 23:56:09 UTC	$ docker compose exec -T materialized2 curl -s -X POST localhost:6878/api/leader/promote
2024-08-29 23:56:12 UTC	Awaiting materialized2 deployment status IsLeader for 900s....
2024-08-29 23:56:23 UTC	.........
[...]
2024-08-30 00:09:12 UTC	.........
```
There is a panic loop after the promotion:
```
thread 'main' panicked at /var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e7bfe2f4c1eaa190-1/materialize/test/src/catalog/src/durable/persist.rs:1677:5:
snapshot_and_fetch guarantees a consolidated result: [((Ok(SourceData(Ok(Row{[Map({"epoch": Numeric(OrderedDecimal(2)), "kind": String("Epoch")})]}))), Ok(())), 102, 1), ((Ok(SourceData(Ok(Row{[Map({"epoch": Numeric(OrderedDecimal(3)), "kind": String("Epoch")})]}))), Ok(())), 102, -1)[...]
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at ./rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
   2: mz_catalog::durable::persist::snapshot_binary_inner::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e7bfe2f4c1eaa190-1/materialize/test/src/catalog/src/durable/persist.rs:1677:5
   3: mz_catalog::durable::persist::snapshot_binary_inner::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e7bfe2f4c1eaa190-1/materialize/test/src/catalog/src/durable/persist.rs:1668:1
   4: <mz_ore::metrics::WallTimeFuture<mz_catalog::durable::persist::snapshot_binary_inner::{closure#0}, prometheus::counter::GenericCounter<prometheus::atomic64::AtomicF64>> as core::future::future::Future>::poll
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e7bfe2f4c1eaa190-1/materialize/test/src/ore/src/metrics.rs:612:28
   5: mz_catalog::durable::persist::snapshot_binary::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e7bfe2f4c1eaa190-1/materialize/test/src/catalog/src/durable/persist.rs:1661:10
   6: mz_catalog::durable::persist::snapshot_binary::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e7bfe2f4c1eaa190-1/materialize/test/src/catalog/src/durable/persist.rs:1650:1
   7: <mz_catalog::durable::persist::PersistHandle<mz_catalog::durable::objects::state_update::StateUpdateKindJson, mz_catalog::durable::persist::UnopenedCatalogStateInner>>::new::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e7bfe2f4c1eaa190-1/materialize/test/src/catalog/src/durable/persist.rs:940:14
   8: <tracing::instrument::Instrumented<<mz_catalog::durable::persist::PersistHandle<mz_catalog::durable::objects::state_update::StateUpdateKindJson, mz_catalog::durable::persist::UnopenedCatalogStateInner>>::new::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
   9: <mz_catalog::durable::persist::PersistHandle<mz_catalog::durable::objects::state_update::StateUpdateKindJson, mz_catalog::durable::persist::UnopenedCatalogStateInner>>::new::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e7bfe2f4c1eaa190-1/materialize/test/src/catalog/src/durable/persist.rs:866:5
  10: mz_catalog::durable::persist_backed_catalog_state::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e7bfe2f4c1eaa190-1/materialize/test/src/catalog/src/durable.rs:405:6
  11: <mz_environmentd::Listeners>::serve::{closure#0}::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e7bfe2f4c1eaa190-1/materialize/test/src/environmentd/src/lib.rs:351:10
  12: <tracing::instrument::Instrumented<<mz_environmentd::Listeners>::serve::{closure#0}::{closure#0}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  13: <mz_environmentd::Listeners>::serve::{closure#0}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e7bfe2f4c1eaa190-1/materialize/test/src/environmentd/src/lib.rs:274:5
  14: environmentd::run::{closure#11}
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e7bfe2f4c1eaa190-1/materialize/test/src/environmentd/src/bin/environmentd/main.rs:1015:14
  15: <tracing::instrument::Instrumented<environmentd::run::{closure#11}> as core::future::future::Future>::poll
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  16: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:63
  17: tokio::runtime::coop::with_budget::<core::task::poll::Poll<core::result::Result<mz_environmentd::Server, anyhow::Error>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:107:5
  18: tokio::runtime::coop::budget::<core::task::poll::Poll<core::result::Result<mz_environmentd::Server, anyhow::Error>>, <tokio::runtime::park::CachedParkThread>::block_on<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:73:5
  19: <tokio::runtime::park::CachedParkThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:31
  20: <tokio::runtime::context::blocking::BlockingRegionGuard>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/blocking.rs:66:9
  21: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:87:22
  22: tokio::runtime::context::runtime::enter_runtime::<<tokio::runtime::scheduler::multi_thread::MultiThread>::block_on<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>::{closure#0}, core::result::Result<mz_environmentd::Server, anyhow::Error>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/runtime.rs:65:16
  23: <tokio::runtime::scheduler::multi_thread::MultiThread>::block_on::<tracing::instrument::Instrumented<environmentd::run::{closure#11}>>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  24: <tokio::runtime::runtime::Runtime>::block_on::<environmentd::run::{closure#11}>
             at ./cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/runtime.rs:349:50
  25: environmentd::run
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e7bfe2f4c1eaa190-1/materialize/test/src/environmentd/src/bin/environmentd/main.rs:938:18
  26: environmentd::main
             at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-0e7bfe2f4c1eaa190-1/materialize/test/src/environmentd/src/bin/environmentd/main.rs:603:23
  27: <fn() as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Full panic message: https://gist.github.com/def-/c8d6f78947b9371afb4a33b4c6629829
It's also occurring in the just cut v0.115.0: https://buildkite.com/materialize/nightly/builds/9327#0191a29d-9c90-4704-8a3a-43b702d221a6 (2/2 times, retrying again). I'm not sure yet if this is a flake or reproducible.
Range of changes of when this started happening: https://github.com/MaterializeInc/materialize/compare/bc6782d50b...6dd964bd20
This change seems suspicious: https://github.com/MaterializeInc/materialize/pull/29249 but it had a nightly run and the test was green there.
Maybe https://github.com/MaterializeInc/materialize/pull/29204 is responsible. I'll do a few more runs to figure out the responsible change.

**Comment by jkosh44** [comment]
It's almost certainly https://github.com/MaterializeInc/materialize/pull/29249. I can try and figure out what's going on, but it might be best to just revert it for now.

**Comment by jkosh44** [comment]
https://github.com/MaterializeInc/materialize/pull/29294

**Comment by jkosh44** [comment]
The problematic entries are here:
```
((Ok(SourceData(Ok(Row{[Map({"epoch": Numeric(OrderedDecimal(2)), "kind": String("Epoch")})]}))), Ok(())), 102, 1), 
((Ok(SourceData(Ok(Row{[Map({"epoch": Numeric(OrderedDecimal(3)), "kind": String("Epoch")})]}))), Ok(())), 102, -1), 
((Ok(SourceData(Ok(Row{[Map({"epoch": Numeric(OrderedDecimal(4)), "kind": String("Epoch")})]}))), Ok(())), 102, 1), 
```

The 2 epoch is never retracted and the 3 epoch is never added.

**Comment by jkosh44** [comment]
I found the actual issue: https://github.com/MaterializeInc/materialize/pull/29295

I actually had a branch that fixed this exact issue, but forgot to incorporate the fix in the previous merged PR. I'll try and add some more targeted tests as well.
