### ISSUE TITLE
cargo test: mz-persist-client internal::state_diff::tests::test_state_sync is flaky

### ISSUE THREAD

**Issue by def-** [MaterializeInc/materialize#29385]
### What version of Materialize are you using?

225d9edf2946

### What is the issue?

Seen in [Cargo test](https://buildkite.com/materialize/test/builds/89794#0191bed3-83b3-4734-880f-63c56b62420e):
```
thread 'internal::state_diff::tests::test_state_sync' panicked at src/persist-client/src/internal/state_diff.rs:1365:22:
diff applies to the synced version of the follower state: "hollow batch lower [44] did not match expected lower [0]"
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/result.rs:1679:5
   3: <core::result::Result<(), alloc::string::String>>::expect
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/result.rs:1059:23
   4: mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::run
             at ./src/internal/state_diff.rs:1363:17
   5: mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::{closure#3}
             at ./src/internal/state_diff.rs:1377:13
   6: <&mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::{closure#3} as core::ops::function::Fn<(proptest::sugar::NamedArguments<&str, alloc::vec::Vec<(mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::Action, bool)>>,)>>::call
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:262:13
   7: proptest::test_runner::runner::call_test::<proptest::sugar::NamedArguments<&str, alloc::vec::Vec<(mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::Action, bool)>>, &mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::{closure#3}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>::{closure#0}
             at /cargo/git/checkouts/proptest-e0d773c2e7a31a11/4d8c406/proptest/src/test_runner/runner.rs:246:49
   8: <core::panic::unwind_safe::AssertUnwindSafe<proptest::test_runner::runner::call_test<proptest::sugar::NamedArguments<&str, alloc::vec::Vec<(mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::Action, bool)>>, &mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::{closure#3}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>::{closure#0}> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panic/unwind_safe.rs:272:9
   9: do_call<core::panic::unwind_safe::AssertUnwindSafe<proptest::test_runner::runner::call_test::{closure_env#0}<proptest::sugar::NamedArguments<&str, alloc::vec::Vec<(mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::Action, bool), alloc::alloc::Global>>, &mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::{closure_env#3}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>>, core::result::Result<(), proptest::test_runner::errors::TestCaseError>>
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:559:40
  10: __rust_try
  11: try<core::result::Result<(), proptest::test_runner::errors::TestCaseError>, core::panic::unwind_safe::AssertUnwindSafe<proptest::test_runner::runner::call_test::{closure_env#0}<proptest::sugar::NamedArguments<&str, alloc::vec::Vec<(mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::Action, bool), alloc::alloc::Global>>, &mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::{closure_env#3}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>>>
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:523:19
  12: std::panic::catch_unwind::<core::panic::unwind_safe::AssertUnwindSafe<proptest::test_runner::runner::call_test<proptest::sugar::NamedArguments<&str, alloc::vec::Vec<(mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::Action, bool)>>, &mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::{closure#3}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>::{closure#0}>, core::result::Result<(), proptest::test_runner::errors::TestCaseError>>
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panic.rs:149:14
  13: call_test<proptest::sugar::NamedArguments<&str, alloc::vec::Vec<(mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::Action, bool), alloc::alloc::Global>>, &mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::{closure_env#3}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>
             at /cargo/git/checkouts/proptest-e0d773c2e7a31a11/4d8c406/proptest/src/test_runner/runner.rs:246:9
  14: <proptest::test_runner::runner::TestRunner>::run_one_with_replay::<proptest::strategy::map::Map<proptest::collection::VecValueTree<proptest::tuple::TupleValueTree<(alloc::boxed::Box<dyn proptest::strategy::traits::ValueTree<Value = mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::Action>>, proptest::bool::BoolValueTree)>>, mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::{closure#2}>, &mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::{closure#3}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>
             at /cargo/git/checkouts/proptest-e0d773c2e7a31a11/4d8c406/proptest/src/test_runner/runner.rs:693:22
  15: <proptest::test_runner::runner::TestRunner>::gen_and_run_case::<proptest::strategy::map::Map<proptest::collection::VecStrategy<(proptest::strategy::traits::BoxedStrategy<mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::Action>, proptest::bool::Any)>, mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::{closure#2}>, mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::{closure#3}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>
             at /cargo/git/checkouts/proptest-e0d773c2e7a31a11/4d8c406/proptest/src/test_runner/runner.rs:649:12
  16: <proptest::test_runner::runner::TestRunner>::run_in_process_with_replay::<proptest::strategy::map::Map<proptest::collection::VecStrategy<(proptest::strategy::traits::BoxedStrategy<mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::Action>, proptest::bool::Any)>, mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::{closure#2}>, mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::{closure#3}, core::iter::sources::empty::Empty<core::result::Result<(), proptest::test_runner::errors::TestCaseError>>>
             at /cargo/git/checkouts/proptest-e0d773c2e7a31a11/4d8c406/proptest/src/test_runner/runner.rs:602:26
  17: <proptest::test_runner::runner::TestRunner>::run_in_process::<proptest::strategy::map::Map<proptest::collection::VecStrategy<(proptest::strategy::traits::BoxedStrategy<mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::Action>, proptest::bool::Any)>, mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::{closure#2}>, mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::{closure#3}>
             at /cargo/git/checkouts/proptest-e0d773c2e7a31a11/4d8c406/proptest/src/test_runner/runner.rs:560:9
  18: <proptest::test_runner::runner::TestRunner>::run::<proptest::strategy::map::Map<proptest::collection::VecStrategy<(proptest::strategy::traits::BoxedStrategy<mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::Action>, proptest::bool::Any)>, mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::{closure#2}>, mz_persist_client::internal::state_diff::tests::test_state_sync::test_impl::{closure#3}>
             at /cargo/git/checkouts/proptest-e0d773c2e7a31a11/4d8c406/proptest/src/test_runner/runner.rs:403:13
  19: test_impl
             at ./src/internal/state_diff.rs:1376:9
  20: mz_persist_client::internal::state_diff::tests::test_state_sync
             at ./src/internal/state_diff.rs:1264:5
  21: mz_persist_client::internal::state_diff::tests::test_state_sync::{closure#0}
             at ./src/internal/state_diff.rs:1264:20
  22: <mz_persist_client::internal::state_diff::tests::test_state_sync::{closure#0} as core::ops::function::FnOnce<()>>::call_once
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:250:5
  23: core::ops::function::FnOnce::call_once
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

ci-regexp: diff applies to the synced version of the follower state

**Comment by def-** [comment]
This seems to have started with https://github.com/MaterializeInc/materialize/pull/29382 being merged, so marking as a potential release blocker
