### ISSUE TITLE
create table from source: unreachable code: kafka sources do not have tables

### ISSUE THREAD

**Issue by nrainer-materialize** [MaterializeInc/materialize#29562]
### What version of Materialize are you using?

e8e6737

### What is the issue?

https://github.com/MaterializeInc/materialize/blob/8fc2805cc3260cf54791adaccac88295196802fe/test/testdrive/source-tables.td#L317-L322

panics due to
```
materialized-1          | thread 'coordinator' panicked at src/adapter/src/catalog/builtin_table_updates.rs:539:38:
materialized-1          | internal error: entered unreachable code: kafka sources do not have tables
materialized-1          |    8: rust_begin_unwind
materialized-1          |              at ./rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
materialized-1          |    9: core::panicking::panic_fmt
materialized-1          |              at ./rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
materialized-1          |   10: <mz_adapter::catalog::state::CatalogState>::pack_item_update
materialized-1          |   11: <mz_adapter::catalog::state::CatalogState>::generate_builtin_table_update
materialized-1          |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-01716cd3d871411f3-1/materialize/test/src/adapter/src/catalog/apply.rs:1079:44
materialized-1          |   12: <mz_adapter::catalog::state::CatalogState>::apply_updates_inner
materialized-1          |              at ./var/lib/buildkite-agent/builds/buildkite-builders-aarch64-585fc7f-i-01716cd3d871411f3-1/materialize/test/src/adapter/src/catalog/apply.rs:176:33
```

**Comment by rjobanp** [comment]
https://github.com/MaterializeInc/materialize/pull/29563
