### ISSUE TITLE
Support PgResultSet.getObject()

### ISSUE THREAD

**Issue by jacobobryant** [MaterializeInc/materialize#3590]
Sometimes, calling [getObject](https://jdbc.postgresql.org/development/privateapi/org/postgresql/jdbc/PgResultSet.html#getObject-int-) (from the postgres jdbc driver) gives the following error:

```
org.postgresql.util.PSQLException: ERROR: Parse error:
SELECT n.nspname = ANY(current_schemas(true)), n.nspname, t.typname FROM pg_catalog.pg_type t JOIN pg_catalog.pg_namespace n ON t.typnamespace = n.oid WHERE t.oid = $1
                       ^^^^^^^^^^^^^^^
Expected SELECT, VALUES, or a subquery in the query body, found: current_schemas
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2532)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2267)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:312)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:153)
        at org.postgresql.jdbc.TypeInfoCache.getPGType(TypeInfoCache.java:447)
        at org.postgresql.jdbc.PgResultSet.initSqlType(PgResultSet.java:2738)
        at org.postgresql.jdbc.PgResultSet.getSQLType(PgResultSet.java:2728)
        at org.postgresql.jdbc.PgResultSet.internalGetObject(PgResultSet.java:167)
        at org.postgresql.jdbc.PgResultSet.getObject(PgResultSet.java:2593)
```

(Let me know if you'd like me to provide a minimal example). I see you have a fork of pgjdbc; perhaps [this method](https://github.com/MaterializeInc/pgjdbc/blob/6743d2c651143e9780d365ebb15520c993d6a3f6/pgjdbc/src/main/java/io/materialize/jdbc/TypeInfoCache.java#L342) could simply be replaced?

**Comment by quodlibetor** [comment]
Until we fully implement `pg_catalog` and related functionality it is possible to use our _temporary_ fork of pgjdbc at https://github.com/MaterializeInc/pgjdbc/ 

We don't intend to publish it, so the sections in the README are holdovers from the fork which we will clean up. Until the documentation is fixed the general strategy is to clone that repo into a subdirectory of your project and refer to it that way. There is approximate documentation in our [Metabase docker image repository](https://github.com/MaterializeInc/metabase-materialize-driver#step-1-use-the-forked-pgjdbc-driver-to-connect-to-materialize).
