### ISSUE TITLE
sql: panic unwrapping error

### ISSUE THREAD

**Issue by justinj** [MaterializeInc/materialize#3914]
```
materialize=> show create view tab0;
          View           |                                                           Create View
-------------------------+---------------------------------------------------------------------------------------------------------------------------------
 materialize.public.tab0 | CREATE VIEW "materialize"."public"."tab0" AS SELECT "column1" AS "tab0_0" FROM (SELECT * FROM (VALUES (NULL::int)) WHERE false)
(1 row)
materialize=> (SELECT * FROM ((SELECT 'foo' AS col1801 FROM ((SELECT 'baz' AS col1799) RIGHT JOIN (SELECT tab0_0 AS col1800 FROM tab0) ON false)) FULL OUTER JOIN (SELECT * FROM ((SELECT true AS col1802, false AS col1803) INNER JOIN (SELECT * FROM (SELECT tab0_0 AS col1804 FROM tab0) EXCEPT ALL (SELECT 456 AS col1806 FROM (SELECT * FROM (SELECT 'baz' AS col1805) WHERE false))) ON col1802) WHERE true) ON (456 <= (789 / col1804))) WHERE (col1803 OR ((false != col1803) OR col1802)));
server closed the connection unexpectedly
```

```
 thread: <unnamed>
message: called `Result::unwrap()` on an `Err` value: "Can\'t union types: Int32 and Bool\nIn Union
```

```
   9: expr::relation::RelationExpr::typ
             at src/expr/src/relation/mod.rs:444
  10: transform::reduction::FoldConstants::action
             at src/transform/src/reduction.rs:40
  11: <transform::reduction::FoldConstants as transform::Transform>::transform::{{closure}}
             at src/transform/src/reduction.rs:33
  12: expr::relation::RelationExpr::try_visit_mut
             at src/expr/src/relation/mod.rs:864
  13: expr::relation::RelationExpr::try_visit_mut::{{closure}}
             at src/expr/src/relation/mod.rs:863
  14: expr::relation::RelationExpr::try_visit1_mut
             at src/expr/src/relation/mod.rs:808
  15: expr::relation::RelationExpr::try_visit_mut
             at src/expr/src/relation/mod.rs:863
  16: expr::relation::RelationExpr::try_visit_mut::{{closure}}
             at src/expr/src/relation/mod.rs:863
  17: expr::relation::RelationExpr::try_visit1_mut
             at src/expr/src/relation/mod.rs:808
  18: expr::relation::RelationExpr::try_visit_mut
             at src/expr/src/relation/mod.rs:863
```

**Comment by benesch** [comment]
`EXPLAIN RAW PLAN` works just fine on this query, so seems to be an optimizer bug.

**Comment by benesch** [comment]
Hand reduced:

```sql
SELECT
	*
FROM
	(
		(SELECT 'foo')
		RIGHT JOIN (
				(SELECT true)
				CROSS JOIN (
						SELECT 1 FROM tab0 EXCEPT ALL (SELECT 456 WHERE false)
					)
			) ON true
	);
```

**Comment by benesch** [comment]
```
              Raw Plan              
------------------------------------
 %0 =                              +
 | Constant ()                     +
 | Map "foo"                       +
                                   +
 %1 =                              +
 | Constant ()                     +
 | Map true                        +
                                   +
 %2 =                              +
 | Get materialize.public.tab0 (u4)+
 | Map 1                           +
 | Project (#1)                    +
                                   +
 %3 =                              +
 | Constant ()                     +
 | Filter false                    +
 | Map 456                         +
 | Negate                          +
                                   +
 %4 =                              +
 | Union %2 %3                     +
 | Threshold                       +
                                   +
 %5 =                              +
 | InnerJoin %1 %4 on true         +
                                   +
 %6 =                              +
 | RightOuterJoin %0 %5 on true    +
 
```

**Comment by benesch** [comment]
It's a bug in the demand transform.

```
thread '<unnamed>' panicked at 'corrupted! old:
%0 =
| Get %?
| | types = (i32)
| | keys = ()
| Negate
| | types = (i32)
| | keys = ()
| Map true, "foo", true, 1
| | types = (i32, bool, string, bool, i32)
| | keys = ()
| Project (#3, #4)
| | types = (bool, i32)
| | keys = ()

%1 =
| Get %?
| | types = (i32)
| | keys = ()
| Map true, true, 1
| | types = (i32, bool, bool, i32)
| | keys = ()
| Project (#2, #3)
| | types = (bool, i32)
| | keys = ()

%2 =
| Union %0 %1
| | types = (bool, i32)
| | keys = ()

%3 =
| Join %2 (= #0 true) (= #0 #1)
| | implementation = Unimplemented
| | types = (bool, i32)
| | keys = ()

new:
%0 =
| Get %?
| | types = (i32)
| | keys = ()
| Negate
| | types = (i32)
| | keys = ()
| Map true, "foo", true, 1
| | types = (i32, bool, string, bool, i32)
| | keys = ()
| Project (#3, #4)
| | types = (bool, i32)
| | keys = ()

%1 =
| Get %?
| | types = (i32)
| | keys = ()
| Map true, true, 1
| | types = (i32, bool, bool, i32)
| | keys = ()
| Project (#2, #3)
| | types = (bool, i32)
| | keys = ()

%2 =
| Union %0 %1
| | types = (bool, i32)
| | keys = ()

%3 =
| Join %2 (= #0 true) (= #0 #1)
| | implementation = Unimplemented
| | demand = (#0, #0)
| | types = (bool, i32)
| | keys = ()
| Project (#0, #0)
| | types = (bool, bool)
| | keys = ()
', src/transform/src/demand.rs:303:13
```

**Comment by benesch** [comment]
Erm, well, maybe not. Somehow we're getting a join that lists a bool and int column as equivalent.

**Comment by benesch** [comment]
Ok, the root cause is the new redundant join transformation. It tries to eliminate a redundant join but doesn't fix up column references correctly.

```
before:
%0 =
| Get ? (u4)
| | types = (i32)
| | keys = ()
| Map 1
| | types = (i32, i32)
| | keys = ()
| Project (#1)
| | types = (i32)
| | keys = ()
| Threshold
| | types = (i32)
| | keys = ()

%1 =
| Get %0
| | types = (i32)
| | keys = ()

%2 =
| Get %1
| | types = (i32)
| | keys = ()
| Map true, "foo"
| | types = (i32, bool, string)
| | keys = ()
| Project (#2, #1, #0)
| | types = (string, bool, i32)
| | keys = ()

%3 =
| Get %1
| | types = (i32)
| | keys = ()
| Negate
| | types = (i32)
| | keys = ()
| Map true, "foo", true, 1
| | types = (i32, bool, string, bool, i32)
| | keys = ()
| Project (#3, #4)
| | types = (bool, i32)
| | keys = ()

%4 =
| Get %0
| | types = (i32)
| | keys = ()
| Map true, true, 1
| | types = (i32, bool, bool, i32)
| | keys = ()
| Project (#2, #3)
| | types = (bool, i32)
| | keys = ()

%5 =
| Union %3 %4
| | types = (bool, i32)
| | keys = ()

%6 =
| Get %0
| | types = (i32)
| | keys = ()

%7 =
| Join %5 %6 (= #0 true) (= #1 #2)
| | implementation = Unimplemented
| | types = (bool, i32, i32)
| | keys = ()
| Map true
| | types = (bool, i32, i32, bool)
| | keys = ()
| Project (#0..#3)
| | types = (bool, i32, i32, bool)
| | keys = ()
| Map null
| | types = (bool, i32, i32, bool, string?)
| | keys = ()
| Project (#4, #0, #1)
| | types = (string?, bool, i32)
| | keys = ()

%8 =
| Union %2 %7
| | types = (string?, bool, i32)
| | keys = ()

after:
%0 =
| Get ? (u4)
| | types = (i32)
| | keys = ()
| Map 1
| | types = (i32, i32)
| | keys = ()
| Project (#1)
| | types = (i32)
| | keys = ()
| Threshold
| | types = (i32)
| | keys = ()

%1 =
| Get %0
| | types = (i32)
| | keys = ()

%2 =
| Get %1
| | types = (i32)
| | keys = ()
| Map true, "foo"
| | types = (i32, bool, string)
| | keys = ()
| Project (#2, #1, #0)
| | types = (string, bool, i32)
| | keys = ()

%3 =
| Get %1
| | types = (i32)
| | keys = ()
| Negate
| | types = (i32)
| | keys = ()
| Map true, "foo", true, 1
| | types = (i32, bool, string, bool, i32)
| | keys = ()
| Project (#3, #4)
| | types = (bool, i32)
| | keys = ()

%4 =
| Get %0
| | types = (i32)
| | keys = ()
| Map true, true, 1
| | types = (i32, bool, bool, i32)
| | keys = ()
| Project (#2, #3)
| | types = (bool, i32)
| | keys = ()

%5 =
| Union %3 %4
| | types = (bool, i32)
| | keys = ()

%6 =
| Join %5 (= #0 true) (= #0 #1)
| | implementation = Unimplemented
| | types = (bool, i32)
| | keys = ()
| Project (#0, #1, #0)
| | types = (bool, i32, bool)
| | keys = ()
| Map true
| | types = (bool, i32, bool, bool)
| | keys = ()
| Project (#0..#3)
| | types = (bool, i32, bool, bool)
| | keys = ()
| Map null
| | types = (bool, i32, bool, bool, string?)
| | keys = ()
| Project (#4, #0, #1)
| | types = (string?, bool, i32)
| | keys = ()

%7 =
| Union %2 %6
| | types = (string?, bool, i32)
| | keys = ()
```

Notice how `Join %5 %6` looks correct (it equates two int columns at least) in the before plan, but equates an int and a bool column in the after plan.
