### ISSUE TITLE
mzconduct failure message when attempting to build new services is confusing

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#5020]
`mzconduct` / `mzcompose` ignore files that git doesn't know about and then print a very confusing
error message when they cannot find a service specified by `mzbuild`. A service which they are
ignoring.

When adding new services, my typical workflow is to create the directory for the service, add an
`mzbuild.yml`, `Dockerfile`, source code and then test create the image by running: `docker build
-f Dockerfile .`.

If the image builds cleanly, I then go and add this service to my `mzcompose.yml` file. For
example:

```
services:
+  create-views:
+    mzbuild: wikirecent-create-views
```

When I go to run `mzconduct`, I get the following error message:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/chris/materialize/materialize/misc/python/materialize/cli/mzcompose.py", line 200, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/chris/materialize/materialize/misc/python/materialize/cli/mzcompose.py", line 68, in main
    composes.append(build_compose_file(repo, args.command, config_file))
  File "/home/chris/materialize/materialize/misc/python/materialize/cli/mzcompose.py", line 124, in build_compose_file
    say(d.spec())
  File "/home/chris/materialize/materialize/misc/python/materialize/mzbuild.py", line 426, in spec
    return self.image.docker_name(f"mzbuild-{self.fingerprint()}")
  File "/home/chris/materialize/materialize/misc/python/materialize/mzbuild.py", line 565, in fingerprint
    with open(abs_path, "rb") as f:
IsADirectoryError: [Errno 21] Is a directory: '/home/chris/materialize/materialize/test/sqllogictest/sqlite'
```

One solution is to run `git add` on the service that I just created. It would be nice, however, if
this error message were a little more helpful.

**Comment by cirego** [comment]
@quodlibetor thoughts?

**Comment by cirego** [comment]
Ran into this again today. 😢

**Comment by cirego** [comment]
Looking at my checkout, `sqlite` is an empty directory. There are no files, not even hidden files, which means it must be a submodule. Running `git submodule update --init --recursive` results in that directory now having files. However, I'm still seeing the same error.

I added some debugging commands and we don't attempt to fingerprint the `sqllogictest/sqlite` directory when the service's `mzbuild.yml` file has been added to `git`. So why is it trying to fingerprint this directory when the `mzbuild.yml` file cannot be found? Perhaps when the `mzbuild` file cannot be found, it's defaulting to checking all files in the repo?

**Comment by cirego** [comment]
Yes, it would appear that this function is the culprit:

````
        for rel_path in sorted(
            set(git.expand_globs(self.image.rd.root, *self.inputs()))
        ): 
````

What if `self.inputs` is empty? It looks like this can happen because `inputs` is generated by doing `set(git.expand_globs(self.image.rd.root, f"{self.image.path}/**"))`.  Well, `self.image.path` is a directory that `git` doesn't know about. What does `expand_globs` do in that case?

It runs the following command, which returns nothing:

```
git diff --name-only -z 4b825dc642cb6eb9a060e54bf8d69288fbee4904 -- /home/chris/materialize/materialize/play/wikirecent/create_views2/**
```

So what's the correct behavior? Emit a warning that the directory needs to be added to git? I'm not sure that this is sufficient, as there are still files that can end up ignored by accident. For example, consider the case where I add a new directory to an existing service, with files in the directory that should be built into my container. While the rebuild will be triggered each time I change the Dockerfile, the rebuild will not be triggered when I change files in the scripts -- at least, not until I `git add` those files.
