### ISSUE TITLE
slt: crash when `SELECT $1`

### ISSUE THREAD

**Issue by sploiselle** [MaterializeInc/materialize#5071]
When running queries through `slt`, encountering a crash on:

```sql
SELECT $1
```

```
thread 'main' panicked at 'expected 1 parameters but got 0', /home/sean/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-postgres-0.5.5/src/query.rs:142:5
stack backtrace:
   0:     0x56151e2ee5c0 - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x56151e2ee5c0 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x56151e2ee5c0 - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x56151e2ee5c0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x56151e315e3c - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x56151e2e5f22 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x56151e2f0b7d - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x56151e2f0b7d - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x56151e2f0b7d - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x56151e2f0828 - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x56151de7e386 - <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call::habb299e010149c17
                               at /home/sean/.rustup/toolchains/1.48.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1056
  11:     0x56151de7e31f - ore::panic::set_abort_on_panic::{{closure}}::hfdf1c222841e0292
                               at /home/sean/github/sploiselle/materialize/src/ore/src/panic.rs:35
  12:     0x56151e2f1286 - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:581
  13:     0x56151e2f0e09 - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  14:     0x56151e2eea2c - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  15:     0x56151e2f0dc9 - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  16:     0x56151e2f0d7b - std::panicking::begin_panic_fmt::hf0503558fbe5b251
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
  17:     0x56151dd0485f - tokio_postgres::query::encode_bind::hbff4878d72589d98
                               at /home/sean/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-postgres-0.5.5/src/query.rs:142
  18:     0x56151dd03a89 - tokio_postgres::query::encode::{{closure}}::h8da32317198e2bdb
                               at /home/sean/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-postgres-0.5.5/src/query.rs:123
  19:     0x56151dd14be6 - tokio_postgres::client::InnerClient::with_buf::h85ef52b24b157583
                               at /home/sean/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-postgres-0.5.5/src/client.rs:120
  20:     0x56151dd03a1f - tokio_postgres::query::encode::h83a4404ee92ccb4a
                               at /home/sean/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-postgres-0.5.5/src/query.rs:122
  21:     0x56151dd025e9 - tokio_postgres::query::query::{{closure}}::h9ac6b035bcfee22a
                               at /home/sean/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-postgres-0.5.5/src/query.rs:34
  22:     0x56151dcef5b4 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::haf14539c58521b64
                               at /home/sean/.rustup/toolchains/1.48.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80
  23:     0x561519e10fdd - tokio_postgres::client::Client::query_raw::{{closure}}::hbaaf694494dddc97
                               at /home/sean/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-postgres-0.5.5/src/client.rs:352
  24:     0x56151a084372 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hcbd2a9d775722457
                               at /home/sean/.rustup/toolchains/1.48.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80
  25:     0x561519e10232 - tokio_postgres::client::Client::query::{{closure}}::h2a932397357e069e
                               at /home/sean/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-postgres-0.5.5/src/client.rs:223
  26:     0x56151a07f17a - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h1bd912b392baf64b
                               at /home/sean/.rustup/toolchains/1.48.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80
  27:     0x56151a952234 - sqllogictest::runner::Runner::run_query::{{closure}}::ha28592c80d4161ee
                               at /home/sean/github/sploiselle/materialize/src/sqllogictest/src/runner.rs:663
  28:     0x56151a085712 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf9d778cabb8148b5
                               at /home/sean/.rustup/toolchains/1.48.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80
  29:     0x56151a94f2a1 - sqllogictest::runner::Runner::run_record::{{closure}}::he905af8b67fbb106
                               at /home/sean/github/sploiselle/materialize/src/sqllogictest/src/runner.rs:571
  30:     0x56151a0830a2 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h9b38ec7a784e3a4e
                               at /home/sean/.rustup/toolchains/1.48.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80
  31:     0x56151a94b22e - sqllogictest::runner::run_string::{{closure}}::h3ad4bf7933134d88
                               at /home/sean/github/sploiselle/materialize/src/sqllogictest/src/runner.rs:822
  32:     0x56151a0845b2 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd02e3247cfc056ca
                               at /home/sean/.rustup/toolchains/1.48.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80
  33:     0x56151a954e30 - sqllogictest::runner::run_file::{{closure}}::h80e40d09a1baaa43
                               at /home/sean/github/sploiselle/materialize/src/sqllogictest/src/runner.rs:855
  34:     0x56151a0822c2 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h7f92242aa43e0f0a
                               at /home/sean/.rustup/toolchains/1.48.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80
  35:     0x56151b352001 - sqllogictest::main::{{closure}}::h41540e8af60f047f
                               at /home/sean/github/sploiselle/materialize/src/sqllogictest/src/main.rs:100
  36:     0x56151a083619 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha9e24eb4cf8c2660
                               at /home/sean/.rustup/toolchains/1.48.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80
  37:     0x56151a8f3863 - tokio::runtime::enter::Enter::block_on::{{closure}}::hc9df9e3b9884ff55
                               at /home/sean/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/enter.rs:160
  38:     0x56151b726006 - tokio::coop::with_budget::{{closure}}::h47c209d82bae4487
                               at /home/sean/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:127
  39:     0x56151a2a7fd1 - std::thread::local::LocalKey<T>::try_with::h4f592019d52906c2
                               at /home/sean/.rustup/toolchains/1.48.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272
  40:     0x56151a2a57ed - std::thread::local::LocalKey<T>::with::hd0b3faa727144ece
                               at /home/sean/.rustup/toolchains/1.48.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248
  41:     0x56151a8f321a - tokio::coop::with_budget::h9f7bed517460c602
                               at /home/sean/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:120
  42:     0x56151a8f321a - tokio::coop::budget::hb0291bfc313cb183
                               at /home/sean/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:96
  43:     0x56151a8f321a - tokio::runtime::enter::Enter::block_on::h1fbfbe8b21822480
                               at /home/sean/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/enter.rs:160
  44:     0x56151b70c205 - tokio::runtime::thread_pool::ThreadPool::block_on::h04b652b195e82d28
                               at /home/sean/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/thread_pool/mod.rs:82
  45:     0x56151a7f054f - tokio::runtime::Runtime::block_on::{{closure}}::hc3c120fb0dea4445
                               at /home/sean/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:446
  46:     0x56151ab3a53d - tokio::runtime::context::enter::h338e2b798d3c4b12
                               at /home/sean/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/context.rs:72
  47:     0x56151b023bf1 - tokio::runtime::handle::Handle::enter::h64225d43977954f7
                               at /home/sean/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/handle.rs:76
  48:     0x56151a7f04b1 - tokio::runtime::Runtime::block_on::h9f6fd6e7e5ed3545
                               at /home/sean/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:441
  49:     0x56151abe99c0 - sqllogictest::main::h72185bcbec3f3bec
                               at /home/sean/github/sploiselle/materialize/src/sqllogictest/src/main.rs:25
  50:     0x56151b1693fb - core::ops::function::FnOnce::call_once::h1e3fe705d785d2dc
                               at /home/sean/.rustup/toolchains/1.48.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
  51:     0x561519d443ae - std::sys_common::backtrace::__rust_begin_short_backtrace::hf1f39fa2b2c985e2
                               at /home/sean/.rustup/toolchains/1.48.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137
  52:     0x56151a66de71 - std::rt::lang_start::{{closure}}::ha67db01eafba19b3
                               at /home/sean/.rustup/toolchains/1.48.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66
  53:     0x56151e2f1777 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::he179d32a5d10d957
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:259
  54:     0x56151e2f1777 - std::panicking::try::do_call::hcb3d5e7be089b2b4
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:381
  55:     0x56151e2f1777 - std::panicking::try::h7ac93b0cd56fb701
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:345
  56:     0x56151e2f1777 - std::panic::catch_unwind::h7b40e396c93a4fcd
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382
  57:     0x56151e2f1777 - std::rt::lang_start_internal::h142b9cc66267fea1
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:51
  58:     0x56151a66de47 - std::rt::lang_start::h9ed63cd6403c04c1
                               at /home/sean/.rustup/toolchains/1.48.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65
  59:     0x56151abe9a3a - main
  60:     0x7f10d86f70b3 - __libc_start_main
  61:     0x5615198e004e - _start
  62:                0x0 - <unknown>
```

**Comment by benesch** [comment]
So we can make this not a crash, but there isn't any way in the SLT format to actually bind the parameter to anything.

**Comment by sploiselle** [comment]
My actual usecase is:

```sql
SELECT pg_typeof($1::int)
```

just to show that the parameter was properly typed, even if the value doesn't exist.

Really nbd, but figured avoiding a crash was preferable because there is at least one `slt` test that uses a "naked" param like this (`typeof.slt`), making it look like my usecase should be valid input.

**Comment by benesch** [comment]
Yeah, that other test case only works by accident because the query returns an error. If that query didn't return an error, then actually trying to _execute_ it would fail (as it does in your example). I'd say just hang tight until we get SQL-level `PREPARE` and `EXECUTE` working.

**Comment by benesch** [comment]
That's https://github.com/MaterializeInc/materialize/issues/3383, for context. We're actually well equipped to support that, now that @mjibson has laid some similar groundwork for `DECLARE` and `FETCH`. @JLDLaughlin would you have any interest in working on that?
