### ISSUE TITLE
0.6.0-rc1 Chaos Tests failed due to Operation Timeout

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#5083]
The chaos tests failed due to inability to locate the `kafka` host:
```

[2020-12-15T17:10:18Z ERROR rdkafka::client] librdkafka: Global error: Resolve (Local: Host resolution failure): kafka:9092/bootstrap: Failed to resolve 'kafka:9092': Name or service not known (after 1ms in state CONNECT, 20identical error(s) suppressed)
[2020-12-15T17:10:19Z ERROR rdkafka::client] librdkafka: FAIL [thrd:kafka:9092/bootstrap]: kafka:9092/bootstrap: Failed to resolve 'kafka:9092': Name or service not known (after 1ms in state CONNECT, 1 identical error(s) suppressed)
ERROR: Error {
    context: "creating Kafka topic: chaos-2645170932",
    source: Kafka(
        KafkaError (Admin operation error: OperationTimedOut (Local: Timed out)),
    ),
}
```

Debugging terminal [here](https://tsh.i.mtrlz.dev/web/cluster/tsh/console/session/4d2f9645-40af-11eb-939e-02037be10c56)

**Comment by cirego** [comment]
Kafka also died, with the following error:

```
[main-SendThread(zookeeper:2181)] WARN org.apache.zookeeper.ClientCnxn - Session 0x0 for server zookeeper:2181, unexpected error, closing socket connection and attempting reconnect
java.lang.IllegalArgumentException: Unable to canonicalize address zookeeper:2181 because it's not resolvable
        at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:65)
        at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:41)
        at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1001)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060)
[main-SendThread(zookeeper:2181)] WARN org.apache.zookeeper.ClientCnxn - Session 0x0 for server zookeeper:2181, unexpected error, closing socket connection and attempting reconnect
java.lang.IllegalArgumentException: Unable to canonicalize address zookeeper:2181 because it's not resolvable
        at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:65)
        at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:41)
        at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1001)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060)
[main-SendThread(zookeeper:2181)] WARN org.apache.zookeeper.ClientCnxn - Session 0x0 for server zookeeper:2181, unexpected error, closing socket connection and attempting reconnect
java.lang.IllegalArgumentException: Unable to canonicalize address zookeeper:2181 because it's not resolvable
        at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:65)
        at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:41)
        at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1001)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060)
[main-SendThread(zookeeper:2181)] WARN org.apache.zookeeper.ClientCnxn - Session 0x0 for server zookeeper:2181, unexpected error, closing socket connection and attempting reconnect
```

**Comment by quodlibetor** [comment]
it looks like these errors all happened on the kafka producer side, not inside materialized?

**Comment by cirego** [comment]
The `creating kafka topic` error message came from the `chaos` container. The `zookeeper` messages are from Kafka.

**Comment by cirego** [comment]
@JLDLaughlin, this reproduced if you want to debug this. Materialized appears to be fine, but Kafka and Zookeeper are unhappy.

**Comment by JLDLaughlin** [comment]
Manually tearing the test down and restarting it in teleport does not result in the same error (it's running successfully now). Is it possible that there is an issue with how terraform/etc is bringing it up?

**Comment by cirego** [comment]
Sounds like a bit of good news and bad news then? We should be clear to release but we need to fix the flaky test.

**Comment by quodlibetor** [comment]
The logs on bootup (`/var/log/cloud-init-output.log`) have a small set of error-level logs:

```console
$ grep -o 'ERROR.*' kafka.log | sort -u
ERROR Caught InterruptedException during metrics collection (io.confluent.support.metrics.BaseMetricsReporter)
ERROR Interrupted the wait for leader to be elected after creating topic=__confluent.support.metrics (io.confluent.support.metrics.common.kafka.KafkaUtilities)
ERROR [KafkaApi-1] Number of alive brokers '0' does not meet the required replication factor '1' for the offsets topic (configured via 'offsets.topic.replication.factor'). This error can be ignored if the cluster is starting up and not all brokers are up yet. (kafka.server.KafkaApis)
```

That doesn't tell me anything, though.

**Comment by cirego** [comment]
The test passed after being restarted.

**Comment by cirego** [comment]
Should we close this issue for now? Have we seen this again?

**Comment by benesch** [comment]
Stale.
