### ISSUE TITLE
mzcompose error when waiting on chbench service

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#5215]
After merging `mzconduct` and `mzcompose`, the `WaitStep` workflow yields the following error:

```
C> Wait for the specified service to exit
$ ps -q chbench
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/brennan/code/materialize/misc/python/materialize/cli/mzcompose.py", line 203, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/brennan/code/materialize/misc/python/materialize/cli/mzcompose.py", line 112, in main
    workflow.run()
  File "/home/brennan/code/materialize/misc/python/materialize/mzcompose.py", line 338, in run
    step.run(self)
  File "/home/brennan/code/materialize/misc/python/materialize/mzcompose.py", line 974, in run
    sub_workflow.run()
  File "/home/brennan/code/materialize/misc/python/materialize/mzcompose.py", line 338, in run
    step.run(self)
  File "/home/brennan/code/materialize/misc/python/materialize/mzcompose.py", line 1088, in run
    ps_proc = spawn.runv(ps_cmd, capture_output=True)
  File "/home/brennan/code/materialize/misc/python/materialize/spawn.py", line 65, in runv
    return subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ps', '-q', 'chbench']' returned non-zero exit status 1.
```

This is because the `docker` command was removed from the cmd. Before:

```python
def mzcompose_wait(
    mzcompose_file: Path, service: str, expected_return_code: int
) -> None:
    ps_cmd = [
        "bin/mzcompose",
        "--mz-quiet",
        "-f",
        str(mzcompose_file),
        "ps",
        "-q",
        service,
    ]
```

After:

```python
    def run(self, workflow: Workflow) -> None:
        say("Wait for the specified service to exit")
        ps_cmd = [
            "ps",
            "-q",
            self._service,
        ]
```

**Comment by benesch** [comment]
Looks like https://github.com/MaterializeInc/materialize/blob/90ec3fea9cf7efd7743024a9f4aa4254110476e4/misc/python/materialize/mzcompose.py#L1088 should use `workflow.run` rather than `spawn.runv`.

**Comment by cirego** [comment]
> Looks like
> 
> https://github.com/MaterializeInc/materialize/blob/90ec3fea9cf7efd7743024a9f4aa4254110476e4/misc/python/materialize/mzcompose.py#L1088
> 
> should use `workflow.run` rather than `spawn.runv`.

Yep! I've got a PR on the way.
