### ISSUE TITLE
Within chbench ingest benchmark, restore kafka from a directory snapshot

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#5456]
Instead of writing code to snapshot / restore topics manually, let's try snapshotting the Kafka data directly.

I have the basic code working but I'm running into the following:

```
[2021-01-25 22:46:12,887] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka.common.InconsistentClusterIdException: The Cluster ID qEu6ZRi8TYyq7rSstvCosQ doesn't match stored clusterId Some(Mid6BRU9QPy6cdjj9xmpSA) in meta.properties. The broker is trying to join the wrong cluster. Configured zookeeper.connect may be wrong.
        at kafka.server.KafkaServer.startup(KafkaServer.scala:244)
        at io.confluent.support.metrics.SupportedServerStartable.startup(SupportedServerStartable.java:114)
        at io.confluent.support.metrics.SupportedKafka.main(SupportedKafka.java:66)
```

**Comment by cirego** [comment]
Perhaps I need to snapshot zookeeper too....

**Comment by cirego** [comment]
Yep, adding zookeeper solved this. Looks like we have something workable!

Here are the directory sizes before we do any compression:

```
[chris-work:~/materialize/benchmark_data/chbench/5] du -ch -d 1
168K    ./zookeeper-logs
12K     ./zookeeper-data
2.4G    ./kafka-data
2.4G    .
2.4G    total
```

Let's see how well / not well they compress. It appears that compression reduces the file size by quite a bit:

```
-rw-rw-r--   1 chris chris 898M Jan 25 15:23 kafka-data.tgz
-rw-rw-r--   1 chris chris  93K Jan 25 15:24 zookeeper-logs.tgz
drwxrwxr-x   5 chris chris 4.0K Jan 25 15:24 ./
-rw-rw-r--   1 chris chris  294 Jan 25 15:24 zookeeper-data.tgz
```

**Comment by cirego** [comment]
I am, however, slightly worried about overall file size if we choose to compress these directories. `s3 sync` may timeout if the tarfile gets to be too big, but let's keep the compression for now.
