### ISSUE TITLE
Load test instances cannot install psutil utility

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#5732]
When trying to install the requirements for `mzbench`, load test instances fail with the following
error message:

```
Command "/home/ubuntu/materialize/misc/python/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-wccf07wv/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-l_kycd6o-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/ubuntu/materialize/misc/python/venv/include/site/python3.6/psutil" failed with error code 1 in /tmp/pip-build-wccf07wv/psutil/
==> Checking for existing virtualenv
no existing virtualenv detected
==> Initializing virtualenv in /home/ubuntu/materialize/misc/python/venv
==> Updating dependencies with pip
==> Updating dev dependencies with pip
Traceback (most recent call last):
  File "/home/ubuntu/materialize/bin/pyactivate", line 162, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/ubuntu/materialize/bin/pyactivate", line 56, in main
    python = str(activate_venv(py_dir, dev))
  File "/home/ubuntu/materialize/bin/pyactivate", line 123, in activate_venv
    acquire_deps(venv_dir, "dev")
  File "/home/ubuntu/materialize/bin/pyactivate", line 156, in acquire_deps
    "--disable-pip-version-check",
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[PosixPath('/home/ubuntu/materialize/misc/python/venv/bin/pip'), 'install', '-r', PosixPath('/home/ubuntu/materialize/misc/python/requirements-dev.txt'), '--disable-pip-version-check']' returned non-zero exit status 1.
```

**Comment by cirego** [comment]
Marking this WONTFIX.
