### ISSUE TITLE
Debezium: Schema incompatibilities cause replication to stop, no error is reported on the Materialize side

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#6570]
### What version of Materialize are you using?

```
b31cf1537657f83e390a6e15ab42b15b62212115
```

### What was the issue?

If a DDL is issued on the Postgres side that causes a schema incompatibility, Debezium will stop replication with an error in the log.

Replication will stop and no error will be reported on the Materialize side. Either the source should start reporting the error or we need to extend our Debezium documentation with explicit advice to users to monitor their Debezium instance for any replication errors.

The log looks like this:

```
2021-04-26 12:09:57,604 ERROR  ||  WorkerSourceTask{id=psql-connector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted   [org.apache.kafka.connect.runtime.WorkerTask]
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:206)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:132)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.convertTransformedRecord(WorkerSourceTask.java:314)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:340)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:264)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.common.config.ConfigException: Invalid value org.apache.kafka.common.errors.InvalidConfigurationException: Schema being registered is incompatible with an earlier schema; error code: 409 for configuration Failed to access Avro data from topic postgres.public.alter_remove_nullability :
	at io.confluent.connect.avro.AvroConverter.fromConnectData(AvroConverter.java:98)
	at org.apache.kafka.connect.storage.Converter.fromConnectData(Converter.java:63)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.lambda$convertTransformedRecord$2(WorkerSourceTask.java:314)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)
	... 11 more
2021-04-26 12:09:57,605 INFO   ||  Stopping down connector   [io.debezium.connector.common.BaseSourceTask]
```

### Is the issue reproducible? If so, please provide reproduction instructions.

Here is an example of a schema-incompatible change:

```
$ postgres-execute connection=postgres://postgres:postgres@postgres
CREATE TABLE alter_remove_nullability (f1 INTEGER);
ALTER TABLE alter_remove_nullability REPLICA IDENTITY FULL;
INSERT INTO alter_remove_nullability VALUES (123),(234);

> CREATE MATERIALIZED SOURCE alter_remove_nullability
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'postgres.public.alter_remove_nullability'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
  ENVELOPE DEBEZIUM;

> SELECT * FROM alter_remove_nullability;
123
234

$ postgres-execute connection=postgres://postgres:postgres@postgres
ALTER TABLE alter_remove_nullability ALTER COLUMN f1 SET NOT NULL;
INSERT INTO alter_remove_nullability VALUES (345);
```

**Comment by cirego** [comment]
Are there any indicators in the Kafka topics that Debezium has stopped replicating? I fear that this may be extremely difficult to detect from the Materialize side.

**Comment by philip-stoev** [comment]
There is a REST API that provides the status of each worker. There is also the ```connect_statuses``` topic that provides messages about issues:

```
{"state":"FAILED","trace":"org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler\n\tat org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:206)\n\tat org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:132)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.convertTransformedRecord(WorkerSourceTask.java:314)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:340)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:264)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\nCaused by: org.apache.kafka.common.config.ConfigException: Invalid value org.apache.kafka.common.errors.InvalidConfigurationException: Schema being registered is incompatible with an earlier schema; error code: 409 for configuration Failed to access Avro data from topic postgres.public.alter_add_primary_key :\n\tat io.confluent.connect.avro.AvroConverter.fromConnectData(AvroConverter.java:98)\n\tat org.apache.kafka.connect.storage.Converter.fromConnectData(Converter.java:63)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.lambda$convertTransformedRecord$2(WorkerSourceTask.java:314)\n\tat org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)\n\tat org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)\n\t... 11 more\n","worker_id":"192.168.128.7:8083","generation":3}
```

**Comment by cirego** [comment]
> There is a REST API that provides the status of each worker. There is also the `connect_statuses` topic that provides messages about issues:
> 
> ```
> {"state":"FAILED","trace":"org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler\n\tat org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:206)\n\tat org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:132)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.convertTransformedRecord(WorkerSourceTask.java:314)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:340)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:264)\n\tat org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)\n\tat org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\nCaused by: org.apache.kafka.common.config.ConfigException: Invalid value org.apache.kafka.common.errors.InvalidConfigurationException: Schema being registered is incompatible with an earlier schema; error code: 409 for configuration Failed to access Avro data from topic postgres.public.alter_add_primary_key :\n\tat io.confluent.connect.avro.AvroConverter.fromConnectData(AvroConverter.java:98)\n\tat org.apache.kafka.connect.storage.Converter.fromConnectData(Converter.java:63)\n\tat org.apache.kafka.connect.runtime.WorkerSourceTask.lambda$convertTransformedRecord$2(WorkerSourceTask.java:314)\n\tat org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)\n\tat org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)\n\t... 11 more\n","worker_id":"192.168.128.7:8083","generation":3}
> ```

Excellent! `connect_statuses` topic is probably the one that we want to read!

**Comment by umanwizard** [comment]
@petrosagg do you think this is fixable?

**Comment by petrosagg** [comment]
I haven't used debezium a lot so I'm only speaking from what I understood from the documentation and it doesn't look like it's fixable. The raw replication stream from pg does provide separate events that notify the client that the schema changed but these are not propagated to Kafka.

The direct postgres source will not have this problem once we process these messages (currently they are ignored)

**Comment by cirego** [comment]
I think this issue is another example for why `Debezium` needs to be a distinct source type, similar to Postgres replication. If we could mark a source as coming from Debezium, we could have the source enter an error state when there are failures in the `connect_statuses` topic.

**Comment by umanwizard** [comment]
Whoops, sorry @petrosagg , I missed that this is specific to Debezium

**Comment by umanwizard** [comment]
@philip-stoev is there an upstream issue to Debezium?

**Comment by philip-stoev** [comment]
@umanwizard I do not think Debezium will agree there is an issue on their side. Basically when they attempt to register the new schema with the schema registry, the schema registry responds with "Schema being registered is incompatible with an earlier schema;". Debezium then would do what we would do if we are faced with a schema incompatibility issue: it puts the connector in an error state pending user intervention.

It is just that we need to be doing the same -- put the source in an error state as well.

**Comment by umanwizard** [comment]
Ok, got it. It doesn't seem from the stanza you posted that the `connect_statuses` topic gives any information about which topic had the error, so I'm not sure how actionable the information it gives us is. Of course, we could put _every_ source in an error state, but that seems a bit extreme ...

**Comment by cirego** [comment]
> Ok, got it. It doesn't seem from the stanza you posted that the `connect_statuses` topic gives any information about which topic had the error, so I'm not sure how actionable the information it gives us is. Of course, we could put _every_ source in an error state, but that seems a bit extreme ...

It does appear that the error message lacks the "collection" affected. It does seem like we would need to error every source using that Debezium connector (and this is part of my motivation for why I think we should have a Debezium source type that looks similar to the new postgres source type).

**Comment by philip-stoev** [comment]
Will open an upstream ticket with Debezium requesting that extra identifiers are made available. The message as is currently available has a worker_id which I guess can somehow be correlated to a particular source via a series of hoops (not sure if we would want to inflict all that additional complexity upon ourselves  though)

**Comment by philip-stoev** [comment]
There is also a "heartbeat" topic that we could monitor to determine if an error has happened on the Debezium side:

> heartbeat.interval.ms | 0 | Controls how frequently heartbeat messages are sent.This property contains an interval in milliseconds that defines how frequently the connector sends messages to a heartbeat topic. The property can be used to confirm whether the connector is still receiving change events from the database. You also should leverage heartbeat messages in cases where only records in non-captured tables are changed for a longer period of time. In such situation the connector would proceed to read the log from the database but never emit any change messages into Kafka, which in turn means that no offset updates are committed to Kafka. This may result in more change events to be re-sent after a connector restart. Set this parameter to 0 to not send heartbeat messages at all.Disabled by default.
-- | -- | --



```
