### ISSUE TITLE
Benchmark data generator exits with code 0 even if kgen threads panic

### ISSUE THREAD

**Issue by cirego** [MaterializeInc/materialize#6642]
I was making a new benchmark and made a mistake in how I named something. The benchmark just hung,
with Materialize giving an error about a column not existing. This struck me as odd and I curious
to see what data had been generated. That's when I looked at the logs for the aggregations
generator and noticed that the threads had panicked:

```sh
[chris-work:~/materialize/materialize:(aggregations-benchmark[|]*)] docker logs aggregations_generator_run_492698a65e15
Spawning 8 generator processes, writing 2500000 messages each
thread 'main' panicked at 'Distribution annotation not found: com.acme.avro.aggregationtestvalue::Key1Unused', src/kafka-util/src/bin/kgen.rs:292:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Distribution annotation not found: com.acme.avro.aggregationtestvalue::Key1Unused', src/kafka-util/src/bin/kgen.rs:292:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
0/8 processes finished: pid=7 returncode=101
thread 'main' panicked at 'Distribution annotation not found: com.acme.avro.aggregationtestvalue::Key1Unused', src/kafka-util/src/bin/kgen.rs:292:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Distribution annotation not found: com.acme.avro.aggregationtestvalue::Key1Unused', src/kafka-util/src/bin/kgen.rs:292:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
1/8 processes finished: pid=8 returncode=101
thread 'main' panicked at 'Distribution annotation not found: com.acme.avro.aggregationtestvalue::Key1Unused', src/kafka-util/src/bin/kgen.rs:292:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2/8 processes finished: pid=9 returncode=101
thread 'main' panicked at 'Distribution annotation not found: com.acme.avro.aggregationtestvalue::Key1Unused', src/kafka-util/src/bin/kgen.rs:292:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
3/8 processes finished: pid=10 returncode=101
4/8 processes finished: pid=11 returncode=101
5/8 processes finished: pid=36 returncode=101
thread 'main' panicked at 'Distribution annotation not found: com.acme.avro.aggregationtestvalue::Key1Unused', src/kafka-util/src/bin/kgen.rs:292:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Distribution annotation not found: com.acme.avro.aggregationtestvalue::Key1Unused', src/kafka-util/src/bin/kgen.rs:292:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
6/8 processes finished: pid=114 returncode=101
7/8 processes finished: pid=184 returncode=101
```

However, when I ran `docker inspect`, that container had exited with code `0`. It should have
exited with error so that benchmark setup would have failed.

**Comment by cirego** [comment]
Fixed by #6675
