### ISSUE TITLE
multi-row insert of mixed data fails with "invalid input syntax for type integer"

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#7360]
### What version of Materialize are you using?

```
v0.8.3-dev (1c396ba53)
```

### What was the issue?

Combining quoted and unquoted numbers in the same multi-row INSERT statement causes an error in Materialize, but is accepted by Postgres. The error given is

```invalid input syntax for type integer: invalid digit```

which seems to indicate that the code expects that all parts of the insert will have the same literal type and that literal type is decided to be integer even when decimal strings are present

### Is the issue reproducible? If so, please provide reproduction instructions.
```
CREATE TABLE decimal_zero (f1 DECIMAL);
INSERT INTO decimal_zero VALUES ('0.0'), (0);
ERROR:  invalid input syntax for type integer: invalid digit found in string: "0.0"
```

**Comment by antiguru** [comment]
gdb bt:
```
#0  core::str::{{impl}}::trim ()
    at /home/moritz/.rustup/toolchains/1.51.0-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/str/mod.rs:1727
#1  repr::strconv::parse_int32 () at /home/moritz/dev/repos/materialize/src/repr/src/strconv.rs:106
#2  0x0000555557af0809 in expr::scalar::func::cast_string_to_int32 () at /home/moritz/dev/repos/materialize/src/expr/src/scalar/func.rs:469
#3  expr::scalar::func::UnaryFunc::eval () at /home/moritz/dev/repos/materialize/src/expr/src/scalar/func.rs:3827
#4  0x0000555557b9aa14 in expr::scalar::MirScalarExpr::eval () at /home/moritz/dev/repos/materialize/src/expr/src/scalar/mod.rs:833
#5  0x0000555557b8dafc in expr::scalar::{{impl}}::reduce::{{closure}} () at /home/moritz/dev/repos/materialize/src/expr/src/scalar/mod.rs:318
#6  expr::scalar::{{impl}}::reduce::{{closure}} () at /home/moritz/dev/repos/materialize/src/expr/src/scalar/mod.rs:331
#7  0x0000555557b8d8ba in expr::scalar::MirScalarExpr::reduce () at /home/moritz/dev/repos/materialize/src/expr/src/scalar/mod.rs:325
#8  0x0000555556095c36 in transform::reduction::FoldConstants::action ()
    at /home/moritz/dev/repos/materialize/src/transform/src/reduction.rs:116
#9  0x00005555560a055a in transform::reduction::{{impl}}::transform::{{closure}} ()
    at /home/moritz/dev/repos/materialize/src/transform/src/reduction.rs:30
#10 expr::relation::MirRelationExpr::try_visit_mut<closure-0,transform::TransformError> ()
    at /home/moritz/dev/repos/materialize/src/expr/src/relation/mod.rs:1078
#11 0x00005555560a051e in expr::relation::{{impl}}::try_visit_mut::{{closure}}<closure-0,transform::TransformError> ()
    at /home/moritz/dev/repos/materialize/src/expr/src/relation/mod.rs:1077
#12 expr::relation::MirRelationExpr::try_visit1_mut<closure-0,transform::TransformError> ()
    at /home/moritz/dev/repos/materialize/src/expr/src/relation/mod.rs:1047
#13 expr::relation::MirRelationExpr::try_visit_mut<closure-0,transform::TransformError> ()
    at /home/moritz/dev/repos/materialize/src/expr/src/relation/mod.rs:1077
#14 0x00005555560a040c in expr::relation::MirRelationExpr::try_visit1_mut<closure-0,transform::TransformError> ()
    at /home/moritz/dev/repos/materialize/src/expr/src/relation/mod.rs:1014
#15 expr::relation::MirRelationExpr::try_visit_mut<closure-0,transform::TransformError> ()
    at /home/moritz/dev/repos/materialize/src/expr/src/relation/mod.rs:1077
#16 0x00005555560a040c in expr::relation::MirRelationExpr::try_visit1_mut<closure-0,transform::TransformError> ()
    at /home/moritz/dev/repos/materialize/src/expr/src/relation/mod.rs:1014
#17 expr::relation::MirRelationExpr::try_visit_mut<closure-0,transform::TransformError> ()
    at /home/moritz/dev/repos/materialize/src/expr/src/relation/mod.rs:1077
#18 0x00005555560955a4 in transform::reduction::{{impl}}::transform () at /home/moritz/dev/repos/materialize/src/transform/src/reduction.rs:30
#19 0x0000555556065ee6 in transform::{{impl}}::transform () at /home/moritz/dev/repos/materialize/src/transform/src/lib.rs:203
#20 0x0000555556065bf8 in transform::{{impl}}::transform () at /home/moritz/dev/repos/materialize/src/transform/src/lib.rs:114
#21 0x0000555556066786 in transform::Optimizer::transform () at /home/moritz/dev/repos/materialize/src/transform/src/lib.rs:236
#22 transform::Optimizer::optimize () at /home/moritz/dev/repos/materialize/src/transform/src/lib.rs:334
#23 0x0000555555dd9be5 in coord::coord::Coordinator::prep_relation_expr () at /home/moritz/dev/repos/materialize/src/coord/src/coord.rs:3058
#24 0x0000555555afce23 in coord::coord::{{impl}}::sequence_insert::{{closure}} ()
    at /home/moritz/dev/repos/materialize/src/coord/src/coord.rs:2812
```
