### ISSUE TITLE
possible regression: kafka matrix test hangs with encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#7661]
### What version of Materialize are you using?

```
v0.8.4-dev (55745edfa)
```

### What was the issue?

The kafka-nightly test has started hanging. The reason is that it for historical reasons it runs the kafka .td tests under --workers=1 and the single worker is stuck like this:

```
Thread 13 (LWP 1030180):
#0  0x00007f84fc5f29f3 in pthread_cond_wait@@GLIBC_2.3.2 () from target:/lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000055e65ca20309 in cnd_wait (cond=<optimized out>, mtx=<optimized out>) at /cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/6920144/rdkafka-sys/librdkafka/src/tinycthread.c:442
#2  0x000055e65ca20585 in cnd_timedwait_abs (cnd=cnd@entry=0x7f84f33197e8, mtx=mtx@entry=0x7f84f33197c0, tspec=tspec@entry=0x7f84f51f8080) at /cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/6920144/rdka>
#3  0x000055e65c9ad39f in rd_kafka_q_pop_serve (rkq=rkq@entry=0x7f84f33197c0, timeout_us=<optimized out>, version=version@entry=0, cb_type=cb_type@entry=RD_KAFKA_Q_CB_RETURN, callback=callback@entry=0x0, o>
#4  0x000055e65c9ad430 in rd_kafka_q_pop (rkq=rkq@entry=0x7f84f33197c0, timeout_us=<optimized out>, version=version@entry=0) at /cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/6920144/rdkafka-sys/librdk>
#5  0x000055e65c9a3163 in rd_kafka_op_req0 (destq=<optimized out>, recvq=recvq@entry=0x7f84f33197c0, rko=rko@entry=0x7f84d062a560, timeout_ms=timeout_ms@entry=-1) at /cargo/git/checkouts/rust-rdkafka-34d94>
#6  0x000055e65c9e810e in rd_kafka_txn_curr_api_req (rk=rk@entry=0x7f84edcf6000, name=<optimized out>, name@entry=0x55e65d88f8f0 <__FUNCTION__.10> "rd_kafka_init_transactions", rko=0x7f84d062a560, timeout_>
#7  0x000055e65c9ea2c2 in rd_kafka_init_transactions (rk=0x7f84edcf6000, timeout_ms=5000) at /cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/6920144/rdkafka-sys/librdkafka/src/rdkafka_txnmgr.c:1371
#8  0x000055e65bfb55ca in <rdkafka::producer::base_producer::BaseProducer<C> as rdkafka::producer::Producer<C>>::init_transactions () at /cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/6920144/src/produ>
#9  <rdkafka::producer::base_producer::ThreadedProducer<C> as rdkafka::producer::Producer<C>>::init_transactions () at /cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/6920144/src/producer/base_producer.>
#10 0x000055e65c2de0f4 in dataflow::sink::kafka::produce_to_kafka::{{closure}} () at src/dataflow/src/sink/kafka.rs:765
#11 dataflow::sink::kafka::produce_to_kafka::{{closure}}::{{closure}} () at src/dataflow/src/sink/kafka.rs:959
#12 timely::dataflow::operators::generic::builder_rc::OperatorBuilder<G>::build_reschedule::{{closure}} () at /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/09b16c5/timely/src/dataflow/operators/gen>
#13 <timely::dataflow::operators::generic::builder_raw::OperatorCore<T,L> as timely::scheduling::Schedule>::schedule () at /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/09b16c5/timely/src/dataflow/>
#14 0x000055e65b98e083 in timely::progress::subgraph::PerOperatorState<T>::schedule () at /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/09b16c5/timely/src/progress/subgraph.rs:684
#15 0x000055e65b8ee4e9 in timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child () at /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/09b16c5/timely/src/progress/subgraph.rs:344
#16 <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule () at /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/09b16c5/timely/src/progress/subgraph.rs:310
#17 0x000055e65b98e083 in timely::progress::subgraph::PerOperatorState<T>::schedule () at /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/09b16c5/timely/src/progress/subgraph.rs:684
#18 0x000055e65b8ed5e9 in timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child () at /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/09b16c5/timely/src/progress/subgraph.rs:344
#19 <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule () at /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/09b16c5/timely/src/progress/subgraph.rs:310
#20 0x000055e65d063b49 in timely::worker::Wrapper::step::{{closure}} () at /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/09b16c5/timely/src/worker.rs:749
#21 core::option::Option<T>::map () at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/option.rs:489
#22 timely::worker::Wrapper::step () at /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/09b16c5/timely/src/worker.rs:749
#23 0x000055e65b823a10 in timely::worker::Worker<A>::step_or_park () at /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/09b16c5/timely/src/worker.rs:396
#24 0x000055e65b8699a9 in dataflow::server::Worker<A>::run () at src/dataflow/src/server.rs:480
#25 dataflow::server::serve::{{closure}} () at src/dataflow/src/server.rs:256
#26 0x000055e65b7e7667 in timely::execute::execute::{{closure}} () at /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/09b16c5/timely/src/execute.rs:285
#27 timely_communication::initialize::initialize_from::{{closure}} () at /cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/09b16c5/communication/src/initialize.rs:291
#28 std::sys_common::backtrace::__rust_begin_short_backtrace () at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:125
#29 0x000055e65b930297 in std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} () at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/mod.rs:481
#30 <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once () at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:347
#31 std::panicking::try::do_call () at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401
#32 std::panicking::try () at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365
#33 std::panic::catch_unwind () at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434
#34 std::thread::Builder::spawn_unchecked::{{closure}} () at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/thread/mod.rs:480
#35 core::ops::function::FnOnce::call_once{{vtable-shim}} () at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:227
#36 0x000055e65d52b647 in <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575
#37 <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/alloc/src/boxed.rs:1575
#38 std::sys::unix::thread::Thread::new::thread_start () at library/std/src/sys/unix/thread.rs:71
#39 0x00007f84fc5ec6db in start_thread () from target:/lib/x86_64-linux-gnu/libpthread.so.0
#40 0x00007f84fb73888f in clone () from target:/lib/x86_64-linux-gnu/libc.so.6
```

I am going to fix the test to not use --workers 1, so this ticket is about the fact that the entire server hangs, which is a genuine bug on its own.

### Is the issue reproducible? If so, please provide reproduction instructions.

Yes, run the ```kafka-matrix``` test suite . Make sure the ```mzcompose.yml``` file has ```--workers 1``` .

### Please attach any applicable log files.

The log has this:

```
2021-08-03T09:52:26.484681Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:52:26.767954Z  INFO coord::catalog: create sink materialize.public.output14_custom_consistency_topic (u131)    
2021-08-03T09:52:26.860674Z  INFO coord::catalog: create source materialize.public.compaction_test_input (u132)    
2021-08-03T09:52:26.860741Z  INFO coord::catalog: create index materialize.public.compaction_test_input_primary_idx (u133)    
2021-08-03T09:52:26.871380Z  INFO coord::timestamp: Timestamping Source u132 with BYO Consistency. Consistency Source: BringYourOwn { broker: "kafka:9092", topic: "testdrive-compaction-test-input-consistency-3654641093" }.    
2021-08-03T09:52:26.905040Z  WARN librdkafka: librdkafka: CONFWARN [thrd:app]: Configuration property isolation.level is a consumer property and will be ignored by this producer instance    
2021-08-03T09:52:31.484761Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:52:32.086554Z  INFO coord::catalog: create sink materialize.public.compaction_test_sink (u134)    
2021-08-03T09:52:36.484954Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:52:41.485019Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:52:46.485096Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:52:51.485179Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:52:56.485261Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:53:01.485362Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:53:06.485500Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:53:11.485590Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:53:16.485672Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:53:21.485753Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:53:26.485832Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:53:31.485916Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:53:36.485998Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:53:41.486157Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:53:46.486255Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:53:51.486339Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:53:56.486409Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:54:01.486489Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:54:06.486644Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:54:11.486878Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:54:16.488312Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:54:21.488405Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:54:26.488481Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:54:31.488540Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:54:36.488600Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:54:41.488669Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:54:46.488727Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:54:51.488800Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:54:56.488881Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:55:01.488963Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:55:06.489033Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:55:11.489097Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:55:16.489170Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:55:21.489235Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:55:26.489318Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:55:31.489384Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:55:36.489453Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:55:41.489513Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:55:46.489585Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:55:51.489643Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:55:56.489722Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:56:01.489798Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:56:06.489875Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:56:11.489934Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:56:16.490024Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:56:21.490103Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:56:26.490171Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:56:31.490253Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:56:36.490342Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:56:41.490426Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:56:46.490494Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:56:51.490561Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:56:56.490642Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:57:01.490704Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:57:06.490783Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:57:11.490860Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:57:16.490925Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:57:21.491002Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:57:26.491118Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:57:31.491193Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:57:36.491269Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:57:41.491327Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:57:46.491398Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:57:51.491469Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:57:56.491544Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:58:01.491604Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:58:06.491675Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:58:11.491753Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:58:16.491828Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:58:21.491906Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:58:26.491982Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:58:31.492042Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:58:36.492103Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:58:41.492166Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:58:46.492246Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:58:51.492306Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:58:56.492377Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:59:01.492449Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:59:06.492521Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:59:11.492594Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:59:16.492658Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:59:21.492775Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:59:26.492854Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:59:31.492920Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:59:36.492996Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:59:41.493072Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:59:46.493149Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:59:51.493224Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
2021-08-03T09:59:56.493301Z ERROR dataflow::sink::kafka: encountered error during kafka interaction. kafka-u130 in state Init at time 1627984341000 : Transaction error: Failed to initialize Producer ID: Local: Timed out    
```

**Comment by philip-stoev** [comment]
Turns out this is a new error in the latest Kafka version:

```
[2021-08-03 11:03:26,348] ERROR [KafkaApi-1001] Number of alive brokers '1' does not meet the required replication factor '3' for the transactions state topic (configured via 'transaction.state.log.replication.factor'). This error can be ignored if the cluster is starting up and not all brokers are up yet. (kafka.server.KafkaApis)
[2021-08-03 11:03:26,348] ERROR [KafkaApi-1001] Number of alive brokers '1' does not meet the required replication factor '3' for the transactions state topic (configured via 'transaction.state.log.replication.factor'). This error can be ignored if the cluster is starting up and not all brokers are up yet. (kafka.server.KafkaApis)
```

The container needs to run with ```KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1```
