### ISSUE TITLE
dbt-materialize: dbt docs doesn't work with sinks

### ISSUE THREAD

**Issue by JLDLaughlin** [MaterializeInc/materialize#7770]
### What version of Materialize are you using?

```
$ materialized -v

```

`dbt=0.18.1`

### How did you install Materialize?

* [ ] Docker image
* [ ] Linux release tarball
* [ ] APT package
* [ ] macOS release tarball
* [ ] Homebrew tap
* [ ] Built from source
* [ ] Materialize Cloud

### What was the issue?

This issue was reported in [our community Slack](https://materializecommunity.slack.com/archives/C01GHNWF690/p1628455271009000). A user was able to use `dbt-materialize` to `dbt run` their model, but running `dbt docs generate` fails:
```
$ dbt docs generate
Running with dbt=0.18.1
Found 11 models, 0 tests, 0 snapshots, 0 analyses, 150 macros, 0 operations, 0 seed files, 0 sources

22:23:57 | Concurrency: 1 threads (target='dev')
22:23:57 | 
Encountered an error:
Runtime Error
  Database Error in model books_agg_sink (models/books_agg_sink.sql)
    unknown catalog item 'materialize.analytics.books_agg'
```

**Comment by elindsey** [comment]
Repro from community slack:

[materialize_dbt_test.zip](https://github.com/MaterializeInc/materialize/files/6963334/materialize_dbt_test.zip)

books is a source (dropped with cascade); books_agg is a view on top of that source; books_agg_sink is a sink based on that view.

Log from dbt docs generation:
```
$ dbt -d docs generate
2021-08-10 15:51:40.680523 (MainThread): Running with dbt=0.20.0
2021-08-10 15:51:40.741699 (MainThread): running dbt with arguments Namespace(record_timing_info=None, debug=True, log_format='default', write_json=True, use_colors=None, strict=False, warn_error=False, partial_parse=None, single_threaded=False, test_new_parser=False, use_experimental_parser=False, project_dir=None, profiles_dir='/Users/eli/.dbt', profile=None, target=None, vars='{}', log_cache_events=False, use_cache=True, compile=True, threads=None, version_check=True, models=None, exclude=None, selector_name=None, state=None, defer=None, cls=<class 'dbt.task.generate.GenerateTask'>, which='generate', rpc_method='docs.generate')
2021-08-10 15:51:40.742590 (MainThread): Tracking: tracking
2021-08-10 15:51:40.755515 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109965e20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10994a400>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10994a550>]}
2021-08-10 15:51:40.766124 (MainThread): Partial parsing not enabled
2021-08-10 15:51:40.774605 (MainThread): Parsing macros/mz_create_source.sql
2021-08-10 15:51:40.776313 (MainThread): Parsing macros/mz_drop_sink.sql
2021-08-10 15:51:40.777611 (MainThread): Parsing macros/mz_create_index.sql
2021-08-10 15:51:40.780545 (MainThread): Parsing macros/mz_drop_source.sql
2021-08-10 15:51:40.781846 (MainThread): Parsing macros/mz_generate_name.sql
2021-08-10 15:51:40.782683 (MainThread): Parsing macros/mz_create_sink.sql
2021-08-10 15:51:40.783489 (MainThread): Parsing macros/catalog.sql
2021-08-10 15:51:40.785765 (MainThread): Parsing macros/relations.sql
2021-08-10 15:51:40.790058 (MainThread): Parsing macros/mz_drop_index.sql
2021-08-10 15:51:40.792124 (MainThread): Parsing macros/adapters.sql
2021-08-10 15:51:40.799662 (MainThread): Parsing macros/materializations/materialized_view.sql
2021-08-10 15:51:40.801688 (MainThread): Parsing macros/materializations/seed.sql
2021-08-10 15:51:40.808216 (MainThread): Parsing macros/materializations/view.sql
2021-08-10 15:51:40.810421 (MainThread): Parsing macros/materializations/helpers.sql
2021-08-10 15:51:40.811772 (MainThread): Parsing macros/materializations/table.sql
2021-08-10 15:51:40.813718 (MainThread): Parsing macros/materializations/incremental.sql
2021-08-10 15:51:40.814235 (MainThread): Parsing macros/core.sql
2021-08-10 15:51:40.817388 (MainThread): Parsing macros/materializations/test.sql
2021-08-10 15:51:40.823393 (MainThread): Parsing macros/materializations/helpers.sql
2021-08-10 15:51:40.832392 (MainThread): Parsing macros/materializations/snapshot/snapshot_merge.sql
2021-08-10 15:51:40.833766 (MainThread): Parsing macros/materializations/snapshot/strategies.sql
2021-08-10 15:51:40.848881 (MainThread): Parsing macros/materializations/snapshot/snapshot.sql
2021-08-10 15:51:40.879512 (MainThread): Parsing macros/materializations/seed/seed.sql
2021-08-10 15:51:40.898271 (MainThread): Parsing macros/materializations/incremental/helpers.sql
2021-08-10 15:51:40.899717 (MainThread): Parsing macros/materializations/incremental/incremental.sql
2021-08-10 15:51:40.906144 (MainThread): Parsing macros/materializations/common/merge.sql
2021-08-10 15:51:40.918711 (MainThread): Parsing macros/materializations/table/table.sql
2021-08-10 15:51:40.924818 (MainThread): Parsing macros/materializations/view/view.sql
2021-08-10 15:51:40.930519 (MainThread): Parsing macros/materializations/view/create_or_replace_view.sql
2021-08-10 15:51:40.934739 (MainThread): Parsing macros/etc/get_custom_alias.sql
2021-08-10 15:51:40.935436 (MainThread): Parsing macros/etc/query.sql
2021-08-10 15:51:40.936220 (MainThread): Parsing macros/etc/is_incremental.sql
2021-08-10 15:51:40.937502 (MainThread): Parsing macros/etc/datetime.sql
2021-08-10 15:51:40.944912 (MainThread): Parsing macros/etc/get_custom_schema.sql
2021-08-10 15:51:40.946408 (MainThread): Parsing macros/etc/get_custom_database.sql
2021-08-10 15:51:40.947686 (MainThread): Parsing macros/adapters/common.sql
2021-08-10 15:51:40.990034 (MainThread): Parsing macros/schema_tests/relationships.sql
2021-08-10 15:51:40.991475 (MainThread): Parsing macros/schema_tests/not_null.sql
2021-08-10 15:51:40.992406 (MainThread): Parsing macros/schema_tests/unique.sql
2021-08-10 15:51:40.993550 (MainThread): Parsing macros/schema_tests/accepted_values.sql
2021-08-10 15:51:41.133857 (MainThread): Acquiring new materialize connection "model.materialize_cloud_dbt.books".
2021-08-10 15:51:41.150492 (MainThread): Acquiring new materialize connection "model.materialize_cloud_dbt.books_agg_sink".
2021-08-10 15:51:41.156673 (MainThread): Acquiring new materialize connection "model.materialize_cloud_dbt.books_agg".
2021-08-10 15:51:41.198366 (MainThread): Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'be4be077-4568-4306-bd22-c4abe5dcc66b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109a910d0>]}
2021-08-10 15:51:41.202448 (MainThread): Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'be4be077-4568-4306-bd22-c4abe5dcc66b', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109a910d0>]}
2021-08-10 15:51:41.202652 (MainThread): Found 3 models, 0 tests, 0 snapshots, 0 analyses, 158 macros, 0 operations, 0 seed files, 0 sources, 0 exposures
2021-08-10 15:51:41.203337 (MainThread): 
2021-08-10 15:51:41.203587 (MainThread): Acquiring new materialize connection "master".
2021-08-10 15:51:41.204248 (ThreadPoolExecutor-0_0): Acquiring new materialize connection "list_materialize_analytics".
2021-08-10 15:51:41.207595 (ThreadPoolExecutor-0_0): Using materialize connection "list_materialize_analytics".
2021-08-10 15:51:41.207712 (ThreadPoolExecutor-0_0): On list_materialize_analytics: /* {"app": "dbt", "dbt_version": "0.20.0", "profile_name": "default", "target_name": "dev", "connection_name": "list_materialize_analytics"} */

    show extended schemas
  
2021-08-10 15:51:41.207816 (ThreadPoolExecutor-0_0): Opening a new connection, currently in state init
2021-08-10 15:51:41.247629 (ThreadPoolExecutor-0_0): SQL status: SELECT 5 in 0.04 seconds
2021-08-10 15:51:41.249702 (ThreadPoolExecutor-0_0): On list_materialize_analytics: Close
2021-08-10 15:51:41.250742 (MainThread): 11:51:41 | Concurrency: 1 threads (target='dev')
2021-08-10 15:51:41.250873 (MainThread): 11:51:41 | 
2021-08-10 15:51:41.252877 (Thread-1): Began running node model.materialize_cloud_dbt.books
2021-08-10 15:51:41.253332 (Thread-1): Acquiring new materialize connection "model.materialize_cloud_dbt.books".
2021-08-10 15:51:41.253604 (Thread-1): Compiling model.materialize_cloud_dbt.books
2021-08-10 15:51:41.256971 (Thread-1): Using materialize connection "model.materialize_cloud_dbt.books".
2021-08-10 15:51:41.257098 (Thread-1): On model.materialize_cloud_dbt.books: /* {"app": "dbt", "dbt_version": "0.20.0", "profile_name": "default", "target_name": "dev", "node_id": "model.materialize_cloud_dbt.books"} */

    
    DROP SOURCE
    
        IF EXISTS
    
    
    materialize.analytics.books_source

    
        CASCADE
    
  
  
2021-08-10 15:51:41.257254 (Thread-1): Opening a new connection, currently in state closed
2021-08-10 15:51:41.264734 (Thread-1): SQL status: DROP SOURCE in 0.01 seconds
2021-08-10 15:51:41.266018 (Thread-1): Writing runtime SQL for node "model.materialize_cloud_dbt.books"
2021-08-10 15:51:41.266418 (Thread-1): Using materialize connection "model.materialize_cloud_dbt.books".
2021-08-10 15:51:41.266539 (Thread-1): On model.materialize_cloud_dbt.books: /* {"app": "dbt", "dbt_version": "0.20.0", "profile_name": "default", "target_name": "dev", "node_id": "model.materialize_cloud_dbt.books"} */

    
    -- Avro file
    create source 
    materialize.analytics.books_source

    from file '/Users/eli/Downloads/mz_dbt_test/models/book.csv' 
    format csv with header 
        

2021-08-10 15:51:41.270624 (Thread-1): SQL status: CREATE SOURCE in 0.00 seconds
2021-08-10 15:51:41.271556 (Thread-1): Writing injected SQL for node "model.materialize_cloud_dbt.books"
2021-08-10 15:51:41.272248 (Thread-1): On model.materialize_cloud_dbt.books: Close
2021-08-10 15:51:41.272802 (Thread-1): Finished running node model.materialize_cloud_dbt.books
2021-08-10 15:51:41.273540 (Thread-1): Began running node model.materialize_cloud_dbt.books_agg
2021-08-10 15:51:41.273977 (Thread-1): Acquiring new materialize connection "model.materialize_cloud_dbt.books_agg".
2021-08-10 15:51:41.274107 (Thread-1): Compiling model.materialize_cloud_dbt.books_agg
2021-08-10 15:51:41.276796 (Thread-1): Writing injected SQL for node "model.materialize_cloud_dbt.books_agg"
2021-08-10 15:51:41.277566 (Thread-1): Finished running node model.materialize_cloud_dbt.books_agg
2021-08-10 15:51:41.278058 (Thread-1): Began running node model.materialize_cloud_dbt.books_agg_sink
2021-08-10 15:51:41.278473 (Thread-1): Acquiring new materialize connection "model.materialize_cloud_dbt.books_agg_sink".
2021-08-10 15:51:41.278642 (Thread-1): Compiling model.materialize_cloud_dbt.books_agg_sink
2021-08-10 15:51:41.281686 (Thread-1): Using materialize connection "model.materialize_cloud_dbt.books_agg_sink".
2021-08-10 15:51:41.281905 (Thread-1): On model.materialize_cloud_dbt.books_agg_sink: /* {"app": "dbt", "dbt_version": "0.20.0", "profile_name": "default", "target_name": "dev", "node_id": "model.materialize_cloud_dbt.books_agg_sink"} */

    
    DROP SINK
    
        IF EXISTS
    
    
    materialize.analytics.books_sink

  
  
2021-08-10 15:51:41.282242 (Thread-1): Opening a new connection, currently in state closed
2021-08-10 15:51:41.286001 (Thread-1): SQL status: DROP SINK in 0.00 seconds
2021-08-10 15:51:41.286534 (Thread-1): Writing runtime SQL for node "model.materialize_cloud_dbt.books_agg_sink"
2021-08-10 15:51:41.286967 (Thread-1): Using materialize connection "model.materialize_cloud_dbt.books_agg_sink".
2021-08-10 15:51:41.287107 (Thread-1): On model.materialize_cloud_dbt.books_agg_sink: /* {"app": "dbt", "dbt_version": "0.20.0", "profile_name": "default", "target_name": "dev", "node_id": "model.materialize_cloud_dbt.books_agg_sink"} */

    
    -- https://materialize.com/docs/sql/create-sink/

    create sink 
    materialize.analytics.books_sink

    from "materialize"."analytics"."books_agg"
    into avro ocf '/Users/eli/Downloads/mz_dbt_test/sinks/books.ocf'
    

2021-08-10 15:51:41.288719 (Thread-1): Postgres error: unknown catalog item 'materialize.analytics.books_agg'

2021-08-10 15:51:41.289738 (Thread-1): On model.materialize_cloud_dbt.books_agg_sink: Close
2021-08-10 15:51:41.290143 (Thread-1): Database Error in model books_agg_sink (models/books_agg_sink.sql)
  unknown catalog item 'materialize.analytics.books_agg'
Traceback (most recent call last):
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/adapters/postgres/connections.py", line 48, in exception_handler
    yield
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/adapters/sql/connections.py", line 80, in add_query
    cursor.execute(sql, bindings)
psycopg2.errors.InternalError_: unknown catalog item 'materialize.analytics.books_agg'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/task/base.py", line 348, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/task/base.py", line 285, in compile_and_execute
    ctx.node = self.compile(manifest)
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/task/compile.py", line 33, in compile
    return compiler.compile_node(self.node, manifest, {})
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/compilation.py", line 464, in compile_node
    node = self._compile_node(node, manifest, extra_context)
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/compilation.py", line 371, in _compile_node
    compiled_node.compiled_sql = jinja.get_rendered(
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/clients/jinja.py", line 598, in get_rendered
    return render_template(template, ctx, node)
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/clients/jinja.py", line 549, in render_template
    return template.render(ctx)
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 17, in top-level template code
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/clients/jinja.py", line 333, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/clients/jinja.py", line 260, in call_macro
    return macro(*args, **kwargs)
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 4, in template
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/clients/jinja.py", line 333, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/clients/jinja.py", line 260, in call_macro
    return macro(*args, **kwargs)
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 10, in template
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/adapters/base/impl.py", line 227, in execute
    return self.connections.execute(
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/adapters/sql/connections.py", line 131, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/adapters/sql/connections.py", line 87, in add_query
    return connection, cursor
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/adapters/postgres/connections.py", line 59, in exception_handler
    raise dbt.exceptions.DatabaseException(str(e).strip()) from e
dbt.exceptions.DatabaseException: Database Error in model books_agg_sink (models/books_agg_sink.sql)
  unknown catalog item 'materialize.analytics.books_agg'
2021-08-10 15:51:41.292983 (Thread-1): Finished running node model.materialize_cloud_dbt.books_agg_sink
2021-08-10 15:51:41.293504 (MainThread): Connection 'master' was properly closed.
2021-08-10 15:51:41.293896 (MainThread): Connection 'model.materialize_cloud_dbt.books_agg_sink' was properly closed.
2021-08-10 15:51:41.294339 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109a394f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109a919a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10998bc10>]}
2021-08-10 15:51:41.294623 (MainThread): Flushing usage events
2021-08-10 15:51:41.441729 (MainThread): Encountered an error:
2021-08-10 15:51:41.441975 (MainThread): Runtime Error
  Database Error in model books_agg_sink (models/books_agg_sink.sql)
    unknown catalog item 'materialize.analytics.books_agg'
2021-08-10 15:51:41.443075 (MainThread): Traceback (most recent call last):
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/main.py", line 125, in main
    results, succeeded = handle_and_check(args)
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/main.py", line 203, in handle_and_check
    task, res = run_from_args(parsed)
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/main.py", line 256, in run_from_args
    results = task.run()
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/task/generate.py", line 204, in run
    compile_results = CompileTask.run(self)
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/task/runnable.py", line 425, in run
    result = self.execute_with_hooks(selected_uids)
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/task/runnable.py", line 384, in execute_with_hooks
    res = self.execute_nodes()
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/task/runnable.py", line 339, in execute_nodes
    self.run_queue(pool)
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/task/runnable.py", line 267, in run_queue
    self._raise_set_error()
  File "/Users/eli/code/materialize/dbt-venv/lib/python3.9/site-packages/dbt/task/runnable.py", line 222, in _raise_set_error
    raise self._raise_next_tick
dbt.exceptions.RuntimeException: Runtime Error
  Database Error in model books_agg_sink (models/books_agg_sink.sql)
    unknown catalog item 'materialize.analytics.books_agg'
```

**Comment by JLDLaughlin** [comment]
Update: this will be fixed by https://github.com/MaterializeInc/materialize/pull/7836!

**Comment by JLDLaughlin** [comment]
This bug was fixed! The user will need to migrate from the `mz_create_object` and `mz_drop_object` macros to our new custom `materialization` types. Examples can be found here for [sources](https://github.com/MaterializeInc/materialize/blob/main/play/materialize-cloud-dbt/models/example/market_orders_raw.sql) and [sinks](https://github.com/MaterializeInc/materialize/blob/main/play/materialize-cloud-dbt/models/example/market_orders_sink.sql).
