### ISSUE TITLE
dbt-materialize: inconsistent `source` referencing behaviour

### ISSUE THREAD

**Issue by morsapaes** [MaterializeInc/materialize#8744]
### What version of Materialize are you using?

```
v0.9.8 (+ dbt 0.21.0, dbt-materialize 0.21.0)
```

### How did you install Materialize?

* [x] Homebrew tap

### What was the issue?

`dbt run` fails if a model uses the [source()](https://docs.getdbt.com/docs/building-a-dbt-project/using-sources) function to reference a Materialize source model. The adapter seems to execute the model with the source dependency ahead of the actual source.

This issue is **not present** if the source is manually created in Materialize (like in the [wikirecent-dbt](https://github.com/MaterializeInc/materialize/tree/main/play/wikirecent-dbt) example), or if [ref()](https://docs.getdbt.com/reference/dbt-jinja-functions/ref) is used instead. It also doesn't affect `dbt docs generate`.

### Is the issue reproducible? If so, please provide reproduction instructions.

You can find a working example in [this repository](https://github.com/morsapaes/mz-playground/tree/main/dbt). To reproduce, edit the `market_orders.sql` model using:

```sql
FROM {{ source('public','market_orders_raw') }}
```

instead of:

```sql
FROM {{ ref('market_orders_raw') }}
```

and hit `dbt run`.

### Please attach any applicable log files.

Using `source()`:

```
2021-10-20 08:03:03.251799 (Thread-1): Began running node model.mz_get_started.market_orders
2021-10-20 08:03:03.251979 (Thread-1): 10:03:03 | 1 of 3 START view model public.market_orders......................... [RUN]
2021-10-20 08:03:03.252170 (Thread-1): Acquiring new materialize connection "model.mz_get_started.market_orders".
2021-10-20 08:03:03.252276 (Thread-1): Compiling model.mz_get_started.market_orders
2021-10-20 08:03:03.254118 (Thread-1): Writing injected SQL for node "model.mz_get_started.market_orders"
2021-10-20 08:03:03.254643 (Thread-1): finished collecting timing info
2021-10-20 08:03:03.260658 (Thread-1): Using materialize connection "model.mz_get_started.market_orders".
2021-10-20 08:03:03.260775 (Thread-1): On model.mz_get_started.market_orders: /* {"app": "dbt", "dbt_version": "0.21.0", "profile_name": "default", "target_name": "dev", "node_id": "model.mz_get_started.market_orders"} */
drop view if exists "materialize"."public"."market_orders" cascade
2021-10-20 08:03:03.260864 (Thread-1): Opening a new connection, currently in state closed
2021-10-20 08:03:03.263020 (Thread-1): SQL status: DROP VIEW in 0.00 seconds
2021-10-20 08:03:03.267569 (Thread-1): Writing runtime SQL for node "model.mz_get_started.market_orders"
2021-10-20 08:03:03.268151 (Thread-1): Using materialize connection "model.mz_get_started.market_orders".
2021-10-20 08:03:03.268233 (Thread-1): On model.mz_get_started.market_orders: /* {"app": "dbt", "dbt_version": "0.21.0", "profile_name": "default", "target_name": "dev", "node_id": "model.mz_get_started.market_orders"} */
create view "materialize"."public"."market_orders"
  as (

SELECT
    ((text::jsonb)->>'bid_price')::float AS bid_price,
    (text::jsonb)->>'order_quantity' AS order_quantity,
    (text::jsonb)->>'symbol' AS symbol,
    (text::jsonb)->>'trade_type' AS trade_type,
    to_timestamp(((text::jsonb)->'timestamp')::bigint) AS ts
FROM "materialize"."public"."market_orders_raw"

  );
2021-10-20 08:03:03.268692 (Thread-1): Postgres error: unknown catalog item 'materialize.public.market_orders_raw'

2021-10-20 08:03:03.268798 (Thread-1): finished collecting timing info
2021-10-20 08:03:03.268890 (Thread-1): On model.mz_get_started.market_orders: Close
2021-10-20 08:03:03.269062 (Thread-1): Database Error in model market_orders (models/market_orders.sql)
  unknown catalog item 'materialize.public.market_orders_raw'
  compiled SQL at target/run/mz_get_started/models/market_orders.sql
Traceback (most recent call last):
  File "/Users/morsapaes/Desktop/Repos/jaffle_shop/dbt-venv/lib/python3.9/site-packages/dbt/adapters/postgres/connections.py", line 56, in exception_handler
    yield
  File "/Users/morsapaes/Desktop/Repos/jaffle_shop/dbt-venv/lib/python3.9/site-packages/dbt/adapters/sql/connections.py", line 80, in add_query
    cursor.execute(sql, bindings)
psycopg2.errors.InternalError_: unknown catalog item 'materialize.public.market_orders_raw'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/morsapaes/Desktop/Repos/jaffle_shop/dbt-venv/lib/python3.9/site-packages/dbt/task/base.py", line 348, in safe_run
    result = self.compile_and_execute(manifest, ctx)
  File "/Users/morsapaes/Desktop/Repos/jaffle_shop/dbt-venv/lib/python3.9/site-packages/dbt/task/base.py", line 291, in compile_and_execute
    result = self.run(ctx.node, manifest)
  File "/Users/morsapaes/Desktop/Repos/jaffle_shop/dbt-venv/lib/python3.9/site-packages/dbt/task/base.py", line 393, in run
    return self.execute(compiled_node, manifest)
  File "/Users/morsapaes/Desktop/Repos/jaffle_shop/dbt-venv/lib/python3.9/site-packages/dbt/task/run.py", line 249, in execute
    result = MacroGenerator(materialization_macro, context)()
  File "/Users/morsapaes/Desktop/Repos/jaffle_shop/dbt-venv/lib/python3.9/site-packages/dbt/clients/jinja.py", line 333, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/morsapaes/Desktop/Repos/jaffle_shop/dbt-venv/lib/python3.9/site-packages/dbt/clients/jinja.py", line 260, in call_macro
    return macro(*args, **kwargs)
  File "/Users/morsapaes/Desktop/Repos/jaffle_shop/dbt-venv/lib/python3.9/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/morsapaes/Desktop/Repos/jaffle_shop/dbt-venv/lib/python3.9/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 45, in macro
  File "/Users/morsapaes/Desktop/Repos/jaffle_shop/dbt-venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/morsapaes/Desktop/Repos/jaffle_shop/dbt-venv/lib/python3.9/site-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/Users/morsapaes/Desktop/Repos/jaffle_shop/dbt-venv/lib/python3.9/site-packages/dbt/clients/jinja.py", line 333, in __call__
    return self.call_macro(*args, **kwargs)
  File "/Users/morsapaes/Desktop/Repos/jaffle_shop/dbt-venv/lib/python3.9/site-packages/dbt/clients/jinja.py", line 260, in call_macro
    return macro(*args, **kwargs)
  File "/Users/morsapaes/Desktop/Repos/jaffle_shop/dbt-venv/lib/python3.9/site-packages/jinja2/runtime.py", line 675, in __call__
    return self._invoke(arguments, autoescape)
  File "/Users/morsapaes/Desktop/Repos/jaffle_shop/dbt-venv/lib/python3.9/site-packages/jinja2/runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "<template>", line 41, in macro
  File "/Users/morsapaes/Desktop/Repos/jaffle_shop/dbt-venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 462, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/morsapaes/Desktop/Repos/jaffle_shop/dbt-venv/lib/python3.9/site-packages/jinja2/runtime.py", line 290, in call
    return __obj(*args, **kwargs)
  File "/Users/morsapaes/Desktop/Repos/jaffle_shop/dbt-venv/lib/python3.9/site-packages/dbt/adapters/base/impl.py", line 226, in execute
    return self.connections.execute(
  File "/Users/morsapaes/Desktop/Repos/jaffle_shop/dbt-venv/lib/python3.9/site-packages/dbt/adapters/sql/connections.py", line 131, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/Users/morsapaes/Desktop/Repos/jaffle_shop/dbt-venv/lib/python3.9/site-packages/dbt/adapters/sql/connections.py", line 87, in add_query
    return connection, cursor
  File "/opt/homebrew/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/morsapaes/Desktop/Repos/jaffle_shop/dbt-venv/lib/python3.9/site-packages/dbt/adapters/postgres/connections.py", line 67, in exception_handler
    raise dbt.exceptions.DatabaseException(str(e).strip()) from e
dbt.exceptions.DatabaseException: Database Error in model market_orders (models/market_orders.sql)
  unknown catalog item 'materialize.public.market_orders_raw'
  compiled SQL at target/run/mz_get_started/models/market_orders.sql
2021-10-20 08:03:03.271942 (Thread-1): Sending event: {'category': 'dbt', 'action': 'run_model', 'label': 'f1491659-ed72-4af1-859a-3947f35a774f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107b42370>]}
2021-10-20 08:03:03.272138 (Thread-1): 10:03:03 | 1 of 3 ERROR creating view model public.market_orders................ [ERROR in 0.02s]
2021-10-20 08:03:03.272229 (Thread-1): Finished running node model.mz_get_started.market_orders
2021-10-20 08:03:03.272319 (Thread-1): Began running node model.mz_get_started.market_orders_raw
2021-10-20 08:03:03.272512 (Thread-1): 10:03:03 | 2 of 3 START source model public.market_orders_raw................... [RUN]
2021-10-20 08:03:03.272723 (Thread-1): Acquiring new materialize connection "model.mz_get_started.market_orders_raw".
2021-10-20 08:03:03.272811 (Thread-1): Compiling model.mz_get_started.market_orders_raw
2021-10-20 08:03:03.274407 (Thread-1): Writing injected SQL for node "model.mz_get_started.market_orders_raw"
2021-10-20 08:03:03.274915 (Thread-1): finished collecting timing info
2021-10-20 08:03:03.278892 (Thread-1): Using materialize connection "model.mz_get_started.market_orders_raw".
2021-10-20 08:03:03.278980 (Thread-1): On model.mz_get_started.market_orders_raw: /* {"app": "dbt", "dbt_version": "0.21.0", "profile_name": "default", "target_name": "dev", "node_id": "model.mz_get_started.market_orders_raw"} */
drop source if exists 
      materialize.public.market_orders_raw
   cascade
2021-10-20 08:03:03.279057 (Thread-1): Opening a new connection, currently in state closed
2021-10-20 08:03:03.281018 (Thread-1): SQL status: DROP SOURCE in 0.00 seconds
2021-10-20 08:03:03.282396 (Thread-1): Writing runtime SQL for node "model.mz_get_started.market_orders_raw"
2021-10-20 08:03:03.283235 (Thread-1): Using materialize connection "model.mz_get_started.market_orders_raw".
2021-10-20 08:03:03.283432 (Thread-1): On model.mz_get_started.market_orders_raw: /* {"app": "dbt", "dbt_version": "0.21.0", "profile_name": "default", "target_name": "dev", "node_id": "model.mz_get_started.market_orders_raw"} */

CREATE SOURCE 
    materialize.public.market_orders_raw

FROM PUBNUB
SUBSCRIBE KEY 'sub-c-4377ab04-f100-11e3-bffd-02ee2ddab7fe'
CHANNEL 'pubnub-market-orders'
2021-10-20 08:03:03.285237 (Thread-1): SQL status: CREATE SOURCE in 0.00 seconds
2021-10-20 08:03:03.288522 (Thread-1): finished collecting timing info
2021-10-20 08:03:03.288637 (Thread-1): On model.mz_get_started.market_orders_raw: Close
2021-10-20 08:03:03.288835 (Thread-1): Sending event: {'category': 'dbt', 'action': 'run_model', 'label': 'f1491659-ed72-4af1-859a-3947f35a774f', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107cc1280>]}
2021-10-20 08:03:03.289007 (Thread-1): 10:03:03 | 2 of 3 OK created source model public.market_orders_raw.............. [CREATE SOURCE in 0.02s]
2021-10-20 08:03:03.289091 (Thread-1): Finished running node model.mz_get_started.market_orders_raw
```

Using `ref()`:

```
2021-10-20 08:05:59.921874 (Thread-1): Began running node model.mz_get_started.market_orders_raw
2021-10-20 08:05:59.922165 (Thread-1): 10:05:59 | 1 of 3 START source model public.market_orders_raw................... [RUN]
2021-10-20 08:05:59.922479 (Thread-1): Acquiring new materialize connection "model.mz_get_started.market_orders_raw".
2021-10-20 08:05:59.922635 (Thread-1): Compiling model.mz_get_started.market_orders_raw
2021-10-20 08:05:59.925490 (Thread-1): Writing injected SQL for node "model.mz_get_started.market_orders_raw"
2021-10-20 08:05:59.925937 (Thread-1): finished collecting timing info
2021-10-20 08:05:59.932530 (Thread-1): Using materialize connection "model.mz_get_started.market_orders_raw".
2021-10-20 08:05:59.932795 (Thread-1): On model.mz_get_started.market_orders_raw: /* {"app": "dbt", "dbt_version": "0.21.0", "profile_name": "default", "target_name": "dev", "node_id": "model.mz_get_started.market_orders_raw"} */
drop source if exists 
      materialize.public.market_orders_raw
   cascade
2021-10-20 08:05:59.932964 (Thread-1): Opening a new connection, currently in state closed
2021-10-20 08:05:59.935672 (Thread-1): SQL status: DROP SOURCE in 0.00 seconds
2021-10-20 08:05:59.939827 (Thread-1): Writing runtime SQL for node "model.mz_get_started.market_orders_raw"
2021-10-20 08:05:59.940259 (Thread-1): Using materialize connection "model.mz_get_started.market_orders_raw".
2021-10-20 08:05:59.940366 (Thread-1): On model.mz_get_started.market_orders_raw: /* {"app": "dbt", "dbt_version": "0.21.0", "profile_name": "default", "target_name": "dev", "node_id": "model.mz_get_started.market_orders_raw"} */

CREATE SOURCE 
    materialize.public.market_orders_raw

FROM PUBNUB
SUBSCRIBE KEY 'sub-c-4377ab04-f100-11e3-bffd-02ee2ddab7fe'
CHANNEL 'pubnub-market-orders'
2021-10-20 08:05:59.942139 (Thread-1): SQL status: CREATE SOURCE in 0.00 seconds
2021-10-20 08:05:59.946576 (Thread-1): finished collecting timing info
2021-10-20 08:05:59.946718 (Thread-1): On model.mz_get_started.market_orders_raw: Close
2021-10-20 08:05:59.946956 (Thread-1): Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '3fcfcc33-a35d-4951-a6dc-2d03312e8622', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107eb3e50>]}
2021-10-20 08:05:59.947173 (Thread-1): 10:05:59 | 1 of 3 OK created source model public.market_orders_raw.............. [CREATE SOURCE in 0.02s]
2021-10-20 08:05:59.947288 (Thread-1): Finished running node model.mz_get_started.market_orders_raw
2021-10-20 08:05:59.947602 (Thread-1): Began running node model.mz_get_started.market_orders
2021-10-20 08:05:59.947783 (Thread-1): 10:05:59 | 2 of 3 START view model public.market_orders......................... [RUN]
2021-10-20 08:05:59.947996 (Thread-1): Acquiring new materialize connection "model.mz_get_started.market_orders".
2021-10-20 08:05:59.948099 (Thread-1): Compiling model.mz_get_started.market_orders
2021-10-20 08:05:59.949629 (Thread-1): Writing injected SQL for node "model.mz_get_started.market_orders"
2021-10-20 08:05:59.949929 (Thread-1): finished collecting timing info
2021-10-20 08:05:59.955774 (Thread-1): Using materialize connection "model.mz_get_started.market_orders".
2021-10-20 08:05:59.955879 (Thread-1): On model.mz_get_started.market_orders: /* {"app": "dbt", "dbt_version": "0.21.0", "profile_name": "default", "target_name": "dev", "node_id": "model.mz_get_started.market_orders"} */
drop view if exists "materialize"."public"."market_orders" cascade
2021-10-20 08:05:59.955966 (Thread-1): Opening a new connection, currently in state closed
2021-10-20 08:05:59.958340 (Thread-1): SQL status: DROP VIEW in 0.00 seconds
2021-10-20 08:05:59.960279 (Thread-1): Writing runtime SQL for node "model.mz_get_started.market_orders"
2021-10-20 08:05:59.960550 (Thread-1): Using materialize connection "model.mz_get_started.market_orders".
2021-10-20 08:05:59.960629 (Thread-1): On model.mz_get_started.market_orders: /* {"app": "dbt", "dbt_version": "0.21.0", "profile_name": "default", "target_name": "dev", "node_id": "model.mz_get_started.market_orders"} */
create view "materialize"."public"."market_orders"
  as (
    
SELECT
    ((text::jsonb)->>'bid_price')::float AS bid_price,
    (text::jsonb)->>'order_quantity' AS order_quantity,
    (text::jsonb)->>'symbol' AS symbol,
    (text::jsonb)->>'trade_type' AS trade_type,
    to_timestamp(((text::jsonb)->'timestamp')::bigint) AS ts

FROM "materialize"."public"."market_orders_raw"
  );
2021-10-20 08:05:59.962093 (Thread-1): SQL status: CREATE VIEW in 0.00 seconds
2021-10-20 08:05:59.962822 (Thread-1): finished collecting timing info
2021-10-20 08:05:59.962935 (Thread-1): On model.mz_get_started.market_orders: Close
2021-10-20 08:05:59.963136 (Thread-1): Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '3fcfcc33-a35d-4951-a6dc-2d03312e8622', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107bcfbb0>]}
2021-10-20 08:05:59.963318 (Thread-1): 10:05:59 | 2 of 3 OK created view model public.market_orders.................... [CREATE VIEW in 0.02s]
2021-10-20 08:05:59.963415 (Thread-1): Finished running node model.mz_get_started.market_orders
2021-10-20 08:05:59.963748 (Thread-1): Began running node model.mz_get_started.avg_bid
2021-10-20 08:05:59.963919 (Thread-1): 10:05:59 | 3 of 3 START materializedview model public.avg_bid................... [RUN]
2021-10-20 08:05:59.964113 (Thread-1): Acquiring new materialize connection "model.mz_get_started.avg_bid".
2021-10-20 08:05:59.964235 (Thread-1): Compiling model.mz_get_started.avg_bid
2021-10-20 08:05:59.966312 (Thread-1): Writing injected SQL for node "model.mz_get_started.avg_bid"
2021-10-20 08:05:59.966685 (Thread-1): finished collecting timing info
2021-10-20 08:05:59.971040 (Thread-1): Using materialize connection "model.mz_get_started.avg_bid".
2021-10-20 08:05:59.971127 (Thread-1): On model.mz_get_started.avg_bid: /* {"app": "dbt", "dbt_version": "0.21.0", "profile_name": "default", "target_name": "dev", "node_id": "model.mz_get_started.avg_bid"} */
drop view if exists "materialize"."public"."avg_bid" cascade
2021-10-20 08:05:59.971205 (Thread-1): Opening a new connection, currently in state closed
2021-10-20 08:05:59.972974 (Thread-1): SQL status: DROP VIEW in 0.00 seconds
2021-10-20 08:05:59.974080 (Thread-1): Writing runtime SQL for node "model.mz_get_started.avg_bid"
2021-10-20 08:05:59.974500 (Thread-1): Using materialize connection "model.mz_get_started.avg_bid".
2021-10-20 08:05:59.974572 (Thread-1): On model.mz_get_started.avg_bid: /* {"app": "dbt", "dbt_version": "0.21.0", "profile_name": "default", "target_name": "dev", "node_id": "model.mz_get_started.avg_bid"} */
create materialized view "materialize"."public"."avg_bid"
  as (
    
SELECT symbol,
       AVG(bid_price) AS avg
FROM "materialize"."public"."market_orders"
GROUP BY symbol
  );
2021-10-20 08:05:59.976635 (Thread-1): SQL status: CREATE VIEW in 0.00 seconds
2021-10-20 08:05:59.977340 (Thread-1): finished collecting timing info
2021-10-20 08:05:59.977456 (Thread-1): On model.mz_get_started.avg_bid: Close
2021-10-20 08:05:59.977655 (Thread-1): Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '3fcfcc33-a35d-4951-a6dc-2d03312e8622', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107f3ce80>]}
2021-10-20 08:05:59.977825 (Thread-1): 10:05:59 | 3 of 3 OK created materializedview model public.avg_bid.............. [CREATE VIEW in 0.01s]
2021-10-20 08:05:59.977911 (Thread-1): Finished running node model.mz_get_started.avg_bid
2021-10-20 08:05:59.978350 (MainThread): Acquiring new materialize connection "master".
2021-10-20 08:05:59.978436 (MainThread): Using materialize connection "master".
2021-10-20 08:05:59.978497 (MainThread): On master: BEGIN
2021-10-20 08:05:59.978561 (MainThread): Opening a new connection, currently in state closed
2021-10-20 08:05:59.980042 (MainThread): SQL status: BEGIN in 0.00 seconds
2021-10-20 08:05:59.980132 (MainThread): On %s: COMMIT
2021-10-20 08:05:59.980198 (MainThread): Using materialize connection "master".
2021-10-20 08:05:59.980257 (MainThread): On master: COMMIT
2021-10-20 08:05:59.980533 (MainThread): SQL status: COMMIT in 0.00 seconds
2021-10-20 08:05:59.980599 (MainThread): On master: Close
2021-10-20 08:05:59.980748 (MainThread): 10:05:59 | 
2021-10-20 08:05:59.980827 (MainThread): 10:05:59 | Finished running 1 source model, 1 view model, 1 materializedview model in 0.20s.
2021-10-20 08:05:59.980894 (MainThread): Connection 'master' was properly closed.
2021-10-20 08:05:59.980950 (MainThread): Connection 'model.mz_get_started.avg_bid' was properly closed.
2021-10-20 08:05:59.983687 (MainThread): 
2021-10-20 08:05:59.983910 (MainThread): Completed successfully
2021-10-20 08:05:59.984012 (MainThread): 
Done. PASS=3 WARN=0 ERROR=0 SKIP=0 TOTAL=3
```

**Comment by dataders** [comment]
@morsapaes jumping in here without context (and have yet to use materialize), so my apologies if I'm way off base here. but here's my guess after one minute of reviewing.

all dbt's `source` macro does is basically look for a [YAML-defined source](https://docs.getdbt.com/docs/building-a-dbt-project/using-sources#declaring-a-source) and then returns the fully-qualified name given the database and schema.

When you try to reference the `public`'s `market_orders_raw` "table", you dbt is looking for YAML file with this in the contents:

```yaml
version: 2

sources:
  - name: public
    tables:
      - name: market_orders_raw
```

But I don't see anything like this. I bet if you were to add a file like this it would work.


The other recommendation I'm thinking is to think through a model in which Materialize `SOURCE`s get created before `dbt run` is called. This could be done with a pre-hook macro or even would work the same was as with [dbt-external-tables](https://github.com/dbt-labs/dbt-external-tables).

Again, I'm just getting started with Materialize, but I'm very interested to learn more in the coming weeks!

**Comment by morsapaes** [comment]
Ah, there is a source definition in the `schema.yml` file under the `/models` directory: https://github.com/morsapaes/mz-playground/blob/main/dbt/models/schema.yml. My hunch is that this may just not be wired in the adapter at all, but I haven't looked at the code yet!

Thank you for looking into it and your suggestions, I'll try to have a closer look into it in the next few days. In the meantime, if you have any questions as you explore Materialize, fire away!

**Comment by morsapaes** [comment]
The great thing about working with people who know dbt inside out is that you get 101 explainers on what you might be doing wrong. @amychen1776 pointed out that:

> Because it's in a model file, you actually have to use `ref()`. It’s more like a seed than a source in dbt land. 

Since we prompt users to define the sources and sinks as models (or, at least that's my understanding of the adapter), these should be referenced using `ref()`; which explains (and invalidates!) the issue I ran into using `source()`.

<hr>

Amy had a question about the source materialization that I don't have enough context to provide a good answer for:

> One question I had about the source dbt materialization was why the decision to have the user write the DDL rather than including it in the wrapper like our other materializations?

@JLDLaughlin / @jwills (👋 ), would either of you be able to help here?

**Comment by jwills** [comment]
Hey @morsapaes, thanks for the ping! @dataders and I were chatting about this problem in the dbt Slack the other day.

The general problem here is that in a non-streaming DW, there is going to be a loader process that is responsible for defining the raw tables that dbt is going to do transformations on, and so that loader process (Fivetran, Meltano, Airbyte, etc.) is going to own the DDL for those raw tables, and these are the tables that you work with in dbt using the `source` macro/YAML declarations. In a streaming database like Materialize, it's not clear to me that there is an equivalent of the upstream loader process-- like, there is clearly a process that is publishing stuff to the stream, but should that process _also_ own the DDL for the `SOURCE`s that Materialize is going to consume? In my experience, the processes that do the writes to Kafka/Kinesis don't know anything about how what they write is consumed downstream, and so I wasn't sure where else they should go, because a Materialize `SOURCE` isn't purely declarative-- it also describes how to consume the stream and (potentially) parse some of the data from it into a tabular form.

My question for this crew is: if the DDL for a Materialize `SOURCE` should not live in dbt (and thus be treated as a `ref`, not a `source`)-- where should it live?

**Comment by amychen1776** [comment]
Happy for anyone to disagree with me but I think there's a simple solution to this. If we have the DDL to create a source live in dbt, this allows a full dependency of the objects that dbt can transform. That's very beneficial to dbt developers. Just like incremental models don't make sense in a Materialize dbt project, the decision can be made that dbt sources aren't supported because they're not necessary/relevant.

Since Marta clarified that no one is doing transformations during the creation of a source and that they can't be queried without a view on top, this decision seems like the right move.

**Comment by jtcohen6** [comment]
Jumping in very quickly to say: This sounds similar to the opinionated attitude taken by [`dbt-external-tables`](https://github.com/dbt-labs/dbt-external-tables), which acknowledges that dbt can have a role in creating some sources, but this should remain a step separate from running models. Sources are naive "pointers"; models are business-logic-bearing transformations. As such, "external" sources are defined in yaml and created as a separate step (via `run-operation`) that "preps" the `dbt run`.

There are some limitations with this approach (https://github.com/dbt-labs/dbt-external-tables/issues/109), but I like the conceptual separation between sources (DDL only) and models (DDL + transformation SQL).

**Comment by jwills** [comment]
Ah, what @jtcohen6 is suggesting here seems like The Way, _especially_ if that third option in https://github.com/dbt-labs/dbt-external-tables/issues/109 makes its way into `dbt-core`-- I can imagine all sorts of fun I could have with that!

**Comment by morsapaes** [comment]
> In a streaming database like Materialize, it's not clear to me that there is an equivalent of the upstream loader process-- like, there is clearly a process that is publishing stuff to the stream, but should that process also own the DDL for the SOURCEs that Materialize is going to consume?

So that everyone is on the same page, a source in Materialize is _sort of_ analogous to a foreign table: it points to data that lives outside of the database, but that can be queried like any other object once you pin down its external location and other config. I'm very much on board with the approach of using `dbt-external-tables` to define sources and sinks!

**Comment by morsapaes** [comment]
Looping @ahelium on our side, who'll start ramping up on the `dbt-materialize` adapter.

**Comment by morsapaes** [comment]
Thanks everyone for contributing to the discussion around this! Since it's now clear why `source()` can't be used with the current implementation, I'll close this issue and open a new one to track the refactor of the adapter.
