### ISSUE TITLE
persist: kafka sources: hang in timely, complete loss of interactivity after dropping and recreating source

### ISSUE THREAD

**Issue by philip-stoev** [MaterializeInc/materialize#8910]
### What version of Materialize are you using?

From the shell:

```
 v0.9.12-dev (5e3f7200d)
```

### What was the issue?

If a Kafka source is dropped and recreated while Mz is running with persistent-kafka-upsert-source, a complete loss of interactivity occurs whereby other unrelated queries hang.

It may be related to the fact that testdrive is dropping the topic inbetween the two invocations. No restart of Mz is required to reproduce.  Not reproducible without persistent kafka sources enabled.

### Is the issue reproducible? If so, please provide reproduction instructions.

Run this .td test 2 or more times:

```
$ set keyschema={
    "type": "record",
    "name": "Key",
    "fields": [
        {"name": "f1", "type": "long"}
    ]
  }

$ set schema={
        "type" : "record",
        "name" : "test",
        "fields" : [
            {"name":"f1", "type":"long"}
        ]
    }

$ kafka-create-topic topic=s1

$ kafka-ingest format=avro topic=s1 key-format=avro key-schema=${keyschema} schema=${schema} publish=true
{"f1": 1} {"f1": 1}

> CREATE MATERIALIZED SOURCE s1
  FROM KAFKA BROKER '${testdrive.kafka-addr}' TOPIC 'testdrive-s1-${testdrive.seed}'
  FORMAT AVRO USING CONFLUENT SCHEMA REGISTRY '${testdrive.schema-registry-url}'
  ENVELOPE UPSERT

> SELECT COUNT(*) = 1 FROM s1;
true
```
The second invocation will fail on the SELECT:
```
> SELECT COUNT(*) = 1 FROM s1;
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 112ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 49s 74s 78s...
```

### Please attach any applicable log files.
Absolutely nothing in the logs under the default logging level. gdb reports one timely thread blocked in librdkafka:

```
Thread 15 (Thread 0x7f2c68a7f700 (LWP 1843270)):
#0  __pthread_clockjoin_ex (threadid=threadid@entry=139828576380672, thread_return=thread_return@entry=0x7f2c68a77d60, clockid=clockid@entry=0, abstime=abstime@entry=0x0, block=block@entry=true) at pthread_join_common.c:145
#1  0x00007f2c707e0b1e in thrd_join (thr=thr@entry=139828576380672, res=res@entry=0x7f2c68a77dac) at thrd_join.c:25
#2  0x000055b00514a884 in rd_kafka_destroy_app (rk=0x7f2c66c95000, flags=<optimized out>) at /home/pstoev/.cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/a0d40d0/rdkafka-sys/librdkafka/src/rdkafka.c:1115
#3  0x000055b004bce780 in <rdkafka::util::NativePtr<T> as core::ops::drop::Drop>::drop () at /home/pstoev/.cargo/git/checkouts/rust-rdkafka-34d944143d921bb0/a0d40d0/src/util.rs:265
#4  core::ptr::drop_in_place<rdkafka::util::NativePtr<rdkafka_sys::bindings::rd_kafka_s>> () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ptr/mod.rs:188
#5  core::ptr::drop_in_place<rdkafka::client::NativeClient> () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ptr/mod.rs:188
#6  core::ptr::drop_in_place<rdkafka::client::Client<dataflow::source::kafka::GlueConsumerContext>> () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ptr/mod.rs:188
#7  core::ptr::drop_in_place<rdkafka::consumer::base_consumer::BaseConsumer<dataflow::source::kafka::GlueConsumerContext>> () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ptr/mod.rs:188
#8  alloc::sync::Arc<T>::drop_slow () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/alloc/src/sync.rs:1065
#9  0x000055b004bb895e in <alloc::sync::Arc<T> as core::ops::drop::Drop>::drop () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/alloc/src/sync.rs:1625
#10 core::ptr::drop_in_place<alloc::sync::Arc<rdkafka::consumer::base_consumer::BaseConsumer<dataflow::source::kafka::GlueConsumerContext>>> () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ptr/mod.rs:188
#11 core::ptr::drop_in_place<rdkafka::consumer::base_consumer::PartitionQueue<dataflow::source::kafka::GlueConsumerContext>> () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ptr/mod.rs:188
#12 core::ptr::drop_in_place<dataflow::source::kafka::PartitionConsumer> () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ptr/mod.rs:188
#13 0x000055b004bee348 in core::ptr::drop_in_place<[dataflow::source::kafka::PartitionConsumer]> () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ptr/mod.rs:188
#14 <alloc::collections::vec_deque::VecDeque<T,A> as core::ops::drop::Drop>::drop () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/alloc/src/collections/vec_deque/mod.rs:151
#15 0x000055b004410c4a in core::ptr::drop_in_place<alloc::collections::vec_deque::VecDeque<dataflow::source::kafka::PartitionConsumer>> () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ptr/mod.rs:188
#16 core::ptr::drop_in_place<dataflow::source::kafka::KafkaSourceReader> () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ptr/mod.rs:188
#17 0x000055b0043e6fc6 in core::ptr::drop_in_place<core::option::Option<dataflow::source::kafka::KafkaSourceReader>> () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ptr/mod.rs:188
#18 core::ptr::drop_in_place<dataflow::source::create_source<timely::dataflow::scopes::child::Child<timely::dataflow::scopes::child::Child<timely::worker::Worker<timely_communication::allocator::generic::Generic>,u64>,u64>,dataflow::source::kafka::KafkaSourceReader>::{{closure}}::{{closure}}> () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ptr/mod.rs:188
#19 0x000055b00440893b in _ZN4core3ptr1194drop_in_place$LT$dataflow..source..util..source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$core..result..Result$LT$dataflow..source..SourceOutput$LT$alloc..vec..Vec$LT$u8$GT$$C$repr..MessagePayload$GT$$C$alloc..string..String$GT$$C$$LP$$LP$dataflow..source..timestamp..SourceTimestamp$C$dataflow..source..timestamp..AssignedTimestamp$RP$$C$u64$C$isize$RP$$C$dataflow..source..create_source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$dataflow..source..kafka..KafkaSourceReader$GT$..$u7b$$u7b$closure$u7d$$u7d$$C$dataflow..source..create_source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$dataflow..source..kafka..KafkaSourceReader$GT$..$u7b$$u7b$closure$u7d$$u7d$..$u7b$$u7b$closure$u7d$$u7d$$GT$..$u7b$$u7b$closure$u7d$$u7d$..$u7b$$u7b$closure$u7d$$u7d$$GT$17hc5c6f5e73a13076cE () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ptr/mod.rs:188
#20 _ZN4core3ptr2670drop_in_place$LT$timely..dataflow..operators..generic..builder_rc..OperatorBuilder$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$GT$..build$LT$dataflow..source..util..source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$core..result..Result$LT$dataflow..source..SourceOutput$LT$alloc..vec..Vec$LT$u8$GT$$C$repr..MessagePayload$GT$$C$alloc..string..String$GT$$C$$LP$$LP$dataflow..source..timestamp..SourceTimestamp$C$dataflow..source..timestamp..AssignedTimestamp$RP$$C$u64$C$isize$RP$$C$dataflow..source..create_source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$dataflow..source..kafka..KafkaSourceReader$GT$..$u7b$$u7b$closure$u7d$$u7d$$C$dataflow..source..create_source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$dataflow..source..kafka..KafkaSourceReader$GT$..$u7b$$u7b$closure$u7d$$u7d$..$u7b$$u7b$closure$u7d$$u7d$$GT$..$u7b$$u7b$closure$u7d$$u7d$$C$dataflow..source..util..source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$core..result..Result$LT$dataflow..source..SourceOutput$LT$alloc..vec..Vec$LT$u8$GT$$C$repr..MessagePayload$GT$$C$alloc..string..String$GT$$C$$LP$$LP$dataflow..source..timestamp..SourceTimestamp$C$dataflow..source..timestamp..AssignedTimestamp$RP$$C$u64$C$isize$RP$$C$dataflow..source..create_source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$dataflow..source..kafka..KafkaSourceReader$GT$..$u7b$$u7b$closure$u7d$$u7d$$C$dataflow..source..create_source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$dataflow..source..kafka..KafkaSourceReader$GT$..$u7b$$u7b$closure$u7d$$u7d$..$u7b$$u7b$closure$u7d$$u7d$$GT$..$u7b$$u7b$closure$u7d$$u7d$..$u7b$$u7b$closure$u7d$$u7d$$GT$..$u7b$$u7b$closure$u7d$$u7d$..$u7b$$u7b$closure$u7d$$u7d$$GT$17h4d9927a5987c0840E () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ptr/mod.rs:188
#21 _ZN4core3ptr5604drop_in_place$LT$timely..dataflow..operators..generic..builder_rc..OperatorBuilder$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$GT$..build_reschedule$LT$timely..dataflow..operators..generic..builder_rc..OperatorBuilder$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$GT$..build$LT$dataflow..source..util..source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$core..result..Result$LT$dataflow..source..SourceOutput$LT$alloc..vec..Vec$LT$u8$GT$$C$repr..MessagePayload$GT$$C$alloc..string..String$GT$$C$$LP$$LP$dataflow..source..timestamp..SourceTimestamp$C$dataflow..source..timestamp..AssignedTimestamp$RP$$C$u64$C$isize$RP$$C$dataflow..source..create_source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$dataflow..source..kafka..KafkaSourceReader$GT$..$u7b$$u7b$closure$u7d$$u7d$$C$dataflow..source..create_source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$dataflow..source..kafka..KafkaSourceReader$GT$..$u7b$$u7b$closure$u7d$$u7d$..$u7b$$u7b$closure$u7d$$u7d$$GT$..$u7b$$u7b$closure$u7d$$u7d$$C$dataflow..source..util..source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$core..result..Result$LT$dataflow..source..SourceOutput$LT$alloc..vec..Vec$LT$u8$GT$$C$repr..MessagePayload$GT$$C$alloc..string..String$GT$$C$$LP$$LP$dataflow..source..timestamp..SourceTimestamp$C$dataflow..source..timestamp..AssignedTimestamp$RP$$C$u64$C$isize$RP$$C$dataflow..source..create_source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$dataflow..source..kafka..KafkaSourceReader$GT$..$u7b$$u7b$closure$u7d$$u7d$$C$dataflow..source..create_source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$dataflow..source..kafka..KafkaSourceReader$GT$..$u7b$$u7b$closure$u7d$$u7d$..$u7b$$u7b$closure$u7d$$u7d$$GT$..$u7b$$u7b$closure$u7d$$u7d$..$u7b$$u7b$closure$u7d$$u7d$$GT$..$u7b$$u7b$closure$u7d$$u7d$$C$timely..dataflow..operators..generic..builder_rc..OperatorBuilder$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$GT$..build$LT$dataflow..source..util..source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$core..result..Result$LT$dataflow..source..SourceOutput$LT$alloc..vec..Vec$LT$u8$GT$$C$repr..MessagePayload$GT$$C$alloc..string..String$GT$$C$$LP$$LP$dataflow..source..timestamp..SourceTimestamp$C$dataflow..source..timestamp..AssignedTimestamp$RP$$C$u64$C$isize$RP$$C$dataflow..source..create_source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$dataflow..source..kafka..KafkaSourceReader$GT$..$u7b$$u7b$closure$u7d$$u7d$$C$dataflow..source..create_source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$dataflow..source..kafka..KafkaSourceReader$GT$..$u7b$$u7b$closure$u7d$$u7d$..$u7b$$u7b$closure$u7d$$u7d$$GT$..$u7b$$u7b$closure$u7d$$u7d$$C$dataflow..source..util..source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$core..result..Result$LT$dataflow..source..SourceOutput$LT$alloc..vec..Vec$LT$u8$GT$$C$repr..MessagePayload$GT$$C$alloc..string..String$GT$$C$$LP$$LP$dataflow..source..timestamp..SourceTimestamp$C$dataflow..source..timestamp..AssignedTimestamp$RP$$C$u64$C$isize$RP$$C$dataflow..source..create_source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$dataflow..source..kafka..KafkaSourceReader$GT$..$u7b$$u7b$closure$u7d$$u7d$$C$dataflow..source..create_source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$dataflow..source..kafka..KafkaSourceReader$GT$..$u7b$$u7b$closure$u7d$$u7d$..$u7b$$u7b$closure$u7d$$u7d$$GT$..$u7b$$u7b$closure$u7d$$u7d$..$u7b$$u7b$closure$u7d$$u7d$$GT$..$u7b$$u7b$closure$u7d$$u7d$..$u7b$$u7b$closure$u7d$$u7d$$GT$..$u7b$$u7b$closure$u7d$$u7d$$GT$17h8831dc720456642eE () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ptr/mod.rs:188
#22 0x000055b004409bc0 in _ZN4core3ptr5681drop_in_place$LT$timely..dataflow..operators..generic..builder_raw..OperatorCore$LT$u64$C$timely..dataflow..operators..generic..builder_rc..OperatorBuilder$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$GT$..build_reschedule$LT$timely..dataflow..operators..generic..builder_rc..OperatorBuilder$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$GT$..build$LT$dataflow..source..util..source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$core..result..Result$LT$dataflow..source..SourceOutput$LT$alloc..vec..Vec$LT$u8$GT$$C$repr..MessagePayload$GT$$C$alloc..string..String$GT$$C$$LP$$LP$dataflow..source..timestamp..SourceTimestamp$C$dataflow..source..timestamp..AssignedTimestamp$RP$$C$u64$C$isize$RP$$C$dataflow..source..create_source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$dataflow..source..kafka..KafkaSourceReader$GT$..$u7b$$u7b$closure$u7d$$u7d$$C$dataflow..source..create_source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$dataflow..source..kafka..KafkaSourceReader$GT$..$u7b$$u7b$closure$u7d$$u7d$..$u7b$$u7b$closure$u7d$$u7d$$GT$..$u7b$$u7b$closure$u7d$$u7d$$C$dataflow..source..util..source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$core..result..Result$LT$dataflow..source..SourceOutput$LT$alloc..vec..Vec$LT$u8$GT$$C$repr..MessagePayload$GT$$C$alloc..string..String$GT$$C$$LP$$LP$dataflow..source..timestamp..SourceTimestamp$C$dataflow..source..timestamp..AssignedTimestamp$RP$$C$u64$C$isize$RP$$C$dataflow..source..create_source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$dataflow..source..kafka..KafkaSourceReader$GT$..$u7b$$u7b$closure$u7d$$u7d$$C$dataflow..source..create_source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$dataflow..source..kafka..KafkaSourceReader$GT$..$u7b$$u7b$closure$u7d$$u7d$..$u7b$$u7b$closure$u7d$$u7d$$GT$..$u7b$$u7b$closure$u7d$$u7d$..$u7b$$u7b$closure$u7d$$u7d$$GT$..$u7b$$u7b$closure$u7d$$u7d$$C$timely..dataflow..operators..generic..builder_rc..OperatorBuilder$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$GT$..build$LT$dataflow..source..util..source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$core..result..Result$LT$dataflow..source..SourceOutput$LT$alloc..vec..Vec$LT$u8$GT$$C$repr..MessagePayload$GT$$C$alloc..string..String$GT$$C$$LP$$LP$dataflow..source..timestamp..SourceTimestamp$C$dataflow..source..timestamp..AssignedTimestamp$RP$$C$u64$C$isize$RP$$C$dataflow..source..create_source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$dataflow..source..kafka..KafkaSourceReader$GT$..$u7b$$u7b$closure$u7d$$u7d$$C$dataflow..source..create_source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$dataflow..source..kafka..KafkaSourceReader$GT$..$u7b$$u7b$closure$u7d$$u7d$..$u7b$$u7b$closure$u7d$$u7d$$GT$..$u7b$$u7b$closure$u7d$$u7d$$C$dataflow..source..util..source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$core..result..Result$LT$dataflow..source..SourceOutput$LT$alloc..vec..Vec$LT$u8$GT$$C$repr..MessagePayload$GT$$C$alloc..string..String$GT$$C$$LP$$LP$dataflow..source..timestamp..SourceTimestamp$C$dataflow..source..timestamp..AssignedTimestamp$RP$$C$u64$C$isize$RP$$C$dataflow..source..create_source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$dataflow..source..kafka..KafkaSourceReader$GT$..$u7b$$u7b$closure$u7d$$u7d$$C$dataflow..source..create_source$LT$timely..dataflow..scopes..child..Child$LT$timely..dataflow..scopes..child..Child$LT$timely..worker..Worker$LT$timely_communication..allocator..generic..Generic$GT$$C$u64$GT$$C$u64$GT$$C$dataflow..source..kafka..KafkaSourceReader$GT$..$u7b$$u7b$closure$u7d$$u7d$..$u7b$$u7b$closure$u7d$$u7d$$GT$..$u7b$$u7b$closure$u7d$$u7d$..$u7b$$u7b$closure$u7d$$u7d$$GT$..$u7b$$u7b$closure$u7d$$u7d$..$u7b$$u7b$closure$u7d$$u7d$$GT$..$u7b$$u7b$closure$u7d$$u7d$$GT$$GT$17ha96bd1c39065dd59E () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ptr/mod.rs:188
#23 0x000055b00450be92 in core::ptr::drop_in_place<alloc::boxed::Box<dyn timely::progress::operate::Operate<u64>>> () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ptr/mod.rs:188
#24 core::ptr::drop_in_place<core::option::Option<alloc::boxed::Box<dyn timely::progress::operate::Operate<u64>>>> () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ptr/mod.rs:188
#25 timely::progress::subgraph::PerOperatorState<T>::shut_down () at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/timely/src/progress/subgraph.rs:713
#26 timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child () at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/timely/src/progress/subgraph.rs:358
#27 <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule () at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/timely/src/progress/subgraph.rs:310
#28 0x000055b0045629f3 in timely::progress::subgraph::PerOperatorState<T>::schedule () at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/timely/src/progress/subgraph.rs:684
#29 0x000055b00450c974 in timely::progress::subgraph::Subgraph<TOuter,TInner>::activate_child () at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/timely/src/progress/subgraph.rs:344
#30 <timely::progress::subgraph::Subgraph<TOuter,TInner> as timely::scheduling::Schedule>::schedule () at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/timely/src/progress/subgraph.rs:310
#31 0x000055b005928289 in timely::worker::Wrapper::step::{{closure}} () at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/timely/src/worker.rs:749
#32 core::option::Option<T>::map () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/option.rs:836
#33 timely::worker::Wrapper::step () at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/timely/src/worker.rs:749
#34 0x000055b003f2f9e0 in timely::worker::Worker<A>::step_or_park () at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/timely/src/worker.rs:396
#35 0x000055b003f5ed85 in dataflow::server::Worker<A>::run () at src/dataflow/src/server.rs:663
#36 0x000055b004b851cd in dataflow::server::serve::{{closure}} () at src/dataflow/src/server.rs:343
#37 timely::execute::execute::{{closure}} () at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/timely/src/execute.rs:285
#38 timely_communication::initialize::initialize_from::{{closure}} () at /home/pstoev/.cargo/git/checkouts/timely-dataflow-4c0cc365061cd263/de28bb4/communication/src/initialize.rs:291
#39 std::sys_common::backtrace::__rust_begin_short_backtrace () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:125
#40 0x000055b004190e57 in std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/thread/mod.rs:481
#41 <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panic/unwind_safe.rs:271
#42 std::panicking::try::do_call () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:403
#43 std::panicking::try () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:367
#44 std::panic::catch_unwind () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panic.rs:129
#45 std::thread::Builder::spawn_unchecked::{{closure}} () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/thread/mod.rs:480
#46 core::ops::function::FnOnce::call_once{{vtable-shim}} () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:227
#47 0x000055b005ec6303 in <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/alloc/src/boxed.rs:1636
#48 <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once () at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/alloc/src/boxed.rs:1636
#49 std::sys::unix::thread::Thread::new::thread_start () at library/std/src/sys/unix/thread.rs:106
#50 0x00007f2c707d3609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#51 0x00007f2c7056e293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by aljoscha** [comment]
@philip-stoev Is this one still relevant? The architecture underneath all this is completely changed by now.

**Comment by philip-stoev** [comment]
I do not think so. This is from a previous life . Closing.

**Comment by aljoscha** [comment]
many thanks!
