### ISSUE TITLE
crash in delta join rendering

### ISSUE THREAD

**Issue by umanwizard** [MaterializeInc/materialize#9921]
### What version of Materialize are you using?

origin/main

### How did you install Materialize?

Built from source

### What was the issue?

running the following code in SLT causes a crash:

```
mode cockroach

statement ok
CREATE TABLE t1 (f1 INTEGER, f2 INTEGER);

statement ok
CREATE TABLE t2  (f1 INTEGER, f2 INTEGER);

statement ok
SELECT 1 FROM t1  RIGHT  JOIN (  SELECT 1 FROM t2  )  ON  NULL  WHERE f2  IN (  9  ,  0  )  OR  0  <  ALL (  SELECT agg1  NULL FROM (  SELECT MAX(  3  ) agg1  FROM (  SELECT  FROM t1  )  GROUP  BY  TRUE  )  )  GROUP  BY  TRUE;
```

### Relevant log output

```source
==> btv.slt                                                                       
thread 'timely:work-0' panicked at 'Arrangement alarmingly absent!: 1, []', src/dataflow/src/render/join/delta_join.rs:75:37
stack backtrace:                                                                  
   0: rust_begin_unwind                                                                                                                                              
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt                                                                                                                                     
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14                                                                 
   2: dataflow::render::join::delta_join::<impl dataflow::render::context::Context<G,repr::row::Row,u64>>::render_delta_join::{{closure}}::{{closure}}::{{closure}}
             at ./src/dataflow/src/render/join/delta_join.rs:75:37                                                                                                   
   3: core::option::Option<T>::unwrap_or_else                                                                                                                        
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/option.rs:787:21
   4: dataflow::render::join::delta_join::<impl dataflow::render::context::Context<G,repr::row::Row,u64>>::render_delta_join::{{closure}}::{{closure}}
             at ./src/dataflow/src/render/join/delta_join.rs:72:35
   5: alloc::collections::btree::map::entry::Entry<K,V>::or_insert_with           
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/alloc/src/collections/btree/map/entry.rs:151:43
   6: dataflow::render::join::delta_join::<impl dataflow::render::context::Context<G,repr::row::Row,u64>>::render_delta_join::{{closure}}
             at ./src/dataflow/src/render/join/delta_join.rs:69:21

(snip)
```

**Comment by umanwizard** [comment]
According to @philip-stoev [here](https://github.com/MaterializeInc/materialize/pull/9806#pullrequestreview-845591683),

> the panic reported appears to affect only queries with scalar subqueries with ANY or ALL

**Comment by umanwizard** [comment]
Discussion in Slack: https://materializeinc.slack.com/archives/C01BE3RN82F/p1641501511004300
